### ISSUE TITLE
Improve support for binder built as a module

### ISSUE THREAD

**Issue by xanmod** [waydroid/waydroid#1003]
Kernels like xanmod have the android binder driver built in as module [1].
waydroid-container.service starts binder_linux module (kconfig's =m / binder_linux-dkms) but does not create **/dev/binder -> /dev/binderfs/binder**

As a solution, binder_linux should be loaded before waydroid-container.service
ex: `echo binder_linux | sudo tee /etc/modules-load.d/binder.conf`

Another note is the need to have PSI enabled by default.

It would be interesting to add a check if the kernel has CONFIG_PSI_DEFAULT_DISABLED=y and notify the user to add psi=1 kernel parameter in the boot loader, if possible, not require it for waydroid to work.

Issue: https://github.com/xanmod/linux/issues/386#issuecomment-1635173382

[1] https://gitlab.com/xanmod/linux-patches/-/tree/master/linux-6.4.y-xanmod/android_anbox (patches from latest ubuntu kernel git)

**Comment by aleasto** [comment]
Which distro is this about?
Waydroid should already handle all cases, except on Fedora

**Comment by austinrojers** [comment]
> Which distro is this about? Waydroid should already handle all cases, except on Fedora

Arch linux

**Comment by xanmod** [comment]
> Which distro is this about? Waydroid should already handle all cases, except on Fedora

Tested with Debian, Ubuntu, Void and Arch Linux.

This issue is related to module binder_linux (=m), with built-in binder (=y) it works without changes.

Xanmod and Ubuntu kernel default:
```
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDERFS=m
```

**Comment by aleasto** [comment]
Indeed in debian and ubuntu binder as a module is the default. And obviously waydroid works there.

**Comment by xanmod** [comment]
I repeated the test with clean installs of Debian, Ubuntu and Arch + binder_linux-dkms and gbinder worked fine with stock kernel and xanmod.

**Comment by austinrojers** [comment]
I tried Arch stock kernel with `binder_linux-dkms`, but binder dies even with `psi=1`.
How did you get it working?
