### ISSUE TITLE
No 'modprobe'

### ISSUE THREAD

**Issue by user-naa** [waydroid/waydroid#1005]
Hello! I have this problem:

```
root@######:/path/to/directory# waydroid upgrade
[19:22:37] ERROR: [Errno 2] No such file or directory: 'modprobe'
[19:22:37] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
root@######:/path/to/directory# waydroid log
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(007622) [19:19:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(007622) [19:19:49] % modprobe -q ashmem_linux
(007622) [19:19:49] ERROR: [Errno 2] No such file or directory: 'modprobe'
(007622) [19:19:49] See also: <https://github.com/waydroid>
(007622) [19:19:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 67, in main
    actions.upgrade(args)
  File "/usr/lib/waydroid/tools/actions/upgrader.py", line 51, in upgrade
    helpers.drivers.probeAshmemDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 116, in probeAshmemDriver
    tools.helpers.run.user(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(007626) [19:19:57] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(007626) [19:19:57] *** output passed to waydroid stdout, not to this log ***
(007765) [19:22:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(007765) [19:22:37] % modprobe -q ashmem_linux
(007765) [19:22:37] ERROR: [Errno 2] No such file or directory: 'modprobe'
(007765) [19:22:37] See also: <https://github.com/waydroid>
(007765) [19:22:37] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 67, in main
    actions.upgrade(args)
  File "/usr/lib/waydroid/tools/actions/upgrader.py", line 51, in upgrade
    helpers.drivers.probeAshmemDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 116, in probeAshmemDriver
    tools.helpers.run.user(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(007784) [19:23:23] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(007784) [19:23:23] *** output passed to waydroid stdout, not to this log ***
```

**Comment by cniw** [comment]
> ERROR: [Errno 2] No such file or directory: 'modprobe'

you're missing the `modprobe` command which usually already installed as kernel dependency

what is your distro & the version? check with `cat /etc/os-release` command
what is your kernel? check with `uname -a` command

maybe you need install it manually, check here https://command-not-found.com/modprobe choose depend on your distro

**Comment by Canta** [comment]
Hi there @cniw 
I'm having the same issue using PostmarketOS edge.
Here are all the details: https://gitlab.com/postmarketOS/pmaports/-/issues/1849#note_1492814863

In any case:
  - I install waydroid (v1.4.1 on pmos repos).
  - I start it through Phosh desktop icon.
  - It starts a GUI telling me to pick and image to download (vanilla vs gapps)
  - Choose vanilla, downloaded fine (about 700MB), then downloaded something else (about 150MB), then got the "no modprobe" error.
  - "Continue" button appears in the GUI after that, I click on it, and that's it: never get to run anything again. Logs show the modprobe error every time I try to run waydroid.
  - Modprobe _is_ on the system: I can run modprobe just fine. The logs (it's on the previous link) say waydroid is trying to execute `modprobe -q ashmem_linux`. I can also run that on the host system without issue.


So, I suspect some path related problem, or something regarding the container context. But `no such file or directory: 'modprobe'` looks more like a sympthom of something else to me, and not the real problem.

Thanks.

**Comment by gamecss** [comment]
Experiencing the same issue with pmos edge and waydroid 1.4.1

**Comment by YJJjun** [comment]
try to install the modprobe

apt-get install kmod

**Comment by YJJjun** [comment]
maybe  your  enviroment  PATH  value does not  include   the  /sbin  ?
you  can    run   the  :  "echo   $PATH"  to check the  PATH  value    include  ":/sbin"
if  you check   it  does not  include
you can run   "export  PATH=$PATH:/sbin"  on the  terminal ， then  run your  comman "waydroid upgrade"  on the same terminal  
to  try

**Comment by parona-source** [comment]
This appears to be a case where the environment isn't used by the process that calls modprobe.

For what I can gather the current setup s that waydroid starts id.waydro.Container.service through dbus which then calls modprobe.  Problem is that dbus activated services don't inherit the environment of the activator, for what I can see the only things set in the environment are DBUS_STARTER_ADDRESS and DBUS_STARTER_BUS_TYPE.

Symlinking modprobe to /usr/bin works through an accident as python will search for executables in the path where its own executable is if PATH is unset.

**Comment by mesflit** [comment]
same issue

**Comment by fraschm1998** [comment]
same using gentoo linux with hyprland and openrc

**Comment by user-naa** [comment]
PATH needs to contain /usr/sbin
