### ISSUE TITLE
Create binder devices automaticly

### ISSUE THREAD

**Issue by sigmaSd** [waydroid/waydroid#101]
Currently waydroid doesn't allocate binder devices in kernel with binderfs support (see https://www.kernel.org/doc/html/latest/admin-guide/binderfs.html#allocating-binder-devices)

So users either have to statically allocate with kernel cmdline `binder.devices=binder,hwbinder,vndbinder `
or dynamically with something like https://gist.githubusercontent.com/sigmaSd/b61466a8aad17468e6214dbaa154f7b6/raw/7df50865315caa5e8cab09f553a07547da83507b/waydroid_binder.c

It would be better if waydroid automatically did this.

**Comment by sigmaSd** [comment]
Edit fixed link https://www.kernel.org/doc/html/latest/admin-guide/binderfs.html#allocating-binder-devices

**Comment by erfanoabdi** [comment]
nice, i think it's doable with `fcntl.ioctl`

**Comment by sigmaSd** [comment]
Fixed in https://github.com/waydroid/waydroid/commit/20d3c5e2cf4fd91e35205a1abfae24456c05fc2e
