### ISSUE TITLE
Should we mount /proc with the hidepid=2 option?

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [waydroid/waydroid#1010]
**Is your feature request related to a problem? Please describe.**
Hello everyone! Last year, [a pull request has been introduced and merged](https://github.com/waydroid/waydroid/pull/523) that mounts ```/proc``` with the ```hidepid=2``` option, so an unprivileged process can only see processes running as the same user. However, [soon this PR was reverted because of another security issue with ```/proc```](https://github.com/waydroid/waydroid/commit/0ad842a015c5153880b377bf7fa5572504339df5). Currently, I have found a way to work around this issue by creating a one-shot service inside Android system (through overlay mounting). It retains the benefits of mixed mounts while preserving the ```hidepid=2``` option. I'm attaching the text of the ```.rc``` file I've added to my system. It can be introduced to the ```/system/bin/etc/init``` directory through overlay mounting already implemented in Waydroid.
[hidepid.rc.gz](https://github.com/waydroid/waydroid/files/12131523/hidepid.rc.gz)

**Comment by aleasto** [comment]
You should be able to write `exec -- mount -o remount,hidepid=2 /proc` instead. And it should probably should happen `on early-init`

Please contribute the changes to `waydroid/android_vendor_waydroid` at `rootdir/etc/init.waydroid.rc`

**Comment by ChrysoliteAzalea** [comment]
OK, it works for me. However, in my PR, it's ```on init``` because ```on early-init``` caused some issues for me, but with ```on init```, it seems to work correctly.
