### ISSUE TITLE
Why do kernels need the binder modules when python-gbinder already has the binder drivers?

### ISSUE THREAD

**Issue by austinrojers** [waydroid/waydroid#1012]
I notice that if you install & initialize Waydroid **with a kernel that has binder modules** and check the `/dev/binderfs` directory, you will see:

```
> ls -1 /dev/binderfs/

features
anbox-binder
anbox-hwbinder
anbox-vndbinder
binder-control
```

> Waydroid works and uses `anbox-binder`

But if you load the `binder_linux` module on boot by:
` echo binder_linux | sudo tee /etc/modules-load.d/binder.conf`

You will notice some new stuff in the directory:
```
> ls -1 /dev/binderfs/

features
anbox-binder
anbox-hwbinder
anbox-vndbinder
binder-control
binder
hwbinder
vndbinder
```

> And waydroid still works.

Now, if I reinitialize (`sudo waydroid init -f`) Waydroid after auto-loading `binder_linux` module on boot, Waydroid will use use `binder` instead of `anbox-binder`
This is actually not required (**That's the point**).

> Again, Waydroid still works.

Continuing my experiment, now if I **remove** `/etc/modules-load.d/binder.conf`, after reboot:

```
> ls -1 /dev/binderfs/

features
anbox-binder
anbox-hwbinder
anbox-vndbinder
binder-control
```

And now, if I try to run Waydroid, I will get an error,

```
Can't open /dev/binder: No such file or directory
[11:37:15] Waiting for binder Service Manager...
[11:38:15] Service Manager never appeared
```

> Now I will have to reinitialize Waydroid again and reboot for Waydroid to use the `anbox-binder`.

So my point is, as per my observations, **you didn't require the binder kernel modules** for Waydroid to work. `python-gbinder` was sufficient.

But if I try to initialize Waydroid with a kernel that **doesn't have** the binder modules, I will get an error:

`modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.4.4`

So maybe you could remove the constraint for kernels to have binder modules for waydroid to work?

Of course, I can use `binder_linux-dkms` for kernels that don't have the binder modules. 
But my question is, isn't `python-gbinder` sufficient?

**Comment by austinrojers** [comment]
Anyone?

**Comment by austinrojers** [comment]
Anyone, please reply.
Let me know if I have made a valid argument.

**Comment by MostHated** [comment]
I am currently running into this same issue on Ubuntu 22.04 with kernel 6.4.x, but can't seem to find solid answers other than "the anbox method doesn't work/isn't needed anymore", and "binder" is included in the kernel, or something along those lines. So I am not sure exactly what needs to be done in this case.

**Comment by unya** [comment]
Python-GBinder is just interface over gbinder, which in turn is userspace component that used kernel binder drivers.

As such, it requires that kernel has binder driver loaded, whether added through DKMS or using one from vanilla kernel.

**Comment by austinrojers** [comment]
> Python-GBinder is just interface over gbinder, which in turn is userspace component that used kernel binder drivers.
> 
> As such, it requires that kernel has binder driver loaded, whether added through DKMS or using one from vanilla kernel.

I see…
So it was a misconception then.
Thanks for the clarification.
