### ISSUE TITLE
Failed to init waydroid on Kubuntu 23.04

### ISSUE THREAD

**Issue by DinhHoangDuy** [waydroid/waydroid#1019]
I'm on Kubuntu 23.03 KDE Wayland, I installed Waydroid with the website's instructions but can't init it. I am just stuck at this screen (Screenshots below)

![Screenshot_20230725_164856](https://github.com/waydroid/waydroid/assets/81969152/25701f79-a897-40b4-a9b2-605f952282db)
![Screenshot_20230725_165205](https://github.com/waydroid/waydroid/assets/81969152/5f695c52-77f8-4ad4-bd1a-e661608f32cd)

Do you know how I can fix this issue?

**Comment by gheescoo** [comment]
i also have the problem. it just succeed one time in my hours' try, and it then stuck at 'extracting ' blahblah

**Comment by gheescoo** [comment]
then i repeatedly restarted the service and it succeed finally
