### ISSUE TITLE
Unable to install an application, while this works on WSA

### ISSUE THREAD

**Issue by gbraad** [waydroid/waydroid#1020]
**Describe the bug**
Unable to install a certain application, while this works on WSA (Windows Subsystem for Android).

The entry shows in the Google Play store as not compatible, and  the APK downloaded from their website starst installing shows: "App not installed" after a short "Installing" progress indicator. The application offers x86_64 support as this works on WSA and an actual Intel Atom-based Android device.

**Additional context**
I am pretty sure the application developer blocks specifically for the fact this runs on Waydroid. Would it be possible to have the device identified as eg., a Pixel or a different device?

**Comment by lgdsgd2000** [comment]
WSA contains houdini, which is the arm to x86 translation layer. I'm guessing the app is only available on arm device. You can try waydroid_scripts to install houdini for waydroid, which can be found at github.

**Comment by lgdsgd2000** [comment]
Maybe the actual Intel Atom-based Android device also contains houdini. As far as I know, houdini is from intel.

**Comment by gbraad** [comment]
@lgdsgd2000 Awesome... this worked. So, yes... perhaps in more recent releases the developer decided not to add any x86 related builds (as that would explain why it runs on my older Atom machine). This is for now resolved. Faith has been restored this was not the developer blocking for "Waydroid"-specific models.
