### ISSUE TITLE
All Waydroid commands say "Run 'waydroid log' for details" including 'waydroid log'

### ISSUE THREAD

**Issue by kirsle** [waydroid/waydroid#103]
After a recent update I was experiencing the issue from #90 and ran `waydroid upgrade` to get the latest LineageOS and then Waydroid behaved weirdly: the systemctl waydroid-container service was running but Android apps wouldn't launch.

In one terminal I ran `waydroid container start` which hung w/o any text output (I guessed it meant it was running, just quiet) and in other terminals I tried commands like `waydroid show-full-ui` or `waydroid app install F-Droid.apk` or so on.

Every Waydroid command I ran said the same thing: "Run 'waydroid log' for details." When I ran `waydroid log`, same thing: "Run 'waydroid log' for details." with no way to actually _see_ what the logs were.

With `waydroid --help` I found the option `--details-to-stdout` and, adding this flag to any Waydroid command: it works!

e.g.

```bash
% waydroid app install F-Droid.apk
Run 'waydroid log' for details.
% waydroid --details-to-stdout app install F-Droid.apk
(it works)
```

I was eventually able to get Waydroid completely up and running this way, with no change except this CLI option. See the attached screenshot from my tmux session.

I would have guessed this was a unique issue to me but I saw confirmation on Reddit that another user experienced the same "Run 'waydroid log'" problem I had so there may be a root bug here.

![Getting Waydroid to freaking run and all it took was debug logging](https://user-images.githubusercontent.com/1663507/134819879-0af12143-e30d-42e1-91f4-fbcc1d2a3c60.png)

**Comment by sigmaSd** [comment]
Duplicate https://github.com/waydroid/waydroid/issues/84
