### ISSUE TITLE
Fedora Universal Blue: systemd service does not work

### ISSUE THREAD

**Issue by plata** [waydroid/waydroid#1032]
**Describe the bug**
On Fedora Silverblue, running Waydroid (`waydroid session start`) fails with
```
Failed to add service waydroidusermonitor
Failed to add service waydroidclipboard
```
Running manually with
```
sudo systemctl stop waydroid-container
sudo waydroid container start
```
works.

**General information (please complete the following information):**
 - Waydroid 1.4.1

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue (Kinoite) 38

**Additional context**
see #891

**Logs**
- `journalctl -u waydroid-container`:
```
мая 08 08:46:56 ushanka systemd[1]: Starting waydroid-container.service - Waydroid Container...
мая 08 08:46:57 ushanka systemd[1]: Started waydroid-container.service - Waydroid Container.
мая 08 08:56:32 ushanka systemd[1]: Started waydroid-container.service - Waydroid Container.
мая 08 09:05:25 ushanka dnsmasq[4014]: started, version 2.89 cachesize 150
мая 08 09:05:25 ushanka dnsmasq[4014]: compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n IDN2 DHCP 
DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash
DNSSEC loop-detect inotify dumpfile
мая 08 09:05:25 ushanka dnsmasq-dhcp[4014]: DHCP, IP range 192.168.240.2 -- 192.168.240.254, lease time 1h
мая 08 09:05:25 ushanka dnsmasq-dhcp[4014]: DHCP, sockets bound exclusively to interface waydroid0
мая 08 09:05:25 ushanka dnsmasq[4014]: reading /etc/resolv.conf
мая 08 09:05:25 ushanka dnsmasq[4014]: using nameserver 127.0.0.53#53
мая 08 09:05:25 ushanka dnsmasq[4014]: read /etc/hosts - 8 names
мая 08 09:05:26 ushanka waydroid[729]: [09:05:26] Failed to parse android version from system.img
мая 08 09:05:26 ushanka waydroid[729]: [09:05:26] waiting 10 seconds for container to start...
мая 08 09:05:27 ushanka waydroid[729]: [09:05:27] Failed to add presence handler: None
мая 08 09:05:27 ushanka waydroid[729]: [gbinder] ERROR: Can't open /dev/binder: Permission denied
...
```
The last 2 strings repeat a lot of times.

- `waydroid session start`:
```
[15:55:45] Failed to add service waydroidusermonitor: -2147483647
[15:55:45] Failed to add service waydroidclipboard: -2147483647
```

- `waydroid log` (after stopping waydroid)
```
...
(018186) [15:56:42] Failed to add presence handler: None
(018186) [15:56:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
(018186) [15:56:42] Failed to add presence handler: None
RUNNING
(018186) [15:56:42] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(018186) [15:56:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(018186) [15:56:42] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(018186) [15:56:43] % systemctl is-enabled -q nfcd
(018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor
(018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor
(018186) [15:56:43] % umount /var/lib/waydroid/rootfs
(018186) [15:56:43] % umount /var/lib/waydroid/rootfs
(020575) [16:04:27] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(020575) [16:04:27] *** output passed to waydroid stdout, not to this log ***
```
The first string repeats a lot of times.

- `sudo waydroid logcat`:
```
05-08 12:56:42.256    15    15 E lowmemorykiller: /proc/zoneinfo parse error
05-08 12:56:42.256    15    15 E lowmemorykiller: Failed to get free memory!
```
Repeating while running.

- `waydroid show-full-ui`:
```
[16:19:55] Failed to get service waydroidplatform, trying again...
```
Repeating every second.

**Comment by plata** [comment]
It seems to be an issue with SELinux.

It works as expected after:
```
systemctl stop waydroid-container
sudo senenforce 0
systemctl start waydroid-container
```
Note that Fedora ships an SELinux policy module for Waydroid (see https://packages.fedoraproject.org/pkgs/waydroid/waydroid-selinux/). `semodule -l` lists `waydroid` and the `.te` file contains entries for binder. Still, `journalctl` complains "[gbinder] ERROR: Can't open /dev/binder: Permission denied".

@aleasto any hints/additional things I might try?

**Comment by aleasto** [comment]
@plata Fedora docs has a lot of information, if you want to delve into it https://docs.fedoraproject.org/en-US/quick-docs/selinux-troubleshooting/

But more likely i'll have to reproduce this myself

**Comment by plata** [comment]
From `ausearch`:
```
type=AVC msg=audit(1693044137.315:15868): avc:  denied  { read write } for  pid=801 comm="waydroid" name="binder" dev="binder" ino=4 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:binder_device_t:s0 tclass=chr_file permissive=0
```
With `audit2allow`:
```
require {
	type binder_device_t;
	type init_t;
	class chr_file open;
}

#============= init_t ==============
allow init_t binder_device_t:chr_file open;
```
However, it still didn't work after loading this with `semodule -i`.

**Comment by plata** [comment]
Generally, do we need specific `.te`s per distribution or can we maintain a central one here?

**Comment by aleasto** [comment]
> From `ausearch`:
> ```
> type=AVC msg=audit(1693044137.315:15868): avc:  denied  { read write } for  pid=801 comm="waydroid" name="binder" dev="binder" ino=4 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:binder_device_t:s0 tclass=chr_file permissive=0
> ```
> With `audit2allow`:
> ```
> require {
> 	type binder_device_t;
> 	type init_t;
> 	class chr_file open;
> }
> 
> #============= init_t ==============
> allow init_t binder_device_t:chr_file open;
> ```
> However, it still didn't work after loading this with `semodule -i`.

The waydroid service should be running with `waydroid_t` context, not `init_t`. The domain transition isn't working

**Comment by plata** [comment]
Any way I can debug that?

**Comment by plata** [comment]
Will this be fixed in Fedora 39?

**Comment by aleasto** [comment]
I had no issues installing, initializing via GUI, and starting Waydroid on Kinoite 38 after just `rpm-ostree install waydroid`

**Comment by plata** [comment]
Mh. I still have the same issues as described above.

I should mention that I'm not on plain Silverblue but building a custom OCI image based on ublue OS. Maybe this causes some problems.

**Comment by aleasto** [comment]
Can you check the selinux label on `/usr/lib/waydroid/waydroid.py`?
`ls -lZ /usr/lib/waydroid/waydroid.py`

**Comment by plata** [comment]
```
-rwxr-xr-x. 3 root root system_u:object_r:lib_t:s0 196  1. Jan 1970  /usr/lib/waydroid/waydroid.py
```

**Comment by aleasto** [comment]
So the file is mislabeled vs the context that it should have by default, which you can get with `matchpathcon /usr/lib/waydroid/waydroid.py`

It is indeed likely that the file loses its label when you build the OCI image, but I wouldn't know how to assist your in fixing the issue

**Comment by plata** [comment]
The waydroid installation shows
```
libsemanage.semanage_rename: WARNING: rename(/etc/selinux/targeted/active, /etc/selinux/targeted/previous) failed: Invalid cross-device link, fall back to non-atomic semanage_copy_dir_flags()
```
Could that be a problem?

When I run the `ls -lZ` during the image build, I get
```
-rwxr-xr-x 1 root root ? 196 Apr 24  2023 /usr/lib/waydroid/waydroid.py
```
At least that date looks reasonable. It seems that all files in `/usr` have date 1970/01/01. No idea how that happens but e.g. https://discussion.fedoraproject.org/t/silverblue-rawhide-2019-02-05-selinux-labels-missing/1080/3 describes the same.

Even after a fresh installation, the SELinux labels and dates are still not set correctly.

**Comment by plata** [comment]
I can confirm now that installing waydroid afterwards (i.e. not including it in the OCI image) works. So it's also not a problem with uBlue OS itself.

The behavior can be reproduced with this Containerfile:
```
FROM "quay.io/fedora-ostree-desktops/kinoite:38"

RUN rpm-ostree install waydroid

RUN rm -rf /tmp/* /var/* && \
ostree container commit
```

**Comment by aleasto** [comment]
https://github.com/ostreedev/ostree-rs-ext/issues/388
