### ISSUE TITLE
Signature spoofing support

### ISSUE THREAD

**Issue by JW10234** [waydroid/waydroid#1034]
**Is your feature request related to a problem? Please describe.**
I would like to have microG (gms, gsf, and FakeStore) installed on Waydroid, which isn't possible as the waydroid images don't have signature spoofing support, because there is no permission for it. 

**Describe the solution you'd like**
Either support for signature spoofing in the vanilla image or a separate FOSS image, that is bundled with microG.

**Comment by JW10234** [comment]
I am aware that signature spoofing can be a major security risk, if the permission can be granted to any app.

**Comment by Quackdoc** [comment]
`echo "pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE" | sudo waydroid shell`

**Comment by ayasa520** [comment]
![image](https://github.com/waydroid/waydroid/assets/55699692/781def5b-4ac7-4cdb-a3ca-04fec3dba5f5)
Have you tried waydroid_script?
https://github.com/casualsnek/waydroid_script#install-microg-aurora-store-and-aurora-droid

**Comment by JW10234** [comment]
Thanks, works fine for me.
