### ISSUE TITLE
Waydroid window stuck in quarter of screen / cannot move/drag Waydroid window

### ISSUE THREAD

**Issue by therobyouknow** [waydroid/waydroid#1035]
**Describe the bug**
Waydroid window is stuck in bottom right quarter of my machine's screen. The top left corner of the window is at the centre of the screen.

I cannot see a way to move the Waydroid window: there is no title pane that I can grab and drag the window with to move it.

Looking at the properties, I cannot see Window origin property, e.g. to define the co-ordinates of the top-left corner of the window. I was hoping for this so that I could change them to something so that the window could be re-positioned.

**Screenshots**
![20230802_220148](https://github.com/waydroid/waydroid/assets/1080646/4651b48f-d8a1-4866-b8db-40af31fbd163)

**General information (please complete the following information):**
[waydroid.tools_version]: [1.4.1]

(I was able to get waydroid tools version from command `sudo waydroid shell getprop` )

 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

```
robdavisprojects@FZ-G1:~$ cat /var/lib/waydroid/waydroid.cfg
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1690594243
vendor_datetime = 1690629818
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3
```

**Desktop (please complete the following information):**
 - OS: Zorin OS 16.3
 - Intel HD Graphics 5500 
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: Mesa Intel HD Graphics 5500 (BDW GT2)
 - Desktop: 

```
robdavisprojects@FZ-G1:~$ gnome-shell --version 
GNOME Shell 3.38.4
robdavisprojects@FZ-G1:~$ 
```

**Smartphone (please complete the following information):**
Not using smart phone. Waydroid is running on an x86-64 machine - a Panasonic FZ-G1 MkIII.  Processor: Intel Core i5-5300U 2.30GHz, 4GB RAM

 
**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`.

```
robdavisprojects@FZ-G1:~$ cat /var/lib/waydroid/waydroid.prop
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
waydroid.host.user=robdavisprojects
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/robdavisprojects/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```

 - Log file, located at `/var/lib/waydroid/waydroid.log`
https://gist.github.com/therobyouknow/7a0db88205a872f786232b2b44c8530d

 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running

https://gist.github.com/therobyouknow/a1cd22143635e36e9204642b50104fea

 - Output of `dmesg`
 - 
https://gist.github.com/therobyouknow/99e76538f9eb57843e775910232ae8f7

**Comment by therobyouknow** [comment]
# Workaround

**Comment by cniw** [comment]
**CLI:** `gsettings set org.gnome.mutter center-new-windows false`
or
**GUI:** GNOME Tweaks => Windows => Center New Windows => disable it (toggle)

---

Duplicate of https://github.com/waydroid/waydroid/issues/81

**Comment by therobyouknow** [comment]
Thank you that worked (the first statement I tried and found to work) @cniw closing issue.
