### ISSUE TITLE
Update on Debian 12 Bookworm failed due to invalid signature.

### ISSUE THREAD

**Issue by fernvenue** [waydroid/waydroid#1039]
**Describe the bug**
As above, Update on Debian 12 Bookworm failed due to invalid signature.

**Screenshots**
No screenshots, but here's the error message:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.waydro.id bookworm InRelease: The following signatures were invalid: EXPKEYSIG 959FE34E90E51522 Czarek Nakamoto <abstruse@mrcyjanek.net>
W: Failed to fetch https://repo.waydro.id/dists/bookworm/InRelease  The following signatures were invalid: EXPKEYSIG 959FE34E90E51522 Czarek Nakamoto <abstruse@mrcyjanek.net>
```

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Kernel version: 6.1.0-10-amd64
 - Desktop: GNOME 43.6

**Additional context**
May relative to https://github.com/waydroid/waydroid/issues/1038.

**Comment by fernvenue** [comment]
Currently I just changed `/etc/apt/sources.list.d/waydroid.list` from `deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ bookworm main` to `deb [trusted=yes] https://repo.waydro.id/ bookworm main` to continue, **not recommended**.

**Comment by ningacoding** [comment]
Same error, i've removed PPA totally, but on the install instructions:

the command line

`curl https://repo.waydro.id | sudo bash`

Throws error:

`El repositorio «https://repo.waydro.id lunar InRelease» no está firmado.`

Repository is not signed.

**Comment by jo-so** [comment]
I fixed it with `curl https://repo.waydro.id/waydroid.gpg |sudo dd of=/etc/apt/trusted.gpg.d/waydroid.gpg`

**Comment by fernvenue** [comment]
On my new device, this problem no longer exists, so I'm gonna close this issue for now :)

**Comment by TriMoon** [comment]
@jo-so and others who stumble across this in future:

> I fixed it with `curl https://repo.waydro.id/waydroid.gpg |sudo dd of=/etc/apt/trusted.gpg.d/waydroid.gpg`

You are placing the GPG key as **a global trusted key** for apt, for ALL packages from all repos...
DON'T do that...

A better way would have been:
```
sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
```

**Comment by jo-so** [comment]
> A better way would have been:
> ```
> sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
> ```

Man sources.list says:

> The recommended locations for keyrings are /usr/share/keyrings for
> keyrings **managed by packages,** and /etc/apt/keyrings for keyrings
> **managed by the system operator.**

If your are using “signed-by” in the sources.list entry, you should place
the file in /etc/apt/keyrings.

**Comment by TriMoon** [comment]
@jo-so , please read https://blog.cloudflare.com/dont-use-apt-key/

After that you will understand why the current defacto is to use `signed-by` with keys under ` /usr/share/keyrings/` :wink:

**Comment by jo-so** [comment]
> @jo-so , please read https://blog.cloudflare.com/dont-use-apt-key/
> 
> After that you will understand why the current defacto is to use
> `signed-by` with keys under ` /usr/share/keyrings/` :wink:

Yes, interesting. This explains the signed-by, but not the violation of the
FHS, nor the part of the sources.list manual page I've cited. Did you saw
that cruft complains about this “file without a package in /usr?”

**Comment by g3n1u5d** [comment]
curl -s https://repo.mobian.org/mobian.gpg | sudo tee /etc/apt/trusted.gpg.d/mobian.gpg
