### ISSUE TITLE
Multi touch not recognizing

### ISSUE THREAD

**Issue by Asost** [waydroid/waydroid#1049]
I am currently running Waydroid with Weston on my X11 Arch system. Everything works amazingly, but my biggest concern is that my laptop's touchscreen is registered as mouse inputs instead of touch inputs. I have tried many things, but `weston-touch-calibrator` won't recognize my device. My closest efforts were through udevs which make it recognize through `libinput list-devices` but not in weston. Any help is appreciated. I was considering wayland seats, but I'm not sure how I would go with that.

**Comment by YogSottot** [comment]
Have you tried the option ```waydroid prop set persist.waydroid.fake_touch '*.*'``` ?
https://docs.waydro.id/usage/waydroid-prop-options

**Comment by Asost** [comment]
> 



> Have you tried the option `waydroid prop set persist.waydroid.fake_touch '*.*'` ? https://docs.waydro.id/usage/waydroid-prop-options

Unfortunately that did not work

**Comment by Quackdoc** [comment]
unfortunately I find that nested wayland sessions don't properly report multitouch at all. I'm not sure there is anything waydroid can do about this as this is fundementally a X11/Wayland interop issue. you will need to run native wayland session. for testing you can log into another TTY session, launch any wayland compositor like launching weston directly, and doing that.

**Comment by Quackdoc** [comment]
Update: Niri supports nested touch when running ontop of x11, I have filed an issue for cosmic so they can support it too hopefully using winit backend as well.

Note the compositor will need to be set to ignore cursor inputs, or you will need to see your DE to disable cursor, as currently most x11 DEs will treat touchscreens as inputs. This will be closed now. 

Niri: https://github.com/YaLTeR/niri
Cosmic ticket: https://github.com/pop-os/cosmic-comp/issues/903
