### ISSUE TITLE
Unable to tap certain parts of certain apps (Mostly happens with 3D games)

### ISSUE THREAD

**Issue by TheoCGaming** [waydroid/waydroid#1050]
**Describe the bug**
I can't interact with certain apps outside of UI elements

**Screenshots**
I'm... not entirely sure how i'd be able to show this.

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg` - system_datetime = 1690082412 - vendor_datetime = 1690089493 (GApps)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - GPU: Radeon R7 Mobile (and Intel HD Graphics 530)
 - Kernel version: 6.4.8-zen1-1-zen
 - Host mesa version: 23.1.4-2
 - Desktop: KDE 5.27.6
 - Model: Dell Latitude E5470

**Additional context**
I can reproduce the issue using [Tripledot Solitaire](https://play.google.com/store/apps/details?id=com.tripledot.solitaire&hl=en_US&gl=US) (don't ask)

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`
here are the logs and things: [Archive.zip](https://github.com/waydroid/waydroid/files/12329002/Archive.zip)

**Comment by Quackdoc** [comment]
have you tried setting `waydroid prop set persist.waydroid.fake_touch`? if not you can use `waydroid prop set persist.waydroid.fake_touch = '*.*'` to test

**Comment by TheoCGaming** [comment]
will try, one moment

**Comment by TheoCGaming** [comment]
it worked, thanks

**Comment by TheoCGaming** [comment]
@Quackdoc I do have a few more questions that I don't want to make separate issues for (because I feel like I'll spam the issue tracker with useless issues), but I don't know where to put them.

1. Some apps are detecting the custom ROM that Waydroid uses and refusing to run because they say that I have root access. Is there any way to mitigate or spoof that?
2. Some apps tend to crash as soon as they're started (I'm using LibHoudini). Is this a bug or can this be worked around?
3. Can viruses escape Waydroid and infect the host?
