### ISSUE TITLE
Pop!_OS 22.04 hangs when installing Waydroid

### ISSUE THREAD

**Issue by Catgithub768** [waydroid/waydroid#1054]
**Describe the bug**
When you try to install Waydroid on Pop!_OS 22.04 with apt install and its respective kernel, the system will hang and become unusable unless you do a Refresh Install

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04
 - GPU: AMD Ryzen 3 3200G integrated graphics
 - Kernel version: 6.4.6-76060406-generic
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Steps to reproduce**
 1. Install anbox-modules
 2. Load other required modules
 3. Follow Ubuntu installation guide
 4. The system will hang, after a forced restart the system will become unusable until a refresh install is made

**Comment by DeForestDiamond** [comment]
I've been having the same issue, although mine freezes after trying to install the kernel modules. Did you get an install error for the anbox-binder install, something to do with the kernel version?

**Comment by Catgithub768** [comment]
No, the anbox-binder installs normally but while installing the waydroid apt the system hangs and you cant see any logs or something to see whats the error

**Comment by shuyshuys** [comment]
i was just trying on Pop! 22.04. using gapps version
the anbox-modules broken, so i uninstall with chroot from live cd Pop!OS

then try again to install normally without anbox, then it installed. seems all working and try install plugin from waydroid_script for many apps support on playstore
