### ISSUE TITLE
Play store: This app won't work on your device

### ISSUE THREAD

**Issue by MoathDawahreh** [waydroid/waydroid#1057]
I am trying to download a particular application and I keep getting this error! 
![image](https://github.com/waydroid/waydroid/assets/24622198/46388624-a46a-4951-a6c5-cbade0e1e488)

any advices?

**Comment by YogSottot** [comment]
install arm translation
https://github.com/casualsnek/waydroid_script#install-libndk-arm-translation

**Comment by MoathDawahreh** [comment]
Thank you @YogSottot ! That  was very useful

**Comment by mak448a** [comment]
Does anyone know how to fix this?

![image](https://github.com/user-attachments/assets/9686eaa9-02c0-424c-8fe6-81b785ab41f5)
![image](https://github.com/user-attachments/assets/750c1366-c9a6-436f-9886-f75759055ca6)

**Comment by DevEddM** [comment]
@savonbeldi yeah, I'm experiencing the same issue on ubuntu 24.04

**Comment by mak448a** [comment]
Hi, I just sideloaded the APK and it seemed to work (somewhat). I think Play Store wouldn't let me download it because it's a phone-exclusive app instead of a tablet app.
