### ISSUE TITLE
failed to restart waydroid

### ISSUE THREAD

**Issue by ajie9115** [waydroid/waydroid#106]
First,  open waydroid full ui successfully
Second, close the waydroid window
Third,  open waydroid again. But there was no response，waydroid window can not show on screen

In order to start waydroid again, I had to reinstall and re-init it. But it is  too troublesome...

**Comment by Luciogi** [comment]
Instead of closing window, you should use
`waydroid session stop`

**Comment by Eveldee** [comment]
I have a similar issue running on **Pop!_OS 21.04** :

When I first run Waydroid after install, every works just fine (even if I reboot my computer before starting waydroid for the first time).
But then, if I close Waydroid (note that `waydroid session stop` doesn't close anything for me), it won't start anymore, even after a reboot although `sudo waydroid init` tells me that it's already initialized and the container service is correctly started. And I don't see any useful info in `sudo waydroid log`:

```
(001953) [11:31:50] % chmod 666 -R /dev/anbox-binder
(001953) [11:31:50] % chmod 666 -R /dev/anbox-vndbinder
(001953) [11:31:50] % chmod 666 -R /dev/anbox-hwbinder
(001953) [11:31:50] Container manager is waiting for session to load
(002589) [11:33:26] WayDroid container is STOPPED
(002591) [11:33:26] WayDroid session is not started
```

**Comment by Luciogi** [comment]
@Eveldee check `waydroid status` if container status is freeze then you can unfreeze it by `waydroid  container unfreeze`

**Comment by ajie9115** [comment]
> Instead of closing window, you should use `waydroid session stop`

thanks for helping me

**Comment by ajie9115** [comment]
closed.
