### ISSUE TITLE
KonoSuba: Fantastic Days: LIAPP Alert: Api hooking, dl_notify_number. Debugging has been detected.

### ISSUE THREAD

**Issue by YogSottot** [waydroid/waydroid#1060]
**Describe the bug**
When I try to run KonoSuba: Fantastic Days, I get the following error: LIAPP Alert: Api hooking, dl_notify_number. Debugging has been detected.

**Screenshots**
![image](https://github.com/waydroid/waydroid/assets/7411302/ec59b1a6-72f9-46c9-86a3-11a301880b4c)

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version GAPPS
```
system_datetime = 1692408656
vendor_datetime = 1692444077
```
**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04 x64
 - GPU: Intel UHD Graphics (i3-1115G4)
 - Kernel version: 6.2.0-1009-lowlatency
 - Host mesa version: 22.3.4
 - Desktop: KDE Plasma 5.24.7

**Additional context**
Waydroid is not rooted. (no Magisk/Zygisk/Lucky Patcher/LSPosed/Game Guardian/etc)
Developer mode disabled
Stock Waydroid with GApps and Google Play Protect certification
This game used to work without any problems.
No suspicious apps installed, just a few games.

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`  
  <details>
   <summary>waydroid.prop</summary>

```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
ro.product.cpu.abilist=x86_64,x86,armeabi-v7a,armeabi,arm64-v8a
ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.dalvik.vm.native.bridge=libndk_translation.so
ro.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec64=1
ro.ndk_translation.version=0.2.3
ro.dalvik.vm.isa.arm=x86
ro.dalvik.vm.isa.arm64=x86_64
waydroid.host.user=neko
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/neko/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1

```

 </details>

 - Log file, located at `/var/lib/waydroid/waydroid.log`

  <details>
   <summary>waydroid.log</summary>

   ```
   (685337) [13:10:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(685337) [13:10:42] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(685337) [13:10:42] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(687150) [13:10:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(687150) [13:10:42] % modprobe -q ashmem_linux
(687150) [13:10:42] % chmod 666 -R /dev/anbox-binder
(687150) [13:10:42] % chmod 666 -R /dev/anbox-vndbinder
(687150) [13:10:42] % chmod 666 -R /dev/anbox-hwbinder
(687168) [13:10:44] Starting waydroid session
(687168) [13:10:44] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(687150) [13:10:44] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(687150) [13:10:44] % systemctl is-active -q nfcd
(687150) [13:10:44] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(687150) [13:10:44] % chmod 777 -R /dev/dri
(687150) [13:10:44] % chmod 777 -R /dev/fb0
(687150) [13:10:44] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(687150) [13:10:44] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(687150) [13:10:44] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(687150) [13:10:44] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(687150) [13:10:44] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(687150) [13:10:44] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(687150) [13:10:44] Save config: /var/lib/waydroid/waydroid.cfg
(687150) [13:10:44] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(687150) [13:10:44] New background process: pid=687242, output=background
(687150) [13:10:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(687150) [13:10:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(687150) [13:10:44] waiting 10 seconds for container to start...
(688205) [13:10:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(687168) [13:10:54] waydroidusermonitor: Received transaction: 1
(687168) [13:10:54] Android with user 0 is ready
(687168) [13:10:54] % adb start-server
(687168) [13:10:54] % adb connect 192.168.240.112
missing port in specification: tcp:192.168.240.112
(687168) [13:10:54] Established ADB connection to Waydroid device at 192.168.240.112.
(690091) [13:11:05] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING

   ```

  </details>

 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 https://gist.github.com/YogSottot/0c3d30f58a247aa7eeb4631908cd2e07
 
 - Output of `dmesg`
https://gist.github.com/YogSottot/e038642b4aaad2e54d8d8d2d98f6391a

**Comment by YogSottot** [comment]
Ok. Fixed it by adding in ```/var/lib/waydroid/waydroid_base.prop```

```
# fix root liapp
ro.product.brand=google
ro.product.manufacturer=Google
ro.system.build.product=redfin
ro.product.name=redfin
ro.product.device=redfin
ro.product.model=Pixel 5
ro.system.build.flavor=redfin-user
ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.tags=release-keys
ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.vendor.build.id=RQ3A.211001.001
ro.vendor.build.tags=release-keys
ro.vendor.build.type=user
ro.odm.build.tags=release-keys
```

**Comment by Weroxig** [comment]
> Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> 
> ```
> # fix root liapp
> ro.product.brand=google
> ro.product.manufacturer=Google
> ro.system.build.product=redfin
> ro.product.name=redfin
> ro.product.device=redfin
> ro.product.model=Pixel 5
> ro.system.build.flavor=redfin-user
> ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.tags=release-keys
> ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.vendor.build.id=RQ3A.211001.001
> ro.vendor.build.tags=release-keys
> ro.vendor.build.type=user
> ro.odm.build.tags=release-keys
> ```

Did you get anything special to get the settings to stick? My waydroid.prop resets and removes it whenever I run `waydoid show-full-ui`.

**Comment by YogSottot** [comment]
> waydroid.prop

waydroid_base.prop not waydroid.prop

```/var/lib/waydroid/waydroid_base.prop```

**Comment by Just-Explode** [comment]
Hold on, I don't understand. How would such a configuration work???

**Comment by YogSottot** [comment]
> Hold on, I don't understand. How would such a configuration work???

Video proof
https://mega.nz/file/7cYSVAhQ#xJENf-97WJMPzUSCV-BccbH1erVZmYNSWPHkwouty3A

**Comment by Just-Explode** [comment]
> > Hold on, I don't understand. How would such a configuration work???
> 
> Video proof https://mega.nz/file/7cYSVAhQ#xJENf-97WJMPzUSCV-BccbH1erVZmYNSWPHkwouty3A

I mean, yeah, it also works for me. But why?
The only change I've seen is only that the phone name changed from "Waydroid x86-64" to "Pixel 5"

**Comment by YogSottot** [comment]
> I mean, yeah, it also works for me. But why? The only change I've seen is only that the phone name changed from "Waydroid x86-64" to "Pixel 5" yeah ofc, some apps that required non-rooted phones started to work

userdebug/test-keys → user/release-keys

Because liapp thinks that if test-keys, the phone is rooted.
In this config, test-keys has been changed to release-keys

**Comment by dannroda** [comment]
> Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> 
> ```
> # fix root liapp
> ro.product.brand=google
> ro.product.manufacturer=Google
> ro.system.build.product=redfin
> ro.product.name=redfin
> ro.product.device=redfin
> ro.product.model=Pixel 5
> ro.system.build.flavor=redfin-user
> ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.tags=release-keys
> ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.vendor.build.id=RQ3A.211001.001
> ro.vendor.build.tags=release-keys
> ro.vendor.build.type=user
> ro.odm.build.tags=release-keys
> ```
Doesnt work for me

**Comment by YogSottot** [comment]
> Doesnt work for me

If you are using VANILLA images, try switching to GAPPS.

**Comment by dannroda** [comment]
> > Doesnt work for me
> 
> If you are using VANILLA images, try switching to GAPPS.

I'm using GAPPS with libhoudini

**Comment by dannroda** [comment]
> > Doesnt work for me
> 
> If you are using VANILLA images, try switching to GAPPS.
I'm using GAPPS with libhoudini.
I'll try a fresh install cuz I can't recall if I installed GAPPS or VANILLA and changed to GAPPS.

**Comment by yms2772** [comment]
> Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> 
> ```
> # fix root liapp
> ro.product.brand=google
> ro.product.manufacturer=Google
> ro.system.build.product=redfin
> ro.product.name=redfin
> ro.product.device=redfin
> ro.product.model=Pixel 5
> ro.system.build.flavor=redfin-user
> ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.build.tags=release-keys
> ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> ro.vendor.build.id=RQ3A.211001.001
> ro.vendor.build.tags=release-keys
> ro.vendor.build.type=user
> ro.odm.build.tags=release-keys
> ```

![image](https://github.com/waydroid/waydroid/assets/6222645/07d908b4-d37f-47cf-a47c-97e5276ab5e7)

Does not work for me.
I installed gapps version and add that props to `waydroid.cfg` and checked changes, but LIAPP ALERT still pop up.

**Comment by dannroda** [comment]
> > Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> > ```
> > # fix root liapp
> > ro.product.brand=google
> > ro.product.manufacturer=Google
> > ro.system.build.product=redfin
> > ro.product.name=redfin
> > ro.product.device=redfin
> > ro.product.model=Pixel 5
> > ro.system.build.flavor=redfin-user
> > ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > ro.build.tags=release-keys
> > ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > ro.vendor.build.id=RQ3A.211001.001
> > ro.vendor.build.tags=release-keys
> > ro.vendor.build.type=user
> > ro.odm.build.tags=release-keys
> > ```
> 
> ![image](https://user-images.githubusercontent.com/6222645/282985654-07d908b4-d37f-47cf-a47c-97e5276ab5e7.png)
> 
> Does not work for me. I installed gapps version and add that props to `waydroid.cfg` and checked changes, but LIAPP ALERT still pop up.

You need to add the props to `/var/lib/waydroid/waydroid_base.prop` file, not `waydroid.cfg`
And make sure that waydroid was installed with GAPPS and not converted from VANILLA!

**Comment by yms2772** [comment]
> > > Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> > > ```
> > > # fix root liapp
> > > ro.product.brand=google
> > > ro.product.manufacturer=Google
> > > ro.system.build.product=redfin
> > > ro.product.name=redfin
> > > ro.product.device=redfin
> > > ro.product.model=Pixel 5
> > > ro.system.build.flavor=redfin-user
> > > ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > > ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > ro.build.tags=release-keys
> > > ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > > ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > ro.vendor.build.id=RQ3A.211001.001
> > > ro.vendor.build.tags=release-keys
> > > ro.vendor.build.type=user
> > > ro.odm.build.tags=release-keys
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/6222645/282985654-07d908b4-d37f-47cf-a47c-97e5276ab5e7.png)
> > Does not work for me. I installed gapps version and add that props to `waydroid.cfg` and checked changes, but LIAPP ALERT still pop up.
> 
> You need to add the props to `/var/lib/waydroid/waydroid_base.prop` file, not `waydroid.cfg` And make sure that waydroid was installed with GAPPS and not converted from VANILLA!

![image](https://github.com/waydroid/waydroid/assets/6222645/edcbc4c8-badf-4ae9-bbe1-994f61de8698)
![image](https://github.com/waydroid/waydroid/assets/6222645/667a7ed5-2d4e-406f-9b34-254a05cc9231)


I definitely installed GAPPS. I also add that props to `/var/lib/waydroid/waydroid_base.prop`.
But LIAPP still alert..

**Comment by dannroda** [comment]
> > > > Ok. Fixed it by adding in `/var/lib/waydroid/waydroid_base.prop`
> > > > ```
> > > > # fix root liapp
> > > > ro.product.brand=google
> > > > ro.product.manufacturer=Google
> > > > ro.system.build.product=redfin
> > > > ro.product.name=redfin
> > > > ro.product.device=redfin
> > > > ro.product.model=Pixel 5
> > > > ro.system.build.flavor=redfin-user
> > > > ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > > ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > > > ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > > ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > > ro.build.tags=release-keys
> > > > ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
> > > > ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
> > > > ro.vendor.build.id=RQ3A.211001.001
> > > > ro.vendor.build.tags=release-keys
> > > > ro.vendor.build.type=user
> > > > ro.odm.build.tags=release-keys
> > > > ```
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/6222645/282985654-07d908b4-d37f-47cf-a47c-97e5276ab5e7.png)
> > > Does not work for me. I installed gapps version and add that props to `waydroid.cfg` and checked changes, but LIAPP ALERT still pop up.
> > 
> > 
> > You need to add the props to `/var/lib/waydroid/waydroid_base.prop` file, not `waydroid.cfg` And make sure that waydroid was installed with GAPPS and not converted from VANILLA!
> 
> ![image](https://user-images.githubusercontent.com/6222645/282989432-edcbc4c8-badf-4ae9-bbe1-994f61de8698.png) ![image](https://user-images.githubusercontent.com/6222645/282989496-667a7ed5-2d4e-406f-9b34-254a05cc9231.png)
> 
> I definitely installed GAPPS. I also add that props to `/var/lib/waydroid/waydroid_base.prop`. But LIAPP still alert..

Restarted the container after the changes?

**Comment by yms2772** [comment]
@dannroda Yes sure. I guess your props can help avoiding root detection, but can't avoid virtual device detection.

**Comment by dannroda** [comment]
@yms2772 what the app's name?

**Comment by yms2772** [comment]
@dannroda the app name is "[blind](https://play.google.com/store/apps/details?id=com.teamblind.blind)".

**Comment by dannroda** [comment]
@yms2772 yeah, I can't even install it from the Play Store. You can try the magisk + frida combo

**Comment by YogSottot** [comment]
Instead the waydroid_base.prop props should be written to /var/lib/waydroid/waydroid.cfg, in the [properties] section, then run waydroid upgrade --offline to regenerate waydroid_base.prop with the new props

https://github.com/casualsnek/waydroid_script/issues/78

**Comment by baptx** [comment]
@YogSottot The changes mentioned in waydroid_base.prop are not enough to bypass root detection of some apps, maybe you have an idea:
https://github.com/waydroid/waydroid/issues/935#issuecomment-1879857081

**Comment by JonathanGithumbi** [comment]
whatsapp detected root. This solved the issue. Thanks OP

**Comment by Mindclaw** [comment]
I'm getting the same error when trying to play "Immortal Rising". 
Have already tried editing the waydroid.cfg and adding the recommended lines, but no change. 
Any thoughts what else could be done to avoid the error?

**Comment by YogSottot** [comment]
@Mindclaw 

Try adding
```
ro.adb.secure = 1
ro.debuggable = 0
```
I tried this game, it works for me.

**Comment by dannroda** [comment]
@Mindclaw are you using libndk or libhoudini?
libndk triggers debugging liapp alert for me.

**Comment by Antonino545** [comment]
anybody got  apple music to work ?

**Comment by richardgc13** [comment]
> Instead the `waydroid_base.prop` props should be written to `/var/lib/waydroid/waydroid.cfg`, in the `[properties]` section, then run `waydroid upgrade --offline` to regenerate waydroid_base.prop with the new props
> 
> [casualsnek/waydroid_script#78](https://github.com/casualsnek/waydroid_script/issues/78)

This worked for me with Waydroid 1.50 using Android 11, on Ubuntu 24.04.2 LTS.

I have Sky Go 24.5.1 installed from the Play Store working after these changes, when previously it threw an error detecting root.

**Comment by YogSottot** [comment]
Tried spoofing on lineage 20.0 (android 13), but konosuba still gives liapp error.  
Probably because, on android 13 I put libndk and on android 11 I use libhoudini.  

```
ro.product.brand = google
ro.product.manufacturer = Google
ro.system.build.product = redfin
ro.product.name = redfin
ro.product.device = redfin
ro.product.model = Pixel 5
ro.system.build.flavor = redfin-user
ro.build.fingerprint = google/redfin/redfin:13/TQ3A.230901.001/10750268:user/release-keys
ro.system.build.description = redfin-user 13 TQ3A.230901.001 10750268 release-keys
ro.bootimage.build.fingerprint = google/redfin/redfin:13/TQ3A.230901.001/10750268:user/release-keys
ro.build.display.id = TQ3A.230901.001
ro.build.tags = release-keys
ro.build.description = redfin-user 13 TQ3A.230901.001 10750268 release-keys
ro.vendor.build.fingerprint = google/redfin/redfin:13/TQ3A.230901.001/10750268:user/release-keys
ro.vendor.build.id = TQ3A.230901.001
ro.vendor.build.tags = release-keys
ro.vendor.build.type = user
ro.odm.build.tags = release-keys
ro.adb.secure = 1
ro.debuggable = 0
ro.build.selinux = 1
```

**Comment by docmathoc** [comment]
Worked for ubports 364, waydroid 1.5.1, on pixel3a to run apple music and the MySkoda app.
