### ISSUE TITLE
Failed to get certificate for gapps on linux mint

### ISSUE THREAD

**Issue by Nathan22211** [waydroid/waydroid#1077]
**Describe the bug**
attempting to get play certificate fails (using waydroid script, but the default method fails too even with waydroid running)

**Screenshots**
![Screenshot from 2023-08-31 05-29-03](https://github.com/waydroid/waydroid/assets/35241068/bb5f0798-bf4d-4c9e-84b3-2b86eac0b0bb)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.1 it says when doing waydroid -V
 - Waydroid Images Version: This I'm not sure of... I selected Android 13 in waydroid script

**Desktop (please complete the following information):**
 - OS: Mint 21.2 Cinnamon
 - GPU: RX 5600 XT
 - Kernel version: 5.15.0
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: Cinnamon 5.8.4

**Additional context**
I have to use weston compositor to use waydroid so some stuff might not be working right there too. And for the record, it's done that error with waydroid running in Weston as well

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**Comment by aleasto** [comment]
https://docs.waydro.id/faq/google-play-certification

**Comment by Nathan22211** [comment]
> [docs.waydro.id/faq/google-play-certification](https://docs.waydro.id/faq/google-play-certification)

did this on Zorin OS (which uses wayland) and I got this when trying that `atabases/gservices.db "select * from main where name = \"android_id\";"       <
Error: unable to open database "/data/data/com.google.android.gsf/databases/gservices.db": unable to open database file
`

**Comment by Nathan22211** [comment]
ok turns out using waydroid script completely borks google play even working. I would remove it from being recommended on the site
