### ISSUE TITLE
I can't download the image

### ISSUE THREAD

**Issue by mathews52gb** [waydroid/waydroid#1086]
Waiting for waydroid container service...
Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230902-GAPPS-waydroid_x86_64-system.zip/download
Validating system image
Downloaded system image hash doesn't match, expected: 00726c5177c71c1c885120f4f5271b66f5adfc7dc05f131e65df4b0d991d39de

**Comment by cyfex** [comment]
Same.

**Comment by aleasto** [comment]
Please hold while SourceForge resolves their issue: https://fosstodon.org/@sourceforgestatus/111022248071061762

**Comment by Bogdan-Torkhov** [comment]
Also can't download image. How long it may take?

**Comment by H3rmit** [comment]
I'm having this same problem with Nexus. Will a fix ever happen?
