### ISSUE TITLE
[Feature]Hardware video acceleration support

### ISSUE THREAD

**Issue by strayedstar** [waydroid/waydroid#1088]
### Is your feature request related to a problem? Please describe.

I'm always worried about watching the video on waydroid,it takes up a lot of CPU resources,it is unnecessary.
CPU:5700G
GPU:6800XT
(USING EGPU)

CPU:N5095
(USING IGPU)

### Describe the solution you'd like.

Blioss os realizes this function,so it seems feasible,ee can make a special plug-in to match the mox media server, such as ffmpeg-vaapi or gstream?

### Describe alternatives you've considered.

If it really doesn't work, let's keep the status.

**Comment by opticblu** [comment]
![230911_04h15m20s_screenshot](https://github.com/waydroid/waydroid/assets/26550539/8c1b1f8e-bb9e-4393-aa6f-11d721f6cb90)

Works for me on AMDGPU

**Comment by SuperKenVery** [comment]
Not working for me on Intel, using 50% cpu while firefox can use hardware decoding.

**Comment by hmtheboy154** [comment]
![photo_2024-01-21_06-03-40](https://github.com/waydroid/waydroid/assets/39849246/6056d9cd-7708-4f91-aeed-074b3c8974a5)

![photo_2024-01-21_06-05-51](https://github.com/waydroid/waydroid/assets/39849246/e9ceeb14-e5af-4550-9ac4-b672daa3b706)

Coming soon

**Comment by YAFU** [comment]
Hi.
A question. Would users of the proprietary nvidia driver be able to use acceleration with this implementation using "nvidia-vaapi-driver" as in other applications?:
https://ubuntuhandbook.org/index.php/2024/01/firefox-vaapi-nvidia/

**Comment by hmtheboy154** [comment]
> Hi. A question. Would users of the proprietary nvidia driver be able to use acceleration with this implementation using "nvidia-vaapi-driver" as in other applications?: https://ubuntuhandbook.org/index.php/2024/01/firefox-vaapi-nvidia/

Possibly ? Maybe ? It just that you will ended up with a kinda funny situation that is `hardware accelerated video decoding` but `software rendering`

**Comment by YAFU** [comment]
> Possibly ? Maybe ? It just that you will ended up with a kinda funny situation that is `hardware accelerated video decoding` but `software rendering`

Ok, thanks.
So I guess that wouldn't solve the no video/black video playback that users of proprietary nvidia drivers are having either.

**Comment by strayedstar** [comment]
> > Possibly ? Maybe ? It just that you will ended up with a kinda funny situation that is `hardware accelerated video decoding` but `software rendering`
> 
> Ok, thanks. So I guess that wouldn't solve the no video/black video playback that users of proprietary nvidia drivers are having either.

I think nvidia hardware accelerated video decoding is possible，In fact we also can use nvidia gpu but developers don't have time to do it.Another way,you can try this brach https://www.linzhuotech.com/Mobile/Product/download but it will borke you system softpack (replace file) you should install it by you self.Support nvidia amd intel gpu and hardware accelerated video decoding,android 13,desktop message......
现在需要老外了解中文去体验了，哈哈哈。东西还是有很多问题，就是不干净，会污染环境，注意一下啊。😄😄😄
