### ISSUE TITLE
.desktop file creation fails if ~/.local/share/applications does not exist

### ISSUE THREAD

**Issue by plata** [waydroid/waydroid#109]
I'm not sure if XDG specifies who is responsible to create this directory (i.e. OS or the one who creates the first .desktop file).

**Comment by relector-tuxnix** [comment]
I updated waydroid/tools/services/user_manager.py on line 61 from:

`apps_dir = "/.local/share/applications"`

to

`apps_dir = args.host_user + "/.local/share/applications"`
 
Solved it for me.
