### ISSUE TITLE
Backup Waydroid with Weston

### ISSUE THREAD

**Issue by Jetrom17** [waydroid/waydroid#1105]
### Describe the bug

I made the backup.
I did as shown here to check where the backup was made.

https://docs.waydro.id/faq/backup-restore-apps-and-data#backup

```bash
~/.local/share/waydroid/media/0/.SeedVaultAndroidBackup
```

But there is only "data" folder and not "average".
I restarted Waydroid to check, but it didn't work. 
I have installed NextCloud, but the system did not identify it as installed.

### Waydroid version

1.4.1

### Device

Linux Desktop

### Operating System

Linux Mints 21.2

### Kernel version

5.15.0-84-generic

### Desktop Environment

Cinnamon 5.8.4

### GPU

Intel Atom Processor Z36xxx/Z37

### Logs

🚫

**Comment by aleasto** [comment]
I fixed the path on the website, it should have been `~/.local/share/waydroid/data/media/0/.SeedVaultAndroidBackup`
