### ISSUE TITLE
What about an option to emulate time?

### ISSUE THREAD

**Issue by Beginner-codi** [waydroid/waydroid#1106]
### Is your feature request related to a problem? Please describe.

You see, i've been playing this game called The Battle Cats lately, and i've researched if such a thing is possible, but i haven't found anything, so i think it would be cool to add such a feature, since it's going to be pretty useful for me at least, but anyway, just wanted to suggest it, it may be a good idea to give the option to separate the android os and the main linux system for some.

### Describe the solution you'd like.

Add an option to emulate time, in better terms, to be able to use a different time then in the system itself.

### Describe alternatives you've considered.

Maybe just separate everything from the system and make it like a virtual machine, but better.

**Comment by ChrysoliteAzalea** [comment]
If you are talking about monotonic time and boot time (uptime), it can be emulated using time namespaces. However, the real time clock is not virtualized and is the same in all namespaces.

> Maybe just separate everything from the system and make it like a virtual machine, but better.

Then, you can use the virtual machine (like QEMU) to run an Android distribution (like BlissOS)? The point of the container (and the idea behind LXC which is used by Waydroid) is to run another Linux distribution on the same Linux kernel, which is better for performance, but causes some limitations. Currently, the Linux kernel does not virtualize the real time (that is shown on clocks).

**Comment by Beginner-codi** [comment]
ok, thank you for your help.
