### ISSUE TITLE
Fedora Documentation

### ISSUE THREAD

**Issue by froginperil** [waydroid/waydroid#1108]
> Waydroid can be installed from the official package repository.
> sudo dnf install waydroid
> sudo systemctl enable --now waydroid-container
> After installing, launch Waydroid from the applications menu and procede with the initialization by pasting these URLs in the OTA fields:
> System OTA: https://ota.waydro.id/system
> Vendor OTA: https://ota.waydro.id/vendor

Presumably, after enabling the service, it is necessary to actually start the service:
`#sudo systemctl start waydroid-container`

I have no clue what is meant by pasting URLs into the "OTA fields."

**Comment by aleasto** [comment]
> Presumably, after enabling the service, it is necessary to actually start the service:

No

> I have no clue what is meant by pasting URLs into the "OTA fields."

*launch Waydroid from the applications menu*
