### ISSUE TITLE
How to inject an APK as system app WITHOUT using external utils like Magisk?

### ISSUE THREAD

**Issue by TriMoon** [waydroid/waydroid#1109]
### Discussed in https://github.com/waydroid/waydroid/discussions/1001

<div type='discussions-op-text'>

<sup>Originally posted by **TriMoon** July 12, 2023</sup>
Where do we place apk files we want to be auto installed as system apps?

I have an apk from some other Androidx86 version for keyboard mapping, i think was from DarkMatter, that i want to try in waydroid that needs to be installed as system app.
- CZGameHelper: [GameHelper.apk.gz](https://github.com/waydroid/waydroid/files/12029798/GameHelper.apk.gz)
_(You need to `gunzip` this file first, it was `gzip`'ed to be able to post here...)_

---
## NOT working:
- apk at `~/.local/share/waydroid/data/system/priv-app/GameHelper/GameHelper.apk`

</div>

**Comment by aleasto** [comment]
`/var/lib/waydroid/overlay/system/`

**Comment by TriMoon** [comment]
After doing:
```console
$ sudo install -vpD GameHelper.apk /var/lib/waydroid/overlay/system/priv-app/GameHelper/GameHelper.apk
install: creating directory '/var/lib/waydroid/overlay/system/priv-app'
install: creating directory '/var/lib/waydroid/overlay/system/priv-app/GameHelper'
'GameHelper.apk' -> '/var/lib/waydroid/overlay/system/priv-app/GameHelper/GameHelper.apk'
$ systemctl restart waydroid-container.service
```
Starting `waydroid show-full-ui` went into a **boot-loop** of Android...
So i guess it worked to inject the apk, but the apk is not compatible with the Android in Waydroid...

Would love to get assistance to make this apk work in Waydroid, it is a mouse-to-tap converter which worked great on the other Android emulator mentioned...
_(It's not mine, and i forgot where i got it)_

**Comment by Quackdoc** [comment]
for anyone that comes across this in the future, you can simply copy the APK, then set the appropriate permissions. 

```
sudo chmod 644 file
sudo chown root:root  file
		```

**Comment by TriMoon** [comment]
@Quackdoc Did you try it, and did it work?
As said i would love to use the functionality it provides, so a detailed step-by-step would be **MOST** welcome :+1:
