### ISSUE TITLE
[Feature] Shared clipboard

### ISSUE THREAD

**Issue by Mam0nga** [waydroid/waydroid#1113]
### Is your feature request related to a problem? Please describe.

I can't use a shared clipboard like on other virtual machines

### Describe the solution you'd like.

How to make a shared clipboard between Waydroid with the host machine?

### Describe alternatives you've considered.

Shared clipboard between systems

**Comment by TriMoon** [comment]
See: https://github.com/waydroid/waydroid/issues?q=pyclip

**Comment by firefoxlover** [comment]
I think its

```
sudo YOURPACKAGEMANAGER install pip

pip install pyclip
```

**Comment by XilinJia** [comment]
I'm running Manjaro KDE Wayland.  Just installing pyclip doesn't help, I have to install wl-clipboard, as suggested: https://github.com/waydroid/waydroid/issues/396#issuecomment-1146171240
There is no need to install xclip as suggested somewhere.

**Comment by firefoxlover** [comment]
@Mam0nga is this issue solved?

**Comment by Mam0nga** [comment]
@firefoxlover Yes thanks, solved, but only using `--break-system-packages`. If I install isolated `pyclip` via `pipx` or `venv`, the clipboard doesn't work, I came to the conclusion that `pyclip` doesn't need isolation because it doesn't do its job, but that `--break-system-packages` may cause a package conflict in the future. Do you know if there is a way to make pyclip and Ubuntu work together, or how not to isolate pyclip completely?

**Comment by firefoxlover** [comment]
Fedora has `python3-pyclip` as a package, manjaro for sure has too. So use these if you want it to be unisolated and avoid conflicts

**Comment by BlueInGreen68** [comment]
Installing [python-pyclip](https://aur.archlinux.org/packages/python-pyclip) from AUR and restarting container fixed it for me too on arch

**Comment by wyktron** [comment]
So, on Nobara I have these installed:

```
Package python3-pip-23.3.2-1.fc40.noarch is already installed.
Package wl-clipboard-2.2.1-2.fc40.x86_64 is already installed.
```

But it still doesn't work. Are there any additional steps I have to take?

**Comment by NacreousDawn596** [comment]
on arch-based distros or using pacman in general, you can just install the following packages instead of the `--break-system-packages`:
- extra/wl-clipboard 
- extra/wl-clip-persist 
- extra/python-pyperclip

**Comment by poiNt3D** [comment]
What about Fedora Silverblue?

**Comment by Damglador** [comment]
> on arch-based distros or using pacman in general, you can just install the following packages instead of the `--break-system-packages`:
> 
>     * extra/wl-clipboard
> 
>     * extra/wl-clip-persist
> 
>     * extra/python-pyperclip

Works perfectly, but only one way - host to Android. I still can't copy from Android and paste on host

**Comment by hamadzidani** [comment]
I'm running POP!OS, Ubuntu derivative.
Copying inside Waydroid, only with having `wl-clipboard` installed via `apt` manager.
And copying from host to Waydroid, only after installing `pip install pyperclip` and/or  `pip install pyclip`. Additionally, I added to `PATH` the location `$HOME/.local/bin` where these packages are installed.

**Comment by supertestnet** [comment]
For me, none of the above suggestions worked. But I realized a workaround that's good enough for me and may help anyone else finding this thread in the future. Make two files, weston_cp.sh and weston_pt.sh. In the first, put this:

```
#!/bin/bash

echo $1 > /tmp/weston_cp.txt
```

In the second, put this:

```
#!/bin/bash

cat /tmp/weston_cp.txt
rm /tmp/weston_cp.txt
```

Move those two files into /usr/local/bin. Then, to copy some text for use in a weston window, run `weston_cp.sh whatever_you_want_to_paste`, then go to the weston window, open a terminal, and run `weston_pt.sh`. Whatever you copied will now be accessible in that terminal window, and you can copy it into the weston clipboard from there. Hope that helps.

**Comment by Nitrousoxide** [comment]
> What about Fedora Silverblue?

You can either overlay it with `rpm-ostree install python3-pyclip`

Or you can use a distrobox container, install it in there, and export it to the host.  I have a distrobox assemble file that installs some frequently used stuff which works fine exported to avoid overlaying things.

```
[Fedora-Assemble]
additional_packages="ansible xournalpp python3-pyclip"
image=ghcr.io/ublue-os/fedora-toolbox:latest
init=false
nvidia=false
pull=true
root=false
replace=true
start_now=false
exported_bins="/usr/bin/ansible"
exported_apps="xournalpp"
exported_bins="/usr/bin/ansible-playbook"
exported_bins="/usr/bin/pyclip"
exported_bins_path="/home/$USER/.local/bin"
```

run `pyclip --help' afterward to make sure it's running correctly.  If it returns the help list, then restarting the waydroid container should enable the shared clipboard.

edit: the distrobox solution should also work for any host distro that can install distrobox, so I'd recommend it if your distro doesn't have pyclip in its repos, or it's an old version or something.

**Comment by airtonix** [comment]
```
pyclip --help
```

mulitline code blocks are soooooooo much easier to copy from

**Comment by airtonix** [comment]
in any case, installing pyclip doesn't fix this for me on fedora 42

**Comment by maxlinux2000** [comment]
works fine on debian:

`sudo apt install python3-pyclipper`
