### ISSUE TITLE
[compatibility] Brawl Stars - Black Screen

### ISSUE THREAD

**Issue by 42Willow** [waydroid/waydroid#1123]
EDIT:
Upon launching the application, a black screen appears and it won't load.

---

<del>Listed on Play Store when using GAPPS as "your device is not compatible with this version"
I'm not sure whether it *is* incompatible or whether it's just marked as incompatible.
I'm on `Fedora Workstation 38` with the stock GNOME DE. 
</del>
I can attach the relevant logs if needed.

**Comment by fabriziofichera** [comment]
do you have libhoudini/libndk installed?
check this: https://github.com/casualsnek/waydroid_script

**Comment by 42Willow** [comment]
no, I just installed it through the waydroid installer. Do those add compatibility?

**Comment by fabriziofichera** [comment]
no, you have to install it manually to check compatibility.
use app like apk extractor for generate Brawl Stars apk.
Install apk with "waydroid app install namexx.apk" and run with "waydroid app launch namexx.apk".

**Comment by 42Willow** [comment]
Oh ok, I was trying to install it via the play store. I'll give that a try thanks.

**Comment by 42Willow** [comment]
How do I extract the apk if I don't have the app installed? I do not have access to another android phone or emulator.

**Comment by 42Willow** [comment]
Related to https://github.com/waydroid/waydroid/issues/968

I will follow https://github.com/casualsnek/waydroid_script#install-libndk-arm-translation and see how I go


oops sorry I forgot to search for existing issues

**Comment by 42Willow** [comment]
Update, I installed the app via aurora store with device spoofing, but upon loading the app, all I get is a black screen. Any way to see the logs of waydroid? I can't seem anything related to the launching of apps in /var/lib/waydroid/waydroid.log

**Comment by fabriziofichera** [comment]
the logs are the ones you indicated. Many times the problem is the missing of permissions on the folders that the various apps create. join the waydroid developers telegram group for better support. we see them.

**Comment by NeuHix** [comment]
@fabriziofichera can you give me the telegram group link ?

**Comment by fabriziofichera** [comment]
you can find it at the bottom of the page:
https://github.com/waydroid/waydroid

**Comment by NeuHix** [comment]
Also @fabriziofichera Can you look intro my issue #1146 if you're freeee..

**Comment by AdolfRoxler** [comment]
Use Aurora Store and spoof your hardware to something like a Samsung S9+

Google is actively preventing you from installing it

**Comment by 42Willow** [comment]
> Update, I installed the app via aurora store with device spoofing, but upon loading the app, all I get is a black screen. Any way to see the logs of waydroid? I can't see anything related to the launching of apps in /var/lib/waydroid/waydroid.log

**Comment by AdolfRoxler** [comment]
Many apps will refuse to continue running if you don't install FakeStore. Try that first

**Comment by 42Willow** [comment]
I have google play store installed on my waydroid instance though, so there should be no need to spoof it's installation right?

**Comment by AdolfRoxler** [comment]
You're screwed because Play Store will refuse to download the game since "Waydroid x86-64" is not a "Samsung Galaxy S9+"

**Comment by 42Willow** [comment]
> You're screwed because Play Store will refuse to download the game since "Waydroid x86-64" is not a "Samsung Galaxy S9+"

I did manage to download the APK, it just doesn't load as said above

**Comment by MihinMUD** [comment]
any updates or workarounds on this?

**Comment by MrPiggy105** [comment]
I manually installed the APK from uptodown... but I'm also stuck on a black screen.

**Comment by geckwwo** [comment]
AFAIK supercell released an update some time ago that broke compatibility with many emulators / compatibility layers / ... , probably intentionally

**Comment by 42Willow** [comment]
I would not be surprised if this is the case. However it is definitely possible as I know Brawl Stars works on LDplayer (although I have not tried it personally)
I'll give this another go at troubleshooting this soonish (since my kernel has changed since last year and doesn't support waydroid, I need to do some tinkering)

If I can't find any error information then I'll close this issue as stale unless someone can figure out a potential fix/find some error messages.

**Comment by GrimsGreen** [comment]
Same here, the black screen
![image](https://github.com/user-attachments/assets/2ef395a1-e871-4262-a027-95cf2520ea4a)

**Comment by 42willow** [comment]
Aurora store is now broken for me on latest waydroid - so I can't test this anymore. I'm closing this issue as stale, please don't post in this thread just to say "me too" as it fills up my inbox.

edit: unless you have more information to add of course :)

**Comment by oabragh** [comment]
in case anyone wants to play brawl in waydroid, i tried BSD brawl and it runs fine but the 3D graphics colors are messed up but maybe thats just the case for my end(?)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e6c30ff3-eb11-40df-b5e1-92de62c56500" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8066a953-34a3-4487-8cdc-f569bd800d13" />

**Comment by jbgi** [comment]
@oabragh could you share any specific settings you used? which arm translation extension?

**Comment by oabragh** [comment]
@jbgi libhoudini (because im using integrated intel gpu) and BSD brawl specifically, thats it really

**Comment by oabragh** [comment]
fixed that thanks to a stranger in null's brawl matrix server, here are the instructions he gave me:

1. Open: sudo nano /var/lib/waydroid/waydroid.cfg
2. Add a line to the end: ro.hardware.egl = angle
3. Ctrl + S, Ctrl +X
4. Run: sudo waydroid upgrade -o
5. if you are using a mouse, then you need to write one more line, because due to the instability of Waydroid + ANGLE, the container crashes when trying to process the mouse: waydroid prop set persist.waydroid.cursor_on_subsurface true
6. Restart Waydroid: sudo systemctl restart waydroid-container

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/827b7447-3763-4100-b9e8-6adb6a8e2d3c" />

i noticed that moving my cursor with trackpad is weirder now tho, if i find a solution im posting here

**Comment by congfo** [comment]
any solution?

> i noticed that moving my cursor with trackpad is weirder now tho, if i find a solution im posting here

**Comment by oabragh** [comment]
> any solution?
> 
> > i noticed that moving my cursor with trackpad is weirder now tho, if i find a solution im posting here

when using wayland-helper key mapper the cursor movement is normal

**Comment by congfo** [comment]
> when using wayland-helper key mapper the cursor movement is normal

when using waydroid_helper can get the key mapping work? at first the transparent windows wasn t running at full screen. that s why i can t make my costum mapping. the an other problem apear. when i finish mapping then pressing F1 and try to play . but theres no input? why? any fix pls

**Comment by congfo** [comment]
> when using wayland-helper key mapper the cursor movement is normal

when lunching BSD brawl it worked but stuck on 50%? when exit it the reopen it it stuck on black screen?
im using libhoudini

**Comment by congfo** [comment]
<img width="1479" height="544" alt="Image" src="https://github.com/user-attachments/assets/ff41b043-693f-42d1-9548-76d547b66995" />
look. this guy can install brawl stars normally? how??? i watche the full 50min of the video and i can t figure out how?? i have amd cpu ad gpu like him? and folow evry step hi did it?

**Comment by congfo** [comment]
> when using wayland-helper key mapper the cursor movement is normal

are you using gapp or microg?

**Comment by oabragh** [comment]
> <img alt="Image" width="1479" height="544" src="https://private-user-images.githubusercontent.com/113842195/546643891-ff41b043-693f-42d1-9548-76d547b66995.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA1NTYzODIsIm5iZiI6MTc3MDU1NjA4MiwicGF0aCI6Ii8xMTM4NDIxOTUvNTQ2NjQzODkxLWZmNDFiMDQzLTY5M2YtNDJkMS05NTQ4LTc2ZDU0N2I2Njk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwOFQxMzA4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDVlOWM5MjcyNjA0OWIxODg5NzRlNTEwOTI2Y2FkNTNlZWRhMDg3YzMzZDZiZjAxYWI4ZWY1NTM3NWFiODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KymiuNwhrmgiLltS2n89kF4wnxrDLwVnKUkv7kxJvLQ"> look. this guy can install brawl stars normally? how??? i watche the full 50min of the video and i can t figure out how?? i have amd cpu ad gpu like him? and folow evry step hi did it?

that is aurora store, he could spoof his device and make it possible to install brawl, but that doesn't guarantee it will work, can you send link to the video? i want to see

**Comment by congfo** [comment]
> that is aurora store, he could spoof his device and make it possible to install brawl, but that doesn't guarantee it will work, can you send link to the video? i want to see

sur!!
can you make a search in your waydroid for ark: ultimate mobile edition?
can you install it?
and search for efootball TM not the squad version .
if you can..

eeeee
can t find the stream video (: 
https://www.youtube.com/watch?v=lZ2tn94Tka0
this is the 50min but theres a recorded video cas this youtuber did a live streeem and some one record it. but can t find the full video (:
sorry. if i find it i will send it

*edit: did you spoof your device? if yes how did you did that? 

<img width="652" height="475" alt="Image" src="https://github.com/user-attachments/assets/0965d485-8b11-4de0-b452-aedab47d5b61" />

using this?

**Comment by oabragh** [comment]
> > that is aurora store, he could spoof his device and make it possible to install brawl, but that doesn't guarantee it will work, can you send link to the video? i want to see
> 
> sur!! can you make a search in your waydroid for ark: ultimate mobile edition? can you install it? and search for efootball TM not the squad version . if you can..
> 
> eeeee can t find the stream video (: https://www.youtube.com/watch?v=lZ2tn94Tka0 this is the 50min but theres a recorded video cas this youtuber did a live streeem and some one record it. but can t find the full video (: sorry. if i find it i will send it
> 
> *edit: did you spoof your device? if yes how did you did that?
> <img alt="Image" width="652" height="475" src="https://private-user-images.githubusercontent.com/113842195/546757596-0965d485-8b11-4de0-b452-aedab47d5b61.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA1NzA3OTksIm5iZiI6MTc3MDU3MDQ5OSwicGF0aCI6Ii8xMTM4NDIxOTUvNTQ2NzU3NTk2LTA5NjVkNDg1LThiMTEtNGRlMC1iNDUyLWFlZGFiNDdkNWI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwOFQxNzA4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTViYWI4NjMzODU3MzU1Zjg5ZjNhMzAxOGEzYjAxOGJmNDQ1MWE5Njc1OGM2ZmFkMDE4YTczMTFhNDU2YTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._1y2qxelgma77rRVKrdgX8zSpF4J0jqQ6949_T4ETe8">
> 
> using this?

in aurora store

<img width="1676" height="1080" alt="Image" src="https://github.com/user-attachments/assets/38fcfc2e-04f6-4a6a-8bc5-22ab18d7c1ae" />

**Comment by congfo** [comment]
> <img alt="Image" width="1676" height="1080" src="https://private-user-images.githubusercontent.com/117027224/546768756-38fcfc2e-04f6-4a6a-8bc5-22ab18d7c1ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA1NzQ1NjAsIm5iZiI6MTc3MDU3NDI2MCwicGF0aCI6Ii8xMTcwMjcyMjQvNTQ2NzY4NzU2LTM4ZmNmYzJlLTA0ZjYtNGE2YS04YmM1LTIyYWIxOGQ3YzFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwOFQxODExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODZjZTA5MzlmNmFiZmFlYjVkZTMxZWM4ZWQzODlkYjNkN2FjYjRjYTYxM2Y4YjZiNDU4MzlhZTQ5ZmQ4MmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DpzTBu-quO-HFEBb2ZDejyNA5XV-XXGRhIsd2GJ6-R0">

Gapp or microG?

**Comment by oabragh** [comment]
> > <img alt="Image" width="1676" height="1080" src="https://private-user-images.githubusercontent.com/117027224/546768756-38fcfc2e-04f6-4a6a-8bc5-22ab18d7c1ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA1NzQ1NjAsIm5iZiI6MTc3MDU3NDI2MCwicGF0aCI6Ii8xMTcwMjcyMjQvNTQ2NzY4NzU2LTM4ZmNmYzJlLTA0ZjYtNGE2YS04YmM1LTIyYWIxOGQ3YzFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIwOFQxODExMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODZjZTA5MzlmNmFiZmFlYjVkZTMxZWM4ZWQzODlkYjNkN2FjYjRjYTYxM2Y4YjZiNDU4MzlhZTQ5ZmQ4MmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DpzTBu-quO-HFEBb2ZDejyNA5XV-XXGRhIsd2GJ6-R0">
> 
> Gapp or microG?

gapp, and it doesnt matter aurora will work anyway

**Comment by congfo** [comment]
> gapp, and it doesnt matter aurora will work anyway

do you haave play store? can you install ark ultimata mobile edition?
edit*: can i use waydroid helper keymapping in scrcpy?

**Comment by congfo** [comment]
> > > that is aurora store, he could spoof his device and make it possible to install brawl, but that doesn't guarantee it will work, can you send link to the video? i want to see

bro, does the new bsd brawl stars work fine for you? for me in the main menu it run at 1fps but in the gameplay it run at 60fps?

**Comment by oabragh** [comment]
i haven't tried yet, but just yesterday someone dm'ed me from this thread and he managed to make it work.

**Comment by congfo** [comment]
> i haven't tried yet, but just yesterday someone dm'ed me from this thread and he managed to make it work.

Keep me updated!! if you can

**Comment by oabragh** [comment]
> Keep me updated!! if you can

my current waydroid uses an unofficial android 16 image so i don't know if my experience would change if i used the official image, but after trying to install latest bsd it refuses to open at all.

**Comment by congfo** [comment]
> > Keep me updated!! if you can
> 
> my current waydroid uses an unofficial android 16 image so i don't know if my experience would change if i used the official image, but after trying to install latest bsd it refuses to open at all.

what arm translation do you use?

**Comment by oabragh** [comment]
houdini

**Comment by congfo** [comment]
> houdini

any updates?

**Comment by geckwwo** [comment]
Information for others: Brawl Stars has protection which gets tripped off by Waydroid. Use BSD brawl, which has these protections removed. As far as I know, it has rudimentary root, environment and lsposed/xposed checks.
