### ISSUE TITLE
[Feature] Remove Google Play store compatibility requirement

### ISSUE THREAD

**Issue by 42Willow** [waydroid/waydroid#1127]
### Is your feature request related to a problem? Please describe.

**NOTE: I have installed libhoudini along with the google play store but I'm not sure if I did it correctly. I installed it with the [waydroid_script](https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation) in a python virtual env**

Related to #668 #1125 #1123 #968 
#968 is the main one

Problem is some Google Play store apps are marked as incompatible with the device (emulator) and hence, can't be installed. 

### Describe the solution you'd like.

An option to disable the "your device is not compatible with this version" message, tricking the Google Play store into thinking the device is compatible.

### Describe alternatives you've considered.

Some other way of installing google play store apps forcibly, possible through the CLI?

A safe, open source way of downloading google play APKs? I couldn't find one.

### Additional context

This is possibly due to needed some sort of Arm translation layer (libhoudini or libndk), I don't really understand how it all works but here's a useful explanation https://android.stackexchange.com/a/177887.

**Comment by Quackdoc** [comment]
this is far to generic of an issue and there is no one solution. I would reccomend trying aurora store with device spoofing

**Comment by 42Willow** [comment]
ok, thanks for pointing me in the right direction - I'll give it a go soonish

**Comment by 42Willow** [comment]
I tried with libhoudini and installing via aurora store w/ device spoofing but I get a black screen when trying to launch brawl stars. Other apps such as signal and clash royale rune smoothly though.

**Comment by fabriziofichera** [comment]
have you solved the backscreen problem?

**Comment by 42Willow** [comment]
Nope, still getting a black screen

**Comment by 42Willow** [comment]
The solution for downloading incompatible apps is aurora store w/ device spoofing

> this is far to generic of an issue and there is no one solution. I would reccomend trying aurora store with device spoofing

I'll use #1123 for the black screen issue

**Comment by hustlerone** [comment]
It's not. You can't buy anything from Aurora.
