### ISSUE TITLE
Waydroid GAPPS tablet mode?

### ISSUE THREAD

**Issue by Hideman85** [waydroid/waydroid#1133]
Hi community,

First of all this project is really insane, the integration of android with linux is just great, the apps come smoothly as executable and right now this looks to run smoothly.

In the other hand I am facing an issue that I cannot find response to it 😕
How do I make playstore believe this is a tablet and not a phone cause right now I am seeing "Looking for XYZ? This app is not compatible with your device"

I followed the procedure to register the device manually and I can install apps but the issue is that it find my device as a phone.
What can I do to make it as a tablet?

Thanks in advance for your help 🙏

Note: I try this thing (suggested by AI) without success
```
sudo waydroid shell
ANDROID_RUNTIME_ROOT=/apex/com.android.runtime ANDROID_DATA=/data ANDROID_TZDATA_ROOT=/apex/com.android.tzdata ANDROID_I18N_ROOT=/apex/com.android.i18n sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "update main set value='tablet' where name='device_form_factor';"
```
Maybe this is worth including it in the doc 🙏

**Comment by Aman9das** [comment]
Generally, you need to enable arm translation via libhoudini or libndk

https://docs.waydro.id/faq/community-projects-we-like

**Comment by Hideman85** [comment]
No sorry for the misunderstanding, I am running this on a laptop with intel cpu so I dont need arm architecture.
My mean is when I start waydroid even if it goes fullscreen the "emulated" device is a phone and not a tablet, therefore play store restrict all the app that are available on tablet and not phone.
Then the question is how I can tell the "emulated device" that this is a tablet not a phone?

**Comment by Aman9das** [comment]
Tablets in general support all of the same applications as phones, but x86 CPUs don't support all the apps from Android. libhoudini will enable waydroid to run some such apps..

**Comment by Hideman85** [comment]
Oh okey, thanks I did not understood it this way. Then yes I used the waydroid script to install the things and now it seem to do it 🙌

Thanks for the help 🙏
