### ISSUE TITLE
[Feature] Place Desktop entries in subfolder "Waydroid" for better structure

### ISSUE THREAD

**Issue by firefoxlover** [waydroid/waydroid#1138]
### Is your feature request related to a problem? Please describe.

Currently the desktop entries are a bit of a mess. Waydroid places lots of them there, for all the android apps you dont need, and also doesnt remove them when apps are uninstalled.

So as a first step to sort it more, would be a subdirectory just for Waydroid Desktop entries.

Needed for this to work: Confirmation that all Desktop Environments can use this

It works on KDE.

```
mkdir ~/.local/share/applications/Waydroid
mv ~/.local/share/applications/waydroid*.desktop ~/.local/share/applications/Waydroid/
```

### Describe the solution you'd like.

create that Directory on Setup and place all desktop entries there

### Describe alternatives you've considered.

manually doing it

**Comment by lcorbasson** [comment]
This is fixed in `main` by https://github.com/waydroid/waydroid/pull/1149.

**Comment by firefoxlover** [comment]
somewhat yes. GUI is better, but the file struture is still all in one folder. Not a huge problem though.
