### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by GuaiYiHu** [waydroid/waydroid#114]
On ubuntu 20.04, waydroid 1.1.0
[07:38:49] ERROR: <urlopen error [Errno 111] Connection refused>
[07:38:49] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by GuaiYiHu** [comment]
Running waydroid log
ERROR: WayDroid is not initialized, run "waydroid init"

**Comment by breakingtherabbit** [comment]
For me too. I'm using on Xubuntu.
