### ISSUE TITLE
[BUG] Arknights (CN version) freezes after launch for image 18.1-20231007 or later.

### ISSUE THREAD

**Issue by Jisu-Woniu** [waydroid/waydroid#1142]
### Describe the bug

I play [Arknights (CN version)](https://ak.hypergryph.com/) on an Arch Linux PC (x86-64). It used to work well, but since I upgraded waydroid-image to 18.1-20231007 (MAINLINE + VANILLA), it just freezes after launch.

I switched the image version back and forth, and also the latest version 18.1-20231014 of image. The game only works on 20230930 and earlier images.

The currently latest `.apk` file can be downloaded from <https://ak.hycdn.cn/apk/202309271907-2101-y0c1c0hpwmvo6svddz9v/arknights-hg-2101.apk>.

### Waydroid version

1.4.1

### Device

Linux Desktop

### Operating System

Arch Linux

### Kernel version

6.5.8-zen1-1-zen

### Desktop Environment

KDE Plasma 5.27.9

### GPU

Intel Corporation Iris Plus Graphics G1 (Ice Lake) (rev 07)

### Logs

/var/lib/waydroid/waydroid.cfg
[waydroid.cfg.gz](https://github.com/waydroid/waydroid/files/13174111/waydroid.cfg.gz)

/var/lib/waydroid/waydroid.prop
[waydroid.prop.gz](https://github.com/waydroid/waydroid/files/13174119/waydroid.prop.gz)

/var/lib/waydroid/waydroid_base.prop
[waydroid_base.prop.gz](https://github.com/waydroid/waydroid/files/13174196/waydroid_base.prop.gz)

/var/lib/waydroid/waydroid.log
[waydroid.log](https://github.com/waydroid/waydroid/files/13174197/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt.gz](https://github.com/waydroid/waydroid/files/13174215/logcat.txt.gz)

`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/waydroid/waydroid/files/13174220/dmesg.txt)

**Comment by Jisu-Woniu** [comment]
Still not working with 20231028 version.

**Comment by aleasto** [comment]
It looks like the mesa-23.2 upgrade broke something in the graphics driver. Unfortunately for some reason that branch is not receiving bugfix releases...

We could revert down to mesa-23.1 or wait out 23.3 which should be soon anyways

**Comment by aleasto** [comment]
The latest images use mesa 23.3, can you verify if this is fixed?

**Comment by Jisu-Woniu** [comment]
The 20231202 version? I'll give it a try later.

**Comment by Jisu-Woniu** [comment]
It works! Thank you very much!
