### ISSUE TITLE
[BUG] "Add the official repository" Error / OS incompatibility

### ISSUE THREAD

**Issue by ZecaUaSamicas** [waydroid/waydroid#1145]
### Describe the bug

This might not be that much of a bug, nor glitch.
Just an OS incompatibility.
In this case, Kali Linux, even that the version of my OS says, literally, that my OS is Kali-Rolling compatible,
I was trying to do the second part of the "Debian/Ubuntu and derivatives" Installation of Waydroid.
 
**curl https://repo.waydro.id | sudo bash**

But for whatever it isn't working at all.
I've tried all of the '-s' flag options "mantic / focal / jammy / kinetic / lunar / bookworm / bullseye / trixie / sid"
Still nothing changed, it just keeps popping up the same "error", as I shall call it for now.

**[!] Distribution "kali-rolling" is not supported**

It starts the downloading process, 3 to 4 seconds later, gives me this warning.
I've been trying to search for any help, but there's none out there about this, or that I just didn't find anything, yet.
I,as well, downloaded the index where the curl link goes through, and tried to find any errors within the commands, everything seemed right to me.
I thought of just skipping this step ahead, but this act just might make everything go downhill.
I also have my Kali machine, "bare-metal", is full up-to-date and upgraded.
So for now I can't figure this out for myself.

### Waydroid version

Most Recent "27/10/23" 

### Device

Linux Desktop

### Operating System

Kali GNU/Linux Rolling x86_64

### Kernel version

6.5.0-kali3-amd64 x86_64

### Desktop Environment

Xfce 4.18

### GPU

dual core Intel Core i3-1005G1 (-MT MCP-)

### Logs

I wasn't able to download the full repository yet.
Just the first step of the installation process "Install pre-requisites"

**sudo apt install curl ca-certificates -y**

**Comment by Israel6661** [comment]
I have the same problem, they found a solution?

> ¿Cerraste el problema porque encontraste una solución? Sería bueno compartir su solución entonces. Obtuve el mismo error diciendo que kali-rolling no es compatible, así que descargué el script https://repo.waydro.id/ y lo modificó para añadir un remap como el que se comenta antes de la comprobación de captura del error (al reemplazar kali-rolling con trixie ya que Kali Linux se basa en Debian Testing que actualmente tiene el nombre en clave trixie):
> 
> ```
> if [ "${UPSTREAM_CODENAME}" = "kali-rolling" ]; then
>     UPSTREAM_CODENAME="trixie"
> fi
> ```
> 
> Otra solución se menciona en https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives:
> 
> > Si el script no detecta su distribución, puede proporcionar una opción válida agregando -s . Los valores actualmente soportados son: focal, jammy, cinético, lunar, mantic, bookworm, bullseye, sid
> 
> Pero la documentación no está actualizada porque no menciona el nombre en clave trixie.

I have the same problem, they found a solution?
