### ISSUE TITLE
[BUG] sid support is broken

### ISSUE THREAD

**Issue by 532910** [waydroid/waydroid#1155]
### Describe the bug

https://docs.waydro.id/usage/install-on-desktops says:
> Currently supported values are: focal, jammy, kinetic, lunar, mantic, bookworm, bullseye, sid

And this was true some time ago, but not now:
```
  404  Not Found [IP: 205.185.118.53 443]
Reading package lists... Done
E: The repository 'https://repo.waydro.id sid Release' does not have a Release file.
```

no sid inside https://repo.waydro.id/dists/

### Waydroid version

not applicable

### Device

Linux Desktop

### Operating System

debian sid

### Kernel version

not applicable

### Desktop Environment

not applicable

### GPU

not applicable

### Logs

not applicable

**Comment by aleasto** [comment]
@MrCyjaneK

**Comment by MrCyjaneK** [comment]
Taking a look

**Comment by MrCyjaneK** [comment]
Okay, it looks like docker's `debian:sid` Image is just using `trixie` as `VERSION_CODENAME`

```plain
sudo docker run --rm -it debian:sid cat /etc/os-release PRETTY_NAME="Debian GNU/Linux trixie/sid"
{...}
VERSION_CODENAME=trixie
{...}
```

Which causes the repo build script to build the repo for trixie instead of sid.

**Comment by MrCyjaneK** [comment]
I've updated the workflows with hardcoded VERSION_CODENAME=sid

I'll ping you once ci finishes building. As for now you may use `trixie` instead of `sid` as this is pretty much the same thing.

**Comment by 532910** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055596

**Comment by 532910** [comment]
@sanvila:

> Packages in unstable propagate to testing after five days.
> 
> If I upload a base-files version for unstable where VERSION_CODENAME=sid,
> after such version propagates to testing, it would be wrong in
> testing.
> 
> So we have to choose. Do we want it to be correct in unstable,
> or we prefer to be correct in testing?
> 
> My choice is to make it correct in testing, as it's closer
> to the next stable (trixie as Debian 13).

**Comment by MrCyjaneK** [comment]
On our end we can use either `trixie` or `sid` and just symlink on to the other, or keep them separate. I don't get the decision to make `VERSION_CODENAME=trixie` on sid's package - as long as the distro is `sid` in sources.list it should have `VERSION_CODENAME=sid` in /etc/os-release - unless unstable/sid is exactly the same as testing/trixie - which, afaik, is not the case.

Currently I've configured it to separate trixie/sid - but this may be pointless due to the fact that sid's /etc/os-release will contain VERSION_CODENAME=trixie - and our script will just think that OS is trixie.

**Comment by sanvila** [comment]
Hi. base-files maintainer here. While itr's true that testing and unstable are not the same, packages uploaded for unstable propagate to testing after a few days. The _same_ package. This is how Debian has worked for a long time, and it's explained in detail here:

`/usr/share/doc/base-files/FAQ`

I don't use waydroid myself, but if you ask me, it does not make a lot of sense to support "sid" and not "trixie". In my opinion, if you have to choose one, it should be "trixie".

**Comment by MrCyjaneK** [comment]
Hey @sanvila Thanks for answer, I don't mind supporting both - the CI was already building packages against sid and trixie packages, but if I understand correctly /etc/os-release will contain trixie even on sid - so our install script which long story short does:

```plain
$ grep "^VERSION_CODENAME=" /etc/os-release | cut -d'=' -f2
```

would return trixie even when sid is installed.

What would be the recommended way of telling the difference between testing and unstable now?

**Comment by sanvila** [comment]
Assuming the install script is the same everywhere and it tries to guess the distribution based on what it sees, you might want to look at the Debian standard lines in sources.list (i.e. some additional grep to /etc/apt/sources.list in addition to the current grep to /etc/os-release).

Unfortunately there are now more than one supported format for sources.list (there is a new RFC822-like format for example), so this might be a little bit tricky.

**Comment by 532910** [comment]
possibly `apt policy` can be used since it's output doesn't depend on the `sources.list` format:
```
% sudo docker run --rm -it debian:sid bash -c 'apt update && apt policy' 
Get:1 http://deb.debian.org/debian sid InRelease [198 kB]
Get:2 http://deb.debian.org/debian sid/main amd64 Packages [9586 kB]
Fetched 9784 kB in 7s (1395 kB/s)                                                                                                                                                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://deb.debian.org/debian sid/main amd64 Packages
     release o=Debian,a=unstable,n=sid,l=Debian,c=main,b=amd64
     origin deb.debian.org
Pinned packages:
```

**Comment by 532910** [comment]
BTW, as base-files is the same for testing and unstable, testing says it is `.../sid`:
```
% cat /etc/debian_version 
trixie/sid
% grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Debian GNU/Linux trixie/sid"
```
Is this OK?

**Comment by sanvila** [comment]
Yes. The idea is that `PRETTY_NAME` is user-visible, while `VERSION_CODENAME` is more suitable to be used in scripts. The string `trixie/sid` is not a valid codename, but the value of the string `VERSION_CODENAME` in trixie is guaranteed to be `trixie` forever, both before and after it becomes stable.

**Comment by aleasto** [comment]
So there's actually no issue here, because the waydroid install script will detect trixie and use trixie which will work on the current sid (it'll eventually break after branching but meh)

**Comment by 532910** [comment]
if sid support is dropped docs must be updated

**Comment by aleasto** [comment]
it's  not unsupported:
`docker run -it debian:sid bash -c "apt update && apt install -y curl && curl https://repo.waydro.id | bash"`

**Comment by MrCyjaneK** [comment]
Hey! I missed one spot to overwrite VERSION_CODENAME, repo should be updated in under 30 minutes.

**Comment by 532910** [comment]
It's still broken:
```
# apt update 
[...]
Get:8 https://repo.waydro.id sid InRelease [1310 B]     
Fetched 5891 B in 2s (2686 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
82 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Conflicting distribution: https://repo.waydro.id sid InRelease (expected sid but got trixie)
```
```
# apt dist-upgrade
[...]
Get:1 https://repo.waydro.id sid/main all libglibutil amd64 1.0.66 [23.5 kB]
Err:1 https://repo.waydro.id sid/main all libglibutil amd64 1.0.66
  File has unexpected size (23444 != 23480). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:ec082c790128328d2d30d9b167ba4f9d7d8b20d8110d060a2aeccc827a8c3073
   - SHA1:f702d6872816b3e67e8925920e42cde688965885 [weak]
   - MD5Sum:9de6dc9e785669acaaae57ff9740acfa [weak]
   - Filesize:23480 [weak]
Get:2 https://repo.waydro.id sid/main all libgbinder amd64 1.1.25 [52.0 kB]
Err:2 https://repo.waydro.id sid/main all libgbinder amd64 1.1.25
  File has unexpected size (51908 != 52012). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:c975a7754d24b46bfad48e63941e8b3be46924045f153ddc5fc8db8175d66e8a
   - SHA1:5fb2c77b113c709cc6340b1f85440639b22cd803 [weak]
   - MD5Sum:1c0ea04557afb4128bb321b56214ecb9 [weak]
   - Filesize:52012 [weak]
Get:3 https://repo.waydro.id sid/main all python3-gbinder amd64 1.1.2 [89.1 kB]
Err:3 https://repo.waydro.id sid/main all python3-gbinder amd64 1.1.2
  File has unexpected size (89156 != 89076). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:e27e065f22201c493d2805f8cab1f324937f7f6c7d74e96a43482d9ee96aedee
   - SHA1:50c637cc36ac2d7839c603fcb22d7daf3db9d915 [weak]
   - MD5Sum:bec430b41ec9a7634287bf11cb9d763c [weak]
   - Filesize:89076 [weak]
E: Failed to fetch https://repo.waydro.id/dists/trixie/libglibutil_1.0.66_amd64.deb  File has unexpected size (23444 != 23480). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:ec082c790128328d2d30d9b167ba4f9d7d8b20d8110d060a2aeccc827a8c3073
    - SHA1:f702d6872816b3e67e8925920e42cde688965885 [weak]
    - MD5Sum:9de6dc9e785669acaaae57ff9740acfa [weak]
    - Filesize:23480 [weak]
E: Failed to fetch https://repo.waydro.id/dists/trixie/libgbinder_1.1.25_amd64.deb  File has unexpected size (51908 != 52012). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:c975a7754d24b46bfad48e63941e8b3be46924045f153ddc5fc8db8175d66e8a
    - SHA1:5fb2c77b113c709cc6340b1f85440639b22cd803 [weak]
    - MD5Sum:1c0ea04557afb4128bb321b56214ecb9 [weak]
    - Filesize:52012 [weak]
E: Failed to fetch https://repo.waydro.id/dists/trixie/python3-gbinder_1.1.2_amd64.deb  File has unexpected size (89156 != 89076). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:e27e065f22201c493d2805f8cab1f324937f7f6c7d74e96a43482d9ee96aedee
    - SHA1:50c637cc36ac2d7839c603fcb22d7daf3db9d915 [weak]
    - MD5Sum:bec430b41ec9a7634287bf11cb9d763c [weak]
    - Filesize:89076 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by MrCyjaneK** [comment]
@532910 uh, it tries to to download trixie version - that's why all the issues are showing up. I'm rebuilding sid repo (once again) after changing apt build script to not depend on the VERSION_CODENAME. This should be working as expected pretty soon.

**Comment by 532910** [comment]
I confirm it works fine now, thank you @MrCyjaneK !
