### ISSUE TITLE
[Feature] arm64 builds of libglibutil / libgbinder / python3-gbinder for trixie

### ISSUE THREAD

**Issue by jordemort** [waydroid/waydroid#1157]
### Is your feature request related to a problem? Please describe.

Your apt repos for trixie contain amd64 packages of libglibutil, libgbinder, and python3-gbinder, but they do not contain arm64 builds. This makes it hard to install your packages on arm64 hosts.

### Describe the solution you'd like.

I would like it if the apt repository contained arm64 builds of these packages.

### Describe alternatives you've considered.

I was able to build and install these packages locally to get waydroid installed on Mobian, but waydroid doesn't work and I'm not sure if I miessed something up along the way.

**Comment by aleasto** [comment]
@MrCyjaneK

**Comment by MrCyjaneK** [comment]
Hey the apt should contain the builds, I'm taking care of that right now for you.

**Comment by MrCyjaneK** [comment]
Looks like the arm64 Raspberry Pi is failing, I've replaced it with another one (slower and older) and it should provide you with working packages pretty soon.

Around Wednesday I'll be able to grab one or two more arm64 devices to use them for CI, so maybe when I'll have more arm64 devices I'll have time to fix them without anybody noticing...

**Comment by MrCyjaneK** [comment]
@jordemort I've triggered a rebuild and arm64 .debs for trixie should be in the repo now
