### ISSUE TITLE
Play store: 'This app won't work on your device' error message

### ISSUE THREAD

**Issue by toni20k5267** [waydroid/waydroid#1160]
### Describe the bug

'This app won't work on your device' popup after trying to install a certain app.
![image](https://github.com/waydroid/waydroid/assets/133744466/31f1de60-5eb7-47b3-9bcd-59c8fc83cb96)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 23.10

### Kernel version

6.5.0-10-generic

### Desktop Environment

45.0

### GPU

Intel® HD Graphics 520 (SKL GT2)

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
You may need arm emulation. You can see casual snek's repo [here](https://github.com/casualsnek/waydroid_script)

If you already have that, you can try [this script](https://github.com/Quackdoc/waydroid-scripts/blob/main/spoof-device.sh)

the changes in this are temporary as I don't know if there are any bad effects of it yet, so changes get overwritten on update.

**Comment by AdolfRoxler** [comment]
The workaround is to use Aurora Store. It will spoof your hardware so Google will let you download anything you want
