### ISSUE TITLE
Unable to start Bluetooth

### ISSUE THREAD

**Issue by abtye** [waydroid/waydroid#1162]
### Describe the bug

I'm on **Arch Linux** with a kernel of `6.6.1-zen1-1-zen` and a **GNOME** desktop environment.  
It has some issues with Bluetooth, and I can't start it in the GNOMEgraphical interface.  
I can only start it using the command `systemctl start bluetooth`.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Arch Linux amd64

### Kernel version

6.6.1-zen1-1-zen

### Desktop Environment

GNOME 45.1

### GPU

Intel® HD Graphics 5500 (BDW GT2)

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`
[It's all in this compressed package](https://github.com/waydroid/waydroid/files/13336725/log.zip)

**Comment by Quackdoc** [comment]
Waydroid doesn't touch bluetooth, waydroid relies on wayland (and related) protocols to handle connection to peripherals, for audio, we use pulse, for input we use wayland etc.
