### ISSUE TITLE
[Feature]Waydroid QEMU-KVM ARM version? ... please

### ISSUE THREAD

**Issue by mitcoes** [waydroid/waydroid#1176]
### Is your feature request related to a problem? Please describe.

[Wishlist](https://www.reddit.com/r/waydroid/search?q=flair_name%3A%22Wishlist%22&restrict_sr=1)
While MS WOS have several QEMU-KVM ARM android emulators using virtual machines, GNU/Linux only have Genymotion, and it is not FOSS.

Waydroid is X86 based, and it is great, but I would love a Waydroid-ARM container, that I suppose it can be done as well as it is already done in MS WOS virtual machines and multiplatform Genymotion.

PvZ2 is almost the only game I play on MS WOS, and now that I switched to AMD I was thinking that Waydroid would play it, but not.

### Describe the solution you'd like.

A Waydroid-ARM QEMU-KVM container, that would play Android ARM apps

### Describe alternatives you've considered.

Dual booting to MS WOS to run QEMU-ARM based "virtualizators"

**Comment by aleasto** [comment]
> Waydroid is X86 based

It's not

**Comment by aleasto** [comment]
https://github.com/casualsnek/waydroid_script#install-libndk-arm-translation
