### ISSUE TITLE
"Waydroid0" has an IP address, but I can't access the internet

### ISSUE THREAD

**Issue by abtye** [waydroid/waydroid#1184]
### Describe the bug

In the Waydroid container, `Settings > About Phone > IP Address` is **unavailable**.
I don't know what's going on. There's a strange network device called `vethIoJX2B@if2` that I didn't manually add, and I can't delete it.

My output when executing `ip addr show` on Arch Linux
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp8s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether fc:3f:db:d3:b6:06 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a8:a7:95:b4:02:85 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.16/24 brd 192.168.10.255 scope global dynamic noprefixroute wlan0
       valid_lft 84297sec preferred_lft 84297sec
    inet6 2409:8a34:4825:6994:12bb:40b5:b28a:430c/64 scope global dynamic noprefixroute 
       valid_lft 148021sec preferred_lft 61621sec
    inet6 fe80::cec4:a355:1ad2:df12/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
12: waydroid0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.240.1/24 brd 192.168.240.255 scope global waydroid0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe00:1/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
13: vethIoJX2B@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master waydroid0 state UP group default qlen 1000
    link/ether fe:a2:93:46:89:75 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fca2:93ff:fe46:8975/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

Output when executing `ip addr show` on the Waydroid container
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:f9:d3:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ce7e:c3d:be1b:8541/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
I suspect it is `vethiojx2b@if2` Causing this phenomenon, when I delete the Waydroid, it also disappears together.

I tried to reinstall Waydroid a few times, but didn't solve the problem.

By the way, I did not install ufw and firewalld, does that matter？

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Arch Linux amd64

### Kernel version

6.6.3-zen1-1-zen

### Desktop Environment

GNOME 45.1

### GPU

Intel® HD Graphics 5500 (BDW GT2)

### Logs

[log.zip](https://github.com/waydroid/waydroid/files/13533187/log.zip)

**Comment by abtye** [comment]
I found a similar issue #953   
Waydroid status      
```
Session:	RUNNING
Container:	RUNNING
Vendor type:	MAINLINE
IP address:	UNKNOWN
Session user:	lin(1000)
Wayland display:	wayland-0
```
I did it [this way](https://github.com/waydroid/waydroid/issues/953#issuecomment-1595901620), but `/var/lib/misc/dnsmasu.waydroid0.leaves` is an empty file.

**Comment by ChrysoliteAzalea** [comment]
I had the similar problem, and in my case, it was the firewall rules on the host that were blocking connections.

**Comment by abtye** [comment]
I reinstalled the system and now the problem has been resolved.

**Comment by phoneticallySAARTHaK** [comment]
> I reinstalled the system and now the problem has been resolved.

Only the system image or the entire waydroid program and data?

I'm also having the exact same problem

**Comment by abtye** [comment]
> > I reinstalled the system and now the problem has been resolved.
> 
> Only the system image or the entire waydroid program and data?
> 
> I'm also having the exact same problem

Well, I don't quite understand what you mean.  
I reinstalled Arch Linux.

**Comment by magbulogtong81** [comment]
> I suspect it is `vethiojx2b@if2` Causing this phenomenon, when I delete the Waydroid, it also disappears together.
I'm having this exact issue with also the weird network inteface.
Since it's fixed on your case, does it still have the weird interface?

**Comment by abtye** [comment]
> > I suspect it is `vethiojx2b@if2` Causing this phenomenon, when I delete the Waydroid, it also disappears together.
> 
> I'm having this exact issue with also the weird network inteface. Since it's fixed on your case, does it still have the weird interface?

> Please forgive my poor English.

I can't understand what you are saying. The content translated by Google is not accurate.

Are you asking if this network interface still exists?

This virtual network interface is essential for Waydroid. In fact, my issue was caused by `systemd-resolved.service` and `dnsmasq.service`. Disabling both of them and restarting the system solved my problem.
