### ISSUE TITLE
Wayland session manager - Ubuntu

### ISSUE THREAD

**Issue by Andrejki** [waydroid/waydroid#119]
Hi. 
Please include a "how to install wayland session manager on Ubuntu/anywhere" because in my Lubuntu, Ubuntu distro, it requires GNOME shell to be installed. I haven't figured out a way to install wayland session manager without GNOME shell - and Waydroid to work.
Regards

**Comment by IlgazC** [comment]
Install weston
sudo apt install weston
run it from terminal: weston
Inside it run Terminal and issue waydroid commands
