### ISSUE TITLE
Failed to load binder driver issue

### ISSUE THREAD

**Issue by DarkXero-dev** [waydroid/waydroid#1192]
Hello

Using ArchWiki guide and AUR package, I am getting the following message when running `waydroid init` command. I am on KDE Wayland session.
```
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.6.6-arch1-1
ERROR: Binder node "binder" for waydroid not found
```

**Comment by Quackdoc** [comment]
{lease don't partially follow the guide, you aren't using the right kernel

**Comment by Quackdoc** [comment]
no further correspondence. closing as stale
