### ISSUE TITLE
[BUG] Module binder_linux not found

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [waydroid/waydroid#1194]
### Describe the bug

Running `sudo waydroid init` gives an error. The output of `waydroid log` is below:

```
(068773) [16:13:53] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.6.6-76060606-generic
(068773) [16:13:53] Failed to load binder driver
(068773) [16:13:53] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.6.6-76060606-generic
(068773) [16:13:53] ERROR: Binder node "binder" for waydroid not found
(068773) [16:13:53] See also: <https://github.com/waydroid>
(068773) [16:13:53] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(068893) [16:13:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(068893) [16:13:56] *** output passed to waydroid stdout, not to this log ***
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Pop!_OS 22.04 LTS

### Kernel version

6.6.6-76060606-generic

### Desktop Environment

GNOME 42.9

### GPU

Intel UHD Graphics 630

### Logs

/var/lib/waydroid/waydroid.cfg: No such file or directory
/var/lib/waydroid/waydroid.prop: No such file or directory
/var/lib/waydroid/waydroid_base.prop: No such file or directory
/var/lib/waydroid/waydroid.log:
```
(068773) [16:13:53] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.6.6-76060606-generic
(068773) [16:13:53] Failed to load binder driver
(068773) [16:13:53] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.6.6-76060606-generic
(068773) [16:13:53] ERROR: Binder node "binder" for waydroid not found
(068773) [16:13:53] See also: <https://github.com/waydroid>
(068773) [16:13:53] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(068893) [16:13:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(068893) [16:13:56] *** output passed to waydroid stdout, not to this log ***
```

`sudo waydroid shell -- logcat -d | tee logcat.txt`: ERROR: WayDroid is not initialized, run "waydroid init"
The output of `sudo dmesg | tee dmesg.txt` is too long for me to add here, GitHub won't let me upload it. Sorry.

**Comment by EJFJCorp** [comment]
Same problem, for months, not possible to install Anbox, which is partially installed on my harddrive but not working... It did not work on any other computer, I had to use Genymotion on my laptop computer... Very very bad solution, lot of alternatives, without any EJFJ Positive Contextualisation, no warranty of anything convenient for users, and devellopers, no just retribution of anything usefully done once to satisfy a specific case which is never unique...

**Comment by adrian-moisa** [comment]
A problem persisting for a very long time. The web is full of such posts. I faced the same issue while trying to setup a Ubuntu VPS with waydroid for testing purposes. I'm now trying to run it in debian. It seems this problem is not there.

**Comment by mathiasdg** [comment]
no help??

**Comment by Quackdoc** [comment]
You need to be running a kernel with binder support, an alternative is the binder dkms found here https://github.com/choff/anbox-modules
