### ISSUE TITLE
[Feature] Pinch zoom in/out.

### ISSUE THREAD

**Issue by ecabott** [waydroid/waydroid#1198]
### Is your feature request related to a problem? Please describe.

Can't zoom in/out on clash of clans.

### Describe the solution you'd like.

scroll wheel should fake zooming in/out. scrolling can be done through click and drag. or a modifier with ctrl for zoom else scroll.

### Describe alternatives you've considered.

.

**Comment by BLACK4585** [comment]
Hey, why did this get closed? I think this would be a good feature.
