### ISSUE TITLE
Anbox differences and running on x86

### ISSUE THREAD

**Issue by JayDoubleu** [waydroid/waydroid#12]
How is this different to anbox itself and is it possible to just run it on x86 with hardware acceleration?

**Comment by rzr** [comment]
on android x86 or GNU/Linux x86 ?

**Comment by JayDoubleu** [comment]
@rzr GNU/Linux

**Comment by rzr** [comment]
So it might also need an android x86 image too, I am not sure Linage supports x86 in that case you might need to rebase on an other native ASOP image like

https://www.android-x86.org/

Unless you want to still sideload  linage in foreign architecture  (ie: emulate ARM on x86 using qemu ) ?
