### ISSUE TITLE
[BUG]Can not install waydroid on Debian

### ISSUE THREAD

**Issue by Kustale** [waydroid/waydroid#1200]
### Describe the bug

I tried installing waydroid.
However, the error below occurs and installation does not work.

waydroid doesn't work on x86?

(Originally in Korean, but translated back to English)

kustale@IRENSIA-DEB:~$ sudo apt-get install waydroid
Reading the package list... Done
Building dependency tree... Done
Reading status information... Done
Some packages cannot be installed. The requested situation may not be possible,
Either you are using an unstable distribution and have not yet created some required packages, or
It may be that it hasn't come out of Incoming yet.
The following information may be helpful in resolving this situation:

The following package dependencies are incorrect:
  waydroid : dependency: python3-gbinder but cannot be installed
E: The problem cannot be corrected. I have a broken fixed package.

When trying to install python3-gbinder:

kustale@IRENSIA-DEB:~$ sudo apt-get install python3-gbinder
Reading the package list... Done
Building dependency tree... Done
Reading status information... Done
The python3-gbinder package is not available. But it's being referenced by another package.
This means that the package is missing or deleted. Or somewhere else
Maybe you need to get a package.

E: Package 'python3-gbinder' has no installable candidates

### Waydroid version

Unknown

### Device

Linux Desktop

### Operating System

Debian 12 i686(?) [x86]

### Kernel version

6.1.0-16-686-pae

### Desktop Environment

LXqt (Maybe)

### GPU

Intel graphics on z3735f

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

[dmesg.txt](https://github.com/waydroid/waydroid/files/13700418/dmesg.txt)

**Comment by sta-c0000** [comment]
If you followed the [install instructions](https://docs.waydro.id/usage/install-on-desktops)...
Then the waydroid repo should be added to your apt sources (`/etc/apt/sources.list.d/waydroid.list`)
if it is, remember to: `apt update`
The waydroid repo supplies the `waydroid` package and these dependencies: `libglibutil`, `libgbinder` and `python3-gbinder`.

**Comment by Kustale** [comment]
> If you followed the [install instructions](https://docs.waydro.id/usage/install-on-desktops)... Then the waydroid repo should be added to your apt sources (`/etc/apt/sources.list.d/waydroid.list`) if it is, remember to: `apt update` The waydroid repo supplies the `waydroid` package and these dependencies: `libglibutil`, `libgbinder` and `python3-gbinder`.

yes. I ran it according to the installation manual.
I ran the command below as is.

curl https://repo.waydro.id | sudo bash
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
   0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:- 0 0 0 0 0 0 0 0 --:--:-- --: --:-- --:--:-100 1693 100 1693 0 0 1274 0 0:00:01 0:00:01 --:--:-- 1274
#=#=# ##O#-# ##O=# # #=#=-# # ############################# ################################################# 100.0%
deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ bookworm main
Existing:1 http://mirror.anigil.com/debian bookworm InRelease
Existing: 2 http://mirror.anigil.com/debian bookworm-updates InRelease
Existing:3 http://security.debian.org/debian-security bookworm-security InRelease
Get:4 https://repo.waydro.id bookworm InRelease [1,312 B]
Get:5 https://repo.waydro.id bookworm/main all Packages [3,174 B]
Download 4,486 bytes, takes 5 seconds (826 bytes/sec)
Reading the package list... Done
Building dependency tree... Done
Reading status information... Done
All packages are up to date.

There are no errors.

I also checked the file created in /etc/apt/sources.list.d/waydroid.list.

deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.i>

Then, I run sudo apt-get install waydroid.

sudo apt-get install waydroid
Reading the package list... Done
Building dependency tree... Done
Reading status information... Done
Some packages cannot be installed. The requested situation may not be possible,
Either you are using an unstable distribution and have not yet created some required packages, or
It may be that it hasn't come out of Incoming yet.
The following information may be helpful in resolving this situation:

The following package dependencies are incorrect:
  waydroid : dependency: python3-gbinder but cannot be installed
E: The problem cannot be corrected. I have a broken fixed package.

Same error occurs.

**Comment by sta-c0000** [comment]
Oops, sorry, I didn't know that [https://repo.waydro.id](https://repo.waydro.id/erfan/bookworm/) (← _click_ to list bookworm packages) only supports arch: `arm64` and `amd64`.
I think you would need to build a (i386) `python3-gbinder` package yourself (see [#214](https://github.com/waydroid/waydroid/issues/214)) .
Appears Intel Atom Z3735F is a 64-bit processor with 32-bit UEFI device?  I think(?) Debian supports installing amd64 OS (with 32-bit grub) on those since Jessie (v8), using the multi-arch netinst/DVD?  I'm not sure.

**Comment by Kustale** [comment]
I just reinstalled it as 64-bit Linux (efi is a 32-bit version).
It will be installed.
