### ISSUE TITLE
[BUG] message Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

### ISSUE THREAD

**Issue by jeremydaw** [waydroid/waydroid#1213]
### Describe the bug

try waydroid session start
I get the message in the subject.  Same result if I start Waydroid from the applications menu, except then the message appears in the output 
note re file upload below - /var/lib/waydroid/waydroid.prop doesn't exist, and I had to add .txt to the name of some others
note - I saw a previous issue but it seemed to be closed without giving or explaining the solution
(eg what is a Wayland compositor, should I be using one, how do I do that ??)

### Waydroid version

1.4.2-1

### Device

Linux Desktop

### Operating System

fedora 39 

### Kernel version

6.5.3-300.fc39.x86_64

### Desktop Environment

xfce

### GPU

don't know how to find this

### Logs

[waydroid.log](https://github.com/waydroid/waydroid/files/13759111/waydroid.log)
[waydroid.cfg.txt](https://github.com/waydroid/waydroid/files/13759132/waydroid.cfg.txt)
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/13759133/waydroid_base.prop.txt)

[dmesg.txt](https://github.com/waydroid/waydroid/files/13759137/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/13759138/logcat.txt)

**Comment by Quackdoc** [comment]
XFCE is not wayland yet, so waydroid wont work on it until it supports wayland, in the mean time you can use a nested compositor like cage or weston

**Comment by SVTA-OP** [comment]
Or you are forced to use another Desktop Environment that currently uses Wayland like GNOME, KDE Plasma, and Sway.

**Comment by riwide** [comment]
I get the same error trying to install and run waydroid on Raspberry Pi 5  RPi OS (Debian Bookworm)  which I thought was now based on wayland.

**Comment by SVTA-OP** [comment]
Afaik, Rpi OS still uses the LXDE Desktop which use xorg, so you can't run waydroid from there without weston.

**Comment by riwide** [comment]
A new version of Raspberry Pi OS is available to download — and it boasts
big changes.

Raspberry Pi OS “Bookworm” is based on the recent Debian 12 “Bookworm”
<https://www.omgubuntu.co.uk/2023/06/debian-12-bookworm> release. This
brings an updated set of software, packages, and tooling to users of
Raspberry Pi OS.

But that’s not all.

*“We have been working on some major architectural changes to the Raspberry
Pi Desktop, and these are launched for the first time in the Bookworm
release. And this is where you might notice some differences,” *explains
Pi’s Simon Long
<https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/>
.

Raspberry Pi OS now uses Wayland (instead of X11) with Wayfire
<https://wayfire.org/> (instead of Mutter) by default on Raspberry Pi 4 and
Raspberry Pi 5. This switch improves OS performance, security, and
aesthetics (there are window opening/closing animations).


:) Wayland

cheers

Richard

**Comment by riwide** [comment]
p.s. The RPI 5 is a lovely beast. Using an ssd it really sprints with a
superb screen.

Richard

**Comment by SVTA-OP** [comment]
Is it possible for you to send a screenshot of your output after running `fastfeatch`?

**Comment by riwide** [comment]
Apologies for the delay, had to install dependencies and build fastfetch.
No prebuilt for arm.

My rpi5 result is:
      _,met$$$$$gg.           ***@***.***
    ,g$$$$$$$$$$$$$$$P.        -----------
  ,g$$P"         """Y$$.".     OS: Debian GNU/Linux bookworm 12.4 aarch64
 ,$$P'               `$$$.     Host: Raspberry Pi 5 Model B Rev 1.0
',$$P       ,ggs.     `$$b:    Kernel: 6.1.0-rpi7-rpi-2712
`d$$'     ,$P"'   .    $$$     Uptime: 22 mins
 $$P      d$'     ,    $$$P    Packages: 1851 (dpkg)
 $$:      $.   -    ,d$$'      Shell: bash 5.2.15
 $$;      Y$b._   _,d$P'       Display: 1920x1080
 Y$$.    `.`"Y$$$$P"'          DE: LXDE-pi-wayfire
 `$$b      "-.__               WM: Wayfire (Wayland)
  `Y$$                         Cursor: PiXflat (24px)
   `Y$$.                       Terminal: lxterminal
     `$$b.                     Terminal Font: Monospace (10pt)
       `Y$$b.                  CPU: Cortex-A76 (4) @ 2.40 GHz
          `"Y$b._              GPU: Broadcom V3D 7.1
             `"""              Memory: 1.42 GiB / 7.86 GiB (18%)
                               Swap: 0 B / 99.98 MiB (0%)
                               Disk (/): 14.25 GiB / 219.53 GiB (6%) - ext4
                               Disk (/media/fudge/Ultimate Pro): 4.12 GiB /
4]
                               Local IP (wlan0): 10.12.54.6/24 *
                               Locale: en_GB.UTF-8

(note - the IP address is edited to be fake)
Richard

**Comment by Quackdoc** [comment]
try manually exporting appropriate WAYLAND_DISPLAY

**Comment by riwide** [comment]
Any examples?
 I have no awareness yet of wayland.
