### ISSUE TITLE
Waydroid refusing upgrade.

### ISSUE THREAD

**Issue by ActiveTutorial** [waydroid/waydroid#1221]
### Describe the bug

I cant upgrade waydroid.
So I unisntalled it and reinstalled it.
Here is me trying immediatly after reinstalling:

$ sudo waydroid init
[00:53:01] Already initialized
$ sudo waydroid
[00:53:07] Run waydroid -h for usage information.
$ sudo waydroid upgrade
[00:53:15] Upgrade refused because a pre-installed image is detected at /usr/share/waydroid-extra/images.
$ sudo rm -rf /usr/share/waydroid-extra/
$ sudo waydroid upgrade
[00:54:08] Upgrade refused because a pre-installed image is detected at /usr/share/waydroid-extra/images.

I hope this gets adressed thanks in advance.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu

### Kernel version

6.2.0-39-generic

### Desktop Environment

I honestly don't know

### GPU

None

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

None of these files appear.

The first commands output:
$ sudo waydroid shell -- logcat -d | tee logcat.txt
[01:02:52] WayDroid container is STOPPED

The 2nd commands output was too long but this is basically what it spammed just with diffrent numbers:
[14551.790542] binder_linux: 18984:18984 cannot find target node
[14551.790586] binder_linux: 18984:18984 transaction call to 0:0 failed 525914/29189/-22, size 0-0 line 3043

**Comment by aleasto** [comment]
You configured waydroid without the OTA updater by placing images in `/usr/share/waydroid-extra/images`. This means you want to manage your own images.

To reconfigure it with the OTA updater, `rm -rf /usr/share/waydroid-extra` and `sudo waydroid init --force`

**Comment by baptx** [comment]
The folder to remove changed according to https://docs.waydro.id/faq/using-custom-waydroid-images:

> /usr/share/waydroid-extra/images/ used to be the previously preferred path before waydroid --version 1.3.3 (it still is perfectly valid however right now as well).

Here is how I fixed the issue and included GAPPS:
```
sudo trash /etc/waydroid-extra/images/
sudo waydroid init -s GAPPS
```

I used the `trash` command instead of `rm` to avoid accidental deletions.
When everything is working, you can then use `sudo trash-list` to verify what you will delete and confirm with `sudo trash-empty`.
