### ISSUE TITLE
[Feature] Support for X11

### ISSUE THREAD

**Issue by Werenter** [waydroid/waydroid#1223]
### Is your feature request related to a problem? Please describe.

X11 is more popular window system on linux, then Wayland, for example, I am using Xorg.

### Describe the solution you'd like.

I think that adding support for X11 is not very hard, but it is useful.

### Describe alternatives you've considered.

I don't now how to fill this string.

**Comment by YasirRWebDesigner** [comment]
I don't think it will have it can be not really sure, distros are dropping Xorg left n right, red hat dropping Xorg, KDE Plasma 6 Dropped it, even Gnome is going to drop Xorg. 

So idk the "popularity" will go down, drastically to a hand full of people who will patch things themselves and use it.

**Comment by Werenter** [comment]
Some statistics from russian website: https://www.linux.org.ru/polls/polls/17322702

73% using Xorg.

Gnome is not important so it is one of the worst things in linux. KDE not dropping X11 support. Distros also support xorg.

**Comment by Werenter** [comment]
@YasirRWebDesigner

**Comment by YasirRWebDesigner** [comment]
> KDE is not dropping X11 support. Distros also support xorg.

KDE has dropped support for X11 in Plasma 6 as of October 2023. This means that the latest version of KDE's desktop environment, Plasma 6, will only run on the newer Wayland display server.

Discussion threads on the topic:

https://discuss.kde.org/t/fedora-kde-40-plans-to-completely-drop-x11/5047
https://forum.endeavouros.com/t/kde-dropping-x11-for-wayland-on-plasma-6-discussion-and-the-alternatives-in-that-case/46561?page=12
https://www.youtube.com/watch?v=Scdi8bcW4Q0



> Gnome is not important so it is one of the worst things in linux.

GNOME is the default desktop environment for several popular Linux distributions, including Ubuntu, Fedora, and openSUSE. This suggests a significant user base, sure it doesn't account for users who change their desktop environment after installation but Gnome and KDE are the most used DEs on linux and once they drop Xorg everyone will follow.

**Comment by Werenter** [comment]
> KDE has dropped support for X11 in Plasma 6 as of October 2023. 

It is not KDE, it is Fedora. Fedora is distro that has gone to shit. Ubuntu also gone. There is no reason to use it. Now the most popular distros are Debian and Arch and they looks like the best by a lot of reasons.

About GNOME - I also don't know any reason for using it. It is bad in all - in design, in UX and UI.

**Comment by Spike1377** [comment]
wayland works grate most of the time, [you can run wayland in x](https://www.youtube.com/watch?v=tJ-Mna_zi0o&pp=ygUNd2F5ZHJvaWQgb24geA%3D%3D) if you want. despite the robot voice it seems like it could be very helpful

**Comment by abtye** [comment]
You can use Weston.

**Comment by SollyBunny** [comment]
so many graphical glitches for me using a nested compositor its pretty much unusable also probably octuple buffering which cant be good

**Comment by lm2lm2** [comment]
> X11 support is not likely to happen, you can use a nested compositor instead

hi, do you have a how to for this? my distro is xorg-ed, and several others distros i use are still working with xorg. Weston/wayland is mainly deployed on trend distros, sort of mainlines ones. Not all of linux distros, far of it

if there is a little how-to to configure nested or something "easily" for a waydroid emulation under xorg, dont hesitate to tell :)

**Comment by 117l11** [comment]
> > X11 support is not likely to happen, you can use a nested compositor instead
> 
> hi, do you have a how to for this? my distro is xorg-ed, and several others distros i use are still working with xorg. Weston/wayland is mainly deployed on trend distros, sort of mainlines ones. Not all of linux distros, far of it
> 
> if there is a little how-to to configure nested or something "easily" for a waydroid emulation under xorg, dont hesitate to tell :)

https://forum.manjaro.org/t/how-to-install-run-waydroid-on-xfce-or-other-non-wayland-desktops/152925

**Comment by Spike1377** [comment]
sudo apt install sway

sway

Super+d

Type "waydroid" press enter

See easy

**Comment by Heavygrass** [comment]
@iEscapedVim 
> GNOME is the default desktop environment for several popular Linux distributions, including Ubuntu, 

Ubuntu Cinnamon has **X11** at least by default.
