### ISSUE TITLE
Waydroid is asking for the SSE3 but not for the PNI CPU-Flag

### ISSUE THREAD

**Issue by git2fa** [waydroid/waydroid#1228]
### Describe the bug

I am trying to install the recent version of waydroid on Debian GNU/Linux 11 (bullseye).
The installation process works fine, but when I try to start waydroid I get the error message:

```
# waydroid init
[21:02:30] ERROR: x86/x86_64 CPU must support SSSE3!
[21:02:30] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

```

```
# waydroid log
...
(045071) [21:02:30] ERROR: x86/x86_64 CPU must support SSSE3!
(045071) [21:02:30] See also: <https://github.com/waydroid>
(045071) [21:02:30] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 33, in setup_config
    args.arch = helpers.arch.host()
  File "/usr/lib/waydroid/tools/helpers/arch.py", line 17, in host
    return maybe_remap(mapping[machine])
  File "/usr/lib/waydroid/tools/helpers/arch.py", line 26, in maybe_remap
    raise ValueError("x86/x86_64 CPU must support SSSE3!")
ValueError: x86/x86_64 CPU must support SSSE3!

```

Well - that's right so far, because the CPU does not support this **sse3** flag, because it is alternative named with **pni**

```
# cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 945 Processor
stepping        : 2
microcode       : 0x10000db
...
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs            : tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2

```

Just have a look at this two websites:
* https://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X4%20945%20-%20HDX945FBK4DGI%20(HDX945FBGIBOX).html
* https://axebase.net/blog/2022/09/05/chromium-fehlendes-sse3-flag/ (german, explaining that sse3 is alternatively named pni)

Will there be a solution by waydroid for it?

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian GNU/Linux 11 (bullseye)

### Kernel version

5.10.0-27-amd64

### Desktop Environment

KDE

### GPU

NVIDIA Corporation GF108 [GeForce GT 430]

### Logs

[waydroid.log](https://github.com/waydroid/waydroid/files/13854822/waydroid.log)

**Comment by aleasto** [comment]
Can you try removing the check at `/usr/lib/waydroid/tools/helpers/arch.py` and see if it indeed works?

There's also an SSE4.2 check that if failed it will use x86 android rather than x86_64.

**Comment by git2fa** [comment]
O.K.


> here's also an SSE4.2 check that if failed it will use x86 android rather than x86_64.

What does this mean?
How should this be fixed?


Changed line 25 in /usr/lib/waydroid/tools/helpers/arch.py to
`        if ("ssse3" and "pni") not in cpuinfo:`

Now the script continues.

```
# waydroid init
[13:05:08] x86_64 CPU does not support SSE4.2, falling back to x86...
[13:05:09] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86/lineage-18.1-20240106-VANILLA-waydroid_x86-system.zip/download
[Downloading] 604.44 MB/604.48 MB    1710.87 kbps(approx.)[13:17:38] Validating system image
[13:17:41] Extracting to /var/lib/waydroid/images
[13:17:52] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86/lineage-18.1-20240106-MAINLINE-waydroid_x86-vendor.zip/download
[Downloading] 95.55 MB/95.63 MB     647.47 kbps(approx.)[13:20:12] Validating vendor image
[13:20:12] Extracting to /var/lib/waydroid/images

```

Further tests later on ...

**Comment by aleasto** [comment]
> What does this mean?

Exactly this:
`[13:05:08] x86_64 CPU does not support SSE4.2, falling back to x86...`

The android x86_64 ABI is defined to require SSE4.2, while the 32-bit x86 ABI doesn't.
So we fallback to using a 32 bit android OS where SSE4.2 isn't detected.

**Comment by Piroro-hs** [comment]
```
sudo rm -rf /var/lib/waydroid /home/.waydroid ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid
```

**Comment by sta-c0000** [comment]
> Well - that's right so far, because the CPU does not support this **sse3** flag, because it is alternative named with **pni**

You are confusing **SSSE3** (_**Supplemental** Streaming SIMD Extensions 3_) with SSE3 (_pni_), they are **NOT** the same!  Some 10+ year old AMD CPUs, like the Phenom, support SSE3 (pni), but **not** SSSE3.  x86_64 and even x86 Android requires [support for SSSE3](https://developer.android.com/ndk/guides/abis#abi-table).

If you remove that check in _arch.py_, the Waydroid container will simply crash on an illegal instruction when starting on a CPU that does not support SSSE3.

**Comment by sta-c0000** [comment]
@git2fa, Google themselves have declared the [SSSE3 instruction set a requirement](https://developer.android.com/ndk/guides/abis#abi-table) for Android x86 (and x86_64) CPUs.
Your CPU simply does not support the SSSE3 instruction set (see [above](https://github.com/waydroid/waydroid/issues/1228#issuecomment-1891008363)).
Since your CPU is not supported by Android itself, there is nothing Waydroid can do about this.
You could try using an [SSSE3 emulator](https://github.com/blogdron/opemu-linux), but it will be _very_ slow.

Please close this issue.

**Comment by git2fa** [comment]
O.K. Maybe this can be tested on an PC with a Intel CPU.
Thank you for the support.

**Comment by jonasmsf** [comment]
Infelizmente não consegui resolver.  Já tentei de tudo, se alguém ainda tiver como me ajudar agradeço.
