### ISSUE TITLE
Issues downloading waydroid repo to linux mint

### ISSUE THREAD

**Issue by Strapchay** [waydroid/waydroid#1233]
Have tried following the installation process in your documentation to download waydroid this is the following commands have ran and the error gotten:
``sudo apt install curl ca-certificates -y``

Whenever i try to add the official repo by running: ``curl https://repo.waydro.id | sudo bash`` then i get:
> curl: (60) SSL certificate problem: certificate has expired
> More details here: https://curl.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

Is it okay download it insecure or what is the best option to bypass this issue?

**Comment by RoBoT095** [comment]
Same here, just updated to Mint 21.3 and wanted to try Cinnamon on Wayland

**Comment by nicolaslh31** [comment]
Hi everyone, same issue on Ubuntu 22.04.3 this afternoon. Sincerely yours.

**Comment by Rouji** [comment]
Same issue everywhere. They forgot to renew their certificate. Not related to your distro.

**Comment by Strapchay** [comment]
If they forgot to renew, how can we be certain its their official repo though

**Comment by Rouji** [comment]
> If they forgot to renew, how can we be certain its their official repo though

You can be about as certain as 2 days ago. It being a day expired doesn't mean some hacker can do anything more with the domain/server than they could when it was still valid.

**Comment by Strapchay** [comment]
I tried adding their repo using ``curl -k https://repo.waydro.id | sudo bash -s victoria`` but i just get stuck on the download:

> Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1693  100  1693    0     0   1079      0  0:00:01  0:00:01 --:--:--  1079
> 
>

**Comment by nicolaslh31** [comment]
It's done, installation completed this morning. No more issue. Thanks a lot. Sincerely yours
