### ISSUE TITLE
[BUG] "Failed to get service waydroidplatform, trying again..."

### ISSUE THREAD

**Issue by toni20k5267** [waydroid/waydroid#1244]
### Describe the bug

Hello! I recently updated Waydroid through the app available in it, Waydroid Updater and Waydroid cannot start, it shows this error message: "Failed to get service waydroidplatform, trying again...". I don't really know what happened, after updating the system it was fine but the next day, when i turned on my laptop again Waydroid could not start. I did download two third party apps but they werent viruses so i dont think its that... it also says the session is running but it is not showing up after using "waydroid show-full-ui", even with admin permissions...
![Screenshot with terminal windows, these two always show up but i didnt think they are a problem: "{23:23:08} WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
{23:23:09} Skipping clipboard manager service because of missing pyclip package
" ](https://github.com/waydroid/waydroid/assets/133744466/3bd25ff0-c9ba-4d7f-9988-306fb6ea5b19)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 23.10

### Kernel version

6.5.0-14-generic

### Desktop Environment

GNOME 45.0

### GPU

Intel® HD Graphics 520 (SKL GT2)

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`
Unfortunately i was not able to provide the log files, it could not load nor fit on the screen to copy, i really apologize... I don't know why it couldn't, my laptop just said 'no' and i couldnt do anything, I again apologize...

**Comment by Quackdoc** [comment]
WAYLAND_DISPLAY is not set means that you are most likely running x11, waydroid has a hard requirement on wayland, you can use sway, cage, or weston nested.
