### ISSUE TITLE
[BUG] Waydroid crashes when starting certain games without any mouse connected.

### ISSUE THREAD

**Issue by Stroopwaf3l** [waydroid/waydroid#1245]
### Describe the bug

Whenever I want to play games like Minecraft I have to connect my Typecover or a bluetooth mouse to my Surface Go 2. If I don´t Waydroid just crashes, and in logcat I found the following line:

`wayland-hwc: error marshalling arguments for lock_pointer (signature noo?ou): null value passed for arg 2`

I think Waydroid tries to capture the mouse and keep it centered, as that's how these games work, and if no mouse is connected it just fails to do that.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian 12

### Kernel version

6.6.11-surface-1

### Desktop Environment

Gnome 43.9

### GPU

Mesa Intel® UHD Graphics 615 (AML-KBL)

### Logs

[dmesg.txt](https://github.com/waydroid/waydroid/files/13987106/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/13987108/logcat.txt)
[waydroid.cfg.txt](https://github.com/waydroid/waydroid/files/13987120/waydroid.cfg.txt)
[waydroid.log](https://github.com/waydroid/waydroid/files/13987121/waydroid.log)
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/13987122/waydroid.prop.txt)
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/13987123/waydroid_base.prop.txt)

**Comment by aleasto** [comment]
Didn't think of that possibility :)

Should be fixed in the next OTA

**Comment by Stroopwaf3l** [comment]
Thank you! I was hoping it wouldn't be an issue with my Debian install.

**Comment by aleasto** [comment]
The update is released, please try it out

**Comment by Stroopwaf3l** [comment]
It works! Thank you! This makes my Surface Go a perfect tablet, this was the last reason to go back to Windows, now I can keep using Debian on it permanently.
