### ISSUE TITLE
Rendering is unreadable and presenting glitches

### ISSUE THREAD

**Issue by mauriciobc** [waydroid/waydroid#125]
All applications and full UI is presented with glitches.
Running Ubuntu 21.04 with GNOME 40.4 from the Shemgp repository. GPU is hybrid, currently using NVE7 / Intel® HD Graphics 4000 (IVB GT2). 

![Captura de tela de 2021-09-30 12-04-27](https://user-images.githubusercontent.com/5098821/135654298-f6735d27-905c-44ed-ba64-1e67c47786a6.png)
![Captura de tela de 2021-09-30 12-16-56](https://user-images.githubusercontent.com/5098821/135654304-29365e16-cbcf-4509-929e-b46283832c5c.png)

**Comment by dwsong07** [comment]
![image](https://user-images.githubusercontent.com/27623326/139788595-5e9b653d-5be1-495e-90e0-07b2b9b10bc1.png)
I'm having same problem.

In GNOME 40.5 wayland in Arch Linux, GPU is Intel HD Graphics 620/NVIDIA GeForce 940MX.

**Comment by actualdankcoder** [comment]
> ![image](https://user-images.githubusercontent.com/27623326/139788595-5e9b653d-5be1-495e-90e0-07b2b9b10bc1.png) I'm having same problem.
> 
> In GNOME 40.5 wayland in Arch Linux, GPU is Intel HD Graphics 620/NVIDIA GeForce 940MX.

Same scenario in EndeavourOS Wayland with Linux zen kernel

**Comment by dwsong07** [comment]
I solved the issue by [this comment](https://github.com/waydroid/waydroid/issues/61#issuecomment-944979878)!
