### ISSUE TITLE
[BUG] Waydroid not launching on Raspberry Pi 5 with Ubuntu due to binder node errors

### ISSUE THREAD

**Issue by matu6968** [waydroid/waydroid#1251]
### Describe the bug

When ran sudo waydroid init:
output:
[16:02:43] Failed to load binder driver
[16:02:43] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.5.0-1008-raspi
[16:02:43] ERROR: Binder node "binder" for waydroid not found
[16:02:43] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

This issue does not happen on Raspberry Pi OS 64 bit.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 23.10 ARM64

### Kernel version

6.5.0-1008-raspi

### Desktop Environment

GNOME 45.2

### GPU

VideoCore VII

### Logs

[dmesg.txt](https://github.com/waydroid/waydroid/files/14025725/dmesg.txt)
[waydroid.log](https://github.com/waydroid/waydroid/files/14025712/waydroid.log)

**Comment by EricB84300** [comment]
hi @matu6968

**Comment by EricB84300** [comment]
hi @matu6968 
did you solve your problem ?

**Comment by matu6968** [comment]
> hi @matu6968 
> 
> did you solve your problem ?
> 
> 

Still nope

**Comment by matu6968** [comment]
> hi @matu6968 
> did you solve your problem ?
> 

It seems like i will have to recompile the kernel with android binder support as this kernel skipped the feature from being compiled into the kernel, but Ubuntu devs has specific instructions to compile the kernel so imma hold off from doing that
