### ISSUE TITLE
[BUG] Camera could not use

### ISSUE THREAD

**Issue by LFRon** [waydroid/waydroid#1256]
### Describe the bug

Waydroid could not use camera.I tested on Ubuntu 22.04/23.04/23.10,deepin v23
It could let camera "open" only use OpenCamera and the image is very stuck

### Waydroid version

1.4.1

### Device

Linux Desktop

### Operating System

Ubuntu 22.04

### Kernel version

6.2.0-generic

### Desktop Environment

KDE Plasma 5.27.8

### GPU

Intel UHD Graphics 630

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
User has not provided the requested logs, closing as invalid, can be re-opened when logs provided
