### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tc9990** [waydroid/waydroid#1270]
### Describe the bug

Waydroid Not Opening And when I give command (waydroid show-full-ui) he 
says-Waiting for binder Service Manager...
and after some time-Service Manager never appeared, Failed to access IPlatform service

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

fedora 39 amd64

### Kernel version

6.7.3-200.fc39.x86_64

### Desktop Environment

GNOME

### GPU

AMD A4-3330MX APU with Radeon™ HD Graphics 

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
Closing as user did not provide logs, can be re-opened when user does so.
