### ISSUE TITLE
Waydroid Not Opening

### ISSUE THREAD

**Issue by tc9990** [waydroid/waydroid#1271]
Waydroid Not Opening And when I give command (![Screenshot from 2024-02-08 19-54-17](https://github.com/waydroid/waydroid/assets/159450744/6ff5f331-2c7a-4364-825a-e57cc7049da2)) he
says-Waiting for binder Service Manager...
and after some time-Service Manager never appeared, Failed to access IPlatform service

**Comment by rastarr** [comment]
did you find a solution to this? I get the same and very frustrated now :)

**Comment by devmmk** [comment]
i have same issues on archlinx, i installed waydroid and binder module with paru
and 

```
penguin@arch ~> sudo modprobe --first-time binder
modprobe: ERROR: could not insert 'binder': Module already in kernel
```

**Comment by Quackdoc** [comment]
We have an issue template, please re-file the issue with the template
