### ISSUE TITLE
[BUG] Waydroid prop options command is not executed

### ISSUE THREAD

**Issue by Snegest** [waydroid/waydroid#1272]
### Describe the bug

Hello. I try to execute " sudo waydroid prop set persist.waydroid.suspend false" in terminal, but terminal returns "waydroid session is stoped" although waydroid is on run

### Waydroid version

lineage_waydroid_x86_64-userdebug 11 RQ3A.211001.001 73 test-keys

### Device

Linux Desktop

### Operating System

Ubuntu 22.04.03 LTS

### Kernel version

6.5.0-17-generic

### Desktop Environment

GNOME 42.9

### GPU

Mesa Intel® Graphics (ADL GT2)

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by YogSottot** [comment]
waydroid prop set must be run without sudo

**Comment by Quackdoc** [comment]
answered
