### ISSUE TITLE
[BUG]: Games does not work

### ISSUE THREAD

**Issue by akashKarmakar02** [waydroid/waydroid#1274]
### Describe the bug

I tried installing Clash of clans and aspholt 9. While Clash of clans refuse to open. Aspholt 9 opens but after starting a race after some mins it shots down. Some good notes minecraft and other sames i tried works.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 39

### Kernel version

Linux 6.6.14-200.fc39.x86_64

### Desktop Environment

Gnome 45

### GPU

AMD Radeon Vega 3

### Logs

(003624) [21:31:17] waydroidclipboard: Received transaction: 2
(003624) [21:31:17] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:03] waydroidclipboard: Received transaction: 2
(003624) [21:34:03] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:10] waydroidclipboard: Received transaction: 2
(003624) [21:34:10] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:10] waydroidclipboard: Received transaction: 2
(003624) [21:34:10] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:23] waydroidclipboard: Received transaction: 2
(003624) [21:34:23] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:29] waydroidclipboard: Received transaction: 2
(003624) [21:34:29] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:34:34] waydroidclipboard: Received transaction: 2
(003624) [21:34:34] Copy failed. wl-paste returned code: 1 Stderr: b'Nothing is copied\n' Stdout: b''
(003624) [21:37:29] waydroidusermonitor: Received transaction: 2
(003624) [21:38:13] waydroidusermonitor: Received transaction: 2
(000918) [21:41:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000918) [21:41:57] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(000918) [21:41:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000918) [21:41:57] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(000918) [21:41:57] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000918) [21:41:57] % umount /var/lib/waydroid/rootfs/vendor
(000918) [21:41:57] % umount /var/lib/waydroid/rootfs/vendor
(000918) [21:41:57] % umount /var/lib/waydroid/rootfs
(000918) [21:41:57] % umount /var/lib/waydroid/rootfs
(020168) [23:57:21] Starting waydroid session
(000918) [23:57:21] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(000918) [23:57:22] % chmod 777 -R /dev/dri
(000918) [23:57:22] % chmod 777 -R /dev/fb0
(000918) [23:57:22] % chmod 777 -R /dev/video0
(000918) [23:57:22] % chmod 777 -R /dev/video1
(000918) [23:57:22] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000918) [23:57:22] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000918) [23:57:22] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(000918) [23:57:22] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000918) [23:57:22] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(000918) [23:57:22] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000918) [23:57:22] Save config: /var/lib/waydroid/waydroid.cfg
(000918) [23:57:22] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000918) [23:57:22] New background process: pid=20250, output=background
(000918) [23:57:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000918) [23:57:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000918) [23:57:22] waiting 10 seconds for container to start...
(020168) [23:57:36] waydroidusermonitor: Received transaction: 1
(020168) [23:57:36] Android with user 0 is ready
(024567) [00:04:08] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(024567) [00:04:08] *** output passed to waydroid stdout, not to this log ***
(020168) [00:13:05] waydroidusermonitor: Received transaction: 2
(027131) [00:18:11] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(027131) [00:18:11] *** output passed to waydroid stdout, not to this log ***

**Comment by artswithastriya** [comment]
Would you like to provide the logcat? When reproducing the issue, run `sudo waydroid logcat`.

Waydroid's log itself doesn't tell a lot about specific compatibility issues, as things such as app logs and crash logs go to Android's logcat instead.

**Comment by Quackdoc** [comment]
User has not responded with correspondence, closing as stale
