### ISSUE TITLE
[BUG] Sonos App keeps crashing

### ISSUE THREAD

**Issue by RandomLegend** [waydroid/waydroid#1275]
### Describe the bug

There are some apps that keep on crashing on me, for example Lightroom for Android but also the Sonos App (S2 in particular). Opening them, immediately closes them and gives the android warning that it keeps on crashing.

I used libndk to install ARM virtualization if that makes a difference. GApps is also installed.

Can someone help me troubleshoot this? I have no idea where i would even begin....

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Garuda-Linux

### Kernel version

6.7.4-zen1-1-zen

### Desktop Environment

Hyprland

### GPU

NVidia 3070

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

[Logs.zip](https://github.com/waydroid/waydroid/files/14234126/Logs.zip)

**Comment by Servail** [comment]
Try libhoudini. I've got some app (Mecha Champions) crashing immediately with libndk, but running with libhoudini on AMD, though performance is really bad (Subway Surf got worse too). Nodataperm hack from waydroid-script applied, further investigations needed.

**Comment by Quackdoc** [comment]
User has not responded with correspondence, closing as stale
