### ISSUE TITLE
[BUG] Can't install this Online Shopping App (Daraz)

### ISSUE THREAD

**Issue by WreckageBrother** [waydroid/waydroid#1277]
### Describe the bug

Can't install this Online Shopping App

https://play.google.com/store/apps/details?id=com.daraz.android

Any way to make it work?

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

SteamOS 3.5.7

### Kernel version

6.1.52-valve9-1-neptune-61

### Desktop Environment

KDE

### GPU

AMD Van Gogh

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
User has not responded with correspondence after being given something to try, closing as stale, can be re-opened if needed
