### ISSUE TITLE
Apps thinking there is no internet.

### ISSUE THREAD

**Issue by Quget** [waydroid/waydroid#129]
Hello,

I have been trying out Waydroid on my **Volla Phone** with **Ubuntu Touch**.
It is currently running Discord and WhatsApp really well. 

But when I tried to use the Dutch "[CoronaCheck](https://play.google.com/store/apps/details?id=nl.rijksoverheid.ctr.holder&hl=en_US&gl=US)" app I get an error after signing in trough a website (It sends me back to the app) that it failed to connect with the internet. While obviously I do have a working internet connection.

My guess is that the app checks if you have mobile network connection or a wi-fi connection and that check fails.

**Comment by bunglesss** [comment]
Is there some way to force the Android network connection status? I'm getting this as well with the BBC Go Explore kids app. Weirdly, their Playtime Island app works fine and can download games.

**Comment by aleasto** [comment]
Some applications test specifically for a Wifi connection.
This is now possible with `persist.waydroid.fake_wifi`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour

**Comment by bunglesss** [comment]
Doesn't seem to have helped with that BBC game sadly.

**Comment by 0-st** [comment]
> Some applications test specifically for a Wifi connection. This is now possible with `persist.waydroid.fake_wifi`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour

Made no difference at all
