### ISSUE TITLE
[BUG] Pikmin Bloom and Nintendo Switch Online fail to login via Nintendo account

### ISSUE THREAD

**Issue by lat9nq** [waydroid/waydroid#1295]
### Describe the bug

Starting apps that require these accounts works as far as I've tested (Pikmin Bloom, Nintendo Switch Online). After following through with the login prompt, the web browser opens up, and I select my Nintendo account that I've already logged into previously. The app in question returns to focus, tries to login, then an error happens. NSO gracefully handles the error, creates an error prompt, and throws me back to the beginning of the setup process. Pikmin Bloom crashes outright.

To throw a wrench in the whole charade, Pokemon HOME works fine through and through.

This is a fairly fresh install of Fedora and thus Waydroid. I had to install Pikmin Bloom and Pokemon HOME through Aurora Store 4.2.5, since newer versions of Aurora don't work (an Issue exists for this iirc), and the Play Store won't let me install these apps on this device.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 39

### Kernel version

6.7.5-200.fc39.x86_64

### Desktop Environment

GNOME 40

### GPU

Intel DG2 [Arc A380]

### Logs

[240227_waydroid_logs_all.tar.gz](https://github.com/waydroid/waydroid/files/14415866/240227_waydroid_logs_all.tar.gz)

**Comment by lat9nq** [comment]
Opened the Issue because I couldn't find any other resources relating to these apps, but maybe I was looking in the wrong places? The ominous number of Issues that have no response compels me to say I'd be happy if another user has any experience with any of this and can comment.

**Comment by Quackdoc** [comment]
Please don't tar the logs, However you can try fake wifi https://docs.waydro.id/usage/waydroid-prop-options , Please re-upload logs in their file form

**Comment by Quackdoc** [comment]
User has not replied, closing as stale, issue can be re-opened if necessary
