### ISSUE TITLE
[Feature] Can we use google's official emulator's images?

### ISSUE THREAD

**Issue by tiziodcaio** [waydroid/waydroid#1298]
### Is your feature request related to a problem? Please describe.

I'm aware we need some hacks to run waydroid, but it is an interesting proposal if we find a way to run official google images on waydroid.

### Describe the solution you'd like.

Is a proposal, it might not exist any solution!

### Describe alternatives you've considered.

keep everything as it is

**Comment by aleasto** [comment]
Short answer: no.

Long answer: it would be nice if it were possible to use a GSI and just the vendor.img from waydroid, but that's not the case today and I don't see it being the case anytime soon

**Comment by beedell-roke** [comment]
@tiziodcaio, if this issue refers to GSIs, see [`issues/2116`](https://github.com/waydroid/waydroid/issues/2116#issue-3603657294).
