### ISSUE TITLE
[BUG] ERROR: WayDroid is not initialized, run "waydroid init"

### ISSUE THREAD

**Issue by Bushido1** [waydroid/waydroid#1299]
### Describe the bug

"waydroid session start" gives "ERROR: WayDroid is not initialized, run "waydroid init"".
"sudo waydroid init" gives "Already initialized".

I have used https://computingforgeeks.com/run-android-operating-system-on-linux-using-waydroid/, https://waydro.id/?ref=itsfoss.com#install and https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04 LTS 64-bit

### Kernel version

6.5.0-21-generic

### Desktop Environment

GNOME 42.9

### GPU

AMD® A4-4300m apu with radeon(tm) hd graphics × 2

### Logs

How to get the required logs if waydroid is having issues to execute due to the aforementioned errors?

**Comment by Quackdoc** [comment]
run `sudo waydroid init -f` to force it, if it still somehow goes wrong you can entirely wipe out waydroid using `sudo rm -rf /var/lib/waydroid /home/.waydroid ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid` and try again

**Comment by Braido350** [comment]
siga o passo a passo deste cara aqui que vai resolver o seu problema https://www.youtube.com/watch?v=k_eMzlHBXiA
resolveu no meu

**Comment by Bushido1** [comment]
I solved it by uninstalling WayDroid and after 3 months I installed WayDroid again. Then I got stuck in the initilization process when the install dialogue was extracting MAINSTREAM .iso file. I left the dialogue open for 30 minutes, closed it without the green "Done" button next to "Download" button in the install dialogue. After that WayDroid opened a working Android.
