### ISSUE TITLE
Arch linux and linux zen support

### ISSUE THREAD

**Issue by Saim20** [waydroid/waydroid#13]
I'm running arch linux with linux-zen > 5.13. It has binder and ashmem built into the kernel,, not as modules.

The install script installs fine, but when trying to start the container, says binder_linux and ashmem_linux not found. Tried commenting out the 'exit' line in nodes check, but doesn't work and gives a lot of errors. I'll update with the error messages....

**Comment by sickcodes** [comment]
`aur/linux-zen-anbox` & `aur/linux-zen-anbox-headers` are currently flagged out of date, but will still work.

Notably, when you boot up, you should work with:

`modprobe binder_linux devices=binder,hwbinder,vndbinder`

aur/linux-xanmod-anbox aur/linux-xanmod-anbox-headers have worked for me in the past.

I was able to run _Antique_ Anbox using the AUR packages (non-zen).

But also Redroid using the AUR repos https://github.com/remote-android/redroid-modules

In the end, swapping kernels every day annoyed the crap out of me and I shoved it into QEMU 6, but this project feels promising!

@erfanoabdi are you planning on making an AUR package? If not, would you like me to maintain one?

**Comment by sickcodes** [comment]
See https://github.com/Anbox-halium/anbox-halium/pull/10/files/f1df7384df05adab5a97f679120ac3745ec99fe0#diff-2fb062b92e5dd0b0e2e1944badc2f5d918a60d5973de5be5ff484eedcfa345a5R18
```bash
    modprobe binder_linux devices="anbox-binder,anbox-hwbinder,anbox-vndbinder"
    modprobe ashmem_linux
```

**Comment by Saim20** [comment]
` linux-zen ` has ` binder-linux ` and ` ashmem_linux ` built into the kernel. ` anbox-git ` in the AUR works with it. But ` modprobe ` says no module named binder_linux and ashmem_linux.

I also tried ` linux-xanmod-anbox ` with the headers. But that also gives the ` binder nodes not found ` error while running ` run_container.sh `.

I don't really understand much about binder and ashmem. So, maybe you got something out of this?

**Comment by sickcodes** [comment]
Check the output of these:
```bash
grep binder /proc/filesystems # output should like: nodev	binder
grep ashmem /proc/misc # output should like: 56 ashmem
```

If you get nothing, the modules are not loaded. I will try Linux Zen Anbox today

**Comment by sickcodes** [comment]
However, they've been out of date since February, so the AUR packages are probably broken.

As expected, they are broken, see comments: https://aur.archlinux.org/packages/linux-zen-anbox/

In any case, choose `linux-git` or `linux-git`

```
RC=5.13.6
RC="${RC//\-/}"
cd ~
sudo pacman -Rns linux-git
yay linux-git --getpkgbuild --force
cd ~/linux-git

# remove html docs
sed -i -e 's/\"\$pkgbase-docs\"//' PKGBUILD
sed -i -e 's/rm\ -r\ \"\$builddir\/Documentation\"//' PKGBUILD
sed -i -e 's/make\ htmldocs//' PKGBUILD
# sed -i -e 's/make\ /make\ -j'${N}'\ /g' PKGBUILD
sed -i -e 's/^pkgver\=.*/pkgver\='${RC}'/' PKGBUILD
sed -i -e 's/^pkgver\=.*/pkgver\='${RC}'/' PKGBUILD

# MANUALLY EDIT OUT THE SKIP SHASUMS TO SKIP

sed -i -e s/^sha256sums/old_sha256sums/g PKGBUILD

perl -i -p -e s/old_sha256sums/sha256sums\=\(\'SKIP\'\ \'SKIP\'\)\\nold_sha256sums/g PKGBUILD

zcat /proc/config.gz  > config

tee -a config <<EOF
CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
EOF

makepkg -si
```

Or change the above to `-zen` where appropriate.

Change the y to m if you want modules, as mentioned by someone on the AUR: https://aur.archlinux.org/pkgbase/linux-zen-anbox/#comment-790375

**Comment by erfanoabdi** [comment]
> @erfanoabdi are you planning on making an AUR package? If not, would you like me to maintain one?

i don't have any plan for aur but definitely not with current stage 
we should rebrand to waydroid and update many things first

**Comment by Saim20** [comment]
> Check the output of these:
> 
> ```shell
> grep binder /proc/filesystems # output should like: nodev	binder
> grep ashmem /proc/misc # output should like: 56 ashmem
> ```
> 
> If you get nothing, the modules are not loaded. I will try Linux Zen Anbox today

The modules are loaded,, outputs are as expected.

And I guess you could make them work on ```linux-zen``` instead of ```linux-zen-anbox``` building a kernel everytime i need to update is kinda hassle. There should be a way to use binder and ashmem without them explicitly being there as modules shoudn't there?

**Comment by sickcodes** [comment]
> > Check the output of these:
> 
> > 
> 
> > ```shell
> 
> > grep binder /proc/filesystems # output should like: nodev	binder
> 
> > grep ashmem /proc/misc # output should like: 56 ashmem
> 
> > ```
> 
> > 
> 
> > If you get nothing, the modules are not loaded. I will try Linux Zen Anbox today
> 
> 
> 
> The modules are loaded,, outputs are as expected.
> 
> 
> 
> And I guess you could make them work on ```linux-zen``` instead of ```linux-zen-anbox``` building a kernel everytime i need to update is kinda hassle. There should be a way to use binder and ashmem without them explicitly being there as modules shoudn't there?

Just do similar to above with Linux-zen-git but change =m to =y

**Comment by Saim20** [comment]
> Just do similar to above with Linux-zen-git but change =m to =y
To be sure.. How much time can it take to build?

**Comment by sickcodes** [comment]
> > Just do similar to above with Linux-zen-git but change =m to =y
> 
> 
> 
> I guess I'll just stick to ``` linux-zen-anbox ``` or ``` linux-xanmod-anbox ```. I can't afford the luxury to build a kernel myself🙂
> 
> 

I know the feeling 😂 takes like 30 minutes each time to build

**Comment by Saim20** [comment]
> > > Just do similar to above with Linux-zen-git but change =m to =y
> > 
> > 
> > I guess I'll just stick to `linux-zen-anbox` or `linux-xanmod-anbox`. I can't afford the luxury to build a kernel myselfslightly_smiling_face
> 
> I know the feeling joy takes like 30 minutes each time to build

30 minutes for me would've been a blessing

**Comment by sickcodes** [comment]
> > > > Just do similar to above with Linux-zen-git but change =m to =y
> 
> > > 
> 
> > > 
> 
> > > I guess I'll just stick to `linux-zen-anbox` or `linux-xanmod-anbox`. I can't afford the luxury to build a kernel myselfslightly_smiling_face
> 
> > 
> 
> > I know the feeling joy takes like 30 minutes each time to build
> 
> 
> 
> Anyways, ```linux-xanmod-anbox``` still gives binder nodes error. I wish I were a bash script professional

Make sure you reboot into the right kernel and then `modprobe ...` the modules above.

I am still working out how to boot this anyways 😂

**Comment by xavier83** [comment]
If anyone succeeded, please provide some instructions/steps to follow to get it working on arch. Thanks :smile:

**Comment by atmouse-** [comment]
1. Build and install custom kernel from [aur](https://aur.archlinux.org/cgit/aur.git/tree/config?h=linux-mainline)

> DONT forget enable this config
```
CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
CONFIG_SW_SYNC=y
CONFIG_UHID=m
```

2. Add grub or systemd-boot with kernel boot parameter `binder.devices=binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder`

3. `pacman -S lxc sway dhcp` and login sway session

4. `mkdir -p /var/lib/lxc/anbox` then touch this files

/var/lib/lxc/anbox/anbox.prop
```
anbox.display_height=1440
anbox.display_width=810
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
debug.stagefright.ccodec=0
ro.sf.lcd_density=160
anbox.xdg_runtime_dir=/run/user/1000
anbox.wayland_display=wayland-1
anbox.stub_sensors_hal=1
#anbox.use_subsurface=false
persist.anbox.multi_windows=false
anbox.active_apps=full
```

/var/lib/lxc/anbox/bootstrap.sh
```
#!/bin/sh

mount -o rw /var/lib/lxc/anbox/anbox_x86_64_system.img /var/lib/lxc/anbox/rootfs
mount -o rw /var/lib/lxc/anbox/anbox_x86_64_vendor.img /var/lib/lxc/anbox/rootfs/vendor
mount -o bind /var/lib/lxc/anbox/anbox.prop /var/lib/lxc/anbox/rootfs/vendor/anbox.prop
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_SESSION_TYPE=wayland
export WAYLAND_DISPLAY=wayland-1
chmod 777 /sys/kernel/debug/sync/sw_sync
chmod 777 -R /run/user/1000
chmod -R 777 /dev/binderfs/*
chmod -R 777 /dev/fb0
chmod -R 777 /dev/dri/
chmod -R 777 /dev/uhid
chmod -R 777 /dev/zero
chmod -R 777 /dev/full
chmod -R 777 /dev/null
chmod -R 777 /dev/ashmem
chmod -R 777 /dev/fuse
chmod -R 777 /dev/char
```

/var/lib/lxc/anbox/config
```
# Anbox LXC Config

lxc.rootfs.path = dir:/var/lib/lxc/anbox/rootfs
lxc.uts.name = anbox
lxc.arch = x86_64
lxc.autodev = 0
lxc.apparmor.profile = unconfined

lxc.init.cmd = /init

lxc.mount.auto = cgroup:rw sys:ro proc

lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = anbox0
lxc.net.0.name = eth0
lxc.net.0.hwaddr = 00:16:3e:f9:d3:03
lxc.net.0.mtu = 1500

# Necessary dev nodes
lxc.mount.entry = tmpfs dev tmpfs nosuid 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file,optional 0 0
lxc.mount.entry = /dev/full dev/full none bind,create=file,optional 0 0
lxc.mount.entry = /dev/null dev/null none bind,create=file,optional 0 0
lxc.mount.entry = /dev/ashmem dev/ashmem none bind,create=file,optional 0 0
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
####lxc.mount.entry = /dev/ion dev/ion none bind,create=file,optional 0 0
lxc.mount.entry = /dev/char dev/char none bind,create=dir,optional 0 0

##### Graphic dev nodes
lxc.mount.entry = /dev/fb0 dev/fb0 none bind,create=file,optional 0 0
lxc.mount.entry = /dev/dri dev/dri none bind,create=dir,optional 0 0
####
##### Binder dev nodes
lxc.mount.entry = /dev/binderfs/anbox-binder dev/binder none bind,create=file 0 0
lxc.mount.entry = /dev/binderfs/anbox-vndbinder dev/vndbinder none bind,create=file 0 0
lxc.mount.entry = /dev/binderfs/anbox-hwbinder dev/hwbinder none bind,create=file 0 0

# Necessary device nodes for adb
lxc.mount.entry = none dev/pts devpts defaults,mode=644,ptmxmode=666,create=dir 0 0
lxc.mount.entry = /dev/uhid dev/uhid none bind,create=file,defaults,optional 0 0

# Mount /data
lxc.mount.entry = tmpfs mnt tmpfs mode=0755,uid=0,gid=1000
lxc.mount.entry = /var/lib/lxc/anbox/data data none bind 0 0

# Recursive mount /run to provide necessary host sockets
lxc.mount.entry = /run run none rbind,create=dir 0 0

# Necessary sw_sync node for HWC
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0

lxc.hook.post-stop = /dev/null
```

/etc/dhcpd.anbox.conf
```
option domain-name-servers 8.8.8.8;
option subnet-mask 255.255.255.0;
option routers 192.168.250.1;
subnet 192.168.250.0 netmask 255.255.255.0 {
  range 192.168.250.150 192.168.250.250;
}
```

5. Download and extract android image [latest-raw-images.zip](https://build.lolinet.com/file/lineage/anbox_x86_64/) to /var/lib/lxc/anbox/

6. Run

```
bash /var/lib/lxc/anbox/bootstrap.sh
ip link add name anbox0 type bridge
ip link set dev anbox0 up
dhcpd -4 -q -cf /etc/dhcpd.anbox.conf --no-pid anbox0
lxc-start -n anbox -F -- /init
```

THAT IS IT

**Comment by allaeddineomc** [comment]
thi image isn't mounting and i'm getting this 
'mount: /var/lib/lxc/anbox/rootfs: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.'

**Comment by sickcodes** [comment]
Boot with kernel args in comment above. Works in X11 too @atmouse- thank you!

```bash
#!/bin/bash
# Author:       atmouse-, sickcodes
# Contact:      https://github.com/atmouse-, https://github.com/sickcodes
# Copyright:    sickcodes (C) 2021
# License:      GPLv3+

# wayfire
# DISPLAY=:1 bash ~/start-waydroid.sh

which dhcpd || pacman -S dhcp --nonconfirm

sudo mkdir -p /var/lib/lxc/anbox/rootfs \
    /var/lib/lxc/anbox/data

sudo touch /var/lib/lxc/anbox/anbox.prop \
    /var/lib/lxc/anbox/bootstrap.sh \
    /var/lib/lxc/anbox/config \
    /etc/dhcpd.anbox.conf

sudo tee /var/lib/lxc/anbox/anbox.prop <<EOF
anbox.display_height=720
anbox.display_width=405
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
debug.stagefright.ccodec=0
ro.sf.lcd_density=160
anbox.xdg_runtime_dir=/run/user/1000
anbox.wayland_display=wayland-1
anbox.stub_sensors_hal=1
#anbox.use_subsurface=false
persist.anbox.multi_windows=false
anbox.active_apps=full
EOF

sudo tee /var/lib/lxc/anbox/bootstrap.sh <<EOF
#!/bin/sh

mount -o rw /var/lib/lxc/anbox/anbox_x86_64_system.img /var/lib/lxc/anbox/rootfs
mount -o rw /var/lib/lxc/anbox/anbox_x86_64_vendor.img /var/lib/lxc/anbox/rootfs/vendor
mount -o bind /var/lib/lxc/anbox/anbox.prop /var/lib/lxc/anbox/rootfs/vendor/anbox.prop
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_SESSION_TYPE=wayland
export WAYLAND_DISPLAY=wayland-1
chmod 777 /sys/kernel/debug/sync/sw_sync
chmod 777 -R /run/user/1000 || true
chmod -R 777 /dev/binderfs/*
chmod -R 777 /dev/fb0
chmod -R 777 /dev/dri/
chmod -R 777 /dev/uhid
chmod -R 777 /dev/zero
chmod -R 777 /dev/full
chmod -R 777 /dev/null
chmod -R 777 /dev/ashmem
chmod -R 777 /dev/fuse
chmod -R 777 /dev/char
EOF

sudo tee /var/lib/lxc/anbox/config <<EOF
# Anbox LXC Config

lxc.rootfs.path = dir:/var/lib/lxc/anbox/rootfs
lxc.uts.name = anbox
lxc.arch = x86_64
lxc.autodev = 0
lxc.apparmor.profile = unconfined

lxc.init.cmd = /init

lxc.mount.auto = cgroup:rw sys:ro proc

lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = anbox0
lxc.net.0.name = eth0
lxc.net.0.hwaddr = 00:16:3e:f9:d3:03
lxc.net.0.mtu = 1500

# Necessary dev nodes
lxc.mount.entry = tmpfs dev tmpfs nosuid 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file,optional 0 0
lxc.mount.entry = /dev/full dev/full none bind,create=file,optional 0 0
lxc.mount.entry = /dev/null dev/null none bind,create=file,optional 0 0
lxc.mount.entry = /dev/ashmem dev/ashmem none bind,create=file,optional 0 0
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
####lxc.mount.entry = /dev/ion dev/ion none bind,create=file,optional 0 0
lxc.mount.entry = /dev/char dev/char none bind,create=dir,optional 0 0

##### Graphic dev nodes
lxc.mount.entry = /dev/fb0 dev/fb0 none bind,create=file,optional 0 0
lxc.mount.entry = /dev/dri dev/dri none bind,create=dir,optional 0 0
####
##### Binder dev nodes
lxc.mount.entry = /dev/binderfs/anbox-binder dev/binder none bind,create=file 0 0
lxc.mount.entry = /dev/binderfs/anbox-vndbinder dev/vndbinder none bind,create=file 0 0
lxc.mount.entry = /dev/binderfs/anbox-hwbinder dev/hwbinder none bind,create=file 0 0

# Necessary device nodes for adb
lxc.mount.entry = none dev/pts devpts defaults,mode=644,ptmxmode=666,create=dir 0 0
lxc.mount.entry = /dev/uhid dev/uhid none bind,create=file,defaults,optional 0 0

# Mount /data
lxc.mount.entry = tmpfs mnt tmpfs mode=0755,uid=0,gid=1000
lxc.mount.entry = /var/lib/lxc/anbox/data data none bind 0 0

# Recursive mount /run to provide necessary host sockets
lxc.mount.entry = /run run none rbind,create=dir 0 0

# Necessary sw_sync node for HWC
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0

lxc.hook.post-stop = /dev/null
EOF

sudo tee /etc/dhcpd.anbox.conf <<EOF
option domain-name-servers 8.8.8.8;
option subnet-mask 255.255.255.0;
option routers 192.168.250.1;
subnet 192.168.250.0 netmask 255.255.255.0 {
    range 192.168.250.150 192.168.250.250;
}
EOF

touch ~/start-waydroid.sh

chmod +x ~/start-waydroid.sh

tee ~/start-waydroid.sh <<EOF
#!/bin/bash
sudo chmod +x /var/lib/lxc/anbox/bootstrap.sh

cd /var/lib/lxc/anbox

[[ -e latest-raw-images.zip ]] \
  || { wget https://build.lolinet.com/file/lineage/anbox_x86_64/latest-raw-images.zip && unzip latest-raw-images.zip ; }

sudo bash /var/lib/lxc/anbox/bootstrap.sh
sudo ip link add name anbox0 type bridge
sudo ip link set dev anbox0 up
sudo dhcpd -4 -q -cf /etc/dhcpd.anbox.conf --no-pid anbox0
sudo lxc-start -n anbox -F -- /init
EOF


# chmod +x /var/lib/lxc/anbox/bootstrap.sh

# cd /var/lib/lxc/anbox

# [[ -e latest-raw-images.zip ]] \
#   || { wget https://build.lolinet.com/file/lineage/anbox_x86_64/latest-raw-images.zip && unzip latest-raw-images.zip ; }

# bash /var/lib/lxc/anbox/bootstrap.sh
# ip link add name anbox0 type bridge
# ip link set dev anbox0 up
# dhcpd -4 -q -cf /etc/dhcpd.anbox.conf --no-pid anbox0
# lxc-start -n anbox -F -- /init


```

**Comment by NXij** [comment]
It was also complaining about missing binder for me, on the latest zen kernel from the arch repo.
Did this
`sudo mkdir /dev/binderfs & sudo mount -t binder binder /dev/binderfs`
and it was okay and the container starts up, aswell as the graphical userspace (Wayfire with Nouveau, propietary nvidia Wayfire broken)

Network however not bridging through, will have to look at it...
anbox0 interface up and eth8@if9 on guest also up but no ip...

**Comment by sickcodes** [comment]
> It was also complaining about missing binder for me, on the latest zen kernel from the arch repo.
> Did this (including the kernel boot option flags from previous posts)
> `sudo mkdir /dev/binderfs & sudo mount -t binder binder /dev/binderfs`
> and it was okay and the container starts up, aswell as the graphical userspace (Wayfire with Nouveau, propietary nvidia Wayfire broken)
> 
> The official python script does not want to init.
> 
> Network however not bridging through, will have to look at it...
> anbox0 interface up and eth8@if9 on guest also up but no ip...
> The anbox network script from arch wiki worked

Thanks @NXij, yeah I remember it wasn't working randomly, but then it started working when I mounted binder. 

I put all the instructions for Arch here: https://github.com/sickcodes/droid-native

Will turn into an AUR, maybe even put prebuilt kernels (or the modules) back into the AUR as it's very annoying to rebuild constantly.

**Comment by sickcodes** [comment]
@NXij FYI I changed to BRIDGE=lxcbr0 as that bridge is already set up with lxc, see: https://github.com/sickcodes/droid-native#wipe-existing-waydroidlineagebliss-data--droid-native

**Comment by frap129** [comment]
Trying to get waydroid working on a similar configuration, ut `sudo ip link add name waydroid0 type bridge` returns
`Error: Unknown device type`
According to `man ip-link`, bridge is a default type. Any of the smart people is this thread have any idea why bridge isnt a known type?

**Comment by NXij** [comment]
@frap129 take a look at the fresh `waydroid` package on AUR. Manages to bring up to network for me.

**Comment by frap129** [comment]
@NXij Guess I asked too soon, I just checked my kernel config and found that CONFIG_BRIDGE wasn't enabled, likely the cause. I am using the waydroid AUR package tho

**Comment by sickcodes** [comment]
Use lxcbr0 instead

**Comment by sickcodes** [comment]
For anyone reading as closed: https://aur.archlinux.org/packages/waydroid/

**Comment by austinrojers** [comment]
Choose a kernel from here: List of Arch Linux Kernels patched for Anbox .
    Anbox works with following kernels :-

    linux-zen (it is in the Arch Official Repositories),
    linux-tkg-bmq (it is in the chaotic-aur for Garuda users),
    linux-cacule (it is in the chaotic-aur for Garuda users,
    for more details refer:https://forum.garudalinux.org/t/linux-cacule-feedback-testing)
    linux-xanmod-anbox (it is in the chaotic-aur for Garuda users),
    [Anbox doesn't work with linux-lts]
    However, you could use any of the kernels from the above link and follow similar steps to install the kernel and the corresponding kernel header.

    To install the Xanmod kernel:
    sudo pacman -S linux-xanmod-anbox linux-xanmod-anbox-headers
    or
    To install the Zen Kernel:
    sudo pacman -S linux-zen linux-zen-headers
    or
    To install Linux-tkg-bmq:
    sudo pacman -S linux-tkg-bmq linux-tkg-bmq-headers
    or
    To install Linux-cacule:
    sudo pacman -S linux-cacule linux-cacule-headers

    Reboot and choose the patched kernel that you just installed

    Setting up Kernel Modules:

i) To enable module loading at boot, create a file inside /etc/modules-load.d/, which contains the lines:
(sudo nano /etc/modules-load.d/anbox.conf)

/etc/modules-load.d/anbox.conf

ashmem_linux
binder_linux

(Save and exit)

ii) Load Modules: sudo modprobe -a binder-linux ashmem-linux
(You can skip this step for linux-tkg-bmq)

iii) To enable creating mount point of binderfs at boot, create a file in /etc/tmpfiles.d/ with the content:
(sudo nano /etc/tmpfiles.d/anbox.conf)

/etc/tmpfiles.d/anbox.conf

d! /dev/binderfs 0755 root root

(Save and exit)

iv) Mount binderfs:

    sudo mkdir -p /dev/binderfs
    sudo mount -t binder none /dev/binderfs

v) To enable mounting binderfs at boot, add a line in the fstab. Using the option nofail here will not greet you with a recovery shell when you are booting a kernel without binderfs support (such as the standard kernel).:
(sudo nano /etc/fstab)

/etc/fstab

none                         /dev/binderfs binder   nofail  0      0

    To check modules status:
    sudo ls -1 /dev/{ashmem,binderfs}

    This should work here.
