### ISSUE TITLE
Extremely poor performance on amdgpu

### ISSUE THREAD

**Issue by doragasu** [waydroid/waydroid#1307]
### Describe the bug

I have waydroid running on an i7-7600 laptop with pretty decent performance, and tried installing on a much more powerful desktop (Ryzen 3700-X, AMD RX-5700 GPU, 32 GB RAM). Waydroid works, but games like DOORS on Roblox are unplayable, there is constant stuttering.

OS is the same on both setups (laptop and desktop). I have searched if maybe I have to do something for this to work better on AMD GPUs but did not find anything. Am I doing anything wrong?

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

ArchLinux

### Kernel version

6.7.8-zen1-1-zen

### Desktop Environment

sway 1:1.9

### GPU

AMD Radeon RX-5700

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1708751846
vendor_datetime = 1709378634
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
ro.product.cpu.abilist = x86_64,x86,arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32 = x86,armeabi-v7a,armeabi
ro.product.cpu.abilist64 = x86_64,arm64-v8a
ro.dalvik.vm.native.bridge = libhoudini.so
ro.enable.native.bridge.exec = 1
ro.vendor.enable.native.bridge.exec = 1
ro.vendor.enable.native.bridge.exec64 = 1
ro.ndk_translation.version = 0.2.3
ro.dalvik.vm.isa.arm = x86
ro.dalvik.vm.isa.arm64 = x86_64
```
/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=minigbm_gbm_mesa
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.cpu.abilist=x86_64,x86,arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.dalvik.vm.native.bridge=libhoudini.so
ro.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec64=1
ro.ndk_translation.version=0.2.3
ro.dalvik.vm.isa.arm=x86
ro.dalvik.vm.isa.arm64=x86_64
waydroid.host.user=pablo
waydroid.host.uid=1001
waydroid.host.gid=1002
waydroid.host_data_path=/home/pablo/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1001
waydroid.pulse_runtime_path=/run/user/1001/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=minigbm_gbm_mesa
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.cpu.abilist=x86_64,x86,arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.dalvik.vm.native.bridge=libhoudini.so
ro.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec=1
ro.vendor.enable.native.bridge.exec64=1
ro.ndk_translation.version=0.2.3
ro.dalvik.vm.isa.arm=x86
ro.dalvik.vm.isa.arm64=x86_64
```
/var/lib/waydroid/waydroid.log
```
(003890) [19:09:09] Starting waydroid session
(000796) [19:09:09] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(000796) [19:09:09] % systemctl is-active -q nfcd
(000796) [19:09:09] % chmod 777 -R /dev/dri
(000796) [19:09:09] % chmod 777 -R /dev/fb0
(000796) [19:09:09] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000796) [19:09:09] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000796) [19:09:09] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(000796) [19:09:09] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000796) [19:09:09] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(000796) [19:09:09] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000796) [19:09:09] Save config: /var/lib/waydroid/waydroid.cfg
(000796) [19:09:09] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000796) [19:09:09] New background process: pid=3928, output=background
(000796) [19:09:09] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000796) [19:09:09] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
RUNNING
(000796) [19:09:09] waiting 10 seconds for container to start...
(003890) [19:09:10] Skipping clipboard manager service because of missing pyclip package
(003890) [19:09:18] waydroidusermonitor: Received transaction: 1
(003890) [19:09:18] Android with user 0 is ready
(003890) [19:09:18] % adb start-server
(003890) [19:09:18] % adb connect 192.168.240.112
already connected to 192.168.240.112:5555
(003890) [19:09:18] Established ADB connection to Waydroid device at 192.168.240.112.
(003890) [19:10:59] Clipboard service is not even started
(000796) [19:10:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
```

**Comment by electrikjesus** [comment]
You did not mention that you installed a native-bridge solution on top of the Waydroid integration.

**Comment by okias** [comment]
I would hijack this discussion a bit about CI testing. If anyone willing to do some waydroid testing in [Mesa3D CI](https://gitlab.freedesktop.org/mesa/mesa/) I would happily help them. Implementing performance monitoring would be harder, but getting extremely could be easily measurable by job taking too long.

**Comment by doragasu** [comment]
> You did not mention that you installed a native-bridge solution on top of the Waydroid integration. If you must use native-bridge on your install, your AMD CPU works better with Libndk-translation and not libhoudini

Thanks a lot for help. I followed ArchWiki instructions, and installed both `libndk` and `libhoudini`. Maybe I'm missing some documentation, is `libndk` and `libnkd-translation` the same? Or maybe I should keep `libndk` and replace `libhoudini` with `libndk-translation`?

**Comment by electrikjesus** [comment]
Libndk and Libndk-translation are the same. AMD's perform better with only that. Remove libhoudini.

**Comment by doragasu** [comment]
Tried removing libhoudini and Roblox crashes on startup. So I removed everything, reinstaled waydroid and guest OS from scratch, installed only libndk and then Roblox, but unfortunately it does not work, it seems it only works with libhoudini.

So is Roblox on AMD hardware a no-go with waydroid?

**Comment by Glich440** [comment]
If you still want to use Roblox on Linux I would recommend grapejuice, it's a bit of a struggle to actually get working but once it is installed it works quite well.

**Comment by doragasu** [comment]
> If you still want to use Roblox on Linux I would recommend grapejuice, it's a bit of a struggle to actually get working but once it is installed it works quite well.

Thanks for the suggestion. I have used GrapeJuice and also Vinegar in the past. They both worked mostly OK, but [recently Roblox has blocked Wine, so they do not work anymore](https://www.gamingonlinux.com/2024/03/game-over-for-roblox-on-linux-steam-deck-as-its-now-blocked/), and it doesn't seem they will anytime soon. So I was trying Waydroid to see if it could do the job.

**Comment by Kodehawa** [comment]
Outside Roblox, graphics performance on amdgpu is lackluster indeed. It works a lot better with Intel iGPUs, no clue why really.

**Comment by doragasu** [comment]
I'm closing this since I think this performance problem might not be a Waydroid issue. I have tested Bliss OS (booted from a USB drive) and it has the same problem: on my intel laptop performance is decent but on the much more powerful AMD box performance (in Roblox) is terrible. Maybe it's just libhoudini, that behaves poorly on AMD hardware.

**Comment by garhow** [comment]
> Tried removing libhoudini and Roblox crashes on startup. So I removed everything, reinstaled waydroid and guest OS from scratch, installed only libndk and then Roblox, but unfortunately it does not work, it seems it only works with libhoudini.
> 
> So is Roblox on AMD hardware a no-go with waydroid?

I was able to get Roblox working with great performance on AMD GPU by using [libndk-fixer](https://github.com/Slappy826/libndk-fixer).

**Comment by Kodehawa** [comment]
> I'm closing this since I think this performance problem might not be a Waydroid issue. I have tested Bliss OS (booted from a USB drive) and it has the same problem: on my intel laptop performance is decent but on the much more powerful AMD box performance (in Roblox) is terrible. Maybe it's just libhoudini, that behaves poorly on AMD hardware.

Yeah libhoudini works badly on AMD hardware, but sadly ndk is awful even on AMD hardware sometimes. In Azur Lane it tends to just... stop playing animations or just stuttering to hell sometimes, for example. It's a mess, specially considering Windows android emulators can all do the job fine. I imagine it's just a matter of them doing Propietary Changes (tm) to either houdini or ndk, which is rly annoying.

**Comment by ilahazs** [comment]
> > Tried removing libhoudini and Roblox crashes on startup. So I removed everything, reinstaled waydroid and guest OS from scratch, installed only libndk and then Roblox, but unfortunately it does not work, it seems it only works with libhoudini.
> > So is Roblox on AMD hardware a no-go with waydroid?
> 
> I was able to get Roblox working with great performance on AMD GPU by using [libndk-fixer](https://github.com/Slappy826/libndk-fixer).

fyi, this method didnt work anymore on the latest roblox apk
