### ISSUE TITLE
[BUG] Playing video in some apps crashes waydroid

### ISSUE THREAD

**Issue by olly1240** [waydroid/waydroid#1317]
### Describe the bug

This is a "regression" since playing some videos inside waydroid makes the whole guest system crash and previously this was not the case. I personally tested: New Pipe, GrayJay and the LineageOS gallery. I don't think this is app-specific, but some apps seems to handle this better. MPV uses software rendering I think, but plays without crashing android, and the same goes for VLC, the integrated browser and Firefox. I am not currently able to pinpoint the issue and what causes it since I have found no log entries regarding the graphic stack on my pc, that might have indicated a weird interaction with mesa. I am using the binder_linux-dkms module, tested both the previous version (6.7) that was working before, and the current (6.8) version and I can reproduce it on both. The only suspect I currently have is Plasma 6.0.1 that was recently updated, but I am not too convinced about it.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

ArchLinux amd64

### Kernel version

6.7.8-arch1-1

### Desktop Environment

Kde Plasma 6.0.1 (Kwin 6.0.1)

### GPU

AMD Radeon Renoir (Vega igpu), AMD Radeon RX6800M (Navi22 dgpu)

### Logs

/var/lib/waydroid/waydroid.cfg
[waydroid.cfg.txt](https://github.com/waydroid/waydroid/files/14532452/waydroid.cfg.txt)

/var/lib/waydroid/waydroid.prop
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/14532454/waydroid.prop.txt)

/var/lib/waydroid/waydroid_base.prop
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/14532456/waydroid_base.prop.txt)

/var/lib/waydroid/waydroid.log
[waydroid.log](https://github.com/waydroid/waydroid/files/14532459/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt](https://github.com/waydroid/waydroid/files/14532460/logcat.txt)

`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/waydroid/waydroid/files/14532461/dmesg.txt)

**Comment by aleasto** [comment]
`E hwcomposer: Current wayland display doesn't support hal format 4`

Indeed this might be a regression from Plasma 6.

**Comment by olly1240** [comment]
That's actually good to know, at least I didn't screw something up. Should I report it to KDE?

**Comment by aleasto** [comment]
No, I'm on it

**Comment by aleasto** [comment]
This should be fixed for Plasma 6.0.3

**Comment by olly1240** [comment]
I have yet to fix my waydroid install, seems binder does not want to work, then I'll get back at you when I test this

**Comment by olly1240** [comment]
This has been resolved by KDE
