### ISSUE TITLE
RDNA2 GPUs can't use hardware acceleration

### ISSUE THREAD

**Issue by cidkidnix** [waydroid/waydroid#133]
As discussed in the matrix chat me and another RDNA2 gpu user have to switch to software rendering for the container to start. SurfaceFlinger waits on /dev/binder then crashes for both of us.

**Comment by Essasetic** [comment]
Hey, any update to this? Been looking into Waydroid as a way to get around games with certain anticheats and would really appreciate GPU acceleration support for RDNA2.

**Comment by aleasto** [comment]
We now support all AMD gpus
