### ISSUE TITLE
[BUG] No Network Connection

### ISSUE THREAD

**Issue by dbob16** [waydroid/waydroid#1349]
### Describe the bug

Not getting any internet connection whatsoever in Waydroid. It's like it's not picking up any sort of Wifi or Ethernet device at all.

I tried everything I could discover with Google. One of the solutions was to add waydroid0 to trusted in the firewalld, the only issue is that waydroid0 does **not** exist at all.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Arch-Latest

### Kernel version

6.8.2-zen2-1-zen

### Desktop Environment

KDE 6.0.6 Qt 6.6.3

### GPU

Intel Graphics 4600

### Logs

[waydroid.cfg.txt](https://github.com/waydroid/waydroid/files/14875767/waydroid.cfg.txt)
[waydroid.log.txt](https://github.com/waydroid/waydroid/files/14875768/waydroid.log.txt)
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/14875769/waydroid.prop.txt)
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/14875770/waydroid_base.prop.txt)
[dmesg.txt](https://github.com/waydroid/waydroid/files/14875744/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/14875745/logcat.txt)

**Comment by sean-gray** [comment]
Im having the same issue. I see no errors in journalctl.

My system:
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.6.15-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 24 × 13th Gen Intel® Core™ i7-13700K
Memory: 62.6 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D29
System Version: 1.0

**Comment by sean-gray** [comment]
its working now. I had to disable firewalld. firewall-cmd to add waydroid0 to trusted zone does not work.

**Comment by sean-gray** [comment]
ok I found the solution. install firewall-config package and in bash type firewall-config and hit enter and in the gui change waydroid0 to trusted zone.

**Comment by AleXoundOS** [comment]
In my case linux kernel parameter `ipv6.disable=1` caused the issue. Once I removed it, network began working in Waydroid after reboot. My distro is NixOS 24.05.

**Comment by solitudealma** [comment]
> In my case linux kernel parameter `ipv6.disable=1` caused the issue. Once I removed it, network began working in Waydroid after reboot. My distro is NixOS 24.05.在我的例子中，linux 内核参数`ipv6.disable=1`导致了这个问题。一旦我删除它，网络在重新启动后就开始在 Waydroid 中工作。我的发行版是 NixOS 24.05。

how to set?
```nix
boot.kernel.sysctl."net.ipv6.conf.eth0.disable_ipv6" = true;
```
this?

**Comment by Goddard** [comment]
Same issue here.  I have checked kernel values for forwarding and I have disabled ufw and firewalld.  

I do have 2 wifi cards and 1 ethernet card.  Only my wifi is connected though.  It is connected through USB if that matters.

**Comment by Goddard** [comment]
Not sure if this will help anyone else, but I found a solution for me.

Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT  false.

Then stop and start everything.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/1349#issuecomment-2299752440

@solitudealma, did that work?

**Comment by mjamilrahman** [comment]
Solved after edit iptables config on Fedora 40 KDE Plasma

# Give internet access to waydroid0 interface from enp3s0 (main interface)
sudo iptables -A FORWARD -i waydroid0 -o enp3s0 -j ACCEPT
sudo iptables -A FORWARD -i enp3s0 -o waydroid0 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE

# save iptables permanently
sudo dnf install iptables iptables-services
sudo service iptables save

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/1349#issuecomment-2311086851

@mjamilrahman, have you considered adding those commands to the WayDroid installation script(s)?

**Comment by dbob16** [comment]
Closing on this issue as I no longer run Arch and the other distros I've hopped through don't seem to have this issue.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/1349#issuecomment-2323088937

I think that those of us on Fedora 40 should create a new issue. If nobody else does, I'll do so soon and link it to here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/1349#issuecomment-2323288615

Updating the WayDroid client OS via `org.lineageos.waydroidupdater.UpdateActivity` to `lineage_waydroid_x86_64-userdebug 11 RQ3A.211001.001 106 test-keys` remediated the problem for me.

**Comment by damster101** [comment]
> ok I found the solution. install firewall-config package and in bash type firewall-config and hit enter and in the gui change waydroid0 to trusted zone.

like this?
![image](https://github.com/user-attachments/assets/ab2ae6e4-4ebc-4bb5-9e5e-47511c4151b4)
doesn't work for me...

**Comment by damster101** [comment]
but completely stopping and disabling firewalld doesn't work either...

**Comment by damster101** [comment]
Removing all firewalls from my system doesn't change anything for me...

**Comment by DeutscheGabanna** [comment]
What worked for me was starting up the `iptables` service in arch.

```sudo systemctl start iptables```

If you want the fix to be permanent, then run:

```sudo systemctl enable iptables```

**Comment by solitudealma** [comment]
tun proxy can solve

**Comment by Le0X8** [comment]
@Goddard 

> Not sure if this will help anyone else, but I found a solution for me.
> 
> Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT false.
> 
> Then stop and start everything.

This works perfectly on Arch Linux. Thank you very much!!!

**Comment by hangodek** [comment]
> usr/lib/waydroid/data/scripts/

this work for me on fedora 41 after searching for hours, thanks

**Comment by beedell-roke** [comment]
> https://github.com/waydroid/waydroid/issues/1349#issuecomment-2739567704

@hangodek, likewise, on `PRETTY_NAME="Fedora Linux 42 (KDE Plasma Desktop Edition)"`. Because this is closed, I have filed https://github.com/waydroid/waydroid/issues/1866#issue-3025512051 to replace it.

**Comment by Genome26** [comment]
> Not sure if this will help anyone else, but I found a solution for me.
> 
> Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT false.
> 
> Then stop and start everything.

this is the solution for this problem, it worked on Fedora 42

**Comment by KFRANCMM** [comment]
> Not sure if this will help anyone else, but I found a solution for me.
> 
> Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT false.
> 
> Then stop and start everything.

Working Solution on Nobara (Fedora 42) KDE edition.

**Comment by MinkuruDev** [comment]
> # Solved after edit iptables config on Fedora 40 KDE Plasma
> The problem is docker break iptables rules.
> 
> ### Give internet access to waydroid0 interface from enp3s0 (main interface)
> #### Use iptables
> sudo iptables -A FORWARD -i waydroid0 -o enp3s0 -j ACCEPT sudo iptables -A FORWARD -i enp3s0 -o waydroid0 -j ACCEPT sudo iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE


Thanks, It work for me. I used wlan0 instead of enp3s0

**Comment by ading2210** [comment]
> ok I found the solution. install firewall-config package and in bash type firewall-config and hit enter and in the gui change waydroid0 to trusted zone.

@sean-gray Thank you! This is the only solution that worked for me on Debian Sid.

**Comment by aervxa** [comment]
> Not sure if this will help anyone else, but I found a solution for me.
> 
> Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT false.
> 
> Then stop and start everything.

@Goddard thanks! A whole new year, and this is the only solution that worked

**Comment by maybejaishkhan** [comment]
> Not sure if this will help anyone else, but I found a solution for me.
> 
> Go into /usr/lib/waydroid/data/scripts/waydroid-net.sh and make LXC_USE_NFT false.
> 
> Then stop and start everything.

Literally the only thing that worked. Thanks a lot man
