### ISSUE TITLE
[BUG] Roblox freezes with a white screen (Steam Deck)

### ISSUE THREAD

**Issue by 0TheGamer0** [waydroid/waydroid#1363]
### Describe the bug

When trying to use roblox on waydroid, the game logo appears and then it simply shows a white screen.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

SteamOS 3.5.17

### Kernel version

6.1.52-valve16-1-neptune-61 (64-bit)

### Desktop Environment

KDE Plasma 5.27.5

### GPU

AMD Custom GPU 0405

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by YogSottot** [comment]
try this https://github.com/Slappy826/libndk-fixer

**Comment by Quackdoc** [comment]
Logs not provided, user given something to try and hasn't done so, closing as stale, can be re-opened
