### ISSUE TITLE
[BUG] Can't install or uninstall Waydroid properly on Steam Deck

### ISSUE THREAD

**Issue by mangonebula** [waydroid/waydroid#1367]
### Describe the bug

I tried to install waydroid following the instructions on this website and it failed. I didn't think to save the konsole text to explore the error.
I tried to uninstall it, but I get a message that the uninstall.sh file doesn't exist.
I can't open the waydroid_toolbox file on the desktop. I just get a window that asks me to select the program to open the file in.
I tried to just do a new install, but I get the error that I don't understand. I included a file that has a copy of the konsole.
When I try to do the git clone command, it says it can't copy the files because there's already something there. 

I'm at a loss, because this is the extent of my skills with this kind of stuff. 

Can you help me clean up waydroid and get it installed properly?

[error.txt](https://github.com/waydroid/waydroid/files/15043328/error.txt)

I'll also paste it below:

SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Please enter current sudo password:
Checking if the sudo password is correct.
Sudo password is good!
Cloning into '/home/deck/AUR/waydroid/waydroid_script'...
remote: Enumerating objects: 717, done.
remote: Counting objects: 100% (327/327), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 717 (delta 260), reused 237 (delta 198), pack-reused 390
Receiving objects: 100% (717/717), 21.74 MiB | 17.21 MiB/s, done.
Resolving deltas: 100% (438/438), done.
Casualsnek repo has been successfully cloned!
Warning: The rootfs is already read-write!
         Nothing is performed.
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-06-29
pacman keyring has been initialized!
binder kernel module has been installed!
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (7) dnsmasq-2.89-1  libgbinder-1.1.35-1  libglibutil-1.0.74-1  lxc-1:5.0.2-1  python-gbinder-1.1.2-1  waydroid-1.4.2-1
             wlroots-0.16.2-1

Total Installed Size:  31.91 MiB

:: Proceed with installation? [Y/n]
(7/7) checking keys in keyring                                                     [################################################] 100%
(7/7) checking package integrity                                                   [################################################] 100%
(7/7) loading package files                                                        [################################################] 100%
(7/7) checking for file conflicts                                                  [################################################] 100%
(7/7) checking available disk space                                                [################################################] 100%
:: Processing package changes...
(1/7) installing wlroots                                                           [################################################] 100%
Optional dependencies for wlroots
    xorg-xwayland: Xwayland support [installed]
(2/7) installing dnsmasq                                                           [################################################] 100%
(3/7) installing lxc                                                               [################################################] 100%
Optional dependencies for lxc
    dnsmasq: lxc-net.service [installed]
    lua [installed]
    lua-filesystem: lxc-top
    lua-alt-getopt: lxc-top
(4/7) installing libglibutil                                                       [################################################] 100%
(5/7) installing libgbinder                                                        [################################################] 100%
(6/7) installing python-gbinder                                                    [################################################] 100%
(7/7) installing waydroid                                                          [################################################] 100%
Optional dependencies for waydroid
    python-pyclip: share clipboard with container
:: Running post-transaction hooks...
(1/7) Creating system user accounts...
(2/7) Reloading system manager configuration...
(3/7) Creating temporary files...
/usr/lib/tmpfiles.d/steamos.conf:6: Duplicate line for path "/root", ignoring.
/usr/lib/tmpfiles.d/steamos.conf:23: Duplicate line for path "/var/empty", ignoring.
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
(4/7) Arming ConditionNeedsUpdate...
(5/7) Reloading system bus configuration...
(6/7) Updating icon theme caches...
(7/7) Updating the desktop file MIME type cache...
waydroid and cage has been installed!
ln: failed to create symbolic link '/home/deck/Desktop/Waydroid-Toolbox': File exists
Config file missing. Lets configure waydroid.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly. Performing cleanup!
checking dependencies...
:: networkmanager optionally requires dnsmasq: connection sharing

Packages (7) dnsmasq-2.89-1  libgbinder-1.1.35-1  libglibutil-1.0.74-1  lxc-1:5.0.2-1  python-gbinder-1.1.2-1  waydroid-1.4.2-1
             wlroots-0.16.2-1

Total Removed Size:  31.91 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
(1/7) removing wlroots                                                             [################################################] 100%
(2/7) removing waydroid                                                            [################################################] 100%
(3/7) removing lxc                                                                 [################################################] 100%
(4/7) removing dnsmasq                                                             [################################################] 100%
(5/7) removing python-gbinder                                                      [################################################] 100%
(6/7) removing libgbinder                                                          [################################################] 100%
(7/7) removing libglibutil                                                         [################################################] 100%
:: Running post-transaction hooks...
(1/5) Reloading system manager configuration...
(2/5) Arming ConditionNeedsUpdate...
(3/5) Reloading system bus configuration...
(4/5) Updating icon theme caches...
(5/5) Updating the desktop file MIME type cache...
Cleanup completed! Try running the install script again! Goodbye!
(deck@steamdeck steamos-waydroid-installer)$

### Waydroid version

latest

### Device

Linux Desktop

### Operating System

Steam OS Holo 3.5.17

### Kernel version

6.1.52-valve16-1-neptune-61

### Desktop Environment

kde plasma

### GPU

Van Gogh 100-000000405

### Logs

[error.txt](https://github.com/waydroid/waydroid/files/15043377/error.txt)
[error.txt](https://github.com/waydroid/waydroid/files/15043391/error.txt)

I don't have these logs because waydroid did not install correctly.

**Comment by Quackdoc** [comment]
This seems like a dependancy issue, but this probably really should be reported to the installer you have used. Ill close this for now.
