### ISSUE TITLE
[BUG] [Errno 2] No such file or directory: 'modprobe'

### ISSUE THREAD

**Issue by SteveObsidian** [waydroid/waydroid#1371]
### Describe the bug

I got this error while wanting to download waydroid, im on a debian based distro, any solution?

### Waydroid version

latest

### Device

Linux Desktop

### Operating System

Antix

### Kernel version

6.1.60-antix.1-amd64-smp

### Desktop Environment

icewm

### GPU

No GPU, just integrated graphics

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by abtye** [comment]
It seems that you need to install `kmod`. If the problem cannot be solved, please provide more detailed information.

By the way, even if it's an integrated graphics card, you should provide the model of the integrated graphics card.

**Comment by Quackdoc** [comment]
user has not provided more information, closing issue, can be re-opened if user provides more info
