### ISSUE TITLE
[Feature] Download speed is slow when using waydroid init

### ISSUE THREAD

**Issue by ncduongg** [waydroid/waydroid#1374]
### Is your feature request related to a problem? Please describe.

When I use waydroid init, the download speed from sourceforge is very slow. I use a VPS with a good internet connection to download the .zip file but there is no way to use it with waydroid init. How do I use waydroid init with a file already downloaded on my computer?

### Describe the solution you'd like.

When I use waydroid init, the download speed from sourceforge is very slow. I use a VPS with a good internet connection to download the .zip file but there is no way to use it with waydroid init. How do I use waydroid init with a file already downloaded on my computer?

### Describe alternatives you've considered.

When I use waydroid init, the download speed from sourceforge is very slow. I use a VPS with a good internet connection to download the .zip file but there is no way to use it with waydroid init. How do I use waydroid init with a file already downloaded on my computer?

**Comment by strayedstar** [comment]
This doesn't really need to be explained，There is a file that records the iso installation location.
It seems to be at /etc。modify it that's fine.

**Comment by abtye** [comment]
You can manually download the zip file on [Source Forge](https://sourceforge.net/projects/waydroid/files/images/), extract it, and then place `system.img` and `vendor.img` under `/usr/share/waydroid-extra/images/`

**Comment by Quackdoc** [comment]
This is a known issue, and workaround provided, only real solution is to find a new provider, which no one has, well, provided.

**Comment by wedreamer** [comment]
use proxy for bash

```bash
sudo HTTPS_PROXY="http://127.0.0.1:7890/" waydroid init -s GAPPS
```

**Comment by Benexl** [comment]
if you are on arch use the chaotic aur, pretty fast in mb/s over kb/s
