### ISSUE TITLE
Unable to use on WSL2 with Ubuntu distro even after downloading custom kernel for Waydroid

### ISSUE THREAD

**Issue by cody8764** [waydroid/waydroid#1382]
### Describe the bug

When I use the kernel provided in the Waydroid telegram channel, everything goes fine until I try to launch it when it outputs an error:

(010048) [21:43:19] Starting waydroid session
(010048) [21:43:19] ERROR: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/user/1000/bus: No such file or directory
(010048) [21:43:19] See also: <https://github.com/waydroid>
(010048) [21:43:19] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/user/1000/bus: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 130, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/user/1000/bus: No such file or directory

(010664) [21:45:54] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(010664) [21:45:54] *** output passed to waydroid stdout, not to this log ***

Somehow, other people have been able to get this working, so I have no idea as to how I fix this problem.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

WSL2 Ubuntu amd64

### Kernel version

5.10.43.3-senjo-cont

### Desktop Environment

WSL2, so no desktop enviroment.

### GPU

Intel HD Graphics 4000

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by strayedstar** [comment]
No desktop environment, start a chicken？
Waydroid relies on Wayland and DBUS, which requires a separate user login.
And Windows isn't a big deal of Android emulators。
you should go to docker-Android，it support you environment。

**Comment by cody8764** [comment]
Was able to get it to work.

**Comment by Lolle2000la** [comment]
@cody8764 Could you share how you got it to work? I am facing the same problem.

**Comment by Co0lDoge** [comment]
> Was able to get it to work.

can you share you fix?

**Comment by strayedstar** [comment]
Are you switch render to sw(llvm)?
I don't know your's gpu,if it is nvidia,you need edit waydroid's config file.
You should check Opengl(es) support on ubuntu,anyway,use sw render instand of hw render at first.
---- Replied Message ----
From ***@***.***> Date 11/04/2024 00:37 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [waydroid/waydroid] Unable to use on WSL2 with Ubuntu distro even after downloading custom kernel for Waydroid (Issue #1382) 
Was able to get it to work.
can you share you fix?

**Comment by taalojarvi** [comment]
@cody8764 Would you mind sharing how you fixed it?

**Comment by mwdle** [comment]
> Was able to get it to work.

I am also facing this issue and am curious how you resolved it

**Comment by taalojarvi** [comment]
> > Was able to get it to work.
> 
> I am also facing this issue and am curious how you resolved it

For me atleast, I switched to software rendering on Waydroid config > installed weston > started Waydroid show-full-UI inside weston
