### ISSUE TITLE
[WARNING] Ubuntu 24.04-LTS CANNOT USE WAYDROID

### ISSUE THREAD

**Issue by LFRon** [waydroid/waydroid#1383]
### Describe the bug

Ubuntu cannot use waydroid because its kernel has removed the binder support.Waydroid should add a kernel with binder support for Ubuntu.I have tried that deepin v23/Debian kernel is good.I will upload it later.
![Image_1714227302771](https://github.com/waydroid/waydroid/assets/141307807/0f823349-19c2-4960-952e-1a85f3a7093d)

### Waydroid version

1.4.1

### Device

Linux Desktop

### Operating System

Ubuntu 24.04LTS amd64

### Kernel version

6.8-official

### Desktop Environment

GNOME 46

### GPU

AMD Radeon 780M

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by strayedstar** [comment]
第一：环境变量设置不对
第二：默认内核没有binder驱动集成，使用包含该驱动的内核或者自行编译，不然无法启动（安卓应用依赖binder进行ipc通讯）
第三：多用用bing/google，问题可以得到解决。
这不是程序的bug，是你环境不对。

**Comment by LFRon** [comment]
> 第一：环境变量设置不对 第二：默认内核没有binder驱动集成，使用包含该驱动的内核或者自行编译，不然无法启动（安卓应用依赖binder进行ipc通讯） 第三：多用用bing/google，问题可以得到解决。 这不是程序的bug，是你环境不对。

您好,我反馈的的确是ub的内核没有集成binder的问题,但是我发现ub2404对于新AMD机子的内核与老设备是不一样的,在TG上问却有人告诉我可以,然而我无论怎么重装24.04,默认的内核都不知道binder,我换了个内核就好了😂

**Comment by strayedstar** [comment]
> > 第一：环境变量设置不对 第二：默认内核没有binder驱动集成，使用包含该驱动的内核或者自行编译，不然无法启动（安卓应用依赖binder进行ipc通讯） 第三：多用用bing/google，问题可以得到解决。 这不是程序的bug，是你环境不对。
> 
> 您好,我反馈的的确是ub的内核没有集成binder的问题,但是我发现ub2404对于新AMD机子的内核与老设备是不一样的,在TG上问却有人告诉我可以,然而我无论怎么重装24.04,默认的内核都不支持binder,我换了个内核就好了😂

ub是根据宿主机选择环境的，并且默内核确实不包括binder，而且现在你应该关掉这个问题反馈。

**Comment by chenxy-china** [comment]
看来我用的ubuntu22.04也是同样的问题。需要自己编译内核才行

**Comment by GreatWallStudio8** [comment]
Thanks man, helps a lot!
