### ISSUE TITLE
WAYLAND_DISPLAY is not set, defaulting to "wayland-0

### ISSUE THREAD

**Issue by ks51git** [waydroid/waydroid#1388]
### Describe the bug

**Describe the bug**

- [20:12:48] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
- [20:12:48] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
- 
- Waydroid tools Version [latest]
- Waydroid Images Version [GGAPS]
- OS: [Ubuntu 22.04 (Xubuntu) x64 with KDE Plasma]

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04 (Xubuntu) x64

### Kernel version

6.5.0-28-generic

### Desktop Environment

KDE Plasma 5.24.7

### GPU

Intel HD Graphics 4400

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by ljoecordoba** [comment]
Have the same error:
waydroid version: 1.4.2
device: linux destop
operating system:Linux Mint 21.3
kernel version: Linux 5.15.0-105-generic
desktop environment: X-Cinnamon

**Comment by kotenok2000** [comment]
For KDE Plasma users, run the following commands to install the necessary Wayland support package:

sudo apt update
sudo apt install plasma-workspace-wayland
Then, reboot or log out and you should see a dropdown menu on the bottom left of your sign-in screen where you can select the desktop session: Plasma (Wayland).

**Comment by chenxy-china** [comment]
i have the same problem

**Comment by Quackdoc** [comment]
Waydroid has a hard requirement with wayland, currently cage, sway, weston all work nested. closing as duplicate

**Comment by imacrosid** [comment]
> For KDE Plasma users, run the following commands to install the necessary Wayland support package:
> 
> sudo apt update sudo apt install plasma-workspace-wayland Then, reboot or log out and you should see a dropdown menu on the bottom left of your sign-in screen where you can select the desktop session: Plasma (Wayland). Or if you don't want to install kde [#195 (comment)](https://github.com/waydroid/waydroid/issues/195#issuecomment-953926526)

I had succeed install plasma-workspace-wayland
Changed **WaylandEnable=true**
Then reboot
But I don't get choice for Plasma (Wayland)
<img width="1382" height="381" alt="Image" src="https://github.com/user-attachments/assets/c587d92c-f563-4e02-8090-ff4ace6d28fd" />
