### ISSUE TITLE
Internet unavailable

### ISSUE THREAD

**Issue by raantss18** [waydroid/waydroid#1392]
### Describe the bug

Waydroid cannot connect to internet after rebooting OS. waydroid0 is unavailable on the waydroid shell command ip a.
At the first time it works but after restarting OS, it disappears.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

EndeavourOS

### Kernel version

6.8.9-zen1-1-zen

### Desktop Environment

KDE 6

### GPU

Nvidia MX250

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
Please provide the logs, closing as invalid, can be re-opened when logs are provided
