### ISSUE TITLE
[Support Q] Specific Google Play app has no internet access

### ISSUE THREAD

**Issue by baburciu** [waydroid/waydroid#1399]
### Describe the bug

This a newcomer's silly question, any pointers one could provide are very welcome. 
I've wanted to use Waydroid for running [this TP-Link IP cameras management app](https://play.google.com/store/apps/details?id=com.tplink.vigi&hl=en&gl=US) on an old (Intel i3 M370 CPU, NVIDIA GeForce GT 520M) laptop running Lubuntu (well Ubuntu 20.04.2 LTS x86_64).
Even though browser and YouTube apps running in this Waydroid env have Internet access, this specific app returns a message complaining of no Internet connection:

<details markdown=1><summary>
screenshot for app login (click to show)
</summary>

![image](https://github.com/waydroid/waydroid/assets/59748058/7c8956b9-f927-4318-966a-e734ec0dbf02)

</details>

Does this behavior ring a bell to anyone? Many thanks in advance.

Some mentions:
- I'm starting Waydroid (`waydroid session start &` , `waydroid show-full-ui`) in an Weston Composition window terminal, as my `$XDG_SESSION_TYPE=x11`;
- I have the device certified for Google Play Protect, following https://docs.waydro.id/faq/google-play-certification;
- This specific app could not be installed initially before following the steps in https://github.com/casualsnek/waydroid_script?tab=readme-ov-file#install-libhoudini-arm-translation, but could be installed afterwards.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 20.04.2 amd64

### Kernel version

5.4.0-181-generic

### Desktop Environment

x11

### GPU

NVIDIA GeForce GT 520M

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/waydroid/waydroid/files/15248590/dmesg.txt)
[logcat.txt](https://github.com/waydroid/waydroid/files/15248591/logcat.txt)
[waydroid.txt](https://github.com/waydroid/waydroid/files/15248592/waydroid.txt)

**Comment by kotenok2000** [comment]
run `waydroid prop set  persist.waydroid.fake_wifi "*" `

**Comment by baburciu** [comment]
> Some apps check for internet connectivity by checking for wifi or cellular connection. Waydroid emulates wired connection. this should help
> 
> `waydroid prop set persist.waydroid.fake_wifi "*" ` source: [#647 (comment)](https://github.com/waydroid/waydroid/issues/647#issuecomment-1353765675)

thanks a lot @kotenok2000, this has worked :). Waydroid project and its community are just awesome 🚀
