### ISSUE TITLE
[15:24:50] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

### ISSUE THREAD

**Issue by GEEKGEEKOP** [waydroid/waydroid#1401]
### Describe the bug

```
[noroozi@fedora ~]$ sudo waydroid init
[15:24:50] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
[15:24:50] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
[noroozi@fedora ~]$ 

```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

fedora 38

### Kernel version

6.4.14-200.fc38.x86_64

### Desktop Environment

i3

### GPU

did't have

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by cniw** [comment]
Fedora Instalation Guide https://docs.waydro.id/usage/install-on-desktops#fedora

Fedora users should write the System and Vendor OTA explicitly
```bash
sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor -s GAPPS
```
`-c` for the System OTA channel URL
`-v` for the Vendor OTA channel URL
`-s GAPPS` will give you the image with Google Play Store
for more details `waydroid init -h`

**Comment by dinosauria123** [comment]
https://ota.waydro.id/system and https://ota.waydro.id/vendor shows 404 error.
Is it OK ?

**Comment by abtye** [comment]
> https://ota.waydro.id/system and https://ota.waydro.id/vendor shows 404 error. Is it OK ?
There is no problem with this because there is no HTML file, so it displays 404.

The code is [here](https://github.com/waydroid/OTA). Here are only some JSON files.

**Comment by Quackdoc** [comment]
>  Is it OK ?

yes.
