### ISSUE TITLE
[BUG] Running Waydroid adds `NoDisplay=true` to the desktop file.

### ISSUE THREAD

**Issue by siddhpant** [waydroid/waydroid#1407]
### Describe the bug

I was unable to find Waydroid in search (GNOME). After some time saw `~/.local/share/applications/Waydroid.desktop` has `NoDisplay=true`.

I removed it and the icon/launcher showed up. But after the run again it disappeared because `NoDisplay=true` was again set. Also tried `NoDisplay=false` to no avail.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian Testung

### Kernel version

6.7.12-amd64

### Desktop Environment

GNOME Shell 44.9

### GPU

Not applicable

### Logs

`grep Waydroid.desktop /var/lib/waydroid/*.*` has no results.

**Comment by cniw** [comment]
Remove that line then lock the file
```bash
 sed -i '/NoDisplay/d' ~/.local/share/applications/Waydroid.desktop
 sudo chmod -w ~/.local/share/applications/Waydroid.desktop
```

**Comment by siddhpant** [comment]
Thanks for the idea, though still, this should not happen in the first place.

**Comment by aleasto** [comment]
If you enable multi-windows mode you're not supposed to launch the full android UI anymore, so we hide its launcher.
You should just launch the android application you want from the GNOME applications menu.

**Comment by siddhpant** [comment]
> If you enable multi-windows mode you're not supposed to launch the full android UI anymore, so we hide its launcher. You should just launch the android application you want from the GNOME applications menu.

Thanks! I can confirm `waydroid prop get persist.waydroid.multi_windows` was set to true.

For anyone stumbling here: Run `waydroid prop set persist.waydroid.multi_windows false`.

In my case, I had hid the applications from the launcher since the default apps (like calculator) were popping up.

**Comment by martinandersson** [comment]
> you're not supposed to launch the full android UI anymore

Excuse my language, but I find this to be, ... ridiculous?

Some users, like myself for example, would love to have both: open the Android UI whenever I need access to the device (enabling/disabling Bluetooth, et cetera), as well as have the installed Android apps integrated with my host desktop, "multi window" mode. 

Forcing me to chose between one or the other is unfortunate and may make some features impossible (like the Bluetooth thing). It is especially unfortunate if this is out of someone's ideology; I "should/am supposed to use the application in a certain way". 

To make matters worse, it is literally beating the victim already on the ground by silently removing  his launcher icon causing people like the poster and myself to wonder WTH just happened and then start wasting time trying to figure it out.

I can only hope that it is not out of personal ideology you have explicitly made Waydroid _less_ useful.

Surely there has to be a technical reason why we can't have both. Technicalities which you do not wish to or are unable to solve/fix, but regardless: do not just automagically drop the launcher icon lol. The least we can do here is to prompt the user with a dialog box saying "Hey, you enabled multi-windows and so now we can't open the Android UI anymore blah blah".

Ideally of course, please leave the icon in place and support launching the Android UI.

Having said that, this ticket should be re-opened with the minimal goal being to pop-up an adequate message to the user.

EDIT: I applied the .desktop file hack as described by @cniw and it appears we can have both! I am able to launch Android apps in their own windows as well opening the Android UI.
