### ISSUE TITLE
[BUG] Epic Seven crashes immediately after launch

### ISSUE THREAD

**Issue by YoJames2019** [waydroid/waydroid#1410]
### Describe the bug

After installing the vanilla lineageOS image, libndk and gapps through [casualsneks waydroid scripts](https://github.com/casualsnek/waydroid_script/issues), and the app itself through gapps, the app would just infinitely hang.

 I searched through some of the issues to try to find a solution and came across [libndk-fixer](https://github.com/Slappy826/libndk-fixer) which was supposed to fix the same issue I was having, but for a different game. (see [this comment](https://github.com/waydroid/waydroid/issues/1323#issuecomment-2068121588) from #1323 for reference)

Now the game just crashes immediately after launch, which I assume to be because of this line: 
`2521  2521 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~xQUILAODzotnAJVZ88SbGQ==/com.stove.epic7.google-Yk2j3Nazq0kkimSS73WGAQ==/lib/arm/libur.so" is for EM_ARM (40) instead of EM_386 (3)`

However I'm not quite sure where to go from here. Any assistance would be greatly appreciated :)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Pop!_OS 22.04 LTS amd64

### Kernel version

6.8.0-76060800daily20240311-generic

### Desktop Environment

GNOME 42.9

### GPU

NVIDIA RTX 3070 LHR

### Logs

[/var/lib/waydroid/waydroid.cfg](https://github.com/waydroid/waydroid/files/15343194/waydroid.cfg.txt)
[/var/lib/waydroid/waydroid.prop](https://github.com/waydroid/waydroid/files/15343201/waydroid.prop.txt)
[/var/lib/waydroid/waydroid_base.prop](https://github.com/waydroid/waydroid/files/15343196/waydroid_base.prop.txt)
[/var/lib/waydroid/waydroid.log](https://github.com/waydroid/waydroid/files/15343192/waydroid.log)

[logcat.txt](https://github.com/waydroid/waydroid/files/15343212/logcat.txt)
[dmesg.txt](https://github.com/waydroid/waydroid/files/15343211/dmesg.txt)

**Comment by Slappy826** [comment]
The error you are describing is because the the apk that you installed only contains 32-bit (armv7) native binaries, while as far as I know libndk only supports translation of 64-bit (arm64-v8a/aarch64) binaries. You will need to source an apk file with the correct binaries. Also my repo only fixes a very specific issue that only happens with roblox, doesn't have anything to do with whats happening in your case.

**Comment by YoJames2019** [comment]
> The error you are describing is because the the apk that you installed only contains 32-bit (armv7) native binaries, while as far as I know libndk only supports translation of 64-bit (arm64-v8a/aarch64) binaries. You will need to source an apk file with the correct binaries. 

Ah thank you, I'll try to find that somewhere

> Also my repo only fixes a very specific issue that only happens with roblox, doesn't have anything to do with whats happening in your case.

I understand that, however the original issue was just the app infinitely hanging at a black screen (without the errors for architecture support), and your repo fixed that exact issue for both roblox and it did end up working for me to at least get to this step

**Comment by YoJames2019** [comment]
I found an apk labeled (arm64-v8a,armeabi-v7a), and am having the exact same error

**Comment by YoJames2019** [comment]
I'll upload a log of what happens with the regular libndk translation layer later when i get back

**Comment by YoJames2019** [comment]
[updated logcat.txt](https://github.com/waydroid/waydroid/files/15366325/logcat.txt)
[updated dmesg.txt](https://github.com/waydroid/waydroid/files/15366327/dmesg.txt)
[updated waydroid_base.prop](https://github.com/waydroid/waydroid/files/15366326/waydroid_base.prop.txt)
