### ISSUE TITLE
i need help im new modprobe  problem

### ISSUE THREAD

**Issue by du12212** [waydroid/waydroid#1412]
### Describe the bug

![Screenshot 2024-05-19 15 38 05](https://github.com/waydroid/waydroid/assets/170268609/b37c4efb-37fb-45f1-b556-ddc74c1af4f9)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

 Debian GNU/Linux 12 (bookworm)

### Kernel version

 Linux 6.6.21-01327-gc9107f2d4947

### Desktop Environment

idk

### GPU

Intel UHD Graphics 600

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
question answered, closing, can be re-opened if needed
