### ISSUE TITLE
How to root waydroid's Android

### ISSUE THREAD

**Issue by mmahdi2020** [waydroid/waydroid#1415]
How to i root waydroids' android?

root needed for GLTOOLS

**Comment by oifj34f34f** [comment]
Try this: https://github.com/casualsnek/waydroid_script

**Comment by Quackdoc** [comment]
Question has been answered, can be reopened if needed

**Comment by Unbreak4ble** [comment]
> Install Magisk using this: https://github.com/casualsnek/waydroid_script

it says magisk is been installed but theres no apk on home and i cant execute "su" command on waydroid shell.

some specs:
- distro: manjaro
- kernel: arch linux
- android version: 13

**Comment by gitmanbloggus** [comment]
> > Install Magisk using this: https://github.com/casualsnek/waydroid_script
> 
> it says magisk is been installed but theres no apk on home and i cant execute "su" command on waydroid shell.
> 
> some specs:
> 
> * distro: manjaro
> * kernel: arch linux
> * android version: 13

try reinstalling the script
