### ISSUE TITLE
[BUG] Some page can't scroll

### ISSUE THREAD

**Issue by MeRrai333** [waydroid/waydroid#1433]
According my video, first page it's should scrollable like second page

**Waydroid version**
1.4.2

**Device**
Linux Desktop

**Operating System**
Ubuntu 22.04

https://github.com/waydroid/waydroid/assets/113435542/8911f992-75b1-464c-8551-b4198c12ceee

**Comment by Quackdoc** [comment]
can you try setting `waydroid prop set persist.waydroid.fake_touch "*"`

**Comment by zebh** [comment]
`waydroid prop set persist.waydroid.fake_touch com.YoStarEN.Arknights`

This solves it for me. 

However, it sometimes seem to never receive a "button up" event so simply moving the mouse pointer will cause it to scroll, regardless if a button is pressed or not. I have not yet figured out if it is a game bug or a bug in Waydroid. I will investigate further and open a separate issue if I think it is Waydroid-related.
