### ISSUE TITLE
What are amd 64 bit system ota and vender ota

### ISSUE THREAD

**Issue by Zombie287432874** [waydroid/waydroid#1437]

**Comment by abtye** [comment]
OTA stands for `Over The Air` and is an online upgrade technology. The Android system fixes bugs and adds new features through OTA.

Android uses `/system` partition to host generic code (which is shared among many software SKUs), and `/vendor` partition to host SoC exclusive BSP code (which is shared across multiple devices based on a specified SoC).

By the way, you shouldn't ask such questions on `issues`. You should search for answers on your own through search engines.
Perhaps what you want to ask is something else?

**Comment by Quackdoc** [comment]
question has been answered, no followup.
