### ISSUE TITLE
[BUG] File not downloading

### ISSUE THREAD

**Issue by emir814** [waydroid/waydroid#1438]
### Describe the bug

![image](https://github.com/waydroid/waydroid/assets/67476241/acc91d5d-28fc-427d-bb71-4a515da85256)
It gets stuck at the end of the download of the System file, I tried 2 times.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 40 KDE AMD64

### Kernel version

6.8.11-300.fc40.x86_64

### Desktop Environment

KDE Plasma 6

### GPU

NVIDIA GeForce GTX 1650

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by abtye** [comment]
You can manually download the zip file on [Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/), extract it, and then place `system.img` and `vendor.img` under `/usr/share/waydroid-extra/images/`

**Comment by emir814** [comment]
Thank You bro.

**Comment by Quackdoc** [comment]
as said, you can manually download it, or you can try again later.

**Comment by ghost** [comment]
> ### Describe the bug
> ![image](https://github.com/waydroid/waydroid/assets/67476241/acc91d5d-28fc-427d-bb71-4a515da85256) It gets stuck at the end of the download of the System file, I tried 2 times.
> 
> ### Waydroid version
> 1.4.2
> 
> ### Device
> Linux Desktop
> 
> ### Operating System
> Fedora 40 KDE AMD64
> 
> ### Kernel version
> 6.8.11-300.fc40.x86_64
> 
> ### Desktop Environment
> KDE Plasma 6
> 
> ### GPU
> NVIDIA GeForce GTX 1650
> 
> ### Logs
> /var/lib/waydroid/waydroid.cfg /var/lib/waydroid/waydroid.prop /var/lib/waydroid/waydroid_base.prop /var/lib/waydroid/waydroid.log `sudo waydroid shell -- logcat -d | tee logcat.txt` `sudo dmesg | tee dmesg.txt`

just use vpn and try to download again, this will fix the issue inshallah
