### ISSUE TITLE
Flickering on my nvidia gpu [BUG]

### ISSUE THREAD

**Issue by RandomGamingIn144p** [waydroid/waydroid#1439]
### Describe the bug

My graphics card is a gtx 1650 and I'm using 550.78 on Fedora 40, and I was using the Weston compositor on KDE Plasma 6 with Xorg, but due to Wayland being laggy to use on other things (noticed that disabling vsync on games caused the screen to flicker with KDE on wayland where Xorg fixed it), it seems to happen too with similar flickering.

Likely NVIDIA and Wayland related, maybe an issue on my part

https://github.com/waydroid/waydroid/assets/131448955/e0960c00-865f-498e-becf-2ca7f84cec14

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 40 amd64

### Kernel version

6.8.10-300.fc40.x86_64

### Desktop Environment

KDE Plasma 6 w/ X.org

### GPU

NVIDIA GeForce GTX 1650

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1717205500
vendor_datetime = 1714216970
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
```

/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
waydroid.host.user=randomgamingin144p
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/randomgamingin144p/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```

/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
```

/var/lib/waydroid/waydroid.log
[waydroid.log](https://github.com/user-attachments/files/15544158/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt](https://github.com/user-attachments/files/15544162/logcat.txt)

`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/user-attachments/files/15544167/dmesg.txt)

**Comment by ClaytonTDM** [comment]
i have the same issue under weston ;-;
