### ISSUE TITLE
[BUG] 'Could not resolve host' when trying to install on Linux

### ISSUE THREAD

**Issue by Mathiaszero** [waydroid/waydroid#1441]
### Describe the bug

When I tried commands like `curl https://repo.wadro.id | sudo bash` it shows an error and I could not install:
![image](https://github.com/waydroid/waydroid/assets/55817193/7ce65e54-04a3-4b94-bf81-6a7f429d089b)

How can I resolve?

### Waydroid version

NA, not installed yet

### Device

Linux Desktop

### Operating System

Ubuntu 20.04 x86_64

### Kernel version

5.15.0-107-generic

### Desktop Environment

LXDE

### GPU

Cirrus Logic GD5446

### Logs

NA, not installed yet

**Comment by abtye** [comment]
You entered the wrong command, it should be `curl https://repo.waydro.id | sudo bash`
