### ISSUE TITLE
[BUG] does it still not support ubuntu 22.04 

### ISSUE THREAD

**Issue by chenxy-china** [waydroid/waydroid#1444]
### Describe the bug

 i can`t run waydroid session ,
log is below:

 (006670) [17:31:20] % modprobe -q ashmem_linux
(006670) [17:31:20] % chmod 666 -R /dev/anbox-binder
(006670) [17:31:20] % chmod 666 -R /dev/vndbinder
(006670) [17:31:20] % chmod 666 -R /dev/hwbinder

(006670) [17:31:33] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(006670) [17:31:33] % systemctl is-active -q nfcd
(006670) [17:31:33] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
chmod: 更改 '/sys/kernel/debug/sync/sw_sync' 的权限: 不允许的操作
(006670) [17:31:33] % chmod 777 -R /dev/dri
(006670) [17:31:33] % chmod 777 -R /dev/fb0
(006670) [17:31:33] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(006670) [17:31:33] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(006670) [17:31:33] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(006670) [17:31:33] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(006670) [17:31:33] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(006670) [17:31:33] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(006670) [17:31:33] Save config: /var/lib/waydroid/waydroid.cfg
(006670) [17:31:33] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(006670) [17:31:33] New background process: pid=6737, output=background
(006670) [17:31:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: utils.c: safe_mount: 1221 Not a directory - Failed to mount "/dev/vndbinder" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/vndbinder"
lxc-start: waydroid: utils.c: safe_mount: 1221 Not a directory - Failed to mount "/dev/hwbinder" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/hwbinder"
RUNNING
(006678) [17:31:33] Skipping clipboard manager service because of missing pyclip package
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

22.04 

### Kernel version

6.2.0-26-generic

### Desktop Environment

ubuntu:GNOME

### GPU

Intel(R) Core(TM) i7-13700

### Logs

[dmesg.txt](https://github.com/user-attachments/files/15737130/dmesg.txt)
[logcat.txt](https://github.com/user-attachments/files/15737142/logcat.txt)
[waydroid.log](https://github.com/user-attachments/files/15737146/waydroid.log)
[waydroid_base.prop.txt](https://github.com/user-attachments/files/15737263/waydroid_base.prop.txt)
[waydroid.prop.txt](https://github.com/user-attachments/files/15737267/waydroid.prop.txt)
[waydroid.cfg.txt](https://github.com/user-attachments/files/15737272/waydroid.cfg.txt)

**Comment by billbeans** [comment]
Same here. Hasn't worked in months

**Comment by mian196** [comment]
Im on 24.04 and it worked smoothly on it , i just have a problem running one of arm games

**Comment by chenxy-china** [comment]
默认内核没有binder驱动集成，使用包含该驱动的内核或者自行编译，不然无法启动
问题关闭了把
