### ISSUE TITLE
Waydroid UI not initiating [BUG]

### ISSUE THREAD

**Issue by ScientificAJ** [waydroid/waydroid#1457]
### Describe the bug

Waydroid UI not starting, when i click it. When i do sudo waydroid init, it shows already initiated, Any solution?

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

MX Linux

### Kernel version

6.00-6mx-amd64

### Desktop Environment

GNOME

### GPU

AMDRV170

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Abdillah** [comment]
Without any log, it's hard to know why @ScientificAJ.
Could you upload your logs when that happens? With the file and command listed on your report.

**Comment by Quackdoc** [comment]
This can be re-opened if the logs are provided
