### ISSUE TITLE
Internet stops working after starting Waydroid session

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [waydroid/waydroid#146]
Hello everyone! I've successfully installed Waydroid and some apps. However, I have a problem with Internet access. When I start the Waydroid session, Internet (both in Waydroid apps and ordinary desktop apps) stops working. **ip a** returns the following output:

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000                                       [1/56]`

 `   link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00      `                  

`    inet 127.0.0.1/8 scope host lo                                               `

`       valid_lft forever preferred_lft forever                                   `

`    inet6 ::1/128 scope host                                                     `

`       valid_lft forever preferred_lft forever                                                                                          `

`2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000`

`    link/ether 28:d2:44:dc:3c:89 brd ff:ff:ff:ff:ff:ff                           `

`3: wlp2s0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000`

`    link/ether 38:b1:db:4e:16:af brd ff:ff:ff:ff:ff:ff                                                                                  `

`    inet 192.168.100.4/24 brd 192.168.100.255 scope global wlp2s0                                                                       `

`       valid_lft forever preferred_lft forever                                                                                          `

`    inet6 fe80::3ab1:dbff:fe4e:16af/64 scope link                                                                                       `

`       valid_lft forever preferred_lft forever                                                                                          `

`4: lxcbr0: <BROADCAST,MULTICAST,DYNAMIC> mtu 1500 qdisc noqueue state DOWN group default qlen 1000`

`    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff                                                                                  `

`9: waydroid0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000`

`    link/ether 22:eb:76:c9:44:c3 brd ff:ff:ff:ff:ff:ff                                                                                  `

`    inet 192.168.250.1/24 brd 192.168.250.255 scope global waydroid0                                                                    `

`       valid_lft forever preferred_lft forever                                                                                          `

`    inet6 fe80::20eb:76ff:fec9:44c3/64 scope link                                                                                       `

`       valid_lft forever preferred_lft forever                                                                                          `

`10: vethJ03SLS@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master waydroid0 state UP group default qlen 1000`

`    link/ether fe:71:3c:f8:4f:f8 brd ff:ff:ff:ff:ff:ff link-netnsid 0                                                                   `

`    inet 169.254.23.63/16 brd 169.254.255.255 scope global vethJ03SLS                                                                   `

`       valid_lft forever preferred_lft forever                                                                                          `

`    inet6 fe80::fc71:3cff:fef8:4ff8/64 scope link                                                                                       `

`       valid_lft forever preferred_lft forever`

**ip route** returns the following output:

`default dev vethJ03SLS scope link   `  
                                                                                                  
`169.254.0.0/16 dev vethJ03SLS proto kernel scope link src 169.254.23.63         `
                                                        
`192.168.100.0/24 dev wlp2s0 proto kernel scope link src 192.168.100.4       `
                                                            
`192.168.100.1 dev wlp2s0 scope link                                                      `
                                               
`192.168.250.0/24 dev waydroid0 proto kernel scope link src 192.168.250.1 `

What can cause the problem and how can it be solved?

P.S. I've connected through Wi-Fi.

Update 12.10: Internet not working on a main system seems to have been an nftables issue, and was solved. However, I still can't access Internet from Waydroid apps.

**Comment by peddy22** [comment]
I'm having this issue as well, did you ever find a solution?

**Comment by azul** [comment]
Internet of the main system stays up for me but in waydroid never works. Pretty standard ubuntu 22.04 install with waydroid 1.2.1.
Host OS connected to internet over wifi with dhcp and dns provided by dhcp.

```
sudo waydroid shell
/system/bin/sh: No controlling tty: open /dev/tty: No such file or directory
/system/bin/sh: warning: won't have full job control
:/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:f9:d3:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::7dfd:e1a7:8714:de65/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

**Comment by ChrysoliteAzalea** [comment]
Solved by allowing the **waydroid0** interface in the firewall.
