### ISSUE TITLE
[BUG] Waydroid still fails to start on Ubuntu 22.04, possible lxc issue

### ISSUE THREAD

**Issue by billbeans** [waydroid/waydroid#1481]
### Describe the bug

Waydroid will not work on Ubuntu 22.04 for months now. It used to work fine, but now it doesn't. I get very little in the way of error messages other than the usual "Failled to get service waydroidplatform, trying again" while the icon appears and reappears in the dock. This is the only output from the log that seems to say anything useful:

`lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"`

I have tried adding `psi=1` to `/etc/default/grub`, but it didn't do anything. I use the lowlatency kernel, but I also tried booting into the default kernel a while back and it still didn't help.

The systemd logs are so verbose and insane that I'm not even going to try and paste them all here, but I have a snippet that might explain some of the reasons for Waydroid's failure to launch. I think it has something to do with lxc and cgroups, but I really have no idea what those are:

```
Jul 11 20:55:59 anonpc Waydroid.desktop[10623]: [20:55:59] Failed to get service waydroidplatform, trying again...
Jul 11 20:55:59 anonpc Waydroid.desktop[10663]: [20:55:59] Failed to get service waydroidplatform, trying again...
Jul 11 20:55:59 anonpc init: starting service 'vendor.hwcomposer-2-1'...
Jul 11 20:55:59 anonpc libprocessgroup: Failed to make and chown /acct/uid_1000: Read-only file system
Jul 11 20:55:59 anonpc init: createProcessGroup(1000, 534) failed for service 'vendor.hwcomposer-2-1': Read-only file system
Jul 11 20:55:59 anonpc init: starting service 'vendor.gralloc-2-0'...
Jul 11 20:55:59 anonpc libprocessgroup: Failed to make and chown /acct/uid_1000: Read-only file system
Jul 11 20:55:59 anonpc init: createProcessGroup(1000, 535) failed for service 'vendor.gralloc-2-0': Read-only file system
Jul 11 20:55:59 anonpc init: starting service 'surfaceflinger'...
Jul 11 20:55:59 anonpc init: Could not create socket 'pdx/system/vr/display/client': Failed to bind socket 'pdx/system/vr/display/client': No such file or directory
Jul 11 20:55:59 anonpc init: Could not create socket 'pdx/system/vr/display/manager': Failed to bind socket 'pdx/system/vr/display/manager': No such file or directory
Jul 11 20:55:59 anonpc init: Could not create socket 'pdx/system/vr/display/vsync': Failed to bind socket 'pdx/system/vr/display/vsync': No such file or directory
Jul 11 20:55:59 anonpc libprocessgroup: Failed to make and chown /acct/uid_1000: Read-only file system
Jul 11 20:55:59 anonpc init: createProcessGroup(1000, 538) failed for service 'surfaceflinger': Read-only file system
Jul 11 20:55:59 anonpc libprocessgroup: Failed to open /dev/stune/foreground/tasks: No such file or directory: No such file or directory
Jul 11 20:55:59 anonpc libprocessgroup: Failed to apply HighPerformance task profile: No such file or directory
Jul 11 20:56:00 anonpc init: Service 'vendor.gralloc-2-0' (pid 535) received signal 6
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'vendor.gralloc-2-0' (pid 535) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 1000 pid 535 in 0ms
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'surfaceflinger' (pid 538) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 1000 pid 538 in 0ms
Jul 11 20:56:00 anonpc init: Service 'vendor.hwcomposer-2-1' (pid 534) received signal 6
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'vendor.hwcomposer-2-1' (pid 534) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 1000 pid 534 in 0ms
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'surfaceflinger' (pid 538) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 1000 pid 538 in 0ms
Jul 11 20:56:00 anonpc init: Service 'surfaceflinger' (pid 538) received signal 6
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'surfaceflinger' (pid 538) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 1000 pid 538 in 0ms
Jul 11 20:56:00 anonpc init: Sending signal 9 to service 'zygote' (pid 412) process group...
Jul 11 20:56:00 anonpc libprocessgroup: Successfully killed process cgroup uid 0 pid 412 in 0ms
Jul 11 20:56:00 anonpc Waydroid.desktop[10623]: [20:56:00] Failed to get service waydroidplatform, trying again...
Jul 11 20:56:00 anonpc Waydroid.desktop[10663]: [20:56:00] Failed to get service waydroidplatform, trying again...
Jul 11 20:56:01 anonpc Waydroid.desktop[10623]: [20:56:01] Failed to get service waydroidplatform, trying again...
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04.4 LTS x86_64

### Kernel version

6.5.0-42-lowlatency

### Desktop Environment

GNOME 42.9

### GPU

AMD Radeon RX 5500

### Logs

(All changed to .txt to meet Github's file type requirements)

[waydroid.cfg.txt](https://github.com/user-attachments/files/16186347/waydroid.cfg.txt)
[waydroid.prop.txt](https://github.com/user-attachments/files/16186363/waydroid.prop.txt)
[waydroid_base.prop.txt](https://github.com/user-attachments/files/16186364/waydroid_base.prop.txt)
[waydroid.log.txt](https://github.com/user-attachments/files/16186367/waydroid.log.txt)
[logcat.txt](https://github.com/user-attachments/files/16186369/logcat.txt)
[dmesg.txt](https://github.com/user-attachments/files/16186370/dmesg.txt)

**Comment by zyxhere** [comment]
Are you still encountering this?

**Comment by billbeans** [comment]
> Are you still encountering this?

No, I fixed it a while ago after redownloading the waydroid-choose-gpu.sh script, but I definitely ran it before making this issue, so I think there was some change in the code on it's git page. It works now

**Comment by debianjake** [comment]
yeah it sends my computer into kernel panic when i try to start it
