### ISSUE TITLE
[BUG] Apt Install fails with "Depends: policykit-1 but it is not installable"

### ISSUE THREAD

**Issue by lucidBrot** [waydroid/waydroid#1484]
### Describe the bug
(If this is *my* issue, not *yours*, I am sorry. It looks to me like the dependencies in apt are wrong though.)

I'm on debian testing (trixie), and following the https://docs.waydro.id/usage/install-on-desktops instructions.

After doing
```bash
apt install curl ca-certificates -y
curl https://repo.waydro.id | sudo bash
sudo apt install waydroid
```

I get the following error:  
```
The following packages have unmet dependencies:
 waydroid : Depends: policykit-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### more details
```bash
generic@nevermore:~$ sudo apt-get -o Debug::pkgProblemResolver=yes install waydroid
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) waydroid:amd64 < none -> 1.4.2 @un puN Ib >
Broken waydroid:amd64 Depends on lxc:amd64 < none | 1:6.0.1-1 @un uH >
  Considering lxc:amd64 1 as a solution to waydroid:amd64 9999
  Re-Instated liblxc1t64:amd64
  Re-Instated liblxc-common:amd64
  Re-Instated lxc:amd64
Broken waydroid:amd64 Depends on python3-gbinder:amd64 < none | 1.1.2 @un uH >
  Considering python3-gbinder:amd64 1 as a solution to waydroid:amd64 9999
  Re-Instated libglibutil:amd64
  Re-Instated libgbinder:amd64
  Re-Instated python3-gbinder:amd64
Broken waydroid:amd64 Depends on policykit-1:amd64 < none @un H >
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 waydroid : Depends: policykit-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```bash
generic@nevermore:~$ sudo apt policy waydroid
waydroid:
  Installed: (none)
  Candidate: 1.4.2
  Version table:
     1.4.2 500
        500 https://repo.waydro.id trixie/main all Packages
generic@nevermore:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
generic@nevermore:~$ sudo apt policykit-1
Error: Invalid operation policykit-1
generic@nevermore:~$ sudo apt policy policykit-1
policykit-1:
  Installed: (none)
  Candidate: (none)
  Version table:

generic@nevermore:~$ uname -a
Linux nevermore 6.9.8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.8-1 (2024-07-07) x86_64 GNU/Linux
```

There aren't actually any broken held packages:  
`dpkg --get-selections | grep hold` has no output.

The apt source the install script created does not look wrong to me:
```
generic@nevermore:~$ sudo cat /etc/apt/sources.list.d/waydroid.list 
deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ trixie main
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian Trixie

### Kernel version

Linux nevermore 6.9.8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.8-1 (2024-07-07) x86_64 GNU/Linux

### Desktop Environment

KDE

### GPU

Intel Meteor Lake-P

### Logs

Not applicable, since installation already fails.

**Comment by kirkfall** [comment]
same issue on mobian plasma and phosh running on a pinephone pro

**Comment by abtye** [comment]
At present, Debian trixie is still in the testing stage. Perhaps the official Debian personnel forgot to package this package? Perhaps you can install it manually.

**Comment by pstef** [comment]
PolicyKit has been replaced by polkit.

**Comment by pstef** [comment]
Sorry, I don't.

**Comment by lucidBrot** [comment]
> @abtye 
> At present, Debian trixie is still in the testing stage.

That is true and if you're not willing to support that, I get it.
Just to point it out though: debian testing is still relatively stable and is usually expected to work, as packages have to be bug-free for a few days before getting into testing. If trixie is still not considered stable enough to be supported, you might want to update the text [in the install instructions](https://docs.waydro.id/usage/install-on-desktops)
> Currently supported values are: mantic, focal, jammy, kinetic, lunar, noble, bookworm, bullseye, **trixie**, sid

> @abtye
> Perhaps the official Debian personnel forgot to package this package? Perhaps you can install it manually.

I don't know how to do that. If you're aware of easy-to-follow instructions, they'd be appreciated I think.

Tbh I don't really understand how the debian maintainers could fix this. Isn't the dependency specified by the package, and the package packaged by waydroid?

**Comment by MrCyjaneK** [comment]
I'll take look at that on the weekend

**Comment by abtye** [comment]
@lucidBrot I have found a solution.

**Comment by AozoraDev** [comment]
@abtye ???
![image](https://github.com/user-attachments/assets/656b02fc-e0c8-44dd-92e2-f6d0bebe6bd4)

**Comment by magic-ian** [comment]
@AozoraDev it looks like the SID testing branch package is no longer there. I was able to get it working according to @abtye using the package.

I reuploaded the version for ARM here that works:
https://archive.org/details/policykit-1_124-2_arm64

**Comment by AozoraDev** [comment]
Heyya!

I just found the fix here.
Turns out, `policykit-1` is just a meta package to install `pkexec` and `polkitd`.

So what i do is just creating a blank meta package deb file that depends on pkexec and polkitd.
Here. You can have mine. You can also check the inside of this file if you doubt.

[policykit-1_124-3_all.deb](https://cdn.discordapp.com/attachments/689071764126433286/1270445139000688733/policykit-1_124-3_all.deb?ex=66b3b9bc&is=66b2683c&hm=07b1f7e202585e4c0a9818b2d4983b02f30aa66b9fcb63ce9ba52c51c6c673f8&)

**Comment by AozoraDev** [comment]
Now you probably gonna face the binder died thingy problem when booting waydroid...
Just add `psi=1` into your kernel parameter and you are good to go.

Idk what this PSI do but hey! If it fixed, it fixed. ¯\\_(ツ)\_/¯

**Comment by keyn0te** [comment]
> Heyya!
> 
> I just found the fix here. Turns out, `policykit-1` is just a meta package to install `pkexec` and `polkitd`.
> 
> So what i do is just creating a blank meta package deb file that depends on pkexec and polkitd. Here. You can have mine. You can also check the inside of this file if you doubt.
> 
> [policykit-1_124-3_all.deb](https://cdn.discordapp.com/attachments/689071764126433286/1270445139000688733/policykit-1_124-3_all.deb?ex=66b3b9bc&is=66b2683c&hm=07b1f7e202585e4c0a9818b2d4983b02f30aa66b9fcb63ce9ba52c51c6c673f8&)

This download link is no longer available, but thanks for the suggestion. I believe I was able to recreate the package with the following steps (for any who stumble across this after).

1. Create directory to house files and cd into it:
mkdir testdir && cd testdir

2. Download equivs package:
sudo apt install equivs

3. Generate template:
equivs-control policykit-1

4. Edit template, uncommenting "Version" and "Depends". Edit the following (Version probably depends on what version of polkitd you have installed):
Package: policykit-1
Version: 124-3
Depends: pkexec,polkitd

5. Build package:
equivs-build policykit-1

6. Install package:
sudo apt install ./policykit-1_124-3_all.deb

7. Install waydroid:
sudo apt install waydroid

Hopefully this temporary workaround won't be needed in the near future.

**Comment by aleasto** [comment]
It'll take a few days for a new build to release.
Thank you for the patience.

**Comment by jardon** [comment]
Hey! I wanted to check in on this.  It's been almost two months and there hasn't been a new release that includes this fix. The sid package seems to still be pulling `1.4.2` which is even older. I can fix this myself with a patch fix, but if upstream has already fixed it, I'd rather

**Comment by aleasto** [comment]
There has been a release! But apparently something went wrong with `sid` specifically.
@MrCyjaneK do you know why `sid` is out of date?

**Comment by llc0930** [comment]
So will this problem be solved?
I'm currently temporarily switching to trixie because I want to clean up the transitional package policykit-1.
Waydroid now has all kinds of problems that seem like they will never be fixed...

**Comment by llc0930** [comment]
#1564

**Comment by MrCyjaneK** [comment]
Hey, this should be working fine now

**Comment by llc0930** [comment]
Then you guys should perhaps mention that people who originally installed with CODENAME=sid will need to modify `waydroid.list`.
Although the install script will apparently delete the old `waydroid.list` and recreate it, if it is not executed then of course it will not take effect.
