### ISSUE TITLE
waydroid init will download the img from Internet

### ISSUE THREAD

**Issue by ajie9115** [waydroid/waydroid#149]
when I run waydroid init, it will download the img from Internet and it takes a lot of time.

Is there  a way to waydroid init from the local img ?

**Comment by Luciogi** [comment]
Put `system.img` and `vendor.img` to `/usr/share/waydroid-extra/images`

**Comment by Theo3113** [comment]
No encuentro tal directorio en ninguna parte. Sin embargo buscando system.img y vendor.img se encuentran en "/var/lib/waydroid/images". Ahora el tema es, cuando uno hace el paso previo, los comandos antecesores a "sudo waydroid init", y si descargamos tales archivos de "https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/" y "https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/" respectivamente, las deberíamos descomprimir en el directorio correcto, sea cual fuere, y luego ejecutar  "sudo waydroid init" o directamente avanzar a "sudo systemctl start waydroid-container"? Esto suponiendo que el directorio necesario se haya creado previamente. Se agradecería cualquier dato extra, porque realmente es más rápido descargar las imágenes necesarias con un gestor que esperar desde el terminal todo ese tiempo, así de paso nos mantendríamos más al tanto de los nuevos lanzamientos.

**Comment by Theo3113** [comment]
Reinstalé el sistema operativo y relicé los pasos de la instalación de Waydroid nuevamente, pero, si uno no ejecuta "sudo waydroid init" el directorio "/var/lib/waydroid/images" no exite hasta que se lo ejecute. También ademas es necesario validar system.img y vendor.img para que todo resulte. Realmente no se de programación sino haría más y hablaría menos, o mejor dicho escribiría menos. Ja

En éste link se encuentra lo que yo desde mi ignorancia veo es la ejecución de Init en phyton supongo "https://github.com/waydroid/waydroid/blob/bullseye/tools/config/__init__.py"

Que sería éste: 


# Copyright 2021 Oliver Smith
# SPDX-License-Identifier: GPL-3.0-or-later
import os
import pwd

#
# Exported functions
#
from tools.config.load import load, load_session, load_channels
from tools.config.save import save, save_session

#
# Exported variables (internal configuration)
#
version = "1.1.1"
tools_src = os.path.normpath(os.path.realpath(__file__) + "/../../..")

# Keys saved in the config file (mostly what we ask in 'waydroid init')
config_keys = ["arch",
               "images_path",
               "vendor_type",
               "system_datetime",
               "vendor_datetime"]

session_config_keys = ["user_name",
                       "user_id",
                       "group_id",
                       "host_user",
                       "xdg_data_home",
                       "waydroid_data",
                       "xdg_runtime_dir",
                       "wayland_display",
                       "pulse_runtime_path",
                       "state",
                       "lcd_density"]

# Config file/commandline default values
# $WORK gets replaced with the actual value for args.work (which may be
# overridden on the commandline)
defaults = {
    "arch": "arm64",
    "work": "/var/lib/waydroid",
    "vendor_type": "MAINLINE",
    "system_datetime": "0",
    "vendor_datetime": "0",
    "preinstalled_images_path": "/usr/share/waydroid-extra/images"
}
defaults["images_path"] = defaults["work"] + "/images"
defaults["rootfs"] = defaults["work"] + "/rootfs"
defaults["data"] = defaults["work"] + "/data"
defaults["lxc"] = defaults["work"] + "/lxc"
defaults["host_perms"] = defaults["work"] + "/host-permissions"

session_defaults = {
    "user_name": pwd.getpwuid(os.getuid()).pw_name,
    "user_id": str(os.getuid()),
    "group_id": str(os.getgid()),
    "host_user": os.path.expanduser("~"),
    "xdg_data_home": str(os.environ.get('XDG_DATA_HOME', os.path.expanduser("~") + "/.local/share")),
    "xdg_runtime_dir": str(os.environ.get('XDG_RUNTIME_DIR')),
    "wayland_display": str(os.environ.get('WAYLAND_DISPLAY')),
    "pulse_runtime_path": str(os.environ.get('PULSE_RUNTIME_PATH')),
    "state": "STOPPED",
    "lcd_density": "0"
}
session_defaults["config_path"] = defaults["work"] + "/session.cfg"
session_defaults["waydroid_data"] = session_defaults["xdg_data_home"] + \
    "/waydroid/data"
if session_defaults["pulse_runtime_path"] == "None":
    session_defaults["pulse_runtime_path"] = session_defaults["xdg_runtime_dir"] + "/pulse"

channels_defaults = {
    "config_path": "/usr/share/waydroid-extra/channels.cfg",
    "system_channel": "https://raw.githubusercontent.com/waydroid/OTA/master/system",
    "vendor_channel": "https://raw.githubusercontent.com/waydroid/OTA/master/vendor",
    "rom_type": "lineage",
    "system_type": "VANILLA"
}
channels_config_keys = ["system_channel",
                        "vendor_channel",
                        "rom_type",
                        "system_type"]


Ahora bien, no estaría genial que  exista una forma de solo crear los directorios necesarios a traves de tales líneas de comando al ejecutar init, y que nosotros agreguemos los archivos "system.img y vendor.img" ya descargados, y que luego y de la misma forma se logre validarlos nuevamente con comandos. Porque también e notado que cuando uno corre "sudo apt install waydroid", en tal proceso hay un error que nos indica acerca de init, del cual adjunto imagen porque no puedo copiar desde la consola ya que justo estoy en init jaja. Ello ahorraría tiempo a los que no sabemos nada de como resolver problemas a través de comandos, y que se nos hace más factible formatear el equipo de nuevo y volver a probar Waydroid desde cero, buscando ver si funciona en otro entorno, o viendo sobre el tema para ver si podemos ir agarrando la mano y conribuir con algo que valga la pena. Muchos no contamos ni con la información necesaria, ni el conocimiento exácto, ni con el tiempo debido; más sin embargo, tenemos muchas ganas de que éste gran proyecto triunfe, pues es algo bueno y grande para toda la comunidad. Aunque sí contamos con todas las ganas informar lo que apenas aprecioamos desde nuestra mínima posibilidad. Gracias por leer y sepan comprender, no lo hago con ánimos de ofender, ni menos preciar, ni desprestigiar, ni valorar, sino con toda la buena honda que los creadores de esta gran herramienta se merecen.

![Captura](https://user-images.githubusercontent.com/32743726/137253176-b76a073b-11fe-4e4e-8eed-9decfd5c2183.png)

**Comment by ajie9115** [comment]
> Put `system.img` and `vendor.img` to `/usr/share/waydroid-extra/images`

I do it and run `waydroid init `again. But it still download img from Internet. 
Can you give a example how to do it ?

**Comment by ronoaldo** [comment]
This is what I'm facing: https://paste.debian.net/1217516

**Comment by Theo3113** [comment]
No sabría decirle si existen sumas de verificación para tales archivos. Lo
que sí puede apreciar es que, desde la última vez que descargué las
imágenes de vendor y system, subieron otras con fechas más actuales e
incluso un paquete de Gapps que aún no he probado instalar.
lineage-17.1-20211007-MAINLINE-waydroid_x86_64-vendor.zip
y lineage-17.1-20211007-VANILLA-waydroid_x86_64-system.zip respectivamentes.

Más de una vez me ha pasado en distintas descargas que he hecho en el
pasado, que ellas han sufrido modificación tras ser interrumpidas o por una
mala conexión, o por simplemente cancelarse y volver a intentar descargar
desde el mismo archivo, o cosas por el estilo, haciendo que las sumas de
verificación no coincidan al haberse alterado el paquete de alguna forma.
Yo le recomendaría probar descargarlas de nuevo, y si es en una conexión de
internet estable mejor, y mucho más si para ello utiliza un gestor o
acelerador de descargas como JDownloader, Free Download Manager o Internet
Dowlnoad Manager que me han resultado muy bien siempre.

Pero estaría bien pedir a los desarrolladores que añadan las checksum para
el que las desee utilizar.

**Comment by d-g** [comment]
> This is what I'm facing: https://paste.debian.net/1217516

```
Entry not found

The requested entry isn't in our database. That usually means it expired or has been deleted by the author. 
```

While this Github's forum is indeed looks meagre and sometimes blatantly broken to anyone who is used to full-featured email, it is not IRC as yet.  So no much need in a third-party ‘paste’ service.

**Comment by ronoaldo** [comment]
> > This is what I'm facing: https://paste.debian.net/1217516
> 
> ```
> Entry not found
> 
> The requested entry isn't in our database. That usually means it expired or has been deleted by the author. 
> ```
> 
> While this Github's forum is indeed looks meagre and sometimes blatantly broken to anyone who is used to full-featured email, it is not IRC as yet. So no much need in a third-party ‘paste’ service.

Sorry! My bad while creating the past bin... I was better using a Gist for that. I managed to workaround my case by downloading the .json manifest locally, and referencing the mirror in the local file. Then, waydroid init worked and installed the images. I am however having other issues starting it.
