### ISSUE TITLE
add support for simulating wifi  depended on linux kernel module cfg80211 and virt_wifi

### ISSUE THREAD

**Issue by warlice** [waydroid/waydroid#1494]
### Is your feature request related to a problem? Please describe.

some apps will check the existence of the wifi for judging whether the environment is a simulator. so need to simulate more closed to the turly device.

### Describe the solution you'd like.

using the linux ko virt wifi, it 's  a wrapper on ethernet to simulate wifi device.
more reference 
 https://wiki.ubuntu.com/Ubiquity/Testing
 https://github.com/sysprog21/vwifi

### Describe alternatives you've considered.

goldfish  simulated wifi

### Additional context

U all need to modrpobe cfg80211 and virt_wifi:
lsmod |grep virt
virt_wifi              20480  1
cfg80211              421888  1 virt_wifi

the approching has two submit  belows:
https://github.com/warlice/waydroid/commit/5fc98f2380b84e9ceac40b2d846cb8bf73011e55
https://github.com/warlice/android_device_waydroid_waydroid/commit/2f9c33b816ed2cffd25fca6b2310482c7c32c509

**Comment by warlice** [comment]
notice : u' ll need to connect the virt wifi by your hand.

**Comment by anilv4** [comment]
I also faced a similar issue with Apple Music: It won't connect and with message, "You are offline."

To solve this, I ran the following command.

`waydroid prop set persist.waydroid.fake_wifi "*"`
stop and start Waydroid.

https://docs.waydro.id/usage/waydroid-prop-options

Hope it will help you.

**Comment by Quackdoc** [comment]
Waydroid is a container so using virtwifi doesn't really make sense, if the given prop above doesn't work, create a seperate issue for the apps it does not work with

**Comment by jianglin-code** [comment]
I want how to do it

**Comment by baptx** [comment]
I read fake_wifi was removed when using Waydroid with Android 13 but here is a workaround needed for some apps even after fake_wifi was added back:
https://github.com/waydroid/waydroid/issues/619#issuecomment-4061247917
