### ISSUE TITLE
[BUG] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"

### ISSUE THREAD

**Issue by blaicer15** [waydroid/waydroid#1500]
### Describe the bug

When installing the **waydroid** version, I don't get any kind of error, but when running the launcher it simply doesn't open anything after a few minutes, I try to run it manually but I get the following error:

waydroid first-launch
[11:43:07] Starting waydroid session
[11:43:07] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[11:43:07] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?

When running the following command it tells me that the **container is stopped** but when I try to start it it tells me that the **container is running**:
`sudo waydroid shell -- logcat -d | tee logcat.txt`
[11:39:41] WayDroid container is STOPPED

sudo waydroid container start
ERROR: WayDroid container service is already running

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Linux Mint 21.3 Cinnamon

### Kernel version

5.15.0-117-generic

### Desktop Environment

Cinnamon 6.0.4

### GPU

NVIDIA Corporation GM107 [GeForce GTX 750 Ti]

### Logs

/var/lib/waydroid/waydroid.cfg
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1722662165
vendor_datetime = 1722684053
suspend_action = freeze
mount_overlays = True
auto_adb = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder

/var/lib/waydroid/waydroid_base.prop
debug.stagefright.ccodec=0
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true

/var/lib/waydroid/waydroid.log
(013777) [10:45:37] ERROR: Action "init" needs root access
(013777) [10:45:37] See also: <https://github.com/waydroid>
(013777) [10:45:37] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(013792) [10:45:44] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(013792) [10:45:44] % mkdir -p /dev/binderfs
(013792) [10:45:44] % mount -t binder binder /dev/binderfs
(013792) [10:45:44] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(013792) [10:45:44] Save config: /var/lib/waydroid/waydroid.cfg
(013792) [10:45:45] % mkdir -p /var/lib/waydroid/cache_http
(013792) [10:45:45] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240803-VANILLA-waydroid_x86_64-system.zip/download
(013792) [10:51:03] Validating system image
(013792) [10:51:05] Extracting to /var/lib/waydroid/images
(013792) [10:51:21] Save config: /var/lib/waydroid/waydroid.cfg
(013792) [10:51:21] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240803-MAINLINE-waydroid_x86_64-vendor.zip/download
(013792) [10:54:15] Validating vendor image
(013792) [10:54:15] Extracting to /var/lib/waydroid/images
(013792) [10:54:18] Save config: /var/lib/waydroid/waydroid.cfg
(013792) [10:54:18] % modprobe -q ashmem_linux
(013792) [10:54:18] % lxc-info --version
5.0.0
(013792) [10:54:18] % mkdir -p /var/lib/waydroid/lxc/waydroid
(013792) [10:54:18] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(013792) [10:54:18] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(013792) [10:54:18] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(013792) [10:54:18] % aa-enabled --quiet
(013792) [10:54:18] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(013792) [10:54:18] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(013459) [10:54:18] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013459) [10:54:18] % chmod 666 -R /dev/anbox-binder
(013459) [10:54:18] % chmod 666 -R /dev/anbox-vndbinder
(013459) [10:54:18] % chmod 666 -R /dev/anbox-hwbinder
(014256) [10:54:25] Starting waydroid session
(014256) [10:54:25] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014256) [10:54:25] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(014285) [10:54:50] Starting waydroid session
(014285) [10:54:50] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014285) [10:54:50] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(014298) [10:54:59] WayDroid session is stopped
(014306) [10:55:02] Already initialized
(014311) [10:55:07] Starting waydroid session
(014311) [10:55:07] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014311) [10:55:07] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(014539) [10:56:19] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014539) [10:56:19] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(014617) [10:57:33] Starting waydroid session
(014617) [10:57:33] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014617) [10:57:33] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(014888) [10:59:41] Starting waydroid session
(014888) [10:59:41] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(014888) [10:59:41] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(016065) [11:00:34] Starting waydroid session
(016065) [11:00:34] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(016065) [11:00:34] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(016508) [11:03:54] Starting waydroid session
(016508) [11:03:54] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(016508) [11:03:54] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(013459) [11:04:16] Hardware service is not even started
(013459) [11:04:16] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013459) [11:04:16] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(013459) [11:04:16] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(016550) [11:04:16] Hardware service is not even started
(016550) [11:04:16] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(016550) [11:04:16] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(016550) [11:04:17] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(013459) [11:04:24] Hardware service is not even started
(013459) [11:04:24] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013459) [11:04:24] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(013459) [11:04:24] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(017783) [11:05:20] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(017783) [11:05:20] % lxc-info --version
5.0.0
(017783) [11:05:20] % mkdir -p /var/lib/waydroid/lxc/waydroid
(017783) [11:05:20] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(017783) [11:05:20] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(017783) [11:05:20] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(017783) [11:05:20] % aa-enabled --quiet
(017783) [11:05:20] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(017783) [11:05:20] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(017875) [11:05:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(017875) [11:05:22] % chmod 666 -R /dev/anbox-binder
(017875) [11:05:22] % chmod 666 -R /dev/anbox-vndbinder
(017875) [11:05:22] % chmod 666 -R /dev/anbox-hwbinder
(017945) [11:06:00] Starting waydroid session
(017945) [11:06:00] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(017945) [11:06:00] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(018725) [11:10:31] Starting waydroid session
(018725) [11:10:31] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(018725) [11:10:31] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(018748) [11:10:46] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(018748) [11:10:46] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(020376) [11:35:07] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(020376) [11:35:07] WayDroid container is STOPPED
(020401) [11:35:47] Starting waydroid session
(020401) [11:35:47] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(020401) [11:35:47] Wayland socket '/run/user/1001/wayland-0' doesn't exist; are you running a Wayland compositor?
(020412) [11:35:56] ERROR: Action "init" needs root access
(020412) [11:35:56] See also: <https://github.com/waydroid>
(020412) [11:35:56] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(020427) [11:36:09] Already initialized

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[11:39:41] WayDroid container is STOPPED

`sudo dmesg | tee dmesg.txt`
[ 8189.330725] audit: type=1400 audit(1722963921.043:100): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="lxc-waydroid" pid=17802 comm="apparmor_parser"

**Comment by Quackdoc** [comment]
you need to run on wayland
