### ISSUE TITLE
Steamdeck Error during installation, Error cloning Casualsnek repo! [BUG]

### ISSUE THREAD

**Issue by ergic** [waydroid/waydroid#1503]
### Describe the bug

 On Steamdeck how do I fix this? I got good internet connection but still get this error.
 
![453288906_1058808858977173_3949782996727097060_n](https://github.com/user-attachments/assets/aa20146f-335a-4496-96f8-1dea4238b8cf)

### Waydroid version

waydroid --version

### Device

Linux Desktop

### Operating System

steamos

### Kernel version

uname --kernel-release

### Desktop Environment

steamos

### GPU

steam deck

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Quackdoc** [comment]
Not a waydroid bug, report to the tool's github

**Comment by Quackdoc** [comment]
Not a waydroid bug
