### ISSUE TITLE
[BUG] Waydroid doesn't recognize any WIFI-Network as Avaible. 

### ISSUE THREAD

**Issue by dragunDaniel** [waydroid/waydroid#1510]
### Description of the Problem

 The bug consists of an error related to the Wi-Fi of Waydroid. Basically, after starting Waydroid, and from the very first time, when I turn on the Wi-Fi, no Wi-Fi networks appear as available to connect to. This is quite strange because this problem should be resolved fairly quickly with the default settings provided in the official documentation: 

 - https://docs.waydro.id/debugging/networking-issues. 
 
Moreover, it’s not just that it doesn’t show the available Wi-Fi networks; Waydroid's Wi-Fi isn’t even able to stay on. When I click on the Wi-Fi symbol, it always remains in "**Turning on...**" mode but never actually turns on. If I exit the settings or get distracted for a moment, Waydroid's Wi-Fi automatically turns off. Additionally, it seems that at no point does the Wi-Fi actually turn on, because as can be seen in the following screenshot, it appears that Waydroid is not able to determine whether it is on or off. (I believe it is never on.)

![Captura desde 2024-08-11 12-12-26](https://github.com/user-attachments/assets/4bfdba6e-a0d9-4f11-a24d-4a0014419974)
![Captura desde 2024-08-11 12-12-56](https://github.com/user-attachments/assets/39f1e0e7-8286-41a9-91f3-441264a90387)

# What I have tried

I have tried several things. First, I restarted the Waydroid container using the command sudo waydroid container restart. I also removed everything related to Waydroid from my system and reinstalled it, but nothing changes regarding the issue. Next, I went to the networking issues section of the sparse documentation provided on the official Waydroid website and followed all the steps: setting Waydroid to trusted zone and executing the suggested UFW commands for ports 56 and 67. However, none of that worked. Other things I tried include disabling firewalld to see if it would work, but it didn't. I followed the commands suggested in the previously published issues in this repository, but nothing has worked for me. I don’t know what is causing this problem... 

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora Linux 39 (Workstation Edition) x86_64 

### Kernel version

6.9.12-100.fc39.x86_64 

### Desktop Environment

GNOME 45.8.1 

### GPU

Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx

### Logs

/var/lib/waydroid/waydroid.cfg :point_down:  
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1723253406
vendor_datetime = 1722684053
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
```
/var/lib/waydroid/waydroid.prop :point_down:  

```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
waydroid.host.user=pc
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/pc/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```

/var/lib/waydroid/waydroid_base.prop :point_down: 
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
```

`sudo waydroid shell -- logcat -d | tee logcat.txt` :point_down: 
[logcat.txt](https://github.com/user-attachments/files/16574178/logcat.txt)

`sudo dmesg | tee dmesg.txt` :point_down: 
[dmesg.txt](https://github.com/user-attachments/files/16574180/dmesg.txt)

**Comment by dragunDaniel** [comment]
It works with `waydroid prop set persist.waydroid.multi_windows "true"`.

**Comment by electrikjesus** [comment]
That prop does not affect how wifi is used within Waydroid. I think you are missing something in the steps to reproduce your issue

**Comment by dragunDaniel** [comment]
> That prop does not affect how wifi is used within Waydroid. I think you are missing something in the steps to reproduce your issue

Maybe. But I don't know what it could be. The fact is that Wi-Fi actually works when you run the apps separately. However, it doesn't work when you execute them with the UI fully displayed. In fact, if you thoroughly check the UI, you'll see that Wi-Fi is not actually enabled... The truly important thing for me is that it functions, regardless of everything else.

**Comment by electrikjesus** [comment]
Ok. So Waydroid uses the host os's Wi-Fi connection and creates an ethernet connection within the Android container. This is why you see apps working like they have Wi-Fi and the Wi-Fi dropped down within Android shows nothing.

**Comment by Winner0283Tech** [comment]
For me, its the same, when i turn WiFi on, no networks were found, and after ca. 1 minute it turns off automatically.
