### ISSUE TITLE
Fixed size for waydroid app windows

### ISSUE THREAD

**Issue by FoamScience** [waydroid/waydroid#152]
I'm having the same issues as #70, and enabling multi-windows works (the apps get rotated correctly) but the windows start too big for my screen (Using sway).

Is there a way I can fix the size of the opened window beforehand?

**Comment by e-g1gor** [comment]
For anyone who stumbled in this issue through search - this is the solution https://github.com/waydroid/waydroid/issues/70#issuecomment-927144567
