### ISSUE TITLE
Is Waydroid Heading in the Right Direction? A Deep Dive into Version Choices and User Experience

### ISSUE THREAD

**Issue by OurCodeBase** [waydroid/waydroid#1531]
# Introduction
Waydroid is offering the ability to run Android apps on a Linux system through an Android container. However, the project’s direction—specifically its focus on newer Android versions and full-screen overlays—has sparked a debate. Why is Waydroid pushing for the latest Android versions instead of refining stability, performance, and resource management? And why is a full-screen overlay necessary in a Linux environment where users typically value flexibility? Let’s dive into these questions and explore whether Waydroid’s current path aligns with its users’ needs.

# The Full-Screen Overlay Dilemma
One of the main criticisms of Waydroid is the requirement to open a full-screen overlay in a workspace to run Android apps. For many Linux users, this seems counterintuitive. Linux’s strength lies in its highly customizable and multitasking-friendly environment. Having to dedicate an entire workspace to a full-screen Android overlay disrupts this flow, making the experience less integrated and more siloed.

# The Version Conundrum: Why Android 13?
Waydroid’s decision to focus on supporting the latest Android versions, like Android 13, is another point of contention. While it’s understandable that users might want access to the latest features and apps, there’s a significant trade-off: resource usage. Newer Android versions are generally more resource-intensive, which can lead to performance issues, especially on older or less powerful hardware.

## Would Android 9 Be a Better Fit?
Android 9, for example, supports the vast majority of Android apps and is less demanding in terms of resources. By opting for a lighter version, Waydroid could improve performance and reduce the strain on system resources. This would be particularly beneficial for users on older hardware or those running other resource-heavy applications alongside Waydroid.

Focusing on a more lightweight Android version would also allow the development team to concentrate on enhancing stability and performance. A stable, smooth-running Android environment on Linux would likely appeal to a broader audience, making Waydroid a more attractive option for daily use.

# Stability and Performance: The Real Priorities?
For many users, the primary appeal of Waydroid is the ability to run Android apps seamlessly on a Linux desktop. However, this seamless experience is heavily dependent on the stability and performance of the system. Newer Android versions bring not only increased resource demands but also new bugs and compatibility issues. As a result, the emphasis on keeping up with the latest Android releases might be detracting from efforts to make the existing system more robust and user-friendly.

## The Case for Focusing on Core Improvements
By prioritizing stability, performance, and the integration of Android apps into the Linux environment, Waydroid could create a more polished and reliable product. This would likely resonate more with the Linux community, which tends to value performance and efficiency over having the latest features.

A more stable and performance-oriented Waydroid would also pave the way for its use in professional environments where reliability is critical. By focusing on these core aspects, the project could build a solid foundation that would allow it to expand and improve in other areas over time.

# Conclusion
Waydroid’s current trajectory, with its focus on newer Android versions and a full-screen overlay, raises important questions about its priorities. While keeping up with the latest Android releases might seem like a good strategy, it comes at the cost of performance, stability, and user experience—especially in a Linux environment where flexibility and resource efficiency are key.

Perhaps it’s time for Waydroid to reassess its approach. By focusing on optimizing for an older, more stable Android version like Android 9 and refining how Android apps are integrated into the Linux desktop, Waydroid could become a much more powerful and appealing tool for Linux users. After all, the goal is not just to run Android apps on Linux but to do so in a way that complements the strengths of both operating systems.

**Comment by Quackdoc** [comment]
Please read whatever your AI is outputting before spamming the waydroid group, first and foremostly, waydroid does not have a hard requirement on fullscreen. https://docs.waydro.id/usage/waydroid-prop-options newer versions of android are fine, and multiple tweaks can be used to lessen resource usage. Please don't spam us with garbage
