### ISSUE TITLE
[BUG] Cannot launch wechat

### ISSUE THREAD

**Issue by TheToxicToast** [waydroid/waydroid#1541]
### Describe the bug

I followed the official install instruction, and installed the play store version of wechat on it. The app installs but doesn't launch, it just shows a white screen

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 40

### Kernel version

6.10.6-200.fc40.x86_64

### Desktop Environment

Gnome 46

### GPU

Nvidia A2000

### Logs

/var/lib/waydroid/waydroid.cfg

[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1724476687
vendor_datetime = 1724498485
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]

/var/lib/waydroid/waydroid.prop
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
waydroid.host.user=toxictoast
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/toxictoast/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1

/var/lib/waydroid/waydroid_base.prop

sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true

/var/lib/waydroid/waydroid.log

(114836) [18:26:58] Save config: /var/lib/waydroid/waydroid.cfg
(114836) [18:27:04] % mkdir -p /var/lib/waydroid/cache_http
(114836) [18:27:04] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240824-VANILLA-waydroid_x86_64-system.zip/download
(114836) [18:30:23] Validating system image
(114836) [18:30:24] Extracting to /var/lib/waydroid/images
(114836) [18:30:34] Save config: /var/lib/waydroid/waydroid.cfg
(114836) [18:30:39] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240824-MAINLINE-waydroid_x86_64-vendor.zip/download
(122727) [18:38:20] Save config: /var/lib/waydroid/waydroid.cfg
(123231) [18:38:53] Save config: /var/lib/waydroid/waydroid.cfg
(123231) [18:39:06] % rm /var/lib/waydroid/cache_http/lineage-18.1-20240824-MAINLINE-waydroid_x86_64-vendor.zip_830318b28443391320c367d9b282e9422380091542e6d19afd48acfc834b74da
(123231) [18:39:06] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240824-MAINLINE-waydroid_x86_64-vendor.zip/download
(123231) [18:44:07] Validating vendor image
(123231) [18:44:07] Extracting to /var/lib/waydroid/images
(123231) [18:44:10] Save config: /var/lib/waydroid/waydroid.cfg
(123231) [18:44:10] % modprobe -q ashmem_linux
(123231) [18:44:10] % lxc-info --version
6.0.1
(123231) [18:44:10] % mkdir -p /var/lib/waydroid/lxc/waydroid
(123231) [18:44:10] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(123231) [18:44:10] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(123231) [18:44:10] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(123231) [18:44:10] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(001207) [18:44:16] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(001207) [18:44:16] % modprobe -q ashmem_linux
(001207) [18:44:16] % chmod 666 -R /dev/binder
(123027) [18:44:16] Starting waydroid session
(001207) [18:44:16] % chmod 666 -R /dev/vndbinder
(001207) [18:44:16] % chmod 666 -R /dev/hwbinder
(001207) [18:44:16] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
success
(001207) [18:44:17] % chmod 777 -R /dev/dri
(001207) [18:44:17] % chmod 777 -R /dev/video0
(001207) [18:44:17] % chmod 777 -R /dev/video1
(001207) [18:44:17] % chmod 777 -R /dev/video2
(001207) [18:44:17] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(001207) [18:44:17] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001207) [18:44:17] % mkdir -p /var/lib/waydroid/overlay_work/system
(001207) [18:44:17] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(001207) [18:44:17] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001207) [18:44:17] % mkdir -p /var/lib/waydroid/overlay_work/vendor
(001207) [18:44:17] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(001207) [18:44:17] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001207) [18:44:17] Save config: /var/lib/waydroid/waydroid.cfg
(001207) [18:44:17] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(001207) [18:44:17] New background process: pid=126922, output=background
(001207) [18:44:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(001207) [18:44:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:44:17] waiting 10 seconds for container to start...
(123027) [18:44:30] waydroidusermonitor: Received transaction: 1
(123027) [18:44:30] Android with user 0 is ready
(123027) [18:44:30] % adb start-server
* daemon not running; starting now at tcp:5037
* daemon started successfully
(123027) [18:44:31] % adb connect 192.168.240.112
connected to 192.168.240.112:5555
(123027) [18:44:31] Established ADB connection to Waydroid device at 192.168.240.112.
(001207) [18:52:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:53:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:53:10] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:53:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:53:21] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:53:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(123027) [18:53:48] waydroidusermonitor: Received transaction: 2
(001207) [18:54:39] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(138838) [18:55:45] Run waydroid session -h for usage information.
(001207) [18:55:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [18:55:50] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
(001207) [18:55:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(001207) [18:55:50] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(001207) [18:55:51] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001207) [18:55:51] % umount /var/lib/waydroid/rootfs/vendor
(001207) [18:55:51] % umount /var/lib/waydroid/rootfs/vendor
(001207) [18:55:51] % umount /var/lib/waydroid/rootfs
(001207) [18:55:51] % umount /var/lib/waydroid/rootfs
(139076) [18:55:55] Starting waydroid session
(001207) [18:55:55] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(001207) [18:55:56] % chmod 777 -R /dev/dri
(001207) [18:55:56] % chmod 777 -R /dev/video0
(001207) [18:55:56] % chmod 777 -R /dev/video1
(001207) [18:55:56] % chmod 777 -R /dev/video2
(001207) [18:55:56] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(001207) [18:55:56] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001207) [18:55:56] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(001207) [18:55:56] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001207) [18:55:56] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(001207) [18:55:56] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001207) [18:55:56] Save config: /var/lib/waydroid/waydroid.cfg
(001207) [18:55:56] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(001207) [18:55:56] New background process: pid=139141, output=background
(001207) [18:55:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(139076) [18:56:12] waydroidusermonitor: Received transaction: 1
(139076) [18:56:12] Android with user 0 is ready
(139076) [18:56:12] % adb start-server
(139076) [18:56:12] % adb connect 192.168.240.112
already connected to 192.168.240.112:5555
(139076) [18:56:12] Established ADB connection to Waydroid device at 192.168.240.112.
(001207) [18:59:26] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(139076) [18:59:33] waydroidusermonitor: Received transaction: 2
(169855) [19:02:09] Starting waydroid session
(169855) [19:02:09] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(169855) [19:02:09] RuntimeError: Already tracking a session
(170969) [19:02:13] Starting waydroid session
(170969) [19:02:13] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(170969) [19:02:13] RuntimeError: Already tracking a session
(001207) [19:03:12] waydroidhardware: Received transaction: 3
(001207) [19:03:12] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [19:03:12] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
lxc-freeze: waydroid: ../src/lxc/freezer.c: do_freeze_thaw: 46 Failed to freeze waydroid
lxc-freeze: waydroid: ../src/lxc/tools/lxc_freeze.c: lxc_freeze_main: 88 Failed to freeze /var/lib/waydroid/lxc:waydroid
(001207) [19:03:12] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001207) [19:03:12] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(171855) [19:03:16] Starting waydroid session
(171855) [19:03:16] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(171855) [19:03:16] RuntimeError: Already tracking a session
(172149) [19:03:23] Run waydroid -h for usage information.
(172250) [19:03:30] ERROR: Action "init" needs root access
(172250) [19:03:30] See also: <https://github.com/waydroid>
(172250) [19:03:30] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(172313) [19:03:35] Run waydroid session -h for usage information.
(172418) [19:03:44] Starting waydroid session
(172418) [19:03:44] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(172418) [19:03:44] RuntimeError: Already tracking a session
(172519) [19:03:51] Starting waydroid session
(172519) [19:03:51] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(172519) [19:03:51] RuntimeError: Already tracking a session
(001207) [19:04:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(001207) [19:04:04] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
(001207) [19:04:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(001207) [19:04:04] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(001207) [19:04:04] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001207) [19:04:04] % umount /var/lib/waydroid/rootfs/vendor
(001207) [19:04:04] % umount /var/lib/waydroid/rootfs/vendor
(001207) [19:04:04] % umount /var/lib/waydroid/rootfs
(001207) [19:04:04] % umount /var/lib/waydroid/rootfs
(173143) [19:04:07] Starting waydroid session
(173148) [19:04:07] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(173148) [19:04:07] % modprobe -q ashmem_linux
(173148) [19:04:07] % chmod 666 -R /dev/binder
(173148) [19:04:07] % chmod 666 -R /dev/vndbinder
(173148) [19:04:07] % chmod 666 -R /dev/hwbinder
(173148) [19:04:07] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(173148) [19:04:07] % chmod 777 -R /dev/dri
(173148) [19:04:07] % chmod 777 -R /dev/video0
(173148) [19:04:07] % chmod 777 -R /dev/video1
(173148) [19:04:07] % chmod 777 -R /dev/video2
(173148) [19:04:07] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(173148) [19:04:07] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(173148) [19:04:07] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(173148) [19:04:07] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(173148) [19:04:07] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(173148) [19:04:07] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(173148) [19:04:07] Save config: /var/lib/waydroid/waydroid.cfg
(173148) [19:04:07] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(173148) [19:04:07] New background process: pid=173209, output=background
(173148) [19:04:07] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(173143) [19:04:17] waydroidusermonitor: Received transaction: 1
(173143) [19:04:17] Android with user 0 is ready
(173143) [19:04:17] % adb start-server
(173143) [19:04:17] % adb connect 192.168.240.112
already connected to 192.168.240.112:5555
(173143) [19:04:17] Established ADB connection to Waydroid device at 192.168.240.112.
(173143) [19:04:37] waydroidusermonitor: Received transaction: 2
(173143) [19:04:37] waydroidusermonitor: Received transaction: 2
(173148) [19:34:34] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(173143) [19:34:35] waydroidusermonitor: Received transaction: 2
(173143) [19:34:46] waydroidusermonitor: Received transaction: 2
(173143) [19:34:46] waydroidusermonitor: Received transaction: 2
(173143) [19:41:03] waydroidusermonitor: Received transaction: 2
(537512) [19:48:28] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(539779) [19:48:30] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(546727) [19:48:38] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING

`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by sujoshua** [comment]
Wechat doesn't support x64 arch. you need an arm translation. If you are new to waydroid, I recommend you use libhoudini. you may wanna try [waydroid_script](https://github.com/casualsnek/waydroid_script) to install it.

**Comment by sujoshua** [comment]
If you just wanna wechat run on linux. Why not have a try on WeChat linux, which is supported officially by Tencent.
