### ISSUE TITLE
[BUG] waydroid init -f requires System OTA and Vendor OTA URLs

### ISSUE THREAD

**Issue by meeuw** [waydroid/waydroid#1550]
### Describe the bug

According to https://docs.waydro.id/faq/using-custom-waydroid-images

waydroid init -f should be executed after placing custom images in /etc/waydroid-extra/images/

This worked for me but since waydroid-1.4.3 it fails with the following error message:

ERROR: You must provide 'System OTA' and 'Vendor OTA' URLs.

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Fedora 40

### Kernel version

6.10.6-200.fc40.x86_64

### Desktop Environment

GNOME 40

### GPU

AMD Ryzen™ 5 5600X × 12

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

Please let me know if you really need these.

**Comment by meeuw** [comment]
@aleasto, I think you caused this regression, PTAL: c312b3fc94fb158df9c74fc20ea81c194b525caa

**Comment by aleasto** [comment]
Ugh you're right

**Comment by aleasto** [comment]
Please test and leave karma: https://bodhi.fedoraproject.org/updates/FEDORA-2024-6f01189cc4

**Comment by meeuw** [comment]
Great! Thanks a lot, works like a charm.

Is the `-f` option still required? Should the FAQ be updated?

**Comment by aleasto** [comment]
Looks like the doc page assumes that you were previously already using waydroid with the OTA download mechanism, since it says to "re-init".

Otherwise you don't need`-f/--force`.
