### ISSUE TITLE
[BUG] Refuses to work at all

### ISSUE THREAD

**Issue by EJSnow** [waydroid/waydroid#1555]
### Describe the bug

So I thought I'd try this out on Pop OS 22.04, since that supports Wayland, and I wanted to try Waydroid to run a few Android games so I can ditch Windows altogether (the games are also on Windows, but you can't very well emulate them on Linux because they're UWP). After getting Waydroid installed, I couldn't get any farther than the first window because this error is given when I click download:
```
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.9.3-76060903-generic
Binder node "binder" for waydroid not found
```
Nice one, Waydroid.

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Pop!_OS 22.04 LTS

### Kernel version

6.9.3-76060903-generic

### Desktop Environment

GNOME 42.9

### GPU

Intel HD Graphics 4000

### Logs

can't, practically none of the files exist.

**Comment by Quackdoc** [comment]
PopOS does not currently support waydroid due to the removal of the kernel modules we rely on. Closing as a duplicate of all the other binder_linux not found issues.

**Comment by EJSnow** [comment]
Okay, thanks. Good to know. I'm probably not going to mess with Linux for a while, since Windows 10 is still working fine for me, it's just a little slow.

**Comment by luanmdlima** [comment]
Is there some sort of workaround(PopOS 22.04 LTS), or should I just try some other alternative application?

**Comment by neonmodder123** [comment]
yes, there is a workaround (sorry for the late reply). clone the anbox-modules github repo (git clone https://github.com/choff/anbox-modules.git), then (cd anbox-modules), after that (chmod +x INSTALL.sh), then (sudo .INSTALL.sh). after that, waydroid should work!

**Comment by chnoack** [comment]
you might install waydroid that way, but it does not run reliably. On my PopOS 24.04 LTS it crashes often and then unfortunately freezes the whole Cosmic UI.

**Comment by neonmodder123** [comment]
It's not stable but works
