### ISSUE TITLE
[BUG]Says to report this

### ISSUE THREAD

**Issue by iidogninjx1** [waydroid/waydroid#1557]
### Describe the bug

![Screenshot_20240907_115719](https://github.com/user-attachments/assets/d8f3461e-f186-4e0f-a5c6-36ed761bbe97)
i need help with this

### Waydroid version

steam deck

### Device

Linux Desktop

### Operating System

steamos 

### Kernel version

6.1.52-valve16-1-neptune-61

### Desktop Environment

steamos

### GPU

AMD Radeon Graphics

### Logs

it wont install

**Comment by JamiKettunen** [comment]
just try again, if you read the error it says there was a checksum mismatch between the expected file contents and what you ended up with

**Comment by Quackdoc** [comment]
closing as stale, if this is still an issue it can be re-opened, but try a few times first
