### ISSUE TITLE
[BUG] Black screen on startup

### ISSUE THREAD

**Issue by lolpowerluke** [waydroid/waydroid#1574]
### Describe the bug

I already tried `waydroid prop set persist.waydroid.multi_windows true`, which didnt work

I installed gapps using https://github.com/casualsnek/waydroid_script
with options 
```
android 11
install
gapps
```
commands I ran for the install:
```
sudo pacman -S lzip
git clone https://github.com/casualsnek/waydroid_script
cd waydroid_script
python3 -m venv venv
venv/bin/pip install -r requirements.txt
sudo venv/bin/python3 main.py
sudo venv/bin/python3 main.py install gapps
```

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Arch Linux

### Kernel version

6.6.52-1-lts

### Desktop Environment

KDE Plasma 6.1.5

### GPU

NVIDIA GeForce RTX 3060

### Logs

/var/lib/waydroid/waydroid.cfg
[waydroid.cfg.txt](https://github.com/user-attachments/files/17152938/waydroid.cfg.txt)
/var/lib/waydroid/waydroid.prop
[waydroid.prop.txt](https://github.com/user-attachments/files/17152941/waydroid.prop.txt)
/var/lib/waydroid/waydroid_base.prop
[waydroid_base.prop.txt](https://github.com/user-attachments/files/17152947/waydroid_base.prop.txt)
/var/lib/waydroid/waydroid.log
[waydroid.log.txt](https://github.com/user-attachments/files/17152949/waydroid.log.txt)
`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt](https://github.com/user-attachments/files/17152959/logcat.txt)
`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/user-attachments/files/17152966/dmesg.txt)

**Comment by Integral-Tech** [comment]
The same problem for me.
