### ISSUE TITLE
Waydroid locks up GUI on PureOS10/Librem5

### ISSUE THREAD

**Issue by steve5289** [waydroid/waydroid#158]
Following the instructions for install found here: https://docs.waydro.id/usage/install-on-desktops

It all goes well, until I try to launch the waydroid client as user purism. A few seconds later the phone gui is completely unresponsive, and it rings the vibrator twice for some reason. Device becomes usable again only after a reboot.

Files attached: 
[waydroid_test_syslog.log](https://github.com/waydroid/waydroid/files/7355195/waydroid_test_syslog.log): Copy of `journelctl -f` during the issue
[waydroid_test_container.log](https://github.com/waydroid/waydroid/files/7355196/waydroid_test_container.log): Copy of `journalctl -u waydroid-container -f`
[waydroid_test_client.log](https://github.com/waydroid/waydroid/files/7355197/waydroid_test_client.log): Copy of output of `waydroid show-full-ui`

**Comment by etam** [comment]
In my case phone GUI did not freeze, but I got the same kernel warnings in `etnaviv_gem_close_object` and waydroid UI failed to start.

**Comment by pini-gh** [comment]
Starting with kernel 5.18, Anbox is not available anymore on Linux phones.

Waydroid seems the most promising alternative. Would be great if this issue could be fixed.

**Comment by tfardet** [comment]
This was solved by [this post](https://forums.puri.sm/t/anyone-successfully-run-waydroid-on-librem-5/16757/8), replacing
``ro.hardware.gralloc=gbm`` with` ``ro.hardware.gralloc=default`` in ``/var/lib/waydroid/waydroid_base.prop``

**Comment by dos1** [comment]
Using `ro.hardware.gralloc=default` completely disables GPU acceleration. I have it working now with full acceleration on my Librem 5 and if all goes right everything that's needed to have it working will be included in LineageOS 18.1-based images by default (and in PureOS, as it needs updated kernel too) soon.

**Comment by sanecito** [comment]
> will be included in LineageOS 18.1-based images by default (and in PureOS, as it needs updated kernel too) soon.

Please comment back when GPU acceleration support with Waydroid is possible in PureOS; having access to apps that solve use cases with no current PureOS store app based solutions would help make Librem5 more usable

**Comment by dos1** [comment]
FWIW https://github.com/waydroid/android_hardware_waydroid/pull/24 and https://github.com/waydroid/android_external_mesa3d/pull/3 is the Waydroid side, while https://source.puri.sm/Librem5/debs/mesa/-/merge_requests/15 and https://source.puri.sm/Librem5/linux/-/merge_requests/621 is the PureOS side.

**Comment by aleasto** [comment]
Waydroid now works out of the box on Librem 5
