### ISSUE TITLE
[Feature] ARM version of waydroid for ARM computers such as the ones using the Snapdragon X Elite

### ISSUE THREAD

**Issue by defiling9046** [waydroid/waydroid#1582]
### Is your feature request related to a problem? Please describe.

It’s sad not being able to run many Android applications that only have ARM support such as Fortnite without going through a lot of hoops that don’t work for many applications.

### Describe the solution you'd like.

An ARM version of Waydroid that runs natively ARM Android applications.

### Describe alternatives you've considered.

Trying Raspberry Pi 5 that has an ARM chip with the one custom Android Rom that it has but it has terrible performance.

### Additional context

It would be nice as then this would open up the ability of running mobile game ports of PC games that have anti cheat that doesn’t work on Linux.

**Comment by abtye** [comment]
Waydroid is written in Python, and I have seen others successfully running it on Armbian, so Waydroid can run on ARM devices. And the system image (Lineage OS) it uses has an ARM version, see [Waydroid | Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/)

**Comment by Quackdoc** [comment]
Waydroid does run arm on arm devices.

**Comment by defiling9046** [comment]
That's why it's a feature request @Quackdoc

**Comment by Quackdoc** [comment]
when you run waydroid on arm devices, everything is natively arm, If there's something else you wanted, you're not getting your point through. 

can you elaborate more?

**Comment by defiling9046** [comment]
so does waydroid work on arm? because on the website it says it only works on x86.

**Comment by defiling9046** [comment]
my fault. rhought it only ran on x86

**Comment by SalahAdDin** [comment]
> Waydroid is written in Python, and I have seen others successfully running it on Armbian, so Waydroid can run on ARM devices. And the system image (Lineage OS) it uses has an ARM version, see [Waydroid | Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/)

does it support installing ARM apps?

**Comment by abtye** [comment]
> > Waydroid is written in Python, and I have seen others successfully running it on Armbian, so Waydroid can run on ARM devices. And the system image (Lineage OS) it uses has an ARM version, see [Waydroid | Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/)
> 
> does it support installing ARM apps?

Of course

**Comment by SalahAdDin** [comment]
> > > Waydroid is written in Python, and I have seen others successfully running it on Armbian, so Waydroid can run on ARM devices. And the system image (Lineage OS) it uses has an ARM version, see [Waydroid | Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/)
> > 
> > 
> > does it support installing ARM apps?
> 
> Of course

without using private libraries or installing extra packages?

**Comment by abtye** [comment]
> > > > Waydroid is written in Python, and I have seen others successfully running it on Armbian, so Waydroid can run on ARM devices. And the system image (Lineage OS) it uses has an ARM version, see [Waydroid | Source Forge](https://sourceforge.net/projects/waydroid/files/images/system/lineage/)
> > > 
> > > 
> > > does it support installing ARM apps?
> > 
> > 
> > Of course
> 
> without using private libraries or installing extra packages?

Yes. By the way, why don't you try it first before asking?
