### ISSUE TITLE
Meta: Add repo summary

### ISSUE THREAD

**Issue by TPS** [waydroid/waydroid#159]
This repo is being highlighted by GitHub!  Congrats!  (It showed up in the Trending feed, which is how I found it.)  Could y'all add a 1-line summary in the repo settings so that description appears in the feed?  Else, folks won't know what they're seeing.  (I just happen to be the inquisitive type.)  Even something as simple as "Android on Linux" would be great.

**Comment by electrikjesus** [comment]
Done. Thanks

**Comment by TPS** [comment]
Thank all y'all! 🙇🏾‍♂️
