### ISSUE TITLE
[BUG] Incorrect Vulkan driver on Broadwell (and potentially Haswell)

### ISSUE THREAD

**Issue by mrvictory1** [waydroid/waydroid#1604]
### Describe the bug

Waydroid assigns "ro.hardware.vulkan=intel" in waydroid_base.prop file. "intel_hasvk" is used by iGPUs found on Intel Core 4th and 5th generation CPUs instead of "intel". As a result Vulkan does not work at all. Changing "intel" to "intel_hasvk" allows Vulkan to work in Waydroid. 

![Ekran Görüntüsü_20241029_210539](https://github.com/user-attachments/assets/81d57aa0-39af-4d7e-acb1-0d276cf2def5)

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Nobara Linux 40 KDE Plasma

### Kernel version

6.11.3-200.fsync.fc40.x86_64

### Desktop Environment

KDE Plasma

### GPU

Intel HD 6000

### Logs

are log files needed?

**Comment by mrvictory1** [comment]
Waydroid probes current kernel module and determines driver based on that, Broadwell also uses i915 so this method fails
https://github.com/waydroid/waydroid/blob/5000c9703de873e4f477ebcdd3556ad163252115/tools/helpers/gpu.py#L25

**Comment by Quackdoc** [comment]
If anyone has a good idea for a better way to probe which driver to use without needing to rely on things like eglinfo it would be nice to hear some ideas

**Comment by mrvictory1** [comment]
inxi has GPU ID values for Broadwell and Haswell. GPU ID can be found at `/sys/class/drm/card1/device/device`. I have 0x1626 which matches Broadwell.
https://github.com/smxi/inxi/blob/15a55d0b948d4ddaffd5bfb266d4d12077b8fc39/inxi#L18215

**Comment by Xtr126** [comment]
This is 

> If anyone has a good idea for a better way to probe which driver to use without needing to rely on things like eglinfo it would be nice to hear some ideas

This is what Bliss OS does to detect GPU generation and set hasvk accordingly https://github.com/BlissRoms-x86/device_generic_common/blob/6017b7d8071e148623efca41531fc1c5ff2a6092/init.sh#L583

**Comment by mrvictory1** [comment]
On Nobara Linux 40 with 6.11.8-200.fsync.fc40.x86_64 I have slightly different paths:
```
$ ls /sys/kernel/debug/dri/
0000:00:02.0/ 1/            128/ 
```

**Comment by aleasto** [comment]
Sorry, I must have checked wrong cause it only depends on debugfs so it's widely available.
I'll be implementing that.
