### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [waydroid/waydroid#161]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Update candidates for the tool implementations:
A)
```diff
-            timeout = timeout - 1
+            timeout -= 1
```

B)
```diff
-            tries = tries - 1
+            tries -= 1
```

**Comment by aleasto** [comment]
It doesn't really matter, but if you care about it you should create a pull request, not an issue ;)
