### ISSUE TITLE
[Feature] Support for KDE fullscreen

### ISSUE THREAD

**Issue by jsommr** [waydroid/waydroid#1611]
### Is your feature request related to a problem? Please describe.

Waydroid already opens in fullscreen via show-full-ui, but by pressing alt-F3 and selecting More Actions -> Fullscreen, all gestures on the edges in KDE are disabled, eg. if you have a panel at the bottom, and Waydroid isn't marked fullscreen in a KDE context, then swiping up from the bottom reveals the panel instead of the Android menu (I'm using a touchscreen). When the window is marked fullscreen, all KDE gestures are disabled (beside the three finger ones which doesn't interfere with Waydroid).

The problem is that Waydroid stops rendering the moment I mark the window as fullscreen (animations turn into a still-image). It reacts to touch events, the sound works, everything basically works but nothing is rendered until i remove focus from Waydroid. Like if I press on an app in Waydroid, it's started (I can hear that if the app has sound), but the UI doesn't render it before I remove focus from Waydroid, like alt-tabbing to another program. As soon as Waydroid receives focus again, it stops rendering.

If I enable multi_windows `waydroid prop set persist.waydroid.multi_windows true`, then it works, also in show-full-ui. I suspect this is because of the transparent passthrough window you have used for this feature because it removes focus from Waydroid that can now be rendered since it's in the background - similar to when I alt-tab to a window on top of Waydroid that thereby loses focus, and again is able to render.

The reason I'd like to have Waydroid running in KDE, as opposed to a separate TTY, is that for a touchscreen without a keyboard, nothing beats being able to swipe between desktops using KDE's three finger gesture - easily going from Waydroid to KDE and back again.

### Describe the solution you'd like.

I'd like to be able to mark Waydroid as "KDE fullscreen" on Wayland without having to use multi_windows.

### Describe alternatives you've considered.

I have tried all combinations of KDE window rules to see if something could make Waydroid render in fullscreen. No luck.

Then I've tried a bunch of nested wayland compositors, but it's not a good experience:

#### kwin_wayland
Visible screen tearing when using OpenGL 2 or OpenGL ES. No tearing when using QPainter but with a substantial reduction in performance. Unticking "Reduce latency by allowing screen tearing artifacts in fullscreen windows" in "System Settings -> Display and Monitor -> Compositor" doesn't change anything.

Waydroid is turned upside down in kwin_wayland on Debian 12, but works as described above in Trixie.

#### Weston
Using the fullscreen-shell.so backend just shows a black screen. I think this might be an indicator that Waydroid stops rendering when it's in "Wayland fullscreen".

desktop-shell.so and kiosk-shell.so are able to render Waydroid but:
* When switching KDE desktops by swiping three fingers from right to left (or the opposite), and swiping back to the Waydroid desktop, then Weston no longer reacts to touch. One has to press two fingers on the screen and "wiggle" them a bit before touch works again.
* I use 165% scaling in KDE and this is applied to Weston. The result is that Waydroid looks blurry. My assumption is that whatever is in Weston is rendered with a resolution of the screen's logical width and height, which is then upscaled.

#### Wayfire
Renders Waydroid in a resolution that uses logical width and height, then upscales it, making the ui look blurry. Forcing Wayfire to use my native resolution renders a gigantic window. Touch continues to work after swiping desktops.

If I use the x11 backend then no scaling is applied and Waydroid looks sharp. But I can't assign KDE window rules to Wayfire x11, so it can't be made fullscreen (!).

#### Mutter
Not easy to deal with. Pulls in a lot of dependencies for a KDE system (this is a 64 GB tablet). Haven't managed to make it start in a Wayland session (seems to use XWayland no matter what I try).

#### Sway, Phoc etc. (+ Wayfire)
Everything based on wlroots upscales things in a nested compositor causing a blurry ui.

So compositors won't fix the issue.

I think being able to set something like `waydroid prop set persist.waydroid.passthrough_window` to true, and use only that part of multi_windows, would be a nice toggle to have.

### Additional context

Applies to Debian 12 and Trixie. Waydroid is installed via the installation guide (yesterday - November 10th, 2024).

**Comment by jsommr** [comment]
Yes! I found an undocumented prop for enabling the subsurface that multi_windows use!
```bash
waydroid prop set persist.waydroid.use_subsurface true
```
Then restart `waydroid session stop && waydroid show-full-ui`

Now it runs in fullscreen without KDE's gestures interfering!!

**Comment by AngelJulioPumaMamani** [comment]
en lo personal solo encontre un metodo y es ocultar los paneles tanto de aplicaciones parte inferior y la barra de estado en la pare superior en manlaro kde, luego inicio en waydroid show-full-ui y funciona pantalla completa pero si mueves el cursor a los paneles estos se mostraran

**Comment by Isaac-Clarke** [comment]
> Yes! I found an undocumented prop for enabling the subsurface that multi_windows use!
> 
> waydroid prop set persist.waydroid.use_subsurface true
> Then restart `waydroid session stop && waydroid show-full-ui`
> 
> Now it runs in fullscreen without KDE's gestures interfering!!

Where do I put this?

**Comment by AfSaft** [comment]
> > Yes! I found an undocumented prop for enabling the subsurface that multi_windows use!
> > waydroid prop set persist.waydroid.use_subsurface true
> > Then restart `waydroid session stop && waydroid show-full-ui`
> > Now it runs in fullscreen without KDE's gestures interfering!!
> 
> Where do I put this?

these are terminal commands that you need to paste them into your terminal manager

**Comment by AfSaft** [comment]
> Yes! I found an undocumented prop for enabling the subsurface that multi_windows use!
> 
> waydroid prop set persist.waydroid.use_subsurface true
> 
> Then restart `waydroid session stop && waydroid show-full-ui`
> 
> Now it runs in fullscreen without KDE's gestures interfering!!

@jsommr hi there. i ran into another problem and an ai adviced me to enable that prob to solve the issue but it didnt work. im trying to play a game that supposed to open in fullscreen (not maximize) but waydroid being stubborn and not opening the app in fullscreen
