### ISSUE TITLE
Can't access navigation buttons on the bottom.

### ISSUE THREAD

**Issue by jtfonebooth** [waydroid/waydroid#1615]
This is my first time posting on github so please excuse me if I don't know proper etiquette.

On the steam deck, after having installed waydroid, the mouse can move around the whole window except over a small invisible bar covering the bottom of the screen, making the navigation buttons impossible to press. Changing the resolution of waydroid via "waydroid prop set persist.waydroid.width/height" did not fix the issue at all. The issue only occurs in game mode, not desktop mode.

This was for a friend so I don't have access to any version numbers or any potentially useful information. Sorry.

**Comment by kevin34ct** [comment]
I have the same issue.
