### ISSUE TITLE
how do i icrease android free storage space?

### ISSUE THREAD

**Issue by mamalubitlal** [waydroid/waydroid#1618]
### Describe the bug

i want more free space in waydroid but dont know how.is there any way?

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Ubuntu 22.04.5 LTS

### Kernel version

6.8.0-48-generic

### Desktop Environment

GNOME 42.9

### GPU

idk

### Logs

i think it doesnt needs it

**Comment by Genxster1998** [comment]
Just close it already. Data resides in your home directory. If you maintain seperate home partition , extend that otherwise close this redundant issue, system/vendor.img size manipulation is available in docs.
