### ISSUE TITLE
waydroid : Depends: python3-gbinder but it is not going to be installed

### ISSUE THREAD

**Issue by y-shevchenko** [waydroid/waydroid#162]
root@pc:/home/installer# sudo apt install waydroid -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 waydroid : Depends: python3-gbinder but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karthickbabu** [comment]
Hello I'm facing the same issue when I try to install waydroid on raspberry pi. Can I know if you resolve this?

**Comment by y-shevchenko** [comment]
> Hello I'm facing the same issue when I try to install waydroid on raspberry pi. Can I know if you resolve this?

export DISTRO="focal"

**Comment by Tim4497** [comment]
Not working still on ubuntu 20
