### ISSUE TITLE
Running waydroid cross-platform fails with ERROR: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by MaWalla** [waydroid/waydroid#163]
Foreword: on the native architecture (x86_64) it works when setup identically. I also know about Houdini, but haven't found anything regarding it... is it even available for Android 10?

So, waydroid works great on my computer natively, but many apps don't support its architecture (x86_64). Luckily qemu is a thing and you can chroot into root file systems with different architectures.

After some tinkering around, I found docker, which supports using different architectures with qemu out of the box, and x11docker to be the most convenient way to approach this.

so I set up waydroid according to https://docs.waydro.id/usage/install-on-desktops on debian arm64. When trying to run `waydroid init`, it fails, reporting:

```
[23:38:20] ERROR: [Errno 38] Function not implemented
[23:38:20] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

`waydroid log` dosn't work since waydroid isn't initialized yet, so I started my own investigation, setup remote debugging with IntelliJ IDEA (and Python plugin) and looked at where things go wrong. I found out that the following line was the cause:

`fcntl.ioctl(binderctrlfd.fileno(), BINDER_CTL_ADD, node_struct)`

which as of writing this is line 62 in tools/helpers/drivers.py

Since fcntl.ioctl is being called I went into the function and IDEA which just sent me to some cached directory (/home/mawalla/.cache/JetBrains/IntelliJIdea2021.2/python_stubs/-1576962306/fcntl.py if it helps anyone) where the function was defined but just empty (a comment explaining the function and a `pass` statement).

I thought that maybe something is missing from the debian provided arm64 binary for python, so I grabbed the Python 3.9.6 source and compiled it myself (within the arm64 container of course) and after running `./configure --enable-optimizations --prefix /opt/python-3.9.6` these lines popped up

```
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
```

So I ran `make -j8` and `make install` and tried it, set up a venv where I installed PyGObject (since gi was missing from my build, I followed the debian guide for pip/venv here: https://pygobject.readthedocs.io/en/latest/getting_started.html) and hit the same error again.

btw. for building the docker container, I set up qemu like that: https://wiki.archlinux.org/title/QEMU#Chrooting_into_arm/arm64_environment_from_x86_64

The image was built like this: `docker buildx build --platform linux/arm64 -t waydroid .` with those contents (excuse the mess please :D):

```
FROM debian:bullseye

RUN apt-get update && apt-get install -y curl systemd

RUN export DISTRO="bullseye" && \
    curl -# --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list && \
    mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list && \
    apt-get update

RUN apt-get install -y waydroid weston
RUN apt-get install -y git openssh-server vim
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev uuid-dev
RUN apt-get install -y wget && wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tar.xz
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && echo root:123 | chpasswd
RUN apt-get install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
```

I then ran it with this:

`x11docker --wayland --init="systemd" --pw="sudo" --clipboard --gpu -p --user="root" -i -- --privileged -v /home/mawalla/IdeaProjects/waydroid:/waydroid --platform=linux/arm64 -- waydroid bash`

I'm running all this on an AMD Ryzen 7 4700U with Arch Linux. I probably put waaayyy too much effort into this, but getting cross platform to work some way would be really incredible!

**Comment by aleasto** [comment]
This is out of scope for the project...
Consider using libhoudini (proprietary): https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation
