### ISSUE TITLE
[BUG] Can't connect to repo.waydro.id

### ISSUE THREAD

**Issue by kotenok2000** [waydroid/waydroid#1631]
### Describe the bug

When I run curl https://repo.waydro.id I get
curl: (7) Failed to connect to repo.waydro.id port 443 after 14101 ms: Couldn't connect to server
Apt update can't connect either.
I can't open it without a VPN. Did you block Russia?

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

ubuntu 24.04 amd64

### Kernel version

6.8.0-48-generic

### Desktop Environment

weston 13.0.0-4build3

### GPU

Vmware SVGA 3D

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Fuseteam** [comment]
cannot confirm, it works fine on my end
![image](https://github.com/user-attachments/assets/a3e14c8b-fc2c-46b8-a003-799982057d9b)
