### ISSUE TITLE
[BUG] Waydroid hangs after a while

### ISSUE THREAD

**Issue by Sarcasthik** [waydroid/waydroid#1642]
### Describe the bug

Starting waydroid apps and stuff after booting my system is fine, but after a random amount of time, the apps become partially unresponsive and look like they are bugged until they become completely unresponsive. 
For example, running NewPipe the first few minutes I can use the app like normal but then it stops playing videos even if it stills register the Back button and such. I have to restart waydroid service so it will work again until the next hang.

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

EndeavourOS

### Kernel version

6.12.4-arch1-1

### Desktop Environment

KDE Plasma 6

### GPU

Radeon RX 7900 GRE

### Logs

/var/lib/waydroid/waydroid.cfg
[waydroid.cfg.txt](https://github.com/user-attachments/files/18128917/waydroid.cfg.txt)

/var/lib/waydroid/waydroid.prop
[waydroid.prop.txt](https://github.com/user-attachments/files/18128920/waydroid.prop.txt)

/var/lib/waydroid/waydroid_base.prop
[waydroid_base.prop.txt](https://github.com/user-attachments/files/18128923/waydroid_base.prop.txt)

/var/lib/waydroid/waydroid.log
[waydroid.log](https://github.com/user-attachments/files/18129185/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt](https://github.com/user-attachments/files/18128926/logcat.txt)

`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/user-attachments/files/18128933/dmesg.txt)

**Comment by Sarcasthik** [comment]
This fixed my issue https://github.com/waydroid/waydroid/issues/576#issuecomment-1379131634

**Comment by Valentin06130** [comment]
Hello,

Waydroid makes my host machine totally hang,

No more Graphics UI interaction, no VT-Switch either, and fans go fast, typical of a kernel crash.

In hope my report proves useful.

Valentin
