### ISSUE TITLE
[BUG]waydroid says its running but is not running when checking status

### ISSUE THREAD

**Issue by jan-doez-animationz** [waydroid/waydroid#1656]
### Describe the bug

whenever i try to use a command it says ERROR: WayDroid container service is already running
i typed in waydroid status and it says 
waydroid status
Session:	STOPPED
Vendor type:	MAINLINE

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Linux Mint 22 x86_64 

### Kernel version

6.8.0-51-generic

### Desktop Environment

Cinnamon 6.2.9 

### GPU

Amd Ati Radeon Hd 7670m

### Logs

488503) [18:52:47] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(488503) [18:52:47] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(488503) [18:52:47] % aa-enabled --quiet
(488503) [18:52:47] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(488503) [18:52:47] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(488075) [18:57:02] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
(488256) [18:57:02] Starting waydroid session
(488256) [18:57:02] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(488256) [18:57:02] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
STOPPED
(488075) [18:57:02] % modprobe -q ashmem_linux
(488075) [18:57:02] % chmod 666 -R /dev/anbox-binder
(488075) [18:57:02] % chmod 666 -R /dev/anbox-vndbinder
(488075) [18:57:02] % chmod 666 -R /dev/anbox-hwbinder
(494253) [18:57:05] Starting waydroid session
(494253) [18:57:05] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(494253) [18:57:05] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
(494277) [18:57:27] Starting waydroid session
(494277) [18:57:27] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(494277) [18:57:27] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
(494407) [18:58:12] WayDroid session is stopped
(494973) [19:00:26] WayDroid session is stopped
(494980) [19:00:32] WayDroid session is stopped
(495132) [19:01:14] WayDroid session is stopped
(495158) [19:01:27] WayDroid session is stopped
(495160) [19:01:29] WayDroid session is stopped
(488075) [19:01:40] Hardware service is not even started
(488075) [19:01:40] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(488075) [19:01:40] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(488075) [19:01:40] % systemctl is-enabled -q nfcd
(000919) [19:01:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000919) [19:01:44] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000919) [19:01:44] % mkdir -p /dev/binderfs
(000919) [19:01:44] % mount -t binder binder /dev/binderfs
(000919) [19:01:44] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(000919) [19:01:44] % modprobe -q ashmem_linux
(000919) [19:01:44] % chmod 666 -R /dev/anbox-binder
(000919) [19:01:44] % chmod 666 -R /dev/anbox-vndbinder
(000919) [19:01:44] % chmod 666 -R /dev/anbox-hwbinder
(002454) [19:05:46] ERROR: Action "container" needs root access
(002454) [19:05:46] See also: <https://github.com/waydroid>
(002454) [19:05:46] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 77, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "container" needs root access

(002563) [19:06:07] WayDroid session is stopped
(002575) [19:06:11] Starting waydroid session
(002575) [19:06:11] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(002575) [19:06:11] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
(003127) [19:06:46] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003127) [19:06:46] *** output passed to waydroid stdout, not to this log ***
(003612) [19:13:18] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003612) [19:13:18] *** output passed to waydroid stdout, not to this log ***

**Comment by KenSharp** [comment]
So how was this fixed?

**Comment by CyberKite** [comment]
session ≠ container status presumably - run waydroid session start as your user account
