### ISSUE TITLE
crowdfounding campaign ended and difficult to find

### ISSUE THREAD

**Issue by polrus** [waydroid/waydroid#17]
Me and probably other ppl would like to donate - the crowdfounding camapaign is difficult to find 
and now it ended so no longer able to donate

maybe a plain and simple www with "about" , "donate", "demo video", and link to github would be a good option

**Comment by darkdragon-001** [comment]
You could also add a [_Sponsor_ button](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository) to this repository and transparently fund your project via [OpenCollective](https://opencollective.com/how-it-works) :wink:

**Comment by darkdragon-001** [comment]
@erfanoabdi what do you think?

**Comment by electrikjesus** [comment]
> You could also add a [_Sponsor_ button](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository) to this repository and transparently fund your project via [OpenCollective](https://opencollective.com/how-it-works) 😉

This is something we are working towards. Due to regional limitations, we had to start setting things up from the US, so the process is taking some time

**Comment by Quackdoc** [comment]
Donate button is now on the front page of the website for [opencollective](https://opencollective.com/waydroid/donate)
