### ISSUE TITLE
lxc error on Fedora 35

### ISSUE THREAD

**Issue by Tuxino88** [waydroid/waydroid#174]
Step to reproduce

1. sudo systemctl start waydroid-container.service

<details>
<summary>Waydroid log</summary>

(007315) [19:02:06] % chmod 666 -R /dev/anbox-binder
(007315) [19:02:06] % chmod 666 -R /dev/anbox-vndbinder
(007315) [19:02:06] % chmod 666 -R /dev/anbox-hwbinder
(007315) [19:02:06] Container manager is waiting for session to load
</details>

2. waydroid show-full-ui
[19:03:28] Starting waydroid session
[gbinder] WARNING: Service manager /dev/anbox-binder has died

<details>
<summary>Waydroid log</summary>

(007315) [19:02:06] % chmod 666 -R /dev/anbox-binder
(007315) [19:02:06] % chmod 666 -R /dev/anbox-vndbinder
(007315) [19:02:06] % chmod 666 -R /dev/anbox-hwbinder
(007315) [19:02:06] Container manager is waiting for session to load
(007620) [19:03:28] Starting waydroid session
(007620) [19:03:28] Save session config: /var/lib/waydroid/session.cfg
(007620) [19:03:28] UserMonitor service is not even started
(007620) [19:03:28] Clipboard service is not even started
(007315) [19:03:28] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(007315) [19:03:28] % waydroid-sensord /dev/anbox-hwbinder
(007315) [19:03:28] New background process: pid=7628, output=background
(007315) [19:03:28] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(007315) [19:03:28] % umount /var/lib/waydroid/rootfs/vendor
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwAccelerometerSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwGyroscopeSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwHumiditySensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwLightSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwMagnetometerSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwOrientationSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwPressureSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwProximitySensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwStepcounterSensor: Could not create sensorfw backend
[waydroid-sensors-daemon] failed to call load_plugin
[waydroid-sensors-daemon] Failed to create SensorfwTemperatureSensor: Could not create sensorfw backend
(007315) [19:03:28] % umount /var/lib/waydroid/rootfs
(007315) [19:03:28] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(007315) [19:03:28] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(007315) [19:03:28] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(007315) [19:03:28] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(007315) [19:03:28] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(007315) [19:03:28] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(007315) [19:03:28] % chmod 777 -R /dev/ashmem
(007315) [19:03:28] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(007315) [19:03:28] % chmod 777 -R /dev/dri
(007315) [19:03:28] % chmod 777 -R /dev/fb0
(007315) [19:03:28] % chmod 777 -R /dev/video1
(007315) [19:03:28] % chmod 777 -R /dev/video0
(007315) [19:03:28] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(007315) [19:03:28] New background process: pid=7668, output=background
(007315) [19:03:29] Save session config: /var/lib/waydroid/session.cfg
[gbinder] Service manager /dev/anbox-hwbinder has appeared
[waydroid-sensors-daemon] Waydroid Sensors HAL service ready.
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"

</details>

[dmesg.log](https://github.com/waydroid/waydroid/files/7391619/dmesg.log)

[waydroid-logcat.log](https://github.com/waydroid/waydroid/files/7391641/waydroid-logcat.log)

Hardware Thinkpad T450 intel i5 5300u iHD5500

**The problem seems to be waydroid-sensors , uninstalling waydroid starts normally.**

**Comment by Essasetic** [comment]
Just to confirm this is still an issue, just had it on my Fedora 35 laptop.

Hardware: Thinkpad X1 Carbon Gen 9, i7 1165G7, Iris Xe

**Comment by aleasto** [comment]
Do not install `waydroid-sensors`.

I took over the fedora packaging and this is not an issue anymore
