### ISSUE TITLE
Failed to get service waydroidplatform, trying again...

### ISSUE THREAD

**Issue by mt190502** [waydroid/waydroid#183]
Hello, I installed ubuntu on my computer today and after everything I installed this program from the waydro.id site according to the instructions. When I type this command after sudo waydroid init command, lineageos logo comes up. After waydroid doesn't work. I reinstalled Waydroid by deleting everything. It still didn't work. Some errors I caught:

/var/lib/waydroid/waydroid.log
004270) [17:42:26] Starting waydroid session
(004270) [17:42:26] Save session config: /var/lib/waydroid/session.cfg
(004270) [17:42:26] UserMonitor service is not even started
(004270) [17:42:26] Clipboard service is not even started
(005124) [17:43:43] WayDroid container is STOPPED
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"

![image](https://user-images.githubusercontent.com/62564400/138599587-b9cc6813-0757-41fb-ac18-a2707009b68d.png)

System: Ubuntu
DE: Gnome Wayland
Kernel: Xanmod

**Comment by rizzini** [comment]
To understand what you just blindly did -> https://www.kernel.org/doc/html/latest/accounting/psi.html

**Comment by Araly** [comment]
I have the same issues, I've added psi=1 (although I use refind instead of grub) and it still doesn't work. Is there a way I can check whether the kernel has the right option or not ?

**Comment by discover02** [comment]
> I have the same issues, I've added psi=1 (although I use refind instead of grub) and it still doesn't work. Is there a way I can check whether the kernel has the right option or not ?

cat /proc/cmdline

**Comment by Araly** [comment]
```
$ cat /proc/cmdline
root=UUID=5f88c23a-4809-4c58-808f-0d751f3d920e rw quiet loglevel=3 nowatchdog psi=1 initrd=boot\initramfs-linux.img
```

So I imagine it worked. I wonder what's the issue now

**Comment by aleasto** [comment]
Closing as the original issue was resolved.
Open a new issue including all the logs if you still have other issues
