### ISSUE TITLE
LXC throws error

### ISSUE THREAD

**Issue by bruhmanist** [waydroid/waydroid#188]
(030219) [17:48:32] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(030219) [17:48:32] *** output passed to waydroid stdout, not to this log ***
(030222) [17:48:37] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(030222) [17:48:37] *** output passed to waydroid stdout, not to this log ***
(030227) [17:48:44] % chmod 666 -R /dev/anbox-binder
(030227) [17:48:44] % chmod 666 -R /dev/vndbinder
(030227) [17:48:44] % chmod 666 -R /dev/hwbinder
(030227) [17:48:44] Container manager is waiting for session to load
(030233) [17:48:49] % chmod 666 -R /dev/anbox-binder
(030233) [17:48:49] % chmod 666 -R /dev/vndbinder
(030233) [17:48:49] % chmod 666 -R /dev/hwbinder
(030233) [17:48:49] Container manager is waiting for session to load
(030241) [17:49:15] Save session config: /var/lib/waydroid/session.cfg
(030241) [17:49:15] UserMonitor service is not even started
(030241) [17:49:15] Clipboard service is not even started
(030227) [17:49:16] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(030227) [17:49:16] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(030227) [17:49:16] % umount /var/lib/waydroid/rootfs/vendor
(030227) [17:49:16] % umount /var/lib/waydroid/rootfs
(030227) [17:49:16] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: WARNING: source write-protected, mounted read-only.
(030227) [17:49:16] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(030227) [17:49:16] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
mount: /var/lib/waydroid/rootfs/vendor: WARNING: source write-protected, mounted read-only.
(030227) [17:49:16] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(030227) [17:49:16] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(030227) [17:49:16] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(030227) [17:49:16] % chmod 777 -R /dev/ashmem
(030227) [17:49:16] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(030227) [17:49:16] % chmod 777 -R /dev/dri
(030227) [17:49:16] % chmod 777 -R /dev/fb0
(030227) [17:49:16] % chmod 777 -R /dev/video1
(030227) [17:49:16] % chmod 777 -R /dev/video0
(030227) [17:49:16] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(030227) [17:49:16] New background process: pid=30270, output=background
lxc-start: waydroid: utils.c: safe_mount: 1204 Not a directory - Failed to mount "/dev/vndbinder" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/vndbinder"
lxc-start: waydroid: utils.c: safe_mount: 1204 Not a directory - Failed to mount "/dev/hwbinder" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/hwbinder"
lxc-start: waydroid: conf.c: mount_entry: 1952 No such file or directory - Failed to mount "tmpfs" on "/usr/lib/x86_64-linux-gnu/lxc/tmp"
lxc-start: waydroid: conf.c: lxc_setup: 3353 Failed to setup mount entries
lxc-start: waydroid: start.c: do_start: 1218 Failed to setup container "waydroid"
lxc-start: waydroid: sync.c: __sync_wait: 36 An error occurred in another process (expected sequence number 5)
lxc-start: waydroid: start.c: __lxc_start: 1999 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 314 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 958 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(030227) [17:49:16] waiting 10 seconds for container to start...
(030227) [17:49:17] waiting 9 seconds for container to start...
(030227) [17:49:18] waiting 8 seconds for container to start...
(030227) [17:49:19] waiting 7 seconds for container to start...
(030227) [17:49:20] waiting 6 seconds for container to start...
(030227) [17:49:21] waiting 5 seconds for container to start...
(030227) [17:49:22] waiting 4 seconds for container to start...
(030227) [17:49:23] waiting 3 seconds for container to start...
(030227) [17:49:24] waiting 2 seconds for container to start...
(030227) [17:49:25] waiting 1 seconds for container to start...
(030227) [17:49:26] ERROR: container failed to start
(030227) [17:49:26] See also: <https://github.com/waydroid>
(030227) [17:49:26] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

(030299) [17:49:26] UserMonitor service is not even started
(030299) [17:49:26] Clipboard service is not even started
(030241) [17:49:27] UserMonitor service is not even started
(030241) [17:49:27] Clipboard service is not even started
(030300) [17:49:35] Starting waydroid session
(030300) [17:49:35] Save session config: /var/lib/waydroid/session.cfg
(030300) [17:49:35] UserMonitor service is not even started
(030300) [17:49:35] Clipboard service is not even started

**Comment by aleasto** [comment]
Fedora is now correctly supported.

Missing information on the original report, assuming fixed by now
