### ISSUE TITLE
Debian Bookworm "init" fails due to missing "vndbinder"

### ISSUE THREAD

**Issue by Zocker1999NET** [waydroid/waydroid#190]
Followed [this document](https://docs.waydro.id/usage/install-on-desktops) to install waydroid, but stopped at `sudo waydroid init` due to:
```
[20:30:26] ERROR: Binder node "vndbinder" for waydroid not found
[20:30:26] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
Full Log shows this:
```
(285724) [20:30:26] % modprobe binder_linux devices="anbox-vndbinder,anbox-hwbinder"
(285724) [20:30:26] ERROR: Binder node "vndbinder" for waydroid not found
(285724) [20:30:26] See also: <https://github.com/waydroid>
(285724) [20:30:26] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 144, in setupBinderNodes
    raise OSError('Binder node "vndbinder" for waydroid not found')
OSError: Binder node "vndbinder" for waydroid not found
```
From other issues I found out that `ashmem_linux` and `binder_linux` are required kernel modules, which are loaded on my system. I recently removed/purged anbox from my system to try out waydroid "in a clean way". However this seems to me like waydroid requires anbox as a dependency but this was not documented elsewhere as I see it.

I use Linux version `5.14.0-2` (from `uname -r`), Debian Bookworm/Sid as distro and tried to use waydroid 1.2.0

Can someone help?

**Comment by teppyboy** [comment]
Add `binder.devices=binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder` to boot parameters. See https://wiki.archlinux.org/title/kernel_parameters if you don't know how to. And you must have a kernel with ashmem & binder, if you don't then install `linux-zen` (https://liquorix.net/ for Debian/Ubuntu)

**Comment by Zocker1999NET** [comment]
I have added the kernel parameters:
```
root@thinkie:~# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-5.14.0-4-amd64 root=/dev/mapper/thinkie--vg-root ro mem_sleep_default=deep binder.devices=binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder quiet splash
```
And I have a kernel (the default debian amd64 kernel) with `ashmem_linux` and `binder_linux` module:
```
root@thinkie:~# lsmod | grep -E 'ashmem|binder'
binder_linux          212992  0
ashmem_linux           20480  0
```
still `waydroid init` fails:
```
root@thinkie:~# waydroid init
[13:00:06] ERROR: Binder node "vndbinder" for waydroid not found
[13:00:06] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
```
(202609) [13:01:26] % modprobe binder_linux devices="anbox-vndbinder,anbox-hwbinder"
(202609) [13:01:26] ERROR: Binder node "vndbinder" for waydroid not found
(202609) [13:01:26] See also: <https://github.com/waydroid>
(202609) [13:01:26] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 144, in setupBinderNodes
    raise OSError('Binder node "vndbinder" for waydroid not found')
OSError: Binder node "vndbinder" for waydroid not found
```

Have I misconfigured something? Or is this kernel really not supported (yet)?

If not required, I do not want to install any other kernel as the default one by Debian.

**Comment by teppyboy** [comment]
Youre using debian, and the default kernel AFAIK doesnt have required
modules to use Anbox/Waydroid, in this case use Liquorix kernel (you can
search google for that)

Vào 20:04, Th 3, 23 thg 11, 2021 Felix Stupp ***@***.***> đã
viết:

**Comment by Zocker1999NET** [comment]
Okay, but for anbox, I did not required a new / different kernel, do you require different kernel modules or could it be that the snap of anbox is shipped with those?

Also, if for a common Debian user further kernel modules are required, than a change of the docs would be good as they claim it "just works (TM)" on Debian systems, which, as I understand it, is now not the case.

**Comment by unalkalkan** [comment]
same issue here for Debian Buster

**Comment by benintech** [comment]
Same issue in Debian Buster.

What I noticed :
Anbox, installed from repos (`apt install anbox`) doesn't work :
```
$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2022-11-12 10:01:36] [launch.cpp:202@operator()] Session manager failed to become ready
```

Waydroid doesn't work either :
```
$ sudo waydroid init
[22:13:27] ERROR: Binder node "vndbinder" for waydroid not found
```

Anbox installed from snapstore works ok.

I suspect both Anbox and Waydroid errors have the same reason, something lacking in Debian's kernel. Anbox snap install does probably install what's lacking.

Did someone manage to make Waydroid or Anbox (not snap) work in Debian 11 ?

**Comment by aleasto** [comment]
The currently supported debian (bullseye, bookworm and sid) and ubuntu (focal, jammy, rolling) versions all work with the default kernel and no additional modules to be compiled.
We don't officially support buster, but indeed you would need to compile the binder module for it if it's not included in the default package.

**Comment by benintech** [comment]
Sorry my mistake, I misspelled, I was installing it on Bullseye, not Buster.

Everything works fine now : the `missing vndbinder` error was due to a previous installation of Anbox (through snap). It seems that both Anbox and Waydroid can not be installed at the same time.

Removing Anbox (`snap remove anbox`) and rebooting solved the problem.

**Comment by unalkalkan** [comment]
> Sorry my mistake, I misspelled, I was installing it on Bullseye, not Buster.
> 

+1 on that, I was using Bullseye too. Don't know why I wrote Buster.

> Everything works fine now : the `missing vndbinder` error was due to a previous installation of Anbox (through snap). It seems that both Anbox and Waydroid can not be installed at the same time.
> 
> Removing Anbox (`snap remove anbox`) and rebooting solved the problem.

In my case Anbox was not installed anymore but the kernel modules (`ashmem` and `binder`) was still there. Just removed them and Waydroid started working now!

**Comment by benintech** [comment]
> In my case Anbox was not installed anymore but the kernel modules (`ashmem` and `binder`) was still there. Just removed them and Waydroid started working now!

Great !
Maybe that's something to be added to the installation instructions : remove all traces of Anbox if it has been previously installed.
