### ISSUE TITLE
Use polkit instead of sudo

### ISSUE THREAD

**Issue by SameExpert** [waydroid/waydroid#191]
Currently, to have root privillage in waydroid session, `sudo` is called, and to make it not ask for password, `sudo -v` is run every few mins to keep it consistant. This affects battery and prevents the device from deep sleep.

Having a polkit (maybe like [this](https://vwangsf.medium.com/creating-a-d-bus-service-with-dbus-python-and-polkit-authentication-4acc9bc5ed29)) rule would not need to execute any command like `sudo` and can have root privillage automatically when needed. This would also fix #48.

**Comment by LecrisUT** [comment]
Should polkit files be created and maintained on the main project or on the package manager repo?

**Comment by SameExpert** [comment]
Having them in the main project would be good.

**Comment by aleasto** [comment]
Waydroid scripts do not call sudo anymore
