### ISSUE TITLE
Is there any plan to support X11?

### ISSUE THREAD

**Issue by rizzini** [waydroid/waydroid#195]
I use Anbox on a daily basis for years now, but, sadly, it has just a few commits over the last months. We need a fresh project like this one. Is there any chance to make it available for X11 users as well?

**Comment by Babber** [comment]
I'd like to add that using Weston or similar compositors for Wayland is not an option for those (quite a lot of people) who e.g. use proprietary Nvidia drivers. As far as I can tell, there's no solution (of comparable quality) for us to run Android apps in a desktop environment other than Gnome or KDE at least.

I added this comment also to issue #382, but now I see, it's more fitting here.

**Comment by hopelessdecoy** [comment]
> 

I unfortunately seem to get a black screen in Weston when running the "waydroid show-full-ui"

**Comment by picklefan** [comment]
> you can simply start a weston session in your X11 session. Weston package sould be shipped within repos of every popular distribution. No need to restart X, it will run as normal window.
> 
> 1. Start a terminal and execute: waydroid session start &
> 2. Start weston manager (simply with Alt+F2 or from that terminal that you already started)
> 3. go into the weston, and start terminal there (look onto left upper corner)
> 4. in this terminal execute waydroid show-full-ui

Finally got the answer but for me, steps 1 and 2 should be swapped.
I think this issue should be added to WIKI.

**Comment by 266-750Balloons** [comment]
I've had issues with weston in the past. To get it working, I've had to do ``` weston --use-pixman ```. Then it works like a charm.

**Comment by Splarkszter** [comment]
Linux Mint 21.1 AMD - Works fine using weston. Thank you a lot!

**Comment by odnanref** [comment]
ls -l /run/user/$UID/ <- you will see the wayland socket to use.

**Comment by Locutus64** [comment]
I personally don't think Wayland is even remotely ready for primetime. I'm with the OP in that I would like to see x11 support for Waydroid. Running this in a container or container like app really is not a solution.

**Comment by twaik** [comment]
Actually it is possible to use scrcpy for X11 displaying. And it is even more comfortable in some cases. Is it possible to make it work without `waydroid show-full-ui`?

**Comment by mubashir-rehman** [comment]
Network connection is not working in the weston.

**Comment by binex-dsk** [comment]
> I personally don't think Wayland is even remotely ready for primetime. I'm with the OP in that I would like to see x11 support for Waydroid. Running this in a container or container like app really is not a solution.

Don't care. Works for me.

**Comment by Simon-Bakken-Jantasuk** [comment]
> Network connection is not working in the weston.

Firewall issue

Look at the documentation from the archwiki, https://wiki.archlinux.org/title/Waydroid#Network

**Comment by s1nistr4** [comment]
> you can simply start a weston session in your X11 session. Weston package sould be shipped within repos of every popular distribution. No need to restart X, it will run as normal window.
> 
> 1. Start a terminal and execute: waydroid session start &
> 2. Start weston manager (simply with Alt+F2 or from that terminal that you already started)
> 3. go into the weston, and start terminal there (look onto left upper corner)
> 4. in this terminal execute waydroid show-full-ui

This doesn't work anymore. Running `waydroid session start &` gives an error saying "Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?" and immediately closes the session. If you try to run it directly through weston it gives the same error.

**Comment by SX-9** [comment]
> you can simply start a weston session in your X11 session. Weston package sould be shipped within repos of every popular distribution. No need to restart X, it will run as normal window.
> 
> 1. Start a terminal and execute: waydroid session start &
> 2. Start weston manager (simply with Alt+F2 or from that terminal that you already started)
> 3. go into the weston, and start terminal there (look onto left upper corner)
> 4. in this terminal execute waydroid show-full-ui
> 

Another solution I havent tested yet is to start waydroid in the background, connect it to adb, and use *scrcpy* to display the ui. Havent tested it yet but theoretically its supposed to work.

**Comment by hamad12a** [comment]
Since I don't have a graphics card, Weston runs very laggy and cannot operate smoothly at all.

**Comment by Canary233** [comment]
> > you can simply start a weston session in your X11 session. Weston package sould be shipped within repos of every popular distribution. No need to restart X, it will run as normal window.
> > 
> > 1. Start a terminal and execute: waydroid session start &
> > 2. Start weston manager (simply with Alt+F2 or from that terminal that you already started)
> > 3. go into the weston, and start terminal there (look onto left upper corner)
> > 4. in this terminal execute waydroid show-full-ui
> 
> Another solution I havent tested yet is to start waydroid in the background, connect it to adb, and use _scrcpy_ to display the ui. Havent tested it yet but theoretically its supposed to work.

Hi,I also want to use scrcpy to remotely connect waydroid, did you succeed?
