### ISSUE TITLE
Unable to share the clipboard although I have installed python-pyclip.

### ISSUE THREAD

**Issue by laichiaheng** [waydroid/waydroid#199]
I can't copy and paste texts to waydroid, such as my password.

**Comment by teppyboy** [comment]
give some logs first so we can analyze that

**Comment by SameExpert** [comment]
Can confirm the same issue in postmarketOS Plasma Mobile. All the log says about it is `Clipboard service is not even started`.

**Comment by Rishabh672003** [comment]
hey i am facing the same problem on manjaro desktop

this is what my log looks like
>(122023) [23:45:04] waydroidclipboard: Received transaction: 2
(122023) [23:45:07] waydroidclipboard: Received transaction: 2
(122023) [23:45:07] waydroidclipboard: Received transaction: 2
(130443) [23:45:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(130443) [23:45:56] *** output passed to waydroid stdout, not to this log ***
(122023) [23:49:17] waydroidclipboard: Received transaction: 1
(122023) [23:49:30] waydroidclipboard: Received transaction: 2
(122023) [23:49:30] waydroidclipboard: Received transaction: 2
(122023) [23:49:31] waydroidclipboard: Received transaction: 2
(122023) [23:49:32] waydroidclipboard: Received transaction: 2
(122023) [23:56:38] waydroidclipboard: Received transaction: 1
(122023) [23:56:56] waydroidclipboard: Received transaction: 2
(122023) [23:56:56] waydroidclipboard: Received transaction: 2
(122023) [23:56:56] waydroidclipboard: Received transaction: 2
(122023) [23:56:57] waydroidclipboard: Received transaction: 2
(122023) [00:00:40] waydroidclipboard: Received transaction: 2
(122023) [00:00:40] waydroidclipboard: Received transaction: 2
(122023) [00:00:40] waydroidclipboard: Received transaction: 2
(122023) [00:00:41] waydroidclipboard: Received transaction: 2
(134944) [00:04:29] UserMonitor service is not even started
(134944) [00:04:29] Clipboard service is not even started
(000330) [00:04:30] session manager stopped, stopping container and waiting...
(000330) [00:04:30] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 987 Failed to run lxc.hook.post-stop for container "waydroid"
(000330) [00:04:30] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
(000330) [00:04:31] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000330) [00:04:31] % umount /var/lib/waydroid/rootfs/vendor
(000330) [00:04:31] % umount /var/lib/waydroid/rootfs
(000330) [00:04:31] % umount /var/lib/waydroid/data
(000330) [00:04:31] % chmod 666 -R /dev/binder
(000330) [00:04:31] % chmod 666 -R /dev/vndbinder
(000330) [00:04:31] % chmod 666 -R /dev/hwbinder
(000330) [00:04:31] Container manager is waiting for session to load
(135016) [00:04:34] Starting waydroid session
(135016) [00:04:34] Save session config: /var/lib/waydroid/session.cfg
(135016) [00:04:34] UserMonitor service is not even started
(135016) [00:04:34] Clipboard service is not even started
(000330) [00:04:35] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(000330) [00:04:35] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(000330) [00:04:35] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(000330) [00:04:35] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000330) [00:04:35] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000330) [00:04:35] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000330) [00:04:35] % mount -o bind /home/rishabh/.local/share/waydroid/data /var/lib/waydroid/data
(000330) [00:04:35] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(000330) [00:04:35] % chmod 777 -R /dev/ashmem
(000330) [00:04:35] % chmod 777 -R /dev/dri
(000330) [00:04:35] % chmod 777 -R /dev/fb0
(000330) [00:04:35] % chmod 777 -R /dev/video1
(000330) [00:04:35] % chmod 777 -R /dev/video0
(000330) [00:04:35] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000330) [00:04:35] New background process: pid=135066, output=background
(000330) [00:04:35] waiting 10 seconds for container to start...
(000330) [00:04:36] Save session config: /var/lib/waydroid/session.cfg
(135016) [00:04:46] waydroidusermonitor: Received transaction: 1
(135016) [00:04:46] Android with user 0 is ready
(136162) [00:04:48] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(136162) [00:04:48] *** output passed to waydroid stdout, not to this log ***
(135016) [00:04:53] waydroidclipboard: Received transaction: 2
(135016) [00:04:55] waydroidclipboard: Received transaction: 2

**Comment by aleasto** [comment]
You need `pyclip >= 0.6.0` and `wl-clipboard`

**Comment by kode54** [comment]
I have both of those packages installed, and I have no idea what key I need to press to make it paste something into a text box.
