### ISSUE TITLE
glitches with mesa and gbm.

### ISSUE THREAD

**Issue by laichiaheng** [waydroid/waydroid#200]
It happens a lot!
OS: ArchLinux
DE: Gnome 40.4
waydroid: 1.2.0-1
![2021-10-31 00-46-11 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/139541870-f69b412d-0542-401c-a199-f5643a19cfb3.png)

**Comment by teppyboy** [comment]
can you try Xorg with Weston

**Comment by aleasto** [comment]
Should be fixed in the latest android 11 images.
