### ISSUE TITLE
Unable to start UI

### ISSUE THREAD

**Issue by Shuaiouke** [waydroid/waydroid#205]
I have followed the steps and install waydroid, but when it came to the last step (`waydroid show-full-ui`), after I ran the command, nothing happened, it just seems like the command had completed and that was is, I dont know if it matters but I was told since Im on x11, I would need to run the command in Weston, but the command acted the same either way, so I have no idea what is going on.

P.S. I believe everything else is fine because `waydroid status` returns all things to be running except the wayland display is None

**Comment by pizdjuk** [comment]
seems that actually you didnt run
waydroid show-full-ui 

from inseide a weston

check it out

**Comment by Shuaiouke** [comment]
I literally said I did but ok.
Also closing issue, as it turned out I have unsupported gpu, had to switch to sw rendering.
