### ISSUE TITLE
Inverted Colors 

### ISSUE THREAD

**Issue by Sakura0134** [waydroid/waydroid#207]
I am facing a weird issue. My apps are having inverted colors in Waydroid. (Usually with Red and Blue I suppose)
Anyway to fix it. (I tried using Matrix chat client but no one is helping me)
![Screenshot from 2021-11-03 00-57-04](https://user-images.githubusercontent.com/85794603/139892631-d69718b5-f2f3-4e26-8d06-2162cd840dbc.png)
Specs
Arch Linux(Kernel 5.14)
Mesa(latest)
DE: Gnome

**Comment by electrikjesus** [comment]
You need to use the patched mutter from our repo.waydro.id or wait for your version to be patched.

**Comment by rubusarbaro** [comment]
Or also you can invert the colors from the Accesibility menu.

**Comment by electrikjesus** [comment]
> Or also you can invert the colors from the Accesibility menu.

I noticed he was using multi-window mode, so I did not suggest that as it would break things. Looks like we got it figured out in the Telegram chat today, so there is a patched version for Gnome 40.x's mutter branch now. 

The change was merged upstream, so we're all in that in-between phase before Gnome adopts the change and a release is made with the color space supported.

**Comment by Sakura0134** [comment]
Thanks. The suggestion worked. But I am not closing the issue until gnome releases the patched build public. (To help others who gets the same issue)

**Comment by laichiaheng** [comment]
Will it be in Gnome 41?

**Comment by EmanuelLoos** [comment]
> Or also you can invert the colors from the Accesibility menu.

I tried using the "Simulate color space" option in the "Developer settings" to see if it made any difference (thinking about it now it would not have helped but I just tried something) and all apps crashed and they are not starting anymore. Looks like there is a issue too, since it is also related to color spaces I am posting it here. I guess I will have to reinstall Waydroid to use it again.

**Comment by laichiaheng** [comment]
It is solved in Gnome 41

**Comment by ACR-Jeff** [comment]
I am on Debian Bullseye vanilla, Fresh install, Installed Waydroid, I thought everything was great until I played a video and everyone in the video was blue. The instructions are not clear how to fix this issue. Any help would be appreciated. Thanks

**Comment by aleasto** [comment]
Update gnome or use `persist.waydroid.invert_colors`: https://docs.waydro.id/usage/waydroid-prop-options
