### ISSUE TITLE
How can I change the keyboard layout used in Waydroid?

### ISSUE THREAD

**Issue by rubusarbaro** [waydroid/waydroid#209]
Hello. Waydroid uses by default the English QWERTY keyboard layout, but I want to change it to the keyboard layout of my computer. I want to set the Spanish DVORAK keyboard layout for Wayland.

If you can help me, I would thank you a lot.

**Comment by Aman9das** [comment]
Yes the most important usability feature is recognition of the physical keyboard..

**Comment by Id2ndR** [comment]
It seams that Android does not detect the computer keyboard as an external (physical) keyboard, because it's not an usb or bluetooth one.
So it prevent changing the settings like explained [here](https://android.stackexchange.com/questions/77538/cannot-change-languange-on-external-keyboard).

Also, the _External Keyboard Helper_ application does not help either (inspired by [this](https://www.howtogeek.com/175267/the-htg-guide-to-using-a-bluetooth-keyboard-with-your-android-device/))?

**Comment by Id2ndR** [comment]
It may help to edit `/var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl`, but I haven't tried yet.

**Comment by jabossu** [comment]
Same question: i don't think this issue should be closed.

I'm using Waydroid on my Manjaro laptop. It works quite well !
But I have a french keyboard, and Waydroid captures QWERTY input. I cannot find a way to switch to AZERTY. 

I have tried:

- changing input language
- changing system language
- installing other keyboard
- disabling the AOSP keyboard

None of those worked. I'm not sure what else to do.

> It may help to edit `/var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl`, but I haven't tried yet.

This file says it should no be edited, but to create another layout file. However, I've got no idea where to find an AZERTY layout file, and i don't know how to point waydroid to using it.

Does anyone have a hint ?
Thanks in advance,

**Comment by firefoxlover** [comment]
> It may help to edit `/var/lib/waydroid/rootfs/system/usr/keylayout/Generic.kl`, but I haven't tried yet.

This will probably work, but the file is read only. Couldn't yet write to it with sudo.

**Comment by vyalcevanet** [comment]
And what if I need to have two keyboard layouts and be able to switch between them? For example, Russian and English. Since Android does not recognize the physical keyboard, it does not allow you to configure keyboard layout switching.

**Comment by onny** [comment]
Why is this issue still closed? In the best case Waydroid should follow system keyboard layout like any other native application would do.

**Comment by meisme-dev** [comment]
I have the inverse problem. My computer uses QWERTY but Waydroid uses some weird keyboard layout and I can't get it to type anything useful.

**Comment by marodriguezr** [comment]
> @rubusarbaro , we all see you closed this issue, in reaction to the fact we can trick the keyboard layout, is there in your mind anything to go further on this matter (like provinding layouts or something like that ? whats the wayforward to not block people for using waydroid ? )

how?

**Comment by benintech** [comment]
Managed to change my keyboard from qwerty to azerty. See https://github.com/waydroid/waydroid/issues/599

**Comment by firefoxlover** [comment]
This issue is not closed! The Generic.kl should not be modified, there are other layout files but its all read-only, especially on immutable distros. This cant be the way.

**Comment by firefoxlover** [comment]
It seems to work in the app now! It detects "wayland_keyboard", which uses the corret layout. Nonetheless it doesnt work at the beginning. What solved it for me was setting the keyboard language to my local language only instead of automatic, removing English in that case

**Comment by mongaikan** [comment]
> It seems to work in the app now! It detects "wayland_keyboard", which uses the corret layout. Nonetheless it doesnt work at the beginning. What solved it for me was setting the keyboard language to my local language only instead of automatic, removing English in that case

Strange it doesn't work for me and I'm still stuck with Android approved layouts it seems.

**Comment by banan314** [comment]
> It seems to work in the app now! It detects "wayland_keyboard", which uses the corret layout. Nonetheless it doesnt work at the beginning. What solved it for me was setting the keyboard language to my local language only instead of automatic, removing English in that case

where is *wayland_keyboard*?

**Comment by firefoxlover** [comment]
@banan314 it should appear under (in Waydroid, Android) Settings-System-Input methods

There is "AOSP keyboard" and below "hardware keyboard: waydroid_keyboard" and I think there you can also change the language

**Comment by banan314** [comment]
Thank you, I found it.

![Screenshot-8](https://github.com/waydroid/waydroid/assets/17968722/582046e3-be82-4878-8721-3503bcf7290e)

**Comment by gaussandhisgun** [comment]
i still dont get why this is closed? some people need to use *two* keyboard layouts, and android's ctrl+space shortcut does not help. and External Keyboard Helper is basically useless when it comes to multi window mode due to the way Waydroid and, say, Phosh handle windows.

**Comment by waozixyz** [comment]
Still no solution? this issue should be open

**Comment by akku1139** [comment]
(Android 13)
I found the keyboard layout settings, but there is no Japanese (jp106)...

<img width="1280" height="1000" alt="Image" src="https://github.com/user-attachments/assets/ef593f29-c6e3-4f19-badc-9ac4e5532efd" />

<img width="1280" height="1002" alt="Image" src="https://github.com/user-attachments/assets/ae133563-5065-49be-8d5b-4316660eecbb" />

**Comment by cypa** [comment]
`Ctrl+Space` do not work, 
but `right_alt` hold make keyboard type english
UPDATE:  if was my fault, 
but then I enabled second keyboard layout and `Ctrl+Space` now works well

**Comment by fakhriaditiarahman** [comment]
Is there still a way out in this case?

**Comment by HumanBojack** [comment]
So there is still no solution if your layout is not in the android keyboard layouts?

**Comment by camilajenny** [comment]
> So there is still no solution if your layout is not in the android keyboard layouts?

still none
