### ISSUE TITLE
add remove.sh

### ISSUE THREAD

**Issue by nanu-c** [waydroid/waydroid#21]
In order to remove all traces from the system, there should be a removal script, too.

**Comment by nanu-c** [comment]
I have written a small click app, that installs, starts and stops waydroid. I am missing the remove. I would be also way easier if the start and stop wouldn't need sudo in order to run.

**Comment by allaeddineomc** [comment]
replace sudo with pkexec to have a graphical sudo password popup that matches the DE being used , i will see if i can create a remove.sh for you

**Comment by sickcodes** [comment]
> I have written a small click app, that installs, starts and stops waydroid. I am missing the remove. I would be also way easier if the start and stop wouldn't need sudo in order to run.

sudo is required to use lxc properly with KVM. You can of course add yourself to those groups, effectively making you "root"

Add yourself as a NOPASSWD sudoer if you want to stop typing in passwords

**Comment by erfanoabdi** [comment]
not related anymore on python tools
