### ISSUE TITLE
Ability to backup or restore application data through adb

### ISSUE THREAD

**Issue by loveisfoss** [waydroid/waydroid#213]
# **Backup**
When doing:
```
$ adb backup -f myapp.ab -apk com.myapp
```
the result is:
```
Now unlock your device and confirm the backup operation...
```
No prompt to allow the backup comes to the Android system that runs into Waydroid.

# **Restore**
After taking a backup from an android phone and trying to restore it on Waydroid. When doing:
```
adb restore ~/myapp.ab
```
the result is:
```
Now unlock your device and confirm the restore operation.
/bin/sh: line 1: /system/bin/bu: No such file or directory
```
No prompt to allow the restore comes to the Android system that runs into Waydroid.

# **Suggestion**
Enable somehow the backup/restore possibility through adb.

**Comment by aleasto** [comment]
We now have backup/restore instructions documented https://docs.waydro.id/faq/backup-restore-apps-and-data
