### ISSUE TITLE
python3-gbinder

### ISSUE THREAD

**Issue by ArruaBrian** [waydroid/waydroid#214]
Error installing waydroid python3-gbinder

> sigma@SigmIsHere: ~ $ sudo apt install waydroid
> Reading package list ... Done
> Creating dependency tree
> Reading status information ... Done
> Do not can instal some pack. This may mean that
> you asked for an impossible situation or, if you are using the distribution
> unstable, that some required packages have not yet been created or are
> They have taken from "Incoming."
> The following information can help resolve the situation:
> 
> The following packages have unmet dependencies:
>  waydroid: Depends: python3-gbinder but it won't install
> E: Problems could not be corrected, you have retained broken packages.

Installing dependencies.....

> sigma@SigmIsHere: ~ $ sudo apt install python3-gbinder
> Reading package list ... Done
> Creating dependency tree
> Reading status information ... Done
> Do not can instal some pack. This may mean that
> you asked for an impossible situation or, if you are using the distribution
> unstable, that some required packages have not yet been created or are
> They have taken from "Incoming."
> The following information can help resolve the situation:
> 
> The following packages have unmet dependencies:
>  python3-gbinder: Depends: python3 (> = 3.9 ~) but 3.8.2-0ubuntu2 is going to be installed
> E: Problems could not be corrected, you have retained broken packages.

**Comment by Gurren-Joestar** [comment]
I had the same problem on Ubuntu 20.04 
```
export DISTRO="bullseye" && \
sudo curl -# --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg && \
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list && \
sudo mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
```
Yeah, I didn't realize I had to change bullseye for focal.

**Comment by Gurren-Joestar** [comment]
`lsb_release -c `
Should make the trick, I would suggest improving that part in the wiki guide
https://docs.waydro.id/development/compile-waydroid-lineage-os-based-images

**Comment by scardracs** [comment]
> I had the same problem on Ubuntu 20.04
> 
> ```
> export DISTRO="bullseye" && \
> sudo curl -# --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg && \
> echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > ~/waydroid.list && \
> sudo mv ~/waydroid.list /etc/apt/sources.list.d/waydroid.list && \
> sudo apt update
> ```
> 
> Yeah, I didn't realize I had to change bullseye for focal.

Ubuntu 20.04 should not use bullseye as distro name 😅

**Comment by sebastian-arnhold** [comment]
Hello dear developers! :)

I'm trying to install Waydroid on the latest Ubuntu development version (22.04 LTS "jammy", to be released in April 2022).

When trying to install via using the outdated - but still most recent - Ubuntu 20.04 LTS "focal" PPA, I get a dependency conflict with python3-gbinder, similar to the one @ArruaBrian described, just with different version numbers. Two years of development progress in Ubuntu probably lead to this version conflict.

In the interest of easy-as-possible-distribution, would it be possbile to make an official release of Waydroid and package that into the Debian unstable repository? That way, it would get perpetuated into the Ubuntu 22.04 repository within two weeks.

The next Ubuntu version would then include Waydroid ready-to-install.
(a Flatpak version would be nice, too - but I can understand that this would be much more work!)

**Comment by electrikjesus** [comment]
Use the bullseye release as that should have all the same dependencies.

**Comment by sebastian-387** [comment]
> Use the bullseye release as that should have all the same dependencies.

Yay! That resolved the issue!

> We will look into what we can do to include our packages upstream.

Thank you very, very much! :)
Keep me posted!

**Comment by mihalycsaba** [comment]
> Use the bullseye release as that should have all the same dependencies. We will look into what we can do to include our packages upstream.

This doesn't work for me. Changing to bullseye will need python 3.9 and focal only has 3.8

```
The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (>= 3.9~) but 3.8.2-0ubuntu2 is to be installed
```

**Comment by Fraetor** [comment]
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm getting this issue using the bullseye repo on Debian sid. It looks like a packaging issue as there doesn't seem to have been anything significant removed in 3.10.

**Comment by prajjwald** [comment]
Running into the same issue with Ubuntu Jammy (22.04) using bullseye as the DISTRO (also tried hirsute, same results).

```bash
# apt install waydroid
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-gbinder : Depends: python3 (< 3.10) but 3.10.4-0ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

![image](https://user-images.githubusercontent.com/5673462/164956864-68b95050-e009-4647-ac6b-02cf2db2fbc6.png)

**Comment by cniw** [comment]
run this commands, this will build good python3-gbinder package for your distro
```bash
# if you're on debian run this
export distro=bullseye
# or if you're on ubuntu run this
export distro=focal


sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ ${distro} main" | \
  sudo tee /etc/apt/sources.list.d/waydroid.list

sudo apt update
sudo apt install -y \
  build-essential cdbs devscripts equivs fakeroot \
  git git-buildpackage git-lfs \
  libgbinder-dev

sudo wget https://raw.githubusercontent.com/MrCyjaneK/waydroid-build/main/build_changelog \
  -O /usr/bin/build_changelog
sudo chmod +x ${_}

mkdir ~/build-packages
cd ${_}
git clone https://github.com/waydroid/gbinder-python.git
cd gbinder-python
build_changelog
sudo mk-build-deps -ir -t "apt -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
sudo debuild -b -uc -us
sudo apt install -f -y ../*.deb

sudo apt remove libgbinder-dev gbinder-python-build-deps git-lfs fakeroot equivs devscripts cdbs
# you can remove git and build-essential packages too
sudo apt autoremove
sudo rm /usr/bin/build_changelog

sudo apt install waydroid
```

**Comment by cniw** [comment]
other issues that related with this issue:
- https://github.com/waydroid/waydroid/issues/361
- https://github.com/waydroid/waydroid/issues/363
- https://github.com/waydroid/waydroid/issues/368

**Comment by Kushagra-Srivastava** [comment]
@cniw Thank you very much, Sir, for sharing your knowledge. It worked for me!!

**Comment by jwrick816** [comment]
> run this commands, this will build good python3-gbinder package for your distro
> 
> ```shell
> # if you're on debian run this
> export distro=bullseye
> # or if you're on ubuntu run this
> export distro=focal
> 
> 
> sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
> echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ ${distro} main" | \
>   sudo tee /etc/apt/sources.list.d/waydroid.list
> 
> sudo apt update
> sudo apt install -y \
>   build-essential cdbs devscripts equivs fakeroot \
>   git git-buildpackage git-lfs \
>   libgbinder-dev
> 
> sudo wget https://raw.githubusercontent.com/MrCyjaneK/waydroid-build/main/build_changelog \
>   -O /usr/bin/build_changelog
> sudo chmod +x ${_}
> 
> mkdir ~/build-packages
> cd ${_}
> git clone https://github.com/waydroid/gbinder-python.git
> cd gbinder-python
> build_changelog
> sudo mk-build-deps -ir -t "apt -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
> sudo debuild -b -uc -us
> sudo apt install -f -y ../*.deb
> 
> sudo apt remove libgbinder-dev gbinder-python-build-deps git-lfs fakeroot equivs devscripts cdbs
> # you can remove git and build-essential packages too
> sudo apt autoremove
> sudo rm /usr/bin/build_changelog
> 
> sudo apt install waydroid
> ```
Bro not working, libgbinder-dev not available for ubuntu 22

**Comment by cniw** [comment]
> Bro not working, libgbinder-dev not available for ubuntu 22

@jwrick816 make sure you run these command, copy and paste exactly like this don't need edit to jammy
```bash
export distro=focal

sudo curl https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ ${distro} main" | \
  sudo tee /etc/apt/sources.list.d/waydroid.list

sudo apt update
```

it will add ubuntu focal waydroid repo even you're on ubuntu jammy, so you can access libgbinder-dev package from official waydroid repo

i also make bash script for this https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97, just run this on your terminal
```bash
curl -s https://gist.githubusercontent.com/cniw/7a0220ce8b75368f7f57aa422d3fea97/raw | bash
```

**Comment by bermano** [comment]
Hi @cniw, I also have problem to install  libgbinder-dev
I do exactly or copy paste from your script and trying in debian 11 $DISTRO=bullseye and ubuntu $DISTRO=focal but can not find package  libgbinder-dev in waydroid repo nor debian repo, found on github lib gbinder here https://github.com/mer-hybris/libgbinder, but getting error when I try to compile with "make" command, what can I do, please help.. :)

**Comment by dreamcat4** [comment]
I think i encountered a small issue

Because yesterday I applied the solution (build and install custom deb). OK it all seemed to work well. And waydroid installed, and no errors or anything.

However I come back the next day and `apt upgrade` gives the following complains:

```sh
The following packages have been kept back:
  libegl-mesa0:i386 libgbm1:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386 libglx-mesa0:i386 mesa-va-drivers:i386
  mesa-vulkan-drivers:i386 python3-gbinder
```

So ignoring all the mesa / gpu stuff... see the last pkg in the list there? Is the `python3-gbinder`

What it seems to be (at least for myself here)...

```sh
python3-gbinder_0.0.0+git.202109121608_amd64.deb
```

That the `0.0.0` version was not set correctly.

Maybe I didn't follow all of the instructions properly? In order for setting properly the version number?

Since not everything in that gist is actually OK. Theres a lot of optional stuff in there which had to skip over and not run.

**Comment by bermano** [comment]
Finally success install waydroid in 64bit machine, I guess the dependencies problem related with difference package on 32bit and 64 bit repo.

**Comment by WallyZambotti** [comment]
I tried all the suggestions here including https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97 but failed to locate the python3-gbinder.  I think the real solution is to wait until waydroid is released for jammy.

**Comment by cniw** [comment]
> I do exactly or copy paste from your script and trying in debian 11 $DISTRO=bullseye and ubuntu $DISTRO=focal but can not find package libgbinder-dev in waydroid repo nor debian repo

@bermano i use lowercase on all that variable at https://github.com/waydroid/waydroid/issues/214#issuecomment-1126644335 you should consistent with you've wrote above, if not you can't access the variable value. not like windows in linux is case sensitive, example
```bash
distro=popos
DISTRO=zorin
echo $distro # this will print popos
```

> Finally success install waydroid in 64bit machine, I guess the dependencies problem related with difference package on 32bit and 64 bit repo.

Yes missing 32 bit packages, i've just check waydroid repo and i notice it only provide deb packages for amd64 and arm64 machine. If you want install waydroid on 32 bit machine you should build it with all the dependencies https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1
```bash
curl -s https://gist.githubusercontent.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1/raw | bash
```

> Bro not working, libgbinder-dev not available for ubuntu 22

> I tried all the suggestions here including https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97 but failed to locate the python3-gbinder. I think the real solution is to wait until waydroid is released for jammy.

@jwrick816 @WallyZambotti  Are you also on 32 bit machine? read above too

**Comment by ShulkerSakura** [comment]
My problem is werid that 
File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ImportError: /usr/lib/python3/dist-packages/gbinder.cpython-39-x86_64-linux-gnu.so: undefined symbol: gbinder_servicemanager_new2

libgbinder* python3-gbinder is already installed

**Comment by chrishpowell** [comment]
Tried all sorts including the above on a fresh Ubuntu 22.04 install.  It fails at with:
`Writing /home/chrisp/build-packages/gbinder-python/debian/python3-gbinder/usr/lib/python3.10/dist-packages/gbinder_python-1.0.0.egg-info
   dh_installdocs -O--buildsystem=pybuild
   dh_installchangelogs -O--buildsystem=pybuild
   dh_python3 -O--buildsystem=pybuild
   dh_installsystemduser -O--buildsystem=pybuild
   dh_perl -O--buildsystem=pybuild
   dh_link -O--buildsystem=pybuild
   dh_strip_nondeterminism -O--buildsystem=pybuild
   dh_compress -O--buildsystem=pybuild
   dh_fixperms -O--buildsystem=pybuild
   dh_missing -O--buildsystem=pybuild
   dh_dwz -a -O--buildsystem=pybuild
   dh_strip -a -O--buildsystem=pybuild
55ff540d80fe199368a1c960aa464651a045a886
   dh_makeshlibs -a -O--buildsystem=pybuild
   dh_shlibdeps -a -O--buildsystem=pybuild
dpkg-shlibdeps: error: no dependency information found for /lib/libgbinder.so.1 (used by debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/python3-gbinder.substvars debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so returned exit code 25
dh_shlibdeps: error: Aborting due to earlier error
make: *** [debian/rules:7: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
`

**Comment by chrishpowell** [comment]
I have tried all sorts of things including above scripts and suggestions on a fresh install of Ubuntu 22.04.  Waydroid worked for me on 21.04.  With 22, I get the following failure at debuild:

```
Writing /home/chrisp/build-packages/gbinder-python/debian/python3-gbinder/usr/lib/python3.10/dist-packages/gbinder_python-1.0.0.egg-info
   dh_installdocs -O--buildsystem=pybuild
   dh_installchangelogs -O--buildsystem=pybuild
   dh_python3 -O--buildsystem=pybuild
   dh_installsystemduser -O--buildsystem=pybuild
   dh_perl -O--buildsystem=pybuild
   dh_link -O--buildsystem=pybuild
   dh_strip_nondeterminism -O--buildsystem=pybuild
   dh_compress -O--buildsystem=pybuild
   dh_fixperms -O--buildsystem=pybuild
   dh_missing -O--buildsystem=pybuild
   dh_dwz -a -O--buildsystem=pybuild
   dh_strip -a -O--buildsystem=pybuild
55ff540d80fe199368a1c960aa464651a045a886
   dh_makeshlibs -a -O--buildsystem=pybuild
   dh_shlibdeps -a -O--buildsystem=pybuild
dpkg-shlibdeps: error: no dependency information found for /lib/libgbinder.so.1 (used by debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/python3-gbinder.substvars debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so returned exit code 25
dh_shlibdeps: error: Aborting due to earlier error
make: *** [debian/rules:7: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
```

**Comment by gmg137** [comment]
I get the following error when running：
```
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 9, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ImportError: /usr/local/lib64/python3.10/site-packages/gbinder.cpython-310-x86_64-linux-gnu.so: undefined symbol: gbinder_servicemanager_new2
```

**Comment by tom-snow** [comment]
> I have tried all sorts of things including above scripts and suggestions on a fresh install of Ubuntu 22.04. Waydroid worked for me on 21.04. With 22, I get the following failure at debuild:
> 
> ```
> Writing /home/chrisp/build-packages/gbinder-python/debian/python3-gbinder/usr/lib/python3.10/dist-packages/gbinder_python-1.0.0.egg-info
>    dh_installdocs -O--buildsystem=pybuild
>    dh_installchangelogs -O--buildsystem=pybuild
>    dh_python3 -O--buildsystem=pybuild
>    dh_installsystemduser -O--buildsystem=pybuild
>    dh_perl -O--buildsystem=pybuild
>    dh_link -O--buildsystem=pybuild
>    dh_strip_nondeterminism -O--buildsystem=pybuild
>    dh_compress -O--buildsystem=pybuild
>    dh_fixperms -O--buildsystem=pybuild
>    dh_missing -O--buildsystem=pybuild
>    dh_dwz -a -O--buildsystem=pybuild
>    dh_strip -a -O--buildsystem=pybuild
> 55ff540d80fe199368a1c960aa464651a045a886
>    dh_makeshlibs -a -O--buildsystem=pybuild
>    dh_shlibdeps -a -O--buildsystem=pybuild
> dpkg-shlibdeps: error: no dependency information found for /lib/libgbinder.so.1 (used by debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so)
> Hint: check if the library actually comes from a package.
> dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/python3-gbinder.substvars debian/python3-gbinder/usr/lib/python3/dist-packages/gbinder.cpython-310-x86_64-linux-gnu.so returned exit code 25
> dh_shlibdeps: error: Aborting due to earlier error
> make: *** [debian/rules:7: binary] Error 25
> dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui -b failed
> ```

Add below to `debian/rules` file if you built gbinger manually (I added below `export PYBUILD_BUILD_ARGS_python3=--cython` ) 
```
override_dh_shlibdeps:
    dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```

[REF here](https://stackoverflow.com/questions/11238134/dpkg-shlibdeps-error-no-dependency-information-found-for)

**Comment by JHacker-JMusicology** [comment]
> ```shell
> 
> sudo apt remove libgbinder-dev gbinder-python-build-deps git-lfs fakeroot equivs devscripts cdbs
> ```

Perfect, So thanks it worked for me on Kali Linux

**Comment by JHacker-JMusicology** [comment]
https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304

Perfect thanks it worked on Kali Linux

**Comment by n1lby73** [comment]
> `lsb_release -c ` Should make the trick, I suggest improving the install guide (https://docs.waydro.id/development/compile-waydroid-lineage-os-based-images) using some kind of distro auto-recognition
> 
> I guess people still need to read and not just copy-paste, including myself

you can use the unofficial [waydroid installer](https://github.com/n1lby73/waydroid-installer)

**Comment by coolst3r** [comment]
same issue on arch linux

**Comment by Kustale** [comment]
> > I do exactly or copy paste from your script and trying in debian 11 $DISTRO=bullseye and ubuntu $DISTRO=focal but can not find package libgbinder-dev in waydroid repo nor debian repo
> 
> @bermano i use lowercase on all that variable at [#214 (comment)](https://github.com/waydroid/waydroid/issues/214#issuecomment-1126644335) you should consistent with you've wrote above, if not you can't access the variable value. not like windows in linux is case sensitive, example
> 
> ```shell
> distro=popos
> DISTRO=zorin
> echo $distro # this will print popos
> ```
> 
> > Finally success install waydroid in 64bit machine, I guess the dependencies problem related with difference package on 32bit and 64 bit repo.
> 
> Yes missing 32 bit packages, i've just check waydroid repo and i notice it only provide deb packages for amd64 and arm64 machine. If you want install waydroid on 32 bit machine you should build it with all the dependencies https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1
> 
> ```shell
> curl -s https://gist.githubusercontent.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1/raw | bash
> ```
> 
> > Bro not working, libgbinder-dev not available for ubuntu 22
> 
> > I tried all the suggestions here including https://gist.github.com/cniw/7a0220ce8b75368f7f57aa422d3fea97 but failed to locate the python3-gbinder. I think the real solution is to wait until waydroid is released for jammy.
> 
> @jwrick816 @WallyZambotti Are you also on 32 bit machine? read above too


hello. I tried installing this.
But error.
What should I do?

==========> Start building libglibutil <==========
==> Building package(s): libglibutil ...
  dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package libglibutil
dpkg-buildpackage: info: source version 1.0.75
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Slava Monich <slava@monich.com>
  dpkg-source --before-build .
dpkg-buildpackage: info: host architecture i386
  debian/rules clean
dh clean
    dh_auto_clean
         make -j4 clean
make[1]: Enter directory ‘/home/kustale/waydroid-build/libglibutil’
make -C test clean
make[2]: Enter directory ‘/home/kustale/waydroid-build/libglibutil/test’
make[3]: Enter directory '/home/kustale/waydroid-build/libglibutil/test/test_datapack'
make[3]: warning: jobserver not available: use -j1. Add '+' to the parent make rule.
make[3]: warning: jobserver not available: use -j1. Add '+' to the parent make rule.
make[3]: warning: jobserver not available: use -j1. Add '+' to the parent make rule.
../common/Makefile:110: *** Multi-target pattern. stoppage.
make[3]: Exit directory '/home/kustale/waydroid-build/libglibutil/test/test_datapack'
make[2]: *** [Makefile:5: clean] error 2
make[2]: Exit directory '/home/kustale/waydroid-build/libglibutil/test'
make[1]: *** [Makefile:166: clean] error 2
make[1]: Exit directory '/home/kustale/waydroid-build/libglibutil'
dh_auto_clean: error: make -j4 clean returned exit code 2
make: *** [debian/rules:16: clean] error 25
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed

==> Building package(s): libglibutil, failed.

**Comment by fabianlawrence** [comment]
I just downloaded and installed the python3-gbinder package from here [](https://repo.waydro.id/dists/jammy/) . it worked hehe

**Comment by creepreee** [comment]
guys i have an issue here. when installing waydroid, dont know what happened

dell@censor:/usr/lib$ dpkg -L libgbinder
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgbinder.so.1.1.25
/usr/share
/usr/share/doc
/usr/share/doc/libgbinder
/usr/share/doc/libgbinder/changelog.gz
/usr/share/doc/libgbinder/copyright
/usr/lib/x86_64-linux-gnu/libgbinder.so.1
/usr/lib/x86_64-linux-gnu/libgbinder.so.1.1

when i ran this command, it was succesfully downloaded
sudo apt install git libglib2.0-dev libglibutil-dev gcc
git clone --depth=1 https://github.com/mer-hybris/libgbinder
cd libgbinder
make
sudo make install

but in this website, it says:
https://github.com/Aman9das/Waydroid_Setup_Guide

get the latest libgbinder updates:
sudo apt install git libglib2.0-dev libglibutil-dev gcc
git clone --depth=1 https://github.com/mer-hybris/libgbinder
cd libgbinder
make
make install
copy the new libgbinder.so.1, libgbinder.so.1.1 and libgbinder.so.1.1.xx files added to /usr/lib to wherever your system has the current libgbinder installed. Use dpkg -L libgbinder to find out.

i cant find libgbinder.so.1.1.xx
please tell me how to fix this?

**Comment by 11111-l** [comment]
统信UOS也安装不了Waydroid
