### ISSUE TITLE
it is too slow when run `waydroid init`

### ISSUE THREAD

**Issue by bibaodi** [waydroid/waydroid#215]
it is too slow when run `waydroid init`
I am in china Mainland, when download the lineage.zip from sourceforge it is very slow, is it possible download by myself or change download website to another website?

**Comment by pizdjuk** [comment]
Look where it needs to be downloaded and place the file there

**Comment by bibaodi** [comment]
> Look where it needs to be downloaded and place the file there

I already download the file from a mirror on my local storage, Just Donot know where shoud I put this zip file. Do you know it? @pizdjuk

**Comment by electrikjesus** [comment]
You need to put the images in  /usr/share/waydroid-extra/images
Then run 'sudo waydroid init -f'

**Comment by bibaodi** [comment]
> You need to put the images in /usr/share/waydroid-extra/images Then run 'sudo waydroid init -f'
> 
> Doing it this way will not allow for automatic updates though, and you will have to repeat this process next update

hi，@electrikjesus。very tks the reply but still have some problems. 
I have copy lineage-17.1...system.zip to the directory, but I got a warning (Missing system or vendor on preinstalled images dir, fallback to default ).
IS there more files I need to download and put in the directory ? 
very tks.

**Comment by bibaodi** [comment]
> > You need to put the images in /usr/share/waydroid-extra/images Then run 'sudo waydroid init -f'
> > Doing it this way will not allow for automatic updates though, and you will have to repeat this process next update
> 
> hi，@electrikjesus。very tks the reply but still have some problems. I have copy lineage-17.1...system.zip to the directory, but I got a warning (Missing system or vendor on preinstalled images dir, fallback to default ). IS there more files I need to download and put in the directory ? very tks.

I check the sourceforge and found vendor files, I will download it and retry.

**Comment by bibaodi** [comment]
@electrikjesus 
Hi, I have try put vendor file in the same directory of system.zip, but still not work.
below is my environment information.

Hope you can give me further comment, very thanks.

`eton@9d:~/feiji/build-src-Desktop_Qt_5_15_2_GCC_64bit-Debug/bin$ ls -l /usr/share/waydroid-extra/images/
total 861468
-rw-r--r-- 1 root root 125103878 Nov 11 10:49 lineage-17.1-20211021-MAINLINE-waydroid_x86_64-vendor.zip
-rw-r--r-- 1 root root 757033921 Nov 11 10:49 lineage-17.1-20211021-VANILLA-waydroid_x86_64-system.zip
eton@9d:~/feiji/build-src-Desktop_Qt_5_15_2_GCC_64bit-Debug/bin$ sudo waydroid init -f
[10:52:59] Missing system or vendor on preinstalled images dir, fallback to default
^CTraceback (most recent call last):
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 94, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 25, in get
    system_request = helpers.http.retrieve(system_ota)
  File "/usr/lib/waydroid/tools/helpers/http.py", line 86, in retrieve
    return 200, response.read()
  File "/usr/lib/python3.9/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.9/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
`

**Comment by electrikjesus** [comment]
No, you extract them so there is only the system.img & vendor.img in that /usr/share/waydroid-extra/images folder

**Comment by NAMIRENGO** [comment]
If i wana learn C can one help

Reeh

**Comment by bibaodi** [comment]
> No, you extract them so there is only the system.img & vendor.img in that /usr/share/waydroid-extra/images folder

Thanks for the reply, I will try it.

**Comment by bibaodi** [comment]
Thanks @electrikjesus . I have success run 'waydroid init'.

```
/usr/share/waydroid-extra/images$ ls -l |grep img
-rw-r--r-- 1 eton eton 1738235904 Oct 21 17:01 system.img
-rw-r--r-- 1 eton eton  324395008 Oct 22 00:46 vendor.img
```

**Comment by mahdi-ln** [comment]
I want to use image that have google play store.
I downloaded GAPPS image.zip
Extracted `system.img` to '/usr/share/waydroid-extra/images/'
Run 
```
$ waydroid init --system_type GAPPS
[17:58:25] Missing system or vendor on preinstalled images dir, fallback to default
[17:58:28] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20211021-GAPPS-waydroid_x86_64-system.zip/download
```
It tries to download again

**Comment by mahdi-ln** [comment]
ok I have to download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20211021-MAINLINE-waydroid_x86_64-vendor.zip

**Comment by 1036831050** [comment]
@electrikjesus  very tks

**Comment by 1036831050** [comment]
> No, you extract them so there is only the system.img & vendor.img in that /usr/share/waydroid-extra/images folder

Hi, I have try put system.img in the same directory , but still not work.

lmd@lmd-HP-Pavilion-Gaming-Notebook:/usr/share/waydroid-extra/images$ sudo waydroid init -f
[14:38:51] Found directory /usr/share/waydroid-extra/images but missing system or vendor image, ignoring...

**Comment by 1036831050** [comment]
> No, you extract them so there is only the system.img & vendor.img in that /usr/share/waydroid-extra/images folder


lmd@lmd-HP-Pavilion-Gaming-Notebook:/usr/share/waydroid-extra/images$ sudo waydroid init -f
[14:38:51] Found directory /usr/share/waydroid-extra/images but missing system or vendor image, ignoring...

**Comment by NAMIRENGO** [comment]
Welcome to Slack

Ta-da! You’ve joined your first Slack workspace and we couldn’t be more delighted. Here are your account details, along with some tips to help you get started.

Workspace name: Evidence

E

evidence-jbd1431.slack.com []

Open Slack [https://evidence-jbd1431.slack.com/x-p9221286494771-9226321245122-9257025847776/messages/C096H8EPT35]
Tips for getting started

Take a quick tour

Get familiar with the basics of Slack [https://evidence-jbd1431.slack.com/x-p9221286494771-9226321245122-9257025847776/resources/using-slack/your-quick-start-guide-to-slack?utm_medium=email&utm_source=confirmation-new-join] so you’re ready to get to work in no time.

Start working in channels

Keep conversations organized in channels [https://evidence-jbd1431.slack.com/x-p9221286494771-9226321245122-9257025847776/features/channels?utm_medium=email&utm_source=confirmation-new-join] — organized spaces for everything related to a project, topic, or team.

Download Slack

For the best experience with Slack, download our apps [https://evidence-jbd1431.slack.com/x-p9221286494771-9226321245122-9257025847776/downloads?utm_medium=email&utm_source=confirmation-new-join&t=T096H8EEJNP] for desktop and mobile.

See more tips [https://evidence-jbd1431.slack.com/x-p9221286494771-9226321245122-9257025847776/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-join]

If you have any questions as you’re getting started, drop us a note at ***@***.*** We’re glad you’re here!
