### ISSUE TITLE
Instructions specified in anbox.xml not valid for Lineage OS 17.1

### ISSUE THREAD

**Issue by zubozrout** [waydroid/waydroid#22]
Hello,
I wanted to build patched Lineage OS but was unfortunately not able to do so using current build instructions.

I failed on the third step, that is: `repo sync`
That gives me: `fatal: remove-project element specifies non-existent project: platform/system/libhwbinder`

The reason for that is that Lineage OS 17.1 does apparently have a different path there:
https://github.com/LineageOS/android/blob/lineage-17.1/default.xml#L626
so these build instructions are not valid for that version, while they should work with the newer Lineage OS 18.1.

So the fix is to replace this line: https://github.com/Anbox-halium/anbox-halium/blob/lineage-17.1/anbox.xml#L5
with: `<remove-project name="LineageOS/android_system_libhwbinder" />`

I am not sure what is the reason behind this - if perhaps you started off with Lineage 18 and then had to revert to 17 but forgot to update the build instructions. Nonetheless noting this here for others as it took me a while to figure out what's actually going on and how to fix that as I am quite a noob at this.

**Comment by nbx3** [comment]
Confirmed this fixes the problem, thanks @zubozrout

**Comment by erfanoabdi** [comment]
Repo structure is changed, for manifest we have a script can be used by:
`wget -O - https://raw.githubusercontent.com/waydroid/android_vendor_waydroid/lineage-17.1/manifest_scripts/generate-manifest.sh | bash`
