### ISSUE TITLE
Attempting to install apps from suitable .apk files fails

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [waydroid/waydroid#220]
When installing from the built-in browser, it downloads complete files, then 'installs' them, finishing with a message of 'app not installed'.  The drive has 42 GB of space free.

**Comment by TheGreatCatAdorer** [comment]
Further details can be provided upon request.

**Comment by pizdjuk** [comment]
it should be the LineageOS issue. BTW, try to install the app trhough wayroid:

waydroid app install your.apk

**Comment by TheGreatCatAdorer** [comment]
That did not work, and given that it doesn't work on debian-stable (I had been using bookworm), I believe it was:

> The apk files you will sometimes find on the internet tend to only have arm support, and will therefore not work on x86_64.

**Comment by arun54321** [comment]
What app is that?

**Comment by TheGreatCatAdorer** [comment]
Firefox, Vivaldi, etc.

**Comment by jaded0** [comment]
Confirmed, here, too. The error message is very uninformative.

**Comment by ACR-Jeff** [comment]
Here is my logcat
[logcat.txt](https://github.com/waydroid/waydroid/files/9720727/logcat.txt)

**Comment by aleasto** [comment]
You may only install apps of the same architecture as your CPU.
If you need to emulate ARM apps on x86_64, you can use `libhoudini` (proprietary): https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation
