### ISSUE TITLE
README.md not formatted properly

### ISSUE THREAD

**Issue by Netherquark** [waydroid/waydroid#221]
Readme.md is visible as follows:

![image](https://user-images.githubusercontent.com/65618735/140948658-0e35bc61-1d45-4a05-abdd-4090346e387a.png)

I doubt that is intentional.

**Comment by electrikjesus** [comment]
![Screenshot_20211109-114827](https://user-images.githubusercontent.com/8572619/140967966-23fad6d0-f390-4223-9cfb-9e287caea970.png)
It was halfway intentional,, but it does not look like it formats properly for GitHubs built-in markdown reader
