### ISSUE TITLE
Not working on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by IlgazC** [waydroid/waydroid#223]
After building these (https://github.com/choff/anbox-modules ) modules on openSUSE Tumbleweed and disabling secure-boot I installed waydroid using this package: https://build.opensuse.org/package/show/home%3ADead_Mozay%3Awaydroid/waydroid

It loads to a point (I see disk activity, CPU activity) but ends with following on console
```
ilgaz@hp:~> waydroid session start
[00:19:55] Failed to start Clipboard manager service, check logs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/waydroid/tools/services/user_manager.py", line 105, in service_thread
    IUserMonitor.add_service(args, userUnlocked, packageStateChanged)
  File "/usr/lib/waydroid/tools/interfaces/IUserMonitor.py", line 15, in add_service
    serviceManager = gbinder.ServiceManager("/dev/" + args.BINDER_DRIVER)
AttributeError: module 'gbinder' has no attribute 'ServiceManager'

```
I don't see anything else except continuous notification sounds.

When I issue "waydroid show-full-ui" following displayed in log
```
(020732) [00:25:00] ERROR: module 'gbinder' has no attribute 'ServiceManager'
(020732) [00:25:00] See also: <https://github.com/waydroid>
(020732) [00:25:00] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 105, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 121, in showFullUI
    justShow()
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 106, in justShow
    platformService = IPlatform.get_service(args)
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 278, in get_service
    serviceManager = gbinder.ServiceManager("/dev/" + args.BINDER_DRIVER)
AttributeError: module 'gbinder' has no attribute 'ServiceManager'
```
[waydroid.log](https://github.com/waydroid/waydroid/files/7508079/waydroid.log)

**Comment by IlgazC** [comment]
I managed to get it Waydroid displaying fine (thanks to Telegram) but a very interesting thing happened. I registered my device id at Google and Google Play store still shows "not certified", OK forget it and try to install an app manually. On Terminal I type
```
waydroid app install Dergilik_v5.31_apkpure.com.apk
[22:11:20] ERROR: module 'gbinder' has no attribute 'ServiceManager'
[22:11:20] See also: <https://github.com/waydroid>

```

**Comment by IlgazC** [comment]
It looks like opensuse python38-gbinder (and other variants) are broken, actually the file (.so) isn't copied to /usr/lib64/python3.8/site-packages so there is no way it will run. I alerted the package maintainer (dead_mozay) and remember this is a rolling release distro so things can change in minutes.

**Comment by Afsalmc** [comment]
Hey how is the current state of things in TW ?

**Comment by IlgazC** [comment]
I fixed the problematic python-gbinder and updated waydroid. Submitted changes to maintainer but no response however they can be binary downloaded I guess.
https://build.opensuse.org/project/show/home:ilgazcl:branches:home:Dead_Mozay:waydroid

**Comment by IlgazC** [comment]
I fixed the problematic python-gbinder and updated waydroid. Submitted changes to maintainer but no response however they can be binary downloaded I guess.
https://build.opensuse.org/project/show/home:ilgazcl:branches:home:Dead_Mozay:waydroid
