### ISSUE TITLE
Install App failed On Debian11  LineageOS 17.1 Waydroid x86_64 Device.

### ISSUE THREAD

**Issue by bibaodi** [waydroid/waydroid#228]
I install the waydroid on Debian11 by download 2 zip files and put it on correct position. then successful see the Lineage UI. 
1. but when I using Browser download app, it is not download successful, so can not be install. 
2. when I using waydroid app install name.app. the command do not display a error message, but no app installed.
3. I saw that Only ARM Device is support normal app, this should using X86_64 app, but Is there any advice where to download or how can I install a App successful?

Android Info:
    LineageOS 17.1 Waydroid x86_64 Device.

**Comment by opitz21254** [comment]
I have the same issue!!!

**Comment by aleasto** [comment]
To emulate ARM apps on x86_64 you may use libhoudini (proprietary): https://docs.waydro.id/faq/using-adb-with-waydroid

**Comment by bibaodi** [comment]
Very thanks to @aleasto . the information is very useful. ->libhoudini.
