### ISSUE TITLE
Waydroid error: not using Wayland. But I am!

### ISSUE THREAD

**Issue by quixote7** [waydroid/waydroid#229]
I followed the install instructions on the waydro.id home page. No errors until I get to "Running Waydroid" and then I get the error.

I'm using Mobian Bookworm and Phosh, on a Braveheart 1.1 Pinephone. 

`sudo container waydroid start`

produces the following errors:

```
[16:06:43] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
[16:06:43] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
[16:06:43] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
the log file seems to be just a grab bag of what it couldn't load or instructions to check the log file :/ . But I am in no way a programmer, so I could easily be missing something.

`waydroid session start`
tells me the XDG session is not Wayland. 

But both

`$ echo $XDG_SESSION_TYPE`
and

`$ loginctl show-session 1 -p Type`

returns "wayland" (I did check to make sure I had the right session)

Anyone have any idea what's going on? Or, even better, how to make it go away?

**Comment by shakakibara12** [comment]
I had the same problem, its not a problem in XDG sesion pointing to wayland. Its because of some lineage os image problem. My error got fixed by removing completely and then installing it again. For image i used **waydroid-image** from AUR in arch. Hope this helps!

**Comment by gyurmogyuri** [comment]
I have same on Manjaro Raspberry Pi 4. Plasma wayland:
`I] ^^>>> ps aux | grep wayland
root         846  0.0  0.2  72564 19712 ?        S    15:47   0:00 /usr/lib/sddm/sddm-helper --socket /tmp/sddm-auth4f729379-d81e-40f3-8399-aeaaa2bf9d5f --id 1 --start /usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland --user gyurmo --autologin
gyurmo       868  0.0  0.2 149932 18532 tty2     Ssl+ 15:47   0:00 /usr/bin/startplasma-wayland
gyurmo       879  0.0  0.1  65980 12516 tty2     S+   15:47   0:00 /bin/kwin_wayland_wrapper --xwayland /usr/lib/startplasma-waylandsession
gyurmo       880  2.0  2.7 1171132 219832 tty2   Sl+  15:47   2:08 /bin/kwin_wayland --wayland_fd 5 --socket wayland-0 --xwayland-fd 7 --xwayland-fd 6 --xwayland-display :1 --xwayland-xauthority /run/user/1000/xauth_bSiVge --xwayland /usr/lib/startplasma-waylandsession
gyurmo       886  0.6  0.8 204440 68408 tty2     S+   15:48   0:42 /bin/Xwayland :1 -auth /run/user/1000/xauth_bSiVge -listen 49 -listen 50 -displayfd 41 -rootless -wm 44
gyurmo       890  0.0  0.2 149912 18296 ?        Sl   15:48   0:00 /usr/lib/startplasma-waylandsession
gyurmo      7443  0.0  0.0   9032  2040 pts/0    S+   17:34   0:00 grep --color=auto wayland`

**Comment by electrikjesus** [comment]
I think the root user doesn't have the XDG_SESSION_TYPE environment variable set. Try:
sudo export XDG_SESSION_TYPE=wayland

**Comment by aleasto** [comment]
Stale, missing info
