### ISSUE TITLE
OpenGL ES AEP and vulkan support.

### ISSUE THREAD

**Issue by arun54321** [waydroid/waydroid#236]
Some games run only on vulkan. Please add vulkan support.

**Comment by Kikasuru** [comment]
Bump, there's no real way to play Sky: The Children of Light on a PC at the moment due to it's Vulkan requirements.  It would be amazing if we finally had a way to!

**Comment by ayasa520** [comment]
> Bump, there's no real way to play Sky: Children of the Light on a PC at the moment due to it's Vulkan requirements.  It would be amazing if we finally had a way to!

It's playable on Waydroid now. https://github.com/ayasa520/Waydroid_Sky/blob/main/README.md http://b23.tv/8JMU806

**Comment by arun54321** [comment]
> > Bump, there's no real way to play Sky: Children of the Light on a PC at the moment due to it's Vulkan requirements.  It would be amazing if we finally had a way to!
> 
> It's playable on Waydroid now. https://github.com/ayasa520/Waydroid_Sky/blob/main/README.md http://b23.tv/8JMU806

Cool. But you've deleted your repo

**Comment by ayasa520** [comment]
> > > Bump, there's no real way to play Sky: Children of the Light on a PC at the moment due to it's Vulkan requirements.  It would be amazing if we finally had a way to!
> > 
> > 
> > It's playable on Waydroid now. https://github.com/ayasa520/Waydroid_Sky/blob/main/README.md http://b23.tv/8JMU806
> 
> Cool. But you've deleted your repo
I'm sorry about this, but it's because the relevant changes have already been committed, so my repository is useless.

https://github.com/waydroid/android_device_waydroid_waydroid/commit/4bef226afbf9ae4c47b4ddd9061578bf9b227229
https://github.com/waydroid/waydroid/commit/e074cf4f8d4a1dabd6767306fbf51d25de90ebc4

**Comment by arun54321** [comment]
> > > > Bump, there's no real way to play Sky: Children of the Light on a PC at the moment due to it's Vulkan requirements.  It would be amazing if we finally had a way to!
> > > 
> > > 
> > > It's playable on Waydroid now. https://github.com/ayasa520/Waydroid_Sky/blob/main/README.md http://b23.tv/8JMU806
> > 
> > 
> > Cool. But you've deleted your repo
> 
> I'm sorry about this, but it's because the relevant changes have already been committed, so my repository is useless.
> 
> [waydroid/android_device_waydroid_waydroid@4bef226](https://github.com/waydroid/android_device_waydroid_waydroid/commit/4bef226afbf9ae4c47b4ddd9061578bf9b227229) [e074cf4](https://github.com/waydroid/waydroid/commit/e074cf4f8d4a1dabd6767306fbf51d25de90ebc4)
Did you install libhoudini or libndk for sky to work?

**Comment by arun54321** [comment]
Now vulkan and openGL ES works. Thank you devs and @ayasa520 .
