### ISSUE TITLE
Terminal apps don't work with lxc 4.0.11.

### ISSUE THREAD

**Issue by arun54321** [waydroid/waydroid#238]
Distro: Arch linux
Waydroid Image: android 11

**Comment by FlorianFranzen** [comment]
Termux crashes with `java.lang.RuntimeException: Cannot open /dev/ptmx` for me too.

**Comment by Etaash-mathamsetty** [comment]
also having this issue

**Comment by chqoot-vgxu** [comment]
The issue is caused by lxc not punting devpts on /dev/pts. I still haven't figured out why it doesn't get mounted though.

A workaround would be to manually mount it with `mount -t devpts -o defaults,mode=644,ptmxmode=666 devpts /dev/pts`

**Comment by Etaash-mathamsetty** [comment]
> The issue is caused by lxc not mounting devpts on /dev/pts. I still haven't figured out why it doesn't get mounted though.
> 
> A workaround would be to manually mount it with `mount -t devpts -o defaults,mode=644,ptmxmode=666 devpts /dev/pts`

I looked at the code and am clueless as well

**Comment by Etaash-mathamsetty** [comment]
how can i run it on waydroid startup?

**Comment by chqoot-vgxu** [comment]
You shouldn't, that's why this is a workaround and not a fix. Unfortunately I didn't have time to investigate further for a real fix

**Comment by Quackdoc** [comment]
this should be fixed now

**Comment by Etaash-mathamsetty** [comment]
> this should be fixed now

still broken for me on waydroid 1.3.0

**Comment by chqoot-vgxu** [comment]
> still broken for me on waydroid 1.3.0 error: cannot open /dev/ptmx
Updating waydroid doesn't necessarily update lxc config. Check if `lxc.pty.max = 10` is present in `/var/lib/waydroid/lxc/waydroid/config`, if not add it manually

**Comment by Etaash-mathamsetty** [comment]
> > still broken for me on waydroid 1.3.0 error: cannot open /dev/ptmx
> 
> Updating waydroid doesn't necessarily update lxc config. Check if `lxc.pty.max = 10` is present in `/var/lib/waydroid/lxc/waydroid/config`, if not add it manually

works fine now!
