### ISSUE TITLE
Waydroid doesn't show up properly

### ISSUE THREAD

**Issue by gohanko** [waydroid/waydroid#239]
## Specifications
Distro: Fedora 35
Desktop Environment: Gnome 41.1
Kernel: XanMod Linux 5.15.4-xm1.0.fc35.x86_64 from https://copr.fedorainfracloud.org/coprs/rmnscnce/kernel-xanmod/

## Problem
I'm running WayDroid on Fedora 35 using XanMod kernel as per this guide https://yanqiyu.info/2021/10/25/waydroid-fedora/

However, it seems that waydroid doesn't render properly. See pic below. Anyone has any idea whats the issue? Apps seems to launch and all as the screen changes color when you do so.

![image](https://user-images.githubusercontent.com/26451183/143305540-951960cc-8eb8-4c7b-80ff-b18c6c468462.png)

**Comment by mizzunet** [comment]
I do not have this error.
But in Telegram group, there's a note
#fix_colors
Install patched mutter packages from repo.waydro.id

(Not needed on gnome 41.1 and above)

**Comment by gohanko** [comment]
Unfortunately, I'm on Wayland and Gnome 41.1.

**Comment by karuboniru** [comment]
What graphics card are you using?

**Comment by gohanko** [comment]
Nvidia, however I think using the ZanMod kernel doesn't load the nvidia driver since when I restart it says it failed to load and fell back to nouveau.

**Comment by karuboniru** [comment]
> Nvidia

That is the problem I think, you might have to switch to swiftshader: https://wiki.archlinux.org/title/Waydroid#GPU_Requirements

**Comment by gohanko** [comment]
It's showing LineageOS properly now, but I now have another problem, tons of apps won't install. Tryna play genshin impact on it but it doesn't install. ApkPure, firefox fennec also doesn't

**Comment by cronosun** [comment]
Had exactly the same problem. Had to disable the "nouveau" kernel module - somehow this module still in use even thou gnome settings says wayland is using the integrated graphics card (intel):

```
cat /etc/modprobe.d/blacklist.conf                                                                              0|1 ✘  root@caelis-machwx9 
blacklist nouveau
```

**Comment by Aman9das** [comment]
> It's showing LineageOS properly now, but I now have another problem, tons of apps won't install. Tryna play genshin impact on it but it doesn't install. ApkPure, firefox fennec also doesn't
> 

That is because your system is x86 architecture.. Try switching to android 11 and installing linhoudini. Try this guide i wrote https://github.com/Aman9das/Waydroid_Setup_Guide (android 11 images section, patch libgbinder and delete the waydroid directory as told by jon west)

**Comment by aleasto** [comment]
Fedora is now supported on the default kernel.
Waydroid now ignores both nvidia and nouveau.
