### ISSUE TITLE
R and B color channel seems swapped

### ISSUE THREAD

**Issue by aryoadhi** [waydroid/waydroid#24]
I managed to run Waydroid on my HP laptop, but seems the color channel is swapped between R and B.

![image](https://user-images.githubusercontent.com/5029654/130228070-a9841f17-94b6-496e-896a-15893b6b4295.png)

Here's the output of `neofetch` from my laptop:

```
OS: Ubuntu 21.04 x86_64 
Host: HP Notebook 
Kernel: 5.11.0-31-lowlatency 
Uptime: 1 hour, 29 mins 
Packages: 2492 (dpkg), 4 (flatpak), 8 (snap) 
Shell: bash 5.1.4 
Resolution: 1366x768 
DE: GNOME 3.38.4 
WM: Mutter 
WM Theme: Adwaita 
Theme: Layan-dark [GTK2/3] 
Icons: Tela-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD A12-9700P RADEON R7 4C+6G (4) @ 2.500GHz 
GPU: AMD ATI Radeon R5/R6/R7 Graphics 
Memory: 2924MiB / 6976MiB 
```

I'm using a quite old laptop, which is HP 15-ba077cl.

**Comment by sickcodes** [comment]
@aryoadhi 

I did this on BlissOS and it looks the same

The toggle should be: `Settings > Accessibility > Color inversion`

![Screenshot_2021-09-05_01-53-50](https://user-images.githubusercontent.com/65906298/132112341-235124f2-6c8c-45d7-824b-49852919ab38.png)

These look like solutions (havent got kernel to test today):

https://forum.xda-developers.com/t/screen-color-all-messed-up-someone-help.3260052/

https://www.reddit.com/r/LineageOS/comments/mmxvm7/colors_glitched_wrong_looks_like_negatives_on/

https://www.reddit.com/r/Oppo/comments/j9opzo/no_option_to_disable_colour_inversion/

**Comment by erfanoabdi** [comment]
We should test on latest "waydroid" images (relevant commit: https://github.com/waydroid/android_hardware_waydroid/commit/ad2d170e20c25f6952b49235a106ef0ea922e286)
"anbox" images definitely have this bug

**Comment by aryoadhi** [comment]
Good idea, but first: how do I remove the older installation (`anbox-halium`) and test the `waydroid` images instead?

**Comment by sickcodes** [comment]
The bug may be in Lineage OS itself,  I'm trying to get ashmem and binder working as MODULES (not rebuilding the kernel every day)

https://github.com/sickcodes/anbox-modules-dkms

Ashmem works, I still get `sudo dmesg`

`[24364.917923] ashmem_linux: Unknown symbol kallsyms_lookup_name (err -2)`

Soo not sure if the wrapper thing worked.

**Comment by notsyncing** [comment]
Same here on a Surface Go 2, with Ubuntu 21.04 (GNOME 3.38.5 on wayland) on the latest 20210907 vanilla waydroid image.

![2021-09-07 15-31-26 的屏幕截图](https://user-images.githubusercontent.com/2649806/132303297-e1533461-fd66-4894-b8ee-84b4c0935e39.png)

**Comment by msizanoen1** [comment]
This is caused by GNOME Mutter not supporting BGR (the reverse of RGB) formatted framebuffers causing Waydroid to fall back to incorrectly presenting the BGR framebuffer as RGB to the display server.
Please report this issue to GNOME instead.

**Comment by erfanoabdi** [comment]
run `waydroid prop set persist.waydroid.invert_colors true` on latest update
`waydroid upgrade`

**Comment by aryoadhi** [comment]
Worked like a charm.

**Comment by CCF100** [comment]
> run `waydroid prop set persist.waydroid.invert_colors true` on latest update `waydroid upgrade`

This doesn't work for me...

**Comment by aryoadhi** [comment]
This definitely works for me. Should've corrected my reply back then: you still need to turn on color invert in Developer Settings in order to fix it.

In other words, doing *only* one of them (Waydroid config and Developer Settings invert color) won't fix the issue.

**Comment by Etaash-mathamsetty** [comment]
> This definitely works for me. Should've corrected my reply back then: you still need to turn on color invert in Developer Settings in order to fix it.
> 
> In other words, doing _only_ one of them (Waydroid config and Developer Settings invert color) won't fix the issue.

enabling both causes rendering to be extremely slow ~1 fps and forces a reinstall becuase I can't change the toggle back becuase of how laggy it is

**Comment by laichiaheng** [comment]
Is it fixed in Gnome 41?

**Comment by lazerl0rd** [comment]
> Is it fixed in Gnome 41 or not?

It's fixed in GNOME/Mutter 41.1.

**Comment by Etaash-mathamsetty** [comment]
I tried it, it looks fine now
unless my brain's RGB became BGR which is unlikely

**Comment by laichiaheng** [comment]
It has been fixed in Gnome 41.

**Comment by ACR-Jeff** [comment]
I am on Debian Bullseye vanilla, Fresh install, Installed Waydroid, I thought everything was great until I played a video and everyone in the video was blue. The instructions are not clear how to fix this issue. Any help would be appreciated. Thanks

**Comment by amkstone** [comment]
`waydroid prop set persist.waydroid.multi_windows false`
`waydroid prop set persist.waydroid.invert_colors true`

**Comment by mkasajim** [comment]
> run `waydroid prop set persist.waydroid.invert_colors true` on latest update
> `waydroid upgrade`

It did not work for me. This worked for me: Inside Waydroid - 
Settings -> Accesibility -> Scroll down to Advanced -> Color Inversion -> Iinvert colors.
