### ISSUE TITLE
[Need help] Is there any way to run waydroid on python3.8?

### ISSUE THREAD

**Issue by diyism** [waydroid/waydroid#245]
I have armbian in pine64 single board.
I've try to install waydroid:
```
# apt install waydroid
The following packages have unmet dependencies:
 waydroid : Depends: python3-gbinder but it is not installable
```
So I try to install python3-gbinder (download from https://production.repo.droidian.org/pool/main/g/gbinder-python/):
```
# gdebi python3-gbinder_1.0.0-2+git20210905094101.7365549.bullseye.production_arm64.deb 
This package is uninstallable
Dependency is not satisfiable: python3 (>= 3.9~)
```

But I have upgraded armbian, it's latest Armbian 21.08.3 Focal, and the python version:
```
# apt install python3
python3 is already the newest version (3.8.2-0ubuntu2)
```

So, is there any way to run waydroid on python3.8?

**Comment by mihalycsaba** [comment]
I think python3-gbinder for focal aarch64 might be missing.

**Comment by diyism** [comment]
There's a python3-gbinder arm64 deb package: https://production.repo.droidian.org/pool/main/g/gbinder-python/
but it depends on python 3.9:

```
# gdebi python3-gbinder_1.0.0-2+git20210905094101.7365549.bullseye.production_arm64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: python3 (>= 3.9~)
```

```
# apt-cache policy python3
python3:
  Installed: 3.8.2-0ubuntu2
  Candidate: 3.8.2-0ubuntu2
  Version table:
 *** 3.8.2-0ubuntu2 500
        500 http://ports.ubuntu.com focal/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by cniw** [comment]
@diyism @mihalycsaba you should build it from source https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1

**Comment by diyism** [comment]
> @diyism @mihalycsaba you should build it from source https://gist.github.com/cniw/98e204d7dbc73a3fa1bf61629b2a2fc1

Thank you, @cniw , you're a genius, your script successfully compiled and installed all needed packages into my pine64 SBC.

But the armbian linux kernel lacks Kprobes support, so I'm asking the armbian community to help: https://github.com/armbian/build/issues/3883

**Comment by aleasto** [comment]
Up to your distribution.
Of course you can build the dependencies yourself.
