### ISSUE TITLE
https://repo.waydro.id is down

### ISSUE THREAD

**Issue by surlyhacker** [waydroid/waydroid#249]
https://repo.waydro.id is not online

**Comment by Qbers13** [comment]
I found this page on Internet Archive: https://web.archive.org/web/20211207142500/https://repo.waydro.id/

**Comment by parcelcat** [comment]
The site seems to be back up.

**Comment by MyGithub4iMh9CawHdyu** [comment]
down, more than 24 h.

**Comment by surlyhacker** [comment]
down right now again

**Comment by ZecaSamicas** [comment]
It's down as well at the time

**Comment by 4iMh9CawHdyu** [comment]
Since yesterday.....
