### ISSUE TITLE
How to use integrated instead of amd?

### ISSUE THREAD

**Issue by Latrolage** [waydroid/waydroid#250]
How can I get waydroid to use the integrated GPU instead of my amd gpu?

**Comment by Quackdoc** [comment]
you can use the gpu script I have in my repo as a work around. it should work, but I haven't tested it too thoroughly https://github.com/Quackdoc/waydroid-scripts

**Comment by Quackdoc** [comment]
you can try doing `gralloc.gbm.device=/dev/dri/renderDxxx" >> /var/lib/waydroid/waydroid_base.prop` replace xxx with appropriate number, but if that doesn't work you can try using my script in my repo for gpu

https://github.com/Quackdoc/waydroid-scripts

**Comment by aleasto** [comment]
We have some documentation here: https://docs.waydro.id/debugging/known-issues#graphical-issues.
