### ISSUE TITLE
mp4 video playback issue

### ISSUE THREAD

**Issue by jzaor** [waydroid/waydroid#252]
When I start playing the mp4 video, it starts to  play audio but visible content is played after.  How to fix it? It’s not important which application I used to play mp4 movie.

**Comment by jzaor** [comment]
Update: here is sample movie:
https://www.jw.org/finder?srcid=jwlshare&wtlocale=B&lank=pub-wsb_2_VIDEO

**Comment by jzaor** [comment]
Next update: This issue persistS across builds: Like the VANILLA or the SAKURA.

**Comment by Quackdoc** [comment]
video plays for me, could you get the logcat? 

sudo waydroid shell 
logcat > whever/log/stored/logcat.txt

**Comment by jzaor** [comment]
[logcat.txt](https://github.com/waydroid/waydroid/files/7775910/logcat.txt)

Here it is. Thank you for your interest.

**Comment by jzaor** [comment]
[logcat.txt](https://github.com/waydroid/waydroid/files/7776296/logcat.txt)

Here it is. Thank you for your interest. And help, I hope.

**Comment by Quackdoc** [comment]
can you try to swap between HW and SW decoding, it should be at the bottom of the screen, also if you could open up the stats screen and take a screenshot

it's the cog, then just press toggle stats, not any of the numbers

**Comment by jzaor** [comment]
I installed the VLC Player, yesterday. It plays this movie in the right way. The Gallery app or the JWLibrary app did not play it right way. 

Here is the infos from VLC Player:

![2C2519EB-109F-4A84-8333-01291A6BDE07](https://user-images.githubusercontent.com/96311782/147468950-57cae0f1-6ce2-4245-8fa7-15fdc8bcfc70.jpeg)

**Comment by jzaor** [comment]
UPDATE: I played the movie directly under Ubuntu 21.10 outside waydroid. It was played perfectly. I think the problem is somewhere in the Waydroid´s codecs. I do not know exactly, how to repair it.

**Comment by Quackdoc** [comment]
> can you try to swap between HW and SW decoding, it should be at the bottom of the screen, also if you could open up the stats screen and take a screenshot
> 
> it's the cog, then just press toggle stats, not any of the numbers

can you try this?

**Comment by jzaor** [comment]
In which app?

**Comment by jzaor** [comment]
I tried to switch on and off the hw acceleration in the vlc. Both was working ok. In the Lineageos 17.1 i can not. I do not know how to do. Maybe in the dev. options?

**Comment by Quackdoc** [comment]
in mpv

**Comment by jzaor** [comment]
Sorry I can not. The MPV-android package installation fails wish “unknown error” or “app is not campatible”.

**Comment by jzaor** [comment]
UPDATE: I have installed mpv-android package successfully.
![9788E114-31C0-436E-87F3-1C87C53FBE84](https://user-images.githubusercontent.com/96311782/147752774-668e3774-c63b-4acf-8754-6d5203a8895e.jpeg)

Video was played in the right way.
SW switch did not its work. Stays on “SW”, clicked on it or not. Didn’t change anything.

**Comment by n1lby73** [comment]
how do i install mpv-android cause i'm also having same issue and does it play the video in the jw app on waydroid

**Comment by jzaor** [comment]
Firstly I had to install the mpv-linux package. After I had installed the android apk. But the primary issue was not resolved. Only for diagnostic  purpose.

**Comment by Quackdoc** [comment]
could you update the post using the issue template as a guide?

**Comment by n1lby73** [comment]
> Firstly I had to install the mpv-linux package. After I had installed the android apk. But the primary issue was not resolved. Only for diagnostic purpose.

meaning jw library doesn't play video still?

**Comment by jzaor** [comment]
Yes, the problem continues with video can’t be played by the JW Library application.

**Comment by jzaor** [comment]
> could you update the post using the issue template as a guide?

You want to have the “Guide” word into the topic label?

**Comment by Quackdoc** [comment]
no, there is a new issue template that should be filled out.

**Comment by aleasto** [comment]
We've reworked out media stack. Please reopen if still reproducible on the latest android images
