### ISSUE TITLE
Waydroid on Guix

### ISSUE THREAD

**Issue by phodina** [waydroid/waydroid#258]
Hi there,

I have attempted to port the waydroid on [Guix](https://guix.gnu.org/).

This gist contains the [patches](https://gist.github.com/phodina/d5f75f57af92595324b58cecaf41919f) for the following: `libglibutil`, `libgbinder`, `python-gbinder`, `python-pyclip`,`waydroid` and `waydroid-script`.

Also it contains the changes for the Linux kernel. These are verified by checking the config file for the booted kernel:
```
$ cat /run/booted-system/kernel/.config
...
CONFIG_ASHMEM=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
```

After that I ran the following commands:
```
$ sudo waydroid init
$ sudo waydroid container start
## Another shell
$ waydroid session start
## Another shell
$ sudo waydroid logcat
$ waydroid shell
$ waydroid show-full-ui 
```

I can get the shell, output in the logcat and show-full-ui.

Here are contents of `/etc/gbinder.d/anbox.conf`
```
[Protocol]
/dev/binder = aidl2
/dev/vndbinder = aidl2
/dev/hwbinder = hidl

[ServiceManager]
/dev/binder = aidl2
/dev/vndbinder = aidl2
/dev/hwbinder = hidl
```

However, I do have question where exactly is this file `/etc/gbinder.d/anbox.conf` referenced as I'd like to substitute the location for one in `/gnu/store` as it's common for Guix and Nix.

Also there is the issue of rotating the display and resizing, but I guess that's solved somewhere in the issues, right?

![20211225_17h48m30s_grim](https://user-images.githubusercontent.com/2997905/147389720-48e7fe3f-0d51-4934-ad40-70a49a3160cc.png)

**Comment by Kabouik** [comment]
Impressive work. Do you plan on submitting it as a package or suite of packages for Guix, @phodina? I would love to use that on Guix but I am way below the average skill level of average Guix users, and I probably wouldn't be able to redo what you did in your gist without breaking things.

**Comment by phodina** [comment]
Hi, it's already in progress https://issues.guix.gnu.org/51737.

**Comment by Kabouik** [comment]
Great, looking forward to trying it when it's merged! Thanks for your work.

**Comment by phodina** [comment]
Finally here's the image, don't know why it couldn't open the one from the Guix thread. Well works well just needs some polishing - patch to remove default image.
![waydroid](https://user-images.githubusercontent.com/2997905/200678525-824f28cb-a7c9-4fbc-ac33-94b9f3c30f1a.png)

**Comment by bphd** [comment]
Is it available in Guix repository?

**Comment by bphd** [comment]
And now?

**Comment by bphd** [comment]
@phodina And now?

**Comment by Kabouik** [comment]
Pinging @phodina again too because I'm still looking forward to using Waydroid on Gnome. I'm wondering if it stalled or is considered done but just awaiting someone among the Guix people with commit rights to pick it up, since the last comment in the Guix issue is already 2 years old. Thanks again for all the work you've already put into it.

**Comment by Pacific6938** [comment]
Any progress?
