### ISSUE TITLE
waydroid hangs on container start

### ISSUE THREAD

**Issue by jumpers775** [waydroid/waydroid#266]
i am using a fresh ubuntu 21.10 system with depends installed, and i have installed following the steps listed on the homepage (using hirsute for step 1). When i run `sudo waydroid container start` it hangs indefinitely. i have narrowed this down to the sleep function on line 114 of /usr/lib/waydroid/tools/actions/container_manager.py. The file /var/lib/waydroid/session.cfg does not exist. im not sure how this is meant to be created though. manually creating it hangs at `[gbinder] Service manager /dev/anbox-binder has appeared` instead. how is this meant to be created?

**Comment by Quackdoc** [comment]
please upload the results from both `waydroid log` and `sudo systemctl status waydroid-container.service`

**Comment by aleasto** [comment]
`sudo waydroid container start` is a daemon, it's supposed to be running forever.
No, obviously you should not be manually creating `/var/lib/waydroid/session.cfg` but running `waydroid show-full-ui` or `waydroid session start`, to start waydroid
