### ISSUE TITLE
zorion os canot start waydroid due to XDG Session is not "wayland"

### ISSUE THREAD

**Issue by pcpro007** [waydroid/waydroid#272]

**Comment by NastyaGrifon** [comment]
Waydroid supports running on Wayland display server only. Please provide the output of 

`cat /etc/*-release`

**Comment by pcpro007** [comment]
DISTRIB_ID=Zorin
DISTRIB_RELEASE=16
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Zorin OS 16"
NAME="Zorin OS"
VERSION="16"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://zorin.com/help/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by NastyaGrifon** [comment]
Right, this should help: 

before you login you should
1. Click the gear icon on the lower right
![Screenshot_20220122_211406](https://user-images.githubusercontent.com/14854919/150648710-62dadb5e-9371-443a-88d1-b2e94937198c.png)

2. Select "Zorin Desktop on Wayland"
![Screenshot_20220122_210835](https://user-images.githubusercontent.com/14854919/150648669-7014e978-5e80-4950-8f41-343b2606b107.png)
3. Enter your password
4. Log in 

XDG Session error should be gone

**Comment by pcpro007** [comment]
[14:25:54] Failed to start Clipboard manager service, check logs
 
i now get this.

**Comment by electrikjesus** [comment]
That is normal and can be dismissed

**Comment by omarenm** [comment]
> Right, this should help:
> 
> before you login you should
> 
> 1. Click the gear icon on the lower right
>    ![Screenshot_20220122_211406](https://user-images.githubusercontent.com/14854919/150648710-62dadb5e-9371-443a-88d1-b2e94937198c.png)
> 2. Select "Zorin Desktop on Wayland"
>    ![Screenshot_20220122_210835](https://user-images.githubusercontent.com/14854919/150648669-7014e978-5e80-4950-8f41-343b2606b107.png)
> 3. Enter your password
> 4. Log in
> 
> XDG Session error should be gone

I don't get that gear icon, what can I do?
