### ISSUE TITLE
Failed to start Clipboard manager service, check logs

### ISSUE THREAD

**Issue by pr0fsmith** [waydroid/waydroid#276]
When I run 
"waydroid session start"

I get
"Failed to start Clipboard manager service, check logs"

Then nothing happens. 

I'm running Ubuntu 21.10 in VM (Qemu)

**Comment by nyan2d** [comment]
You need to install python-clips.

**Comment by pr0fsmith** [comment]
I just installed it and get the same error message.  I now get this
additional message "[gbinder] Service manager /dev/anbox-binder has
appeared"

**Comment by mizzunet** [comment]
> "[gbinder] Service manager /dev/anbox-binder has
appeared

That's normal.

**Comment by mahdi-ln** [comment]
> You need to install python-clips.

How should be done in Arch Linux (Endeavour OS)

**Comment by doctorcolossus** [comment]
> > You need to install python-clips.
> 
> How should be done in Arch Linux (Endeavour OS)

`pip install pyclip` as root worked for me.

**Comment by mizzunet** [comment]
> Failed to get service waydroidplatform, trying again...

It probably because you had tried open waydroid.desktop or execute `waydroid show-full-ui` before starting container. Both start session. Session is to be started after container is present.

**Comment by doctorcolossus** [comment]
@mizzunet, thank you for your input!

I don't think that is the issue, since I have already started the `waydroid-container` systemd service packaged with waydroid in the Arch User Repository. The service file looks like this:

```
[Unit]
Description=Waydroid Container

[Service]
ExecStart=/usr/bin/waydroid container start
ExecStop=/usr/bin/waydroid container stop
ExecStopPost=/usr/bin/waydroid session stop

[Install]
WantedBy=multi-user.target
```

So `waydroid container start` is indeed called:

```
# systemctl status waydroid-container
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2022-03-24 22:27:55 MDT; 3min 6s ago
   Main PID: 4725 (python3)
      Tasks: 1 (limit: 38120)
     Memory: 14.1M
        CPU: 104ms
     CGroup: /system.slice/waydroid-container.service
             └─4725 python3 /usr/bin/waydroid container start

kov. 24 22:27:55 dragonfly systemd[1]: Started Waydroid Container.
```

**Comment by aleasto** [comment]
https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm
