### ISSUE TITLE
Pointer Capture is not supported

### ISSUE THREAD

**Issue by Snivyer1910** [waydroid/waydroid#279]
Games/Apps that rely on Android 8's Pointer Capture do not work properly

Ex: In Minecraft, the mouse is inverted (in all axis) and when it reaches the Window border you can't move the camera anymore

since the MCPE Launcher is EOL, this could be supported in this program as an alternative to run Minecraft Bedrock or other Android games that support Mouse and Keyboard on Linux

**Comment by stsquad** [comment]
I was confused by this because the pointer works fine for the browsing of the normal Waydroid/Lineage GUI. Waydroid doesn't seem to think it has a physical keyboard plugged in though.

**Comment by stsquad** [comment]
This PR fixes the axis inversion although I still see a problem on multi-monitor setups turning left that eventually the mouse runs off the screen. Not sure if this is a WM issue or with Waydroid itself.

**Comment by DemonicSavage** [comment]
It seems it's a Waydroid problem - either that or all KWin, Sway and Weston present the issue.

**Comment by DemonicSavage** [comment]
A cursory (heh) glance in the [Wayland specs for pointers](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer) doesn't yield anything conclusive, but I'm unfamiliar with Wayland from a dev perspective.

**Comment by stsquad** [comment]
There is https://wayland.app/protocols/pointer-constraints-unstable-v1 but it's not a stable API. Maybe the other alternative is to reset the raw xy and just report a delta?

**Comment by Snivyer1910** [comment]
can we reopen this issue? while the inverted mouse is fixed the mouse locking is not and when the mouse reaches the screen border the camera stops moving

(will upload video soon™)

**Comment by Snivyer1910** [comment]
https://youtube.com/shorts/JSsYXyqOw2E?feature=share

**Comment by DemonicSavage** [comment]
@Snivyer1910 I'm also interested in this issue being reopened.

**Comment by stsquad** [comment]
It seems this isn't the whole fix. However I would need some pointers to how waydroid deals with pointer capture so we can ensure the pointer doesn't scroll of the side if you are not fullscreen or have multiple displays. I can't re-open the issue though so perhaps a new bug would be better?

**Comment by DemonicSavage** [comment]
Done.

**Comment by DemonicSavage** [comment]
@stsquad Created a new bug report.
