### ISSUE TITLE
Is it possible to use a lower version of Android to 7.1, for example?

### ISSUE THREAD

**Issue by rizzini** [waydroid/waydroid#280]
Waydroid is awesome, but the Android version is too recent for my shy Intel i3-4170. It takes too long to boot and consumes more resources than I'm willing to "allocate" to it.

If possible, where I can download the image that's compatible with Waydroid?

**Comment by mizzunet** [comment]
Unfortunately, Android Nougat images for waydroid aren't available. Only Android 10 & 11 images are available

You might use Anbox image which is Android 7.1, but I'm not sure. Try asking developer in the Matrix 

>  where I can download the image that's compatible with Waydroid?
https://sourceforge.net/projects/waydroid/
https://sourceforge.net/projects/blissos-dev/files/waydroid/

**Comment by aleasto** [comment]
Nobody is going to invest time into deprecated android versions, sorry
