### ISSUE TITLE
How Waydroid works in technical?

### ISSUE THREAD

**Issue by ClickNinYT** [waydroid/waydroid#287]
Hi, I'm ClickNin. Sorry as this is not exactly an issue but rather a question.
How did the Waydroid team get Android to work though LXC container? I would like a detail or just some steps on how that can be done. I looked from Google and present me with some information that I need to manually write config, adjust so that the initramfs is the Root File System of Android itself.

Thanks.

**Comment by marschr** [comment]
I've looked into the code a bit few months ago as I was trying to make it work on ARM64 but didn't find the time to dig deeper. An overview of the architecture would be nice, what is forwarded straight to the host and what and why has mid-layers like libgbinder. Also, some overview of the Android ROM patches.
