### ISSUE TITLE
What are the installation instructions for desktop ubuntu 21.04? 

### ISSUE THREAD

**Issue by Dinibewerbig** [waydroid/waydroid#29]
What are the necessary steps for installing Waydroid on desktop Ubuntu? I know already that I have to enable Wayland but have no clue how to install Waydroid.

**Comment by sickcodes** [comment]
https://github.com/sickcodes/droid-native

For now, it's arch only but if @erfanoabdi gets a desktop repo going I'll commit there 😂

Modules from here for Ubuntu https://github.com/remote-android/redroid-modules

**Comment by farmerbb** [comment]
Installation instructions have been posted here: https://docs.waydro.id/usage/install-on-desktops

**Comment by erfanoabdi** [comment]
hirsuite added to docs and repo
