### ISSUE TITLE
Unhandled Page fault on Pinephone Pro

### ISSUE THREAD

**Issue by Arsen6331** [waydroid/waydroid#291]
Every time I open Waydroid on my Pinephone Pro, I get an error message in journalctl, and the entire Linux GUI, even outside the waydroid window (which is not visible) starts breaking. It only stops when I use ssh and kill the process.

This is the error message:
```
Jan 30 14:28:59 danctnix kernel: panfrost ff9a0000.gpu: Unhandled Page fault in AS0 at VA 0x0000000107ED2CC0
                                 Reason: TODO
                                 raw fault status: 0x6F002C1
                                 decoded fault status: SLAVE FAULT
                                 exception type 0xC1: TRANSLATION_FAULT_1
                                 access type 0x2: READ
                                 source id 0x6F0
Jan 30 14:28:59 danctnix kernel: panfrost ff9a0000.gpu: js fault, js=0, status=JOB_BUS_FAULT, head=0x8badcc0, tail=0x8badcc0
Jan 30 14:28:59 danctnix kernel: panfrost ff9a0000.gpu: gpu sched timeout, js=0, config=0x3300, status=0x8, head=0x8bd1cc0, tail=0x8bd1cc0, sched_job=00000000fed24003
```
It keeps repeating until the process is killed or I focus another window. I installed it from the repos, using `sudo pacman -S waydroid waydroid-image`, and started it by running `sudo systemctl start waydroid-container` followed by running Waydroid's desktop entry.

This is all running on the latest release of Pine64-Arch: https://github.com/dreemurrs-embedded/Pine64-Arch

**Comment by Herrie82** [comment]
I can confirm I have the same on LuneOS. I can get it to run using software renderer, but it's very slow. According to @erfanoabdi the mesa version provided with Waydroid is probably too old for the RK3399 to properly work. I can confirm other HW accelerated tests work fine on PPP.

**Comment by pgwipeout** [comment]
It seems the version of Mesa in Lineage 17 is too old for reliable panfrost usage.
Operating in software mode works, add the following to `/var/lib/waydroid/waydroid_base.prop`:
```
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
```

The question is, will this be solved by moving to Lineage 18, or is that also too old?
Has anyone had success using Android at all on Panfrost yet?

**Comment by jjardon** [comment]
For reference, upstream issues in Mesa is here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5928

**Comment by Herrie82** [comment]
> For reference, upstream issues in Mesa is here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5928

I doubt it's a Mesa issue really, other tests seem to work fine at my end. So I'm pretty sure it's the Mesa version used by Waydroid itself.

**Comment by Djhg2000** [comment]
Working on the hypothesis that Mesa in the Android image is too old, would there be any way to use the Mesa libraries from the host?

**Comment by rothn** [comment]
I get:

```
Sep 15 21:15:46 manjaro-arm kernel: panfrost ff9a0000.gpu: gpu sched timeout, js=0, config=0x3302, status=0x8, head=0x61e7240, tail=0x61e7240, sched_job=00000>
Sep 15 21:15:46 manjaro-arm kernel: panfrost ff9a0000.gpu: Soft-stop failed
Sep 15 21:15:47 manjaro-arm kernel: panfrost ff9a0000.gpu: Unhandled Page fault in AS2 at VA 0x0000000109E66780
                                    Reason: TODO
                                    raw fault status: 0x6F002C1
                                    decoded fault status: SLAVE FAULT
                                    exception type 0xC1: TRANSLATION_FAULT_1
                                    access type 0x2: READ
                                    source id 0x6F0
Sep 15 21:15:47 manjaro-arm kernel: panfrost ff9a0000.gpu: js fault, js=0, status=JOB_BUS_FAULT, head=0xbbe5240, tail=0xbbe5240
```

**Comment by rothn** [comment]
This 3-step guide that demonstrates building from the latest sources solves the issue: https://docs.google.com/document/d/1Sly_VH3w6wFIdE72WXijQegoHZh8IxEnJ9m0hH7GodU/edit#

**Comment by Herrie82** [comment]
> This 3-step guide that demonstrates building a GAPPS image from the latest sources solves the issue: https://docs.google.com/document/d/1Sly_VH3w6wFIdE72WXijQegoHZh8IxEnJ9m0hH7GodU/edit#
Any chance you could share the image that you already built? Saves a lot of work :)

**Comment by rothn** [comment]
I've added prebuilt images to the guide for people who want to skip the first step. However, I generally wouldn't recommend this. It's usually better to be safe and build software yourself.

**Comment by aleasto** [comment]
Waydroid now uses the latest mesa
