### ISSUE TITLE
SFOS/Xperia XZ2c: apps always open in freeform mode when started with am

### ISSUE THREAD

**Issue by teleshoes** [waydroid/waydroid#292]
e.g.: these two commands both start CoolReader in freeform instead of fullscreen windowing mode.
`am start org.coolreader/.CoolReader`

`am start-activity -n org.coolreader/.CoolReader -a android.intent.action.MAIN -c android.intent.category.LAUNCHER --activityType 1 --windowingMode 1`

this is on SFOS on an Xperia XZ2 Compact

**Comment by aleasto** [comment]
Disable `persist.waydroid.multi_windows`
