### ISSUE TITLE
cannot use swipe gesture in certain apps

### ISSUE THREAD

**Issue by Mchito** [waydroid/waydroid#296]
Swiping doesn't work in some apps, whilst usually I can make it by simply left clicking and dragging.
In a game I play, only one-spot clicks are available. Though except that everything works perfect, I do need swipes to continue the story. The issue persists both on full-ui and multi windows.
![스크린샷, 2022-02-04 00-26-53](https://user-images.githubusercontent.com/76689397/152373406-d76d67f7-11d2-460d-9cae-c5bd97258903.png)
I need swipes when I change the angle of view in the game. I'm fine without it usually, but at certain points I can proceed only with the gesture involved.  

Information about my system and the app with this issue:

OS      : Pop!_OS 21.10(amd64)
Device: Laptop, ASUS Vivobook X509DA(without touch interface of course)
Kernel : 5.16.0-4.2-liquorix-amd64
DE      : Gnome 40.4(with COSMIC extension)
App    : Layton Brothers Mystery Room, English, installed through Google Play

**Comment by aleasto** [comment]
You can now emulate touch inputs with `persist.waydroid.fake_touch`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour
