### ISSUE TITLE
No Internet connection, WiFi switch switches back off

### ISSUE THREAD

**Issue by firefoxlover** [waydroid/waydroid#300]
The issue seems to be known.

Waydroid itself works wonderfully, but the Internet doesnt. 

Can you add a detailed step-by-step explanation of what to do to solve it?

Or make Waydroid itself install the needed parts to fix it on its own? 

Using Kubuntu non-LTS with Backports.

Thanks!

**Comment by parithy** [comment]
able to replicate this issue

**Comment by v1nsai** [comment]
I'm on Arch, following [the guide on the wiki](https://wiki.archlinux.org/title/Waydroid#Usage).  After running the following to upgrade and fully re-init:
```
sudo rm -rf /var/lib/waydroid /home/.waydroid
rm -rf ~/waydroid ~/.share/waydroid ~/.local/share/applications/*aydroid* ~/.local/share/waydroid
sudo waydroid init -s GAPPS -f
waydroid session start
```
Once it starts up I have no network connectivity.  I'm not sure if wifi is supposed to be running, the Arch wiki makes no mention of it, but when I try to turn it on, it switches back off after a few seconds.  I ran `waydroid logcat` and it looks like this is failing.  
```
WifiNative: Failed to connect to supplicant
WifiNative: Failed to start supplicant
```
I can provide full logs if that helps anyone, I'm still investigating this

**Comment by vuongtuha** [comment]
Help me please, I'm on the same boat. Some guys said that my Xanmod kernel is the problem. But after switch login to kernel LTS original from kernel.org, it still didn't show any connection avaiable. I still can install *.apk normaly but cannot connect to internet is too big deal T^T

**Comment by North-West-Wind** [comment]
> I'm on Arch, following [the guide on the wiki](https://wiki.archlinux.org/title/Waydroid#Usage). After running the following to upgrade and fully re-init:

@v1nsai  thank you so much. Turns out it is just firewall blocking it.

**Comment by HeroRareheart** [comment]
I found disabling my firewall and then restarting Waydroid fixed it. I'm using the GUFW SNAP because I'm lazy and it works sooooo good enough for me. What firewall solutions are you running and does disabling it work for you or is is this just me?

**Comment by aleasto** [comment]
You can try the GUFW instructions here https://docs.waydro.id/debugging/networking-issues#setting-up-your-firewall
