### ISSUE TITLE
SailfishOS: failed to start due to vndservicemanager crashed

### ISSUE THREAD

**Issue by DCMMC** [waydroid/waydroid#305]
**Describe the bug**

In Sailfish OS, waydroid failed to show Android UI due to vndservicemanager crashed.

```
02-13 13:54:30.291    18    18 I SELinux : SELinux: Loaded service_contexts from:
02-13 13:54:30.291    18    18 I SELinux :     /vendor/etc/selinux/vndservice_contexts
02-13 13:54:30.291    18    18 E VendorServiceManager: SELinux: Failed to acquire service_manager context. Aborting.
02-13 13:54:30.291    18    18 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18 (vndservicemanag), pid 18 (vndservicemanag)
```

`/vendor/bin/vndservicemanager` crashed due the selinux `getcon` return nonzero:

```c
  | if (selinux_enabled > 0) {
  | if (sehandle == NULL) {
  | ALOGE("SELinux: Failed to acquire sehandle. Aborting.\n");
  | abort();
  | }
  |  
  | if (getcon(&service_manager_context) != 0) {
  | ALOGE("SELinux: Failed to acquire service_manager context. Aborting.\n");
  | abort();
  | }
  | }
```

**Screenshots**

<img src="https://user-images.githubusercontent.com/8016514/153757046-567f3cab-0b31-40d9-829e-825acde228f2.png" width="200">

**General information (please complete the following information):**
 - Waydroid tools Version: **1.2.0**
 - Waydroid Images Version: **VANILLA 20211021**

**Smartphone (please complete the following information):**
 - Device: **Oneplus 6**
 - OS: **Sailfish OS 4.3.0.12**
 - Mainline or Halium: **Hybris**
 - Kernel version: **4.9.209-hybris**

**Additional context**

[Kernel configs](https://github.com/DCMMC/android_kernel_oneplus_sdm845-stable/blob/dc5bf16a766d2c4aeea3e088d468c59100a63bd4/arch/arm64/configs/enchilada_defconfig#L1-L5)

[Waydroid Sailfish OS packaging](https://github.com/sailfishos-open/waydroid)

**Logs (please upload as file)**
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

[waydroid_logcat.log](https://github.com/waydroid/waydroid/files/8055693/waydroid_logcat.log)

[waydroid.log](https://github.com/waydroid/waydroid/files/8055694/waydroid.log)

**Comment by erfanoabdi** [comment]
Thanks for logs but problem is actually something else (media!)
can send me your prop file: /var/lib/waydroid/waydroid_base.prop

**Comment by DCMMC** [comment]
Thank you a ton for the reply and pointing out the real problem.

Here is my prop file:

```
ro.hardware.gralloc=sdm845
media.settings.xml=/system/etc/media_profiles_vendor.xml
ro.vendor.extension_library=libqti-perfd-client.so
ro.hardware.vulkan=sdm845
ro.opengles.version=196610
waydroid.system_ota=http://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=http://ota.waydro.id/vendor/waydroid_arm64/HALIUM_9.json
waydroid.tools_version=1.2.0
ro.product.waydroid.brand=OnePlus
ro.product.waydroid.device=OnePlus6
ro.product.waydroid.manufacturer=OnePlus
ro.product.waydroid.model=ONEPLUS A6003
ro.build.fingerprint=OnePlus/OnePlus6/OnePlus6:9/PKQ1.180716.001/1908012000:user/release-keys
```

**Comment by DCMMC** [comment]
I found `/system/etc/media_profiles_vendor.xml` is missed in system.img. After copy this file from my host. Waydroid is now work perfectly. Thank you very much!
