### ISSUE TITLE
Infared (Consumer IR) support

### ISSUE THREAD

**Issue by upintheairsheep** [waydroid/waydroid#307]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when...

I want this to be a full Android thing for future projects. 

**Describe the solution you'd like**

Add Support for external IrDA or regular infared blasters to be used as Android IR controllers.
**Describe alternatives you've considered**

**Additional context**

**Comment by erfanoabdi** [comment]
IR should be working on halium devices, if there's any bug please share logs

**Comment by aleasto** [comment]
Stale, missing info
