### ISSUE TITLE
Clipboard doesn't work (Python 3.10)

### ISSUE THREAD

**Issue by Shatur** [waydroid/waydroid#309]
**Describe the bug**
The clipboard doesn't shared between the container and the host.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.2.0
 - Waydroid Images Version: LineageOS 17.1-20211021 

**Phone:**
 - OS: ArchLinux Arm
 - GPU: Mali-400 MP2
 - Kernel version: linux-megi 5.16.8
 - Host mesa version: 21.3.6
 - Desktop: Plasma Mobile / Phosh (tested on both)

**Logs**

When I trying co copy anything I have the following error message:

```
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
Exception ignored in: 'gbinder.local_transact_callback'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
```

Please, let me know If I need to provide more information, I just assume that the issue in `IClipboard.py`.

**Comment by sakthimaan** [comment]
@Shatur install xlip to resolve this issue,

`sudo pacman -S xclip`

**Comment by Shatur** [comment]
@sakthimaan I installed `xclip` but the error is still there. It's easy to reproduce, just copy something in the host machine and try to past it into Waydroid.

**Comment by sakthimaan** [comment]
@Shatur  can you test the **pyclip** by executing `python -m pyclip paste`

**Comment by sakthimaan** [comment]
I have faced the same issue and it is resolved after installing xclip,

**Comment by Shatur** [comment]
> @Shatur can you test the pyclip by executing python -m pyclip paste

@sakthimaan Hm... I have the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/pyclip/__main__.py", line 16, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pyclip/cli.py", line 39, in main
    ret = _main(args)
  File "/usr/lib/python3.10/site-packages/pyclip/cli.py", line 23, in _main
    sys.stdout.buffer.write(paste())
  File "/usr/lib/python3.10/site-packages/pyclip/__init__.py", line 42, in paste
    return DEFAULT_CLIPBOARD.paste(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pyclip/xclip_clip.py", line 102, in paste
    raise ClipboardException(
pyclip.base.ClipboardException: Copy failed. xclip returned code: 1 Stderr: b'Error: target STRING not available\n' Stdout: b
```

**Comment by personWithCommonSense** [comment]
On Ubuntu I fixed clipboard by installing wl-clipboard, run following: `sudo apt install wl-clipboard`

**Comment by sidevesh** [comment]
Installing wl-clipboard and restarting container fixed it for me too on arch

**Comment by dbogdanov** [comment]
I have this issue with `wl-clipboard`, `pyclip` and `xclip` installed. Double clicking on any text field in any Android app leads to the error.

Waydroid 1.3.3, Weston 10.0.1

**Comment by aleasto** [comment]
> I have this issue with `wl-clipboard`, `pyclip` and `xclip` installed. Double clicking on any text field in any Android app leads to the error.
> 
> Waydroid 1.3.3, Weston 10.0.1

What version of pyclip?

**Comment by dbogdanov** [comment]
pyclip 0.7.0

**Comment by aleasto** [comment]
Odd, i cannot reproduce here.

Does `wl-copy foo` - `wl-paste` work by its own? And what about `echo foo | pyclip copy` - `pyclip paste` ?

**Comment by aleasto** [comment]
I may have found a way to reproduce: Starting a nested wayland compositor so that the **clipboard is empty**, then try to select text in android. Is this what is happening @dbogdanov ?

**Comment by BlurryFlurry** [comment]
> I have this issue with `wl-clipboard`, `pyclip` and `xclip` installed. Double clicking on any text field in any Android app leads to the error.
> 
> Waydroid 1.3.3, Weston 10.0.1

I have the same issue. even copying a text in the guest machine leads to this error

**Comment by aleasto** [comment]
Fixed redundantly with https://github.com/waydroid/waydroid/commit/cd0a81cf28bfa990bb85d660c239a9e45bcb48a6 and https://github.com/waydroid/android_vendor_waydroid/commit/206ab21899afe9ece0f5cbf3e2c89b269c6bb6cc

**Comment by aleasto** [comment]
Beware that you're not supposed to be able to share your clipboard between waydroid and the X11 desktop when using a nested wayland compositor. The clipboard is implemented by the wayland compositor and does not talk with the outer X11 clipboard.

*However* there is an odd interaction that allows clipboard sharing with the outer X11 desktop in one specific situation:
The nested wayland compositor is using the default `wayland-0` socket name and you run `waydroid session start` (or `show-full-ui`) without setting `WAYLAND_DISPLAY=wayland-0`. When `WAYLAND_DISPLAY` is unset, android will default to rendering to `wayland-0` while `pyclip` will fallback to xorg and xclip.

**Comment by ElectricAlgorhythm** [comment]
I was troubleshooting and ended up realizing that pipx wouldn't work for pyclip in this instance, it has to be installed with pip so waydroid will use it.

**Comment by TriMoon** [comment]
@aleasto please eliminate the need for the user to install `pyclip` on their own or whatever else is needed for the clipboard to work properly in waydroid<->host.
It's fundamental functionality that should be build-in into waydroid, just like the keyboard and mouse is.

**Comment by TheGrave** [comment]
> On Ubuntu I fixed clipboard by installing wl-clipboard, run following: `sudo apt install wl-clipboard`
> 
> Edit: Also make sure that pyclip is installed, `pip install pyclip`

This doesn't work in 24.04:

pip install pyclip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

I tried also sudo apt install python3-pyclipper but it doesn't fix the problem.
