### ISSUE TITLE
Error when installing on EndeavourOS (Arch-based)

### ISSUE THREAD

**Issue by hmtheboy154** [waydroid/waydroid#31]
Hello, I'm trying to install WayDroid on EndeavourOS. I manually compiled `libglibutil`, `libgbinder` and `python-gbinder` and trying to start the container and the session then this happened

```
(003987) [01:42:50] Failed to add service waydroidhardware: -1
(003998) [01:42:51] Failed to add service waydroidclipboard: -1
(003998) [01:42:51] Failed to add service waydroidusermonitor: -1
```
I'm using xanmod kernel which already have stuff for Android compiled like ashmem or binder.

[tools.log](https://github.com/waydroid/waydroid/files/7117584/tools.log)

**Comment by erfanoabdi** [comment]
create a file in /etc/gbinder.conf:

```
[General]
ApiLevel = 29
```

**Comment by hmtheboy154** [comment]
It still the same

**Comment by erfanoabdi** [comment]
> create a file in /etc/gbinder.conf:
> 
> ```
> [General]
> ApiLevel = 29
> ```

nevermind, was not needed after all

**Comment by hmtheboy154** [comment]
closed, thanks for helping me on Telegram

**Comment by decoherencer** [comment]
can you post the steps that solved it?

> closed, thanks for helping me on Telegram

**Comment by Congee** [comment]
copy `https://github.com/waydroid/waydroid/blob/lineage-17.1/gbinder/anbox.conf` to `/etc/gbinder.d/`
