### ISSUE TITLE
Can Waydroid run in a virtual machine?

### ISSUE THREAD

**Issue by 07416** [waydroid/waydroid#310]
I haven't found information regarding VM-support in Waydroid, but there's at least a related [Github pull request][1]. I don't currently run Ubuntu or any of its derivatives on my main machine and I'm using AMD hardware.

I have [installed Waydroid][2] on Ubuntu 21.10 (Impish Indri) and  20.04 (Focal Fossa) in Oracle Virtualbox, but Android apps don't launch and no error messages are printed to the terminal — I'll create a dedicated issue if VMs are within the scope.

  [1]: https://github.com/waydroid/waydroid/pull/242
  [2]: https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-based-install-instructions

**Comment by hackel** [comment]
Seeing the same on the latest (14 Feb) release of Waydroid-linux.  I installed it in a Virtualbox VM.  I've tried running Waydroid under the default "Ubuntu" session, Waydroid on Mutter, and Weston, and on all of them, the Waydroid session appears to run, but Win+Tab does nothing, and I have yet to see an actual Android app.  I can see them running in the processlist.  I suspect this has to do with the graphics subsystem inside the VM not emulating Intel.  I haven't figured out how to switch to software rendering yet.

```
hackel@waydroid-virtualbox:~$ waydroid session start
[10:21:10] Failed to start Clipboard manager service, check logs
[gbinder] Service manager /dev/anbox-binder has appeared
[10:21:47] Android with user 0 is ready
```
And in `waydroid log` I see:
```
lxc-start: waydroid: utils.c: safe_mount: 1198 No such file or directory - Failed to mount "/dev/video1" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/video1"
lxc-start: waydroid: utils.c: safe_mount: 1198 No such file or directory - Failed to mount "/dev/video0" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/video0"
```

**Comment by 07416** [comment]
> I followed the instructions here and now it is working.
> https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

Great — I was able to launch both Newpipe and F-Droid after editing the config file, but with heavy rendering glitches and the apps crashed soon after.

AMD's integrated graphics.

**Comment by ikosp** [comment]
I edited waydroid_base.prop in Vmware player, android started, but immediately the whole system crashed.
The graphics card is nvidia quadro

**Comment by calvinweb** [comment]
Why no run android x86 driectly?

**Comment by Quackdoc** [comment]
it's worth noting that on qemu virgl works with waydroid.

**Comment by Quackdoc** [comment]
> I edited waydroid_base.prop in Vmware player, android started, but immediately the whole system crashed. The graphics card is nvidia quadro

using those instructions provided in the faq you will be using software rendering. if you followed those and you are still having issues it is probably worth creating a different issue

**Comment by aleasto** [comment]
> Can Waydroid run in a virtual machine?

Yes but you need to disable graphics hw acceleration: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

**Comment by wuyue92tree** [comment]
> > Can Waydroid run in a virtual machine?
> 
> Yes but you need to disable graphics hw acceleration: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

I did this, but still not work.

**Comment by tom-snow** [comment]
> I did this, but still not work. Any config wrong? ![image](https://user-images.githubusercontent.com/7899044/217990551-7a060aa0-7d1f-44ae-bda4-134fbccc000c.png)


You should start a wayland socket first. (You can using `weston`)
If you running on a VPS you can [run weston with rdp backend](https://manpages.ubuntu.com/manpages/jammy/en/man7/weston-rdp.7.html).
