### ISSUE TITLE
Unable to access matrix group

### ISSUE THREAD

**Issue by audricschiltknecht** [waydroid/waydroid#311]
I know this is not the proper place but this is the only way to contact the devs :)

It seems there is an issue with the matrix server.
When I try to join the group with Element I get an error message:

```
#waydroid:connolly.tech is not accessible at this time.

Try again later, or ask a room admin to check if you have access.
```

Furthermore, using the Matrix Federation Tester tool at https://federationtester.matrix.org/#connolly.tech returns:

```
Got 0 connection report. This usually means at least one error happened.
Connection Errors
Get "https://51.195.201.165:8448/_matrix/key/v2/server": dial tcp 51.195.201.165:8448: connect: connection refused

DNS results

No SRV records found

Hosts
connolly.tech

Addresses
51.195.201.165
```

**Comment by cniw** [comment]
here is the new matrix room's join link https://matrix.to/#/#waydroid:mrcyjanek.net

**Comment by AAGaming00** [comment]
This is now also down.
