### ISSUE TITLE
How to invoke an app directly with weston without full GUI or manually entering commands in terminal?

### ISSUE THREAD

**Issue by bornagainpenguin** [waydroid/waydroid#315]
I run Ubuntu-Mate so we use xorg still because Wayland is not yet fully supported on the desktop yet.  I have wanted for a while now to try Waydroid after being disappointed by the way AnBox seems to have been abandoned but since my desktop did not work with Wayland I thought it was not possible for me to do so.  It was only recently that someone mentioned it was possible to get Wayland to nest under xorg with Weston.

I have succeeded in getting the full gui running within the weston window by enter commends in the terminal.

What I am asking is if there is a way to create a command I can use in my app menu to launch Android apps directly without the full GUI of Android showing up?  Is it truly necessary to manually enter commands to open Weston and then again enter commands in the Weston instance to load the full Android GUI before launching an app?

Thanks for your time and the work you've done.

**Comment by electrikjesus** [comment]
All in the documentation my friend, you want the "waydroid app launch <appname> " command: 
https://docs.waydro.id/usage/install-and-run-android-applications

**Comment by bornagainpenguin** [comment]
> We can update that doc to better present the options

That would be appreciated because I can see nothing that invokes weston to show those apps.  Those directions assume that wayland is being used.

**Comment by Etaash-mathamsetty** [comment]
just run weston
open terminal in weston
type commands
and you are done

**Comment by bornagainpenguin** [comment]
So what I am reading here is that it is in fact not possible to create a shortcut to launch the application directly with weston and without having everything load in a system image.  You must open the apps from within weston after manually loading it and then inputting commands in the terminal.

Fair enough.  Perhaps I will try again when the Mate desktop is fully Wayland compatible.

**Comment by electrikjesus** [comment]
This could be done through Weston's autolaunch:
https://man.archlinux.org/man/weston.ini.5.en

You will find it at the end, in config options

[autolaunch]
path=$EXEC_PATH
watch=true //will make Weston exit when the process finishes
