### ISSUE TITLE
ERROR: Binder node "vndbinder" for waydroid not found 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [waydroid/waydroid#316]
**Describe the bug**
I was trying to install waydroid on Kali (Gnome on Wayland) yet it returns this:

>└─# sudo waydroid init                     
> 
> [16:12:19] ERROR: Binder node "vndbinder" for waydroid not found
> [16:12:19] See also: <https://github.com/waydroid>
> Run 'waydroid log' for details.

**General information (please complete the following information):**
 - Waydroid tools Version [latest version]
 - Waydroid Images Version [latest version]

**Desktop (please complete the following information):**
 - OS: Kali
 - GPU: Intel HD 3000
 - Kernel version: 5.16.0-kali2-amd64

**Comment by MohammedMehdiTBER** [comment]
> You need to be including the binder and ashmem kernel configs in your kernel.

How can I do it practically?

**Comment by MohammedMehdiTBER** [comment]
Tried Anbox modules yet it shows this:

> └─# bash ./INSTALL.sh
> 
> Kernel preparation unnecessary for this kernel. Skipping...
> 
> Building module:
> cleaning build area...
> make -j4 KERNELRELEASE=5.16.0-kali2-amd64 all KERNEL_SRC=/lib/modules/5.16.0-kali2-amd64/build...(bad exit status: 2)
> Error! Bad return status for module build on kernel: 5.16.0-kali2-amd64 (x86_64)
> Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.
> 
> Kernel preparation unnecessary for this kernel. Skipping...
> 
> Building module:
> cleaning build area...
> make -j4 KERNELRELEASE=5.16.0-kali2-amd64 all KERNEL_SRC=/lib/modules/5.16.0-kali2-amd64/build...(bad exit status: 2)
> Error! Bad return status for module build on kernel: 5.16.0-kali2-amd64 (x86_64)
> Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
> binder_linux          225280  0
> ashmem_linux           20480  0
> crwxrwxrwx 1 root root 10, 125 Feb 24 20:50 /dev/ashmem
> crwxrwxrwx 1 root root 10, 124 Feb 24 20:50 /dev/binder
>

**Comment by VictorTagayun** [comment]
> Did you try to run : sudo waydroid init -f

same problem as this:

`[16:12:19] ERROR: Binder node "vndbinder" for waydroid not found`
`[16:12:19] See also: https://github.com/waydroid`

**Comment by afzl-wtu** [comment]
> > Did you try to run : sudo waydroid init -f
> 
> same problem as this:
> 
> `[16:12:19] ERROR: Binder node "vndbinder" for waydroid not found` `[16:12:19] See also: https://github.com/waydroid`
> 
> I am running in VM by the way. I am using Q4OS on bullseye.

I am not sure why are you using vm? If you want to use vm. Diresctly use any emulator

**Comment by VictorTagayun** [comment]
Some personal reasons.
I want something I can hide and delete easily.

**Comment by aleasto** [comment]
You can follow these instructions for PopOS, they should behave the same: https://docs.waydro.id/usage/install-on-desktops#popos
