### ISSUE TITLE
debian sway init error

### ISSUE THREAD

**Issue by ati46** [waydroid/waydroid#32]
debian execute init after installation according to the document and report an error : ERROR:('Connection aborted.',ConnectionResetError(104,'Connection reset by peer'))
https://docs.waydro.id/usage/install-on-desktops

![image](https://user-images.githubusercontent.com/33859622/132453433-a3e05a25-b8b6-4cc2-b54b-1edd4a593d09.png)

**Comment by erfanoabdi** [comment]
`rm -rf /var/lib/waydroid`

**Comment by ati46** [comment]
> `rm -rf /var/lib/waydroid`

not work

![image](https://user-images.githubusercontent.com/33859622/132509014-971004fa-e96d-4e0f-919b-85f8a1aef1a0.png)

**Comment by ati46** [comment]
@erfanoabdi  Can you tell me the address of the resource I need to access? , Because the local network is stable.

**Comment by erfanoabdi** [comment]
download latest system image from: https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/
and vendor: https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/

extract both zips and place img files to: "/usr/share/waydroid-extra/images"
run `waydroid init -f`

**Comment by ati46** [comment]
@erfanoabdi  Still reporting an error, but no longer prompting network timeout

![image](https://user-images.githubusercontent.com/33859622/132648074-70d4eef3-6295-4ff4-8da3-8d76d7887534.png)

**Comment by ati46** [comment]
@erfanoabdi  Sorry, my fault. After I set up the proxy, the initialization can be completed normally. But when I start the session, I get an error failed to start clipboard manager service

![image](https://user-images.githubusercontent.com/33859622/132652894-3ec38224-b589-48d1-b497-4280640b29a5.png)

**Comment by erfanoabdi** [comment]
start session from your user, not root

for clipboard management you need to install pyclip from pip
and xclip from apt, but it's not hard dependency 
check `waydroid logcat` for errors

**Comment by ati46** [comment]
@erfanoabdi  After installing clip, it works, but it gets stuck after executing waydroid session start.
After sudo waydroid logcat, enter the log information in a loop

![image](https://user-images.githubusercontent.com/33859622/132819715-f8b882a2-0b8b-4a8b-bc06-aa0f7efd32ca.png)

![image](https://user-images.githubusercontent.com/33859622/132819727-ed7e40a5-43c1-4a26-b217-8156aff7eda6.png)

![image](https://user-images.githubusercontent.com/33859622/132819744-ea49ddd4-02ed-4e33-962a-c236a18e2e58.png)

**Comment by atmouse-** [comment]
waydroid currently unable perform well on swaywm, you could try run another wayland composer inside sway, which [wayfire](https://github.com/WayfireWM/wayfire) is a good choice.


1. start `wayfire` on swaywm
2. check that wayland-2 (WAYLAND_DISPLAY) exist in /run/user/1000/

then
```
% export WAYLAND_DISPLAY=wayland-2
% python waydroid.py session start
```

Maybe you would like GNOME desktop which official supported. I mean, waydroid :kissing:

**Comment by ati46** [comment]
@atmouse-  I tried to run `waydroid session start` under gnome. The same error

**Comment by nergzd723** [comment]
I wonder, how comes Waydroid works on Phosh but doesn't work on Sway? The same thing happened to me, and my point is that both Sway and Phosh use wlroots as the core library, I'd expect it to work totally fine.

**Comment by atmouse-** [comment]
> @atmouse- I tried to run `waydroid session start` under gnome. The same error

Please check that there's NO selinux or apparmor enabled

**Comment by ati46** [comment]
@atmouse-  I don't know how to confirm apparmor. But selinux does not.
![image](https://user-images.githubusercontent.com/33859622/133380563-3d3f59ce-603c-423f-a998-36ea424906a1.png)

**Comment by atmouse-** [comment]
disable apparmor from [here](https://wiki.debian.org/AppArmor/HowToUse)

**Comment by atmouse-** [comment]
finally waydroid works on sway, by [falling back to wl_shell](https://github.com/waydroid/android_hardware_waydroid/commit/08428931b99c02492538930ff3a9c5d4a9669011) tho

**Comment by MatthiasGrandl** [comment]
@atmouse- how do I get this fallback? I don't understand how those repos are related and it doesn't seem like the fallback is included in the current AUR version.

**Comment by atmouse-** [comment]
> @atmouse- how do I get this fallback? I don't understand how those repos are related and it doesn't seem like the fallback is included in the current AUR version.

it committed 2 days ago, u could waiting the next OTA image building include it

**Comment by ati46** [comment]
@erfanoabdi   After reinstalling the system and using the latest img file, I still prompt ERROR: <urlopen error [Errno 104] Connection reset by peer> when I run init

![image](https://user-images.githubusercontent.com/33859622/134793281-c4d24f3d-7d00-4ec0-84ef-a39aaed13af1.png)

**Comment by ati46** [comment]
Does this question have something to do with the region where I live, I am in China, but I have turned on the proxy, and there is no problem with accessing Google, etc.? Is there a way to mount the resources locally, and load the resources locally during waydroid init?

**Comment by qwerzl** [comment]
> Does this question have something to do with the region where I live, I am in China, but I have turned on the proxy, and there is no problem with accessing Google, etc.? Is there a way to mount the resources locally, and load the resources locally during waydroid init?

Did you set the HTTPS_PROXY env variable? Also, you should use sudo -E to pass the variable to root.

**Comment by 3498972895** [comment]
I also have this problems, but i found that i open my proxy net software and make the tun mode open, then everything works fine. err104 disapper
