### ISSUE TITLE
please fix colour graphics in waydroid

### ISSUE THREAD

**Issue by apy7hst** [waydroid/waydroid#322]
Hi, I am new to waydroid. After setting up waydroid and installing google play store, the colour is appearing totally in wrong form. here is the screenshot:-
![Screenshot from 2022-03-10 20-16-54](https://user-images.githubusercontent.com/101340385/157686650-bca3e21a-4d4e-4e08-85fe-83eb82891f3a.png)
desktop: ubuntu 20.04
cpu: intel

**Comment by apy7hst** [comment]
thanks for pointing out correctly

**Comment by apy7hst** [comment]
Thanks for pointing out to this previous issue, but there are multiple libmutter and mutter packages in the waydroid repo and I do not know which is the correct one.

**Comment by ACR-Jeff** [comment]
> Thanks for pointing out to this previous issue, but there are multiple libmutter and mutter packages in the waydroid repo and I do not know which is the correct one.

Did you ever get this resolved? I am having the same issue, The instructions are not clear on how to resolve this.

**Comment by amkstone** [comment]
run this in the terminal
`waydroid prop set persist.waydroid.multi_windows false
waydroid prop set persist.waydroid.invert_colors true`

Note that with this option enabled, you can not use this in combination with multi-window mode

Source `https://docs.waydro.id/faq/color-correction-in-mutter`

**Comment by 995qa** [comment]
I had this same problem today, and i had to turn on color inversion in the accesibility settings.

**Comment by ruthan** [comment]
I still have this issue on Intel 530, Mint 22 cinnamon wayland. Commands above not helped, maybe more commands needed.
