### ISSUE TITLE
Add chrome os theme for play store

### ISSUE THREAD

**Issue by apy7hst** [waydroid/waydroid#326]
I liked the chrome os theme made for ubuntu 20.04 in gtk. Here is the repository for the source code of the theme :- https://github.com/vinceliuice/ChromeOS-theme. It we would be great if it was added for the play store like chrome OS.

**Comment by mizzunet** [comment]
What?

**Comment by apy7hst** [comment]
chrome os theme bar for waydroid in linux

**Comment by electrikjesus** [comment]
It's already included in the Ubuntu 21.10 and Debian bookworm versions of our iso
