### ISSUE TITLE
Built-in browser app's webview process crashes soon after launching on 20220316 image

### ISSUE THREAD

**Issue by vroad** [waydroid/waydroid#328]
**Describe the bug**
Browser app always get stuck at loading. I can still type URL in address bar, or get search keyword suggestions. Checking the log, I found that webview process was crashing with fatal error: `F webview_zygote: runtime.cc:630] Runtime aborting...`

The browser worked fine when I tried out waydroid on Ubuntu running on VMware one month ago or so, not sure what's causing the issue. Kernel? Waydroid images?

~~I don't know how to switch to older images.~~ I was able to use older image simply by extracting 20211021 zip files to `/var/lib/waydroid/images/`. Browser no longer crashes after switching to old image, so the issue is specific to the newest image.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version: 1.2.0
 - Waydroid Images Version: lineage-17.1-20220316-VANILLA-waydroid_x86_64

**Desktop (please complete the following information):**
Huawei Matebook E (core m3 7Y30 model)
 - OS: Ubuntu 20.04 x64
 - GPU: Intel HD Graphics 615
 - Kernel version: `5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Host mesa version: Mesa 21.2.6
 - Desktop: Gnome 3.36.8

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`: 
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services: 
https://gist.github.com/vroad/df6082541bc7e2c7b1aa8629f1b25994

**Comment by vroad** [comment]
A user on telegram told me that running `chmod 0755 /sys/kernel/debug/tracing` fixes the problem. It indeed fixed the problem, but I don't know why it works and why it's required.

https://github.com/waydroid/android_vendor_waydroid/blob/1de566fd61487ad7245240d2cfa0a11b525bec40/rootdir/etc/init.waydroid.rc#L4

**Comment by aleasto** [comment]
Cannot reproduce. Please reopen if still relevant
