### ISSUE TITLE
No way to un-maximize free form windows when launching from .desktop

### ISSUE THREAD

**Issue by vega-d** [waydroid/waydroid#33]
When I have a window in free form launched from .desktop and I click maximize it opens full screen, but there's no way to un-maximize it. To get it back to free form I have to launch full ui from the terminal, click recents and select free form from there.

Maybe have header with navigation buttons on the top of free form windows remain when in full screen so there's a button to unmaximize/close?

**Comment by erfanoabdi** [comment]
multi-win is on experimental stage
