### ISSUE TITLE
Need Help, can't get waydroid working with WSL2

### ISSUE THREAD

**Issue by briantho** [waydroid/waydroid#332]
**Describe the bug**
Not sure if this supported, or I'm doing something wrong. I'm trying to run waydroid on top of ubuntu for windows (via WSL2)
I've installed waydroid, but when running waydroid init I get errors. Is WSL2 not supported or something, or am i doing something wrong? here is the output when running "sudo waydroid init"

`[14:44:54] Failed to load binder driver
[14:44:54] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
[14:44:54] ERROR: Binder node "binder" for waydroid not found
[14:44:54] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.        `

**Screenshots**

**General information (please complete the following information):**
 - Waydroid 1.20
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 x64 running on WSL2
 - GPU: Nvidia RTX 2080, CPU i9 9900k 
 - Kernel version: 5.10.60.1-microsoft-standard-WSL2
 - Host mesa version: Mesa 21.2.6
 - Desktop: Headless I guess, as it's wsl2

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
`(001291) [18:49:32] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(001291) [18:49:32] Failed to load binder driver
(001291) [18:49:32] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(001291) [18:49:32] ERROR: Binder node "binder" for waydroid not found
(001291) [18:49:32] See also: <https://github.com/waydroid>
(001291) [18:49:32] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(001653) [18:55:03] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(001653) [18:55:03] Failed to load binder driver
(001653) [18:55:03] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(001653) [18:55:03] ERROR: Binder node "binder" for waydroid not found
(001653) [18:55:03] See also: <https://github.com/waydroid>
(001653) [18:55:03] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(001656) [18:55:12] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(001656) [18:55:12] *** output passed to waydroid stdout, not to this log ***
(000071) [14:44:54] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(000071) [14:44:54] Failed to load binder driver
(000071) [14:44:54] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
(000071) [14:44:54] ERROR: Binder node "binder" for waydroid not found
(000071) [14:44:54] See also: <https://github.com/waydroid>
(000071) [14:44:54] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(000096) [15:14:02] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(000096) [15:14:02] *** output passed to waydroid stdout, not to this log ***
`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

**Comment by voltrare** [comment]
you need to compile kernel for ashmem and binder
see:-
https://github.com/waydroid/waydroid/issues/217
https://www.reddit.com/r/bashonubuntuonwindows/comments/eofn5s/run_anbox_on_wsl_2/
