### ISSUE TITLE
RDNA2 GPU Acceleration

### ISSUE THREAD

**Issue by Essasetic** [waydroid/waydroid#333]
**Is your feature request related to a problem? Please describe.**
If I try to use my GPU (RX 6800) on Waydroid. It will not boot (gets stuck on Starting waydroid with "waydroid show-full-ui")

**Describe the solution you'd like**
I would like there to be GPU acceleration support for RDNA2 GPUs like there is for Polaris and other GPUs like it.

**Describe alternatives you've considered**
I have used software acceleration, it's surprisingly okay. But it's not good enough if I want to use it to play games.

**Additional context**
Mostly just want it as a way to play games with anti-cheat embedded into it as some haven't/have refused to support Linux natively.

**Comment by sergiorgb** [comment]
This seems to be a issue related to Mesa version in the waydroid image not being new enough.
Initial Support for RDNA2 was released in mesa 20.2

**Comment by rothn** [comment]
Consider building from the latest sources: [guide](https://docs.google.com/document/d/1Sly_VH3w6wFIdE72WXijQegoHZh8IxEnJ9m0hH7GodU/edit#) (crossposting for visibility)

**Comment by aleasto** [comment]
Waydroid now uses the latest mesa
