### ISSUE TITLE
[gbinder] ERROR: Can't open /dev/binder: No such file or directory

### ISSUE THREAD

**Issue by gattolfo98** [waydroid/waydroid#336]
Hi when i execute waydroid session start, the output is:

[09:42:35] Failed to start Clipboard manager service, check logs
[gbinder] ERROR: Can't open /dev/binder: No such file or directory
[09:42:35] Failed to add presence handler: None

the first time i execute waydroid actually work, but after a reboot now is broken 

waydroid version: 1.2.0

my pc:
Pop Os 21.04
Mesa Intel® UHD Graphics (TGL GT2)
5.15.30-xanmod1
Mesa 21.2.2
[Log.txt](https://github.com/waydroid/waydroid/files/8331425/Log.txt)

**Comment by mizzunet** [comment]
Does your kernel have `binderfs` and `ashmen` modules?

Check whether they have been loaded `lsmod` 
or load it manually `modprobe`

**Comment by gattolfo98** [comment]
> Il tuo kernel ha `binderfs`e `ashmen`moduli?
> 
> Controlla se sono stati caricati `lsmod` o caricalo manualmente`modprobe`

I tried to reinstall waydroid, and now work!
