### ISSUE TITLE
ModuleNotFoundError: No module named 'gbinder'

### ISSUE THREAD

**Issue by fcat97** [waydroid/waydroid#344]
Waydroid on Manjaro giving this error:

```bash
$ waydroid init -f

Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 9, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 7, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'
```

**Comment by cniw** [comment]
If waydroid was works before but now this is happen maybe because python update on your system eg. update from 3.9 to 3.10 so you must to rebuild the module
Reinstal the gbinder python module from [AUR](https://aur.archlinux.org/packages/python-gbinder) `yay -S python-gbinder`

Not related but here you should run `waydroid init` command with `sudo`, `sudo waydroid init -f`

**Comment by ayasa520** [comment]
I use pyenv to manage Python versions, so I need to create symlinks.
`ln -s /usr/lib/python3.10/site-packages/*  /home/rikka/.pyenv/versions/3.10.6/lib/python3.10/site-packages`

**Comment by rguptasingh** [comment]
hey unfortunately this didn't work out for me, any ideas?

**Comment by cniw** [comment]
> hey unfortunately this didn't work out for me, any ideas?

which is you mean of "this"?
please describe what you did more details
what is your distro?

**Comment by rguptasingh** [comment]
Hey! So I am using Linux arch. I executed the yay command to to rebuild the module. However, waydroid is still not starting and I am getting this error message: [rgupta@rahul-desktop python-gbinder]$ waydroid show-full-ui
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'

**Comment by cniw** [comment]
here mine after update, all are 3.11
```bash
❯ python --version
Python 3.11.3
❯ pacman -Ql python-gbinder
python-gbinder /usr/
python-gbinder /usr/lib/
python-gbinder /usr/lib/python3.11/
python-gbinder /usr/lib/python3.11/site-packages/
python-gbinder /usr/lib/python3.11/site-packages/gbinder.cpython-311-x86_64-linux-gnu.so
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/PKG-INFO
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/SOURCES.txt
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/dependency_links.txt
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/top_level.txt
```

@rguptasingh can you check yours

**Comment by rguptasingh** [comment]
hey, sorry I am quite new to linux:
![image](https://user-images.githubusercontent.com/113334333/236682349-3b66bafd-bbc3-4e5f-acb7-9163d7ad39aa.png)

**Comment by cniw** [comment]
@rguptasingh it's mean you didn't update it yet, try again `yay -S python-gbinder --rebuild`

**Comment by rguptasingh** [comment]
> yay -S python-gbinder --rebuild

hey just ran the command somehow it doesn't seem to work: 
![image](https://user-images.githubusercontent.com/113334333/236682759-b2804ef9-d28c-4fb2-9516-a34970a8054c.png)

**Comment by cniw** [comment]
@rguptasingh did the building package process success? i can't see it from your screenshot, you can share your full process logs as a text

btw do you use unofficial repo like chaotic-aur?
and do you have pyenv setup enabled?

**Comment by rguptasingh** [comment]
> 

Hey I am sorry it seems like I am just an idiot. I just pressed enter without typing in A to cleanbuild all packages instead of just none which is the default value. It works perfectly fine now. Thank you for the quick reply.

**Comment by cniw** [comment]
> It works perfectly fine now. Thank you for the quick reply.

@rguptasingh nice to see it's works for you too

> I just pressed enter without typing in A to cleanbuild all packages instead of just none which is the default value.

i update the command a bit for it
`yay -S python-gbinder --answerclean All --answerdiff None --asdeps --aur --rebuild`
