### ISSUE TITLE
waydroid starting container problem

### ISSUE THREAD

**Issue by Sehrail** [waydroid/waydroid#345]
**Describe the bug**
Hi, ı have a problem running `waydroid` on `fedora 35`. When I start waydroid everything works until I run waydroid session start when I do this the waydroid container crashes and closes after 10 seconds.

**Logs (please upload as file)**
`/usr/lib/waydroid/data/scripts/waydroid-net.sh: satır 187: dnsmasq: komut yok
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(005612) [14:23:05] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005612) [14:23:05] % umount /var/lib/waydroid/rootfs/vendor
(005612) [14:23:05] % umount /var/lib/waydroid/rootfs
(005612) [14:23:05] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(005612) [14:23:05] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(005612) [14:23:05] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(005612) [14:23:05] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(005612) [14:23:05] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005612) [14:23:05] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(005612) [14:23:05] % chmod 777 -R /dev/ashmem
(005612) [14:23:05] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(005612) [14:23:05] % chmod 777 -R /dev/dri
(005612) [14:23:05] % chmod 777 -R /dev/fb0
(005612) [14:23:05] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(005612) [14:23:05] New background process: pid=5710, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethmnhZ6U" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(005612) [14:23:06] waiting 10 seconds for container to start...
(005612) [14:23:07] waiting 9 seconds for container to start...
(005612) [14:23:08] waiting 8 seconds for container to start...
(005612) [14:23:09] waiting 7 seconds for container to start...
(005612) [14:23:10] waiting 6 seconds for container to start...
(005612) [14:23:11] waiting 5 seconds for container to start...
(005612) [14:23:12] waiting 4 seconds for container to start...
(005612) [14:23:13] waiting 3 seconds for container to start...
(005612) [14:23:14] waiting 2 seconds for container to start...
(005612) [14:23:15] waiting 1 seconds for container to start...
(005612) [14:23:16] ERROR: container failed to start
(005612) [14:23:16] See also: <https://github.com/waydroid>
(005612) [14:23:16] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start`

**Comment by skeydan** [comment]
This looks like it's the same as what's described in #346

**Comment by aleasto** [comment]
Cannot reproduce on fedora.
If you are using a custom kernel, report the issue with the people providing you such
