### ISSUE TITLE
Failed to get service waydroidplatform, trying again...

### ISSUE THREAD

**Issue by androidu93** [waydroid/waydroid#347]
Hello,

When i try to launch waydroid, this message appears

`Failed to get service waydroidplatform, trying again...`

Thanks. (sorry if i have a bad english)

**Comment by lucasew** [comment]
Duplicate of #282

**Comment by Luciogi** [comment]
Run commands in sequence
`waydroid session start`
`sudo waydroid container start`
`waydroid show-full-ui` here you have to wait for a little while you might see `Failed to get service waydroidplatform, trying again...` it should start waydroid UI

**Comment by lucasew** [comment]
Extra note: If you are using a DE/WM that is based on Xorg instead of wayland then use weston

But before running the commands run `export XDG_SESSION_TYPE=wayland`

**Comment by slondr** [comment]
@Luciogi's solution (to just wait) doesn't seem to be working on my machine, unless I should be waiting more than a few hours :D

**Comment by Luciogi** [comment]
Sorry I cant help anymore with this problem

**Comment by aleasto** [comment]
Missing any information

**Comment by Luciogi** [comment]
https://github.com/waydroid/waydroid/issues/427#issuecomment-1185745452
try this
