### ISSUE TITLE
Key presses and touches get stuck after switching apps with Alt + Tab (or with GNOME's 3 finger gesture)

### ISSUE THREAD

**Issue by vroad** [waydroid/waydroid#350]
**Describe the bug**
Wayland does not cancel key presses / touches when user switches to apps other than Waydroid, causing key presses and touches to be stuck.
Wayland fires events for those situations, waydroid just need to handle them properly, I guess.

https://github.com/waydroid/android_hardware_waydroid/blob/bc85e3c88798f6bbecc8fef0fc4d9370f679d83f/hwcomposer/wayland-hwc.cpp#L547-L548
https://github.com/waydroid/android_hardware_waydroid/blob/bc85e3c88798f6bbecc8fef0fc4d9370f679d83f/hwcomposer/wayland-hwc.cpp#L891-L894

SDL, for example, releases all key presses when it receive wayland's keyboard leave event.

https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/src/video/wayland/SDL_waylandevents.c#L892-L893
https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/src/events/SDL_keyboard.c#L623

For touch gesture, there is cancellation event (but SDL doesn't seem to handle that):
https://wayland-book.com/seat/touch.html#gesture-cancellation

**Screenshots**
Enabling "Show taps" options reveals that touches get stuck after switching apps with GNOME's 3-finger gesture.
![-6181411868816552456_121](https://user-images.githubusercontent.com/396351/161938847-960eebd8-5e4a-41d1-a449-7828fd647533.jpg)

**General information (please complete the following information):**
 - Waydroid tools Version: c2c1ccb39c313e3689735f7c725f28b9f22d0154
 - Waydroid Images Version: Still reproducible with new image I manually built with robotnix: https://github.com/vroad/robotnix/tree/8f1f6515de72927b05ebe1f46085de5bfeab37c2

**Desktop (please complete the following information):**
Not relevant? For touches I confirmed the issue with [Huawei Matebook E (2017)](https://github.com/waydroid/waydroid/issues/330#issue-1174586827).
Key presses got stuck on both laptop (Dell G5 15 5590) and Matebook E.
 - OS: NixOS 21.11
 - GPU: Intel UHD Graphics 630
 - Kernel version: 5.10.109
 - Host mesa version: 21.2.6
 - Desktop: 41.1

**Additional context**

**Logs (please upload as file)**
Not relevant?

**Comment by aleasto** [comment]
Thank you for the contribution.
This is now fixed... by you :)
