### ISSUE TITLE
Waydroid display corrupted

### ISSUE THREAD

**Issue by ddams2000** [waydroid/waydroid#356]
**Describe the bug**
the waydroid display is completely corrupted, works with software rendering.

**screenshot**
![cdab8a4fb4342f7963e40a1315ceb13e1d0eaecd](https://user-images.githubusercontent.com/101818343/162610932-fe1145e0-27a3-4701-a7ba-9a293c3f167e.jpeg)

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.0-2
 - Waydroid Images Version 17.1

**Desktop (please complete the following information):**
 - OS: manjaro kde arm
 - GPU: Mali G52 Panfrost
 - Kernel version: mainline 5.17.1-4
 - Host mesa version: mesa 22.0.1
 - Desktop: Kde plasma 5.24.4

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of waydroid logcat :
[logcat.txt](https://github.com/waydroid/waydroid/files/8459240/logcat.txt)

**Comment by marschr** [comment]
I'm having the exact same issue when trying to run waydroid on my Khadas VIM3, which board you're on? Also, software rendering with swiftshader runs fine (laggy as usual).
Could it be related to missing Mali Panfrost drivers on Android?

**Comment by ddams2000** [comment]
I'm on a ugoos-am6b-plus (S922xj) box with manjaro kde
I don't know where the problem comes from, I would say mesa or panfrost, I tried with mesa-git 22.1, same thing.
sad :(

**Comment by aleasto** [comment]
This should be fixed in the latest android images
