### ISSUE TITLE
Failed to add service waydroidusermonitor: -1 // gbinder issue? // Ubuntu Touch Halium 9

### ISSUE THREAD

**Issue by luksus42** [waydroid/waydroid#358]
Hi, I am trying to troubleshoot this issue again and again over the past months...

**Describe the bug**
After starting waydroid by desktop-file (waydroid show-full-ui), it fails to create the waydroidusermonitor device.
Access to container shell is working.

The last five lines of waydroid log:
```(011656) [12:50:42] Save session config: /var/lib/waydroid/session.cfg
(011730) [12:50:43] Failed to start Clipboard manager service, check logs
(011730) [12:50:43] Failed to add service waydroidusermonitor: -1
(012336) [12:51:01] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(012336) [12:51:01] *** output passed to waydroid stdout, not to this log ***
```

**General information:**
Taken from waydroid.prop:
- waydroid.system_ota=http://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
- waydroid.vendor_ota=http://ota.waydro.id/vendor/waydroid_arm64/HALIUM_9.json
- waydroid.tools_version=1.2.0

**Smartphone/Tablet:**
 - Device: Lenovo Tab M10 X605L
 - OS: Ubuntu touch OTA22+ devel-channel
 - Halium 9
 - Kernel version: 3.18.120

**Additional context**
I ported UT to this device.
I got waydroid working once, then some time ago, something must have changed and it did never work again. Here is a screenshot from 12th September 2021:

![waydroid_x605](https://user-images.githubusercontent.com/6659488/162730073-61dc8212-7ed5-477f-b4cd-78d2083551e6.jpg)

I also tried it with old kernel builds, which where created around the time I made the screenshot, but nothing helps.

**Logs (please upload as file)**
[waydroid_base.txt](https://github.com/waydroid/waydroid/files/8463498/waydroid_base.txt)
[waydroid_log.log](https://github.com/waydroid/waydroid/files/8463511/waydroid_log.log)
[waydroid_shell_logcat.log](https://github.com/waydroid/waydroid/files/8463513/waydroid_shell_logcat.log)

**Comment by aleasto** [comment]
The logcat suggests you run `waydroid session start` or `waydroid show-full-ui` from ssh, so it's missing the WAYLAND_DISPLAY environment variable required to draw on the screen.
