### ISSUE TITLE
List `which` as required dependency

### ISSUE THREAD

**Issue by thigg** [waydroid/waydroid#359]
**Describe the bug**
At least the archlinux-arm packaging is missing `which` as a required dependency. 
The debian packaging looks like it has the same issue.
It might not be strictly needed because it is in most distros present. 

`data/scripts/waydroid-net.sh ` needs it. 

Additionally:

`waydroid-net.sh` fails silently without which right now. It would be good if it would cause an error when which is missing in the script and not fail silently.

**General information (please complete the following information):**
 - master branch, [AUR 1.2.0-2](https://aur.archlinux.org/packages/waydroid)

**Desktop (please complete the following information):**
 - OS: arch

**Smartphone (please complete the following information):**
 - Device: pinephone

**Comment by Quackdoc** [comment]
this should be added as a dependency in the PKGBUILD. 

@erfanoabdi I am unsure if any debian based distro would have an issue with this so im not sure it warrants an in-repo fix

**Comment by ammgws** [comment]
It seems like Debian-based distros may remove it some time in the near future: https://lwn.net/Articles/874049/

**Comment by GalaxySnail** [comment]
`which` can be replaced with `command -v`. Please see: https://hynek.me/til/which-not-posix/
