### ISSUE TITLE
Can’t open waydroid

### ISSUE THREAD

**Issue by Liwangxiaosuo** [waydroid/waydroid#362]
All my steps are fine, but when I finally click the waydroid icon, no screen pops up.
![图片](https://user-images.githubusercontent.com/94662442/164721955-048a7867-48b0-45c1-86f4-54ae988bc710.png)

**Comment by cniw** [comment]
```bash
echo "Session type: $XDG_SESSION_TYPE" > /tmp/info.txt
echo "Session desktop: $XDG_SESSION_DESKTOP" >> /tmp/info.txt
glxinfo | grep OpenGL.*string >> /tmp/info.txt
sudo rm /var/lib/waydroid/waydroid.log
sudo systemctl restart waydroid-container.service
```
Click the waydroid icon and wait 1-2 minutes
```bash
systemctl status waydroid-container.service > /tmp/waydroid-container_status.txt
cp /var/lib/waydroid/waydroid.log /tmp
sudo dmesg > /tmp/dmesg.log
```

Upload these files here
- /tmp/info.txt
- /tmp/waydroid-container_status.txt
- /tmp/waydroid.log
- /tmp/dmesg.log

**Comment by aleasto** [comment]
Stale, missing info
