### ISSUE TITLE
waydroid upgrade overwrites waydroid_base.prop

### ISSUE THREAD

**Issue by skeydan** [waydroid/waydroid#365]
`waydroid upgrade` overwrites user changes made to `waydroid_base.prop`.

Not totally sure this is a bug (instead of expected behavior) - opening just in case.

**Comment by aleasto** [comment]
This is intended.
User defined props should go to `/var/lib/waydroid/waydroid.cfg` in section `[properties]`. They will be included in `waydroid_base.prop` on re-init or upgrade.
