### ISSUE TITLE
Random crashes - surface 3 non pro

### ISSUE THREAD

**Issue by khariche** [waydroid/waydroid#366]
**Describe the bug**
Crashes occur randomly, when opening applications, trying to rename files or simply swiping up in home screen to open app drawer. The lineageos logo appears suddenly and android reboots, and after it has restarted, there is no internet connection (missing icon in system tray). Restarting the waydroid session from the linux terminal is required to regain connection.

**General information:**
 - Waydroid tools Version : 1.2.1
 - Waydroid Images Version : default current stable version from "waydroid init" (sorry, could not find the precise version)

**Desktop:**
 - OS: Manjaro 21.2.6 (happened also with ubuntu 21.10)
 - GPU: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 20)
 - Kernel version: 5.17.4-arch1-1-surface
 - Host mesa version: 21.3.8-1
 - Desktop: Sway (version downgraded for compatibility with wlroots <0.15) / KDE / Gnome / weston / mutter / wayfire)

**Additional context**
Surface 3 non pro (atom processor)

[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/8564642/waydroid_base.prop.txt)

[waydroid-logcat.pdf](https://github.com/waydroid/waydroid/files/8564896/waydroid-logcat.pdf)

output of "systemctl status waydroid-container":
waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; vendor preset: disab>
     Active: active (running) since Tue 2022-04-26 15:42:26 CEST; 2h 0min ago
   Main PID: 3263 (python3)
      Tasks: 2 (limit: 4589)
     Memory: 6.5M
        CPU: 6.205s
     CGroup: /system.slice/waydroid-container.service
             └─3263 python3 /usr/bin/waydroid container start

avril 26 17:24:30 user-surface3 dnsmasq-dhcp[3309]: DHCPACK(waydroid0) 192.168.250.112 00:16:3e:f9:d3:>
avril 26 17:26:17 user-surface3 dnsmasq-dhcp[3309]: DHCPDISCOVER(waydroid0) 00:16:3e:f9:d3:03
avril 26 17:26:17 user-surface3 dnsmasq-dhcp[3309]: DHCPOFFER(waydroid0) 192.168.250.112 00:16:3e:f9:d>
avril 26 17:26:17 user-surface3 dnsmasq-dhcp[3309]: DHCPREQUEST(waydroid0) 192.168.250.112 00:16:3e:f9>
avril 26 17:26:17 user-surface3 dnsmasq-dhcp[3309]: DHCPACK(waydroid0) 192.168.250.112 00:16:3e:f9:d3:>
avril 26 17:27:51 user-surface3 dnsmasq-dhcp[3309]: DHCPDISCOVER(waydroid0) 00:16:3e:f9:d3:03
avril 26 17:27:51 user-surface3 dnsmasq-dhcp[3309]: DHCPOFFER(waydroid0) 192.168.250.112 00:16:3e:f9:d>
avril 26 17:27:51 user-surface3 dnsmasq-dhcp[3309]: DHCPREQUEST(waydroid0) 192.168.250.112 00:16:3e:f9>
avril 26 17:27:51 user-surface3 dnsmasq-dhcp[3309]: DHCPACK(waydroid0) 192.168.250.112 00:16:3e:f9:d3:>
avril 26 17:28:16 user-surface3 waydroid[3263]: [17:28:16] session manager stopped, stopping container>

output of "waydroid log":
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:00] waydroidclipboard: Received transaction: 2
(003280) [16:20:01] waydroidclipboard: Received transaction: 2
(003280) [16:20:01] waydroidclipboard: Received transaction: 2
(003280) [17:28:16] Copy failed. wl-paste returned code: -2 Stderr: b'' Stdout: b''
(003263) [17:28:16] session manager stopped, stopping container and waiting...
(003263) [17:28:17] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(003263) [17:28:19] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
(003263) [17:28:19] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(003263) [17:28:19] % umount /var/lib/waydroid/rootfs/vendor
(003263) [17:28:19] % umount /var/lib/waydroid/rootfs
(003263) [17:28:19] % umount /var/lib/waydroid/data
(003263) [17:28:19] % chmod 666 -R /dev/anbox-binder
(003263) [17:28:19] % chmod 666 -R /dev/anbox-vndbinder
(003263) [17:28:19] % chmod 666 -R /dev/anbox-hwbinder
(003263) [17:28:19] Container manager is waiting for session to load
(121723) [17:44:13] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(121723) [17:44:13] *** output passed to waydroid stdout, not to this log ***
(121737) [17:44:35] Save session config: /var/lib/waydroid/session.cfg
(121737) [17:44:35] UserMonitor service is not even started
(121737) [17:44:35] Clipboard service is not even started
(003263) [17:44:36] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(003263) [17:44:36] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(003263) [17:44:36] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(003263) [17:44:36] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(003263) [17:44:36] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(003263) [17:44:36] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(003263) [17:44:36] % mount -o bind /home/user/.local/share/waydroid/data /var/lib/waydroid/data
(003263) [17:44:36] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(003263) [17:44:36] % chmod 777 -R /dev/ashmem
(003263) [17:44:36] % chmod 777 -R /dev/dri
(003263) [17:44:36] % chmod 777 -R /dev/fb0
(003263) [17:44:36] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(003263) [17:44:36] New background process: pid=121794, output=background
(003263) [17:44:37] Save session config: /var/lib/waydroid/session.cfg
(122126) [17:44:50] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(122126) [17:44:50] *** output passed to waydroid stdout, not to this log ***

Thank you for your kind help!

**Comment by aleasto** [comment]
"AndroidRuntime: android.view.Surface$OutOfResourcesException"

It appears that your device is out of memory...
