### ISSUE TITLE
Waydroid container fails to start Asahi Linux

### ISSUE THREAD

**Issue by Radiicall** [waydroid/waydroid#373]
**Describe the bug**
Waydroid container fails to start

**General information (please complete the following information):**
 - Waydroid tools Version [1.2.1]
 - Waydroid Images Version [aur/waydroid-image 17.1_20220316-2]

**Desktop (please complete the following information):**
 - OS: Asahi Linux ArchLinuxARM
 - GPU: No GPU support
 - Kernel version: 5.17.0-rc7-asahi-next-20220310-5-2-ARCH
 - Host mesa version: mesa-22.0.3-1
 - Desktop: Gnome 42.1

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.2.1
ro.vndk.lite=true
ro.product.waydroid.model=Apple MacBook Air (M1, 2020)

```
 - Output of `waydroid log`

```
(000424) [16:26:38] % chmod 666 -R /dev/anbox-hwbinder
(000424) [16:26:38] Container manager is waiting for session to load
(007602) [16:27:50] WayDroid container is STOPPED
(007709) [16:27:50] WayDroid session is not started
(000396) [16:28:06] % mkdir -p /dev/binderfs
(000396) [16:28:06] % mount -t binder binder /dev/binderfs
(000396) [16:28:06] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/binder /dev/binderfs/binder-control /dev/
ln: failed to create symbolic link '/dev/binder': File exists
(000396) [16:28:06] % chmod 666 -R /dev/binder
(000396) [16:28:06] % chmod 666 -R /dev/anbox-vndbinder
(000396) [16:28:06] % chmod 666 -R /dev/anbox-hwbinder
(000396) [16:28:06] Container manager is waiting for session to load
(001723) [16:28:35] Starting waydroid session
(001723) [16:28:35] Save session config: /var/lib/waydroid/session.cfg
(001723) [16:28:35] UserMonitor service is not even started
(001723) [16:28:35] Clipboard service is not even started
(000396) [16:28:36] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(000396) [16:28:36] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(000396) [16:28:36] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(000396) [16:28:36] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000396) [16:28:36] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000396) [16:28:36] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000396) [16:28:36] % mount -o bind /home/benja/.local/share/waydroid/data /var/lib/waydroid/data
(000396) [16:28:36] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(000396) [16:28:36] % chmod 777 -R /dev/ashmem
(000396) [16:28:36] % chmod 777 -R /dev/dri
(000396) [16:28:36] % chmod 777 -R /dev/fb0
(000396) [16:28:36] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000396) [16:28:36] New background process: pid=1786, output=background
(000396) [16:28:36] waiting 10 seconds for container to start...
CANNOT LINK EXECUTABLE "/init": can't enable GNU RELRO protection for "": Invalid argument
linker: CANNOT LINK EXECUTABLE "/init": can't enable GNU RELRO protection for "": Invalid argument

lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(000396) [16:28:37] waiting 9 seconds for container to start...
(000396) [16:28:38] waiting 8 seconds for container to start...
(000396) [16:28:39] waiting 7 seconds for container to start...
(000396) [16:28:40] waiting 6 seconds for container to start...
(000396) [16:28:41] waiting 5 seconds for container to start...
(000396) [16:28:42] waiting 4 seconds for container to start...
(000396) [16:28:43] waiting 3 seconds for container to start...
(000396) [16:28:44] waiting 2 seconds for container to start...
(000396) [16:28:45] waiting 1 seconds for container to start...
(000396) [16:28:46] ERROR: container failed to start
(000396) [16:28:46] See also: <https://github.com/waydroid>
(000396) [16:28:46] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

(001838) [16:28:46] UserMonitor service is not even started
(001838) [16:28:46] Clipboard service is not even started
(001723) [16:28:46] UserMonitor service is not even started
(001723) [16:28:46] Clipboard service is not even started
(001845) [16:29:06] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(001845) [16:29:06] *** output passed to waydroid stdout, not to this log ***
```
**Additional Info**
For binder and ashmem im using the anbox-modules-dkms-git package from the AUR

**Comment by zhuowei** [comment]
I ran into something similar as well, but in a VM (UTM/QEMU/Fedora 36)

The current system image has 32-bit support enabled (init.zygote64_32.rc), and the media drivers (e.g. /system/bin/mediadrmserver) are built as 32-bit.
So the system image can't boot on Apple Silicon, which has no 32-bit support.

**Comment by mio-19** [comment]
Related issue: #644

**Comment by oklopfer** [comment]
See here https://github.com/waydroid/waydroid/issues/692, as I solved the issue and have been building local arm64-only images for myself. If you want, I might be able to upload them to google drive.

**Comment by Radiicall** [comment]
@oklopfer I think making a PKGBUILD for the aur is the better option as asahi linux is arch based, im gonna look into how to build the image and then try to make a PKGBUILD from that.

**Comment by mio-19** [comment]
> @oklopfer I think making a PKGBUILD for the aur is the better option as asahi linux is arch based, im gonna look into how to build the image and then try to make a PKGBUILD from that.

It would be even greater if -bin package is available. Building android image is sometimes a pain

**Comment by Radiicall** [comment]
> > @oklopfer I think making a PKGBUILD for the aur is the better option as asahi linux is arch based, im gonna look into how to build the image and then try to make a PKGBUILD from that.
> 
> It would be even greater if -bin package is available. Building android image is sometimes a pain
I dont think any waydroid images on aur get built from source, its like 200gb of space needed

**Comment by oklopfer** [comment]
The packages waydroid-image and waydroid-image-gapps on the AUR are just AUR mirrors of the images being hosted on the Waydroid sourceforge. If you wanted to make an AUR package for it, then Waydroid would need upstream arm64-only builds. Until then, you'll have to build images downstream using the method + patches in the issue opened up by Jami that I linked. As it states there, one of the main things needed is a way to auto-parse from the device if it supports 32 bit binaries, so we can feed it arm64-only images automatically

**Comment by Radiicall** [comment]
I tried building this to no avail, i think the bigger issue is asahi being 16k and that's not possible for Waydroid to work around (correct me if im wrong)

**Comment by oklopfer** [comment]
As in you failed to build it? It has to be built on an x86_64 source, regardless if the deployment target is ARM.

**Comment by Radiicall** [comment]
> As in you failed to build it? It has to be built on an x86_64 source, regardless if the deployment target is ARM.


No no, i built it just fine but it doesnt run on a 16k kernel as far as i can see, i applied the lunch target and the patches. Tried multiple times, even tried compiling on arm even though it doesnt work.

**Comment by mio-19** [comment]
> 

A possible workaround is to install custom 4k page kernel.
I found a tutorial of that https://www.reddit.com/r/AsahiLinux/comments/tq575y/possibility_to_install_a_4k_kernel_on_arch/i7vjtja?utm_medium=android_app&utm_source=share&context=3

**Comment by oklopfer** [comment]
squash em together and see if it works!

**Comment by Radiicall** [comment]
> > 
> 
> 
> 
> A possible workaround is to install custom 4k page kernel.
> 
> I found a tutorial of that https://www.reddit.com/r/AsahiLinux/comments/tq575y/possibility_to_install_a_4k_kernel_on_arch/i7vjtja?utm_medium=android_app&utm_source=share&context=3

This would probably work but the performance penalty wouldnt really be worth it

**Comment by oklopfer** [comment]
Well then it's no longer a matter of if it works but if you personally believe it's worth it :)

**Comment by Radiicall** [comment]
Since this issue is not really "fixable" at the moment (because of the kernel) i will close it, thanks for all the help everyone.

**Comment by dharmtej-0206** [comment]
so can you we waydroid on asahil linux?

**Comment by supechicken** [comment]
See https://github.com/waydroid/waydroid/issues/2185#issuecomment-4373901742, someone got Waydroid working on Asahi
