### ISSUE TITLE
Native Window Decorations

### ISSUE THREAD

**Issue by daudix-UFO** [waydroid/waydroid#375]
Android windows looks out of place with it android window decorations

It would be cool to make waydroid multi-window mode use native window decorations

**Comment by imhemish** [comment]
Also, it is almost impossible to move windows on a touch screen when there are no window decorations

**Comment by 2zqa** [comment]
Currently, it seems a single big window is launched in which the app window is rendered. The size of this window is set with the `persist.waydroid.width` and `persist.waydroid.height` props. So adding native window decorations would require rethinking this approach as well.

Separate windows would improve:
- system integration (like moving/resizing with meta + left/right click, GNOME overview window not appearing excessively large)
- touch support like mentioned above
