### ISSUE TITLE
lineage-18.1 black screen

### ISSUE THREAD

**Issue by a5s4d56agw** [waydroid/waydroid#383]
**Describe the bug**
I get black screen from `waydroid show-full-ui`

**General information (please complete the following information):**
 - $ waydroid --version
1.2.1
 - Waydroid Images Version
 https://sourceforge.net/projects/blissos-dev/files/waydroid/lineage/lineage-18.1/

**Desktop (please complete the following information):**
 - OS: archlinux
 - GPU: amd a10 7890k
 - Kernel version: 5.17.5-zen1-1-zen
 - Host mesa version: 22.0.2
 - Desktop: xorg i3, waydroid ran through kwin_wayland

**Additional context**
vanilla images with libndk are able to open everything except one game called princess connect
so i wanted to try lineage-18.1 with libhoudini but when i run it i just get black screen.

**Logs (please upload as file)**
 - Prop file: [waydroid_base.txt](https://github.com/waydroid/waydroid/files/8694145/waydroid_base.txt)
 - Output of `waydroid log`: [waydroid_log.txt](https://github.com/waydroid/waydroid/files/8694160/waydroid_log.txt)
 - Output of `waydroid logcat`: [waydroid_logcat.txt](https://github.com/waydroid/waydroid/files/8694161/waydroid_logcat.txt)

some logs can have weird timestamps i believe its because i have 3 hour past bios time than linux time.

**Comment by a5s4d56agw** [comment]
i tried it with
kernel version: 5.17.7-zen1-1-zen
mesa version: 22.0.3

behaviour is same.

**Comment by a5s4d56agw** [comment]
found instructions at telegram for how to make it work.
i see visual glitches and game i want to open still doesnt open.

**Comment by lucas-04** [comment]
> 

What are these instructions?

**Comment by Vap0r1ze** [comment]
Please post the instructions
