### ISSUE TITLE
Add Waydroid multi-open container support

### ISSUE THREAD

**Issue by botao1995** [waydroid/waydroid#385]

**Comment by n1lby73** [comment]
> 

Do you mean multi window mode

**Comment by logan001** [comment]
so how do you open multiple instances of waydroid?

**Comment by assiless** [comment]
@botao1995
Why did you close this issue? Did you find the solution? So how?

I want to open at least two instances, one for the client and one for the server
Try an application on the client as well as on the server

waydroid multiple instances will help developer to learn, test, deploy with small overheads

**Comment by aleck099** [comment]
So how to start multiple waydroid sessions?

**Comment by TriMoon** [comment]
You can't...

**Comment by fir3-1ce** [comment]
why is this closed? you should be able to have multiple instances of Waydroid on the same system. It seems insecure, and a bit of a privacy concern to only have one instance allowed on your machine. 

Yes, I know you can just rename the folder, but there should at least be a script or an option in Waydroid Settings to switch between containers

**Comment by michaelCTS** [comment]
This would be a great feature to have. Like win with its multiple drives or docker with multiple containers.

**Comment by Benjamin-Loison** [comment]
@fir3-1ce May you precise what do you mean by *I know you can just rename the folder*? Even if I have to proceed manually or elaborate a script, I would love to have multiple system types on the same machine without additional tools like VirtualBox etc.
