### ISSUE TITLE
Waydroid refuses to install on Debian Sid because Python version is too new

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [waydroid/waydroid#386]
Waydroid depends on python3-gbinder, however, it refuses to install on Debian Sid because the Python version is newer than 3.10 (and it seems to be explicitly disallowed in python3-gbinder dependencies). Is there a way to install Waydroid on Debian Sid? Is it safe to install Waydroid and python3-gbinder anyway, or should I use things like systemd-nspawn to use an older version of Python?

**Comment by seltzered** [comment]
see https://github.com/waydroid/waydroid/issues/363

**Comment by ChrysoliteAzalea** [comment]
Thank you!
