### ISSUE TITLE
Pointer changes size after moving onto the waydroid system screen

### ISSUE THREAD

**Issue by apy7hst** [waydroid/waydroid#388]
While using the mouse pointer on the waydroid screen, the black mouse pointer becomes bigger in size. Please fix this issue.

**Comment by cniw** [comment]
Cursor size is depend on waydroid/android screen dpi setting, by add/apply custom `ro.sf.lcd_density` prop value lower than the default/decrease the dpi value it also affect decrease the cursor size.
You can use this website https://dpi.lv/ as reference or just set your custom dpi value, if i am don't wrong the default value is 160 (waydroid assume it use HVGA screen) even on my screen 1366x768.
```bash
echo "ro.sf.lcd_density=118" | sudo tee -a /var/lib/waydroid/waydroid_base.prop
```
Then restart waydroid.
