### ISSUE TITLE
Unity/Lomiri crashes if apps are removed from recents.

### ISSUE THREAD

**Issue by nitanmarcel** [waydroid/waydroid#39]
On Halium 10, ubports 10 there's a bug that makes every app I try to launch crash if anything related to the container is removed from the recents menu.

After than I have to restart the container else the android apps will crash right away after waydroid splashscreen.

Logcat: https://paste.ubuntu.com/p/qyt93my6c2/
Dmesg: https://paste.ubuntu.com/p/2rdvYkGgjx/

**Comment by erfanoabdi** [comment]
It's ubuntu touch bug
