### ISSUE TITLE
Set Android 11 as default image instead of 10

### ISSUE THREAD

**Issue by afzl-wtu** [waydroid/waydroid#390]
**Is your feature request related to a problem? Please describe.**

AFAIK Android 11 images have native arm translations. I do not know much about libndk and libhoudni (Better for android 11 and more stable).

**Describe the solution you'd like**

So it would be great if you set Android 11 as default image instead of wasting time on android 10 images.  I am running Android 11 image in waydroid but there is not GAPP support for it I can not install playstore in it. There is already some MicroG app and Aurora App Store in it.

**Comment by Thijmer** [comment]
I am also wondering why Waydroid is using a more than two years old Android version.

**Comment by xiliuya** [comment]
There is an Android 11 image on AUR, but if the graphics card does not support OpenGL es 3.1, it will not start AVD is the same. Android 11 cannot be used on old devices You can try using AVD's Android 11 GAPP emulator to create a dart image

**Comment by Aromate** [comment]
yes,i think should add the android 11 to test. Android 11 better than android 10.

**Comment by Quackdoc** [comment]
There are unofficial android 11 images, they are buggy, you can try them if you wish but don't expect support for them. more information can be found in the telegram/matrix group. 

android 11 will be ready when it's ready

**Comment by darkdragon-001** [comment]
LineageOS 19 (Android 12) is out already as well. Could someone create a test image as well? Could be that it even get's easier with Google's move to upstream first...

**Comment by vuongtuha** [comment]
I need image  of Lineage waydroid 12. Even beta or testing, just public it in a special box with warning. Not only me, many ppl wanna try newest when Gg almost release android 13 next month

**Comment by Weathercold** [comment]
Android 13 is out, LineageOS 20 will be out soon, and we are still on android 10. Any news?

**Comment by rothn** [comment]
Especially for those of use with the PinePhone Pro, the repo version with Android 11 already works way better out-of-the-box than the default Android 10 version due to kernel updates. I would suggest releasing.

**Comment by aleasto** [comment]
Android 11 based images were released today

**Comment by Weathercold** [comment]
Finally!!!

**Comment by steviator** [comment]
is there any way of downgrading back to Android 10, all versions after that cannot be locked in portrait mode, making about 50% of applications impossible to use in Waydroid rendering it basically useless.

**Comment by chriswyatt** [comment]
> is there any way of downgrading back to Android 10, all versions after that cannot be locked in portrait mode, making about 50% of applications impossible to use in Waydroid rendering it basically useless.

I have Android 11 running under Waydroid on an Ubuntu Touch device, and I was able to lock into both portrait and landscape mode. It doesn't seem like a feature they'd be likely to remove, so I suspect there's either a problem with your specific configuration, or it's user error.

I followed this guide here: https://www.wikihow.com/Switch-to-Portrait-or-Landscape-Mode-on-Android
