### ISSUE TITLE
can't start on OpenSUSE TW

### ISSUE THREAD

**Issue by Pshemas** [waydroid/waydroid#395]
I've tried to start it. Initially it didn't went well as I didn't have a clue I have to add psi=1 to kernel parameters.

Now ``` systemctl start waydroid-container``` works and systemctl status shows it's active.

But when I try to launch it with ``` waydroid show-full-ui ``` it stops after a couple of seconds.
When I look into the log I see this:

```
(008007) [22:03:56] Container manager is waiting for session to load
(011455) [22:06:40] Starting waydroid session
(011455) [22:06:40] Save session config: /var/lib/waydroid/session.cfg
(011455) [22:06:40] UserMonitor service is not even started
(011455) [22:06:40] Clipboard service is not even started
(008007) [22:06:40] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

dnsmasq: nie udało się otworzyć pliku z PID-em /run/waydroid-lxc/dnsmasq.pid: Brak dostępu
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(008007) [22:06:41] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(008007) [22:06:41] % umount /var/lib/waydroid/rootfs/vendor
(008007) [22:06:41] % umount /var/lib/waydroid/rootfs
(008007) [22:06:41] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(008007) [22:06:41] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(008007) [22:06:41] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(008007) [22:06:41] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(008007) [22:06:41] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(008007) [22:06:41] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: nie podano punktu montowania.
(008007) [22:06:41] % chmod 777 -R /dev/ashmem
(008007) [22:06:41] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(008007) [22:06:41] % chmod 777 -R /dev/dri
(008007) [22:06:41] % chmod 777 -R /dev/fb0
(008007) [22:06:41] % chmod 777 -R /dev/video0
(008007) [22:06:41] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(008007) [22:06:41] New background process: pid=11569, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 710 No such file or directory - Failed to attach "vethl3cbqf" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3413 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1843 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(008007) [22:06:41] waiting 10 seconds for container to start...
(008007) [22:06:42] waiting 9 seconds for container to start...
(008007) [22:06:43] waiting 8 seconds for container to start...
(008007) [22:06:44] waiting 7 seconds for container to start...
(008007) [22:06:45] waiting 6 seconds for container to start...
(008007) [22:06:46] waiting 5 seconds for container to start...
(008007) [22:06:47] waiting 4 seconds for container to start...
(008007) [22:06:48] waiting 3 seconds for container to start...
(008007) [22:06:49] waiting 2 seconds for container to start...
(008007) [22:06:50] waiting 1 seconds for container to start...
(008007) [22:06:51] ERROR: container failed to start
(008007) [22:06:51] See also: <https://github.com/waydroid>
(008007) [22:06:51] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

(011703) [22:06:51] UserMonitor service is not even started
(011703) [22:06:51] Clipboard service is not even started
(011455) [22:06:51] UserMonitor service is not even started
(011455) [22:06:51] Clipboard service is not even started
(011713) [22:07:01] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(011713) [22:07:01] *** output passed to waydroid stdout, not to this log ***
```

**Comment by 13werwolf13** [comment]
as I understand the waydroid for work you need ashmem. and he is no longer in the core after 5.18.

https://github.com/torvalds/linux/commit/721412ed3d819e767cac2b06646bf03aa158aaec

**Comment by Quackdoc** [comment]
if you were using it previous to the kernel upgrade you will need to either re-init waydroid or add `sys.use_memfd=true` to waydroid_base.prop. the location of which can be found in the docs. 

this looks like a different issue however i not sure if networking issues will cause this but if it is, you can see I have a fix here #267 which will allow users to set their own networking interface, as a testing measure can you edit this file `/usr/lib/waydroid/data/scripts/waydroid-net.sh` and add `exit` to the top of it and see if it works?

**Comment by DeadMozay** [comment]
> I've tried to start it. Initially it didn't went well as I didn't have a clue I have to add psi=1 to kernel parameters.
> 
> Now ` systemctl start waydroid-container` works and systemctl status shows it's active.
> 
> But when I try to launch it with `waydroid show-full-ui` it stops after a couple of seconds. When I look into the log I see this:
> 
> ```
> (008007) [22:03:56] Container manager is waiting for session to load
> (011455) [22:06:40] Starting waydroid session
> (011455) [22:06:40] Save session config: /var/lib/waydroid/session.cfg
> (011455) [22:06:40] UserMonitor service is not even started
> (011455) [22:06:40] Clipboard service is not even started
> (008007) [22:06:40] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
> 
> dnsmasq: nie udało się otworzyć pliku z PID-em /run/waydroid-lxc/dnsmasq.pid: Brak dostępu
> Failed to setup waydroid-net.
> Failed to setup waydroid-net.
> (008007) [22:06:41] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
> (008007) [22:06:41] % umount /var/lib/waydroid/rootfs/vendor
> (008007) [22:06:41] % umount /var/lib/waydroid/rootfs
> (008007) [22:06:41] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
> (008007) [22:06:41] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
> (008007) [22:06:41] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
> (008007) [22:06:41] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
> (008007) [22:06:41] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
> (008007) [22:06:41] % umount -l /sys/fs/cgroup/schedtune
> umount: /sys/fs/cgroup/schedtune: nie podano punktu montowania.
> (008007) [22:06:41] % chmod 777 -R /dev/ashmem
> (008007) [22:06:41] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
> (008007) [22:06:41] % chmod 777 -R /dev/dri
> (008007) [22:06:41] % chmod 777 -R /dev/fb0
> (008007) [22:06:41] % chmod 777 -R /dev/video0
> (008007) [22:06:41] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
> (008007) [22:06:41] New background process: pid=11569, output=background
> lxc-start: waydroid: network.c: netdev_configure_server_veth: 710 No such file or directory - Failed to attach "vethl3cbqf" to bridge "waydroid0", bridge interface doesn't exist
> lxc-start: waydroid: network.c: lxc_create_network_priv: 3413 No such file or directory - Failed to create network device
> lxc-start: waydroid: start.c: lxc_spawn: 1843 Failed to create the network
> lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
> lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
> lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
> lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
> lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
> (008007) [22:06:41] waiting 10 seconds for container to start...
> (008007) [22:06:42] waiting 9 seconds for container to start...
> (008007) [22:06:43] waiting 8 seconds for container to start...
> (008007) [22:06:44] waiting 7 seconds for container to start...
> (008007) [22:06:45] waiting 6 seconds for container to start...
> (008007) [22:06:46] waiting 5 seconds for container to start...
> (008007) [22:06:47] waiting 4 seconds for container to start...
> (008007) [22:06:48] waiting 3 seconds for container to start...
> (008007) [22:06:49] waiting 2 seconds for container to start...
> (008007) [22:06:50] waiting 1 seconds for container to start...
> (008007) [22:06:51] ERROR: container failed to start
> (008007) [22:06:51] See also: <https://github.com/waydroid>
> (008007) [22:06:51] Traceback (most recent call last):
>   File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
>     actions.container_manager.start(args)
>   File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
>     raise OSError("container failed to start")
> OSError: container failed to start
> 
> (011703) [22:06:51] UserMonitor service is not even started
> (011703) [22:06:51] Clipboard service is not even started
> (011455) [22:06:51] UserMonitor service is not even started
> (011455) [22:06:51] Clipboard service is not even started
> (011713) [22:07:01] % tail -n 60 -F /var/lib/waydroid/waydroid.log
> (011713) [22:07:01] *** output passed to waydroid stdout, not to this log ***
> ```

If you are using waydroid from my repository, I have applied the patch https://github.com/waydroid/waydroid/pull/267 suggested @Quackdoc 
You can check

**Comment by Pshemas** [comment]
Thank you - will give it a shot. 

@DeadMozay : awesome, will try your repo. I'm pretty sure it was one of the 2 I've tried.

I have my fingers crossed - some of the Android apps would fill gaps in my workflow quite nicely.

**Comment by Pshemas** [comment]
ok, now it seems I don't have ashmem and binder - thus can't re-initilize. Any ideas howto add those?

**Comment by Afsalmc** [comment]
> ok, now it seems I don't have ashmem and binder - thus can't re-initilize. Any ideas howto add those?

https://linux32bituefi.blogspot.com/2021/12/install-waydroid-in-opensuse-tumbleweed.html

Follow step 3 to enable all anbox modules . keep in mind that this guide may be outdated and ashmem support is now removed from linux kernel .

**Comment by DeadMozay** [comment]
> ok, now it seems I don't have ashmem and binder - thus can't re-initilize. Any ideas howto add those?

`home:Dead_Mozay:kernel:android:TW`

enabled `binder` module
the `ashmem` module is no longer in the kernel, instead of it, there is now another `memfd` module

```
cat /proc/config.gz| grep MEMFD
CONFIG_MEMFD_CREATE=y
```
it's already enabled in the kernel

**Comment by Afsalmc** [comment]
since ashmem is removed from the core linux , you need to either re-init waydroid or add sys.use_memfd=true to /var/lib/waydroid/waydroid_base.prop

**Comment by DeadMozay** [comment]
> 

Should be fine
```
❯ uname -a
Linux note 5.18.5-5-default #1 SMP PREEMPT_DYNAMIC Thu Jun 16 12:29:30 UTC 2022 (0ac72f9) x86_64 x86_64 x86_64 GNU/Linux
```

```
❯ sudo zypper if kernel-default
Loading repository data...
Reading package packaging...


Details - kernel-default package:
--------------------------------
Repository            : home:Dead_Mozay:kernel:android:TW
Name                    : kernel-default
Version                 : 5.18.5-5.4
Architecture          : x86_64
Provider                : obs://build.opensuse.org/home:Dead_Mozay
Size after installation : 209,5 MiB
Installed            : Yes
State                 : actual
Source Package : kernel-default-5.18.5-5.4.nosrc
Source address           : https://www.kernel.org/
Conclusion                  : The Standard Kernel
Description               : 
    The standard kernel for both uniprocessor and multiprocessor systems.


    Source Timestamp: 2022-06-16 12:29:30 +0000
    GIT Revision: 0ac72f9bf174b073b3cd82142f6bd1c6cf4cf10b
    GIT Branch: stable
```

**Comment by Afsalmc** [comment]
> > 
> 
> Should be fine
> 
> ```
> ❯ uname -a
> Linux note 5.18.5-5-default #1 SMP PREEMPT_DYNAMIC Thu Jun 16 12:29:30 UTC 2022 (0ac72f9) x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> ```
> ❯ sudo zypper if kernel-default
> Loading repository data...
> Reading package packaging...
> 
> 
> Details - kernel-default package:
> --------------------------------
> Repository            : home:Dead_Mozay:kernel:android:TW
> Name                    : kernel-default
> Version                 : 5.18.5-5.4
> Architecture          : x86_64
> Provider                : obs://build.opensuse.org/home:Dead_Mozay
> Size after installation : 209,5 MiB
> Installed            : Yes
> State                 : actual
> Source Package : kernel-default-5.18.5-5.4.nosrc
> Source address           : https://www.kernel.org/
> Conclusion                  : The Standard Kernel
> Description               : 
>     The standard kernel for both uniprocessor and multiprocessor systems.
> 
> 
>     Source Timestamp: 2022-06-16 12:29:30 +0000
>     GIT Revision: 0ac72f9bf174b073b3cd82142f6bd1c6cf4cf10b
>     GIT Branch: stable
> ```

Woaaah ! It was secure boot preventing the booting .

Now container fails to start . It was working fine with kernel 5.17 .

**Comment by aleasto** [comment]
```
