### ISSUE TITLE
Clipboard manager service Not working 

### ISSUE THREAD

**Issue by Animationss** [waydroid/waydroid#396]
**Describe the bug**

When attempting to start waydroid with the commands listed in this [post](https://github.com/waydroid/waydroid/issues/266#issuecomment-1099287901), I get Clipboard manager service error 

**Screenshots**

![image](https://user-images.githubusercontent.com/89710296/171746147-c411b47d-0b2d-438b-953d-16b0f574e414.png)
Waydroid Logs
![image](https://user-images.githubusercontent.com/89710296/171746293-d1e205ca-2b23-43d2-8861-0b7a5febec72.png)

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.1
 - Waydroid Images Version ???

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 x64 (Linux Mint Una 20.3)
 - GPU: Integrated 
 - Kernel version: 5.4.0-113-generic
 - Host mesa version: ???
 - Desktop: Cinnamon 5.2.7

**Logs (please upload as file)**

 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
https://pastebin.com/raw/3Qx7X3qq
 - Output of `waydroid log`
 https://pastebin.com/raw/ra3weuDJ
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
Taking to long going to edit page when done

**Comment by cniw** [comment]
> Failed to start Clipboard manager service

Install PyClip python module and wayland clipboard package https://github.com/spyoungtech/pyclip

```bash
pip install pyclip
sudo apt install wl-clipboard
```

fyi even with issue you should still can start waydroid, cause it not a crusial part

---

the crusial part is here

> XDG Session is not "wayland"
> Desktop: Cinnamon 5.2.7

It mean you're on x11 session, while wayland compositor is needed to run waydroid.
Until now Cinnamon still hasn't support wayland (it only support x11).
Workaround on x11 session you can have wayland compositor running in nested mode inside your x11 session use kwin_wayland, mutter, wayfire, weston, etc.
the easiest and light you can try weston:

```bash
sudo apt install weston	# installing
weston	# run it, then it would open a weston session in a window
```

now focus to that window, then open terminal inside the by click the terminal icon there

```bash
sudo waydroid container restart
waydroid show-full-ui
```

or just install and use gnome session or kde plasma session

**Comment by Animationss** [comment]
> 

Thx This worked nicely, But internet didn't seem to work.

**Comment by aleasto** [comment]
As stated, you need a wayland compositor

**Comment by SakuraWald** [comment]
> 

This works.

**Comment by iyadahmed** [comment]
I also suffered from this, there are two solutions:
1) a program or a script that types your clipboard as if they were keyboard presses
2) Apps like Zorin connect or KDE connect that sync clipboard between PC and Android (this is what I ended up using)

**Comment by mictadlo** [comment]
Hi,
I ran `sudo apt install waydroid git python3-pip wl-clipboard -y`. Next, I tried:

```
$ pip install pyclip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
Could I combine pyclip and waydroid_script in the following way:
```
git clone https://github.com/casualsnek/waydroid_script
cd waydroid_script
python3 -m venv venv

venv/bin/pip install pyclip
venv/bin/pip install -r requirements.txt

sudo venv/bin/python3 main.py
```

Thank you in advance
