### ISSUE TITLE
Installing gapps build

### ISSUE THREAD

**Issue by stupid-kid-af** [waydroid/waydroid#397]
Hello guys 
Sorry for not searching on web but could anyone tell me how can I install the gapps build?

**Comment by mahancoder** [comment]
`sudo waydroid init -s GAPPS -f`
Also, take a look at https://wiki.archlinux.org/title/Waydroid

**Comment by v1nsai** [comment]
> `sudo waydroid init -s GAPPS -f` Also, take a look at https://wiki.archlinux.org/title/Waydroid

Maybe I'm misunderstanding, but should this install a lineage image with gapps installed?  I'm on Arch and have been following that guide on the wiki but I just end up with a build that has no gapps.

**Comment by mahancoder** [comment]
> > `sudo waydroid init -s GAPPS -f` Also, take a look at https://wiki.archlinux.org/title/Waydroid
> 
> Maybe I'm misunderstanding, but should this install a lineage image with gapps installed? I'm on Arch and have been following that guide on the wiki but I just end up with a build that has no gapps.

I'm not really an expert, but this is how I've setup my emulator (without android studio)
There are also some AUR packages for the images, maybe try one of those.

**Comment by mahancoder** [comment]
> > `sudo waydroid init -s GAPPS -f` Also, take a look at https://wiki.archlinux.org/title/Waydroid
> 
> Maybe I'm misunderstanding, but should this install a lineage image with gapps installed? I'm on Arch and have been following that guide on the wiki but I just end up with a build that has no gapps.

I'm not really an expert, but I used this command to set it up, and it just worked for me.

**Comment by DuttaAB-dev** [comment]
Hey, so I have installed the gapps version of lineage os from sourceforge and registered the install with google device registration. Yet when I press the sign in button, it loads for a few seconds, then the window flashes and the given app(here playstore) resets.
Any help on this matter? Should I create a new issue on this?

**Comment by stupid-kid-af** [comment]
> Hey, so I have installed the gapps version of lineage os from sourceforge and registered the install with google device registration. Yet when I press the sign in button, it loads for a few seconds, then the window flashes and the given app(here playstore) resets. Any help on this matter? Should I create a new issue on this?

Sure!

**Comment by ammgws** [comment]
> Hey, so I have installed the gapps version of lineage os from sourceforge and registered the install with google device registration. Yet when I press the sign in button, it loads for a few seconds, then the window flashes and the given app(here playstore) resets. Any help on this matter? Should I create a new issue on this?

@DuttaAB-dev For me the issue turned out to be because "Android System WebView" wasn't installed. I grabbed the x86/x64 version from [here](https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-103-0-5060-70-release/android-system-webview-103-0-5060-70-8-android-apk-download/) and installed it via adb (tried through `waydroid app install` first but there was no indication in the terminal that it actually worked...). After that Google Play Store etc functioned correctly.

**Comment by DuttaAB-dev** [comment]
@ammgws Thanks for your solution, it worked in my case as well and it confirmed my initial suspicion. I suppose, the gapps image does not actually contain the android webview, thus causing this issue. Should not this be considered a bug?

**Comment by Quackdoc** [comment]
> @ammgws Thanks for your solution, it worked in my case as well and it confirmed my initial suspicion. I suppose, the gapps image does not actually contain the android webview, thus causing this issue. Should not this be considered a bug?

it does have webview, it's just outdated, and it will get updated whenever google and gapps decides they get updated, until then you can manually update by clicking the three dots in the corner and update the included webview.

**Comment by aleasto** [comment]
We now also have a GUI for initialization that should make this easier

**Comment by SirMegaMU** [comment]
I installed the gapp version and i still can;t use the google services... due to the play protection
have any one solved this ?
![image](https://user-images.githubusercontent.com/87977817/203011553-2261e9a0-e036-49f8-bd24-4053bafd2517.png)

**Comment by sanket5105e** [comment]
> I installed the gapp version and i still can;t use the google services... due to the play protection have any one solved this ? ![image](https://user-images.githubusercontent.com/87977817/203011553-2261e9a0-e036-49f8-bd24-4053bafd2517.png)

i am also facing same issue

**Comment by iBolski** [comment]
> Follow the instructions from the link on screen

Doesn't work. When I try to use sqlite3 to query the id, it core dumps. I'm doing it via the waydroid shell, not ADB as ADB doesn't find the instance running.

**Comment by floatinger** [comment]
In case you face the same issue as @sanket5105e follow the official waydroid instructions for getting Google Play Certification https://docs.waydro.id/faq/google-play-certification

**Comment by IndylabPWR** [comment]
> Fedora: `sudo waydroid init -s GAPPS -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor -f`

tysm, works on fedora 41

**Comment by Saadnasir-lab** [comment]
> I installed the gapp version and i still can;t use the google services... due to the play protection have any one solved this ? ![image](https://user-images.githubusercontent.com/87977817/203011553-2261e9a0-e036-49f8-bd24-4053bafd2517.png)

You should see this [video](https://youtu.be/ZbcOQJyxN3E?si=kTiSG3BR9wAbhlsg) This can solve your problem
