### ISSUE TITLE
 ERROR: Binder node "vndbinder" for waydroid not found - Debian 11

### ISSUE THREAD

**Issue by Lordarking** [waydroid/waydroid#399]
When following the instructions from the waydroid website it fails at the point "waydroid init"

**General information**
 - Waydroid Version [1.2.1]

**Desktop**
 - OS: [Debian 11 Bullseye]
 - Kernel version: [5.10.0-14-amd64]
 - Desktop: [KDE Plasma Wayland]

Installed this version at 04.06.2022 with the latest stable version from [https://www.debian.org/download](url)

**Waydroid log**
```
(018374) [12:53:00] % modprobe binder_linux devices="anbox-vndbinder,anbox-hwbinder"
(018374) [12:53:00] ERROR: Binder node "vndbinder" for waydroid not found
(018374) [12:53:00] See also: <https://github.com/waydroid>
(018374) [12:53:00] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 144, in setupBinderNodes
    raise OSError('Binder node "vndbinder" for waydroid not found')
OSError: Binder node "vndbinder" for waydroid not found

(018384) [12:57:07] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(018384) [12:57:07] *** output passed to waydroid stdout, not to this log ***
```

I tried using the guide from [https://github.com/anbox/anbox-modules](url) to get binder up and running but that fails at make ashmem/binder. And the reason as to why that fails would be this: [https://github.com/anbox/anbox-modules/issues/86#issuecomment-988077940](url)

**Comment by cniw** [comment]
I think you don't need to install anbox-modules, because afaik the default debian kernel already has the modules required by waydroid

**Comment by Lordarking** [comment]
So I did a fresh install of Debian again and tried once more. Now it worked. So I will close this one out as an inproper installation from Debian.
