### ISSUE TITLE
Installation bugs

### ISSUE THREAD

**Issue by geole** [waydroid/waydroid#40]
Hello
I noticed two errors in the installation scripts
The first
`apt install waydroid`
must be
`sudo apt install waydroid`
The second for the installation in focal version
The order must become
wget 'https://static.mrcyjanek.net/abstruse/apt-repository/mrcyjanek-repo/mrcyjanek-repo_2.0-1_all.deb' -O cyjanrepo.deb && sudo apt install ./cyjanrepo.deb && rm ./cyjanrepo.deb && **sudo** rm -rf /etc/apt/sources.list.d/cyjan.list && echo 'deb [signedby=/usr/share/keyrings/mrcyjanek-archive-keyring.gpg] https://static.mrcyjanek.net/abstruse/apt-repository/ focal main' **| sudo tee** /etc/apt/sources.list.d/cyjan.list && sudo apt update

**Comment by MrCyjaneK** [comment]
`wget 'https://static.mrcyjanek.net/abstruse/apt-repository/mrcyjanek-repo/mrcyjanek-repo_2.0-1_all.deb' -O cyjanrepo.deb && sudo apt install ./cyjanrepo.deb && rm ./cyjanrepo.deb && rm -rf /etc/apt/sources.list.d/cyjan.list && echo 'deb [signedby=/usr/share/keyrings/mrcyjanek-archive-keyring.gpg] https://static.mrcyjanek.net/abstruse/apt-repository/ focal main' > /etc/apt/sources.list.d/cyjan.list && sudo apt update`

Executing this as root works also, the sudo at the end is not needed

**Comment by geole** [comment]
Hello
Thank you for the answer. But She is contentious
1) Nowhere in the documentation is it specified to be root.
2) If we put ourselves root, then it is useless to put sudo

This order is a big mix and needs to be clarified

==> https://docs.waydro.id/usage/install-on-desktops

**Comment by erfanoabdi** [comment]
docs updated,
i don't think sudo is needed to be mentioned tbh, everyone knows what to do at this point
