### ISSUE TITLE
Is waydroid and WSA (Windows Subsystem for Android) same?

### ISSUE THREAD

**Issue by afzl-wtu** [waydroid/waydroid#400]
I am quite surprised with the performance of android apps in Waydroid. Because it runs apps in a container natively. But there are some issues like Camera support is not available and Game key-mapping is also missing.
I would like to know if WSA is following same native approach. I know it follow Hyper-V technology but is WSA an emulator or it is native as waydroid. There is a huge difference in performance of Waydroid and WSA. If WSA follows same technology as WSA then why it is even slower than Bluestack 5 which is an emulator?

**Comment by Quackdoc** [comment]
not really, WSA and waydroid use different technologies, WSA uses something more akin to kvm. I have a more indepth writeup if you join the telegram chat. and will be happy to talk more there, but this isn't really a discussions suitable for waydroid issue tracker.

**Comment by afzl-wtu** [comment]
> not really, WSA and waydroid use different technologies, WSA uses something more akin to kvm. I have a more indepth writeup if you join the telegram chat. and will be happy to talk more there or on the matrix as the two of them are linked, but this isn't really a discussions suitable for waydroid issue tracker.

please send telegram joining group link.

**Comment by Quackdoc** [comment]
> please send telegram joining group link.

you can get the links on the contact section of waydroids website https://waydro.id/#contact
