### ISSUE TITLE
I propose enabling AppArmor for Waydroid

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [waydroid/waydroid#401]
**Is your feature request related to a problem? Please describe.**
Currently, AppArmor is widely used on desktops, however, Waydroid doesn't use AppArmor protection and sets the container processes to be in "unconfined" mode.

**Describe the solution you'd like**
I propose adding AppArmor profiles for Waydroid container. I've created three AppArmor profiles: one for apps, one for ADBD, one for all the other processes. Also, I'm using a new AppArmor 3.0 kernel and userspace, so there are some features used such as profile stacking (they are stacked in order to be usable in "no new privileges" mode)

**Additional context**
These are the profiles. Also, I haven't tested the ADBD, so I don't know how it works with profiles. It's as permissive as possible for the current profile in "no new privileges" mode
[profiles.tar.gz](https://github.com/waydroid/waydroid/files/8855789/profiles.tar.gz)

Proposed in a [pull request #403](https://github.com/waydroid/waydroid/pull/403).

**Comment by ChrysoliteAzalea** [comment]
> Android has a lot of SELinux policy written for it. I wonder if we could take advantage of LSM namespaces, or if they are not ready yet.

As far as I know, SELinux and AppArmor cannot be used together, so they can only be used on SELinux systems. Since a lot of desktop systems use AppArmor, I think we should have policy for AppArmor too.

**Comment by CameronNemo** [comment]
You seem to have missed the "LSM namespaces" part. See here for example: https://blog.linuxplumbersconf.org/2017/ocw/system/presentations/4768/original/Namespacing%20and%20Stacking%20the%20LSM.pdf

I don't really know if that project was delivered in the past 5 years, but it would be a lot easier and better to use the prewritten Android policy than write AppArmor policy from scratch.

**Comment by ChrysoliteAzalea** [comment]
The problem is that SELinux labels the filesystem and AppArmor doesn't. If the Android container uses SELinux (and therefore labeled filesystem) and the rest of the system uses AppArmor and therefore doesn't use FS labels, how would Android container react to some host FS resources being exposed to it? Moreover, how would container use SELinux if it's already confined by AppArmor? Would enabling SELinux confinement disable AppArmor confinement?

Also, AppArmor has the profile stacking feature, so an application can restrict itself further if the "No New Privileges" is enabled (but not loosen restrictions). I don't know whether such feature exists in SELinux.

**Comment by ChrysoliteAzalea** [comment]
[There is already a pull request](https://github.com/waydroid/waydroid/pull/403).
