### ISSUE TITLE
Kernel config options for ethernet bridging in Waydroid 

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#402]
Hey there,
What kernel config options are needed in order to use ethernet bridging with Waydroid? 

So far I have modularized every option under Networking support that is modularizable. The setup with this lsmod works:

https://dpaste.com/4QACXLWKS

Keep up the great work! 

Thanks in advance.

EDIT: After over 15 hours of trial and error I got the last missing Kernel config options tracked down.
Procedure: 
1. enable everything in the kernel that has something to do with networking -> Waydroid Internet must work as there is no option that was left out.
2. modularize every networking option that is modularizable and see what modules are getting used by executing `lsmod`. Compile these options into the kernel if desired.
3. turn on every option that cannot be modularized, try different areas of networking options (eg. networking filesystems, networking drivers and networking support)
4. leave out areas where nothing is getting used from.
5. try smaller areas within a larger area (eg. in Networking support: Netfilter, the IPv6 protocol, general networking support).

needed options: 

modularizable:

XFRM_INTERFACE
INET6_TUNNEL
INET_TUNNEL
CONFIG_VSOCKETS
CONFIG_VSOCKETS_LOOPBACK
CONFIG_VIRTIO_VSOCKETS
BRIDGE
CFG80211 (needed if you want to use a wireless internet connection)
RFKILL (needed if you want to use a wireless internet connection)
VLAN_8021Q
CONFIG_VLAN_8021Q_GVRP
CONFIG_VLAN_8021Q_MVRP
STP
MRP
BPFILTER
NETFILTER_XT_TARGET_CHECKSUM
IP_NF_MANGLE
NETFILTER_XT_TARGET_MASQUERADE
IP_NF_NAT
NF_NAT
CONFIG_NETFILTER_XT_MATCH_STATE
NETFILTER_XT_MATCH_CONNTRACK
NF_CONNTRACK
NF_DEFRAG_IPV4
NF_DEFRAG_IPV6
CONFIG_IP_NF_FILTER
CONFIG_IP_NF_IPTABLES
CONFIG_NFT_COMPAT

non-modularizable:

CONFIG_IP_ADVANCED_ROUTER
CONFIG_IP_MULTIPLE_TABLES
CONFIG_IP_ROUTE_MULTIPATH

CONFIG_IPV6_SUBTREES
CONFIG_IPV6_SEG6_LWTUNNEL
CONFIG_IPV6_SEG6_HMAC
CONFIG_IPV6_RPL_LWTUNNEL

**Comment by oklopfer** [comment]
I have been trying to fix networking on waydroid for days on end. this is exactly what I needed for the fix. thank you.
