### ISSUE TITLE
Please add an scale setting (HIDPI support)

### ISSUE THREAD

**Issue by Zeioth** [waydroid/waydroid#407]
**Is your feature request related to a problem? Please describe.**
Waydroid works good, but apps look tiny on my 4k screen, which in practice makes them unusable.

**Describe the solution you'd like**
Having an env var like WAYDROID_SCALE=2 to scale the window content, [like most apps work](https://wiki.archlinux.org/title/HiDPI) .

**Describe alternatives you've considered**
A waydroid prop for the same purpose.

**Comment by cniw** [comment]
Honestly i don't know the dpi value which is equivalent to hidpi so just set the value as you like.

```
# Remove ro.sf.lcd_density properly if exist
grep ro.sf.lcd_density /var/lib/waydroid/waydroid_base.prop && \
sudo sed -i '/ro.sf.lcd_density/d' /var/lib/waydroid/waydroid_base.prop

# Append ro.sf.lcd_density property
echo "ro.sf.lcd_density=320" | sudo tee -a /var/lib/waydroid/waydroid_base.prop
```

Then restart waydroid.

Please read this too  https://github.com/waydroid/waydroid/issues/388#issuecomment-1135696836

**Comment by Zeioth** [comment]
So we do have a prop for it!! It would be nice to [add it to the docs](https://docs.waydro.id/usage/waydroid-prop-options).

It worked perfect, thank you so much.

**Comment by Quackdoc** [comment]
yeah this is true. this issue should stay open until it is addressed

**Comment by aleasto** [comment]
There already is `GRID_UNIT_PX`

Also I don't know how but on my HiDPI laptop it's nicely scaled out of the box?

**Comment by aleasto** [comment]
Your compositor should be reporting the wayland display scale. If not, you can use `export GRID_UNIT_PX=` or other ways as pointed out.
