### ISSUE TITLE
XDG Session is not "wayland"

### ISSUE THREAD

**Issue by geole** [waydroid/waydroid#41]
`Hello`
Under HIRSUTE.

a@a:~/Téléchargements$ sudo waydroid session stop
[11:46:28] WayDroid session is not started

a@a:~/Téléchargements$ sudo waydroid session start
[11:46:37] XDG Session is not "wayland"
[11:46:39] Failed to start Clipboard manager service, check logs

a@a:~/Téléchargements$ sudo waydroid app install F-Droid.apk
[11:58:45] WayDroid session is stopped

```
a@a:~Téléchargements$ echo $XDG_SESSION_TYPE
wayland
a@a:~ Téléchargements
```

**Comment by MrCyjaneK** [comment]
iirc session should be started as normal user not as root

**Comment by geole** [comment]
Hello
It is possible that part of the startup was done by the root user because the problem has just disappeared after a restart.

This proves that you should not be root during the installation because you sometimes forget to leave this mode.
