### ISSUE TITLE
Detailed openSUSE Guide

### ISSUE THREAD

**Issue by Sehrail** [waydroid/waydroid#413]
There are no good resources for installing Waydroid on OpenSUSE. Resources are also lacking. Please create a detailed guide to install Waydroid on OpenSUSE

NOTE: https://linux32bituefi.blogspot.com/2021/12/install-waydroid-in-opensuse-tumbleweed.html this guide is not working

**Comment by Afsalmc** [comment]
Hey on kernel 5.17 waydroid is working like a charm for me . For 5.18 things have changed , ashmem support is removed and memfd is pushed instead . 
A kernel with memfd and binder support which i have not tested is released by Dead_Mozay . also check the step 3 of the blogspot guide .
[](https://software.opensuse.org//download.html?project=home%3ADead_Mozay%3Akernel%3Aandroid%3ATW&package=kernel-default)

**Comment by Afsalmc** [comment]
Updated to 5.18 . It's broken for me as well .

**Comment by aleasto** [comment]
As you can imagine we cannot handle distributing the software for all flavours. This is tipically handled by maintainers downstream.

If you have a working package and few lines of instructions, please submit them to https://github.com/waydroid/docs

Otherwise, if you want to pick up the task, the Fedora RPM might be a good starting place: https://pagure.io/waydroid/waydroid

**Comment by hatch01** [comment]
this guide worked for me https://codeberg.org/cream/waydroid-openSUSE-setup
(I just replaced anbox-kmp-default and anbox-modules-autoload by the one made by onlyJak0b:Stable:waydroid)

**Comment by Runa-Chin** [comment]
Well, I got updated for guides. It still works for Tumbleweed, also with Slowroll too.
[See my updated guides for installing WayDroid on openSUSE Tumbleweed and Slowroll](https://gist.github.com/Runa-Chin/fac044b026946120e660fe9576da721e) or see the newest discussion by myself.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/413#issuecomment-1584660598

@hatch01, best to link to the revision you accessed it on, in case the file becomes unavailable in the future: https://codeberg.org/cream/waydroid-openSUSE-setup/src/commit/66175e670b2c6905af4e1c6e5d1c734f4c5f4600/README.md#waydroid-opensuse-setup
