### ISSUE TITLE
Could the new open source drivers nvidia is making allow you to support them in waydroid?

### ISSUE THREAD

**Issue by linusrg1** [waydroid/waydroid#417]
If waydroid is supposed to be a anbox replacement then it should support nvidia like it did, and I see no reason not to now due to half of the driver package being open source now. And it is prolly the part of the package you care about most about, the kernel modules.

Great project unfortunately poor support at the moment.

**Comment by chinese-wzq** [comment]
Yeah,there are lots of nvidia users all over the world,but they have to get terrible support.

**Comment by Quackdoc** [comment]
the least important half for is open source. we need userland to be open, or at least compatible, it is neither right now

**Comment by aleasto** [comment]
Not anytime soon
