### ISSUE TITLE
cgroup issues (i think) that prevent android from booting

### ISSUE THREAD

**Issue by sp1ritCS** [waydroid/waydroid#420]
While I'm able to start the container and the session, `waydroid status` also reports them as running, actually interacting with the android system (e.g. `waydroid show-full-ui`) only leads to `Failed to get service waydroidplatform, trying again...`.

There are quite a lot of error messages in dmesg, that I'm unsure what exactly is the culprit, but I assume the root cause is:
```
[  263.915903] libprocessgroup: Failed to mount blkio cgroup: Operation not permitted
[  263.915911] libprocessgroup: Failed to setup blkio cgroup
[  263.915940] libprocessgroup: Failed to mount cpu cgroup: Operation not permitted
[  263.915944] libprocessgroup: Failed to setup cpu cgroup
[  263.915966] libprocessgroup: Failed to mount cpuacct cgroup: Operation not permitted
[  263.915970] libprocessgroup: Failed to setup cpuacct cgroup
[  263.915981] libprocessgroup: Failed to mount cpuset cgroup: Operation not permitted
[  263.915985] libprocessgroup: Failed to setup cpuset cgroup
[  263.915996] libprocessgroup: Failed to mount memory cgroup: Operation not permitted
[  263.915999] libprocessgroup: Failed to setup memory cgroup
[  263.916005] cgroup: Unknown subsys name 'schedtune'
[  263.916009] libprocessgroup: Failed to mount schedtune cgroup: Invalid argument
[  263.916013] libprocessgroup: Failed to setup schedtune cgroup
```

that then lead to a lot of `libprocessgroup: Failed to make and chown /acct/uid_<number>: Read-only file system` errors, which in turn end up with `SIGABRT`s.

**General information (please complete the following information):**
 - Waydroid tools 1.2.1+git.3 (facf2b7)
 - Waydroid Images ? (I ran `sudo waydroid init -c https://waydroid.bardia.tech/OTA/system -v https://waydroid.bardia.tech/OTA/vendor` today)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed 20220616
 - GPU: AMD Radeon™ RX 580
 - Kernel version: 5.18.5-5-default
 - Host mesa version: 22.1.1
 - Desktop: GNOME 42.2 & swaywm 1.7 (wlroots 0.15.1)

**Additional context**
This doesn't appear to be a selinux issues, as I'm able to replicate it in permissive mode, and with other LSMs (appamor and without anything)  

**Logs (please upload as file)**
 - [waydroid_base.prop.gz](https://github.com/waydroid/waydroid/files/8934344/waydroid_base.prop.gz)
 - [waydroid_log.txt](https://github.com/waydroid/waydroid/files/8934347/waydroid_log.txt)
 - [waydroid_logcat.txt](https://github.com/waydroid/waydroid/files/8934349/waydroid_logcat.txt)
 - dmesg: [kern_log.gz](https://github.com/waydroid/waydroid/files/8934350/kern_log.gz)
 - dmesg: [kern_log_color.gz](https://github.com/waydroid/waydroid/files/8934352/kern_log_color.gz)

**Comment by skeydan** [comment]
Hey, I think you might want to take a look at https://github.com/waydroid/waydroid/issues/346 and see if it helps.
There, the problem was the kernel had CONFIG_RT_GROUP_SCHED set (and it needs to be unset).

**Comment by sp1ritCS** [comment]
no, my kernel does not have CONFIG_RT_GROUP_SCHED set, so it's probably something else
```
admin@spiritPC:~> cat /boot/config-5.18.5-5-default | grep RT_GROUP
# CONFIG_RT_GROUP_SCHED is not set
```

**Comment by aleasto** [comment]
```
lxc-start: waydroid: utils.c: safe_mount: 1218 No such file or directory - Failed to mount "/dev/anbox-vndbinder" onto "/usr/lib64/lxc/rootfs/dev/vndbinder"
lxc-start: waydroid: utils.c: safe_mount: 1218 No such file or directory - Failed to mount "/dev/anbox-hwbinder" onto "/usr/lib64/lxc/rootfs/dev/hwbinder"
```
You seem to be missing binder devices.
This is not on us, you should be discussing this downstream. We don't even have a SUSE install guide linked on the docs...

**Comment by Hccccc1** [comment]
Any updates ? I ran into the same issues.
