### ISSUE TITLE
Unable to use pen input tablet.

### ISSUE THREAD

**Issue by DuttaAB-dev** [waydroid/waydroid#423]
**Describe the bug**
While using a pen input tablet for drawing, the cursor just disappears when I try to bring it onto any waydroid window(here, sketchbook)

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.1]

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - GPU: Intel uhd 620
 - Kernel version: 5.18.5-200.fc36.x86_64 
 - Desktop: Gnome 42 with wayland

**Comment by jor1196** [comment]
This happens to me with ubuntu 22.04, any bash solution?
