### ISSUE TITLE
[Need Help] This error log shows forever: "Failed to get service waydroidplatform, trying again..."

### ISSUE THREAD

**Issue by diyism** [waydroid/waydroid#427]
First I burned Armbian_22.05.3_Pine64_focal_current_5.15.48.img.xz into my pine64 single board and boot successfully.

```
$ sudo su
$ apt update
$ apt install gnome-session-wayland
$ apt install gnome-terminal
$ apt install gdm3
$ gnome-session-inhibit --inhibit idle top

$ apt install linux-headers-current-sunxi64
$ git clone https://github.com/choff/anbox-modules.git
$ cd anbox-modules
$ ./INSTALL.sh
...
DKMS: install completed.
binder_linux          122880  0
ashmem_linux           24576  0

$ curl -s https://gist.githubusercontent.com/diyism/add38aaf34c4e14a76c25666439a318e/raw | bash

$ waydroid init

$ waydroid session start
UserMonitor service is not even started
Clipboard service is not even started

$ sudo waydroid container start
[gbinder] Service manager /dev/binder has appeared
[15:00:23] Failed to add service waydroidhardware: -1

$ waydroid status
Session:	RUNNING
Container:	RUNNING
Vendor type:	MAINLINE
Session user:	malcolm(1000)
Wayland display:	wayland-0

$ waydroid show-full-ui
(011151) [14:41:37] Failed to get service waydroidplatform, trying again...
(011151) [14:41:38] Failed to get service waydroidplatform, trying again...
```

This message continue forever, I can't figure out what's wrong, any idea?

**Comment by Luciogi** [comment]
Try this https://github.com/waydroid/waydroid/issues/347#issuecomment-1087607521 , give feedback.

**Comment by diyism** [comment]
> Try this [#347 (comment)](https://github.com/waydroid/waydroid/issues/347#issuecomment-1087607521) , give feedback.

No, #347 just wait for about 1 minutes then the Waydroid android UI will show, but in my case, the error message will continue forever.

I can't figure out what's wrong, while "waydroid status" show Session and Container are running, and both binder_linux and ashmem_linux are OK, and my DE  gnome-session-wayland also seems OK.

**Comment by Luciogi** [comment]
check is there any log file /var/log/

**Comment by diyism** [comment]
Thanks,

I saw
"pine64 kernel: [288625.818815] binder_linux: undelivered death notification, 00000
00000000000"
in /var/log/syslog

I'll try to recompile binder_linux.

**Comment by diyism** [comment]
No effect, It seems the upper syslog triggered by killing "waydroid show-full-ui", it's not an error.

**Comment by Luciogi** [comment]
see logs using command `waydroid log`

**Comment by diyism** [comment]
$ sudo waydroid log
(011151) [14:41:37] Failed to get service waydroidplatform, trying again...
(011151) [14:41:38] Failed to get service waydroidplatform, trying again...
(011151) [14:41:37] Failed to get service waydroidplatform, trying again...
(011151) [14:41:38] Failed to get service waydroidplatform, trying again...
…

It's same with the "waydroid show-full-ui".

**Comment by diyism** [comment]
"sudo waydroid shell" is ok
I can see the waydroid ip is 192.168.250.112
and I can "adb connect 192.168.250.112"
"adb devices" show "192.168.250.112:5555 device",
but while I do "adb shell", it say:
"error: fork failed, no such device"

**Comment by kj7rrv** [comment]
I'm having the same issue on my PinePhone running DanctNIX Phosh.

**Comment by kj7rrv** [comment]
This is what I did (**WARNING**: this deletes all your Waydroid data):

    waydroid session stop
    paru -R waydroid waydroid-image
    sudo rm -rf /var/lib/waydroid ~/.local/share/waydroid /usr/share/waydroid-extra
    paru -S waydroid waydroid-image
    waydroid init
    systemctl enable waydroid-container.service

Then I rebooted, and now Waydroid works.

**Comment by diyism** [comment]
@kj7rrv  Amazing, thanks.
I just did:
```
sudo apt remove waydroid
sudo rm -rf /var/lib/waydroid ~/.local/share/waydroid /usr/share/waydroid-extra
sudo waydroid init
waydroid session start &
sudo waydroid container start &
waydroid show-full-ui
```
After 1 minute, I can see the android desktop now.

**Comment by jhay06** [comment]
this happens when you run 2 waydroid session at the same time 

what i did is restart waydroid-container and then run waydroid show-full-ui

**Comment by ayasa520** [comment]
> This is what I did (**WARNING**: this deletes all your Waydroid data and is equivalent to a factory reset):
> 
> ```
> waydroid session stop
> paru -R waydroid waydroid-image
> sudo rm -rf /var/lib/waydroid ~/.local/share/waydroid /usr/share/waydroid-extra
> paru -S waydroid waydroid-image
> sudo waydroid init
> sudo systemctl enable waydroid-container.service
> ```
> 
> Then I rebooted, and now Waydroid works.

Thank you so much, this worked for me

**Comment by aleasto** [comment]
Pine GPUs should now be supported
