### ISSUE TITLE
Excessive permissions in `/var/lib/waydroid`

### ISSUE THREAD

**Issue by LecrisUT** [waydroid/waydroid#43]
Besides the `.cfg` file having write permission to all, the write permission to directories is completely excessive
```shell
drwxrwxrwx. 1 root root    0 Sep 12 18:07 cache_http
drwxrwxrwx. 1 root root    0 Sep 12 18:07 host-permissions
drwxrwxrwx. 1 root root   40 Sep 12 18:07 images
drwxrwxrwx. 1 root root    0 Sep 12 18:07 rootfs
-rw-rw-rw-. 1 root root 1848 Sep  6 21:38 tools.log
-rw-rw-rw-. 1 root root  419 Sep 12 18:07 waydroid.cfg
-rw-rw-rw-. 1 root root 2240 Sep 12 18:38 waydroid.log
```
It might be due to botched installation, but if these are indeed set so by  the installer, consider changing them. If it is an error with the installer, there should be failsafe to not allow those permissions.

**Comment by erfanoabdi** [comment]
yes indeed, i left a `umask(0)` and totally forgot about it
will take care of it later..

**Comment by nobodysu** [comment]
I hate to press on this, but world-writable files should be fixed asap.

**Comment by ChrysoliteAzalea** [comment]
I checked today -- the waydroid session doesn't start if write access to ```waydroid.log``` is denied, but write access to other files and directories can be made for root only.
