### ISSUE TITLE
Container wont start, possibly because of iptables

### ISSUE THREAD

**Issue by Apacelus** [waydroid/waydroid#430]
**Describe the bug**
Followed the install instructions and used the script to compile the missing/broken python lib(as described in #368)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 via [breath](https://github.com/cb-linux/breath)
 - GPU: Intel UHD(i3 11th gen cpu)
 - Kernel version: 5.10.106 chromeos kernel
 - Host mesa version: N/A
 - Desktop: Gnome 42

**Additional context**
I am running ubuntu with a chromeos kernel. A normal virtual machine via qemu with network does work tho.
- ashmem is working
- dnsmasq is already installed

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`: https://pastebin.com/3yh4F655
 - Output of `waydroid log`: https://pastebin.com/c8p1apuq
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services: N/A

**Comment by aleasto** [comment]
Your host system has an odd version of iptables.
Consider removing `iptables-legacy` and installing `iptables-nft` instead, or jumping directly to `nftables` by changing `LXC_USE_NFT="false"` to `LXC_USE_NFT="true"` in `/usr/lib/waydroid/data/scripts/waydroid-net.sh`

**Comment by Apacelus** [comment]
@aleasto 
> Your host system has an odd version of iptables. Consider removing `iptables-legacy` and installing `iptables-nft` instead, or jumping directly to `nftables` by changing `LXC_USE_NFT="false"` to `LXC_USE_NFT="true"` in `/usr/lib/waydroid/data/scripts/waydroid-net.sh`

That just refuses to work. I have nftables installed and after editing that file, the script still uses iptables-legacy.

I do not have an `iptables-legacy` package, only `iptables`, which I cant remove because lxc-utils depends on it(and waydroid depends on lxc-utils)
