### ISSUE TITLE
waydroid assumes uid/gid 1000. Wrong user premission for  ~/.local/share/waydroid

### ISSUE THREAD

**Issue by sylv-io** [waydroid/waydroid#434]
**Describe the bug**
Installing apk gives me permission denied:
```
$ waydroid app install downloads/F-Droid.apk 
[18:36:33] ERROR: [Errno 13] Permission denied: '/home/sylv/.local/share/waydroid/data/waydroid_tmp'
```

It looks like the data folder has uid/gid 1000:
```
$ ls -l /home/sylv/.local/share/waydroid
total 0
drwxrwx--x 1 1000 1000 748 Jul  1 18:35 data
```

However my user has uid/gid 1337:
```
$ id
uid=1337(sylv) gid=1337(sylv) 
```

For me it looks like it assumes my uid/gui is 1000, which is default on most systems.

**General information (please complete the following information):**
 - Waydroid version 1.2.1

**Desktop:**
 - Device: Lenovo ThinkPad T14 AMD Gen. 1
 - OS: Arch Linux
 - Kernel version: 5.18.7
 - Desktop: sway 1.7

**Comment by sylv-io** [comment]
workaround:
Add yourself into a group with gid 1000

**Comment by aleasto** [comment]
Hi, is `waydroid app install` the only issue you have when running on a different user than 1000:1000?

**Comment by aleasto** [comment]
`waydroid app install` is fixed by: https://github.com/waydroid/android_vendor_waydroid/commit/fa1d1e9b0ccc2628de72d7b5dd8c29251106b973

**Comment by aleasto** [comment]
Closing because the fix for installing apps was deployed. If there's more issues please reopen.
