### ISSUE TITLE
Ubuntu 20.04: container failed to start: `waidroid0` inderface does not exists

### ISSUE THREAD

**Issue by matusf** [waydroid/waydroid#437]
Hello,I was following the installation instructions for ubuntu, but I'm unable to start the waydroid container. Going through the logs, it seems that it fails because the `waydroid0` interface does not exists and it fails to create one. I tried going through the existing issues and created it manueally, but it did not help, so I reinstalled waydroid. 

I'm using a wayland session. (`$XDG_SESSION_TYPE == wayland`)

```
lxc-start: waydroid: network.c: netdev_configure_server_veth: 710 No such file or directory - Failed to attach "veth9j3O6Q" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3413 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1843 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
```

**General information (please complete the following information):**
 - Waydroid tools Version `waydroid -V 1.2.1`
 - Waydroid Images Version `lineage-17.1-20220515-VANILLA-waydroid_x86_64-system` `lineage-17.1-20220515-MAINLINE-waydroid_x86_64-vendor`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 x86_64
 - GPU: Mesa Intel® UHD Graphics 620 (KBL GT2)
 - Kernel version: 5.13.0-52-generic
 - Desktop: Gnome 3.36.8

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.2.1
ro.vndk.lite=true
```

 - Output of `waydroid log`: [waydroid.log](https://github.com/waydroid/waydroid/files/9042198/waydroid.log)

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
```
[00:23:56] WayDroid container is STOPPED
```

**Comment by m-h-san** [comment]
You may be able to fix this problem in the below way.

1. run this command in the shell to stop waydroid container.
```sh
sudo systemctl stop waydroid-container
```
2. make a bridge connection with this command.
```sh
nmcli con add type bridge ifname waydroid0 -- connection.id waydroid-net ipv4.method shared ipv4.addresses 192.168.250.1/24
```
This command is modified the one can be found in anbox post on Archwiki ([Anbox - ArchWiki](https://wiki.archlinux.org/title/Anbox#Via_NetworkManager)).
***Do so at your own risk as you will be editing the system.
I cannot be held responsible.**
  
3. start waydroid container
```sh
sudo systemctl stop waydroid-container
```
-----
(I am studying English.
I write sentences with the help of automatic translation.
I am sure that some parts may be difficult to convey, but I hope that I have been helpful.)

**Comment by aleasto** [comment]
```
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
```

You are using a kernel that is missing some networking features.
