### ISSUE TITLE
waydroid adb connection

### ISSUE THREAD

**Issue by jhay06** [waydroid/waydroid#453]
hi , i want my host ADB to connect to waydroid so i can use Android studio to create app and deploy to waydroid

using this command 
adb connect 192.168.250.112:5555  returns connection refused 

and  also try to telnet it 192.168.250.112 5555 but same error connection refused 

any ideas ?

**Comment by jhay06** [comment]
also i try to sudo apt-get upgrade , and waydroid installed its updated app , and the ip becomes 192.168.240.112 , but the same output when connecting adb to it.

**Comment by jhay06** [comment]
![image](https://user-images.githubusercontent.com/5191437/182098272-877a7b14-4a75-460f-bd73-7fd1a064006d.png)
i think that is the reason why adb connection always failing

**Comment by escape0707** [comment]
I was able to connect with adb, Android Studio shows `Device 1` but still can't use that device to install and debug apps.

**Comment by jhay06** [comment]
still not solved , adbd still crashing hope this will fix soon

**Comment by jhay06** [comment]
bump , anyone ?

**Comment by aleasto** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/348

**Comment by escape0707** [comment]
> Duplicate of https://github.com/waydroid/waydroid/issues/348

Sir, since this issue is marked as duplicate, could you kindly confirm that android studio works with waydroid without problems now?
