### ISSUE TITLE
3d Games Crash on Start

### ISSUE THREAD

**Issue by k4ever** [waydroid/waydroid#458]
**Describe the bug**
3d game apps like Beach Buggy Blitz and Sparkle Unleashed crash immediately upon start

**General information (please complete the following information):**
 - Waydroid Tools version 1.2.1-1
 - Waydroid-Image-Gapps 17.1_20220515-2

**Desktop (please complete the following information):**
 - Hardware: Microsoft Surface Pro 8 11th Gen Intel® Core™ i5-1135G7 × 8
 - OS: EndeavourOS
 - GPU: Mesa Intel® Xe Graphics (TGL GT2)
 - Kernel version: 5.18.12-arch1-1-surface
 - Host mesa version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.3
 - Desktop: GNOME 42.3

**Additional context**
Whenever I install and start a 3d game in Waydroid, it immediately crashes. It seems that only 2d games like Freecell work.

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9165204/waydroid_base.prop.txt)

 - Output of `waydroid log`
[waydroid-log.txt](https://github.com/waydroid/waydroid/files/9165197/waydroid-log.txt)

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
[waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/9165175/waydroid-logcat.txt)

**Comment by wilsontulus** [comment]
@k4ever All apps you mentioned are confirmed to be x86-compatible by using apkcombo, so the architecture support of these apps aren't the main problem.

**Comment by wilsontulus** [comment]
Also some 3D games are working on waydroid, assuming you have a stable GPU driver and the game is natively x86-compatible.

**Comment by aleasto** [comment]
We are now running the latest mesa version
