### ISSUE TITLE
Waiting for waydroid container service... Binder node "vndbinder" for waydroid not found

### ISSUE THREAD

**Issue by bonginkosi0607** [waydroid/waydroid#469]
![Screenshot at 2022-07-30 06-43-45](https://user-images.githubusercontent.com/79277467/181872751-4c4aa7b5-fa68-4004-87cd-cd129ae13be8.png)

**Comment by cniw** [comment]
What is your Distro `grep -oP '(?<=^NAME=).*' /etc/os-release` and Kernel `uname -r`?

**Comment by vyalcevanet** [comment]
what is your result of running
zcat /proc/config.gz | grep BINDER
?

it should be:
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"

**Comment by EkCaAv** [comment]
> What is your Distro `grep -oP '(?<=^NAME=).*' /etc/os-release` and Kernel `uname -r`?

I have the same problem and the distro is Kali GNU/Linux and kernel 5.18.0-kali7-amd64

**Comment by aleasto** [comment]
Assuming this is PopOS, we now have PopOS install procedure documented: https://docs.waydro.id/usage/install-on-desktops#popos

You may try the same on Kali linux.
