### ISSUE TITLE
What would it take to port Waydroid to X11?

### ISSUE THREAD

**Issue by enthusiastic2003** [waydroid/waydroid#470]
The title says it all. I am planning to do it. What would it take? Or is it impossible?

**Comment by Quackdoc** [comment]
it would take x11 to support wayland protocols, using a nested wayland session is the route to go

**Comment by MasterKia** [comment]
For more info see Waydroid on Arch Wiki.
It explains how to use it on X11.

**Comment by aleasto** [comment]
This is not feasible.

**Comment by MasterKia** [comment]
> For more info see Waydroid on Arch Wiki.
> It explains how to use it on X11.

https://wiki.archlinux.org/title/Waydroid#Wayland_session_manager:
_Note that even if you are in X11, many Wayland session managers support nested session (so you can run it inside your X11 session), the simplest example is [weston](https://archlinux.org/packages/?name=weston)._
