### ISSUE TITLE
Stylus input does not work

### ISSUE THREAD

**Issue by Thesola10** [waydroid/waydroid#472]
**Describe the bug**
Android supports stylus input, as seen on the Samsung Galaxy Note series among other devices. When I use a Wacom stylus on a Waydroid window, the window does not react whatsoever, even on apps that support active stylus input like Nebo.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.2.1
 - Waydroid Images Version: GAPPS 17.1_20220515-2

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: Intel Iris Xe
 - Kernel version: 5.18.14-arch1-1
 - Host mesa version: 22.1.3
 - Desktop: GNOME 42.3.1

**Additional context**
It should be noted that stylus input works on GNOME itself and is differentiated as such. This behavior is specific to Waydroid.

**Logs (please upload as file)**
 - [waydroid.prop.txt](https://github.com/waydroid/waydroid/files/9229529/waydroid.prop.txt)
 - [waydroid.log](https://github.com/waydroid/waydroid/files/9229528/waydroid.log)
 - [waydroidlogcat.log](https://github.com/waydroid/waydroid/files/9229530/waydroidlogcat.log)

**Comment by Quackdoc** [comment]
iirc waydroid stylus support was merged fairly recently, so make sure you are up to date with waydroid upgrade, and make sure waydroid itself is up to date

**Comment by Thesola10** [comment]
I couldn't find anything about that in PRs, what version number would that be so I can keep an eye out?

**Comment by Thesola10** [comment]
The latest system image (20220723) works with stylus input, thanks
