### ISSUE TITLE
Waydroid lasted image sound broke

### ISSUE THREAD

**Issue by ruditimmermans** [waydroid/waydroid#476]
**Describe the bug**
Waydroid lasted image sound broke
 
**Smartphone (please complete the following information):**
 - Pixel 3a
 - Ubuntu touch OTA-23
 - Halium 9

**Additional context**
When go to Waydroid settings select change notification sound, select a mp3 sound file Waydroid get complete stuck and it dont play the sound.

With the Waydroid images from 2022-05-14 everything works as it should be.

**Comment by aleasto** [comment]
This is fixed in the latest update
