### ISSUE TITLE
Graphical issues when using Waydroid

### ISSUE THREAD

**Issue by Ahmed-E-86** [waydroid/waydroid#477]
**Describe the bug**
I guess the screenshot will describe the issue well than I can with words.

**Screenshots**
![image](https://user-images.githubusercontent.com/29783425/183747769-2d520ed6-4aff-4e90-9de4-35f697b03d0e.png)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.2.1
 - Waydroid Images Version : lineage-17.1-20220723-VANILLA-waydroid_x86_64

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04 x64
 - GPU: AMD Radeon™ HD 8750M
 - Kernel version: Generic 5.15.0-43
 - Host mesa version:  mesa 22.1.5
 - Desktop: KDE Plasma 5.24.6

**Additional context**

**Logs (please upload as file)**
 - Prop file: [waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9294154/waydroid_base.prop.txt)
 - Output of `waydroid log`: [waydroid.log](https://github.com/waydroid/waydroid/files/9294158/waydroid.log)

**Comment by JamiKettunen** [comment]
You can try https://docs.waydro.id/debugging/known-issues#graphical-issues I suppose, otherwise check out software rendering for now https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm (maybe someone else knows how to debug it further)
