### ISSUE TITLE
"Failed to load binder driver" upon running waydroid init

### ISSUE THREAD

**Issue by weisshs** [waydroid/waydroid#481]
I know that this has been covered before, but I am still very new to linux, so I may need some very basic instruction.

 I am running Pop!_os, and have already installed all the dependencies, if that helps any. I tried the install instructions found on docs.waydro.id, but there was an issue with broken packages, so I used the bash by cniw (found here: https://gist.githubusercontent.com/cniw/7a0220ce8b75368f7f57aa422d3fea97/raw). 

This got me past the issue of broken packages, but upon trying to run 'sudo waydroid init' it tells me that the binder driver failed to load, the binder_linux module is not in it's directory, and the binder node "binder is not found". I searched around and cannot seem to find just a simple install command for the binder node. I have already put system.img and vendor.img into their folder (usr/share/waydroid-extra/images).

**Comment by cniw** [comment]
FYI Pop!_OS stock kernel doesn't have binder and  ashmem or memfd which required by Waydroid, so you should install it manually. Check this out https://github.com/choff/anbox-modules

**Comment by weisshs** [comment]
This fixed it! I did have some trouble figuring out waylands afterwards, but once I got that figured out, It worked like a charm and I now have waydroid running well on my system. Thanks for the help!

**Comment by mattiasghodsian** [comment]
I can confirm this works. Clone `andbox-modules` repo and run this commands in the root of the repo on your machine.
```bash
 sudo cp -rT ashmem /usr/src/anbox-ashmem-1
 sudo cp -rT binder /usr/src/anbox-binder-1
 ```
 and then
 ```
 sudo dkms install anbox-ashmem/1
 sudo dkms install anbox-binder/1
 ```
 and then Waydroid should work.

**Comment by saksham-991** [comment]
> I can confirm this works. Clone `andbox-modules` repo and run this commands in the root of the repo on your machine.
> 
>  sudo cp -rT ashmem /usr/src/anbox-ashmem-1
>  sudo cp -rT binder /usr/src/anbox-binder-1
> 
> and then
> 
> ```
> sudo dkms install anbox-ashmem/1
> sudo dkms install anbox-binder/1
> ```
> 
> and then Waydroid should work.

Too good to be true.

**Comment by phoenix-2709** [comment]
hello, i'm runing linux debian on a chromebook and i have the sema problem, non of the comands you said works, what can i do?
