### ISSUE TITLE
Document page installation instructions changed and are incorrect.

### ISSUE THREAD

**Issue by ACR-Jeff** [waydroid/waydroid#489]
**Describe the bug**
I have installed waydroid a number of times the last few weeks. Today I went to the Documents page [](https://docs.waydro.id/usage/install-on-desktops) to remember the proper installation instructions and get the repo for Debian Bullseye install. Yet the instructions seemed to have changed within the last few hours. I am not sure if this is the only step missing or changed but I know for a fact `sudo waydroid init` has been removed (Maybe intentional). 
I followed the steps on the Documents page exactly and when getting to the part to run waydroid from the applications menu a window pops up with "Intialize Waydroid" Followed by the system ota and vendor ota, Yet when trying to download it just presents with "Waiting for waydroid container service..., The waydroid container service is not listening." So then I tried `sudo systemctl restart waydroid-container` and this solved that problem. This step maybe needed to be added to the instructions or code to prevent further issues. After `sudo systemctl restart waydroid-container` then going to the Waydroid application menu and running waydroid it works perfect. Thank you.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: Debian Bullseye Gnome
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: 5.10.0-17-amd64
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

**Comment by aleasto** [comment]
Did you have waydroid previously installed on this same debian installation?

**Comment by ACR-Jeff** [comment]
> Did you have waydroid previously installed on this same Debian installation?

Nope this was a fresh install of Debian with only system updates.
