### ISSUE TITLE
Open inside weston runned in X11 session 

### ISSUE THREAD

**Issue by savegame** [waydroid/waydroid#49]
Is it possible run `waydroid sow-full-ui` in Weston?  Weston started from X11 session, in window.
Container starting normal. and i can enter to shell, after `waydroid show-full-ui`, but it not show Android desktop, and it show in stdout
```
XDG Session is not "wayland"
```

**Comment by 123-123-nil** [comment]
` ~ XDG_SESSION_TYPE=wayland waydroid show-full-ui
[10:38:32] Starting waydroid session`
and the app quits. I am having an old nvidia GPU, hence can't use Wayland.

**Comment by savegame** [comment]
hm, app not quit, but it show nothing 
sorry for screenshot, cant copy text from weston window
![изображение](https://user-images.githubusercontent.com/16311332/134462159-37b16bd6-b652-4537-9823-3ddefa3c6ef0.png)

**Comment by axxop** [comment]
First confirm that your waydroid can run in wayland.

on x11:
1.Stop container: `sudo waydroid container stop`
2.Start container: `sudo waydroid container start`

open weston, run `waydroid show-full-ui` it works fine:

![image](https://user-images.githubusercontent.com/53638052/134801385-12f02072-8006-4a07-bdd2-b5a4f60f8f6e.png)

**Comment by savegame** [comment]
ok ) waydroid works well inside gnome wayland session. but not inside weston in KDE/X11 ...

**Comment by gappleto97** [comment]
Does it work in KDE Wayland?

**Comment by shuriken1812** [comment]
I am testing on my Arch system with the latest packages.. I am on KDE plasma and its working great in wayland as its supposed to.. Weston on X11 works a tiny bit less performant than the native wayland session. haven't tested anything heavy yet.

**Comment by shuriken1812** [comment]
Update for KDE users, instead of using weston, use `kwin_wayland "waydroid show-full-ui"`   This launches a wayland session under X11. :)

**Comment by rizzini** [comment]
@shuriken1812 Thank you so much.

**Comment by savegame** [comment]
@shuriken1812 
> **instead of using weston, use `kwin_wayland "waydroid show-full-ui"` This launches a wayland session under X11. :)**

in this way the key sequences are not work in kwin X11, like `Alt + Tab`

**Comment by bornagainpenguin** [comment]
Is there a way to load weston in the background somewhere and call the Android apps through it directly so they run without needing the entire Android GUI?

**Comment by UlyssesZh** [comment]
> First confirm that your waydroid can run in wayland.
> 
> on x11: 1.Stop container: `sudo waydroid container stop` 2.Start container: `sudo waydroid container start`
> 
> open weston, run `waydroid show-full-ui` it works fine:

@axxop Which distro are you using? I cannot see the Android UI showing up following your step.

**Comment by ramosvacca** [comment]
> I am testing on my Arch system with the latest packages.. I am on KDE plasma and its working great in wayland as its supposed to.. Weston on X11 works a tiny bit less performant than the native wayland session. haven't tested anything heavy yet.

Same for me in Ubuntu 22.04. Tested on Wayland and runs great; then on Weston on X11 an same as above.
