### ISSUE TITLE
Container will not start on system startup

### ISSUE THREAD

**Issue by ACR-Jeff** [waydroid/waydroid#491]
**Describe the bug**
Waydroid Container will not start on system startup. I have to manually start or restart the container to get waydroid to work. I have tried everything I could think of.
My temporary solution is creating a script, With the contends of 
`sudo systemctl restart waydroid-container
sudo systemctl restart waydroid-container`

This is only a temporary solution as it isn't an actual solution, It allows waydroid to work, Yet each time I have to enter my password.
Any suggestions would be great. 

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: Debian Bullseye 11
 - GPU: Intel Device 5906
 - Kernel version: 5.18.0-0.bpo-1-amd64
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: Gnome 1:3.38+3

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

**Comment by electrikjesus** [comment]
Take a close look here at home we are doing it on Waydroid-Linux https://github.com/waydroid/waydroid-linux_tools/tree/main/wd_startup
