### ISSUE TITLE
Failed to load config for waydroid

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#493]
**Description of the bug**
Whenever I try to start the waydroid container. Waydroid fails to read the config, even though, it is present.

``` ~
</> doas waydroid container start
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
[12:11:31] WayDroid container is
```
and whenever I stop the container:
```~
</> doas waydroid container stop
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
[12:22:46] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
[12:22:46] ERROR: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
[12:22:46] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
I have setup waydroid using `doas waydroid init`.

**General information:**
 - Waydroid version: 1.2.1
 - Waydroid Images Version [e.g. VANILLA 20220723]

**Desktop:**
 - OS: Gentoo GNU/Linux ARM64
 - GPU: AMD Radeon™ RX 580 XFX
 - Kernel version: 5.15.10-ga495d1d1543d (https://github.com/SolidRun/linux-stable/tree/linux-5.15.y-cex7)
 - Host mesa version: 22.1.7
 - Desktop: Suckless' dwm window manager 

**Additional context**
Waydroid used to work a few weeks ago.

**Logs**
 https://0x0.st/oLgH.log

**Comment by HanoJing** [comment]
Fix: in `/var/lib/waydroid/lxc/waydroid/config` comment out: lxc.apparmor.profile = unconfined.

**Comment by Sam-programs** [comment]
You might need to restart your device after changing the setting.
