### ISSUE TITLE
Add key mapping for mobile games

### ISSUE THREAD

**Issue by ozair-dev** [waydroid/waydroid#496]
Can we add key mapping feature so mobile games can be played on pc with proper controls (keyboard and mouse)!

**Comment by stupid-kid-af** [comment]
use octopus keymapper apk

**Comment by ayasa520** [comment]
I use [qtscrcpy](https://github.com/barry-ran/QtScrcpy) and it works fine. There is almost no lag on key presses, but the fps of the monitor built in qtscrcpy is low, so I recommend displaying the screen through waydroid and contorl it via qtscrcpy.

**Comment by YogSottot** [comment]
> I use [qtscrcpy](https://github.com/barry-ran/QtScrcpy) and it works fine. There is almost no lag on key presses, but the fps of the monitor built in qtscrcpy is low, so I recommend displaying the screen through waydroid and contorl it via qtscrcpy.

I have set up key mapping in QtScrcpy. But the reaction to mapped buttons is only in QtScrcpy built in monitor. 
In the waydroid window (weston) there is no reaction to these keys.
How is it possible to set up control via qtscrcpy in the waydroid window?

**Comment by CheerfulPianissimo** [comment]
If you're on sway, you can use it's mouse automation features to simulate keymapping without involving waydroid. Just pass the commands to the IPC interface to bind the required keys. it's a bit rough but functional and has the bonus point of working on just about anything. Also scrcpy no longer works with waydroid, so qtscrcpy is presently unusable. Some example `swaymsg` commands:

`swaymsg bindsym Alt+m exec "swaymsg 'seat \"seat0\" cursor set 1700 1000' && swaymsg 'seat \"seat0\" cursor press button1 ' " `

Or:

`swaymsg bindsym Alt+n exec "swaymsg 'seat \"seat0\" cursor release button1' "  `

This simply binds `Alt+m` into moving the cursor to the specified x-y coordinates and pressing the right button and `Alt+n` into releasing it. More info can be probably found in the sway-input docs. Also refer to this [issue](https://github.com/swaywm/sway/issues/1779) in the swaywm repo.

**Comment by roberto68** [comment]
what's sway? and I don't care about gaming but only really pg up/down and up/down arrows and alt+left/right (move back/fwd)

**Comment by selurvedu** [comment]
https://swaywm.org/

**Comment by ashu-otaku** [comment]
> If you're on sway, you can use it's mouse automation features to simulate keymapping without involving waydroid. Just pass the commands to the IPC interface to bind the required keys. it's a bit rough but functional and has the bonus point of working on just about anything. Also scrcpy no longer works with waydroid, so qtscrcpy is presently unusable. Some example `swaymsg` commands:
> 
> `swaymsg bindsym Alt+m exec "swaymsg 'seat \"seat0\" cursor set 1700 1000' && swaymsg 'seat \"seat0\" cursor press button1 ' " `
> 
> Or:
> 
> `swaymsg bindsym Alt+n exec "swaymsg 'seat \"seat0\" cursor release button1' " `
> 
> This simply binds `Alt+m` into moving the cursor to the specified x-y coordinates and pressing the right button and `Alt+n` into releasing it. More info can be probably found in the sway-input docs. Also refer to this [issue](https://github.com/swaywm/sway/issues/1779) in the swaywm repo.

how can i do it on hyprland
