### ISSUE TITLE
Failed to recursively turn old root mount tree into dependent mount. Continuing...

### ISSUE THREAD

**Issue by Alee14** [waydroid/waydroid#497]
**Describe the bug**
I started the Waydroid container from systemd and the error occurred
**Screenshots**
![image](https://user-images.githubusercontent.com/11698947/186555806-bd2a9a3b-9ac7-4666-aa28-39f8b1cea732.png)
**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0] 1.3.0
 - Waydroid Images Version [e.g. VANILLA 20211021] Latest (Don't really know how to check the version of that)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64] Arch Linux x64
 - GPU: [e.g. AMD Radeon™ RX 5700] AMD Radeon RX 6600
 - Kernel version: [e.g. Generic 5.4.x] 5.19.3-zen1-1-zen
 - Host mesa version: [e.g. mesa 2.2] mesa-22.1.6-1
 - Desktop: [e.g. Gnome 40.x.x] sway 1.7

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

(waydroid_base.prop) https://pastebin.com/afmLEaAQ (GH wouldn't let me upload the file)
[waydroid.log](https://github.com/waydroid/waydroid/files/9420665/waydroid.log)
[waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/9420692/waydroid-logcat.txt)

**Comment by hartmark** [comment]
+1
I get the same error

**Comment by hartmark** [comment]
It seems I loaded the wrong images, loading the latest waydroid images fixed my issue

**Comment by aitorpazos** [comment]
I am getting this error with the following images:

- https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20221231-VANILLA-waydroid_x86_64-system.zip/download

```
(008089) [01:30:40] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(008089) [01:30:40] New background process: pid=8423, output=background
lxc-start: waydroid: ../src/lxc/conf.c: turn_into_dependent_mounts: 3919 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
(008089) [01:30:40] waiting 10 seconds for container to start...
(008089) [01:30:41] Save session config: /var/lib/waydroid/session.cfg
(008377) [01:30:41] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
```

OS: OpenSUSE Tumbleweed
