### ISSUE TITLE
Crash dump on trying to start session and/or launch an app.

### ISSUE THREAD

**Issue by RandomRuskiy** [waydroid/waydroid#498]
**Describe the bug**
When attemping to launch an app, it causes some sort of a crash/hang/dump.

**Screenshots**
![Screenshot_20220824_182557](https://user-images.githubusercontent.com/51451706/186741696-57679547-1988-408c-9a9e-e8f6562a2b41.png)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.0
 - Waydroid Images Version: Don't know how to see this, it would be whatever was the latest vanilla image on the 23rd.

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - GPU: AMD RENOIR (Ryzen 5 4500U Integrated GPU)
 - Kernel version: 5.18.18-200.fc36.x86_64
 - Host mesa version: 22.1.7
 - Desktop: KDE Plasma 5.25.4

**Logs (please upload as file)**
 - Prop file: [waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9427495/waydroid_base.prop.txt)
 - Output of `waydroid log`: [waydroid_log.txt](https://github.com/waydroid/waydroid/files/9427508/waydroid_log.txt)
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services: [waydroid_logcat.txt](https://github.com/waydroid/waydroid/files/9427516/waydroid_logcat.txt)

**Comment by aleasto** [comment]
This is an issue with kernels 5.18.18 and up, fix is awaiting merge

**Comment by aleasto** [comment]
Fix will land in kernel 5.19.6
