### ISSUE TITLE
Android apps frequently crashes

### ISSUE THREAD

**Issue by Echiji** [waydroid/waydroid#499]
**Describe the bug**
I'm not sure if this counts as bug. But anyways, this is my first time using Waydroid.
My issue is the apps frequently crashes, even a simple app like CPU-Z crashes after running for 10 seconds. Not only that, the browser itself also crashes when you tried to paste a link on search box. A lot of stuff are crashing, what surprised me is the game I was planning to install wasn't supported on Waydroid, probably due to arm support.

**Screenshots**
N/A

**General information (please complete the following information):**
- Waydroid version: Latest from Arch repo
- Waydroid Image: Latest Gapps image

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: AMD Radeon Vega 7
 - Kernel version: 5.19.4-arch1-1
 - Host mesa version: 22.1.7
 - Desktop: KDE Plasma 5.25.4

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Arch Linux
 - N/A
 - Kernel version: 5.19.4-arch1-1

**Additional context**
N/A

**Logs (please upload as file)**
No logs

**Comment by kibo1no1shirei-kan** [comment]
pls check with the other issue

**Comment by aleasto** [comment]
Missing information ("No logs"...)

But we should have improved the AMD GPU support with the latest android images
