### ISSUE TITLE
Failed to get service waydroidplatform, trying again...

### ISSUE THREAD

**Issue by frap129** [waydroid/waydroid#50]
Running `waydroid app install path/to/my.apk` results in 
```
[14:08:12] Failed to get service waydroidplatform, trying again...
```
The same goes for `waydroid show-full-ui` and `waydroid app list`

My system is running arch linux, with the waydroid and waydroid-image packages installed, system image is lineage-17.1-20210913-VANILLA-waydroid_x86_64-system.zip with the MAINLINE vendor. 

Waydroid log:
```
(142114) [14:07:33] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(142114) [14:07:33] *** output passed to waydroid stdout, not to this log ***
(142126) [14:07:50] Save session config: /var/lib/waydroid/session.cfg
(142126) [14:07:50] UserMonitor service is not even started
(142126) [14:07:50] Clipboard service is not even started
(140432) [14:07:51] % sudo /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(140432) [14:07:51] % sudo waydroid-sensord /dev/hwbinder
(140432) [14:07:51] New background process: pid=142150, output=background
(140432) [14:07:51] % sudo umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
sudo: waydroid-sensord: command not found
(140432) [14:07:51] % sudo umount /var/lib/waydroid/rootfs/vendor
(140432) [14:07:51] % sudo umount /var/lib/waydroid/rootfs
(140432) [14:07:51] % sudo mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(140432) [14:07:51] % sudo mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(140432) [14:07:51] % sudo mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(140432) [14:07:51] % sudo mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(140432) [14:07:51] % sudo mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(140432) [14:07:51] % sudo chmod 777 -R /dev/ashmem
(140432) [14:07:51] % sudo chmod 777 -R /sys/kernel/debug/sync/sw_sync
(140432) [14:07:51] % sudo chmod 777 -R /dev/dri
(140432) [14:07:51] % sudo chmod 777 -R /dev/fb0
(140432) [14:07:51] % sudo lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(140432) [14:07:51] New background process: pid=142187, output=background
lxc-start: waydroid: utils.c: open_devnull: 1209 No such file or directory - Can't open /dev/null
(140432) [14:07:51] Save session config: /var/lib/waydroid/session.cfg
(142481) [14:08:10] Failed to get service waydroidplatform, trying again...
(142481) [14:08:11] Failed to get service waydroidplatform, trying again...
lxc-start: waydroid: utils.c: open_devnull: 1209 No such file or directory - Can't open /dev/null
(142481) [14:08:12] Failed to get service waydroidplatform, trying again...
```

EDIT: Should have mentioned, my kernel version is 5.13.16

**Comment by rafaelrgazquez** [comment]
I'm having the exact same error. I'm on Manjaro, linux 5.14.0.

**Comment by frap129** [comment]
I use way as my wm of choice, but after reading #32 I decided to try in gnome since I have that installed too. `waydroid show-full-ui` worked for a few seconds before binder died, need to work that one out still

**Comment by MDP43140** [comment]
i also get the same error

**Comment by somefoo** [comment]
Also get the error on PostmarketOS (Alpine) using kernel 5.13.12

**Comment by austinrojers** [comment]
Same here,
These are my logs:
```
19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
```

**Comment by raploz** [comment]
The error was fixed for me after restarting the computer. Check if that works.

**Comment by JoseskVolpe** [comment]
To avoid restarting your computer, if you use SystemD, you can do:
```
sudo systemctl restart lxc
sudo systemctl start waydroid-container
waydroid session start
```

**Comment by BjoernLange** [comment]
I saw the error

```
Failed to get service waydroidplatform, trying again...
```

on Manjaro ARM 5.15.7-3 on the Pinephone (beta 20). For me waiting a moment (maybe a minute or two) after running

```
waydroid session start
```

before running

```
waydroid show-full-ui
```

fixed it.

**Comment by nnuel** [comment]
> Same here, These are my logs:
> 
> ```
> 19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
> 19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
> 19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
> 19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
> ```

Yes, I do have these same errors in `dmesg`.

Did you find a solution @austinrojers for this or is it still not working on your end?

**Comment by austinrojers** [comment]
> > Same here, These are my logs:
> > ```
> > 19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
> > 19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
> > 19/09/21 12:32 PM	init	Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 13 (/system/bin/hwservicemanager)
> > 19/09/21 12:32 PM	init	Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
> > ```
> 
> Yes, I do have these same errors in `dmesg`.
> 
> Did you find a solution @austinrojers for this or is it still not working on your end?

@nnuel, I am not using Waydroid, I am actually not having a pc as of now. Sorry I can’t help here.

**Comment by hungry-thom** [comment]
Had similar issue on pinephone. A kind soul directed me to this solution.

https://github.com/dreemurrs-embedded/Pine64-Arch/issues/273

Downgrading sway and wlroots did the trick for me.
