### ISSUE TITLE
Wi-Fi emulation for some apps

### ISSUE THREAD

**Issue by vyalcevanet** [waydroid/waydroid#501]
Some applications only check for Wi-Fi or Mobile Data types of Internet connection, and do not detect it if the connection is of another type (e.g. Ethernet). I have encountered this on a physical Android device as well. And since the Waydroid connects to the host over a virtual Ethernet network, the network inside it is detected as Ethernet, and is not detected by apps that only check for Wi-Fi or Mobile Data.

Maybe a physical Wi-Fi adapter can be attached to the container with Waydroid? lxc.net.1.type = phys in the LXC configuration. Maybe you can create a dummy Wi-Fi adapter that connects to a virtual network so Android in the container sees the Wi-Fi connection, and use a VPN between the host and the container to actually communicate? I've tried that for internet reverse tethering from computer to phone.

**Comment by vyalcevanet** [comment]
I tried to attach the physical interface wlan0 to the container, Android failed to start.
waydroid logcat:
08-28 22:03:21.911  2904  2978 I WifiScanningService: Created a new impl for wlan0
08-28 22:03:21.911  2904  2978 I WifiScanningService: wifi driver loaded with scan capabilities: max buckets=16
08-28 22:03:21.911    27    27 I hwservicemanager: getTransport: Cannot find entry android.hardware.wifi.supplicant@1.1::ISupplicant/default in either framework or device manifest.
08-28 22:03:21.911  2904  2975 I SupplicantStaIfaceHal: Starting supplicant using init
08-28 22:03:21.911  2904  2904 D ConnectivityModuleConnector: Networking module service start requested
08-28 22:03:21.912  2904  2904 D SystemServerTiming: StartTethering took to complete: 1ms
08-28 22:03:21.912  2904  2904 I SystemServerTiming: MakeCountryDetectionServiceReady
08-28 22:03:21.912  2904  2904 D SystemServerTiming: MakeCountryDetectionServiceReady took to complete: 0ms
08-28 22:03:21.912  2904  2904 I SystemServerTiming: MakeNetworkTimeUpdateReady
08-28 22:03:21.912  2904  2975 W libc    : Unable to set property "ctl.start" to "wpa_supplicant": error code: 0x20
08-28 22:03:21.912  2904  2975 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: WifiHandlerThread

Maybe WiFi is not supported in my image? I used Lineage-OS-18.1-waydroid_x86_64-202111291420-foss-sd-hd-ex_ax86-vaapi_gles-aep.zip based on Android 11.

**Comment by aleasto** [comment]
This is now possible with `persist.waydroid.fake_wifi`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour

**Comment by 0-st** [comment]
> This is now possible with `persist.waydroid.fake_wifi`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour

This does not work

**Comment by ruditimmermans** [comment]
> > This is now possible with `persist.waydroid.fake_wifi`: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour
> 
> This does not work

No indeed a lot of apps dont works anymore on Waydroid for almost more then 6 months i dont understand way the not make the wifi working into Waydroid this will solve this....

**Comment by FirewallDaProtogen** [comment]
fully agree! im using a couple apps that do not work with the persist fake wifi feature
