### ISSUE TITLE
Waydroid, glitches even tho i do not have two gpu

### ISSUE THREAD

**Issue by kibo1no1shirei-kan** [waydroid/waydroid#507]
**Describe the bug**
This sometimes occurs making the application usable.
after the application launch, it glitches due to this it goes back to the home screen
closing other applications, this occurs consistently every 30 seconds during the glitch I can see the background of my pc

**Screenshots**
![image](https://user-images.githubusercontent.com/96419861/187590491-e7ab421b-250e-4a70-8e5f-c8cdf5332e8f.png)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux x86_64 ]
 - GPU: [Intel GeminiLake [UHD Graphics 600] ]
 - Kernel version: [ 5.15.60-1-MANJARO]
 - Host mesa version: [i do not know]
 - Desktop: [kde plasma]

**Logs (please upload as file)**
 - Prop file, 
[waydroid_base.txt](https://github.com/waydroid/waydroid/files/9458396/waydroid_base.txt)

 - Output of `waydroid log
[waydroid_log.txt](https://github.com/waydroid/waydroid/files/9458402/waydroid_base.txt)

**Comment by JamiKettunen** [comment]
Why did you remove these from your issue report? Please edit your issue, add these back and fill them in
```
**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]
```
Also fill in your mesa version (`pacman -Qi mesa`) and mention version of your desktop environment too (`pacman -Qi plasma-desktop`)

**Comment by JamiKettunen** [comment]
That 4 GB RAM isn't too ideal for Waydroid considering you're booting a full Android system on top of your whole Linux desktop... Please try to keep other running applications to a minimum and try again while keeping an eye on the system memory usage.

**Comment by kibo1no1shirei-kan** [comment]
I don't know how to get thos info sorry

**Comment by kibo1no1shirei-kan** [comment]
And am planning to uograde

**Comment by aleasto** [comment]
Please reopen if still reproducible with the latest android images (`sudo waydroid upgrade`), and attach `sudo waydroid logcat` after the crashes happen, as there's nothing i can do with the available information
