### ISSUE TITLE
adb connection refused with waydroid

### ISSUE THREAD

**Issue by partedMagic** [waydroid/waydroid#508]
![scrsh](https://user-images.githubusercontent.com/74645668/188195611-0dc81f87-91b4-46ca-bc94-96c3971f7eeb.png)
I just want it to connect so I can mount the partition and root waydroid with magisk. How can I fix this?

Ubuntu 22.04 
5.15.0

**Comment by Hhk78** [comment]
Go to developer option in waydroid. Open wireless or network debugging.

**Comment by jhay06** [comment]
have the same issue ,  this is failing because , adbd module is crashing on waydroid , waiting for the developer to fix this issue

**Comment by jhay06** [comment]
![image](https://user-images.githubusercontent.com/5191437/188384335-b02305bc-bf7c-40a6-8f5d-f7a1c4528b66.png)

**Comment by aleasto** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/348
