### ISSUE TITLE
[Ubantu 20.04] ERROR: WayDroid is not initialized, run "waydroid init"

### ISSUE THREAD

**Issue by asitgujar2** [waydroid/waydroid#51]
hex0311@Exox64:~$ sudo waydroid init
Run 'waydroid log' for details.
hex0311@Exox64:~$ waydroid log
ERROR: WayDroid is not initialized, run "waydroid init"

it's always the same , it is not initialized even while using in root

Using Zorin os 16 (ubantu 20.04) based (waydroid focal installed)

help if possible , i really want to try it.
Anbox works fine

**Comment by fvroig** [comment]
Same problem here, using Ubuntu 20.04

**Comment by freechelmi** [comment]
Just the same here :-)

**Comment by Student414** [comment]
same

**Comment by nagayev** [comment]
@asitgujar2 Hello.
Are you using X11?

**Comment by Student414** [comment]
> @asitgujar2 Hello.
> Are you using X11?

yes, i am using x11😰😰😰

**Comment by diaevd** [comment]
Same results.

diabolo@veles:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

diabolo@veles:~$ uname -a
Linux veles 5.13.0-16-generic #16~20.04.1-Ubuntu SMP Fri Sep 17 07:06:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

diabolo@veles:~$ gnome-shell --version
GNOME Shell 3.36.9

diabolo@veles:~$ echo $XDG_CURRENT_DESKTOP && echo $XDG_SESSION_DESKTOP && echo $XDG_SESSION_TYPE 
ubuntu:GNOME
ubuntu-wayland
wayland

**Comment by GuaiYiHu** [comment]
Same

**Comment by douyouknow** [comment]
Same, I have no idea

**Comment by erfanoabdi** [comment]
fixed on https://github.com/waydroid/waydroid/commit/9cec7cac9481750a4955c5bbc6c68a218d4635db

**Comment by biswabaral417** [comment]
how to uninstall it i want to remove it ???
`
sudo remove waydroid
ERROR: WayDroid is not initialized, run "waydroid init"
waydroid init 
[10:58:14] ERROR: Action "init" needs root access
[10:58:14] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
`
