### ISSUE TITLE
Pyhton3-pip removing waydroid

### ISSUE THREAD

**Issue by Hhk78** [waydroid/waydroid#510]
I installed with this iso file : `waydroid-linux-debian-bookworm-lineage-17.1-vanilla-amd64_2022-03-15_1121.iso`
I want to install python3-pip to process this project. https://github.com/casualsnek/waydroid_script
But depency problem. :(

Installing python3-pip removes waydroid. 
*turkish system log*
` sudo apt install python3-pip
*******
Aşağıdaki paketler KALDIRILACAK:
  python-pip python3-gbinder waydroid`

KALDIRILACAK=REMOVİNG

can you help me?

**Comment by aleasto** [comment]
I believe `waydroid-linux-debian-bookworm-lineage-17.1-vanilla-amd64_2022-03-15_1121.iso` is meant as a feature showcase and not for people to actually use.

Please just install debian bookworm then install waydroid on it
