### ISSUE TITLE
Missing PID file on Alpine Linux Edge.

### ISSUE THREAD

**Issue by cynicsketch** [waydroid/waydroid#521]
**Describe the bug**
See title. Discovered issue when the waydroid wouldn't start, and I noticed that the waydroid-container service also failed to start.

```
:/home/cysk$ doas rc-service waydroid-container restart -v                     
waydroid-container       |waydroid-container       | * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/waydroid-container start
waydroid-container       | * Starting Waydroid Container Manager ...
waydroid-container       | * supervise-daemon: fopen `/run/waydroid-container.pid': No such file or directory
waydroid-container       | * Detaching to start `/usr/bin/waydroid'                                                                                                                     [ ok ]
:/home/cysk$ 

```

**General information (please complete the following information):**
Waydroid version 1.3.1-r0
Images version not relevant.

**Desktop (please complete the following information):**
 - OS: Alpine Linux Edge
 - GPU: Not relevant
 - Kernel version: Linux 5.15.67-0-lts
 - Host mesa version: Not relevant
 - Desktop: GNOME 42

**Additional context**
Waydroid was working recently. Tried reinstalling Waydroid through the instructions in doc.waydro.id, but it didn't fix the problem.

Followed the pmOS guide for installation, because Alpine is the upstream for pmOS and should theoretically work. (As I said earlier, it **did** work in the past...) https://wiki.postmarketos.org/wiki/Waydroid

I updated my system recently, and the bug became apparent after said update. Not sure if it's cooincidence or causation. Several packages for 'lxc' on Alpine were updated, and I noticed that one package was purged. (not sure what it was, didn't think it would be important at the time)

'waydroid init' has **not** been successfully run.

**Logs (please upload as file)**
 - Prop file: https://pastebin.com/5YABRvgM
 - Output of waydroid log: https://pastebin.com/ZPQ2hydR [Does not seem to have anything useful...]
 - [LOGCAT NON-FUNCTIONAL] See below, I guess...

```
:/home/cysk$ doas waydroid logcat
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
[00:16:45] WayDroid container is 
:/home/cysk$
```
(Yes, it IS cut off like that.)

**Comment by JamiKettunen** [comment]
Distro specific issues such as this one should be reported upstream, in this case at https://gitlab.alpinelinux.org/alpine/aports/-/issues/new.

The packaging itself is at https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/waydroid if you'd be interested in fixing the problem yourself :)

**Comment by aleasto** [comment]
This is an issue with your distribution package.
You can also just run `waydroid container start &` as root
