### ISSUE TITLE
waydroid not opening on weston

### ISSUE THREAD

**Issue by stupid-kid-af** [waydroid/waydroid#522]
waydroid session start
[17:52:43] XDG Session is not "wayland"

Anyone could please show me show to do with photos and output of commands??

**Comment by Quackdoc** [comment]
there is a bug report template, use that please

**Comment by Crazypersonalph** [comment]
I have this same issue (also listen to quackdoc, it helps a lot)

**Comment by stupid-kid-af** [comment]
> I have this same issue (also listen to quackdoc, it helps a lot)
Thanks
Nope,
I fixed it.
