### ISSUE TITLE
Waydroid not starting under Weston, XDG Session is not "wayland"

### ISSUE THREAD

**Issue by Crazypersonalph** [waydroid/waydroid#526]
**Describe the bug**
When you are trying to run the waydroid session under weston, it does not run, instead erroring out with ```XDG Session is not "wayland"```

**Screenshots**
![image](https://user-images.githubusercontent.com/93847055/190837394-6699da34-31b8-4c29-891e-927719fe0b57.png)
This is the output of waydroid container start when trying to run waydroid session start alongside it
![image](https://user-images.githubusercontent.com/93847055/190837422-b7b09774-0a79-4a01-af10-db490e197eb5.png)

**General information:**
 - Waydroid tools Version 1.3.1
 - Waydroid Images Version 17.1-20220723

**Desktop:**
 - OS: Arch Linux x86_64
 - GPU: Intel Iris XE Graphics
 - Kernel version: 5.19.8-zen1-1-zen
 - Host mesa version: 22.1.7
 - Desktop: KDE Plasma 5.25.5

**Smartphone:**
Not exactly sure, using waydroid GAPPS

**Additional context**
Not much else

**Logs**
[propfile.txt](https://github.com/waydroid/waydroid/files/9590816/propfile.txt)
 
[waydroid-log.txt](https://github.com/waydroid/waydroid/files/9590818/waydroid-log.txt)

[logcat.txt](https://github.com/waydroid/waydroid/files/9590822/logcat.txt)

**Comment by Crazypersonalph** [comment]
Also waydroid had been start with ```sudo systemctl enable --now waydroid-container```

**Comment by stupid-kid-af** [comment]
1. install weston (make sure that you have init)
2. open weston
3. open temrinal in weston (top left small icon of terminal)
4. type these commands (in weston termainal):
     `sudo systemctl restart lxc`
     `sudo systemctl start waydroid-container`
     `waydroid session start #without sudo `
     `waydroid show-full-ui #without sudo`

**Comment by stupid-kid-af** [comment]
> **Describe the bug** When you are trying to run the waydroid session under weston, it does not run, instead erroring out with `XDG Session is not "wayland"`
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/93847055/190837394-6699da34-31b8-4c29-891e-927719fe0b57.png) This is the output of waydroid container start when trying to run waydroid session start alongside it ![image](https://user-images.githubusercontent.com/93847055/190837422-b7b09774-0a79-4a01-af10-db490e197eb5.png)
> 
> **General information:**
> 
> * Waydroid tools Version 1.3.1
> * Waydroid Images Version 17.1-20220723
> 
> **Desktop:**
> 
> * OS: Arch Linux x86_64
> * GPU: Intel Iris XE Graphics
> * Kernel version: 5.19.8-zen1-1-zen
> * Host mesa version: 22.1.7
> * Desktop: KDE Plasma 5.25.5
> 
> **Smartphone:** Not exactly sure, using waydroid GAPPS
> 
> **Additional context** Not much else
> 
> **Logs** [propfile.txt](https://github.com/waydroid/waydroid/files/9590816/propfile.txt)
> 
> [waydroid-log.txt](https://github.com/waydroid/waydroid/files/9590818/waydroid-log.txt)
> 
> [logcat.txt](https://github.com/waydroid/waydroid/files/9590822/logcat.txt)

follow those instructions tagged above 
In case if it's not working try with foss (non-gapps)

**Comment by Crazypersonalph** [comment]
I am not home to test this right now, I will get back to you to see if it works

Thanks!

**Comment by Crazypersonalph** [comment]
It does not seem to work, it still says XDG Session is not "wayland"

**Comment by stupid-kid-af** [comment]
> It does not seem to work, it still says XDG Session is not "wayland"

have u opened(commands) this in weston terminal?

**Comment by Crazypersonalph** [comment]
> > It does not seem to work, it still says XDG Session is not "wayland"
> 
> have u opened(commands) this in weston terminal?

Yes

**Comment by Cqjn-zyk** [comment]
I using above command is ok
           .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Inspiron 16 7610 
               `+oooooo:                 Kernel: 5.19.9-zen1-1-zen 
               -+oooooo+:                Uptime: 18 mins 
             `/:-:++oooo+:               Packages: 1532 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 3072x1920, 3072x1728 
          `/+++ooooooooooooo/`           DE: Plasma 5.25.5 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze [GTK3] 
      :osssssss/        osssso+++.       Terminal: terminator 
     /ossssssss/        +ssssooo/-       CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
  `+sso+:-`                 `.-/+oso:    GPU: Intel TigerLake-H GT1 [UHD Graphics] 
 `++:.                           `-/+/   Memory: 5348MiB / 31844MiB

**Comment by Crazypersonalph** [comment]
> I using above command is ok .o+` --------- `ooo/ OS: Arch Linux x86_64 `+oooo: Host: Inspiron 16 7610 `+oooooo: Kernel: 5.19.9-zen1-1-zen -+oooooo+: Uptime: 18 mins `/:-:++oooo+: Packages: 1532 (pacman) `/++++/+++++++: Shell: zsh 5.9 `/++++++++++++++: Resolution: 3072x1920, 3072x1728 `/+++ooooooooooooo/` DE: Plasma 5.25.5 ./ooosssso++osssssso+` WM: KWin .oossssso-````/ossssss+` Theme: [Plasma], Breeze [GTK3] -osssssso. :ssssssso. Icons: [Plasma], breeze [GTK3] :osssssss/ osssso+++. Terminal: terminator /ossssssss/ +ssssooo/- CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz `/ossssso+/:- -:/+osssso+- GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q `+sso+:-` `.-/+oso: GPU: Intel TigerLake-H GT1 [UHD Graphics] `++:. `-/+/ Memory: 5348MiB / 31844MiB

Did you try and copy and paste a neofetch?

**Comment by Cqjn-zyk** [comment]
> 



> > I using above command is ok .o+`---------`ooo/ OS: Arch Linux x86_64 `+oooo: Host: Inspiron 16 7610 `+oooooo: Kernel: 5.19.9-zen1-1-zen -+oooooo+: Uptime: 18 mins `/:-:++oooo+: Packages: 1532 (pacman) `/++++/+++++++: Shell: zsh 5.9 `/++++++++++++++: Resolution: 3072x1920, 3072x1728 `/+++ooooooooooooo/` DE: Plasma 5.25.5 ./ooosssso++osssssso+` WM: KWin .oossssso-````/ossssss+`Theme: [Plasma], Breeze [GTK3] -osssssso. :ssssssso. Icons: [Plasma], breeze [GTK3] :osssssss/ osssso+++. Terminal: terminator /ossssssss/ +ssssooo/- CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz`/ossssso+/:- -:/+osssso+- GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q `+sso+:-` `.-/+oso: GPU: Intel TigerLake-H GT1 [UHD Graphics] `++:. `-/+/ Memory: 5348MiB / 31844MiB
> 
> Did you try and copy and paste a neofetch?

Yes

**Comment by rothn** [comment]
Are you running this from a GUI-based console or over SSH? Judging by the error, it looks like Waydroid expects this to run in a GUI-based session (i.e. as a child process of a window manager, not a text-based shell).

**Comment by Crazypersonalph** [comment]
> Are you running this from a GUI-based console or over SSH? Judging by the error, it looks like Waydroid expects this to run in a GUI-based session (i.e. as a child process of a window manager, not a text-based shell).

Yes, I am. I am on Arch Linux, on the actual machine, with KDE Plasma

**Comment by rothn** [comment]
@Crazypersonalph What do you get from this command in that GUI shell?

`env | grep XDG`

**Comment by luksus42** [comment]
Did you try:
`XDG_SESSION_TYPE=wayland waydroid show-full-ui`

?

**Comment by Cqjn-zyk** [comment]
I  get the issue now, found the env WAYLAND_SOCKET is null, I didn't know why

WL_EXPORT struct wl_display *
wl_display_connect(const char *name)
{
	char *connection, *end;
	int flags, fd;

	connection = getenv("WAYLAND_SOCKET");
//connection is NULL

**Comment by Cqjn-zyk** [comment]
> I get the issue now, found the env WAYLAND_SOCKET is null, I didn't know why,Please help me
> 
> ```
>                    -`
>                   .o+`
>                  `ooo/
>                 `+oooo:
>                `+oooooo:
>                -+oooooo+:
>              `/:-:++oooo+:
>             `/++++/+++++++:
>            `/++++++++++++++:
>           `/+++ooooooooooooo/`           zyk@zyk-L 
>          ./ooosssso++osssssso+`          --------- 
>         .oossssso-````/ossssss+`         OS: Arch Linux x86_64 
>        -osssssso.      :ssssssso.        Host: Inspiron 16 7610 
>       :osssssss/        osssso+++.       Kernel: 5.19.10-zen1-1-zen 
>      /ossssssss/        +ssssooo/-       Uptime: 1 hour, 36 mins 
>    `/ossssso+/:-        -:/+osssso+-     Packages: 1583 (pacman) 
>   `+sso+:-`                 `.-/+oso:    Shell: zsh 5.9 
>  `++:.                           `-/+/   Resolution: 3072x1920, 3072x1728 
>  .`                                 `/   DE: Plasma 5.25.5 
>                                          WM: KWin 
>                                          Theme: [Plasma], Breeze [GTK3] 
>                                          Icons: [Plasma], breeze [GTK2/3] 
>                                          Terminal: terminator 
>                                          CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
>                                          GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
>                                          GPU: Intel TigerLake-H GT1 [UHD Graphics] 
>                                          Memory: 11042MiB / 31844MiB 
> 
>                                                                  
>                                                                  
> ```
> 
> external/wayland/src/wayland-client.c
> 
> ```
>   WL_EXPORT struct wl_display *
>   wl_display_connect(const char *name)
>   {
> 	  char *connection, *end;
> 	  int flags, fd;
>   
> 	  connection = getenv("WAYLAND_SOCKET");
>   //connection is NULL
> ```

I  using error start session , using wayland session start OK

**Comment by aleasto** [comment]
> (100741) [11:04:39] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
> mount: /var/lib/waydroid/rootfs: mount failed: Operation not permitted.

It seems that your distribution is providing broken android images or that you have some permission issue.
Possibly, you're also missing some networking features:
Error: Could not process rule: No such file or directory
> (100741) [11:04:39] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Error: Could not process rule: No such file or directory
;
                                                                                           ^^^^^^^^^^
Failed to setup waydroid-net.

In any case, report downstream, as this is not our issue and unrelated to Wayland/Weston
