### ISSUE TITLE
installation waydroid raspberry pi with ubuntu hirsute

### ISSUE THREAD

**Issue by alain-lnpcrd** [waydroid/waydroid#53]
hello
Installation on raspberry pi 4 with ubuntu hirsute `ARM64`
Then
error message in log :+1: 
Failed to get service waydroidplatform, trying again...
Hervé (I'm French)
`moi@moi-desktop:~$ ps aux | grep waydroid
root        2194  0.2  0.2 276432 23976 ?        Ssl  13:03   0:03 /usr/bin/python3 /usr/bin/waydroid container start
moi         2257  0.2  0.2 128448 23356 ?        Sl   13:03   0:02 /usr/bin/python3 /usr/bin/waydroid show-full-ui
lxc-dns+    2301  0.0  0.0  17820  1788 ?        S    13:03   0:00 dnsmasq --conf-file=/dev/null -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.250.1 --dhcp-range 192.168.250.2,192.168.250.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=waydroid0 --dhcp-leasefile=/var/lib/misc/dnsmasq.waydroid0.leases --dhcp-authoritative
root        2342  0.0  0.0  19740  5220 ?        S    13:03   0:00 sudo lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
root        2344  0.0  0.0   5436  3032 ?        S    13:03   0:00 lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
moi         2419  0.0  0.0 107784  5004 ?        Sl   13:03   0:00 /system/bin/hw/vendor.waydroid.task@1.0-service
moi         2426  0.0  0.0  37556  5212 ?        S    13:03   0:00 /vendor/bin/hw/android.hardware.health@2.0-service.waydroid
moi         2427  0.0  0.0  37324  5024 ?        S    13:03   0:00 /vendor/bin/hw/android.hardware.light@2.0-service.waydroid
moi         2429  0.0  0.0  37320  4892 ?        S    13:03   0:00 /vendor/bin/hw/android.hardware.power@1.0-service.waydroid
moi         2430  0.0  0.0  37492  5076 ?        S    13:03   0:00 /vendor/bin/hw/android.hardware.sensors@1.0-service.waydroid
moi         2431  0.0  0.0  37348  4888 ?        S    13:03   0:00 /vendor/bin/hw/android.hardware.vibrator@1.0-service.waydroid
moi         8867  0.0  0.0  11264   792 pts/0    S+   13:22   0:00 grep --color=auto waydroid
`

**Comment by gyurmogyuri** [comment]
I can install to Arch linux to same machine. But for me still have error message on usage.

**Comment by erfanoabdi** [comment]
for rpi waydroid images need to get rebuilt
with some patches on gralloc and a flag
also revert this : https://github.com/waydroid/android_hardware_waydroid/commit/baa694d427ea65cccdea253a75e15118ead4add4

and add 
```
TARGET_USE_V3D := true
TARGET_USE_V3D_KMSRO := true 
```
to device tree

Personally i don't have rpi device sorry i can't support it

**Comment by vricosti** [comment]
@erfanoabdi I assume you live in Iran, I might send you a raspberry pi 4B to your country but I don't even know if it will arrive.
If you visit Paris let me know I will give you one :-)
I was looking at the price of the raspberry pi and prices are crazy nowadays, almost 200$ only for the raspberry pi alone...

**Comment by rcasta74** [comment]
> for rpi waydroid images need to get rebuilt with some patches on gralloc and a flag also revert this : [waydroid/android_hardware_waydroid@baa694d](https://github.com/waydroid/android_hardware_waydroid/commit/baa694d427ea65cccdea253a75e15118ead4add4)
> 
> and add
> 
> ```
> TARGET_USE_V3D := true
> TARGET_USE_V3D_KMSRO := true 
> ```
> 
> to device tree

@erfanoabdi Hello, what are the patches mentioned?
I'm using manjaro on rpi4 and running `waydroid show-full-ui` no window is displayed; in logcat I can find several times following errors:
```
04-27 13:37:49.323    65    65 E GRALLOC-GBM: failed to create BO, size=1920x1044, fmt=5, usage=4
04-27 13:37:49.323    76   313 E GraphicBufferAllocator: Failed to allocate (1920 x 1044) layerCount 1 format 5 usage b00: 5
04-27 13:37:49.323    76   313 E BufferQueueProducer: [BootAnimation#0] dequeueBuffer: createGraphicBuffer failed
```
I can get it working if I switch to software rendering following the instruction [here](https://wiki.archlinux.org/title/Waydroid), but it is quite slow.

**Comment by aleasto** [comment]
It should be working now on the latest Android 11 based images
