### ISSUE TITLE
https://repo.waydro.id/ broken: 504 Gateway Time-out

### ISSUE THREAD

**Issue by nmschulte** [waydroid/waydroid#533]
https://repo.waydro.id/ is responding with HTTP 504 (Gateway Time-out), though the host is up (responding to ICMP and http:// (404 Not Found), etc.).

**Comment by basanys** [comment]
Same here on Ubuntu 22.04

**Comment by beangeli** [comment]
Experiencing the same

**Comment by lexcroftdev1** [comment]
broken. apt update is throwing error... please fix it

**Comment by ydaniels** [comment]
any update

**Comment by JeffAlBr** [comment]
curl: (22) The requested URL returned error: 504 // and
Failed to fetch https://repo.waydro.id/dists/jammy/InRelease

**Comment by lentas1** [comment]
same 
![image](https://user-images.githubusercontent.com/88710364/195882304-bd7e3031-9e2e-46ea-9941-f10a4f6b9d13.png)

**Comment by nmschulte** [comment]
@lentas1 you should create a new issue as this one has been resolved and yours is different.

That seems to be a GitHub 404 page ... unless something has changed since you posted, this URL is working for me: https://repo.waydro.id/
