### ISSUE TITLE
Setting WayNotif as the default notification handler for waydroid on ubuntu touch

### ISSUE THREAD

**Issue by ghost** [waydroid/waydroid#534]
I have recently found a repository named [WayNotif](https://github.com/FakeShell/WayNotif) by bardia which is a notification script for waydroid on ubuntu touch. I think this script can be useful so can it be set as the default notification handler for waydroid on ubuntu touch?

**Comment by aleasto** [comment]
We do need a notification framework, but i don't think polling dumpsys will be it...

**Comment by aleasto** [comment]
Closing in favour of https://github.com/waydroid/waydroid/issues/211
