### ISSUE TITLE
Failed to load binder driver

### ISSUE THREAD

**Issue by Heus-Sueh** [waydroid/waydroid#535]
**Describe the bug**
ERROR: Binder node "binder" for waydroid not found

**Screenshots**
![image](https://user-images.githubusercontent.com/98482469/192156620-07f0acc1-b1e7-4d10-8cad-1332bda72e6b.png)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021]

**Desktop (please complete the following information):**
 - OS: [e.g. PopOS 22.04 LTS x64]
 - GPU: [e.g. NVIDIA GTX1060]
 - Kernel version: [e.g. 5.19.0-76051900-generic]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome x.x]

**Additional context**
I only followed the steps of the site https://docs.waydro.id/usage/install-on-desktops

**Logs
[waydroid.log](https://github.com/waydroid/waydroid/files/9641377/waydroid.log)

**Comment by LikDev-256** [comment]
It seems you have to install,
[Anbox-Modules](https://github.com/anbox/anbox-modules)

If you're using Arch it is pretty straight forward just install,
`anbox-modules-dkms-git` AUR Package

**I think this should be added to the documentation**

**Comment by Heus-Sueh** [comment]
why waydroid didn't include this along? license?

**Comment by gamer0mega** [comment]
> It seems you have to install,
> [Anbox-Modules](https://github.com/anbox/anbox-modules)

![image](https://user-images.githubusercontent.com/76910135/193101903-730e7d4e-1760-4190-851e-4d60fab5cd69.png)
cant seem to do that on ubuntu 22.04 lts(with a mainline kernel)

**Comment by Quackdoc** [comment]
> why waydroid didn't include this along? license?

anbox-modules is a separate project and quite outdated, I would send a request to POP os to add support for binder in their kernel builds

**Comment by wesleifreitas** [comment]
Not working: kernel 5.19.11 :(

**Comment by tester1969** [comment]
neither 5.19.16. Isn't any workaround on this? What i have googling are very complicated and I don't want to break my machine

**Comment by aleasto** [comment]
Waydroid requires the binder kernel module. You can compile the module or refer to your distro.
