### ISSUE TITLE
waydroid doesnt work with powervr/omap

### ISSUE THREAD

**Issue by MightyM17** [waydroid/waydroid#54]
Tried waydroid on samsung-espresso3g on pmOS, and it didnt seem to run.
Checking the logcat, I get
```
09-17 18:20:42.303   237   237 I SurfaceFlinger: Phase offset NS: 2000000
09-17 18:20:42.303   237   237 D RenderEngine: RenderEngine GLES Backend
09-17 18:20:42.314   237   237 D libEGL  : loaded /vendor/lib/egl/libGLES_mesa.so
09-17 18:20:42.409   237   237 W EGL-MAIN: MESA-LOADER: failed to open pvr: dlopen failed: library "/vendor/lib/dri/pvr_dri.so" not found (search paths /vendor/lib/dri)
09-17 18:20:42.413   237   237 W EGL-MAIN: MESA-LOADER: failed to open omapdrm: dlopen failed: library "/vendor/lib/dri/omapdrm_dri.so" not found (search paths /vendor/lib/dri)
09-17 18:20:42.413   237   237 W EGL-MAIN: Failed to open any DRM device
09-17 18:20:42.423   237   237 W EGL-MAIN: Failed to open any DRM device
09-17 18:20:42.424   237   237 W libEGL  : eglInitialize(0xb6a2c600) failed (EGL_NOT_INITIALIZED)
09-17 18:20:42.427   237   237 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 237 (surfaceflinger), pid 237 (surfaceflinger)
09-17 18:20:42.468   242   242 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
09-17 18:20:42.468   101   101 I /system/bin/tombstoned: received crash request for pid 237
09-17 18:20:42.469   242   242 I crash_dump32: performing dump of process 237 (target tid = 237)
```

Looks like the mesa waydroid is using misses powervr files.

**Comment by erfanoabdi** [comment]
powervr is not supported on waydroid mesa
even if it was, you needed bionic built blobs inside waydroid which matches your hardware and firmware and host blobs DDK

**Comment by MightyM17** [comment]
PowerVR for now is on 1.17 DDK, I don't think any updates for it are going to come now (atleast not soon), pmOS uses the latest 1.17 + wayland anyways so should be easier to get support.

**Comment by erfanoabdi** [comment]
We have Android blobs for 1.17?
Anyway i don't want to add official pvr support
But I'll help you to build custom waydroid vendor with pvr support

**Comment by MightyM17** [comment]
https://github.com/airend/android_hardware_ti_omap4/tree/OZ/rebase I actually dont know from where he got this source, iirc its in some hardware-ti-open git repo, cannot seem to find it

**Comment by MightyM17** [comment]
@erfanoabdi http://git.omapzoom.org/?p=device/ti/proprietary-open.git here found it
