### ISSUE TITLE
repo.waydro.id 404 not found

### ISSUE THREAD

**Issue by MinGW32-2006** [waydroid/waydroid#540]
**Describe the bug**
I can't reach repo.waydro.id, and it says 404.

**Screenshots**
![2022-10-02 15-17-50 的屏幕截图](https://user-images.githubusercontent.com/111475297/193442831-7ba68673-bdeb-4c80-8240-4cf4fa4c4107.png)

**Additional context**
I'm in China.

So how can I install waydroid? Are there any mirrors?

**Comment by aleasto** [comment]
You must use https.
You also shouldn't have to browse it manually.

**Comment by MinGW32-2006** [comment]
Thanks. It's solved.

**Comment by lentas1** [comment]
i have same on  finland, (network is elisa

**Comment by lentas1** [comment]
![image](https://user-images.githubusercontent.com/88710364/195882030-5b464282-703f-42fb-83a5-4d764e024089.png)

**Comment by lentas1** [comment]
and galaxy s7 install not work
