### ISSUE TITLE
Waydroid lost network connection.

### ISSUE THREAD

**Issue by rolf-ewald** [waydroid/waydroid#541]
Waydroid lost network connection.

I installed Waydroid on Kubuntu22.04 (without wifi card, with cable network card) and F-Droid. The first time I ran F-Droid the list of applications appeared, the internet browser also worked. Now there is no more access to the network and the internet. In the android settings the wi-fi appears disabled and it is not possible to activate it. Can you please help me to solve it (I'm a user with no computer knowledge)? Thank you very much in advance. (Text translated from Portuguese [Brazil] to English by google).

**Comment by aleasto** [comment]
WiFi is not supposed to be turned on inside Android.

Missing debugging informations, cannot reproduce
