### ISSUE TITLE
Unable to Update or install some apps

### ISSUE THREAD

**Issue by ACR-Jeff** [waydroid/waydroid#543]
**Describe the bug**
Unable to update or install some apps, After trying to update or install some apps I get a message "App not installed".
One of the main apps that won't upgrade/update is "SmartTubeNext"
A few of the apps I noticed that won't install at all "MX Player" and "Kodi"

**General information (please complete the following information):**
 - Waydroid Version 13.3

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm 
 - GPU: intel 5906
 - Kernel version: 5.16.0-4-amd64
 - Desktop: Gnome 42.3.1

**Additional context**
Not much else I can say about this issue. It's got limited information from the installer.

**Logs (please upload as file)**
[waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/9721137/waydroid-logcat.txt)
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9721138/waydroid_base.prop.txt)

**Comment by aleasto** [comment]
You may only install applications compatible with your cpu architecture, probably x86_64, but most apps are only compiled for ARM. SmartTubeNext used to be compiled for both, but now is only compiled for ARM so you may not update.

If you want to emulate ARM on x86_64, you can look at libhoudini: https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation
