### ISSUE TITLE
Waydroid container locks up/freezes on PinePhone Manjaro

### ISSUE THREAD

**Issue by CalcProgrammer1** [waydroid/waydroid#55]
I'm using waydroid from AUR, build up to date.  I have the service running and can start the Android UI upon powering on the phone.  I can then open Android apps and they work great.  However, if I turn off the screen and leave the phone for any significant amount of time (~30 minutes or more?), the Android container freezes and any apps I had open are unresponsive.  I cannot close the windows for these locked apps and cannot open new apps.  The container shows as frozen in waydroid status.  I have to restart the service, then re-open the Android UI and watch it boot again before I can reopen any apps.

**Comment by CalcProgrammer1** [comment]
Setting these properties seems to fix it, but probably at the expense of background CPU usage and battery life:

waydroid prop set persist.waydroid.no_suspend true

waydroid prop set persist.waydroid.suspend false

Got these looking at recent commits to the other Waydroid projects.

**Comment by erfanoabdi** [comment]
suspend feature is disabled by default and freeze issues fixed

to enable suspend use this: `waydroid prop set persist.waydroid.suspend true`
