### ISSUE TITLE
404 on waydroid init

### ISSUE THREAD

**Issue by nerd7473** [waydroid/waydroid#551]
https://ota.waydro.id/vendor/waydroid_arm64/HALIUM_11.json
Is not available

**Comment by axelsimon** [comment]
Experiencing the same. In fact, it's the whole of https://ota.waydro.id/ that's 404.

This also shines a light on the fact that the `waydroid init` sequence is not documented.

**Comment by aleasto** [comment]
Halium 11 is not supported yet

**Comment by axelsimon** [comment]
I'm not sure this is relevant, given the 404 is on ota.waydro.id in its entirety.
When starting Waydroid graphically on Fedora 36, for instance, i get a 404 (of course) both on trying to download the vanilla or gapps version of Lineage:
```
Waiting for waydroid container service...
Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
```

```
Waiting for waydroid container service...
Failed to get system OTA channel: /lineage/waydroid_x86_64/GAPPS.json, error: -1

```

So initialising Waydroid is impossible.

**Comment by aleasto** [comment]
> I'm not sure this is relevant, given the 404 is on ota.waydro.id in its entirety.

That's not how http works

> When starting Waydroid graphically on Fedora 36, for instance, i get a 404 (of course) both on trying to download the vanilla or gapps version of Lineage:
> ```
> Waiting for waydroid container service...
> Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
> ```
> 
> ```
> Waiting for waydroid container service...
> Failed to get system OTA channel: /lineage/waydroid_x86_64/GAPPS.json, error: -1
> 
> ```
> 
> So initialising Waydroid is impossible.

There's no 404 in your log.
Follow the instructions at https://waydro.id/#quick-install-reference or https://docs.waydro.id/usage/install-on-desktops#fedora (the copr homepage has install instructions)

**Comment by MinGW32-2006** [comment]
Try switching to waydroid.bardia.tech

**Comment by aleasto** [comment]
HALIUM 11 is now supported

**Comment by axelsimon** [comment]
Thanks for trying to help, aleasto.

> That's not how http works

That's a good point, i forgot you can serve nothing on the root and yet serve stuff at a path.

I'm still unable to  initialise Waydroid, either with `sudo waydroid init` or the GUI. I'll open a new issue to track that.
