### ISSUE TITLE
Support zwp_idle_inhibit_manager_v1

### ISSUE THREAD

**Issue by Quackdoc** [waydroid/waydroid#552]
**Is your feature request related to a problem? Please describe.**
Currently waydroid doesn't seem to tell the host not to idle. wayland has a solution for this called [zwp_idle_inhibit_manager_v1](https://wayland.app/protocols/idle-inhibit-unstable-v1#zwp_idle_inhibit_manager_v1)

if the android guest is operating, we probably want some way to prevent idling, (user reported in the telegram the screen would shut off while they are watching shows using some android apps via waydroid with plasma wayland).

currently the protocol is in unstable, but has not had any activity in a long time so it's "unstable". 

Kwin and wlroots both support it, mutter does not. however if support is introduced, waydroid will not be alone in having this issue be specific to mutter based compositors as high profile apps such as VLC and MPV have both support this protocol.

**Comment by aleasto** [comment]
I don't think we want to prevent sleep unconditionally

**Comment by Quackdoc** [comment]
I was thinking if possible, if we could use the android's idle, so can create the inhibitor and destroy it when android's idle kicks in. 

not entirely sure how Android handles idle though, so I'm not sure how creating the inhibitor again would work. not sure if android has events for idle state ending.

**Comment by aleasto** [comment]
Done through https://github.com/waydroid/android_vendor_waydroid/commit/4b743d7256250c1536e5caa52b80988ee0b8a805 and https://github.com/waydroid/android_hardware_waydroid/commit/720b67777dc2d8c0a93f2c8813c8be062ed5116e

GNOME does not support the wayland interface.
Mir2.x does but Mir1.8 does not.

So effectively this is only currently working in KWin and Sway

**Comment by TriMoon** [comment]
TIP, See: `man systemd-inhibit`, no need to be window-manager specific, just let systemd take care of stuff :wink: 

Example on my Kubuntu 23.04:
```console
$ systemd-inhibit --list

WHO                          UID  USER     PID  COMM            WHAT                                                                       WHY                                                        MODE
ModemManager                 0    root     1288 ModemManager    sleep                                                                      ModemManager needs to reset devices                        delay
NetworkManager               0    root     1239 NetworkManager  sleep                                                                      NetworkManager needs to turn off networks                  delay
UPower                       0    root     1567 upowerd         sleep                                                                      Pause device polling                                       delay
Unattended Upgrades Shutdown 0    root     1363 unattended-upgr shutdown                                                                   Stop ongoing upgrades or perform upgrades before shutdown  delay
PowerDevil                   1000 <zapped> 2091 org_kde_powerde handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch KDE handles power events                                   block
Screen Locker                1000 <zapped> 2012 ksmserver       sleep                                                                      Ensuring that the screen gets locked before going to sleep delay

6 inhibitors listed.
```
