### ISSUE TITLE
Clipboard does not work on Ubuntu Touch (Unity/Lomiri)

### ISSUE THREAD

**Issue by Talkless** [waydroid/waydroid#556]
**Describe the bug**

Number of Ubuntu Touch users, including me, complain that Cliboard from/to Waydroid<->Ubuntu Touch does not work:

https://forums.ubports.com/topic/7986/waydroid-clipboard-broken-permanently

One user noted that using older image fixed the issue.

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.0
 - Waydroid Images Version - not sure how to get image version. Vendor type: HALLIUM_10

**Smartphone (please complete the following information):**
 - Device: Volla Phone X
 - OS: Ubuntu Touch OTA-23
 - Mainline or Halium - not sure
 - Kernel version: 4.9.190+

**Comment by Talkless** [comment]
It seems past'ing does not work within Android itself either. If I copy something in other app, I cannot paste it into K9 mail, but even if I copy anything in K9 I cannot paste it back to K9. Long-press popup simply suggest to Cut/Copy/Share/Replace.. but never Paste.

**Comment by JamiKettunen** [comment]
https://github.com/spyoungtech/pyclip is not a package in Ubuntu Touch repos, I'm planning to change that with https://gitlab.com/ubports/development/core/packaging/waydroid/-/issues/6 unless something goes wrong during testing. I'll also have to check out the copy paste in between Android apps as well..

**Comment by aleasto** [comment]
I had not realized we broke the android clipboard when pyclip isn't installed. Fixed in https://github.com/waydroid/android_vendor_waydroid/commit/8a8cfada1b280f41186cab17f00f59a10cf8209d

**Comment by dreamweaverit** [comment]
hi, I'm now a developer, I hope I'm not totally wrong writing this comment (let me know otherwise). I just jumped on ubuntu touch. I bought a Pixel 3A, installed UT, and then Waydroid through the helper. Copy and paste work inside waydroid, but not between waydroid and ubuntu, unfortunately. Hoping someone can look into it once more.
