### ISSUE TITLE
Failed to get service waydroidplatform, trying again...

### ISSUE THREAD

**Issue by zainbits** [waydroid/waydroid#56]
On executing the following command in terminal I am getting this output.
Command:  "waydroid show-full-ui"
Output: "Failed to get service waydroidplatform, trying again...".
OS: Ubuntu 21.04 hirsute

**Comment by NXij** [comment]
Are you on Wayland?

**Comment by zainbits** [comment]
Yes.

**Comment by zainbits** [comment]
Yes
