### ISSUE TITLE
Cannot install/update play store apps

### ISSUE THREAD

**Issue by ChemicalXandco** [waydroid/waydroid#561]
**Describe the bug**
I have set up everything as necessary including registering the id for the google play services. When I try to install or update and app in the google play store it loads for a second then it goes back to how it was for a start; nothing happens. Other than that, everything else seems to work fine.

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3
 - Waydroid Images Version lineage-17.1-20220723-GAPPS

**Desktop (please complete the following information):**
 - OS: PostmarketOS edge
 - platform: aarch64
 - GPU: using software rendering
 - Kernel version: linux-rpi4 5.15.75
 - Host mesa version: 22.2.2
 - Desktop: sway 1.7
 - root filesystem: btrfs

**Additional context**

The most interesting line from the logcat is
`[2] acpi.i(5): EFD: Error creating /storage/emulated/0/Android/data/com.android.vending/files/installer`

I did a quick investigation into this, and I found the directory looks like this for an install that works:
```
:/ # ls -la /storage/emulated/0/Android/data/
total 20
drwxrwx--x 5 root    sdcard_rw 4096 2022-10-01 12:10 .
drwxrwx--x 4 root    sdcard_rw 4096 2022-10-01 12:10 ..
-rw-rw---- 1 root    sdcard_rw    0 2022-10-01 12:10 .nomedia
drwxrwx--x 3 u0_a108 sdcard_rw 4096 2022-10-01 12:10 com.android.vending
drwxrwx--x 3 u0_a92  sdcard_rw 4096 2022-10-01 12:10 com.google.android.gms
drwxrwx--x 3 u0_a100 sdcard_rw 4096 2022-10-01 12:10 com.google.android.googlequicksearchbox
```

For the one that doesn't work, it looks like this:
```
:/ # ls -la /storage/emulated/0/Android/data/
total 0
drwx------ 5 root root 100 2022-10-29 09:00 .
drwx------ 3 root root  60 2022-10-29 08:39 ..
drwx------ 3 root root  60 2022-10-29 09:00 com.android.vending
drwx------ 3 root root  60 2022-10-29 08:39 com.google.android.gms
drwx------ 3 root root  60 2022-10-29 08:40 com.google.android.googlequicksearchbox
```

Additionally, it does not persist after a reboot:
```
:/ # ls -la /storage/emulated/0/Android/data/
total 0
drwx------ 3 root root 60 2022-10-29 10:46 .
drwx------ 3 root root 60 2022-10-29 10:46 ..
drwx------ 3 root root 60 2022-10-29 10:46 com.google.android.gms
```

The one that does work has the following characteristics:

platform: x86 QEMU vm
operating system: arch linux
kernel: linux-zen
root filesystem: ext4

Other than that they should be mostly the same. When I have more time I will see if I can narrow down which difference is causing the problem.

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9893636/waydroid_base.prop.txt)

 - Output of `waydroid log`
[waydroid_log.txt](https://github.com/waydroid/waydroid/files/9893638/waydroid_log.txt)

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
[waydroid_logcat.txt](https://github.com/waydroid/waydroid/files/9893639/waydroid_logcat.txt)

**Comment by aleasto** [comment]
Does it happen again if you `sudo rm -rf ~/.local/share/waydroid`?

**Comment by ChemicalXandco** [comment]
> Does it happen again if you `sudo rm -rf ~/.local/share/waydroid`?

yes

**Comment by ChemicalXandco** [comment]
>Is the broken installation running root as the main user?

No and I will need to investigate further what the cause of this is because I need to eliminate some variances in the configuration.

**Comment by ChemicalXandco** [comment]
I have done some further testing and I have now got it working on NixOS. The main difference between NixOS and PostmarketOS is that the latter uses the raspberry pi kernel whereas the former uses the upstream kernel so I should think that is what was causing the problem.
