### ISSUE TITLE
Waydroid failed to start

### ISSUE THREAD

**Issue by chiragnahata** [waydroid/waydroid#562]
![image](https://user-images.githubusercontent.com/63905783/198833041-636d71f0-c2b3-4e07-9bc8-a604f7fc19d9.png)
![image](https://user-images.githubusercontent.com/63905783/199293586-d68835dd-f753-4b0f-8b13-2eafc8edd250.png)
![image](https://user-images.githubusercontent.com/63905783/199293625-70a4217e-23e1-48d2-81d5-f40501abafb6.png)
![image](https://user-images.githubusercontent.com/63905783/199293658-a54f8b68-e580-4735-ab11-c21444a733a7.png)
![image](https://user-images.githubusercontent.com/63905783/199293692-5e9e96a9-3f4e-4759-b82b-f9941b6031bd.png)
![image](https://user-images.githubusercontent.com/63905783/199293738-962e45e8-eacd-40c0-9698-97e346571060.png)

Ubuntu arm64
Oracle Always Free

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/198833424-14985224-c1ce-474e-87c8-f08a7078755c.png)

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/198833461-6f7f9b71-e650-4b40-bfe2-e8f7d5dc6e91.png)
![image](https://user-images.githubusercontent.com/63905783/198833475-32229941-cc75-4f6b-9643-36b21bb1f5b2.png)

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/199292370-d676e80e-1332-4ca9-aa8b-7a184c80a687.png)

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/199293223-3f64ebc1-5063-4c97-bd91-e16812c0c4ae.png)

**Comment by lazbar1** [comment]
helllo
please let me know if you found a solution i have been trying to install it too in arm oracle too for the passt month and had no lucj

**Comment by aleasto** [comment]
Waydroid requires the binder kernel module. You can compile the module or refer to your distro.
