### ISSUE TITLE
Official Lineage 18.1 Image fails to start

### ISSUE THREAD

**Issue by j-lgs** [waydroid/waydroid#567]
**Describe the bug**
The official image for waydroid was updated to Lineage 18.1 last week. With this the session fails to start when 17.1 worked.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3
 - Waydroid Images Version 20221030-GAPPS

**Desktop (please complete the following information):**
 - OS: NixOS
 - GPU: Radeon RX 67090XT
 - Kernel version: 5.18.14-zen1
 - Host mesa version: mesa 22.0.4
 - Desktop: Plasma Wayland 5.24.5

**Additional context**
# Steps to reproduce
## Failure, using 18.1 image that downloads by default
```
$ sudo systemctl stop waydroid-container
$ sudo rm -rdf ~/.local/share/waydroid/*
# change images_path in waydroid.cfg /var/lib/waydroid/images
$ sudo waydroid upgrade
$ sudo waydroid init -f
# change waydroid_base.prop to use software rendering
# ro.hardware.gralloc = default
# ro.hardware.egl = swiftshader
$ sudo systemctl start waydroid-container
$ waydroid session start
> [16:50:10] Failed to add service waydroidusermonitor: -2147483647
> [16:50:10] Failed to add service waydroidclipboard: -2147483647
# In the container's journal
> Nov 03 16:50:09 hostname waydroid[40423]: [16:50:09] Failed to add service waydroidhardware: -2147483647
> Nov 03 16:50:09 hostname waydroid[40423]: [16:50:09] Failed to add service waydroidhardware: -2147483647
```

## Success, using 17.1 image downloaded from waydroid's sourceforge
```
# Download 17.1 system and vendor images to /usr/share/waydroid-extra/images
$ sudo systemctl stop waydroid-container
$ sudo rm -rdf ~/.local/share/waydroid/*
# change images_path in waydroid.cfg /usr/share/waydroid-extra/images
$ sudo waydroid upgrade
$ sudo waydroid init -f
# change waydroid_base.prop to use software rendering
# ro.hardware.gralloc = default
# ro.hardware.egl = swiftshader
$ sudo systemctl start waydroid-container
$ waydroid session start
> [17:14:24] Android with user 0 is ready
```

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
   [waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9926015/waydroid_base.prop.txt)
 - Failed run log
   [waydroid-18.1-fail.log](https://github.com/waydroid/waydroid/files/9926021/waydroid-18.1-fail.log)
 - Successful run log
   [waydroid-17.1-success.log](https://github.com/waydroid/waydroid/files/9926022/waydroid-17.1-success.log)
 - Failed run logcat
   [waydroid-18.1-fail-logcat.log](https://github.com/waydroid/waydroid/files/9926029/waydroid-18.1-fail-logcat.log)
 - Successful run logcat
   [logcat17.log](https://github.com/waydroid/waydroid/files/9926030/logcat17.log)

**Comment by aleasto** [comment]
Searching the NixOS package repository I only see Waydroid 1.2.0
How did you get Waydroid 1.3.3?

**Comment by j-lgs** [comment]
1.3.3 is available in the unstable channel.

**Comment by aleasto** [comment]
Ok. The other dependencies need to be updated as well. Namely `python-gbinder` and `libgbinder`

**Comment by aleasto** [comment]
Closing this as packaging issue.
