### ISSUE TITLE
Wrong way to add gpg key and sources-list in ubuntu 21.04 listed in official web site

### ISSUE THREAD

**Issue by LedBass** [waydroid/waydroid#57]
Hi guys,

Following the "how to" steps to install WayDroid at https://waydro.id/#howto in Ubuntu 21.04 I have faced a "permission denied" to add both gpg key and sources.list file

PROBLEM:

Per the installation guide at https://waydro.id/#howto, we should run the commands bellow to install WayDroid:

```
$export DISTRO="bullseye" && \
curl https://repo.waydro.id/waydroid.gpg > /usr/share/keyrings/waydroid.gpg && \ 
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" > /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
```
However, it givers the following error message in Ubuntu 21.04:
```
bash: /usr/share/keyrings/waydroid.gpg: Permissão negada (translation from portuguese -> permission denied)
bash: /etc/apt/sources.list.d/waydroid.list: Permissão negada (translation from portuguese -> permission denied)
```

SOLUTION

Per Debian documentation, this is the recommended approach to add gpg key and source.list file:  
```
export DISTRO="bullseye" && \ 
wget -O- -q https://repo.waydro.id/waydroid.gpg | sudo tee /usr/share/keyrings/waydroid.gpg && \
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
```
In both scenarios I replaced "bullseye" with "hirsute" to match my distro

P.s.: I used wget just for personal preference

**Comment by Ahmed-E-86** [comment]
I was pulling my hair off. That worked without any issues. Thanks!

**Comment by yjftsjthsd-g** [comment]
What's particularly odd is that the last part is listed as `sudo apt update`; either you're running as root and can write to `/usr/share/keyrings` (in which case you can run apt without sudo), or you're running as a normal user, in which case you need sudo to write to keyrings (usually with the tee trick used above).

**Comment by awal1984** [comment]
I tried to install too, but it fails. What can I do? In the image you can see what I did.[](url
![export_distro_fail](https://user-images.githubusercontent.com/104687725/166112262-079f9fa2-3640-4a42-9f64-9468302426a1.jpg)
)

**Comment by cniw** [comment]
```
DISTRO=hirsute

[[ ! -f /usr/bin/curl ]] && sudo apt install -y curl
sudo curl https://repo.waydro.id/waydroid.gpg -o /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=${_}] https://repo.waydro.id/ ${DISTRO} main" | \
sudo tee /etc/apt/sources.list.d/waydroid.list

sudo apt update
sudo apt install -y waydroid
```

**Comment by aleasto** [comment]
Fixed
