### ISSUE TITLE
[Feature Request] Faking Device model /brands

### ISSUE THREAD

**Issue by jhay06** [waydroid/waydroid#570]
hi , would like to request if this posible . 
to add device/brands  model changer like build.prop editor . but for waydroid without the need of root access . maybe on waydroid helper/settings app  ? 

because theres some app that require a brand and a model which is already known . found this concern on specific playstore apps compatibility, i looked at about app and my android device listed on which device works and not. and found waydroid_x86_64 on the device that will not work.  this is weird . because i have asus prehistoric x86 phone. zenfone 2 to be specific . but the device is listed as working device. so i believe this is because waydroid is considered by the app not known device so it considered as emulator device

**Comment by aleasto** [comment]
You can set `ro.product.waydroid.brand`, `ro.product.waydroid.device`, `ro.product.waydroid.manufacturer`, `ro.product.waydroid.model`, `ro.product.waydroid.name` in `/var/lib/waydroid/waydroid.cfg` under the `[properties]` section, then run `sudo waydroid upgrade -o`
