### ISSUE TITLE
Virtualization for running on devices with 16K pages

### ISSUE THREAD

**Issue by Donkey-Doug** [waydroid/waydroid#577]
**Is your feature request related to a problem? Please describe.**
Hi, so this is probably a long shot, but I decided to make the issue anyway.

There are devs currently reverse engineering Apple M-hardware to run linux. The project is called Asahi linux. Apple uses 16K pages instead of the 4K pages Android uses. Due to this difference in page sizes, usage of waydroid on for example an Apple m1 macbook running linux won't work.

**Describe the solution you'd like**
I think virtualization is needed in order to get 4K pages android apps run on 16K pages hardware. It would be nice if such feature could be built into waydroid.

**Describe alternatives you've considered**
I could use an actual VM, but the beauty of waydroid is that android apps are shown in the app list/overview with the native linux apps. I really like this level of integration.

**Comment by aleasto** [comment]
That's way out of scope.
However, there's active development in upstream AOSP to support 16k pages. So in some future version of android this will be possible.

Of course, your alternative is to compile a 4K kernel for those machines.

**Comment by marcan** [comment]
FYI, 4K kernels are not currently supported, as the IOMMUs and GPU only support 16K pages and the kernel needs significant more work to be able to use them with 4K CPU pages. So no, you can't compile a 4K kernel for these machines.

**Comment by supechicken** [comment]
See https://github.com/waydroid/waydroid/issues/2185#issuecomment-4373901742, someone got Waydroid working on Asahi
