### ISSUE TITLE
Program sleeps infinitly during container start

### ISSUE THREAD

**Issue by Mar2ck** [waydroid/waydroid#58]
After running `sudo waydroid container start` during the installation process, the program sleeps endlessly with no output. Killing it with CTRL+C gives:
```
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 110, in start
    time.sleep(1)
KeyboardInterrupt
```

In the container_manager.py file, the program is reaching the line `while not os.path.exists(tools.config.session_defaults["config_path"]):` and since the path doesn't exist the while loop never breaks so it just sleeps forever. I'm not sure what the intended behavior is supposed to be.

**Comment by AryToNeX** [comment]
you'd have to start a session in a separate terminal; remember to not use sudo to do it

`waydroid session start`

**Comment by CalcProgrammer1** [comment]
If your distro uses systemd it should provide a systemd service you can enable

sudo systemctl enable waydroid-container.service

You can replace enable with disable, start, stop, and restart.  Enabled means it autostarts on boot.

Start the service and then do waydroid show-full-gui or use the Waydroid application from your start menu.

What distro?  You also need binder support in the kernel.
