### ISSUE TITLE
Initializing Waydroid on UT with a certain version of Halium downloads incorrect Waydroid system image 

### ISSUE THREAD

**Issue by zubozrout** [waydroid/waydroid#583]
When running `waydroid init` on UT (in my case a Hallum 10 phone) incorrect system image is downloaded, but vendor image is correct:

```
root@ubuntu-phablet:~# waydroid init -s GAPPS # same results without -s GAPPS
[15:28:36] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20221110-GAPPS-waydroid_arm64-system.zip/download
[15:36:11] Validating system image
[15:36:12] Extracting to /var/lib/waydroid/images
[15:36:41] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/lineage-17.1-20221109-HALIUM_10-waydroid_arm64-vendor.zip/download
[15:38:30] Validating vendor image
[15:38:30] Extracting to /var/lib/waydroid/images
```

That means I am unable to run Waydroid on my device since recently and I have not been able to make it work even with images downloaded manually.

Is there a way to specify what Lineage OS version Waydroid should download?
I wasn't able to find anything useful neither in the docs nor while Googling.

This is ultimately leading this guide incorrect/non functional:
https://forums.ubports.com/topic/6764/anbox-halium-or-waydroid-no-support-for-ut/11

**General information:**
 - Waydroid tools Version: 1.2.0

**Smartphone:**
 - Device: [Xiaomi Redmi Note 9 Pro](https://devices.ubuntu-touch.io/device/joyeuse/)
 - OS: Ubuntu touch 16.04, devel (2022-11-11)
 - Halium 10
 - Kernel version: 4.14.288-halium+

**Logs**
```
phablet@ubuntu-phablet:~$ waydroid session start
[15:44:26] XDG Session is not "wayland"
[15:44:26] Failed to start Clipboard manager service, check logs
[15:44:26] Failed to add service waydroidusermonitor: -2147483647
```

**Comment by zubozrout** [comment]
This is the content of the waydroid.cfg btw:

```
[waydroid]
images_path = /home/phablet/Downloads/waydroid/
system_datetime = 0
vendor_datetime = 0
arch = arm64
vendor_type = HALIUM_10
system_ota = http://ota.waydro.id/system/lineage/waydroid_arm64/GAPPS.json
vendor_ota = http://ota.waydro.id/vendor/waydroid_arm64/HALIUM_10.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
```

And running Waydroid upgrade or init -f is still trying to download Lineage 18 despite Halium 10 likely not being compatible :(

**Comment by zubozrout** [comment]
But fortunately it seems changing that GAPPS/VANILLA.json link to a custom one where Lineage 18 is removed from the list actually allows me to install and run Waydroid again.

```
waydroid init -f -s GAPPS -c https://zubozrout.cz/data/waydroid
```

Which then tries to download the JSON from this link on my phone:
https://zubozrout.cz/data/waydroid/lineage/waydroid_arm64/GAPPS.json (or VANILLA.json)

But it is still very weird downloading system and vendor images, extracting the download zip archives to a certain folder and running `waydroid init -i /path/to/where/the/images/are/downloaded` doesn't work for me and Waydroid still downloads the images from SourceForge. Also, sadly replacing the images in `/var/lib/waydroid/images` didn't fix Waydroid for me either even if executing `waydroid init` after the file overwrite :thinking:.

**Comment by aleasto** [comment]
Waydroid only supports loading distro or user provided images from `/usr/share/waydroid-extra/images` (or `/etc/waydroid-extra/images` in waydroid >= 1.3.3). You just put system.img and vendor.img there and run `waydroid init -f` without `-i <path>`.
`-i <path>` specifies the path where waydroid should download the images from OTA into. Different thing.

As for your actual issue, Ubuntu Touch ships a version of the waydroid package (and dependencies) too old to support Android 11 (Lineage 18) out of the box. For Halium 10 the temporary workaround is `sed '/aidl/s/2/3/' -i /etc/gbinder.d/anbox.conf`
