### ISSUE TITLE
How to rotate app window?

### ISSUE THREAD

**Issue by Ebraama06** [waydroid/waydroid#584]
![Screenshot from 2022-11-11 16-46-21](https://user-images.githubusercontent.com/81094849/201364678-ba6630f1-4c7f-4676-b4c1-a9790e02b22b.png)
after trying a lot I get this and inverted mouse movement. 
I just want to open vertical app correctly and resize the window how do I do it?

**Comment by Ebraama06** [comment]
and i tried F11 but does nothing for me

**Comment by zcattacz** [comment]
A work around: if usable depending on your use case, if you use weston, 
       start waydroid in the vertical sized weston window e.g.  `weston --width=640 --height=360`
       in that weston window open a terminal run `waydroid show-full-ui`

**Comment by Ebraama06** [comment]
@zcattacz Thanks a lot man
now it works fine

**Comment by Gentran** [comment]
Run "waydroid shell wm set-user-rotation lock 0" with root permission

**Comment by aleasto** [comment]
You can also use `persist.waydroid.width` and `.height` to do the same without having to nest a compositor.
https://docs.waydro.id/usage/waydroid-prop-options

**Comment by meramsey** [comment]
This worked nicely as well 
```
weston --width=480 --height=800 --backend=x11-backend.so --xwayland & 
```

**Comment by anonimo82** [comment]
Sorry for necro posting, but I have a similar issue and I don't need to open a new one.
Now, I'd like to rotate orientation WITHOUT going fullscreen. I've been able to open DJ Studio on my Ubuntu box (Mantic on x86-64) with the right orientation (Landscape), but I can't open any other App in landscape mode.
Please, how can I do? With F11 I can switch orientation, but my App goes full screen, which I don't want.

Thanks in advance for any help.

Regards, have a ncie day. Bye =)

**Comment by Pikatsuto** [comment]
After a bit of digging around, I came up with this script, which manages automatic rotation in the background

it's not perfect, as it returns waydroid to the foreground and requires sudo configuration without passwords, but it works well and is comfortable to use

```sh
#!/bin/bash

ROTATE_OLD=0

while true; do
    ROTATE=$(monitor-sensor --accel | cut -d : -f 2 & (usleep 50000; pkill -f monitor-sensor))
    ROTATE=$(echo ${ROTATE} | cut -d " " -f 9 | cut -d ")" -f 1 | sed -e "s/normal/0/g" -e "s/right-up/1/g")

    [ "${ROTATE}x" != "${ROTATE_OLD}x" ] \
        && ROTATE_OLD=${ROTATE} \
        && sudo waydroid shell wm set-user-rotation ${ROTATE}
done
```

**Comment by ryanrudolfoba** [comment]
> After some research, I developed this script, which handles automatic rotation in the background
> 
> it's not perfect, as it brings waydroid to the foreground and requires password-less sudo configuration, but it works well and is comfortable to use
> 
> ```shell
> #!/bin/bash
> 
> ROTATE_OLD=0
> 
> while true; do
>     ROTATE=$(monitor-sensor --accel | cut -d : -f 2 & (usleep 50000; pkill -f monitor-sensor))
>     ROTATE=$(echo ${ROTATE} | cut -d " " -f 9 | cut -d ")" -f 1 | sed -e "s/normal/0/g" -e "s/right-up/1/g")
> 
>     [ "${ROTATE}x" != "${ROTATE_OLD}x" ] \
>         && ROTATE_OLD=${ROTATE} \
>         && sudo waydroid shell wm set-user-rotation ${ROTATE}
> done
> ```

Hi thank you for this. May i ask which distro are you using that has the `monitor-sensor` binary? I want to try this in an arch-based distro. Thank you

**Comment by GuzioMG** [comment]
Just a quick heads-up to anyone trying this on Android 16 (I know Waydoid doesn't officially support anything past Android 13, but after an initial bumpy start (issue linked above), I had great success with a community Android 16 image) and maybe also Android 14 and/or 15, as idk when they changed it:

The command is no longer `sudo waydroid shell wm set-user-rotation lock [0-3]`, but rather `sudo waydroid shell wm user-rotation lock [0-3]` (so without the `set-`) or `sudo waydroid shell settings put system user_rotation [0-3]` (actually, this one will probably also exist on any version between Android 13 and Android 16 (because it doesn't use `wm` at all - tho they're's ofc always the chance that they also changed `settings`), so it's likely the safest one for any automated scripts, eg. the one @Pikatsuto posted).

**Comment by GuzioMG** [comment]
> > After some research, I developed this script, which handles automatic rotation in the background
> > it's not perfect, as it brings waydroid to the foreground and requires password-less sudo configuration, but it works well and is comfortable to use
> > #!/bin/bash
> > 
> > ROTATE_OLD=0
> > 
> > while true; do
> >     ROTATE=$(monitor-sensor --accel | cut -d : -f 2 & (usleep 50000; pkill -f monitor-sensor))
> >     ROTATE=$(echo ${ROTATE} | cut -d " " -f 9 | cut -d ")" -f 1 | sed -e "s/normal/0/g" -e "s/right-up/1/g")
> > 
> >     [ "${ROTATE}x" != "${ROTATE_OLD}x" ] \
> >         && ROTATE_OLD=${ROTATE} \
> >         && sudo waydroid shell wm set-user-rotation ${ROTATE}
> > done
> 
> Hi thank you for this. May i ask which distro are you using that has the `monitor-sensor` binary? I want to try this in an arch-based distro. Thank you

@ryanrudolfoba The Arch package for `monitor-sensors` is `iio-sensor-proxy`.
