### ISSUE TITLE
[Feature request] Shared folder from Linux to Waydroid

### ISSUE THREAD

**Issue by CalcProgrammer1** [waydroid/waydroid#59]
Is there currently a means to mount a folder from the host filesystem into the Waydroid one?  For instance, if I have my music in /home/user/Music, can I mount that into the main storage/as an SD card so I can play music from an Android app?

**Comment by Quackdoc** [comment]
this seems to have gotten missed. 

https://docs.waydro.id/faq/setting-up-a-shared-folder

**Comment by CalcProgrammer1** [comment]
Closing as documented

**Comment by aria-dos** [comment]
Small addition, these folders only work one direction. to make a shared folder from Waydroid to the host system, simply switch source and target folders. To access the files you'll need to use `chmod -R 777` on the folder every time it is updated.

**Comment by rexendevar** [comment]
> you'll need to use `chmod -R 777` on the target folder every time it is updated.

Is there no way to add the waydroid user to a group that can access the files? surely leaving everything in my home folder at 777 is a giant mistake
