### ISSUE TITLE
Apps not loading

### ISSUE THREAD

**Issue by CCWTech** [waydroid/waydroid#591]
(155500) [10:07:04] Failed to get service waydroidplatform, trying again...
(155500) [10:07:05] Failed to get service waydroidplatform, trying again...
(155500) [10:07:06] Failed to get service waydroidplatform, trying again...
(155500) [10:07:07] Failed to get service waydroidplatform, trying again...
(155500) [10:07:08] Failed to get service waydroidplatform, trying again...
(155500) [10:07:09] Failed to get service waydroidplatform, trying again...
(155500) [10:07:10] Failed to get service waydroidplatform, trying again...
(155500) [10:07:11] Failed to get service waydroidplatform, trying again...
(155500) [10:07:12] Failed to get service waydroidplatform, trying again...
(155500) [10:07:13] Failed to get service waydroidplatform, trying again...
(155500) [10:07:14] Failed to get service waydroidplatform, trying again...
(155500) [10:07:15] Failed to get service waydroidplatform, trying again...
(155500) [10:07:16] Failed to get service waydroidplatform, trying again...
(155500) [10:07:17] Failed to get service waydroidplatform, trying again...
(155500) [10:07:18] Failed to get service waydroidplatform, trying again...
(155500) [10:07:19] Failed to get service waydroidplatform, trying again...
(155500) [10:07:20] Failed to get service waydroidplatform, trying again...
(155617) [10:07:23] Stopping container
(155617) [10:07:23] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(155617) [10:07:23] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(155617) [10:07:23] % umount /var/lib/waydroid/rootfs/vendor
(155617) [10:07:23] % umount /var/lib/waydroid/rootfs
(155617) [10:07:23] % lxc-info --version
5.0.0~git2209-g5a7b9ce67
(155617) [10:07:23] % mkdir -p /var/lib/waydroid/lxc/waydroid
(155617) [10:07:23] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_2" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(155617) [10:07:23] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(155617) [10:07:23] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(155617) [10:07:23] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(155617) [10:07:23] Starting container
(155617) [10:07:23] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(155617) [10:07:23] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(155617) [10:07:23] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(155617) [10:07:23] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(155617) [10:07:23] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(155617) [10:07:23] Save config: /var/lib/waydroid/waydroid.cfg
(155617) [10:07:23] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(155617) [10:07:23] New background process: pid=155674, output=background
lxc-start: waydroid: utils.c: safe_mount: 1221 No such file or directory - Failed to mount "/dev/ashmem" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/ashmem"
(066107) [10:07:32] waydroidusermonitor: Received transaction: 1
(066107) [10:07:32] Android with user 0 is ready
(157550) [10:07:45] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(157550) [10:07:45] *** output passed to waydroid stdout, not to this log ***
(157696) [10:09:10] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(157696) [10:09:10] *** output passed to waydroid stdout, not to this log ***
(157701) [10:09:26] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(157701) [10:09:26] *** output passed to waydroid stdout, not to this log ***
(157857) [10:10:38] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(157857) [10:10:38] *** output passed to waydroid stdout, not to this log ***
(157978) [10:11:54] Already initialized
(158449) [10:18:31] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(158449) [10:18:31] *** output passed to waydroid stdout, not to this log ***
(160821) [10:35:19] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(160821) [10:35:19] *** output passed to waydroid stdout, not to this log ***
(160830) [10:35:33] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(160830) [10:35:33] *** output passed to waydroid stdout, not to this log ***
(174679) [12:41:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(174679) [12:41:15] *** output passed to waydroid stdout, not to this log ***

**Comment by CCWTech** [comment]
Ubuntu 22.10 - Fresh install.

**Comment by dbogdanov** [comment]
I am having the same issue after upgrading from Ubuntu 22.04 to 22.10.

**Comment by dbogdanov** [comment]
@CCWTech I am using weston and I was able to launch following these steps: https://github.com/waydroid/waydroid/issues/526#issuecomment-1249996925

**Comment by CCWTech** [comment]
Thanks!
