### ISSUE TITLE
waydroid / X11 / Weston : can I prevent new (Linux) apps to open inside Weston ?

### ISSUE THREAD

**Issue by benintech** [waydroid/waydroid#593]
Hi,
I successfully managed to make Waydroid run inside X11, through Weston (see https://github.com/waydroid/waydroid/issues/195).

But now every new (Linux, non-Android) apps I launch are opened inside the Weston window. Is it possible to open them as usual, directly in X11 ? I'd like to use Weston only for Waydroid apps.

**Comment by aleasto** [comment]
Change the Wayland socket name.

Closing because unrelated to the project.

**Comment by successtheman** [comment]
> Hi, I successfully managed to make Waydroid run inside X11, through Weston (see #195).
> 
> But now every new (Linux, non-Android) apps I launch are opened inside the Weston window. Is it possible to open them as usual, directly in X11 ? I'd like to use Weston only for Waydroid apps.

Did you ever figure this out?

**Comment by benintech** [comment]
> Did you ever figure this out?

Yes, it's [@aleasto's solution](https://github.com/waydroid/waydroid/issues/593#issuecomment-1316830270) : change the socket name.
Example :
```
$ weston --socket=mysocket &
```
