### ISSUE TITLE
Failed to add service waydroidusermonitor | ( Ubuntu Touch )

### ISSUE THREAD

**Issue by leuchtturmsss** [waydroid/waydroid#594]
**Describe the bug**
According to the Waydroid documentation after running `sudo waydroid container start`  I am supposed to execute `waydroid session start` to begin Waydroid. The application does not allow for this to happen.

I am using the [Waydroid Helper](https://open-store.io/app/waydroidhelper.aaronhafer) for Ubuntu Touch and have also tried launching it from the menu startup but the app appears to idle frozen. 

**Screenshots**

Pictures of described issue: 
![IMG_5106](https://user-images.githubusercontent.com/118345067/202133538-6356ea24-3bfc-4a37-924f-11ce1e7c7167.PNG)

![IMG_5105](https://user-images.githubusercontent.com/118345067/202133552-f63c0476-d76a-4795-8755-04a9fb1a2830.PNG)

This is the screen it shows me when trying to launch from application menu:
![IMG_5107](https://user-images.githubusercontent.com/118345067/202133461-d3a3a420-7b9e-43ff-a6bc-6a4248cd2014.PNG)

**General information (please complete the following information):**
Installed through latest release of [Waydroid Helper](https://open-store.io/app/waydroidhelper.aaronhafer)

```
$ waydroid -V
1.2.0
```

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Ubuntu touch
- Ubuntu 16.04 (OTA-23)
I installed it through the Ubuntu Touch Installer today.

**Additional context**
 

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`: https://paste.debian.net/1260878
 - Output of `waydroid log`: https://paste.debian.net/1260876
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services: https://paste.debian.net/1260877

**Comment by aleasto** [comment]
The waydroid version shipped in Ubuntu Touch is too old.

As a workaround until they update it, run `sed '/aidl/s/2/3/' -i /etc/gbinder.d/anbox.conf`

Closing because this is not our issue

**Comment by leuchtturmsss** [comment]
@aleasto regardless thank you so much for your help. I'll try and use Ubuntu Touch and their helper's support channels.

______________________

```
phablet@ubuntu-phablet:~$ sed '/aidl/s/2/3/' -i /etc/gbinder.d/anbox.conf 
sed: couldn't open temporary file /etc/gbinder.d/sedmgDQHj: Read-only file system
phablet@ubuntu-phablet:~$ sudo sed '/aidl/s/2/3/' -i /etc/gbinder.d/anbox.conf
[sudo] password for phablet:            
sed: couldn't open temporary file /etc/gbinder.d/sedEbfO24: Read-only file system                                       
phablet@ubuntu-phablet:~$ 
```

I do appear to still be receiving error messages of a read only file system when executing that command.
