### ISSUE TITLE
Won't Start After Update

### ISSUE THREAD

**Issue by levone1** [waydroid/waydroid#595]
**Describe the bug**
Been starting fine from app icon and from terminal commands for several months.  Updated yesterday via apt, and now won't start.  Tried restart, etc.
**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0] 1.3.3
 - Waydroid Images Version [e.g. VANILLA 20211021] GAPPS 20221109

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64] Linux Mint 20.3 Una \n \l
 - GPU: [e.g. AMD Radeon™ RX 5700] AMD CAICOS (DRM 2.50.0 / 5.4.0-132-generic, LLVM 12.0.0) (0x677b)
    Version: 21.2.6  ([?] from `glxinfo` command)...
 - Kernel version: [e.g. Generic 5.4.x] Linux version 5.4.0-132-generic
 - Host mesa version: [e.g. mesa 2.2] 3.1 Mesa 21.2.6 ([?] opengl version string)...
 - Desktop: [e.g. Gnome 40.x.x] Gnome 3.36.8

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 output of waydroid.log
`(002909) [16:24:12] % chmod 666 -R /dev/anbox-binder
(002909) [16:24:12] % chmod 666 -R /dev/anbox-vndbinder
(002909) [16:24:12] % chmod 666 -R /dev/anbox-hwbinder
(002909) [16:24:12] Container manager is waiting for session to load
(002965) [16:24:25] Save session config: /var/lib/waydroid/session.cfg
(002965) [16:24:25] UserMonitor service is not even started
(002965) [16:24:25] Clipboard service is not even started
(002909) [16:24:26] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
waydroid-net is already running
(002909) [16:24:26] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002909) [16:24:26] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002909) [16:24:26] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(003090) [16:24:26] UserMonitor service is not even started
(003090) [16:24:26] Clipboard service is not even started
(002909) [16:24:26] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002909) [16:24:26] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002909) [16:24:27] Save config: /var/lib/waydroid/waydroid.cfg
(002909) [16:24:27] % mount -o bind /home/admin/.local/share/waydroid/data /var/lib/waydroid/data
(002909) [16:24:27] % chmod 777 -R /dev/ashmem
(002909) [16:24:27] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(002909) [16:24:27] % chmod 777 -R /dev/dri
(002909) [16:24:27] % chmod 777 -R /dev/fb0
(002909) [16:24:27] % chmod 777 -R /dev/video1
(002909) [16:24:27] % chmod 777 -R /dev/video0
(002909) [16:24:27] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002909) [16:24:27] New background process: pid=3110, output=background
(002909) [16:24:27] waiting 10 seconds for container to start...
(002965) [16:24:27] UserMonitor service is not even started
(002965) [16:24:27] Clipboard service is not even started
(002909) [16:24:28] waiting 9 seconds for container to start...
(002909) [16:24:29] Save session config: /var/lib/waydroid/session.cfg
(003250) [16:24:36] Failed to get service waydroidplatform, trying again...
(003250) [16:24:37] Failed to get service waydroidplatform, trying again...
(003250) [16:24:38] Failed to get service waydroidplatform, trying again...`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services

Tried to upload waydroid base prop, and got error, "type not supported".  Will retry as directed.  Going to restart now, and get logcat and upload...

Thanks

**Comment by levone1** [comment]
Got logcat.  When attempting to upload, I get "something went really wrong and we can't process that file"...

Here's Mega links:
waydroid base prop - https://mega.nz/file/xxURwaZI#Qm76jYWOV-V-K4L6FcbR6rnZNb4iM6_iwqEmz-Y7l6Q
logcat - https://mega.nz/file/A49SxLZT#gLjSAWCHllbTH6eKyEiW4KL_GJF8SWCxQsmH4n6DIzw

**Comment by aleasto** [comment]
One issue was fixed by: https://github.com/waydroid/android_hardware_waydroid/commit/7812a04e77aa077d73ada2088af22c800960d43f

The other issue is your kernel is lacking features:
```
11-17 19:23:50.040    52    52 W XfrmController: Could not get a new socket, line=239
11-17 19:23:50.040    52    52 E netd    : Failed to initialize XfrmController (Status[code: 93, msg: "[Protocol not supported] : Could not open netlink socket"])
11-17 19:23:50.040    52    52 I netd    : Initializing XfrmController: 155us
11-17 19:23:50.040    52    52 E Netd    : Unable to create netlink socket for family 5: Protocol not supported
11-17 19:23:50.040    52    52 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
11-17 19:23:50.040    52    52 E Netd    : Unable to create netlink socket for family 12: Protocol not supported
11-17 19:23:50.040    52    52 E Netd    : Unable to open strict socket
11-17 19:23:50.040    52    52 E Netd    : Unable to create NFLogListener: Status[code: 93, msg: "[Protocol not supported] : socket() failed"]
```

**Comment by aleasto** [comment]
Added PopOS install instructions: https://docs.waydro.id/usage/install-on-desktops#popos

**Comment by levone1** [comment]
> One issue was fixed by: [waydroid/android_hardware_waydroid@7812a04](https://github.com/waydroid/android_hardware_waydroid/commit/7812a04e77aa077d73ada2088af22c800960d43f)
> 
> The other issue is your kernel is lacking features:
> 
> ```
> 11-17 19:23:50.040    52    52 W XfrmController: Could not get a new socket, line=239
> 11-17 19:23:50.040    52    52 E netd    : Failed to initialize XfrmController (Status[code: 93, msg: "[Protocol not supported] : Could not open netlink socket"])
> 11-17 19:23:50.040    52    52 I netd    : Initializing XfrmController: 155us
> 11-17 19:23:50.040    52    52 E Netd    : Unable to create netlink socket for family 5: Protocol not supported
> 11-17 19:23:50.040    52    52 W Netd    : Unable to open qlog quota socket, check if xt_quota2 can send via UeventHandler
> 11-17 19:23:50.040    52    52 E Netd    : Unable to create netlink socket for family 12: Protocol not supported
> 11-17 19:23:50.040    52    52 E Netd    : Unable to open strict socket
> 11-17 19:23:50.040    52    52 E Netd    : Unable to create NFLogListener: Status[code: 93, msg: "[Protocol not supported] : socket() failed"]
> ```

Ok, thanks.  Changing Waydroid version back to the one that was working before now doesn't work.  I guess maybe it was due to a Linux update...

**Comment by levone1** [comment]
> Added PopOS install instructions: https://docs.waydro.id/usage/install-on-desktops#popos

I figured maybe this was posted here so I could try it, so I did, and went smooth up to last step, which caused me to check issues, where I found this - https://github.com/anbox/anbox-modules/issues/101#issuecomment-1258134180.  Seems likely to be my issue.
