### ISSUE TITLE
WayDroid installs OK but does not initialize

### ISSUE THREAD

**Issue by jmd8800** [waydroid/waydroid#598]
**Describe the bug**
I installed WayDroid on a JingPad C1 with instructions from the ubports forum. I installed with WayDroid Helper and through command line. Each time the installation went OK. Reboot and from the menu I choose the WayDroid icon and a window comes up saying WayDroid and the little blue circle spins. Nothing after that. 

**Screenshots**
https://mega.nz/file/vFgVSSCA#R0tws2HWuBiCQSTiRf4hSxsD0r9b8hmDuH2c3U5JREU

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0] (I don't see this)
 - Waydroid Images Version: VANILLA 18.1-20221111

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Smartphone (please complete the following information):**
 - Device: JingPad C1
 - OS: Ubuntu Touch OTA-23
 - Mainline or Halium 10
 - Kernel version: 4.14.x]

**Additional context**
WayDroid Stop kills the process

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - https://mega.nz/file/eA53iDJI#ahohcNE7ZInnkh51U31AClLTqlYH4Koyu-GGJrpcpfc
 - Output of `waydroid log`
 - https://mega.nz/file/aURwyaaA#4UBOIY_WKxgr4oDM8WV2fl924kw8G6sNe85Tr-5t3fQ
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
 - I do not know how to do this.
 - Output from ps aux | grep waydroid
 - https://mega.nz/file/XdgiDCLI#Vj0kFcKeHDdnunf8aA_jII8uMNJ38LZ0Kc5kaU5mJ3w

**Comment by aleasto** [comment]
The version of waydroid distributed by Ubuntu Touch is too old to support Android 11 (LineageOS 18.1).

The current workaround, until they update it, is to `sudo sed '/aidl/s/2/3/' -i /etc/gbinder.d/anbox.conf`
