### ISSUE TITLE
ERROR: Binder node "binder" for waydroid not found Ubuntu

### ISSUE THREAD

**Issue by 2br-2b** [waydroid/waydroid#60]
Hi,

I'm using Ubuntu 21.04 and I get this error after installing Waydroid:

```
foo@cumputer:~$ sudo waydroid init
[15:39:40] ERROR: Binder node "binder" for waydroid not found
[15:39:40] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
foo@cumputer:~$ waydroid log 
ERROR: WayDroid is not initialized, run "waydroid init"
```

**Comment by 2br-2b** [comment]
Update: thanks to @erfanoabdi oan the Matrix channel, the problem was resolved. It turns out you can't have Anbox and Waydroid installed at the same time. I had to remove Anbox and reboot to get rid of the Anbox kernel modules.

**Comment by klasrocket** [comment]
maybe this is something that could be added to the documentation or put into a more clarifying error code, that would have helped me.
