### ISSUE TITLE
Emulate wifi instead of wired internet

### ISSUE THREAD

**Issue by wsippel** [waydroid/waydroid#600]
**Is your feature request related to a problem? Please describe.**
I got Waydroid up an running and tried to install a few three games, they all fail during their update process. Having played all three games on native devices, I'think they all tell you to use wifi instead of cellular at that point - but Waydroid uses neither. I believe that's probably causing thosf updaters to fail?

**Describe the solution you'd like**
Pretend the virtual network connection is a wlan connection. Android supports wired connections, but doesn't really "get it" from what I can tell.

**Comment by aleasto** [comment]
This is already a feature: https://docs.waydro.id/usage/waydroid-prop-options#modify-app-behaviour
