### ISSUE TITLE
How can I modify system.img ?

### ISSUE THREAD

**Issue by benintech** [waydroid/waydroid#603]
In order to change the physical keyboard layout (see https://github.com/waydroid/waydroid/issues/599), I'd like to modify `system.img` (e.g., `/var/lib/waydroid/images/system.img`). How can I do that ? It seems it can only be mounted read-only :
```
# mount /var/lib/waydroid/images/system.img /tmp/waydroid/
mount: /tmp/waydroid: WARNING: source write-protected, mounted read-only.
``` 
How can I make some modifications inside `system.img` ?

**Comment by aleasto** [comment]
Soon via https://github.com/waydroid/waydroid/pull/580

Currenty, by resizing (`resize2fs`) the image then mounting it RW

**Comment by benintech** [comment]
Great, it worked, thanks :
```
# e2fsck -f /var/lib/waydroid/images/system.img
# resize2fs /var/lib/waydroid/images/system.img 2G
# mount -o rw /var/lib/waydroid/images/system.img /tmp/waydroid
```
Now, before your answer I tried a different approach, that _seemed_ to work too, but I wonder if there are side effects down the road :
- I mounted `system.img`
- Then I copied its content to another directory (for example `/tmp/wdroid`)
- After having made the modifications, I then rebuilt `system.img` with `mksquashfs`
```
# mksquashfs /tmp/wdroid/* /tmp/system.img
```
I then replaced the original `/var/lib/waydroid/images/system.img` by this newly built one, and everything worked fine.

Are there any downsides to using squashfs ? The advantage is that system.img is much smaller, only around 750MB, comparing to the original 1.8GB size

**Comment by aleasto** [comment]
> Are there any downsides to using squashfs ?

I don't think so

**Comment by Xf0ur** [comment]
I did that, system.img is much smaller but i can't scan/resize it anymore.

e2fsck -f /var/lib/waydroid/images/system.img
e2fsck 1.45.5 (07-Jan-2020)
ext2fs_open2: Bad magic number in super-block
e2fsck: Superblock invalid, trying backup blocks...
e2fsck: Bad magic number in super-block while trying to open /var/lib/waydroid/images/system.img

The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

How i can solve that issue?
