### ISSUE TITLE
waydroid init fails on Fedora 37 (including Kionite)

### ISSUE THREAD

**Issue by firefoxlover** [waydroid/waydroid#606]
**Describe the bug**
Using the aleasto/waydroid COPR repo, the install works perfectly fine. But when I try to do `waydroid init`, it gives me:

```Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
See also: <htps://github.com/waydroid`

**Log**
```
(025431) [18:04:46] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(025431) [18:04:46] *** output passed to waydroid stdout, not to this log ***
(025445) [18:05:15] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(025445) [18:05:15] See also: <https://github.com/waydroid>
(025445) [18:05:15] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 53, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 101, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 61, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(025456) [18:05:21] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(025456) [18:05:21] *** output passed to waydroid stdout, not to this log ***

```

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3
 - Waydroid Images Version (unknown)

**Desktop (please complete the following information):**
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.8-300.fc37.x86_64 (64-bit)
Graphics Platform: X11

**Comment by aleasto** [comment]
Follow the instructions on the copr webpage.
Specifically, it is suggested to use the graphical initializer and paste the two OTA links.
If you want to use the CLI regardless, pass the same OTA links as arguments to `waydroid init -c <system_ota> -v <vendor_ota>`.

The default links had to be removed from the default package because they download some licensed material (MPEG-LA codecs...) and that's against fedora policy

**Comment by firefoxlover** [comment]
> Follow the instructions on the copr webpage. Specifically, it is suggested to use the graphical initializer and paste the two OTA links. If you want to use the CLI regardless, pass the same OTA links as arguments to
> 
> ```
> waydroid init -c <system_ota> -v <vendor_ota>
> ```
> 
> `waydroid init --help` for all options.
> 
> The default links had to be removed from the default package because they download some licensed material (MPEG-LA codecs...) and that's against fedora policy

Thank you for the response!
