### ISSUE TITLE
Does not start on Alpine Linux (armv7)

### ISSUE THREAD

**Issue by peter-marshall5** [waydroid/waydroid#607]
A couple of seconds after running `waydroid session start`, it crashes with the message: `[gbinder] WARNING: Service manager /dev/binder has died`

OS: Alpine Linux (on armv7 cpu)
GPU: Mali T760
Kernel Version: 6.0.8
Host mesa version: 22.3.0
Desktop: sway 1.7

waydroid log:
`(007381) [16:20:05] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(007381) [16:20:05] Save config: /var/lib/waydroid/waydroid.cfg
(007381) [16:20:05] % chmod 777 -R /dev/dri
(007381) [16:20:05] % chmod 777 -R /dev/fb0
(007381) [16:20:05] % chmod 777 -R /dev/video4
(007381) [16:20:05] % chmod 777 -R /dev/video3
(007381) [16:20:05] % chmod 777 -R /dev/video2
(007381) [16:20:05] % chmod 777 -R /dev/video1
(007381) [16:20:05] % chmod 777 -R /dev/video0
(007381) [16:20:05] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(007381) [16:20:05] New background process: pid=7452, output=background
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1221 No such file or directory - Failed to mount "/dev/ashmem" onto "/usr/lib/lxc/rootfs/dev/ashmem"
(007381) [16:20:05] Save session config: /var/lib/waydroid/session.cfg
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(007381) [16:20:21] session manager stopped, stopping container and waiting...
(007381) [16:20:21] WayDroid container is STOPPED
(007381) [16:20:21] % modprobe -q ashmem_linux
(007381) [16:20:21] % chmod 666 -R /dev/binder
(007381) [16:20:21] % chmod 666 -R /dev/vndbinder
(007381) [16:20:21] % chmod 666 -R /dev/hwbinder
(007381) [16:20:21] Container manager is waiting for session to load
(007857) [16:27:06] Save session config: /var/lib/waydroid/session.cfg
(007857) [16:27:06] UserMonitor service is not even started
(007857) [16:27:06] Clipboard service is not even started
(007381) [16:27:07] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
waydroid-net is already running
(007381) [16:27:07] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(007381) [16:27:07] % umount /var/lib/waydroid/rootfs/vendor
(007381) [16:27:07] % umount /var/lib/waydroid/rootfs
(007381) [16:27:07] % mount /mnt/waydroid/system.img /var/lib/waydroid/rootfs
(007381) [16:27:09] % mount -o remount,ro /mnt/waydroid/system.img /var/lib/waydroid/rootfs
(007381) [16:27:10] % mount /mnt/waydroid/vendor.img /var/lib/waydroid/rootfs/vendor
(007381) [16:27:10] % mount -o remount,ro /mnt/waydroid/vendor.img /var/lib/waydroid/rootfs/vendor
(007381) [16:27:10] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(007381) [16:27:10] Save config: /var/lib/waydroid/waydroid.cfg
(007381) [16:27:10] % chmod 777 -R /dev/dri
(007381) [16:27:10] % chmod 777 -R /dev/fb0
(007381) [16:27:10] % chmod 777 -R /dev/video4
(007381) [16:27:10] % chmod 777 -R /dev/video3
(007381) [16:27:10] % chmod 777 -R /dev/video2
(007381) [16:27:10] % chmod 777 -R /dev/video1
(007381) [16:27:10] % chmod 777 -R /dev/video0
(007381) [16:27:10] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(007381) [16:27:10] New background process: pid=7886, output=background
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1221 No such file or directory - Failed to mount "/dev/ashmem" onto "/usr/lib/lxc/rootfs/dev/ashmem"
(007381) [16:27:10] waiting 10 seconds for container to start...
(007381) [16:27:11] Save session config: /var/lib/waydroid/session.cfg
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(007381) [16:28:58] session manager stopped, stopping container and waiting...
(007381) [16:28:58] WayDroid container is STOPPED
(007381) [16:28:58] % modprobe -q ashmem_linux
(007381) [16:28:58] % chmod 666 -R /dev/binder
(007381) [16:28:58] % chmod 666 -R /dev/vndbinder
(007381) [16:28:58] % chmod 666 -R /dev/hwbinder
(007381) [16:28:58] Container manager is waiting for session to load
(008205) [16:29:04] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(008205) [16:29:04] *** output passed to waydroid stdout, not to this log ***`

waydroid.prop
`sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=panfrost
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm/MAINLINE.json
waydroid.tools_version=1.3.3
ro.vndk.lite=true
ro.product.waydroid.model=Google Speedy
waydroid.host.user=peter
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.stub_sensors_hal=1`

waydroid logcat was generated with: `sudo waydroid logcat >log.txt 2>>log.txt`

**Comment by peter-marshall5** [comment]
[logcat.txt](https://github.com/waydroid/waydroid/files/10048087/logcat.txt)

**Comment by aleasto** [comment]
Logcat is very explicit here:
```
11-19 21:20:06.134    46    46 D LibBpfLoader: bpf_prog_load lib call for /system/etc/bpf/time_in_state.o (tracepoint_sched_sched_switch) returned fd: -1 (Invalid argument)
11-19 21:20:06.134    46    46 W LibBpfLoader: bpf_prog_load - BEGIN log_buf contents:
11-19 21:20:06.134    46    46 W LibBpfLoader: 
11-19 21:20:06.134    46    46 W LibBpfLoader: bpf_prog_load - END log_buf contents.
11-19 21:20:06.134    46    46 E LibBpfLoader: non-optional program failed to load.
11-19 21:20:06.134    46    46 E LibBpfLoader: Failed to load programs, loadCodeSections ret=-1
11-19 21:20:06.134    46    46 E bpfloader: Failed to load object: /system/etc/bpf/time_in_state.o, ret: Operation not permitted
11-19 21:20:06.134    46    46 E bpfloader: === CRITICAL FAILURE LOADING BPF PROGRAMS ===
11-19 21:20:06.134    46    46 E bpfloader: If this triggers reliably, you're probably missing kernel options or patches.
11-19 21:20:06.134    46    46 E bpfloader: If this triggers randomly, you might be hitting some memory allocation problems or startup script race.
11-19 21:20:06.134    46    46 E bpfloader: --- DO NOT EXPECT SYSTEM TO BOOT SUCCESSFULLY ---
```
Namely,
> **you're probably missing kernel options or patches.**

**Comment by peter-marshall5** [comment]
Thanks for the insight. How did I miss this before?

Anyways, any idea specifically on what kernel features could be missing? I have the BPF JIT compiler enabled in the kernel, and the same error occurs even after running `echo 0 > /proc/sys/kernel/unprivileged_bpf_disabled` to enable unpriveleged BPF.

**Comment by peter-marshall5** [comment]
Fixed by enabling cgroup support ifor eBPF programs in the kernel. The required config option is `CONFIG_CGROUP_BPF`

Waydroid now launches but there are still problems with insufficient memory, should be easy enough to fix with zram or the non-gapps rom.
