### ISSUE TITLE
ARM Emulation on waydroid x86-64 images

### ISSUE THREAD

**Issue by johndoe9867** [waydroid/waydroid#616]
One question,

Do the android 11 x64 images contain the native bridge for running ARM apps as well?

**Comment by aleasto** [comment]
No

**Comment by rebokdev** [comment]
I think support for it should be added
cause unity stopped supporting
x86 and x64 architectures
most games is made using unity

**Comment by ayasa520** [comment]
> I think support for it should be added cause unity stopped supporting x86 and x64 architectures most games is made using unity
This is not a technical issue, but may have legal risks
