### ISSUE TITLE
32-bit LineageOS 18.1 images require SSE 4.1 roundss instruction

### ISSUE THREAD

**Issue by dreamlayers** [waydroid/waydroid#617]
**Describe the bug**
I'm trying to run Waydroid on an Intel Core 2 Duo T7400. It has SSE3 but not SSE4. The CPU can run Android x86 9.0 r2. However, running init I get an illegal instruction error, showing a roundss instruction, which is SSE 4.1:

```
Thread 2.1 "init" received signal SIGILL, Illegal instruction.
[Switching to process 18726]
0xf7f38376 in __dl_ceilf () from target:/system/bin/bootstrap/linker
(gdb) disassemble
Dump of assembler code for function __dl_ceilf:
   0xf7f38370 <+0>:     movss  0x4(%esp),%xmm0
=> 0xf7f38376 <+6>:     roundss $0x2,%xmm0,%xmm0
   0xf7f3837c <+12>:    movss  %xmm0,-0x4(%esp)
   0xf7f38382 <+18>:    flds   -0x4(%esp)
   0xf7f38386 <+22>:    ret    
End of assembler dump.
```

I got this by running `sudo gdb 'which lxc-start'`, `set args -P /var/lib/waydroid/lxc -F -n waydroid -- /init` and `set follow-fork-mode child`. The `waydroid log` output was useless: `lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126`, and dmesg was only a little bit more helpful, with things like `traps: init[22116] trap invalid opcode ip:f7eff376 sp:ffb6836c error:0 in linker[f7e48000+fa000]`.

This seems real:
```
$ objdump -d /var/lib/waydroid/rootfs/system/lib/bootstrap/libm.so | grep -A 5 ceilf
0002e140 <ceilf@@LIBC>:
   2e140:       f3 0f 10 44 24 04       movss  0x4(%esp),%xmm0
   2e146:       66 0f 3a 0a c0 02       roundss $0x2,%xmm0,%xmm0
   2e14c:       f3 0f 11 44 24 fc       movss  %xmm0,-0x4(%esp)
   2e152:       d9 44 24 fc             flds   -0x4(%esp)
   2e156:       c3                      ret
```
Note that the `rootfs/system/apex/com.android.runtime/lib/bionic/libm.so` file is identical.

Info about roundss instruction: https://www.felixcloutier.com/x86/roundss

**General information (please complete the following information):**
waydroid 1.3.3
I installed the default, LineageOS. The installer did say it was installing i386 because of lack of SSE4.2.
MD5 values of images:
9a2e78901f786360e5b190397a0d5382  system.img
d72e7ce20a567bf3ed3d5284d3e714d3  vendor.img
Downloaded on 2022-11-23. I don't know where to find the version of the image.

**Desktop (please complete the following information):**
 - Ubuntu 22.10
 - GPU: Mobility Radeon X1400
 - Kernel version: 5.19.0-23-generic
 - Host mesa version: 22.3\~git2210080600.12efb8\~oibaf\~j (from oibaf PPA, I should update or revert to non-PPA files, but it seems irrelevant)
 - Desktop: KDE Plasma 5.25.5-0ubuntu4

**Logs (please upload as file)**
 -  `/var/lib/waydroid/waydroid_base.prop` and output of `waydroid log` are in
[waydroid_logs.zip](https://github.com/waydroid/waydroid/files/10073069/waydroid_logs.zip)
 - I can't give you `waydroid logcat` because init crashed at the beginning of startup, and logcat was never accessible

**Comment by dreamlayers** [comment]
Using https://github.com/mirh/opemu-linux I was able to get further, with the ability to run a shell and logcat, but still no GUI. There are clearly more SSE4.1 instructions present. Probably opemu has bugs and/or unimplemented instructions. I didn't examine that yet. I had to [alter opemu_linux make it build in Linux 5.19](https://github.com/dreamlayers/opemu-linux/tree/linux-5.19-hack) and maybe I did something wrong there. [I'm attaching the resulting logcat.](https://github.com/waydroid/waydroid/files/10076974/logcat.txt.gz)

Anyways,  at https://developer.android.com/ndk/guides/abis I still see that the x86 Android ABI only needs x86 (IA-32), MMX, SSE/2/3 and SSSE3. It does not need SSE4. There shouldn't be any SSE4 instructions in an x86 build, except maybe used conditionally if the CPU feature is detected. I should not need opemu_linux on that CPU, and I can run Android x86 directly on the CPU (without virtualization or emulation) without these problems.

**Comment by dreamlayers** [comment]
The last LineageOS 17.1 image available on https://sourceforge.net/projects/waydroid/files/images/ **worked** for me: lineage-17.1-20220723-GAPPS-waydroid_x86-system.zip with lineage-17.1-20220723-MAINLINE-waydroid_x86-vendor.zip 

The first LineageOS 18.1 image,  lineage-18.1-20221030-GAPPS-waydroid_x86-system.zip with sudo lineage-18.1-20221030-MAINLINE-waydroid_x86-vendor.zip , did not work. So probably LineageOS 17.1 works but 18.1 has this problem. I looked at libm.so and found that it contains roundss in ceilf.

BTW.  Switching between images was problematic. When I just put the images in `/usr/share/waydroid-extra/images/` and used `sudo waydroid init -f`, I was still using the old image. So I would stop the container, make sure `waydroid-container.service` is stopped, unmount everything under `/var/lib/waydroid/`, and then `sudo rm -r /var/lib/waydroid .local/share/waydroid`, start the container, and use the new version. Maybe the situation left after an image crashed made switching more difficult. Also, deletion of `.local/share/waydroid` may have been necessary due to the downgrade from 18.1 to 17.1. Otherwise Trebuchet and Google Play Services kept constantly crashing.

**Comment by aleasto** [comment]
Thanks for looking into it.
I'll see if I can find where to disable SSE4 entirely for x86

**Comment by aleasto** [comment]
Yea upgrading from a GAPPS system to a non-GAPPS system without removing data is not supported.

I'll merge the change!

**Comment by dreamlayers** [comment]
Can you please release a new build with this change? At https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86/ the last build is still April 22nd. That is a much longer time period than was usual between builds.

**Comment by aleasto** [comment]
Long delay, but the change is now shipping.
Please confirm if you can!

**Comment by dreamlayers** [comment]
Confirmed working with lineage-18.1-20230805-GAPPS-waydroid_x86-system.zip, lineage-18.1-20230805-MAINLINE-waydroid_x86-vendor.zip and waydroid 1.4.1 on x86_64 Ubuntu 23.04 with Intel Core 2 Duo T7400 CPU. I simply replaced the Android 10 images I had in /usr/share/waydroid-extra/images. The first startup took a long time because of the upgrade from Android 10 to 11, but after that performance is pretty good. I consider this solved. Thank you.

**Comment by dreamlayers** [comment]
It is weird that the lineage-17.1-20220723-GAPPS-waydroid_x86-system image that worked for me causes this problem. Maybe the problem is that the code detects your CPU supporting some features that my Core 2 Due doesn't support, and then tries to use code it wouldn't try on my CPU. For example, maybe it detects SSE3 support and tries to use pshufb, but that requires SSSE3, not SSE3. As far as I can tell, your CPU doesn't support SSSE3.

**Comment by Flashwalker** [comment]
it still fails to start.

$ waydroid first-launch
[18:18:37] Waiting for binder Service Manager...
[18:19:37] Service Manager never appeared
[18:19:37] Failed to access IPlatform service

On the first startup, after loading VANILA, I saw the bootable animated logo and then it died.

Now all i can see is:
```
$ waydroid first-launch
[18:18:37] Waiting for binder Service Manager...
[18:19:37] Service Manager never appeared
[18:19:37] Failed to access IPlatform service
```

```
$ lxc-checkconfig
LXC version 5.0.3
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-6.12.8-x64v3-xanmod1

--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled
Cgroup v1 mount points: 
Cgroup v2 mount points: 
 - /sys/fs/cgroup
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```
