### ISSUE TITLE
Getting to run on SWMO without workarounds/hacks

### ISSUE THREAD

**Issue by JamiKettunen** [waydroid/waydroid#627]
I recently got Waydroid running in [SWMO (Sxmo Sway session)](https://sxmo.org/) on my [Lenovo IdeaPad Duet Chromebook](https://wiki.postmarketos.org/wiki/Lenovo_IdeaPad_Duet_Chromebook_(google-krane)) running postmarketOS:
<img src="https://user-images.githubusercontent.com/47358222/205460031-267c10ec-4fbc-400d-a0b8-6990074809b0.jpg" width="420" />

Along the way I noticed a few issues I thought were noteworthy enough to document here:
1. `XDG_RUNTIME_DIR` can be anywhere really, including under `/dev/shm/user/$(id -u)` like on Sxmo which required me to add `lxc.mount.entry = /dev/shm/user/10000 dev/shm/user/10000 none rbind,create=dir 0 0` to `/var/lib/waydroid/lxc/waydroid/config_nodes`; we need to start properly mounting only `XDG_RUNTIME_DIR` instead of a bunch of random dirs that could potentially contain it
   - These current "randomly mounted" dirs currently appear to contain at least `/run`, `/var/run` and `/tmp/run-*`
3. To avoid a `/system/bin/vold` crash `modprobe fuse` is needed before `waydroid show-full-ui`
   - The `loop` module [already needed manual probing](https://git.alpinelinux.org/aports/tree/community/waydroid/waydroid-container.initd#n16) to even mount the rootfs `*.img`'s and I don't think it makes sense to keep throwing more things to the Alpine OpenRC service when these could be issues anyone at least using [BusyBox coreutils](https://busybox.net/) could possibly encounter; can we start integrating loading modules required to start Waydroid if they're detected not present by some means? I also remembered [`nft_xfrm` on Pop!_OS](https://docs.waydro.id/usage/install-on-desktops#popos) requires manual probing, so that could also be solved at the same time by loading the required modules as a session (or just the container service?) is started.
   - Related `waydroid logcat` lines to `/system/bin/vold` crash:
```
12-03 00:50:49.447    26    26 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-03 00:50:49.447    26    26 F DEBUG   : Abort message: 'terminating with uncaught exception of type NSt3__14__fs10filesystem16filesystem_errorE: filesystem error: in directory_iterator::directory_iterator(...): No such file or directory [/sys/fs/fuse/connections]'
```

Possibly related (previous issue mentioning Sxmo/Swmo): #108

Cc. @aleasto @Quackdoc

**Comment by Quackdoc** [comment]
seems like it can be boiled down to 

- mount XDG_RUNTIME_DIR manually
- add fuse and loop modules to auto loading modules

**Comment by stacyharper** [comment]
I would think it is the Waydroid concern to mount what is exposed as XDG_RUNTIME_DIR and to at least check if required kernel modules are loaded (and to throw an understandable error if not).

**Comment by aleasto** [comment]
I tend to agree for the kernel modules.

For XDG_RUNTIME_DIR we have to add it to the list of LXC mounts ourselves.

However that happens as root while XDG_RUNTIME_DIR is per-user so i think I'll have to just add /dev/shm to the mounts

**Comment by stacyharper** [comment]
Making /dev/shm available in LXC container doesnt looks wrong. And that permit us to use it as XDG_RUNTIME_DIR and to works under waydroid.

About fuse, I guess we will just add the modprobe in aports recipe daemon.

**Comment by JamiKettunen** [comment]
As Waydroid should now simply work on Sxmo since [v1.3.4](https://github.com/waydroid/waydroid/commit/38aebb39e4e6fb6c9766d4cd3a11f74d42c9d683 I'll now close this ([v1.4.0](https://github.com/waydroid/waydroid/commit/c49dfd272d994b1cdaa14107fee66be84b80c06b) goes further with a dynamic `XDG_RUNTIME_DIR` detection finally!)

As for the `modprobe` situation [in the Alpine OpenRC service](https://git.alpinelinux.org/aports/tree/community/waydroid/waydroid-container.initd#n16) etc I've made #784 where that topic can continue :)
