### ISSUE TITLE
Physical-Keyboard not working

### ISSUE THREAD

**Issue by s4msy** [waydroid/waydroid#63]
System: Debian 11 gnome-wayland - Lineage-Container is from 09/20/2021
Running in Window-Mode

Physical Keyboard works for near 5 seconds and then stops. I was able to search in Settings, but searching in F-Droid or Aurora Store doesnt work.

Here is my Debug-Log using: 

waydroid logcat | grep keyboard

`lxc-attach: waydroid: terminal.c: lxc_terminal_create_native: 924 Not a directory - Failed to open terminal multiplexer device
09-22 07:22:48.061   129   296 D EventHub: No input device configuration file found for device 'wayland_keyboard'.
09-22 07:22:48.067   129   296 W EventHub: Unable to disable kernel key repeat for /dev/input/wl_keyboard_events: Not a typewriter
09-22 07:22:48.067   129   296 I EventHub: New device: id=1, fd=119, path='/dev/input/wl_keyboard_events', name='wayland_keyboard', classes=0x1, configuration='', keyLayout='/system/usr/keylayout/Generic.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false, 
09-22 07:22:48.070   129   296 I InputReader: Device added: id=1, name='wayland_keyboard', sources=0x00000101
09-22 07:22:48.837   129   129 W InputMethodUtils: No software keyboard is found. imis=[] systemLocale=de_DE fallbackLocale=null
09-22 07:22:49.483   354   354 D SystemUIBootTiming: StartServicescom.android.systemui.keyboard.KeyboardUI took to complete: 1ms
09-22 07:22:56.017   129   129 W InputMethodUtils: No software keyboard is found. imis=[] systemLocale=de_DE fallbackLocale=null`

If I read this correctly, my locales with de_DE are the troublemaker, fallbackLocale=null seems a problem.

EDIT: Found a solution, with `waydroid show-full-ui` the keyboard works flawless.

**Comment by firefoxlover** [comment]
For me it works now, using Fedora 37 KDE. It detects "wayland_keyboard", which uses the corret layout. Nonetheless it doesnt work at the beginning. What solved it for me was setting the keyboard language to my local language only instead of automatic, removing English in that case
