### ISSUE TITLE
Unable to install waydroid on ubunbu 22.10

### ISSUE THREAD

**Issue by AsumVictor** [waydroid/waydroid#630]
'  Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20221109-VANILLA-waydroid_x86_64-system.zip/download  '. When installing waydroid, the statement above appears.

**Comment by aleasto** [comment]
Yes. Indeed it's downloading the files.

**Comment by AsumVictor** [comment]
> Yes. Indeed it's downloading the files.

Downloaded system image hash doesn't match, expected: f2262a8109291104c56d4dcc777e2f7b8d5341c00a8ba7ba75dd71312b373d69
 please any help. It was downloading and unfortunately.

**Comment by Zer0C001** [comment]
Had the same issue on debian : 
"ERROR: Downloaded system image hash doesn't match, expected: ..."
running `waydroid init` again seems to fix it.
