### ISSUE TITLE
Cannot install waydroid 1.3.3 from repo

### ISSUE THREAD

**Issue by quantumstar1** [waydroid/waydroid#636]
When attempting to install Waydroid 1.3.3 I get the following error:

$ sudo apt install waydroid --fix-missing
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  waydroid
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 215 kB of archives.
After this operation, 411 kB of additional disk space will be used.
Get:1 https://repo.waydro.id jammy/main all waydroid all 1.3.3 [215 kB]
Err:1 https://repo.waydro.id jammy/main all waydroid all 1.3.3
  File has unexpected size (215128 != 215118). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:8b9b60ae2e0c68926505bd53d090f59d7075af9b1aaeec2bb2ca5916dbaaf821
   - SHA1:25a2443a3f067b8b55e6eeca69e7ca515b9d1885 [weak]
   - MD5Sum:4e898fa7802a4c2ee59a4f824e558141 [weak]
   - Filesize:215118 [weak]
E: Failed to fetch https://repo.waydro.id/erfan/jammy/waydroid_1.3.3_all.deb  File has unexpected size (215128 != 215118). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:8b9b60ae2e0c68926505bd53d090f59d7075af9b1aaeec2bb2ca5916dbaaf821
    - SHA1:25a2443a3f067b8b55e6eeca69e7ca515b9d1885 [weak]
    - MD5Sum:4e898fa7802a4c2ee59a4f824e558141 [weak]
    - Filesize:215118 [weak]
E: Internal Error, ordering was unable to handle the media swap

Ran sudo apt update multiple times

 - OS: Ubuntu 22.04 x64

**Comment by zerom-H** [comment]
Same issue with me

**Comment by gi2477111** [comment]
Same issue with me ...

**Comment by quantumstar1** [comment]
Why was this closed without an explanation? I'm still getting the error..

**Comment by secskb** [comment]
Same issue with me ...
