### ISSUE TITLE
Waydroid doesn't want to install

### ISSUE THREAD

**Issue by chetpwi** [waydroid/waydroid#640]
pls fix. idk what to do

here's the error log
Get:1 https://repo.waydro.id jammy/main all waydroid all 1.3.3 [215 kB]        
Err:1 https://repo.waydro.id jammy/main all waydroid all 1.3.3                 
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:b7b369ee30d1387b8d2eb4438f2578f2e0808c74de3b85c3ff335af754ce4810
   - SHA1:68f64fc21a6007eb902c3bde5eb646307a221453 [weak]
   - MD5Sum:db737d1cf8698d89a01c3fa60b30a132 [weak]
   - Filesize:215128 [weak]
  Hashes of received file:
   - SHA256:ffa2430447568870c2d212e6db1fdaa02212b3bdb90fb4104e72cd6de4c870ee
   - SHA1:168d496afbf5522c422d2d4e34b30d44d7e73a90 [weak]
   - MD5Sum:4c8c3da814a477f4b31d1d5a0fabc704 [weak]
   - Filesize:215128 [weak]
  Last modification reported: Sun, 11 Dec 2022 01:02:59 +0000
Fetched 215 kB in 15s (13.9 kB/s)                                              
E: Failed to fetch https://repo.waydro.id/erfan/jammy/waydroid_1.3.3_all.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:b7b369ee30d1387b8d2eb4438f2578f2e0808c74de3b85c3ff335af754ce4810
    - SHA1:68f64fc21a6007eb902c3bde5eb646307a221453 [weak]
    - MD5Sum:db737d1cf8698d89a01c3fa60b30a132 [weak]
    - Filesize:215128 [weak]
   Hashes of received file:
    - SHA256:ffa2430447568870c2d212e6db1fdaa02212b3bdb90fb4104e72cd6de4c870ee
    - SHA1:168d496afbf5522c422d2d4e34b30d44d7e73a90 [weak]
    - MD5Sum:4c8c3da814a477f4b31d1d5a0fabc704 [weak]
    - Filesize:215128 [weak]
   Last modification reported: Sun, 11 Dec 2022 01:02:59 +0000

**Comment by aleasto** [comment]
Done
