### ISSUE TITLE
init.rc: Keep /proc/sys/kernel/modprobe as is it

### ISSUE THREAD

**Issue by atmouse-** [waydroid/waydroid#642]
I think we shouldn't break host system's module auto-loads

in system/etc/init/hw/init.rc
```
on early-init

    # Android doesn't need kernel module autoloading, and it causes SELinux
    # denials.  So disable it by setting modprobe to the empty string.  Note: to
    # explicitly set a sysctl to an empty string, a trailing newline is needed.
    write /proc/sys/kernel/modprobe \n
```

Waydroid shared kernel with host environment, I consider `kernel.modprobe = /sbin/modprobe` should be required

**Comment by aleasto** [comment]
I see other procfs entires reading different values between the host procfs and the container procfs. How exactly does this work?

**Comment by atmouse-** [comment]
I found that /proc/sys should be mounted as read-only from [here](https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html#lbAU)
```
proc:mixed (or proc): mount /proc as read-write, but remount /proc/sys and /proc/sysrq-trigger read-only for security / container isolation purposes. 
```
🤔 the lxc config 
```
lxc.mount.auto = cgroup:ro sys:ro
lxc.mount.entry = proc proc proc nodev,nosuid,noexec,hidepid=2 0 0
```
bind mounting the same procfs as rw from my end

**Comment by atmouse-** [comment]
Seems this commit f5543df68651277042b156f19f5b3804c297f2a7 made a regress of procfs rw mode

found a similar issue https://github.com/lxc/lxc/issues/4075#issuecomment-1025860646 about procfs mounting options

**Comment by aleasto** [comment]
I see!
I'm unable to recreate that structure with `/proc/sys` read-only but `/proc/sys/net` writable.
LXC internally does this by temporarily mounting it RW on some location, then using MS_MOVE to move it back on top of the now RO `/proc/sys`: https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L703
But I can't figure out why that doesn't work if I do the same in `lxc.mount.entry`

I think i'll be reverting https://github.com/waydroid/waydroid/commit/f5543df68651277042b156f19f5b3804c297f2a7 as this has arguably higher priority than hidepid=2.
