### ISSUE TITLE
Windows appear offsetted

### ISSUE THREAD

**Issue by Shaarigan** [waydroid/waydroid#657]
Whenever I open Waydroid or an Android App, the window appears offset half the screen in both, X and Y direction.

Lenovo IdeaPad Flex 5 14ALC - Zorin OS 16.2
AMD Ryzen™ 5 5500U Prozessor (Hexa-Core)
16 GB DDR4-3200 SO-DIMM
AMD Radeon RX Vega 7
Both Waydroid (Vanilla, Gapps) Images

Installed a fresh Zorin OS 16.2 on the device today and setup a Waydroid instance. Don't know if that matters, I had to build the python3-gbinder module from source manually as of this post here https://github.com/waydroid/waydroid/issues/214#issuecomment-1120926304 but finally everything installed properly. I had the same issue regardless of if I used the gapps or vanilla image

**Comment by marat2509** [comment]
Same problem
![image](https://user-images.githubusercontent.com/93652988/211349183-7edbf2d4-d6b2-42e4-9f18-8e5c1f1db894.png)

**Comment by aleasto** [comment]
Waydroid requests a maximized window. It's not up to us to decide where the compositor will place it.
