### ISSUE TITLE
Cursor not showing up on window mode kde plasma

### ISSUE THREAD

**Issue by Richardsause** [waydroid/waydroid#66]
after running 
`waydroid prop set persist.waydroid.multi_windows true`

and restarting the container via systemctl, as said on the docs, on kde plasma the cursor wont show up while hovering over the android window, it also shows the android cursor while on non window mode, i am not sure if thats whats supposed to happen, but its worth mentioning.

some info:

waydroid:
`version 1.0.0`

my pc:
```
Debian sid 64 bits
Linux debian 5.14.0-1-amd64
Kde plasma wayland(of course)
Kde plasma version 5.21.5
Kde frameworks 5.86.0
qt 5.15.2
```

also very nice project, very smooth, and stupidly feature rich when comparing to the concurrency.

**Comment by PseudoDistant** [comment]
So this issue is Plasma's fault? ;-;

**Comment by vfosnar** [comment]
+1

**Comment by benklop** [comment]
> There's an experimental patch by erfanoabdi which will be upstreamed in next update if anyone facing same issue .

Did this ever get merged? Without a link to the patch it's hard to know. Also, it's unclear whether you're referring to a patch to waydroid or to KDE.

**Comment by benklop** [comment]
FYI I _think_ this refers to `waydroid prop set persist.waydroid.cursor_on_subsurface` mentioned in the waydroid documentation. That _does_ appear to still be necessary unfortunately.

**Comment by benklop** [comment]
also unfortunate, this workaroun seems to cause KDE's cursor to be shown in addition to the android one, and not just over the window but across the entire screen.
