### ISSUE TITLE
Waydroid does not launch at all

### ISSUE THREAD

**Issue by ddams2000** [waydroid/waydroid#671]
**Describe the bug**

Hello, waydroid does not launch, waydroid-container.service does not load.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.4-1 - Waydroid 
 - Images Version VANILLA 20221231

**Desktop (please complete the following information):**
 Operating System: Manjaro-ARM
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.12-1-MANJARO-ARM (64-bit)
Graphics Platform: Wayland
Processors: 2 × ARM Cortex-A53, 4 × ARM Cortex-A73
Memory: 3.6 Gio of RAM
Graphics Processor: Mali-G52
Product Name: Ugoos AM6b Plus

**Logs (please upload as file)**

 - Prop file : 
`sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=panfrost
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.3.4
ro.vndk.lite=true
ro.product.waydroid.model=Ugoos AM6b Plus`
 
- waydroid log : 
`(001830) [10:43:32] % mkdir -p /dev/binderfs
(001830) [10:43:32] % mount -t binder binder /dev/binderfs
(001830) [10:43:32] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/binderfs/binder /dev/binderfs/binder-control /dev/
(001830) [10:43:32] % modprobe -q ashmem_linux
(001830) [10:43:32] % chmod 666 -R /dev/binder
(001830) [10:43:32] % chmod 666 -R /dev/vndbinder
(001830) [10:43:32] % chmod 666 -R /dev/hwbinder
(001830) [10:43:32] Container manager is waiting for session to load
(001839) [10:43:44] Save session config: /var/lib/waydroid/session.cfg
(001839) [10:43:44] UserMonitor service is not even started
(001839) [10:43:44] Clipboard service is not even started
(001830) [10:43:45] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 35: which : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 37: which : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 39: which : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 41: which : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 48: which : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 91: -I : commande introuvable
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 213: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 214: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 215: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 216: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 217: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 218: -D : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 219: -t : commande introuvable
/usr/lib/waydroid/data/scripts/waydroid-net.sh: ligne 220: -t : commande introuvable
(001830) [10:43:45] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001830) [10:43:45] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001830) [10:43:45] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001830) [10:43:45] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001830) [10:43:45] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001830) [10:43:45] Save config: /var/lib/waydroid/waydroid.cfg
(001830) [10:43:45] % mount -o bind /home/dams/.local/share/waydroid/data /var/lib/waydroid/data
(001830) [10:43:45] % chmod 777 -R /dev/dri
(001830) [10:43:45] % chmod 777 -R /dev/fb0
(001830) [10:43:45] % chmod 777 -R /dev/video0
(001830) [10:43:45] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(001830) [10:43:45] New background process: pid=1902, output=background
(001830) [10:43:45] waiting 10 seconds for container to start...
lxc-start: waydroid: ../src/lxc/network.c: netdev_configure_server_veth: 711 No such file or directory - Failed to attach "vethr7OHBm" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: ../src/lxc/network.c: lxc_create_network_priv: 3427 No such file or directory - Failed to create network device
lxc-start: waydroid: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "waydroid"
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(001830) [10:43:46] waiting 9 seconds for container to start...
(001830) [10:43:47] waiting 8 seconds for container to start...
(001830) [10:43:48] waiting 7 seconds for container to start...
(001830) [10:43:49] waiting 6 seconds for container to start...
(001830) [10:43:50] waiting 5 seconds for container to start...
(001830) [10:43:51] waiting 4 seconds for container to start...
(001830) [10:43:52] waiting 3 seconds for container to start...
(001830) [10:43:53] waiting 2 seconds for container to start...
(001830) [10:43:54] waiting 1 seconds for container to start...
(001830) [10:43:55] ERROR: container failed to start
(001830) [10:43:55] See also: <https://github.com/waydroid>
(001830) [10:43:55] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 131, in start
    raise OSError("container failed to start")
OSError: container failed to start
(001936) [10:43:56] UserMonitor service is not even started
(001936) [10:43:56] Clipboard service is not even started
(001839) [10:43:56] UserMonitor service is not even started
(001839) [10:43:56] Clipboard service is not even started
(001937) [10:44:06] Starting waydroid session
(001937) [10:44:06] Save session config: /var/lib/waydroid/session.cfg
(001937) [10:44:06] UserMonitor service is not even started
(001937) [10:44:06] Clipboard service is not even started
(001942) [10:44:24] WayDroid container is STOPPED
(001947) [10:44:37] UserMonitor service is not even started
(001947) [10:44:37] Clipboard service is not even started
(001937) [10:44:38] UserMonitor service is not even started
(001937) [10:44:38] Clipboard service is not even started`

**Comment by profimedica** [comment]
Not a solution but try to kill the process or restart the service

```
killall waydroid
sudo systemctl restart waydroid-container sudo systemctl restart waydroid-container
```
# Failed to restart sudo.service: Unit sudo.service is masked.
# Failed to restart systemctl.service: Unit systemctl.service not found.
# Failed to restart restart.service: Unit restart.service not found.
```
waydroid session stop
waydroid session start
```
# Failed to start Clipboard manager service, check logs
# Service manager /dev/anbox-binder has appeared
# Android with user 0 is ready

**Comment by ddams2000** [comment]
Thank you, i try it but no sucess...

**Comment by aleasto** [comment]
Your log is unreadable...
But it should be enough to `sudo apt install debianutils` or `sudo apt install which`. I don't know what's going on at debian.

**Comment by ddams2000** [comment]
> ur log is unreadable...
> But it should be enough to

Thank you very much it works !

**Comment by joshb019919** [comment]
> Thanks, I tried but no success.

I'd recompiled to a different kernel than the one that came standard and had to follow the instructions here: [Github](https://github.com/waydroid/waydroid/issues/590) to clone this repo for [Anbox](https://github.com/choff/anbox-modules) then do the `waydroid init -f` to redownload the necessary files.
