### ISSUE TITLE
Can not install on debian sid. Dependencies is broken.

### ISSUE THREAD

**Issue by songww** [waydroid/waydroid#679]
**Describe the bug**
Can not install on debian sid. Dependencies is broken.
python3 on Debian sid has been upgrade to python3.11, but python3-gbinder depends on python3.10.

**Logs**

```
The following packages have unmet dependencies:
 waydroid : Depends: python3-gbinder but it is not installable
The following actions will resolve these
dependencies:

     Keep the following packages at their curren
1)     waydroid [Not Installed]
```

**Desktop (please complete the following information):**
 - OS: Debian Sid x64

**Comment by aleasto** [comment]
Done
