### ISSUE TITLE
Alternate installation commands

### ISSUE THREAD

**Issue by glennsantos** [waydroid/waydroid#68]
I had an issue installing waydroid. Got these alternate commands from a user in HN. I'm using Ubuntu Focal

DISTRO="focal"
sudo curl https://repo.waydro.id/waydroid.gpg -o /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list
sudo apt update
sudo apt install waydroid

maybe we can add this in the documentation
source: https://news.ycombinator.com/item?id=28625188

**Comment by aleasto** [comment]
Done
