### ISSUE TITLE
waydroid init always failed while downloading the lineage image

### ISSUE THREAD

**Issue by butterl** [waydroid/waydroid#685]
**Describe the bug**
waydroid init always failed while downloading the lineage image

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [1.3.4]
 - Waydroid Images Version [20230107-VANILLA]

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04 x64]
 - GPU: [NA]
 - Kernel version: [5.15.0-57-generic (buildd@lcy02-amd64-110)]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
cat /var/lib/waydroid/waydroid_base.prop
cat: /var/lib/waydroid/waydroid_base.prop: No such file or directory
```
 - Output of `waydroid log`
```
```
$ sudo waydroid --details-to-stdout init 
(468142) [09:16:13] Save config: /var/lib/waydroid/waydroid.cfg
(468142) [09:16:16] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230107-VANILLA-waydroid_x86_64-system.zip/download
[Downloading]   4.33 MB/766.49 MB       0.68 kbps(approx.) (468142) [09:30:14] Validating system image
(468142) [09:30:14] ERROR: Downloaded system image hash doesn't match, expected: ffeb6ec321c60e683f733a2c0391a7c55a7618d8caa11f7baf02207ad57fd73b
(468142) [09:30:14] See also: <https://github.com/waydroid>
(468142) [09:30:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 119, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 43, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: ffeb6ec321c60e683f733a2c0391a7c55a7618d8caa11f7baf02207ad57fd73b
```
```
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
```
ERROR: WayDroid is not initialized, run "waydroid init
```

**Comment by butterl** [comment]
not sure what happened, I download the image with IDM and use waydroid init -f to avoid this issue

**Comment by Gonharaka** [comment]
> not sure what happened, I download the image with IDM and use waydroid init -f to avoid this issue

how to install idm in linux , did you use wine

**Comment by mian196** [comment]
i had same problem today wasted 5 to 6 hrs downloading same image and again but well sourceforge is garbage when it comes to select the good mirror to download , in my case i choose usa server any of them works fine or go with versa web , then same step put it in custom folder to initialize it
