### ISSUE TITLE
waydroid init always failed while downloading the lineage image

### ISSUE THREAD

**Issue by butterl** [waydroid/waydroid#686]
**Describe the bug**
waydroid init always failed while downloading the lineage image

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [1.3.4]
 - Waydroid Images Version [20230107-VANILLA]

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04 x64]
 - Kernel version: [5.15.0-57-generic (buildd@lcy02-amd64-110)]

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
cat /var/lib/waydroid/waydroid_base.prop
cat: /var/lib/waydroid/waydroid_base.prop: No such file or directory
```
 - Output of `waydroid log`
```
$ sudo waydroid --details-to-stdout init 
(468142) [09:16:13] Save config: /var/lib/waydroid/waydroid.cfg
(468142) [09:16:16] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230107-VANILLA-waydroid_x86_64-system.zip/download
[Downloading]   4.33 MB/766.49 MB       0.68 kbps(approx.) (468142) [09:30:14] Validating system image
(468142) [09:30:14] ERROR: Downloaded system image hash doesn't match, expected: ffeb6ec321c60e683f733a2c0391a7c55a7618d8caa11f7baf02207ad57fd73b
(468142) [09:30:14] See also: <https://github.com/waydroid>
(468142) [09:30:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 119, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 43, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: ffeb6ec321c60e683f733a2c0391a7c55a7618d8caa11f7baf02207ad57fd73b
```

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
```
ERROR: WayDroid is not initialized, run "waydroid init
```

**Comment by nopxjs** [comment]
how you fix it

**Comment by butterl** [comment]
> how you fix it

download with wget then do waydroid init with predownloaded image bypassed th issue

**Comment by z0xyz** [comment]
@butterl  can you elaborate more on it?

**Comment by butterl** [comment]
@z0xyz 

from error log like this，
wegt https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230107-VANILLA-waydroid_x86_64-system.zip

and then waydroid init -i $image_path_downloaded

(468142) [09:16:16] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230107-VANILLA-waydroid_x86_64-system.zip/download

**Comment by z0xyz** [comment]
@butterl Alright thanks. I found this method [helpful](https://www.reddit.com/r/Fedora/comments/16qt4bj/comment/k1z1yl2/?utm_source=share&utm_medium=web2x&context=3) as well
