### ISSUE TITLE
Potential nvidia support by choosing mesa driver (zink, aka OpenGL over vulkan)

### ISSUE THREAD

**Issue by commandblock2** [waydroid/waydroid#688]
**Is your feature request related to a problem? Please describe.**
I'm ? when I see an opportunity that there are some potential hardware accelerated solution for nvidia users.
I don't know a lot about these things though.

**Describe the solution you'd like**
Add a option for the user to choosing the mesa driver, possibly in the config files.
If we are not talking about waydroid, with other programs we can use a few environmental variable to override which mesa driver to use. For example
`__GLX_VENDOR_LIBRARY_NAME=mesa MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink glxgears`

IIRC android uses egl instead of glx? not sure if that will make any difference. 

**Describe alternatives you've considered**
previously mentioned [virgl](https://github.com/waydroid/waydroid/issues/564) and [libnvidia-container](https://github.com/waydroid/waydroid/issues/650)
It would only need minimal change if the zink driver could work.

**Additional context**
I personally is not capable of launching any program with the mesa zink driver (glxgears for example) at the moment, it always crash within `zink_dri.so`.
If anyone can try with the zink driver I would be grateful.
https://wiki.archlinux.org/title/OpenGL#OpenGL_over_Vulkan_(Zink)

**Comment by Quackdoc** [comment]
this may be useful if we could get vulkan working in the guest, but as it stands it wouldnt do anything, this might change when NVK + nouveau kernel driver come to fruition

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> this may be useful if we could get vulkan working in the guest, but as it stands it wouldnt do anything, this might change when NVK + nouveau kernel driver come to fruition

Sorry NVK driver is already merged into Mesa3D and linux 6.7 Nouveau DRM driver already contains a GSP firmware support implementation, GSP blobs is already in Linux Firmware

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> this may be useful if we could get vulkan working in the guest, but as it stands it wouldnt do anything, this might change when NVK + nouveau kernel driver come to fruition

Is not possible to internal layered drivers communicate out of the sandbox?
Zink looks to just need to use Vulkan ICD for loading driver and dispatch calls
