### ISSUE TITLE
waydro.id: installation instructions not correct

### ISSUE THREAD

**Issue by netikras** [waydroid/waydroid#69]
## Problem
> Replace DISTRO="bullseye" with your current target. Options: focal, bullseye, hirsute
```
export DISTRO="bullseye" && \
curl https://repo.waydro.id/waydroid.gpg | sudo tee /usr/share/keyrings/waydroid.gpg && \ 
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
```

An unprivileged user usually has no WRITE permissions to anything `/usr/**` and `/etc/**`. This is why this very first step is going to fail - neither key nor repo coordinates will be persisted.

And judging from the `sudo` in the last command (`sudo apt update`) you are not giving instructions for the root shell (a preceding `#` or `$` would clarify this ambiguity).

## Proposal
I propose changing this oneliner into:

```
# export DISTRO="bionic" && \
curl https://repo.waydro.id/waydroid.gpg | tee /usr/share/keyrings/waydroid.gpg && \ 
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | tee /etc/apt/sources.list.d/waydroid.list && \
sudo apt update
```

or (preferably)

```
$ curl -s https://repo.waydro.id/waydroid.gpg | sudo tee /usr/share/keyrings/waydroid.gpg >/dev/null
$ DISTRO=bullseye echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list
$ sudo apt update
```

## Motivation
Oneliners, while a witty-nitty looking approach, are more cryptic and a PITA to work with when either of the commands needs to be altered/debugged. Also, if `sudo` session is not open, oneliner messes up the password prompt. Splitting a oneliner into clearly separated commands adds some clarity and makes it easier to customize things. Prefixing each command (line) with either `#` or `$` makes it clear which shell these commands are to be run in. And `sudo tee` is just fixing the mistake in given commands.

## P.S.
```
Err:38 https://repo.waydro.id bionic Release        
  404  Not Found [IP: 192.243.103.185 443]
Reading package lists... Done
E: The repository 'https://repo.waydro.id bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by AdnanHodzic** [comment]
Seems related to what was mentioned in #57

**Comment by netikras** [comment]
> Seems related to what was mentioned in #57

Indeed it is

**Comment by aleasto** [comment]
Done
