### ISSUE TITLE
How do I resize window?

### ISSUE THREAD

**Issue by tazihad** [waydroid/waydroid#700]
Sorry for making a Bug report. But I can't find any information on the internet.
My monitor size 1600x900. 
I have set waydroid resolution 720x1280.
But the window is bigger than my monitor. I also can't resize window. Anyway I can resize the window to fit my monitor? I want to have a vertical phone screen.
I am using Fedora KDE Kinoite.

![Screenshot_20230117_203405](https://user-images.githubusercontent.com/19417232/212927083-8a388c4c-579c-44dc-84cd-e50437a6ce99.png)

**Comment by tazihad** [comment]
@cniw That's very helpful. But display resolution of waydroid becomes 606x900 pixels. Is there anyway I can make 1920x1080 display fit in my monitor. I could resize it in emulators on windows.

**Comment by cniw** [comment]
from your screenshot above the screen density = 180 dpi,
you can decrease it's value if you want higher result
- edit this file `sudo nano /var/lib/waydroid/waydroid_base.prop`
- add this line `ro.sf.lcd_density=100` (adjust this value until you get result like you want)
- save it Ctrl+O, exit Ctrl+X
- restart waydroid

**Comment by tazihad** [comment]
If I set `ro.sf.lcd_density=100`. The device physical size becomes 21 inches. And fonts becomes too small. I have set `ro.sf.lcd_density=403` to Emulate 1080p display Redmi Note 3. Physical Size 5.5 inch. But as you can see the display is too big for my monitor.
Thanks again for helping with your precious time.
![Screenshot_20230118_003507](https://user-images.githubusercontent.com/19417232/212983016-1bf08ae3-2501-4474-a55f-809b3ef7aa64.png)

**Comment by mazunki** [comment]
So there's no way to resize the window dynamically after launch, and no way to stretch the contents of the window to expand/shrink to the window's size?

**Comment by rocketraman** [comment]
> reset to default setting, this will make waydroid fullscreen
> 
> waydroid prop set persist.waydroid.width ""
> waydroid prop set persist.waydroid.height ""
> make portrait orientation on 1600x900 screen, 16:9 aspect ratio
> 
> * width = 900 / 16 * 9 = 506.25 ~ 506
> 
> waydroid prop set persist.waydroid.width 506
> to apply that changes you need restart
> 
> * waydroid container `sudo waydroid restart waydroid-container` or
> * at lease waydroid session `waydroid session stop`
> 
> then click waydroid icon laucher to start it again

This helps, but one thing to note is that each waydroid application window has to be resized after restart -- if it was smaller before due to experimentation it will remain smaller until resized. However, dynamic resizing is still not possible -- once the Window has been resized to the configured size, it cannot be resized again.
