### ISSUE TITLE
Waydroid images have been deleted from SourceForge

### ISSUE THREAD

**Issue by kode54** [waydroid/waydroid#703]
**Describe the bug**
All of the files have been deleted from the SourceForge images repository.

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.4-1
 - Waydroid Images Version can't install because they no longer exist

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: Intel Arc A770 16GB
 - Kernel version: linux-tkg-cfs 6.2-rc4-273
 - Host mesa version: mesa git 23.1
 - Desktop: Gnome 43.2

**Comment by RarogCmex** [comment]
I can confirm it. I see no files.

**Comment by manu-romero-411** [comment]
Yeah, it has been having troubles for me, starting an hour ago. No files in SourceForge. Kinda strange.

**Comment by fabian-st** [comment]
Can confirm this issue

**Comment by r1979** [comment]
I can confirm it too

**Comment by RarogCmex** [comment]
Now I am able to download GAPPS version. Still there are questions about sourceforge's reliability.

**Comment by reivilibre** [comment]
Downloading the required files from sourceforge is being very flaky at the moment. For a few seconds I'll get a good speed, then it usually drops off and eventually cuts off the download. (Unfortunately there doesn't seem to be a way to resume the downloads.)

```
# waydroid init
[22:23:22] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20230120-MAINLINE-waydroid_x86_64-vendor.zip/download
[Downloading]   7.47 MB/165.42 MB     369.39 kbps(approx.)[22:25:57] Validating vendor image
[22:25:57] ERROR: Downloaded vendor image hash doesn't match, expected: 06b906344cac368bb4cbeafa01196cd59d49526e646b816919a6abec990673e7
[22:25:57] See also: <https://github.com/waydroid>
 Run 'waydroid log' for details.
```

This in combination with this issue makes me wonder if sourceforge is just being unreliable. My connection isn't excellent but it's not so bad that it would repeatedly fail a simple HTTPS download.

**Comment by aleasto** [comment]
Sourceforge had issues, then GitHub pages had issues.
This is now resolved.
