### ISSUE TITLE
Turn on all effects by default

### ISSUE THREAD

**Issue by kde-yyds** [waydroid/waydroid#708]
Some effects, like blur is missing on waydroid.

**Comment by JamiKettunen** [comment]
Can you provide an example of what it should look like? Do keep in mind latest Waydroid images are still Android 11, so this "blur" you're talking about might've only been introduced in Android 12, in which case this issue is a bit pointless

**Comment by JamiKettunen** [comment]
Also keep in mind the images are based on LineageOS, so whatever fancy effects other Android distributions (ROMs) might have potentially won't exist in LOS.

**Comment by kde-yyds** [comment]
It seems that Lineage doesn't have a blur effect.Closing it
