### ISSUE TITLE
Waydroid Not work correctly

### ISSUE THREAD

**Issue by RinLin-NYA** [waydroid/waydroid#710]
**Describe the bug**
The waydroid GUI would not show up in any way, and I have tried the way all in #61 and it did not work either.

**Screenshots**
![图片](https://user-images.githubusercontent.com/87124071/213900319-7f7b14dd-b87d-4d64-a5ba-ef125d1be618.png)

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.4
 - Waydroid Images Version GAPPS 20230121

**Desktop (please complete the following information):**
 - OS: Arch Linux rolling
 - GPU: AMD Radeon R7 260X
 - Kernel version: 6.1.7-zen1-1-zen
 - Host mesa version: mesa 22.3.3
 - Desktop: GNOME Wayland 43.5

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
 - Output of `waydroid log`
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
[log.zip](https://github.com/waydroid/waydroid/files/10473749/log.zip)

**Comment by aleasto** [comment]
From your logs:
```
ro.hardware.gralloc=default
ro.hardware.egl=mesa
```

This configuration is invalid. Mesa requires `gbm`. 
Revert back to the stock configuration (`sudo waydroid upgrade --offline`) and share a new logcat

**Comment by WaessrigesFuchs** [comment]
I have a similar problem
I changed my configuration to `ro.hardware.egl=minigbm_gbm_mesa` as its required for some things to be visible
Since the latest update it doesnt boot with this config anymore

**Comment by RinLin-NYA** [comment]
> From your logs:
> 
> ```
> ro.hardware.gralloc=default
> ro.hardware.egl=mesa
> ```
> 
> This configuration is invalid. Mesa requires `gbm`. Revert back to the stock configuration (`sudo waydroid upgrade --offline`) and share a new logcat

I have rolled back to Windows 10.
I will try this when I back to Arch Linux.
Now I will close this issue.

**Comment by Congee** [comment]
Hi, can this issue be reopened? I am experiencing the same issue.

Actually, the screen shows and egl works. But, immediately the screen dims off. Resizing the window lights up the screen momentarily but it still dims off immediately. So, I guess it's related to how the vm captures focus event or config is not appropriate in the android vm.
