### ISSUE TITLE
modprobe: FATAL: Module binder_linux not found in Ubuntu v22.04.1 on WSL2

### ISSUE THREAD

**Issue by LOuroboros** [waydroid/waydroid#712]
**Describe the bug**

After installing Waydroid on WSL2, I try to boot it up by typing `sudo waydroid init` inside the terminal. However, I'm greeted with this:

>lunos:~$ sudo waydroid init
> [22:59:35] Failed to load binder driver
> [22:59:35] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.102.1-microsoft-standard-WSL2
> [22:59:35] ERROR: Binder node "binder" for waydroid not found
> [22:59:35] See also: <https://github.com/waydroid>
> Run 'waydroid log' for details.

I use Windows 10 21H1 x64 with Ubuntu 22.04.1 on WSL2 as I said in the title, with the WSL Kernel v5.10.102.1.

Also, for whatever it's worth, my installation is as up-to-date as it can be. I think.
I did perform a `sudo do-release-upgrade` and a `sudo apt update && sudo apt upgrade` as well.

I was hoping that maybe I could get this running on Windows 10 via WSL with VcXsrv providing the visual feedback, which is how I already use a certain Linux application on my Windows installation.

I did read [this article](https://docs.anbox.io/userguide/install_kernel_modules.html) over here that supposedly teaches how to install that module manually, but sadly it just doesn't work.
After typing `sudo add-apt-repository ppa:morphis/anbox-support` in the terminal, this is what I get:

>Repository: 'deb https://ppa.launchpadcontent.net/morphis/anbox-support/ubuntu/ jammy main'
>More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
>Adding repository.
>Press [ENTER] to continue or Ctrl-c to cancel.
>Adding deb entry to /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-jammy.list
>Adding disabled deb-src entry to /etc/apt/sources.list.d/morphis-ubuntu-anbox-support-jammy.list
>Adding key to /etc/apt/trusted.gpg.d/morphis-ubuntu-anbox-support.gpg with fingerprint CFD4CCDE77B82D4FA3B113E521C6044A875B67B7
>Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
>Hit:2 https://apt.devkitpro.org stable InRelease
>Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
>Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
>Ign:5 https://ppa.launchpadcontent.net/morphis/anbox-support/ubuntu jammy InRelease
>Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
>Err:7 https://ppa.launchpadcontent.net/morphis/anbox-support/ubuntu jammy Release
>  404  Not Found [IP: 185.125.190.52 443]
>Hit:8 https://repo.waydro.id jammy InRelease
>Reading package lists... Done
>E: The repository 'https://ppa.launchpadcontent.net/morphis/anbox-support/ubuntu jammy Release' does not have a Release file.
>N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>N: See apt-secure(8) manpage for repository creation and user configuration details.

I'd understand if this was not officially supported. Feel free to close the Issue ticket if so.

**Comment by JamiKettunen** [comment]
Don't read Anbox documentation, Waydroid is a completely separate project and the FOSS Anbox is completely dead at this point which explains why the repo/support for Ubuntu 22.04 (`jammy`) isn't present there, remove the broken repository entirely.

I doubt you've read the WSL note in https://t.me/WayDroid since you're here and looking at the kernel version identifier, but you'll need a custom kernel configuration to get Waydroid running due to missing features.

To make it easier (and more maintainable) for others if you don't mind could you contribute changes like the following to https://github.com/beghem/WSL2-Linux-Kernel-Builder as a `waydroid.config` (with respective tweaks to `.github/workflows/build.yml` and `README.md`) after verifying it works?
```
CONFIG_PSI=y
# CONFIG_PSI_DEFAULT_DISABLED is not set
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES=""
CONFIG_ASHMEM=y
```
You can use the `can.config` workflow config example to get `waydroid.config` applied.

These changes would be applied on top of e.g. https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.10.y/Microsoft/config-wsl by the repo and once done you can download a kernel built on GitHub Actions as an artifact.

**Comment by LOuroboros** [comment]
> remove the broken repository entirely.

Got it. I removed it as soon as I got the error really, otherwise I wouldn't be able to keep using `sudo apt update && sudo apt upgrade`  👀 👍  

> I doubt you've read the WSL note in https://t.me/WayDroid

I don't use a phone and Telegram requires one, not to mention I wasn't even aware of that... chat room(?), so yeah.

> To make it easier (and more maintainable) for others if you don't mind could you contribute changes like the following to https://github.com/beghem/WSL2-Linux-Kernel-Builder as a `waydroid.config` (with respective tweaks to `.github/workflows/build.yml` and `README.md`) after verifying it works?
> ```
> CONFIG_PSI=y
> # CONFIG_PSI_DEFAULT_DISABLED is not set
> CONFIG_ANDROID=y
> CONFIG_ANDROID_BINDER_IPC=y
> CONFIG_ANDROID_BINDERFS=y
> CONFIG_ANDROID_BINDER_DEVICES=""
> CONFIG_ASHMEM=y
> ```
> You can use the can.config workflow config example to get waydroid.config applied.

I can give it a shot, but I'm actually a noob so I won't make any promises 😂 ...

I don't think it's going to work out nicely though. Checking the Actions history for that custom kernel I see that the 3 last attempts of GH Actions at compiling it have failed, and the project hasn't been touched in the past 3 months either.

Does this look correct? GH Actions must be running already so I'll check if manages to compile a copy successfully later.

https://github.com/LOuroboros/WSL2-Linux-Kernel-Builder/commit/fc7b6b510f2388ace2dfcc377b31f05759338dd7

**Comment by JamiKettunen** [comment]
Seems 5.4 kernel failed to build due to the following, which in turn skipped both 5.10 and 5.15 kernel builds:
```
 arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table
make[2]: *** [scripts/Makefile.build:344: arch/x86/entry/thunk_64.o] Error 1
```

**Comment by 00prometheus** [comment]
On WSL2, Windows10:

```
$ sudo apt install curl ca-certificates -y
$ curl https://repo.waydro.id | sudo bash
$ sudo apt install waydroid
$ sudo waydroid init
[16:30:16] Failed to load binder driver
[16:30:16] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.102.1-microsoft-standard-WSL2
[16:30:16] ERROR: Binder node "binder" for waydroid not found
[16:30:16] See also: <https://github.com/waydroid>
```
Someone closed this thread. Is this documented somewhere else?

**Comment by LOuroboros** [comment]
> Someone closed this thread. Is this documented somewhere else?

As you can see above, it was closed as "Not planned" which is equivalent to, among other things, "won't fix". In other words, the developers won't spend any time trying to get Waydroid working on WSL2, so you're basically on your own.

**Comment by Pinaz993** [comment]
> > Someone closed this thread. Is this documented somewhere else?
> 
> As you can see above, it was closed as "Not planned" which is equivalent to, among other things, "won't fix". In other words, the developers won't spend any time trying to get Waydroid working on WSL2, so you're basically on your own.

@00prometheus To put a finer point on it, they can't force Microsoft to add those modules, and patching the kernel to add modules needed for Waydroid to work is out of scope of the project. They might want to support WSL2, but there's no good solution to the problem from this end.

That being said, it might still be a solvable problem, you'll just have to look elsewhere. I'm doing so right now, so I'll try to remember to let you know what I come up with if I succeed.

**Comment by CesarFRR** [comment]
SOLVED!! --> https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install/

**Comment by CesarFRR** [comment]
SOLVED HERE: https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install/

**Comment by kairusds** [comment]
> SOLVED HERE: https://www.reddit.com/r/linux4noobs/comments/rdpsz4/driver_problem_while_attempting_to_install/
> 
> The user: Jazzlike-Researcher5 has the answer

You still need a custom kernel since the wsl2 kernel doesn't have the headers available.
