### ISSUE TITLE
Multiwindow stuck at android starting window

### ISSUE THREAD

**Issue by nitanmarcel** [waydroid/waydroid#713]
**Describe the bug**
When enabling multiwindow, waydroid boot animation appears and it gets stuck there, and no other windows are shown, unless you try to open an app again, then the app starts, and after a 1 second it freezes

**Screenshots**
![image](https://user-images.githubusercontent.com/41646249/214277587-0a9545b6-d788-46c6-b9ac-17d11bf65d14.png)
![image](https://user-images.githubusercontent.com/41646249/214278046-da3cd7ae-80c6-4b1c-aa8f-92a297c79a25.png)

**General information (please complete the following information):**
 - Waydroid tools Version: `master` branch
 - Waydroid Images Version: VANILLA 20230121

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04 x64
 - GPU: AMD Radeon Vega 10 Graphics
 - Kernel version: 6.1.7-x64v3-xanmod1
 - Host mesa version: Mesa 22.0.5
 - Desktop: Gnome 42.5

**Logs (please upload as file)**
[logcat.txt](https://github.com/waydroid/waydroid/files/10489065/logcat.txt)

**Comment by nitanmarcel** [comment]
# Same thing with extensions disabled, or/and software rendering

![image](https://user-images.githubusercontent.com/41646249/214280658-897447c7-6ecd-415d-91c0-ca1591be41fb.png)

**Comment by IAmTheRedSpy** [comment]
I have the same issue.

- OS: Kubuntu 22.10 x64
- GPU: NVidia RTX 3060 Ti, using software rendering
- Kernel version: 5.19.0-29-generic (64-bit)
- Video Drivers: NVIDIA 525.78.01
- Desktop: KDE Plasma 5.25.5

**Comment by aleasto** [comment]
How are you starting waydroid? `waydroid session start`, `waydroid show-full-ui` or launching an app?

Please test all three and report back findings

**Comment by IAmTheRedSpy** [comment]
It happens for me with both `waydroid show-full-ui` and launching from the application menu. I'll try the third way later.

**Comment by aleasto** [comment]
> It happens for me with both `waydroid show-full-ui` and launching from the application menu. I'll try the third way later.

Please be more explicit about your steps and define `It`

**Comment by nitanmarcel** [comment]
> How are you starting waydroid? `waydroid session start`, `waydroid show-full-ui` or launching an app from applications menu?
> 
> Please test all three and report back findings

I'm pretty sure I just restarted the container via systemd and just opened an app. Anyway, by starting the session via the terminal, then opening an app, seems to have not freezed waydroid at the boot animation but after the app open

![image](https://user-images.githubusercontent.com/41646249/215161647-d26655a6-d6ba-4a67-94a7-d20637777f93.png)

**Comment by nitanmarcel** [comment]
Also to point out. I've been getting those system has stopped dialogs from time to time, but I couldn't click any of the buttons on it

**Comment by nitanmarcel** [comment]
> > It happens for me with both `waydroid show-full-ui` and launching from the application menu. I'll try the third way later.
> 
> Please be more explicit about your steps and define `It`.
> 
> Example: I run `waydroid show-full-ui`, I wait for <...>, I see <...>. Then I start <...>and <...> happens. Alternatively, a video capture would help.

With `waydroid show-full-ui` I get greeted by the launcher, and the systemui isn't responding dialog

![image](https://user-images.githubusercontent.com/41646249/215162208-f727ef32-3600-42f9-b72c-14ba464a459b.png)

**Comment by nitanmarcel** [comment]
> Yes because freezing is totally unrelated
> 
> EDIT: Unless the reason that the "Phone is starting" window never closes it's because it's already frozen. But that's not what i get from your original message

It is most likely related. It seems that its either freezing after the boot was complete, or before. Or maybe better said, when System UI starts, or after it starts

**Comment by nitanmarcel** [comment]
This logcat could hopefully give more information than the one in the original post.

[logcat.txt](https://github.com/waydroid/waydroid/files/10521844/logcat.txt)

**Comment by aleasto** [comment]
> > > It happens for me with both `waydroid show-full-ui` and launching from the application menu. I'll try the third way later.
> > 
> > 
> > Please be more explicit about your steps and define `It`.
> > Example: I run `waydroid show-full-ui`, I wait for <...>, I see <...>. Then I start <...>and <...> happens. Alternatively, a video capture would help.
> 
> With `waydroid show-full-ui` I get greeted by the launcher, and the systemui isn't responding dialog
> 
> ![image](https://user-images.githubusercontent.com/41646249/215162208-f727ef32-3600-42f9-b72c-14ba464a459b.png)

That looks like it would happen without multi-windows too, no?

**Comment by nitanmarcel** [comment]
> Consider trying `rm -rf ~/.local/share/waydroid/data` if not done already

hmm, was done before enabling multi window. Now if I delete it, and run with multiwindow already enabled, it just freezes gnome, and I have to reboot

**Comment by nitanmarcel** [comment]
> > > > It happens for me with both `waydroid show-full-ui` and launching from the application menu. I'll try the third way later.
> > > 
> > > 
> > > Please be more explicit about your steps and define `It`.
> > > Example: I run `waydroid show-full-ui`, I wait for <...>, I see <...>. Then I start <...>and <...> happens. Alternatively, a video capture would help.
> > 
> > 
> > With `waydroid show-full-ui` I get greeted by the launcher, and the systemui isn't responding dialog
> > ![image](https://user-images.githubusercontent.com/41646249/215162208-f727ef32-3600-42f9-b72c-14ba464a459b.png)
> 
> That looks like it would happen without multi-windows too, no?

Nope, without multi-windows everything works fine. I get no freezes

**Comment by nitanmarcel** [comment]
> Consider trying `rm -rf ~/.local/share/waydroid/data` if not done already

Oh, doing this and running `waydroid session start` then opening an app, seems to work. But all of the windows are big with no way to resize them

![image](https://user-images.githubusercontent.com/41646249/215164020-413f9d3a-a3eb-42c8-9c98-59d9cc893066.png)

**Comment by aleasto** [comment]
You're not using multi-windows anymore

**Comment by nitanmarcel** [comment]
> You're not using multi-windows anymore

Yeah, I just checked it now. The freeze is back

**Comment by aleasto** [comment]
Host or just waydroid?
Also check dmesg for GPU faults

**Comment by nitanmarcel** [comment]
This logcat could hopefully give more information than the one in the original post.

[logcat.txt](https://github.com/waydroid/waydroid/files/10521844/logcat.txt)


> Host or just waydroid? Also check dmesg for GPU faults

Waydroid. I also did a dmesg -w after restarting waydroid via systemd, search for the keywords `mesa`, `gpu`, `amd` and nothing showed up. Actually all the dmesg I get after opening an android app, comes from waydroid

**Comment by aleasto** [comment]
idk i cannot reproduce this at all,  and still think it might be issue #585

**Comment by aleasto** [comment]
it seems to only happen on ubuntu, like you two

**Comment by nitanmarcel** [comment]
> idk i cannot reproduce this at all, and still think it might be issue #585

Most likely related to the linked issue. With software rendering enabled, I can interact with waydroid (sometimes) but only for a few seconds until it freezes again.

**Comment by nitanmarcel** [comment]
Also after enabling software rendering, some the previous open window crashes after a few seconds from opening a new one with a different app

[logcat.txt](https://github.com/waydroid/waydroid/files/10522170/logcat.txt)

**Comment by aleasto** [comment]
Well the good news is that i can reproduce this ANR in Ubuntu over KVM (and can't in Fedora over KVM)

**Comment by aleasto** [comment]
Bisected to: https://github.com/waydroid/android_hardware_waydroid/pull/21/files

**Comment by nitanmarcel** [comment]
> Bisected to: [waydroid/android_hardware_waydroid#21](https://github.com/waydroid/android_hardware_waydroid/pull/21)

I can confirm  that I'm not able to use waydroid with `persist.waydroid.use_subsurface=true` giving the same results as `persist.waydroid.multi_windows=true`

![image](https://user-images.githubusercontent.com/41646249/215277852-ca55b575-3492-4678-8cbb-42a7582839cf.png)

**Comment by aleasto** [comment]
Fixed for next build
