### ISSUE TITLE
Missing radeonsi driver for arm64

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#719]
**Describe the bug**
The new Lineage18.1 images fail to start with "mesa" and "gbm", they succeed with "swiftshader" and "default" set in "waydroid_base.prop". This does not happen with Lineage17.1 images.

**General information**
 Waydroid tools Version: 1.3.4 
 Waydroid Images Version: 
 Vendor: lineage-18.1-20230120-MAINLINE-waydroid_arm64-vendor
 System: lineage-18.1-20230128-VANILLA-waydroid_arm64-system

**Desktop**
 OS: Void Linux ARM64
 CPU: NXP LayerScape LX2160A Cortex-A72 ARM (16 cores 16 threads) 
 GPU: AMD Radeon RX580 XFX
 Motherboard: SolidRun HoneyComb LX2K
 Kernel version:  5.19.7 (SolidRun Vendor kernel)
 Host mesa version: 22.2.4
 Desktop: dwm (Suckless dynamic window manager)

**Additional context**
I am running weston inside of Xorg, could this be the issue?
Lineage18.1 images work just fine on my RockPro64 that also runs Void Linux ARM64, waydroid there is making use of mesa and gbm and uses ro.hardware.vulkan=panfrost instead of ro.hardware.vulkan=radeon.
Using the Void Linux Distro kernel on the HoneyComb LX2K doesn't work as /dev/binder isn't found.
I am using the config of the Distro kernel in the Vendor Kernel which fixes the issue of /dev/binder not being found.

**Logs**

Waydroid log:
 
[lineage18.1-waydroid-log-mesa-gbm.log](https://github.com/waydroid/waydroid/files/10526842/lineage18.1-waydroid-log-mesa-gbm.log)
[lineage18.1-waydroid-log-swiftshader-default.log](https://github.com/waydroid/waydroid/files/10526843/lineage18.1-waydroid-log-swiftshader-default.log)

 Waydroid logcat:
 
[lineage-18.1-logcat-mesa-gbm-fail.log](https://github.com/waydroid/waydroid/files/10526848/lineage-18.1-logcat-mesa-gbm-fail.log)
[lineage18.1-logcat-swiftshader-default-success.log](https://github.com/waydroid/waydroid/files/10526849/lineage18.1-logcat-swiftshader-default-success.log)

Thanks in advance.

**Comment by aleasto** [comment]
Uh, yea we're currently not building the AMD GPU driver for Arm because iirc it was failing to compile. And we thought there would be nobody using AMD on Arm.

Will have to revisit that.

**Comment by HanoJing** [comment]
Thanks for the quick reply and the info. Sure an ARM64 desktop is rare nowadays but thanks for the clarity on the issue. I'll stick to lineage17.1 and waydroid tools 1.2.1 for now. I guess it won't be possible for me to  build my own Lineage18.1 image as the driver fails to compile. Did you get any build log of the AMD ARM driver by any chance? If yes, please post it.

**Comment by aleasto** [comment]
Fixed: https://github.com/waydroid/android_external_llvm-project/commit/4c3c3ca0803c441a00629dfcea7469f5cf9b33b1

And re-enabled `radeonsi`/`vulkan.radeon` on arm for the next builds
