### ISSUE TITLE
`waydroid init` should check requirements

### ISSUE THREAD

**Issue by nagayev** [waydroid/waydroid#72]
Hello. I'm running Debian 11 KDE based and I forget I'm using X11 not Wayland.
But when I run `waydroid init` it just started downloading lineage os, without throwing any warnings like:
[WARNING] You are using X11, not Wayland. More info: waydro.id/errors/x11
Also waydroid can checks python3 and lxc.

**Comment by erfanoabdi** [comment]
waydroid init can download images regardless of x11 or wayland
but actually starting session will throw warnings 
lets say for example you can init on x11 and switch to wayland and start waydroid session
