### ISSUE TITLE
LineageOS 18.1 kernel crashing on boot

### ISSUE THREAD

**Issue by vinszent** [waydroid/waydroid#721]
**Describe the bug**
Android kernel for LineageOS 18.1 crashing on boot, LineageOS 17.1 working as normal.

**General information (please complete the following information):**
 - Waydroid a8a93fdc7d40eac2bf60caca3ff81f52f5add92e
 - Waydroid Images lineage-18.1-20230128

**Smartphone (please complete the following information):**
 - Device: Pine64 PinePhone
 - OS: NixOS
 - Mainline
 - Kernel version: 6.0.12

**Additional context**
The problem on the surface appears as `[gbinder] WARNING: Service manager /dev/binder has died` when running `waydroid session start`. However after looking at the `dmesg` for the Android kernel, it's crashing when trying to run `/init`.

**Logs (please upload as file)**
[Full dmesg output](https://github.com/waydroid/waydroid/files/10528710/waydroid.txt)
[waydroid log](https://github.com/waydroid/waydroid/files/10529557/waydroid-log.txt)
[waydroid.prop](https://github.com/waydroid/waydroid/files/10529559/waydroid-prop.txt)
[waydroid logcat](https://github.com/waydroid/waydroid/files/10529581/waydroid-logcat.txt)

**Comment by aleasto** [comment]
You did not include all logs as per the issue template, namely `waydroid logcat`

**Comment by vinszent** [comment]
Ah sorry, I didn't include logcat because it only contains `[10:29:36] WayDroid container is STOPPED`. I assume this is because it's crashing during init and nothing has been written. I have included `waydroid log` and `waydroid.prop` as well now.

**Comment by aleasto** [comment]
Well, run `waydroid logcat` while it's still alive

**Comment by vinszent** [comment]
It dies very quickly, but I think I managed to capture it.

**Comment by aleasto** [comment]
```
01-29 10:45:52.334    49    49 D LibBpfLoader: bpf_create_map name cookie_tag_map, ret: -1
01-29 10:45:52.335    49    49 E LibBpfLoader: Failed to create maps: (ret=-1) in /system/etc/bpf/netd.o
01-29 10:45:52.335    49    49 E bpfloader: Failed to load object: /system/etc/bpf/netd.o, ret: Operation not permitted
01-29 10:45:52.335    49    49 E bpfloader: === CRITICAL FAILURE LOADING BPF PROGRAMS ===
01-29 10:45:52.335    49    49 E bpfloader: If this triggers reliably, you're probably missing kernel options or patches.
01-29 10:45:52.335    49    49 E bpfloader: If this triggers randomly, you might be hitting some memory allocation problems or startup script race.
01-29 10:45:52.335    49    49 E bpfloader: --- DO NOT EXPECT SYSTEM TO BOOT SUCCESSFULLY ---
```
Your kernel is lacking necessary features.
Bring it up to your distribution, if you are not compiling your own.

**Comment by vinszent** [comment]
Ok, thanks for your time. I see it's the same issue as https://github.com/waydroid/waydroid/issues/666, missing `CONFIG_BPF_SYSCALL`. I will compile a custom kernel (using distro provided atm) and try again.

```
[root@PHONE:/var/lib/waydroid]# zcat /proc/config.gz | grep BPF
CONFIG_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
# BPF subsystem
# CONFIG_BPF_SYSCALL is not set
CONFIG_BPF_JIT=y
CONFIG_BPF_JIT_DEFAULT_ON=y
# end of BPF subsystem
CONFIG_NETFILTER_XT_MATCH_BPF=y
# CONFIG_BPFILTER is not set
# CONFIG_TEST_BPF is not set
```
