### ISSUE TITLE
Mouse over windowed mode apps disappears on KDE

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [waydroid/waydroid#726]
**Describe the bug**
On KDE, the mouse pointer visually disappears when hovering over Waydroid application windows. This is only reproducible for seperate windows (both windowed and fullscreen). Via `waydroid show-full-ui`, the issue is not reproducible. On Gnome, the mouse icon is visible as expected.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.4
 - Waydroid Images Version VANILLA: 18.1_20230128

**Desktop (please complete the following information):**
 - OS: Arch Linux x64
 - GPU: AMD Radeon RX Vega 7 (iGPU of AMD Ryzen 5 5600U)
 - Kernel version: 6.1.3-zen
 - Host mesa version: 22.3.3
 - Desktop: 5.26.5

**Logs (please upload as file)**

 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/10536676/waydroid_base.prop.txt)
 - Output of `waydroid log`
[waydroid.log](https://github.com/waydroid/waydroid/files/10536678/waydroid.log)
 - *Full* Output of `waydroid logcat` from the beginning of starting waydroid services
[waydroid.logcat.log](https://github.com/waydroid/waydroid/files/10536680/waydroid.logcat.log)
 - Output of `systemctl status waydroid-container`
[systemctl_status_waydroid-container.service.log](https://github.com/waydroid/waydroid/files/10536683/systemctl_status_waydroid-container.service.log)

**Comment by MegPredator** [comment]
I think you need to enable a prop:
waydroid prop set persist.waydroid.cursor_on_subsurface true

**Comment by Richardsause** [comment]
https://github.com/waydroid/waydroid/issues/66#issue-1004897695 the only workaround is to indeed mess with the props

**Comment by ThePBone** [comment]
kwin 5.27 fixed this issue.

The workaround needs to be disabled, otherwise, there will be two cursors visible:
```
waydroid prop set persist.waydroid.cursor_on_subsurface true
```
