### ISSUE TITLE
Update to Android 11 for official ARM emulation support

### ISSUE THREAD

**Issue by Victor239** [waydroid/waydroid#73]
Android 11 has [official ARM emulation support on x86](https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html) which allows for much improved performance, but this is missing on Android 10. It would be great to see Waydroid update to this newer version.

**Comment by atmouse-** [comment]
related: mer-hybris/libgbinder/pull/75

**Comment by madushan1000** [comment]
Does android 11 has an open source arm translation layer? I thought they were using something proprietary from arm themselves.

**Comment by pavlukivan** [comment]
> Note that the ARM to x86 translation technology enables the execution of intellectual property owned by Arm Limited. It will only be available on Google APIs and Play Store system images, and can only be used for application development and debug purposes on x86 desktop, laptop, customer on-premises servers, and customer-procured cloud-based environments. The technology should not be used in the provision of commercial hosted services.

**Comment by fortressia** [comment]
> Looks like libhoudini was updated for android 11 too for microsoft android apps on windows thing. So we have two options.

Wait, can you please give me the source? I can't find anything much about libhoudini.

**Comment by ThePirate42** [comment]
The last images use Android 11, but I can't install an ARM apk. Do I have to do something to enable ARM support?

**Comment by aleasto** [comment]
That is the GMS emulator images only and not open source

**Comment by firefoxlover** [comment]
If I install the ARM emulation layers, will all apps use it, or will some apps still use x86? Would be a huge performance decrease I guess

**Comment by electrikjesus** [comment]
> If I install the ARM emulation layers, will all apps use it, or will some apps still use x86? Would be a huge performance decrease I guess

It will only use the translation layer for the arm apps. X86 based apps will run at native speed
