### ISSUE TITLE
Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

### ISSUE THREAD

**Issue by Yona-TYT** [waydroid/waydroid#732]
**Describe the bug**
Running "sudo waydroid session start" gives me the following error: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.4

**Desktop (please complete the following information):**
 - OS: Arch Linux x64
 - GPU: Intel Corporation Core Processor Integrated Graphics Controller (rev 18) (prog-if 00 [VGA controller])
 - Kernel version: 6.1.8-zen1-1-zen
 - Host mesa version: Mesa 22.3.3
 - Desktop: Gnome 43.2

**Additional context**

**Logs (please upload as file)**
`(002096) [05:18:51] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(002096) [05:18:51] See also: <https://github.com/waydroid>
(002096) [05:18:51] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

(002456) [05:23:00] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002456) [05:23:00] *** output passed to waydroid stdout, not to this log ***
(003359) [05:30:52] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003359) [05:30:52] *** output passed to waydroid stdout, not to this log ***`

**Comment by Yona-TYT** [comment]
> > Running "sudo waydroid session start" gives me the following error: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
> 
> it's can't find the valid value of DBUS_SESSION_BUS_ADDRESS because you've started the waydroid session using sudo/root access, please don't use sudo here
> 
> also make you're running wayland session or at lease wayland compositor because waydroid is wayland apps so it's important

It still doesn't work, the log says:

```
(002456) [05:23:00] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002456) [05:23:00] *** output passed to waydroid stdout, not to this log ***
(003359) [05:30:52] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003359) [05:30:52] *** output passed to waydroid stdout, not to this log ***
(003407) [05:33:41] Run waydroid -h for usage information.
(004188) [05:44:52] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(004188) [05:44:52] See also: <https://github.com/waydroid>
(004188) [05:44:52] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

(002029) [07:42:54] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(002029) [07:42:56] % systemctl is-active -q nfcd
(002029) [07:42:56] % chmod 777 -R /dev/dri
(002029) [07:42:56] % chmod 777 -R /dev/fb0
(002029) [07:42:56] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(002029) [07:42:56] % mount -o ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(002029) [07:42:56] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(002029) [07:42:56] % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002029) [07:42:57] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(002029) [07:42:57] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002029) [07:42:57] Save config: /var/lib/waydroid/waydroid.cfg
(002029) [07:42:57] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002029) [07:42:57] New background process: pid=5785, output=background
(002029) [07:42:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002029) [07:42:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002029) [07:42:57] waiting 10 seconds for container to start...
(002029) [07:42:58] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(002029) [07:42:58] waiting 9 seconds for container to start...
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(002029) [07:44:18] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002029) [07:44:18] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(002029) [07:44:19] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(002029) [07:44:19] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002029) [07:44:19] % umount /var/lib/waydroid/rootfs/vendor
(002029) [07:44:19] % umount /var/lib/waydroid/rootfs/vendor
(002029) [07:44:19] % umount /var/lib/waydroid/rootfs
(002029) [07:44:19] % umount /var/lib/waydroid/rootfs
(005952) [07:44:37] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005952) [07:44:37] *** output passed to waydroid stdout, not to this log ***
```

**Comment by lsl-046** [comment]
I got same problem, what can I do to resolve it?

**Comment by LeviLeal** [comment]
same problem here...

**Comment by hexatronn** [comment]
same problem, but ''waydroid session start'' command doesn't work correctly:
[13:00:38] Failed to start Clipboard manager service, check logs
[gbinder] Service manager /dev/binder has appeared

container enabled but session doesn't start
how to fix this?

**Comment by chapainaashish** [comment]
The same problem
OS: Arch Linux x64
Kernel: 6.2.0-36-generic

**Comment by 1049451037** [comment]
same problem!!!! why closed!!!

**Comment by Tea23** [comment]
For wandering Googlers - I ran into this earlier on Arch. I had upgraded my kernel but not rebooted yet. After rebooting it worked fine. Try that!

**Comment by coolst3r** [comment]
ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

**Comment by somson** [comment]
> same problem!!!! why closed!!!

I think you can run without sudo

**Comment by DIDIK3V1** [comment]
> ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

same error message here having it for MONTHS

**Comment by xknex** [comment]
> ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

Could you please go into detail how to exactly accomplish that? I installed from the official repo, not from sources.

**Comment by cstiago** [comment]
This issue is indeed related to calling `waydroid session start` with sudo, which was solved by simply omitting it.

Also had the https://github.com/waydroid/waydroid/issues/1945 issue on Arch. I had upgraded the kernel a moment before and a simple reboot did the job. Not quite sure about how correlated they were, though.
