### ISSUE TITLE
Failed to load binder driver

### ISSUE THREAD

**Issue by BenPI88** [waydroid/waydroid#739]
I was trying to follow the install instructions but then I get to the application, start it, click download, but I get the error below:

`Waiting for waydroid container service...
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.19.0-1012-raspi
Binder node "binder" for waydroid not found`

Any suggestions on how to fix?

**Comment by BenPI88** [comment]
I've already tried switching to GAPPS instead of vanilla, still doesn't work.

**Comment by HanoJing** [comment]
Make sure, that you have enabled the following options in your kernel: 

```
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
```

If you have them all enabled already, but it is still failing,
please put the output of 
the commands `waydroid log` and `waydroid logcat` in a file and post it here.
Also upload the content of `waydroid_base.prop` located at `/var/lib/waydroid` as as file.

For further information, please refer to https://docs.waydro.id.
