### ISSUE TITLE
AMDGPU crashes with new LineageOS 18.1 images

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#742]
**Describe the bug**
When using the waydroid UI, it can randomly happen that the whole Xorg crashes, the screen goes black and graphical glitches appear all over the screen. This did not happen with LineageOS 17.1 images.

**General information (please complete the following information):**
Waydroid tools Version: 1.3.4
Waydroid Images Version: `lineage-18.1-20230128-VANILLA-waydroid_arm64-system`
                                          `lineage-18.1-20230204-MAINLINE-waydroid_arm64-vendor`

**Desktop (please complete the following information):**
OS: Gentoo Linux ARM64
Motherboard: SolidRun HoneyComb LX2K
CPU: NXP LayerScape LX2160A Cortex-A72
GPU: AMD Radeon RX580 XFX
Kernel version: 5.19.7 (SolidRun Vendor Kernel with custom config)
Host mesa version: 22.2.5
Desktop: Xorg, dwm (Suckless' dynamic window manager)

**Additional context**
The amdgpu driver crashed from what it looks like.

**Logs (please upload as file)**
Prop file: [waydroid-prop.log](https://github.com/waydroid/waydroid/files/10659874/waydroid-prop.log)
Output of `waydroid log`: [waydroid-log.log](https://github.com/waydroid/waydroid/files/10659878/waydroid-log.log)
*Full* (not partially) Output of `waydroid logcat`:[waydroid-logcat.log](https://github.com/waydroid/waydroid/files/10659879/waydroid-logcat.log)

dmesg: [dmesg.log](https://github.com/waydroid/waydroid/files/10659880/dmesg.log)

**Comment by HanoJing** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=205089 
Apparently it might be because I'm using a compositor (picom in my case).

```
 David Nichols 2021-11-27 14:12:48 UTC

Also seeing it on Ubuntu 21.10 on aarch64:

Kernel: 5.15.0
Mesa: mesa_22.0~git2111150600

Hardware: 
GPU: AMD RX 580 (8GB)
CPU: 16 Core Arm Cortex A72
SoC: NXP LX2160A (SolidRun HoneyComb system)


Running 2 games: flightgear and endless-sky
```
This user even has my hardware, but it's also happening on x86_64 hardware according to the issue.

**Comment by aleasto** [comment]
Is your kernel built with `CONFIG_SW_SYNC` ?

**Comment by aleasto** [comment]
Meh not sure it matters actually. This is the relevant part of dmesg:
```
[   99.457077] amdgpu 0004:01:00.0: amdgpu: GPU fault detected: 146 0x0000480c for process diba.bankingapp pid 6723 thread de.ingdiba:cs0 pid 6842
[   99.457092] amdgpu 0004:01:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000
[   99.457095] amdgpu 0004:01:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x0204800C
[   99.457099] amdgpu 0004:01:00.0: amdgpu: VM fault (0x0c, vmid 1, pasid 32783) at page 0, read from 'TC4' (0x54433400) (72)
```

**Comment by HanoJing** [comment]
> Is your kernel built with `CONFIG_SW_SYNC` ?

Nope, that is not built into my kernel.

Moreover, it can happen regardless of the app I am running inside of waydroid. Wether I start using waydroid quickly right after boot of my PC or use any other app.

**Comment by HanoJing** [comment]
The new `lineage-18.1-20230211-MAINLINE-waydroid_arm64-vendor` image seems to have fixed AMDGPU crashes now. I did some stresstests with a triple-A title.
Did the fix have to come at sacrifice of the function of the square icon in the down right corner?

**Comment by aleasto** [comment]
I only merged mesa stable fixes, so probably something was broken there. In any case, happy to see it fixed.

> Did the fix have to come at the sacrifice of the function of the square icon in the down right corner?
(Pressing the squared button used to show apps that are running in the background)

If you launch an android app with `waydroid app launch com.foo.bar` or from the desktop files it opens a window specifically for that application. When that application stops being focused the window gets closed. That's probably what you are referring to? :shrug:
