### ISSUE TITLE
waydroid first launch on kde neon error

### ISSUE THREAD

**Issue by ansaus** [waydroid/waydroid#744]
**Describe the bug**
after installing I try the comment waydroid first-launch
and then see this
Starting waydroid session
Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1674883062
vendor_datetime = 1675509716
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder

[properties]

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

KDE neon plasma 5.26.5
64 bit

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` 
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.3.4
ro.vndk.lite=true

**LOG
(1699775) [20:29:21] Starting waydroid session
(1699775) [20:29:21] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(1699775) [20:29:21] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

**Comment by aleasto** [comment]
You need a Wayland compositor.

**Comment by ansaus** [comment]
> You need a Wayland compositor.

where can I get it for kde ? cannot find it. please give me a link if you know
