### ISSUE TITLE
Chrome browser plays web video black screen problem！

### ISSUE THREAD

**Issue by kahunama** [waydroid/waydroid#748]
My graphics card is amd RX550 2G arch linux plus kde plasma environment, waydroid chrome browser plays video black screen, tried both zen and kdm drivers, same. Some media playback software can be accelerated by hardware and can be hard-coded. When opening some games with video animation, the screen is as black as the chrome browser.

**Comment by Commandcracker** [comment]
@kahunama Did you get it fixed ? When, yes, how, or did you close it because of inactivity?
