### ISSUE TITLE
Resizing a window in the multi window mode "breaks" it

### ISSUE THREAD

**Issue by skoruppa** [waydroid/waydroid#749]
**Describe the bug**
If you try to change window size by pulling an edge or corner, it will break. It looks like it zooms in for an unknown reason

**Screenshots**
Before resizing
![obraz](https://user-images.githubusercontent.com/899429/217377637-69bf0a82-c489-4796-8e14-9d6bfe650e57.png)
After resizing
![obraz](https://user-images.githubusercontent.com/899429/217377764-473758aa-2bc0-4be2-8eac-caa72f1fb4e8.png)

**Video**
[resize.webm](https://user-images.githubusercontent.com/899429/217378214-c2142fa8-a103-4bb4-85b6-779f44fcee59.webm)

**General information (please complete the following information):**
 - Waydroid tools Version - 1.3.4
 - GAPPS 
 system_datetime = 1675474369
vendor_datetime = 1675509716

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 x64]
 - GPU: Intel i7-10750H
 - Kernel version: Generic 6.0.9
 - Host mesa version: 22.2.5
 - Desktop: Gnome 42.5

**Additional context**

**Logs (please upload as file)**
 -  [waydroid.log](https://github.com/waydroid/waydroid/files/10679844/waydroid.log)

**Comment by aleasto** [comment]
This is a bug in GNOME (mutter), that was fixed in 42.7 and 43.2

I don't know why Ubuntu hasn't updated yet, but you should bring it up with your them.
