### ISSUE TITLE
Why sudo apt install waydroid -y doesn't work

### ISSUE THREAD

**Issue by gitfans5** [waydroid/waydroid#751]
Why does sudo apt install waydroid -y not work? or how to isntall python3-gbinder? Thanks.

**Comment by aleasto** [comment]
How am I supposed to know what distribution you are using

**Comment by HanoJing** [comment]
> Why does sudo apt install waydroid -y not work? or how to isntall python3-gbinder? Thanks.

Please refer to the installation instructions at https://github.com/waydroid/docs/blob/master/usage/install-on-desktops.md
and look under "Ubuntu/Debian and derivatives" if you haven't done so already.

**Comment by gitfans5** [comment]
How fix this error  "E: Package 'python3-gbinder' has no installation candidate" when running "sudo apt install waydroid -y"? Thanks.

**Comment by gitfans5** [comment]
> 

Ubuntu

**Comment by aleasto** [comment]
Ubuntu what

**Comment by HanoJing** [comment]
> How fix this error "E: Package 'python3-gbinder' has no installation candidate" when running "sudo apt install waydroid -y"? Thanks.

Well, you have to add the repo where python3-gbinder is in, if you haven't done so already. 
The script: https://repo.waydro.id/ adds the repository that contains python3-gbinder as per 
https://github.com/waydroid/docs/blob/master/usage/install-on-desktops.md.

**Comment by gitfans5** [comment]
> Ubuntu what

20.04

**Comment by gitfans5** [comment]
> > How fix this error "E: Package 'python3-gbinder' has no installation candidate" when running "sudo apt install waydroid -y"? Thanks.
> 
> Well, you have to add the repo where python3-gbinder is in, if you haven't done so already. The script: https://repo.waydro.id/ adds the repository that contains python3-gbinder as per https://github.com/waydroid/docs/blob/master/usage/install-on-desktops.md.
> 
> Also, your issue description sadly badly lacks in quality. Please provide more information like the exact distribution you are using.
> 
> Moreover, the issue you have is not a bug of waydroid, if you need help with the installation of waydroid, you may want to reach out on the matrix or telegram groups.

Thank you for your reply. 

The Linux distribution is Ubuntu 20.04. 

There doesn't appear to be any problem when running "sudo apt install curl ca-certificates -y" and "curl https://repo.waydro.id | sudo bash", but why does the error "waydroid : Depends: python3-gbinder but it is not installable
E: Unable to correct problems, you have held broken packages." always come up when running "sudo apt install waydroid -y"? 

Thanks  a lot.

**Comment by HanoJing** [comment]
Ah,  then you might want to execute:
`sudo apt --fix-broken install`
