### ISSUE TITLE
Device isn't play protect certified

### ISSUE THREAD

**Issue by ferryafbi** [waydroid/waydroid#753]
**Describe the bug**
I have error with messsage
"ERROR: Cannot access gservices.db, make sure gapps is installed and waydroid was started at least once after installation and make sure waydroid is running !"

**Screenshots**
![image](https://user-images.githubusercontent.com/53357609/217445350-c25088a5-a813-4c73-97c3-301c95efabb7.png)

and error message in waydroid
![image](https://user-images.githubusercontent.com/53357609/217445561-94a0ecde-f7a2-4a99-9ef9-b41e7a7f92e5.png)

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

**Desktop **
 - OS: Ubuntu 22.04.1 LTS
 - GPU: AMD Radeon™ Ryzen 5 4500U
 - Lenovo IdeaPad 3 14ARE05
 - Desktop: Gnome 42.5

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`.
 
![image](https://user-images.githubusercontent.com/53357609/217445950-691e1c86-5a84-4f4c-b814-4e12582e32d7.png)

I thought, that's all I can report, I was hoping for some help

**Comment by oklopfer** [comment]
How to Possibly Unblock Google Apps on Waydroid
1) Run below command on waydroid shell: 
ANDROID_RUNTIME_ROOT=/apex/com.android.runtime ANDROID_DATA=/data ANDROID_TZDATA_ROOT=/apex/com.android.tzdata ANDROID_I18N_ROOT=/apex/com.android.i18n sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"
2) Grab device id and register on this website: https://www.google.com/android/uncertified/
3) Restart waydroid

**Comment by Abdelwahed-Aridj** [comment]
same issue when i ran your command i got :

**Comment by oklopfer** [comment]
1) did you actually run it in Waydroid shell, not your linux shell?
2) was waydroid running when you ran it?

**Comment by Abdelwahed-Aridj** [comment]
Yep that was the issue i wasn't running waydroid shell and i had to enable rooted debugging on developer settings, thanks for the quick reply though

**Comment by Vap0r1ze** [comment]
i had to put backslashes on the quotes inside the sql query like this:
```
ANDROID_RUNTIME_ROOT=/apex/com.android.runtime ANDROID_DATA=/data ANDROID_TZDATA_ROOT=/apex/com.android.tzdata ANDROID_I18N_ROOT=/apex/com.android.i18n sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"
```

**Comment by Dhela19** [comment]
i got an error:
Error: no such column: android_id

**Comment by ruscher** [comment]
pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true sqlite3 /var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db "select * from main where name='android_id';" | cut -f2 -d"|"

**Comment by yhchang685** [comment]
try this : 
echo 'ANDROID_RUNTIME_ROOT=/apex/com.android.runtime sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"' | sudo waydroid shell


android_id|4197135655598826517

**Comment by bigbruno** [comment]
Old way to read android_id direct in terminal of base system:
sudo sqlite3 /var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db "select * from main where name='android_id';" | cut -f2 -d"|"

New way:
sudo grep android_id ~/.local/share/waydroid/data/data/com.google.android.gms/shared_prefs/Checkin.xml | cut -f2 -d">" | cut -f1 -d"<"

Maybe in your system need change ~ to your correct /home/user

**Comment by occhristian** [comment]
Is everyone ignoring the fact that when you `ls` into **/data/data** folder from the waydroid shell (`sudo waydroid shell`), the **com.google.android** folder doesn't exist?

By the way, I haven't installed GAPPS.
I will try that and update my comment here.

**Comment by nocode99** [comment]
I was able to get the `android_id` and then add it to the certified list but my device still says it's not certified after restarting waydroid. Any ideas?

**Comment by SuperNinja313** [comment]
> 2. Grab device id
Where do I find the device id?

**Comment by SamtheGOC** [comment]
> I was able to get the `android_id` and then add it to the certified list but my device still says it's not certified after restarting waydroid. Any ideas?
> 
> Edit: looks like I needed to wait a little longer

Could you please share how long you had to wait for the device to be approved?

**Comment by SamtheGOC** [comment]
> > 2. Grab device id
> 
> Where do I find the device id?

Follow instructions from [here](https://docs.waydro.id/faq/google-play-certification)

**Comment by Poikilos** [comment]
> > I was able to get the `android_id` and then add it to the certified list but my device still says it's not certified after restarting waydroid. Any ideas?
> > Edit: looks like I needed to wait a little longer
> 
> Could you please share how long you had to wait for the device to be approved?

Mine took about 4 minutes after it said "registered". Even though I restarted the waydroid-container service immediately after "registered", I still had to wait about that long.

**Comment by AlyShmahell** [comment]
> I was able to get the `android_id` and then add it to the certified list but my device still says it's not certified after restarting waydroid. Any ideas?
> 
> Edit: looks like I needed to wait a little longer

just waiting a little longer solved it for me too

**Comment by rramos8** [comment]
my case registered, but still unable to sign in, because it is not deleting google play services data ):

**Comment by officialnochill** [comment]
I seem to get this error when attempting to certify.

❯ sudo waydroid shell
[sudo] password for nochill: 
ite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"            <
Error: unable to open database "/data/data/com.google.android.gsf/databases/gservices.db": unable to open database file
1|:/ #                

![Image](https://github.com/user-attachments/assets/3eb935cf-9204-46d4-8a23-c5236d87c7ca)

**Comment by Vajean1** [comment]
Hi, same here. 

![Image](https://github.com/user-attachments/assets/51265957-5ccb-48c1-85b1-783479b1aadf)

**Comment by sk-2073** [comment]
I installed the GAPPS and got the same error as everybody else.

I used [occhristian](https://github.com/occhristian) metode at got it to work :)

> Obviously, when I first installed Waydroid, I installed the other version, not the GAPPS.
> Now, I used sudo waydroid init -s GAPPS -f and it downloaded and extracted the GAPPS image (apparently).
> Now everything works, and I was also able to register my device.
