### ISSUE TITLE
E: Some index files failed to download

### ISSUE THREAD

**Issue by gitfans5** [waydroid/waydroid#754]
How exactly to fix the error below:

"E: Failed to fetch http://iad-ad-3.clouds.ports.ubuntu.com/ubuntu-ports/dists/focal/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://iad-ad-3.clouds.ports.ubuntu.com/ubuntu-ports/dists/focal-updates/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Failed to fetch http://iad-ad-3.clouds.ports.ubuntu.com/ubuntu-ports/dists/focal-backports/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.39 80]
E: Some index files failed to download. They have been ignored, or old ones used instead."

when running "curl https://repo.waydro.id | sudo bash" on Ubuntu 20.04? Thanks a lot!

**Comment by aleasto** [comment]
Not related to waydroid
