### ISSUE TITLE
trebuchet crashed at start

### ISSUE THREAD

**Issue by NobodzzZ** [waydroid/waydroid#755]
After the last update of waydroid,
the linage-os trebuchet crash at every start,
which causes an infinitive loop of restart of lineage-os.

Due no changes on the android image,
it seems there is something with waydroid,
which causes this.

UPDATE
verified
version 1.3.4 works
version 1.4.0 does not

sudo apt-get install waydroid=1.3.4
solved it, with no other changes

**Comment by aleasto** [comment]
We update the deb package with every new git commit, which means that `waydroid=1.3.4` is actually exactly equal to `waydroid=1.4.0` minus the version bump, so this doesn't make sense.

Also, you did not follow the issue template so I don't have anything to look at
