### ISSUE TITLE
`lineage-18.1-20230211-VANILLA-waydroid_arm64-system` has an issue with AMDGPU.

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#756]
**Describe the bug**
The new `lineage-18.1-20230211-VANILLA-waydroid_arm64-system` image crashes waydroid, the older `lineage-18.1-20230128-VANILLA-waydroid_arm64-system` image does not.

**General information (please complete the following information):**
Waydroid tools Version: 1.3.4
Waydroid Images Version: `lineage-18.1-20230211-VANILLA-waydroid_arm64-system`
                                          `lineage-18.1-20230211-MAINLINE-waydroid_arm64-vendor`

**Desktop (please complete the following information):**
OS: Gentoo Linux ARM64
motherboard: SolidRun HoneyComb LX2K
CPU: NXP LayerScape LX2160A Cortex-A72 ARM
GPU: AMD Radeon RX580 XFX
Kernel version: 5.19.7
Host mesa version: 22.2.5
Desktop: Xorg, dwm (Suckless' dynamic window manager)

**Additional context**
With the new `lineage-18.1-20230211-VANILLA-waydroid_arm64-system` image, waydroid is unable to start.
This is a hardware issue again, the system image is working fine on my RockPro64.
When I set `swiftshader` and `gbm`in `waydroid_base.prop`, waydroid starts!
I have also verified that it's not a kernel issue as this also happens when using the Void Linux distro kernel config.
Something with the amdgpu driver again. Just like in #719 but for the system image this time.

**Logs (please upload as file)**
Prop file: [waydroid-prop.log](https://github.com/waydroid/waydroid/files/10712817/waydroid-prop.log)
Log file:[waydroid-log.log](https://github.com/waydroid/waydroid/files/10712819/waydroid-log.log)
*Full* (not partial) output of `waydroid logcat`:[waydroid-logcat.log](https://github.com/waydroid/waydroid/files/10712820/waydroid-logcat.log)
Output of `dmesg`: [dmesg.log](https://github.com/waydroid/waydroid/files/10712821/dmesg.log)

Do you wish to see logs with swiftshader and gbm aswell?
Please let me know about the quality of this bug report.

**Comment by aleasto** [comment]
The build servers are producing some broken builds. We'll have to rebuild.

**Comment by HanoJing** [comment]
Fixed with the newest `lineage-18.1-20230211-VANILLA-waydroid_arm64-system`. 
The issue I had with the squared button down at the right is also fixed.
