### ISSUE TITLE
No sound support

### ISSUE THREAD

**Issue by megastallman** [waydroid/waydroid#76]
Hi guys, Waydroid already looks insainly good and comfortable to use.
But unfortunately - there is no sound. If I try to enable sound in youtube - the browser crashes.

Thanks in advance, guys! You are doing a really good job!

**Comment by erfanoabdi** [comment]
sounds is enabled and already works, maybe you are missing codecs
Please let me know what device is having this issue?

**Comment by c4pp4** [comment]
@erfanoabdi 
Hi, I can confirm this behavior on Xiaomi Mi A2 with UT OTA-19 or latest devel. There is no sound from apps. If I try to turn up/down media volume or set notification sound both through settings it freezes for a while and "close app" notice appears.

**Comment by megastallman** [comment]
As for me - I'm using Waydroid on an x86_64 laptop, running Kubuntu 21.04 on Wayland session. Sound is disabled in browser, Pulseaudio control sees no clients, when I try to enable sound - the browser crashes.

**Comment by c4pp4** [comment]
The solution in my case was vendor.img update.

**Comment by megastallman** [comment]
Sound works fine since Kubuntu 22.04

**Comment by SerJaimeLannister** [comment]
Sound isn't working on archlinux hyprland

**Comment by MurdochLovesJapan** [comment]
I have sound working on my main user account, but it doesn't work on one of my other user accounts. I'm using Arch Linux with an AMD GPU and an Intel CPU.

**Comment by zabeiua** [comment]
On kde neon waydrod stream was muted in "System settings - Sound" after a fresh waydroid install. Just had to unmute it.
