### ISSUE TITLE
rk3588SOC Rock-5b Mali-G610 GPU no work

### ISSUE THREAD

**Issue by xinlonzh** [waydroid/waydroid#760]
The rock-5b using rk3588 SOC can start normally without GPU parameters, but after deleting the no-GPU parameters, it cannot enter the Lineage desktop. If this problem can be solved, Rock-5b will be a perfect desktop host solution.

/var/lib/waydroid/waydroid.cfg
[waydroid]
arch = arm64
vendor_type = MAINLINE
system_datetime = 1676124581
vendor_datetime = 1676132070
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_arm64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
ro.hardware.gralloc = default
ro.hardware.egl = swiftshader

 - Waydroid tools Version:1.4.0
 - Waydroid Images Version:GAPPS 20230211

 - OS: Armbian 22.11.4 Jammy arm64
 - GPU: Mali-G610 (Panfrost)
 - Kernel version: 5.10.110-rockchip-rk3588
 - Host mesa version: mesa 23.0.0
 - Desktop: Gnome 42.5

**Smartphone (please complete the following information):**
 - Device: Radxa Rock-5b
 - OS: Armbian 22.11 Jammy Gnome
 - Kernel version: 5.10.110
[waydroid.log](https://github.com/waydroid/waydroid/files/10728445/waydroid.log)

**Comment by aleasto** [comment]
Your bug report is incomplete, specifically it's missing the output of `waydroid logcat` (from a waydroid session started without the software rendering options) so I have nothing to debug

**Comment by aleasto** [comment]
Mali-G610 is simply not supported in mesa. You are likely using software rendering for the host desktop as well.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8054
https://docs.mesa3d.org/drivers/panfrost.html#panfrost

**Comment by xinlonzh** [comment]
My glxinfo -B cat:
xinlon@rock-5b ~> glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Panfrost (0xffffffff)
    Device: Mali-G610 (Panfrost) (0xffffffff)
    Version: 23.0.0
    Accelerated: yes
    Video memory: 15718MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-G610 (Panfrost)
OpenGL version string: 3.0 Mesa 23.0.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.0.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by xinlonzh** [comment]
I tried to get the wedroid-logcat, in the attachment, I don't know if it helps,thanks!
[waydroid-logcat.zip](https://github.com/waydroid/waydroid/files/10739570/waydroid-logcat.zip)

**Comment by aleasto** [comment]
If mesa really grew support for your GPU in 23.0.0-devel, so will waydroid once 23.0.0 is out

**Comment by xinlonzh** [comment]
@aleasto thank you for your reply!
