### ISSUE TITLE
Failed to get service waydroidplatform,  trying again...What is the reason

### ISSUE THREAD

**Issue by tianyi725** [waydroid/waydroid#761]
I followed this step to install waydroid on the virtual machine

**1.sudo apt install curl ca-certificates -y
2.curl https://repo.waydro.id | sudo bash
3.sudo apt install waydroid -y**

and then 
**4.waydroid status**
Session:             RUNNING
Container:         RUNNING
Vendor  type:    MAINLINE
Session  user:    kk(1000)
Wayland display:      wayland-0

But I keep getting this error when I install FDRoid.apk
**5.waydroid app install F-Droid.apk**

[13:26:34] Failed to get service waydroidplatform,  trying again...

What is the reason

Or does waydroid not support virtual machines?

thank you

**Comment by HanoJing** [comment]
You did not post as per the following template:

```
**Describe the bug**
A clear and concise description of what the bug is.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**
Add any other context about the problem here.

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`
```
All in all, what waydroid tools version do you use? What version do your waydroid images have? What hardware do you have, what OS do you use? And what do the logs show?

Also please refer to: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm.

**Comment by aleasto** [comment]
The reason is that android is trying to boot but failing.
Indeed unless your virtual machine supports OpenGL via Virtio, you need to follow the steps to enable software rendering
