### ISSUE TITLE
Waydroid didn't start

### ISSUE THREAD

**Issue by ardian923** [waydroid/waydroid#763]
I try to start waydroid by typing : 'waydroid show-full-ui'
Waited long but it never started. The log was : 

`(000697) [20:23:13] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000697) [20:23:13] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(000697) [20:23:13] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000697) [20:23:13] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(000697) [20:23:13] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(000697) [20:23:13] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000697) [20:23:13] % umount /var/lib/waydroid/rootfs/vendor
(000697) [20:23:13] % umount /var/lib/waydroid/rootfs/vendor
(000697) [20:23:13] % umount /var/lib/waydroid/rootfs
(000697) [20:23:13] % umount /var/lib/waydroid/rootfs
(011148) [20:23:19] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(011148) [20:23:19] *** output passed to waydroid stdout, not to this log ***
`

**Comment by ardian923** [comment]
i run 'waydroid upgrade', and the problem solved...

**Comment by HanoJing** [comment]
Then please close issue if you say that it is solved. Thanks in advance.
