### ISSUE TITLE
Container stops shortly after starting

### ISSUE THREAD

**Issue by guyuming76** [waydroid/waydroid#766]
I am new to waydroid and lxc.

While 
```
gym@gymDeskGentoo ~ $ waydroid status
Session:	RUNNING
Container:	RUNNING
Vendor type:	MAINLINE
Session user:	gym(1001)
Wayland display:	wayland-0
```

but lxc-info says its stopped:
```
gym@gymDeskGentoo ~ $ lxc-info -P /var/lib/waydroid/lxc -n waydroid
Name:           waydroid
State:          STOPPED
gym@gymDeskGentoo ~ $ 
```

and 
```
gym@gymDeskGentoo ~ $ sudo systemctl status waydroid-container.service 
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disa>
     Active: active (running) since Mon 2023-02-20 06:56:31 CST; 3h 51min ago
   Main PID: 392 (waydroid)
      Tasks: 3 (limit: 18576)
     Memory: 46.7M
     CGroup: /system.slice/waydroid-container.service
             ├─ 392 /usr/bin/python3.9 /usr/lib/python-exec/python3.9/waydroid container start
             └─7383 dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces >

Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 1.0.0.1#53
Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 8.8.4.4#53
Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 2606:4700:4700::1111#53
Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 2001:4860:4860::8888#53
Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 2606:4700:4700::1001#53
Feb 20 10:07:50 gymDeskGentoo dnsmasq[7383]: using nameserver 2001:4860:4860::8844#53
Feb 20 10:07:54 gymDeskGentoo dnsmasq[7383]: reading /etc/resolv.conf
Feb 20 10:07:54 gymDeskGentoo dnsmasq[7383]: using nameserver 192.168.100.1#53
Feb 20 10:07:54 gymDeskGentoo dnsmasq[7383]: reading /etc/resolv.conf
```

actually interacting with the android system (e.g. waydroid show-full-ui) only leads to Failed to get service waydroidplatform, trying again....

In waydroid log, i can see something like:
```
(000392) [07:03:34] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000392) [07:03:34] New background process: pid=7400, output=background
(000392) [07:03:34] waiting 10 seconds for container to start...
(000392) [07:03:35] Save session config: /var/lib/waydroid/session.cfg
(007769) [07:03:48] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(007769) [07:03:48] *** output passed to waydroid stdout, not to this log ***
(007348) [07:04:53] Failed to add service waydroidusermonitor: -2147483647
(007348) [07:04:53] Failed to add service waydroidclipboard: -2147483647
(000392) [07:04:53] Failed to add service waydroidhardware: -2147483647
lxc-start: waydroid: ../lxc-5.0.1/src/lxc/conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: ../lxc-5.0.1/src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"

```
gym@gymDeskGentoo ~ $ 
```

and 
```
gym@gymDeskGentoo ~ $ waydroid --version
1.2.1
gym@gymDeskGentoo ~ $ lxc-checkconfig
LXC version 5.0.1
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/memory
/sys/fs/cgroup/blkio
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/pids
/sys/fs/cgroup/perf_event

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

**Comment by guyuming76** [comment]
further test shows that after initial machine boot, both waydroid status and lxc-info show container as running, but after waydroid show-full-ui, lxc-info show container as stopped.

![20230220_13h14m45s_grim](https://user-images.githubusercontent.com/12045548/220015681-033af373-1beb-4847-b4a9-f1132cdc6634.png)
![20230220_13h15m57s_grim](https://user-images.githubusercontent.com/12045548/220015722-34ccc0b8-bbbc-4591-9e88-5031379e7d30.png)

**Comment by cniw** [comment]
> Failed to add service waydroidusermonitor: -2147483647
> Failed to add service waydroidclipboard: -2147483647
> Failed to add service waydroidhardware: -2147483647

gbinder config not compatible with current official waydroid images (android 11)
```bash
ls -1 /etc/gbinder.conf /etc/gbinder.d/
```

you're using old waydroid version and you should set gbinder config manually

info:
- to use android 11 need libgbinder >=1.1.14 version
- waydroid >= 1.3.0 able to automatically handle different android version on demand and doesn't need gbinder config file

solution:
- please update your waydroid and libgbinder packages
- or use old images (android 10) manually

**Comment by guyuming76** [comment]
@cniw , thanks!

i am using gentoo and install waydroid from the guru repository, this is the only version of waydroid i can choose from that repository now.

my libgbinder version is  dev-libs/gbinder-1.1.19

so, i thank i should try an old image first, 
shall i change some config and run waydroid init -f ?
which configure file shall i change to specify and old image? Thanks!

**Comment by cniw** [comment]
> my libgbinder version is dev-libs/gbinder-1.1.19

this libgbinder support for android 11 but you need set the config manually because of old waydroid version

check config these file `ls -1 /etc/gbinder.conf /etc/gbinder.d/`,
- open that files with your text editor
- replace all `aidl2` with `aidl3`
- and at `ApiLevel` line replace `29` with `30`
- save it and restart waydroid

**Comment by cniw** [comment]
> i am using gentoo and install waydroid from the guru repository, from which this is the only version of waydroid i can choose now.

why you still get version 1.2.1?
meanwhile i see it's waydroid-1.3.4-r6 at http://gpo.zugaina.org/app-containers/waydroid

**Comment by guyuming76** [comment]
@cniw   just sync my guru repository and upgraded waydroid to version 1.3.4
but still the same error:

![20230220_17h12m34s_grim](https://user-images.githubusercontent.com/12045548/220063648-f249af18-e312-46b8-889e-bc97045aef0c.png)
![20230220_17h16m39s_grim](https://user-images.githubusercontent.com/12045548/220063720-06c63284-f243-44a4-b9cd-e184dd6bc389.png)

**Comment by guyuming76** [comment]
@cniw , i modified anbox.conf after upgrading to 1.3.4, still no luck.

```
gym@gymDeskGentoo ~ $ cat /etc/gbinder.d/anbox.conf
[Protocol]
/dev/binder = aidl3
/dev/vndbinder = aidl3
/dev/hwbinder = hidl

[ServiceManager]
/dev/binder = aidl3
/dev/vndbinder = aidl3
/dev/hwbinder = hidl

[General]
ApiLevel = 30
```

I notice that there are always errors such as follows in dmesg, what does it mean?

`[   50.818704] init: /vendor/etc/init/android.hardware.audio.service.rc: 1: ignored duplicate definition of service 'vendor.audio-hal'
`
```

[   50.821082] libprocessgroup: restored ownership for cgroup2 cgroup
[   50.821149] libprocessgroup: Failed to mount cpu cgroup: Operation not permitted
[   50.821162] libprocessgroup: Failed to setup cpu cgroup
[   50.821209] libprocessgroup: Failed to mount cpuacct cgroup: Operation not permitted
[   50.821221] libprocessgroup: Failed to setup cpuacct cgroup
[   50.821276] new mount options do not match the existing superblock, will be ignored
[   50.821680] cgroup1: Unknown subsys name 'schedtune'
[   50.821692] libprocessgroup: Failed to mount schedtune cgroup: Invalid argument
[   50.821704] libprocessgroup: Failed to setup schedtune cgroup
[   50.821853] init: Failed to open device-mapper: No such file or directory
```

```

[   50.824672] libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
[   50.824690] init: createProcessGroup(0, 4) failed for service 'exec 1 (/system/bin/linkerconfig --target /linkerconfig/bootstrap)': Read-only file system
```

**Comment by cniw** [comment]
> [gbinder] WARNING: Service manager /dev/binder has died

what is kernel variant do you use and please check this kernel config?
```bash
uname -r
zgrep PSI /proc/config.gz
```

**Comment by aleasto** [comment]
Your kernel is most likely missing required features.
You're going to have to post all the logs as instructed in the issue template.

**Comment by guyuming76** [comment]
@cniw @aleasto  , here is my kernel .config: https://pastebin.com/Nmn5anZB

**Comment by guyuming76** [comment]
@cniw @aleasto,
i wonder if this can be related to apparmor USE flag in gentoo, although i almost know nothing about armor.

At first, with waydroid version 1.2.1, before i created this thread, container cannot start, and with clue in waydroid log, i added apparmor USE flag for lxc in gentoo, and then container can start.

but when i upgraded to waydroid version 1.3.4, i noticed that apparmor USE flag was added in waydroid package, but is deactivated by default, and i had not activated it during upgrade.

And i just removed the apparmor USE flag from lxc and container failed to start again:
`lxc-stop: waydroid: ../lxc-5.0.1/src/lxc/confile.c: set_config_apparmor_profile: 1651 Invalid argument - Built without AppArmor support`


what follows is my current apparmor usage, and i notice that systemd is also built without this flag. I wonder whether i need to add this flag globally to have all three packages reinstalled with apparmor flag? and whether i need to run waydroid init -f after that (it runs so slowly to download a new image, can i specify not to download new image if any re-configuration is necessary)?


```
gym@gymDeskGentoo ~ $ euse -I apparmor
global use flags (searching: apparmor)
************************************************************
[-      ] /var/db/repos/gentoo/profiles/use.desc:apparmor - Enable support for the AppArmor application security system

Installed packages matching this USE flag:
app-containers/lxc-5.0.1-r2
app-containers/waydroid-1.3.4-r6
sys-apps/systemd-251.8

local use flags (searching: apparmor)
************************************************************
no matching entries found
```

**Comment by guyuming76** [comment]
in waydroid log, i notice what follows, as in one of my screenshots above :
```
(000396) [20:02:57] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(000396) [20:02:57] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000396) [20:02:57] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000396) [20:02:57] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000396) [20:02:58] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
```
the system.img and vendor.img is mounted ro, is this the reason why there are so many red message in dmesg that says:
```
[   85.497963] libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
[   85.497993] init: createProcessGroup(0, 5) failed for service 'ueventd': Read-only file system
[   85.498564] init: starting service 'apexd-bootstrap'...
[   85.499055] libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
[   85.499082] init: createProcessGroup(0, 6) failed for service 'apexd-bootstrap': Read-only file system
```

So, why those two .img files are mounted readonly?

**Comment by aleasto** [comment]
You have not posted the logcat, I don't know what configs may missing, and there's nothing we can do upstream to fix your kernel anyways.
