### ISSUE TITLE
Device not certified for google play services

### ISSUE THREAD

**Issue by Xandor19** [waydroid/waydroid#769]
**Describe the bug**
When I run Waydroid and open de Google Play Store (GAPPS image), after a while of "Checking Information" I get a message that my device is not certified to run Google Play Services and the only aviable choice is "Got It" which returns to the Play Store login screen.

**General information (please complete the following information):**
 - Waydroid 1.4.0
 - Waydroid GAPPS with vendor_datetime 1676719330

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 x64
 - GPU: NVIDIA Geforce GTX1050M 4GB
 - Kernel version: 5.15
 - Desktop: Gnome 42

**Smartphone (please complete the following information):**
 - Device: WayDroid x86_64 Device (this is shown as Device Name and Device Model in the Android Configuration)
 - OS: LineageOS 18.1

**Additional context**
Just installed Waydroid and launched the app after rebooting and starting the session with Ubuntu on Wayland
Already checked Issue #753 but the 3rd command of the 1st step in the 1st comment outputs: 

`/system/bin/sh: /data/data/com.google.android.gsf/databases/gservices.db: can't execute: Permission denied`

Note that I enabled Rooting Debbuging in the developer settings as indicated

**Comment by PhilDevProg** [comment]
That means that you have to register your device at Google. You can use this script: https://github.com/casualsnek/waydroid_script

**Comment by alevesely** [comment]
I have a similar problem on a Pinephone pro.  I run waydroid_script and can download soma apps, for example telegram.  However, some apps are not showed, and when I force their selection, I get this:
```
    Waydroid Pine64 PinePhone (1.2)
    This item is not compatible with your device
```
Isn't it possible to pretend to be Android?

**Comment by PhilDevProg** [comment]
You can use the Aurora Store (alternative frontend for Play Store) which shows them too for me.

**Comment by alevesely** [comment]
Once I did.  I downloaded  bper-banca.apk on the PC and transferred it to the phone.  But it doesn't install.

How can I trace what happens?

**Comment by PhilDevProg** [comment]
What do you mean by 'it doesn't install'? How did you try to install it? Was there an error?

**Comment by alevesely** [comment]
I  run `waydroid app install bper-banca.apk`.  It runs for a short time and exits without giving any notice.  The app is not installed.  In the journal I find these lines, possibly related:

```log
Feb 22 08:59:42 alesmart kernel: binder: 675571 RLIMIT_NICE not set
Feb 22 08:59:44 alesmart kernel: binder: undelivered death notification, 0000000000000001
```

If I run it as root, then I get a line of output:
```sh
[ale@alesmart ~]$ sudo waydroid app install bper-banca.apk 
[09:06:29] WayDroid session is stopped
```
And the log says:
```log
Feb 22 09:06:27 alesmart sudo[676822]: pam_systemd_home(sudo:account): Not a user managed by systemd-homed: No home for user ale known
Feb 22 09:06:27 alesmart sudo[676822]:      ale : TTY=pts/0 ; PWD=/home/ale ; USER=root ; COMMAND=/usr/bin/waydroid app install bper-banca.apk
Feb 22 09:06:27 alesmart sudo[676822]: pam_unix(sudo:session): session opened for user root(uid=0) by ale(uid=1002)
Feb 22 09:06:29 alesmart sudo[676822]: pam_unix(sudo:session): session closed for user root
Feb 22 09:06:46 alesmart kernel: binder: 676886 RLIMIT_NICE not set
Feb 22 09:06:47 alesmart kernel: binder: undelivered death notification, 0000000000000001
```

I'd need something like gdb for Python, methinks.

**Comment by baptx** [comment]
I got the issue and fixed it by following the instructions on https://docs.waydro.id/faq/google-play-certification.

**Comment by alevesely** [comment]
On 26/12/2023 23:01, baptx wrote:
> I got the issue and fixed it by following the instructions on 
> https://docs.waydro.id/faq/google-play-certification 
> <https://docs.waydro.id/faq/google-play-certification>.


That article talks about launching waydroid with GAPPS for the first 
time.  Dunno it I followed that recipe or a similar one.  It worked.  I 
installed Telegram and Whatsapp though Google store, and run them regularly.

One point, at least for me I think, is that some apps come with a list 
of allowed devices which (look look) doesn't include items like 
"Waydroid Pine64 PinePhone (1.2)"

**Comment by baptx** [comment]
@alevesely Maybe this can help you:
https://github.com/waydroid/waydroid/issues/935#issuecomment-1745029486 (https://github.com/waydroid/waydroid/issues/1060#issuecomment-1732325955)

**Comment by NorkQ** [comment]
If anybody needs, solution is here -> [](https://www.ihsankaya.com/en/how-to-install-google-play-services-waydroid/)

**Comment by electrikjesus** [comment]
How is that link any different than what is in Waydroid documentation?
