### ISSUE TITLE
Restore former session after weston(or other compositor) shutdown

### ISSUE THREAD

**Issue by metalbrick** [waydroid/waydroid#774]
**Describe the bug**

I run waydroid show-full-ui in weston compositor in a X11 session, It works flawlessly, BUT there's problem, after I shut the weston window, I can no longer to restore the former waydroid session, It keeps prompting "RuntimeError: Already tracking a session"
Is there any way to restore the former session?
The container and session is definitely preserving, the app is still running and audio is still playing background
I go through all cli options but find nothing

**Logs (please upload as file)**

$ waydroid show-full-ui
[13:49:53] Starting waydroid session
[13:49:53] RuntimeError: Already tracking a session

**Comment by aleasto** [comment]
Wayland clients die when the compositor quits

**Comment by K-L-R-3** [comment]
Did you find a solution? I have the same problem.

**Comment by metalbrick** [comment]
No, I have to restart a new session every time I mistakenly closed the weston window.


Did you find a solution? I have the same problem.

**Comment by llc0930** [comment]
There is another situation, after weston reports the error `libwayland: error in client communication`, the waydroid ui disappears, waydroid clients is still running, but I can no longer make it display the ui...
