### ISSUE TITLE
Waydroid glitching on 1440p screens, fine with 1080p on a dual-monitor setup

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#777]
**Describe the bug**
When starting `waydroid show-full-ui` on a 2560x1440p screen and putting it in fullscreen mode, the part that is more than with 1080p is glitching out and unfunctional.

**Screenshots**
1440p:
![20230223_17h31m14s_grim](https://user-images.githubusercontent.com/123803351/220971268-a353be80-83d0-4715-92c5-b4f8f4a6a00d.jpeg)

1080p:
![20230223_17h30m20s_grim](https://user-images.githubusercontent.com/123803351/220971314-5a6902e5-90ac-4793-abca-9b4a5d843f30.jpeg)

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.4
 - Waydroid Images Version: `lineage-18.1-20230211-VANILLA-waydroid_arm64-system`
                                                    `lineage-18.1-20230218-MAINLINE-waydroid_arm64-vendor`

**Desktop (please complete the following information):**
 - OS: Gentoo Linux ARM64
 - GPU: AMD Radeon RX580 XFX
 - Kernel version: 6.1.3+
 - Host mesa version: mesa 22.2.5 
 - Desktop: Hyprland (https://github.com/hyprwm/hyprland)

**Additional context**
Possible depending factors:
1. The fact that I have dual monitor setup
2. The order of the DisplayPort cables on the Graphicscard
3. GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.pcie_gen_cap=0x4"

It used to be, that this issue not happened always, but now it happens always.

**Logs (please upload as file)**
 - Prop file: [waydroid-prop.log](https://github.com/waydroid/waydroid/files/10816060/waydroid-prop.log)
 - Log file: [waydroid-log.log](https://github.com/waydroid/waydroid/files/10816066/waydroid-log.log)
 - `waydroid logcat`: [waydroid-logcat.log](https://github.com/waydroid/waydroid/files/10816070/waydroid-logcat.log)
 - Output of `dmesg`: [dmesg.log](https://github.com/waydroid/waydroid/files/10816075/dmesg.log)

**Comment by HanoJing** [comment]
1. The issue is fixed when plugging the 1080p monitor out.

**Comment by aleasto** [comment]
> and putting it in fullscreen mode

?

**Comment by HanoJing** [comment]
> > and putting it in fullscreen mode
> 
> ?

By that I mean, that I pull the window by its corners to the corners of the monitor.

**Comment by aleasto** [comment]
Waydroid does not support resizing. Display resolution is irrelevant.

**Comment by HanoJing** [comment]
Oh, is there some way to set a go-to resolutin then?

**Comment by aleasto** [comment]
Are you restarting the waydroid session? It definitely works

**Comment by HanoJing** [comment]
Yup! The issue is fixed, thank you very much!
