### ISSUE TITLE
Improve overall setup experience

### ISSUE THREAD

**Issue by atrauzzi** [waydroid/waydroid#78]
It might be time to spend a little bit on polishing up the setup experience. Ideally a PPA should be all that's necessary to get waydroid up and running.  Additional commands such as starting services, configuring them on system startup and containers can all be handled by that setup process.

**Comment by darkdragon-001** [comment]
PPA exists (see [docs](https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-based-install-instructions)), so this should be fixed by now?
