### ISSUE TITLE
Waydroid 1.4.0: ModuleNotFoundError: No module named 'dbus.mainloop'

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#780]
**Describe the bug**
The latest Waydroid tools version won't work.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.0
 - Waydroid Images Version: This doesn't matter in my case, I think

**Desktop (please complete the following information):**
 - OS: Gentoo Linux ARM64
 - GPU: AMD Radeon RX580 XFX
 - Kernel version: 6.1.3+
 - Host mesa version: 22.2.5
 - Desktop: Hyprland

**Additional context**
Why does Waydroid tools use dbus now?

**Logs (please upload as file)**
 ```
</> waydroid
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
```

in `__init__.py`: 
```
import dbus.mainloop.glib
import dbus
import dbus.exceptions
```

**Comment by HanoJing** [comment]
Installing `dbus-python` fixed the issue!

**Comment by Rayytra** [comment]
Still having the same issue here
I have installed dbus and even built it from source but still no luck yet.

**Comment by AlpikTech** [comment]
i have same issue:

`❯ waydroid
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'

~
❯ 
`

**Comment by abraham-1672** [comment]
~ 
❯ waydroid
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'

~ 

yah I have the same issue did someone get it to work?

**Comment by tockudex** [comment]
Hi,

Had faced the same issue despite having installed `python-dbus` on Arch Linux.
Turns out my `$PATH` was "messed up" by `conda` (virtual env), which I found out by running `python3` in my terminal.

Basically, the installation path of your system-wide `python` should appear in your `$PATH` before any externally managed python.
