### ISSUE TITLE
Need method to disable on-screen keyboard without losing spell checker

### ISSUE THREAD

**Issue by dreamlayers** [waydroid/waydroid#789]
Having the on screen keyboard pop up every time for text entry is annoying. At https://docs.waydro.id/faq/disable-on-screen-keyboard the instructions suggest disabling the on-screen keyboard Android app to get rid of this. However, the spell checker is part of that app, and so this also removes spell checking. Also, in some rare situations the on-screen keyboard is useful or even necessary to use a feature in an app.

Android actually supports a real keyboard, and can keep the on-screen keyboard hidden when a real keyboard is connected. Android x86 uses this, and it works perfectly. The on screen keyboard never pops up by itself, but if I need it I can easily pop it up using the Alt key. So, if Waydroid provided input via what seemed like a real keyboard to Android, the problem would be solved. Even providing a dummy real keyboard, and delivering an input another way, may solve this problem.

Another option would be to install some app which provides spell checking but not on-screen keyboard functionality. Though I'm not sure which app to use.

Doing something special to prevent the on-screen keyboard from popping up or to visually hide it is another possibility, but that would probably be messy.

**Comment by aleasto** [comment]
> So, if Waydroid provided input via what seemed like a real keyboard to Android, the problem would be solved.

This is already the case since Jan 24th, so you can prevent the virtual keyboard from popping up with `Settings > System > Languages & input > Physical keyboard > Use on-screen keyboard`

We'll have to update the docs

**Comment by dreamlayers** [comment]
I guess that requires a recent Android 11 image, because it doesn't work in an old Android 10 image. I'm using 17.1-20220723-GAPPS-waydroid_x86 because in the past I found the LineageOS 18.1 x86 images require SSE4.1 #617, The 17.1 image acts as if no hardware keyboard is connected.

**Comment by dreamlayers** [comment]
This does indeed require a LineageOS 18.1 Android 11 image. I just upgraded after that other issue was solved. The new image acts as if a physical keyboard is connected, and gives me the option to hide the on-screen keyboard.

**Comment by thanveeralisayed** [comment]
the on screen keyboard option is now greyed. Not able to disable it

**Comment by sinon727uwu** [comment]
there is a method !!!!

**Comment by sinon727uwu** [comment]
> Having the on screen keyboard pop up every time for text entry is annoying. At https://docs.waydro.id/faq/disable-on-screen-keyboard the instructions suggest disabling the on-screen keyboard Android app to get rid of this. However, the spell checker is part of that app, and so this also removes spell checking. Also, in some rare situations the on-screen keyboard is useful or even necessary to use a feature in an app.
> 
> Android actually supports a real keyboard, and can keep the on-screen keyboard hidden when a real keyboard is connected. Android x86 uses this, and it works perfectly. The on screen keyboard never pops up by itself, but if I need it I can easily pop it up using the Alt key. So, if Waydroid provided input via what seemed like a real keyboard to Android, the problem would be solved. Even providing a dummy real keyboard, and delivering an input another way, may solve this problem.
> 
> Another option would be to install some app which provides spell checking but not on-screen keyboard functionality. Though I'm not sure which app to use.
> 
> Doing something special to prevent the on-screen keyboard from popping up or to visually hide it is another possibility, but that would probably be messy.

here run this once 

sudo waydroid shell settings put secure show_ime_with_hard_keyboard 0

on screen keyboard will never popup again
