### ISSUE TITLE
Missing environment variable BOOTCLASSPATH 

### ISSUE THREAD

**Issue by ayasa520** [waydroid/waydroid#793]
**Describe the bug**
when I run some commands like `input` on waydroid shell nothing happens. 

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.0

**Desktop (please complete the following information):**
 - OS: Manjaro
 - GPU: UHD 630
 - Kernel version: 6.1.12-1-MANJARO
 - Host mesa version: 22.3.5
 - Desktop: Gnome43

**Logs (please upload as file)**
```
03-06 16:21:05.429   296   308 I chatty  : uid=1000(system) FinalizerDaemon identical 4 lines
03-06 16:21:05.429   296   308 W System  : A resource failed to call release. 
03-06 16:21:09.053  2013  2013 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
03-06 16:21:09.055  2013  2013 I AndroidRuntime: Using default boot image
03-06 16:21:09.055  2013  2013 I AndroidRuntime: Leaving lock profiling enabled
03-06 16:21:09.056  2013  2013 E app_process: Could not open boot oat file for extracting boot class path: File /apex/com.android.art/javalib/boot.art:/system/framework/boot-framework.art!/system/etc/x86_64/boot-image.vdex does not exist.
03-06 16:21:09.056  2013  2013 E AndroidRuntime: JNI_CreateJavaVM failed
03-06 16:21:09.569   542   542 W Choreographer: Frame time is 0.29961 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
```

If I manually set `BOOTCLASSPATH`  to `/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar`, everything works fine.

![image](https://user-images.githubusercontent.com/55699692/223178140-73bdb8af-4a26-4250-b7a4-dc30c462aa0c.png)

**Comment by lordmemed** [comment]
yeah, just tried and it works.
thanks.

**Comment by marciodasilvasantos1973-oss** [comment]
Xit

**Comment by uveshrajput223-star** [comment]
Touch_screen_blocks = 0

Ui_refresh_rate = 98.8

adaptive_touch_sensitivity = speed

Touch_pressure_scale = 0.01

**Comment by uveshrajput223-star** [comment]
Touch_screen_blocks = 0

Ui_refresh_rate = 98.8

adaptive_touch_sensitivity = speed

Touch_pressure_scale = 0.01

**Comment by uveshrajput223-star** [comment]
> **Describe the bug** when I run some commands like `input` on waydroid shell nothing happens.
> 
> **General information (please complete the following information):**
> 
> * Waydroid tools Version 1.4.0
> 
> **Desktop (please complete the following information):**
> 
> * OS: Manjaro
> * GPU: UHD 630
> * Kernel version: 6.1.12-1-MANJARO
> * Host mesa version: 22.3.5
> * Desktop: Gnome43
> 
> **Logs (please upload as file)**
> 
> ```
> 03-06 16:21:05.429   296   308 I chatty  : uid=1000(system) FinalizerDaemon identical 4 lines
> 03-06 16:21:05.429   296   308 W System  : A resource failed to call release. 
> 03-06 16:21:09.053  2013  2013 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 03-06 16:21:09.055  2013  2013 I AndroidRuntime: Using default boot image
> 03-06 16:21:09.055  2013  2013 I AndroidRuntime: Leaving lock profiling enabled
> 03-06 16:21:09.056  2013  2013 E app_process: Could not open boot oat file for extracting boot class path: File /apex/com.android.art/javalib/boot.art:/system/framework/boot-framework.art!/system/etc/x86_64/boot-image.vdex does not exist.
> 03-06 16:21:09.056  2013  2013 E AndroidRuntime: JNI_CreateJavaVM failed
> 03-06 16:21:09.569   542   542 W Choreographer: Frame time is 0.29961 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
> ```
> 
> If I manually set `BOOTCLASSPATH` to `/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar`, everything works fine.
> 
> ![image](https://user-images.githubusercontent.com/55699692/223178140-73bdb8af-4a26-4250-b7a4-dc30c462aa0c.png)

https://github.com/waydroid/waydroid/issues/793#issuecomment-5163270473
