### ISSUE TITLE
Apps crash/freeze on certian activities

### ISSUE THREAD

**Issue by CactiChameleon9** [waydroid/waydroid#8]
Certain apps, such as settings and signal, freeze on anbox-halium when going into certain activities (screens).

- Settings freezes on the system/gestures/system navigation activity
- Signal freezes on any messaging screen

Tested on ubuntu touch GSI and droidian GSI on the oneplus 6

I am unsure on how to get a logcat because I don't know how to adb into anbox-halium

**Comment by erfanoabdi** [comment]
This happens because of broken media hal
and makes system crash on playing any video or audio, will debug it later

**Comment by guibbv2011** [comment]
hello guys,

yeah, it happened to me today,

today I catch a "bug" with anbox in redmi note 7 devices,
I installed the WhatsApp app and then running it the anbox freezes and the UT stay crashed, getting a reboot loop.

https://forums.ubports.com/topic/6486/freeze-in-10s-and-catch-in-loop-reboot-ut?_=1627321720802

Did whats happen with Whatsapp for the serious crash?

Unfortunately, I don't get the log of the bug

**Comment by erfanoabdi** [comment]
Should be fixed now, please reopen if it's still the case
