### ISSUE TITLE
Graphics Corruption

### ISSUE THREAD

**Issue by nesper8** [waydroid/waydroid#803]
**Describe the bug**
Graphics is corrupted

**Screenshots**
![Screenshot_20230314_192005](https://user-images.githubusercontent.com/57890520/225026501-3dd94ba8-f318-4d3c-ad25-c9cb69964725.png)

**General information:**
 - Waydroid tools Version = 1.4.0
 - Waydroid Images Version = lineage-18.1-20230311-GAPPS-waydroid_x86_64-system.zip

**Desktop:**
 - OS: PikaOS 22.10 x64 (Ubuntu 22.10 based)
 - GPU: Intel HD 520 (iGPU) & AMD R5 M330 (dGPU)
 - Kernel version: 6.1.0-7.203.fsync-cosmo-amd64
 - Host mesa version: Mesa 23.0.0
 - Desktop: KDE Plasma 5.27.2

**Logs**
[waydroid.log](https://github.com/waydroid/waydroid/files/10969559/waydroid.log)
[dmesg.log](https://github.com/waydroid/waydroid/files/10969561/dmesg.log)
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/10969588/waydroid.prop.txt)

**Comment by antoniocaiazzo** [comment]
Hi, I'm experiencing the same issue of corrupt graphics but in some games only. I've tried the script to switch to the other GPU but waydroid doesn't boot anymore, it just fails with the `Failed to get service waydroidplatform, trying again...` message. Only by switching back to the first GPU it then boots again.

These are my specs:
- Waydroid 1.4.2, Lineage 18.1 2024-03-23 GAPPS
- OS: Nobara 39 x64
- GPU: AMD Radeon RX 6800S (discreet), Radeon 680M (integrated)
- Kernel: 6.7.6-201.fsync.fc39.x86_64
- Host mesa version: 23.3.6

**Comment by KingKrouch** [comment]
> this is a known issue with dual gpus https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh
> 
> you can run this script, if it doesnt work with the first gpu you select, chose the other gpu

I decided to run the script, but for some reason, when I try to use my AMD APU on my laptop rather than the dGPU, Waydroid just refuses to launch. I checked my logs to see what was going on, and there seems to be some strange service shenanigans and broken Python script stuff going on.

https://gist.github.com/KingKrouch/63da636d3627d4b61073f6277a529d49
