### ISSUE TITLE
I have tried everything to get Candy Crush Soda Saga in wardroid. I have the GAPPS, and it doesn't even show up in playstore. I have used "waydroid app install" to install the apk file, while waydroid is running. Nothing. I have installed aurora store, and it isn't there either. Why is this happening? and YES. my device is certified.

### ISSUE THREAD

**Issue by Musicman-22** [waydroid/waydroid#806]
**Describe the bug**

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**Comment by novhy** [comment]
download your stock rom system img and vendor
or download any device that spec is like your pc/laptop

copy all /system/etc/permission/*.xml /vendor/etc/permission/*.xml to waydroid (except vendor xml like qcom,mtk etc, just android and google xml files)

then playstore will show all supported app by rom your downloaded

**Comment by ayasa520** [comment]
You need to install libhoudini or libndk first.  https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation
![image](https://user-images.githubusercontent.com/55699692/226159498-a101f5e7-7c14-42c8-9211-a2bc00575681.png)
![image](https://user-images.githubusercontent.com/55699692/226159515-6cf6d2b5-b9c9-4b7a-8700-75e83cb1c7b7.png)

**Comment by ayasa520** [comment]
You need to install libhoudini or libndk first. https://github.com/casualsnek/waydroid_script#install-libhoudini-arm-translation
![image](https://user-images.githubusercontent.com/55699692/226159887-a2bfc43a-5a24-42be-bd19-2c7bef558554.png)
