### ISSUE TITLE
"Audio server died"

### ISSUE THREAD

**Issue by Lolmc0587** [waydroid/waydroid#829]
**Describe the bug**
i play some video on youtube after long time, the logcat say: "Audio server died". All application stop responding.

**Screenshots**
N/A

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.0
 - Waydroid Images Version: MAINLINE-20230318

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10 x64
 - GPU: Intel® HD Graphics 5500
 - Kernel version: 5.19.0-38-generic
 - Host mesa version: Mesa 22.2.5
 - Desktop: Gnome 43.1

**Additional context**
N/A

**Logs (please upload as file)** - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`: [waydroid.log](https://github.com/waydroid/waydroid/files/11071773/waydroid.log)
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running: [waydroid_logcat.log](https://github.com/waydroid/waydroid/files/11071833/waydroid_logcat.log)
 - Output of `dmesg`: [dmesg.txt](https://github.com/waydroid/waydroid/files/11071838/dmesg.txt)

**Comment by PhilDevProg** [comment]
This also happens in other apps like the ARD Mediathek. Mostly after you paused a video.

**Comment by Lolmc0587** [comment]
Yes. That really annoying.

**Comment by Lolmc0587** [comment]
that happened in all app that play video

**Comment by Lolmc0587** [comment]
does anyone know how to fix this?

**Comment by Lolmc0587** [comment]
Thanks. I will try it

**Comment by Lolmc0587** [comment]
problem solved

**Comment by rexendevar** [comment]
this solution used to work but now it doesn't
