### ISSUE TITLE
Failed to start Clipboard manager service

### ISSUE THREAD

**Issue by jaro3** [waydroid/waydroid#83]
On latest Arch linux it doesn't start with error message:

Failed to start Clipboard manager service, check logs

(nothing more in the log)

**Comment by Richardsause** [comment]
Same happens with me, I'm on kde

**Comment by x1unix** [comment]
Same stuff. Using ArchLinux with linux-zen and GNOME 40

**Comment by profMastermind** [comment]
try:
$pip3 install pyclip

**Comment by x1unix** [comment]
@profMastermind installed. Now `sudo waydroid container start` and `session start` just hangs (nothing happens).

**Comment by rez-commons** [comment]
Same issue, and same results as @x1unix

Running Mobian 11 on the Pinephone, Kernel: 5.10-sunxi64

**Comment by JumperLuko** [comment]
In Manjaro

I was with error

I used the command: `pip3 install pyclip`

And when copying and pasting on Android it doesn't work, when trying to give the following errors in the terminal

```
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
Exception ignored in: 'gbinder.local_transact_callback'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
Exception ignored in: 'gbinder.local_transact_callback'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
```

**Comment by BlurryFlurry** [comment]
> In Manjaro
> 
> I was with error
> 
> I used the command: `pip3 install pyclip`
> 
> And when copying and pasting on Android it doesn't work, when trying to give the following errors in the terminal
> 
> ```
> Traceback (most recent call last):
>   File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
>   File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
>     local_response.append_string16(ret)
>   File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
>   File "gbinder.pyx", line 9, in gbinder.ensure_binary
> TypeError: not expecting type '<class 'NoneType'>'
> Exception ignored in: 'gbinder.local_transact_callback'
> Traceback (most recent call last):
>   File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
>   File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
>     local_response.append_string16(ret)
>   File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
>   File "gbinder.pyx", line 9, in gbinder.ensure_binary
> TypeError: not expecting type '<class 'NoneType'>'
> Traceback (most recent call last):
>   File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
>   File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
>     local_response.append_string16(ret)
>   File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
>   File "gbinder.pyx", line 9, in gbinder.ensure_binary
> TypeError: not expecting type '<class 'NoneType'>'
> Exception ignored in: 'gbinder.local_transact_callback'
> Traceback (most recent call last):
>   File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
>   File "/usr/lib/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
>     local_response.append_string16(ret)
>   File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
>   File "gbinder.pyx", line 9, in gbinder.ensure_binary
> TypeError: not expecting type '<class 'NoneType'>'
> ```

Same

**Comment by 530f6caa** [comment]
I had the same error as @JumperLuko. I solved it by installing xclip.

**Comment by aleasto** [comment]
`Failed to start Clipboard manager service` is not an issue, just means you won't get the shared clipboard functionality.
Missing info on the actual problem and debug logs
