### ISSUE TITLE
Waydroid Debian 12 repo issue

### ISSUE THREAD

**Issue by Sensei1304** [waydroid/waydroid#833]
Duplicates #832, sorry for that report, but I believe issues still persists

**Describe the bug**
apt fails on https://repo.waydro.id/erfan/bookworm/waydroid_1.4.0_all.deb, 
apt update doesn't help

**Screenshots**

```
Unable to download https://repo.waydro.id/erfan/bookworm/waydroid_1.4.0_all.deb  File has unexpected size (220392 != 220380). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:e18c191051a3054692a188ee5d313414e38210809e05158a8c00880365beed5a
    - SHA1:e1eff32dd8af944fa3fd28b240bda9374dbc6424 [weak]
    - MD5Sum:27dacf1e48274856fbfbf0954c4c67a6 [weak]
    - Filesize:220380 [weak]
```

**General information:**
 - I'm using waydroid 1.4.0
 - Image GAPPS, system_datetime = 1679071370, vendor_datetime = 1679093549

**Smartphone:**
 - Device: Pinephone Pro Explorer edition
 - OS: latest Mobian bookworm
 - Mainline
 - Kernel version: 6.1

**Comment by aleasto** [comment]
I don't know what to tell you.
```
docker run -it debian:bookworm bash -c "apt update; apt install -y curl; curl https://repo.waydro.id | bash; apt install -y waydroid"
```
works, both on amd64 and arm64 (not that it should matter, the deb is arch independent)

And https://repo.waydro.id/dists/bookworm/main/binary-all/Packages shows `Size: 220392` correctly.

**Comment by Sensei1304** [comment]
It's OK for me now
After:
1. Commenting out waydroid repo
2. Running apt update
3. Uncommenting waydroid repo
4. apt update && apt upgrade

No idea how and why it happened, but I agree it wasn't waydroid repo issue.
Thank you
