### ISSUE TITLE
Waydroid will not start on Fedora 37 KDE

### ISSUE THREAD

**Issue by compata** [waydroid/waydroid#834]
**Describe the bug**
Tried to start waydroid:
```
$ waydroid show-full-ui
[19:43:02] Starting waydroid session
^C
```
Killed after several minutes with no response.

Investigation:
```
# waydroid status
Session: RUNNING
Container: STOPPED
Vendor type: MAINLINE
Session user: dave(1000)
# systemctl status waydroid-container
 waydroid-container.service - Waydroid Container
Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disabled)
Active: active (running) since Sun 2023-03-26 19:42:45 PDT; 22min ago
Process: 31599 ExecStartPre=/usr/bin/ln -sf /dev/binderfs/binder /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/ (code=exited, status=0/SUCCESS)
Main PID: 31600 (waydroid)
Tasks: 3 (limit: 9439)
Memory: 16.4M
CPU: 1.001s
CGroup: /system.slice/waydroid-container.service
# waydroid container start
ERROR: WayDroid container service is already running
```
Referencing the answer to a previous report, I do not have apparmor or nfcd installed or running.
```
# ls /etc/apparmor*
/usr/bin/ls: cannot access '/etc/apparmor*': No such file or directory
# dnf provides */nfcd.service
Last metadata expiration check: 3:19:34 ago on Sun 26 Mar 2023 04:50:12 PM PDT.
Error: No matches found.
```

 - Waydroid tools Version [e.g. 1.1.0]
   waydroid-selinux-1.4.0-1.fc37.noarch
   waydroid-1.4.0-1.fc37.noarch

 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`
   system_datetime = 1679120172
   vendor_datetime = 1679130864

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
    Fedora 37 x86_64
 - GPU: [e.g. AMD Radeon™ RX 5700]
    none
 - Kernel version: [e.g. Generic 5.4.x]
    6.2.7-200.fc37.x86_64

 - Host mesa version: [e.g. mesa 2.2]
    not installed
 - Desktop: [e.g. Gnome 40.x.x]
    KDE plasma version 5.27.3

**Smartphone (please complete the following information):**
 not relevant

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
    not present
 - Log file, located at `/var/lib/waydroid/waydroid.log`
[waydroid.log](https://github.com/waydroid/waydroid/files/11093529/waydroid.log)

 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
    waydroid won't start - subject of this report
 - Output of `dmesg`
[dmesg.txt](https://github.com/waydroid/waydroid/files/11093546/dmesg.txt)

**Comment by compata** [comment]
Details omitted previously:
```
Operating System: Fedora Linux 37
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.7-200.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 2 × Intel® Core™2 Duo CPU E6550 @ 2.33GHz
Memory: 7.7 GiB of RAM
Graphics Processor: i915
Manufacturer: Hewlett-Packard
Product Name: HP Compaq dc7800 Small Form Factor
```

**Comment by aleasto** [comment]
> Prop file, located at /var/lib/waydroid/waydroid.prop. In case that doesn't exist, use /var/lib/waydroid/waydroid_base.prop instead
not present

Given your dmesg, that can't possibly be the case.

And the dmesg is cut.
