### ISSUE TITLE
Waydroid not showing in the  Application Menu

### ISSUE THREAD

**Issue by pakosaan** [waydroid/waydroid#836]
**Description**
Waydroid is not appearing in the application menu, even though the .desktop file is present in the .local/share/application/Waydroid.desktop directory. However, when I rename the file from Waydroid.desktop to waydroid.desktop, it appears in the menu. After restarting or shutting down the computer, a new Waydroid.desktop file is generated, resulting in two .desktop files. Despite this, Waydroid still doesn't appear in the application menu, and I have to repeat the renaming process to get it to show up again. This results in a never-ending cycle. Can anyone help me with this issue?

**Desktop:**
 - OS: Fedora 37
 - Kernel version: [6.2.8-200.fc37.x86_64]
 - Desktop: [KDE 5.27.3]

**Comment by aleasto** [comment]
When using `persist.waydroid.multi_windows` the Waydroid launcher gets hidden because "multi windows" means you launch individual applications directly from the desktop instead of the android homescreen.

**Comment by nwkyz** [comment]
May need to edit `~/.local/share/applications/Waydroid.desktop` and change `NoDisplay` to `false` manually after disabled `persist.waydroid.multi_windows`. Waydroid seems doesn't automatically appears in the applications menu after disabled the option. Waydroid 16.1, Zorin OS16.2 (Ubuntu 20.04) on Wayland.
