### ISSUE TITLE
Some waydroid commands fails when run as normal user just because of logging

### ISSUE THREAD

**Issue by sigmaSd** [waydroid/waydroid#84]
This line actually requires root https://github.com/waydroid/waydroid/blob/bullseye/tools/__init__.py#L44 because it appends to the log file.
This makes commands like waydroid session start or show-full-ui fail when run as normal user just because of logging. (commenting that like makes them work normally)

**Comment by sigmaSd** [comment]
The issue boils down to `/var/lib/waydroid/waydroid.log` becomes inaccessible to normal user somehow.

steps to reproduce:
- `sudo systemctl stop waydroid-container`
- `rm /var/lib/waydroid/waydroid.log`
- `sudo systemctl start waydroid-container`
- `stat /var/lib/waydroid/waydroid.log` -> 0o666
- Run `waydroid session start` for a couple of seconds then ctrlc
-  `stat /var/lib/waydroid/waydroid.log` -> 0o700

**Comment by sigmaSd** [comment]
Current workaround 
`sudo chown urusername /var/lib/waydroid/waydroid.log`

**Comment by JordanViknar** [comment]
I can confirm I also encountered this problem. It started happening after doing "waydroid upgrade" and updating waydroid using the AUR. I suspect the problem is related to either the newest waydroid update on the AUR or the "waydroid upgrade" command.

**Comment by sigmaSd** [comment]
Fixed in https://github.com/waydroid/waydroid/commit/9cec7cac9481750a4955c5bbc6c68a218d4635db

**Comment by DaniyalAhmadSE** [comment]
I'm facing the same issue, now i can only run waydroid commands as `sudo`

**Comment by natesworks** [comment]
this was not fixed (workaround works)

**Comment by natesworks** [comment]
```
natesworks@pi:~ $ waydroid log
Run 'waydroid log' for details.
```

works as root
