### ISSUE TITLE
Waydroid window doesn't always appear on Librem 5

### ISSUE THREAD

**Issue by BurnyBoi** [waydroid/waydroid#840]
**Describe the bug**
Sometimes when starting a Waydroid session on Librem 5, the Waydroid window will never appear even though `waydroid status` says it should be started:

```
purism@pureos:~/Downloads$ waydroid status
Session:	RUNNING
Container:	RUNNING
Vendor type:	MAINLINE
Session user:	purism(1000)
Wayland display:	wayland-0

```

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`
system_datetime = 1680361501
vendor_datetime = 1680367788

**Smartphone (please complete the following information):**
 - Device: Purism Librem 5
 - OS: PureOS 10 Byzantium 
 - Mainline
 - Kernel version: Linux 6.1.0-1-librem5 aarch64

**Additional context**
When I experience this issue, I can usually fix it by running `waydroid session stop`, waiting for a while, then rebooting the phone. If I do this, starting waydroid again using the same method (tapping the icon on the homescreen) will get the Waydroid window to load as expected. Attached logs are from an instance where I attempted to start waydroid then waited for several minutes as it never appeared.

**Logs (please upload as file)**
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/11133028/waydroid.prop.txt)
[waydroid.log.txt](https://github.com/waydroid/waydroid/files/11133029/waydroid.log.txt)
[waydroid_logcat.log.txt](https://github.com/waydroid/waydroid/files/11133031/waydroid_logcat.log.txt)
[dmesg.log.txt](https://github.com/waydroid/waydroid/files/11133032/dmesg.log.txt)

**Comment by aleasto** [comment]
I'm surprised you say it works sometimes?
Anyhow, fixed in https://github.com/waydroid/android_hardware_waydroid/commit/3441ad339444472dcc3611a315ceb367a3292a5a
