### ISSUE TITLE
Anbox issues with manual installation from choff/anbox-modules

### ISSUE THREAD

**Issue by acheong08** [waydroid/waydroid#849]
Installing anbox from https://github.com/choff/anbox-modules creates /dev/binder but no /dev/anbox-binder.

`sudo ln -s /dev/binder /dev/anbox-binder` creates other issues so I assume they're not compatible. How do i fix this?

```
OS: Ubuntu 22.10 x86_64 
Host: Laptop AB 
Kernel: 6.2.8-060208-generic 
Uptime: 2 hours, 3 mins 
Packages: 4060 (dpkg), 47 (nix-default), 17 (flatpak), 25 (snap) 
Shell: zsh 5.9 
Resolution: 2256x1504 
DE: GNOME 43.1 
WM: Mutter 
WM Theme: WhiteSur-Dark 
Theme: WhiteSur-Dark [GTK2/3] 
Icons: WhiteSur-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 4459MiB / 15769MiB 
```

**Comment by aleasto** [comment]
`sudo waydroid upgrade --offline`

**Comment by acheong08** [comment]
I ran this and it still looks for `/dev/anbox-binder`. 
```
[gbinder] Service manager /dev/anbox-binder has appeared
[gbinder] WARNING: Service manager /dev/anbox-binder has died
```

**Comment by acheong08** [comment]
It seems a bit premature to close an issue before it has been resolved

**Comment by aleasto** [comment]
The binder device names don't matter. Your issue is elsewhere

**Comment by acheong08** [comment]
> The binder device names don't matter. Your issue is elsewhere

Can you give some tips on where that might be?
