### ISSUE TITLE
Ubuntu failed to start Waydroid. WAYLAND_DISPLAY is not set, defaulting to "wayland-0"

### ISSUE THREAD

**Issue by DinhHoangDuy** [waydroid/waydroid#850]
I just install Waydroid using the [websites manual] (https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives)

I want to install Android app but I can't do it because of the Wayland Display error. I'm using Wayland that comes with Ubuntu 22.10

**Screenshots**
![image](https://user-images.githubusercontent.com/81969152/232070940-dc86dc27-8cf8-4e93-9dec-3b24b0d53759.png)

 - OS: [Ubuntu 22.10 x64]
 - GPU: [Intel UHD/ MX230]
 - CPU: [Intel i5 1035G1]
 - Desktop: [Gnome 43.1]

**Comment by FadhilRasyidin** [comment]
Your problem might be similar to mine. Try doing what I did.
- You might want to [Remove](https://docs.waydro.id/usage/install-on-desktops#reinstalling-waydroid) Waydroid first so everything else will be more convenient,
- Your Ubuntu might not be running on Wayland, and to fix that you should follow a guided walk through [here](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop),
- After that, to switch to a Wayland session, you can try logging out and then logging back in, selecting "GNOME on Wayland" or "Ubuntu on Wayland" as your session type (gear icon) in the login screen. Alternatively, you can try running the following command to start a new Wayland session: `gnome-session --session=ubuntu-wayland`. After that command you should be automatically switched to Ubuntu on Wayland in the login screen. (make sure by press on the gear icon),
- Try running `echo $WAYLAND_DISPLAY` & `echo $XDG_SESSION_TYPE` it should return as `wayland-0` & `wayland` (not `x11`) respectively,
- [Reinstall](https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives) everything on your Wayland session,
- Before running Waydroid (Clicking the program shortcut), make sure to start the container service by running `sudo systemctl enable --now waydroid-container`
- Then click on the Wayland shortcut, i think everything will be familiar to run for you after that!

Really hope this is what you're looking for.

**Comment by DinhHoangDuy** [comment]
Hơw

> Your problem might be similar to mine. Try doing what I did.
> 
> * You might want to [Remove](https://docs.waydro.id/usage/install-on-desktops#reinstalling-waydroid) Waydroid first so everything else will be more convenient,
> * Your Ubuntu might not be running on Wayland, and to fix that you should follow a guided walk through [here](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop),
> * After that, to switch to a Wayland session, you can try logging out and then logging back in, selecting "GNOME on Wayland" or "Ubuntu on Wayland" as your session type (gear icon) in the login screen. Alternatively, you can try running the following command to start a new Wayland session: `gnome-session --session=ubuntu-wayland`. After that command you should be automatically switched to Ubuntu on Wayland in the login screen. (make sure by press on the gear icon),
> * Try running `echo $WAYLAND_DISPLAY` & `echo $XDG_SESSION_TYPE` it should return as `wayland-0` & `wayland` (not `x11`) respectively,
> * [Reinstall](https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives) everything on your Wayland session,
> * Before running Waydroid (Clicking the program shortcut), make sure to start the container service by running `sudo systemctl enable --now waydroid-container`
> * Then click on the Wayland shortcut, i think everything will be familiar to run for you after that!
> 
> Really hope this is what you're looking for.

Holy **** it just work :)). Click the Waydroid app and it just open the whole "Tablet" UI :+1: 
But now I don't know how to connect Waydroid to Internet. The Wifi button keeps turn itself off
How can I fix it?

**Comment by FadhilRasyidin** [comment]
as long as your Ubuntu is connected to the internet i think it will be able to access the internet no?

**Comment by DinhHoangDuy** [comment]
> as long as your Ubuntu is connected to the internet i think it will be able to access the internet no?

At first Waydroid didn't connect to internet. But that's fine now, I just fix it with this [Reddit Post](https://www.reddit.com/r/waydroid/comments/z57rx7/help_i_cant_connect_waydroid_to_internet/)

Thanks for your help. I'm appreciated

**Comment by miguelrosa81** [comment]
So I have an issue! I use Barrier, that not support wayland and so I've turned off the "wayland" to use Barrier. Any way to use waydroid without wayland?
