### ISSUE TITLE
VMWare doesn't receive Window Key since Waydroid installed

### ISSUE THREAD

**Issue by DinhHoangDuy** [waydroid/waydroid#851]
Video: 

https://user-images.githubusercontent.com/81969152/232325996-e6e093e7-0436-48ab-b0ca-3966ebfe1078.mp4

This is kinda weid, I don't know this is VMWare or Waydroid problem. But yeah, since the time I installed Waydroid, my VMWare app does not receive the Window key anymore.
Software: VMware Workstation pro 17.

**Comment by aleasto** [comment]
> since Waydroid installed

No, since you switched your Desktop session to Wayland
