### ISSUE TITLE
Container is running, but waydroid saiys container is stopped

### ISSUE THREAD

**Issue by MtFBella109** [waydroid/waydroid#852]
Bug:
I installed waydroid an downloaded the GAPPS Image, I tried to verify the Google Account, but everytime I tried to go in the waydroid shell I got: Container ist stopped. Then I tried systemctl start waydroid, but it said Waydroid is running already, then I tried: waydroid container start, but it said: „Container is running already“. Note: maybe the commands and the output of the commands are not exactly how you write or get it from the the Terminal, but I didn‘t lookup in my PC, in the time I write this.

Desktop:
 - OS: First Fedora 37 now Fedora 38
 - GPU: NVIDIA GeForce GTX 960
 - Kernel version: 6.2
 - Desktop: Gnome.44

**Comment by aleasto** [comment]
launch waydroid

**Comment by upseguest** [comment]
> launch waydroid

It doesnt work
