### ISSUE TITLE
Cant install from repo.  Error saying expected Size is wrong.  

### ISSUE THREAD

**Issue by TxTechnician** [waydroid/waydroid#856]
**Describe the bug**
Unable to install.  Getting the following error:
```
sudo apt install waydroid -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  kitty-doc kitty-terminfo libjs-sphinxdoc
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  waydroid
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 221 kB of archives.
After this operation, 445 kB of additional disk space will be used.
Get:1 https://repo.waydro.id ubuntu-devel/main all waydroid all 1.4.0 [221 kB]
Err:1 https://repo.waydro.id ubuntu-devel/main all waydroid all 1.4.0
  File has unexpected size (221128 != 220736). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:a3e96b2fefe8b11f1ef6487cc6515b7b392fb35912ffe7328370b41f7ca31129
   - SHA1:89f4a9ecc87aa7823618eface42f3c2d1e5b2ccb [weak]
   - MD5Sum:79f650b51fbfbcf5493141ceec2223e2 [weak]
   - Filesize:220736 [weak]
E: Failed to fetch https://repo.waydro.id/erfan/ubuntu-devel/waydroid_1.4.0_all.deb  File has unexpected size (221128 != 220736). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:a3e96b2fefe8b11f1ef6487cc6515b7b392fb35912ffe7328370b41f7ca31129
    - SHA1:89f4a9ecc87aa7823618eface42f3c2d1e5b2ccb [weak]
    - MD5Sum:79f650b51fbfbcf5493141ceec2223e2 [weak]
    - Filesize:220736 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version [e.g. 1.1.0]
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.10
 - GPU: [e.g. AMD Radeon™ RX 5700]
 - Kernel version: [e.g. Generic 5.4.x]
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: [e.g. Gnome 40.x.x]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**Comment by aleasto** [comment]
Fixed, run `apt update`
