### ISSUE TITLE
Replace System.img in Waydroid

### ISSUE THREAD

**Issue by muhammadbahaa2001** [waydroid/waydroid#863]
**Is your feature request related to a problem? Please describe.**
Is there a way to replace System.img in Waydroid?

**Describe the solution you'd like**
I know Waydroid runs with Lineage 18.1 System.img based-on Android 13, for example I want to replace it Android 13.

**Additional context**
What about Android Studio x86 System Images? Can it work if we can simply swap/replace System.img?

**Comment by aleasto** [comment]
No
