### ISSUE TITLE
`sys.use_memfd=true` should be set if ashmem is unavailable but memfd is.

### ISSUE THREAD

**Issue by rokejulianlockhart** [waydroid/waydroid#871]
**Describe the solution you'd like**
Per https://github.com/waydroid/waydroid/issues/395#issuecomment-1151757646, `sys.use_memfd=true` should be set based upon whether WayDroid can ascertain ashmem/memfd support.

**Describe alternatives you've considered**
Use memfd instead of ashmem.

**Additional context**
Why should the user need to deal with this?

**Comment by aleasto** [comment]
it is

**Comment by RokeJulianLockhart** [comment]
> https://github.com/waydroid/waydroid/issues/871#issuecomment-1528893918

Perhaps this should have been a https://github.com/waydroid/waydroid/discussions/new?category=q-a first. Apologies.
