### ISSUE TITLE
https://repo.waydro.id/ broken: 504 Gateway Time-out

### ISSUE THREAD

**Issue by Hemie143** [waydroid/waydroid#880]
https://repo.waydro.id/ broken: 504 Gateway Time-out. It's not possible to add the repo for Ubuntu/Debian for the moment.
curl on the URL fails. A web browser shows HTTP 504 error. 

 - OS: Ubuntu 20.04 x64]
 - GPU: GT1060
 - Kernel version: 5.15.0-70-generic
 - Host mesa version: -
 - Desktop: bash

curl https://repo.waydro.id | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0      2      0  0:01:23  0:01:00  0:00:23    42
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>504 Gateway Time-out</title></head>

**Comment by Hemie143** [comment]
It's solved now ?

**Comment by U-siro** [comment]
No It isnt.
![image](https://user-images.githubusercontent.com/3070987/235931178-c286297f-2d55-4082-9cbf-ace51563dd97.png)
