### ISSUE TITLE
WayDroid won't start on Fedora XFCE

### ISSUE THREAD

**Issue by VenomousSteam81** [waydroid/waydroid#888]
**Describe the bug**
Trying to install an app reports `WayDroid session is stopped`.I tried the `sudo systemctl enable --now waydroid-container`, which did nothing except ask for my password. I then try `waydroid init`, which tells me its already initialized. I then ran `waydroid app install Downloads/app-debug.apk` which tells me that it isn't initialized.

**Screenshots**
https://imgur.com/9xmMVnV.png

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version 
`system_datetime = 1682127058`
`vendor_datetime = 1682162466`

**Desktop (please complete the following information):**
 - OS: Fedora XFCE 38 64-bit
 - GPU: Mesa Intel UHD Graphics 600 (3.7GB)
 - Kernel version: Generic 6.2.13
 - Host mesa version: N/A
 - Desktop: XFCE 4.18

**Additional context**
None

**Logs (please upload as file)**
Prop file output:
```
cat /var/lib/waydroid/waydroid_base.prop 
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
```
[waydroid log file](https://gist.github.com/VenomousSteam81/c765b2b2af925cccfe146bdaa08d2e75#file-waydroid-log) (CONTAINS LOGS FROM PREVIOUS RUN WHICH DIDN'T WORK EITHER)

`waydroid logcat` output:
```
[12:23:14] WayDroid container is STOPPED
```
`dmesg` does not give any output for waydroid

**Comment by cniw** [comment]
> WayDroid session is stopped

before installing android apps make sure that waydroid session is running, you can check the status with this command `waydroid status`.
if it's not running, run this command `waydroid session start`, `waydroid show-full-ui` or just click the waydroid icon launcher.
starting waydroid container is not enough.

**Comment by cniw** [comment]
> Desktop: XFCE 4.18

xfce currently only support x11, meanwhile waydroid is a wayland app that need wayland compositor.
so if you really want to run waydroid on xfce you should install a wayland compositor and run it in nested mode, recommended `weston` it's lightweight and easy to use.

for the others wayland compositor see https://wiki.archlinux.org/title/wayland#Compositors

**Comment by dginovker** [comment]
Fwiw here's a good tutorial on running Waydroid from XFCE on Arch: https://forum.manjaro.org/t/how-to-install-run-waydroid-on-xfce-or-other-non-wayland-desktops/152925
