### ISSUE TITLE
Gbinder error. Can't run Waydroid on Manjaro x86 system.

### ISSUE THREAD

**Issue by MatveyM11** [waydroid/waydroid#89]
OS: Manjaro Linux x86_64 
                                                               
                                                                 Kernel: 5.14.2-1                                                                                  
                                                                 DE: Plasma 5.22.5 
                                                                 WM: KWin
                                                                 CPU: Intel i7-4790 
                                                                 GPU: NVIDIA GeForce GTX 970 
 
 
 
 I had installed both waydroid and waydroid image from the aur,  gbinder is also was installed, but any command that's related to the waydroid is giving me a gbinder error.
 
 waydroid
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 9, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 7, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'

**Comment by Id2ndR** [comment]
It works for me on Manjaro x86_64 with kernel 5.10.63-1-MANJARO. The following packages are installed:
```
$ pacman -Q | grep -i gbinder
libgbinder 1.1.11-1
python-gbinder 1.0.0-1
```

**Comment by Quackdoc** [comment]
is this still an issue?

**Comment by Vilhelm-Ian** [comment]
I just got the issue

**Comment by Quackdoc** [comment]
try to re-install libgbinder and pythong-gbinder. preferably from the aur.

**Comment by harmtemolder** [comment]
Same issue, even after having reinstalled `libgbinder` and `python-gbinder` from the AUR (using `yay`):

```
$ pacman -Q | grep -i gbinder
libgbinder 1.1.16-1
python-gbinder 1.0.0-3
```

```
$ uname -rm
5.15.19-1-MANJARO x86_64
```

And `python -c 'help("modules")'` doesn't show anything resembling `gbinder`.

Has `yay` installed `python-gbinder` outside of my `PATH` somewhere?

**Comment by Misaka13514** [comment]
try to clean build and re-install python-gbinder.

**Comment by harmtemolder** [comment]
Clean-built both `python-gbinder` and `waydroid`, but same thing:

```
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 9, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 7, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'
```

**Comment by Misaka13514** [comment]
For me it worked fine after rebuilding, but it might be different for you, you can try to check if the python version matches.

```
$ pacman -Ql python-gbinder
python-gbinder /usr/
python-gbinder /usr/lib/
python-gbinder /usr/lib/python3.10/
python-gbinder /usr/lib/python3.10/site-packages/
python-gbinder /usr/lib/python3.10/site-packages/gbinder.cpython-310-x86_64-linux-gnu.so
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.0.0-py3.10.egg-info
```

**Comment by aleasto** [comment]
We are not responsible for packaging for Manjaro.
Anyways i can assume your issue was resolved
