### ISSUE TITLE
Fedora Silverblue: urlopen error [Errno 13] Permission denied

### ISSUE THREAD

**Issue by plata** [waydroid/waydroid#891]
**Describe the bug**
As described in https://www.reddit.com/r/Fedora/comments/136lgp8/waydroid_on_fedora_silverblue/, Waydroid should work on Fedora Silverblue. However, the initial download via GUI fails.

When trying manually, `waydroid init` fails with "Failed to get system OTA channel". Apparently, it doesn't use the default as described in `--help`. Using `-c` and `-v` solves this issue.

**General information:**
 - Waydroid 1.4.1

**Desktop:**
 - OS: Fedora Silverblue (Kinoite) 38

**Comment by cniw** [comment]
on Fedora, user need to write the system and vendor ota url explicitly & manually
- VANILLA image
`sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor` (default)
`sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor -s VANILLA`
- GAPPS image
`sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor -s GAPPS`

**Comment by plata** [comment]
Just out of curiosity: Why is this the case only on Fedora?

The `--help`  should mention it.

**Comment by cniw** [comment]
> Just out of curiosity: Why is this the case only on Fedora?

afaik because of fedora legal/license rules
maybe @aleasto can explain it better since he is the waydroid fedora package maintainer

> The `--help` should mention it.

yea, i think we should mention it

**Comment by plata** [comment]
Ok, anyways even if I do the init manually, it doesn't start:
```
Failed to add service waydroidusermonitor
Failed to add service waydroidclipboard
```
and CPU 100% but nothing happens.

**Comment by cniw** [comment]
> Failed to add service waydroidusermonitor
> Failed to add service waydroidclipboard

can you check the logs with `waydroid log` and `sudo waydroid logcat` or maybe restart your pc

**Comment by plata** [comment]
It shows a lot of
```
Failed to add presence handler: None
```

**Comment by cniw** [comment]
> `Failed to add presence handler: None`

still have no clue :thinking: , do you see the other from this?

**Comment by plata** [comment]
There's
```
conf.c run_buffer: 321 Script exited with status 126
start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
```

**Comment by fsobolev** [comment]
I have the same problem on Fedora Silverblue 38 (custom image based on [ublue](https://github.com/ublue-os/main)) when starting waydroid container with systemd. As was suggested, init was done with the command: `sudo waydroid init -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor`

* `journalctl -u waydroid-container`:

    ```
    мая 08 08:46:56 ushanka systemd[1]: Starting waydroid-container.service - Waydroid Container...
    мая 08 08:46:57 ushanka systemd[1]: Started waydroid-container.service - Waydroid Container.
    мая 08 08:56:32 ushanka systemd[1]: Started waydroid-container.service - Waydroid Container.
    мая 08 09:05:25 ushanka dnsmasq[4014]: started, version 2.89 cachesize 150
    мая 08 09:05:25 ushanka dnsmasq[4014]: compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n IDN2 DHCP 
    DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash
    DNSSEC loop-detect inotify dumpfile
    мая 08 09:05:25 ushanka dnsmasq-dhcp[4014]: DHCP, IP range 192.168.240.2 -- 192.168.240.254, lease time 1h
    мая 08 09:05:25 ushanka dnsmasq-dhcp[4014]: DHCP, sockets bound exclusively to interface waydroid0
    мая 08 09:05:25 ushanka dnsmasq[4014]: reading /etc/resolv.conf
    мая 08 09:05:25 ushanka dnsmasq[4014]: using nameserver 127.0.0.53#53
    мая 08 09:05:25 ushanka dnsmasq[4014]: read /etc/hosts - 8 names
    мая 08 09:05:26 ushanka waydroid[729]: [09:05:26] Failed to parse android version from system.img
    мая 08 09:05:26 ushanka waydroid[729]: [09:05:26] waiting 10 seconds for container to start...
    мая 08 09:05:27 ushanka waydroid[729]: [09:05:27] Failed to add presence handler: None
    мая 08 09:05:27 ushanka waydroid[729]: [gbinder] ERROR: Can't open /dev/binder: Permission denied
    ...
    ```

    The last 2 strings repeat a lot of times.

* `waydroid session start`:
    ```
    [15:55:45] Failed to add service waydroidusermonitor: -2147483647
    [15:55:45] Failed to add service waydroidclipboard: -2147483647
    ```

* `waydroid log` (after stopping waydroid)
    ```
    ...
    (018186) [15:56:42] Failed to add presence handler: None
    (018186) [15:56:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
    (018186) [15:56:42] Failed to add presence handler: None
    RUNNING
    (018186) [15:56:42] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
    lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
    lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
    (018186) [15:56:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
    STOPPED
    (018186) [15:56:42] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
    vnic is waydroid0
    (018186) [15:56:43] % systemctl is-enabled -q nfcd
    (018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
    (018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor
    (018186) [15:56:43] % umount /var/lib/waydroid/rootfs/vendor
    (018186) [15:56:43] % umount /var/lib/waydroid/rootfs
    (018186) [15:56:43] % umount /var/lib/waydroid/rootfs
    (020575) [16:04:27] % tail -n 60 -F /var/lib/waydroid/waydroid.log
    (020575) [16:04:27] *** output passed to waydroid stdout, not to this log ***
    ```
    The first string repeats a lot of times.

* `sudo waydroid logcat`, these 2 lines were repeating while running:
    ```
    05-08 12:56:42.256    15    15 E lowmemorykiller: /proc/zoneinfo parse error
    05-08 12:56:42.256    15    15 E lowmemorykiller: Failed to get free memory!
    ```

* `waydroid show-full-ui`: `[16:19:55] Failed to get service waydroidplatform, trying again...` repeating every second

If I stop systemd service and start the container manually (`sudo waydroid container start`), it works fine.

**Comment by plata** [comment]
@fsobolev did you manage to init waydroid during the build phase of your container?

I can confirm that
```
sudo systemctl stop waydroid-container
sudo waydroid container start
```
works.

Does anybody know what's the difference when running the systemd service and why that doesn't work on Silverblue?
