### ISSUE TITLE
Failed to mount "tmpfs" 

### ISSUE THREAD

**Issue by silentdefault** [waydroid/waydroid#90]
Aloha, i saw this eror at intent to start the container, im using ubuntu 21.04:
`
	(013827) [20:53:27] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init

	(013827) [20:53:27] New background process: pid=13866, output=background
	lxc-start: waydroid: conf.c: mount_entry: 1952 No such file or directory - Failed to mount "tmpfs" on "/usr/lib/x86_64-linux-gnu/lxc/mnt_extra"
	lxc-start: waydroid: conf.c: lxc_setup: 3353 Failed to setup mount entries
	lxc-start: waydroid: start.c: do_start: 1218 Failed to setup container "waydroid"
	lxc-start: waydroid: sync.c: __sync_wait: 36 An error occurred in another process (expected sequence number 5)
	lxc-start: waydroid: start.c: __lxc_start: 1999 Failed to spawn container "waydroid"
	lxc-start: waydroid: conf.c: run_buffer: 314 Script exited with status 126
	lxc-start: waydroid: start.c: lxc_end: 958 Failed to run lxc.hook.post-stop for container "waydroid"
	lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
	lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
	(013827) [20:53:27] waiting 10 seconds for container to start...
	(013827) [20:53:28] waiting 9 seconds for container to start...
`

**Comment by sigmaSd** [comment]
You need to upgrade the android image

sudo waydroid upgrade

**Comment by silentdefault** [comment]
yeah, was upgraded to lineage-17.1-20210928... and the issue is solved.
Thanks~
