### ISSUE TITLE
Since 04-22-2023 There haven't been new waydroid images 3 weeks straight.

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#911]
Is there possibly something up with the build system? Is it under high maintenance right now?

Thanks for any answers in advance.

**Comment by erfanoabdi** [comment]
server is very broken i'm still working on it
due to exams i was slow

sorry for inconvenient

**Comment by HanoJing** [comment]
> server is very broken i'm still working on it due to exams i was slow
> 
> sorry for inconvenient

No worries, I just wanted to know, good luck fixing it! For me the latest mesa (which is in the waydroid images) is broken anyways and crashes waydroid instantly, but that's #860.
