### ISSUE TITLE
Please Just Add X11 Support

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [waydroid/waydroid#914]
Because of threads like https://old.reddit.com/r/linux_gaming/comments/zvrj9f/kde_wayland_on_nvidia_status_as_of_525_driver/?sort=new,  https://old.reddit.com/r/linux_gaming/comments/wjrsq1/the_fact_that_nvidia_still_doesnt_fully_support/?sort=new, and https://old.reddit.com/r/kde/comments/qhytjx/wacom_driverssetting_on_wayland/?sort=new,
I still get the feeling I've had since wayland was first mentioned on OSNews, that if I switched to wayland, I'll end up having to factory-reset my whole PC for how broken everything will get. Please just add X11 support. It shouldn't be shunned.

**Comment by neurodiverseEsoteric** [comment]
How does that work?

**Comment by ChrysoliteAzalea** [comment]
You need to install Weston and then run it (for example, with ```weston``` command in bash). It will run as an X11 app and will provide a socket for Wayland apps (for example, Waydroid will see the Wayland socket and will use it to display itself inside Weston).

**Comment by neurodiverseEsoteric** [comment]
Thanks, though the fact that I had to use the terminal inside the weston window to run waydroid where waydroid would notice the socket seems to have been overlooked.

**Comment by vuongtuha** [comment]
Please stop this funny idea. Why don't you just suggest ppl change the name Waydroid to Xdroid instead?
We need Wayland compositor at the backend to make Android app running "parallel" with current kernel. And by whatever way, you still use Wayland at all, or you could never let it work. 
Hope anyone explain more clear for you. This is not new thing.

**Comment by aleasto** [comment]
Implementing anything new with X11 in 2023 is just backwards.

> if I switched to wayland, I'll end up having to factory-reset my whole PC for how broken everything will get.

Your mind was twisted by too many years of Windows :wink: 

I daily drive my **nvidia** machine with KDE Wayland.

Not planned (by myself)
