### ISSUE TITLE
waydroid-extra folder not found

### ISSUE THREAD

**Issue by svta-7125** [waydroid/waydroid#917]
For using custom images, the documentation says to take system.img and vendor.img to /usr/share/waydroid-extra/images and run waydorid init -f. However, I never even had a waydroid-extra folder to begin with. Am I supposed to init first and re - init after copying the images again?

**Comment by cniw** [comment]
> However, I never even had a waydroid-extra folder to begin with.

Just make it `sudo mkdir -p /usr/share/waydroid-extra/images`

> Am I supposed to init first and re - init after copying the images again?

no, after you put both img files to that folder just do initialize `sudo waydroid init`.
the `-f` or `--force` option only needed if you already did initialized before.
