### ISSUE TITLE
Waydroid images

### ISSUE THREAD

**Issue by svta-7125** [waydroid/waydroid#922]
It's been a while since android 13 has come out, android 14 may even come out soon. However, waydroid is still using LineageOS 18.1 on android 11. 

Have you guys started working on android 12 support or LineageOS 19.1 images for waydroid? 

I have been using waydroid for upto 6 months now and have been encouraging my friends to try out waydroid for the best android experience on linux.

Thank you in advance.

**Comment by cniw** [comment]
No Android 12, next images will be Android 13 based on LineageOS 20 it's currently status as WIP (work in progress). For the source codes you can see at lineage-20 branches below:
- https://github.com/waydroid/android_vendor_waydroid/commits/lineage-20
- https://github.com/waydroid/android_hardware_waydroid/commits/lineage-20
- https://github.com/waydroid/android_device_waydroid_waydroid/commits/lineage-20

For devs who want to build and test images from those branches can follow our doc pages below:
- Building
  - https://docs.waydro.id/development/compile-waydroid-lineage-os-based-images
  - https://docs.waydro.id/development/compile-waydroid-using-android-generic-project
- Testing
  - https://docs.waydro.id/faq/using-custom-waydroid-images

There is no release schedule for it, so don't ask about it. Most Waydroid devs are just working on their free time, so please understand.

**Comment by cniw** [comment]
Luckily a month ago @SnipeXandrej share his unofficial build images on telegram, for you're guys curious can try it
- Images
  - VANILLA image https://t.me/WayDroid/143191
  - GAPPS image https://t.me/WayDroid/143203
- Screenshots
  - https://t.me/WayDroid/133422 by @aleasto (dev) at 5 Februari 2023
  - https://t.me/WayDroid/143151 by @SnipeXandrej at 26 April 2023

**Comment by svta-7125** [comment]
Thank you so much for the update! Sorry for pushing you guys, really appreciate your work. Can't wait for the stable release!
Best of luck waydroid!
