### ISSUE TITLE
chrome shows black screen

### ISSUE THREAD

**Issue by fryzha** [waydroid/waydroid#923]
**Describe the bug**
open a website with chrome, it works normally at first, and then it shows a black screen(transparent window in Multi-Window Mode). Firefox doesn't have this problem.

**Screenshots**
![1](https://github.com/waydroid/waydroid/assets/48411399/05edfb1f-1af3-416b-a69f-03a1c3350627)
![2](https://github.com/waydroid/waydroid/assets/48411399/9aca1949-38c2-4293-8105-6996bd364298)
![3](https://github.com/waydroid/waydroid/assets/48411399/63d7b0e1-205f-4862-99bc-452e6e27f057)

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version  vendor_datetime = 1682162466

**Desktop (please complete the following information):**
 - OS: fedora 6.2.15-300.fc38
 - GPU: AMD Radeon RX 6600M
 - Kernel version: 6.2.15-300
 - Host mesa version: 23.0.3
 - Desktop: GNOME 44.1

**Additional context**
use clash in tun mode on the fedora

**Logs (please upload as file)**
 - Prop file, [waydroid.prop](https://github.com/waydroid/waydroid/files/11554930/waydroid.prop.txt)
 - Log file, [waydroid.log](https://github.com/waydroid/waydroid/files/11554981/waydroid.log)
 - [waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/11555143/waydroid-logcat.txt)

**Comment by soumadeepsarkar1** [comment]
I am also facing this issue on on Ubuntu 23.04

**Comment by fryzha** [comment]
I turned off the tun mode in clash, and the problem was solved

**Comment by Joseph-DiGiovanni** [comment]
Why was this closed? this is still an issue for me

**Comment by brunofin** [comment]
also an issue for me on Fedora.

**Comment by attarchi** [comment]
I have a similar bug. Ubuntu 22.04.3

**Comment by ItsAlphaNeon** [comment]
Same issue here, how are people resolving this?

**Comment by anurag-verma-india** [comment]
I'm also facing the same issue on Ubuntu 22.04.4 LTS
