### ISSUE TITLE
gbinder /dev/anbox-binder has  appeared stall

### ISSUE THREAD

**Issue by KaziiTheAvali** [waydroid/waydroid#926]
**Describe the bug**
The bug is currently refusing to go pass Service manager /dev/andbox-binder has appeared

**Screenshots**
![image](https://github.com/waydroid/waydroid/assets/87594664/eb384286-4e33-495b-b0c5-7253335a0ff0)

**General information (please complete the following information):**
 - Waydroid tools Version (unknown please tell me how to find that
 - Waydroid Images Version: lineage-18.1-20230422-VANILLA-waydroid_x86_64-system

**Desktop (please complete the following information):**
 - OS: Garuda Linux x86_64 (aur based)
 - GPU: AMD Radeon RX 5700
 - Kernel version: 6.3.4-zen1-1-zen
 - Host mesa version: unknown (feel free to tell me how to find that)
 - Desktop: KDE Dr460nized

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**
from the log it seems to keep looping through that as i see the same parts over and over again.

**Logs (please upload as file)**
[waydroidlogcat.txt](https://github.com/waydroid/waydroid/files/11567896/waydroidlogcat.txt)

if any other info is needed please tell me how to find said info so i can get it to you and if this has happened and was fixed befor tell me where i can find it as i couldent see my issue

**Comment by aleasto** [comment]
You cannot switch from GAPPS variant to non-GAPPS variant without deleting data:
`sudo rm -rf ~/.local/share/waydroid/data`

**Comment by Jab2870** [comment]
I came here from issue #1242 . Same symptom - getting stuck at 

![image](https://github.com/user-attachments/assets/2cd1b444-2992-4c86-a3a2-dffa295c495c)

Although haven't switched from a gapps variant to non-gapps (or visa versa).  I am hesitant to delete .local/share/waydroid/data if that will mean loosing app data from the android install
