### ISSUE TITLE
Always full-screen on KDE

### ISSUE THREAD

**Issue by Yersi88** [waydroid/waydroid#931]
**Describe the bug**
The waydroid running under KDE always opens in maximized window. Both full UI and the apps open in fullscreen and they can't be resized. Example below, the full UI and calucator both open in fulls screen mode in KDE. 

**Screenshots**
![image](https://github.com/waydroid/waydroid/assets/77145281/a950e684-f0a2-43cb-99ba-d84107ca4cff)
![image](https://github.com/waydroid/waydroid/assets/77145281/dd1a04e8-f658-422c-a418-7921dae6ec39)

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version system_datetime = 1682127058 vendor_datetime = 1682162466

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - GPU: AMD ATI 16:00.0 Raphael
 - Kernel version: 6.3.5-zen1-1-zen
 - Host mesa version: [e.g. mesa 2.2]
 - Desktop: Plasma 5.27.5 

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3a]
 - OS: [e.g. Ubuntu touch OTA19]
 - Mainline or Halium [e.g. Halium 9]
 - Kernel version: [e.g. 4.14.x]

**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**Comment by emiquey** [comment]
Hi, I am discovering waydroid but facing the same issue (on Debian + Gnome). Did you solve this ?

**Comment by Damglador** [comment]
Same issue

**Comment by Damglador** [comment]
> Hi @Yersi88, I am discovering waydroid but facing the same issue (on Debian + Gnome). Did you solve this ?

https://wiki.archlinux.org/title/Waydroid#Installation section 5.1

Year later, lmao. But better later than never
