### ISSUE TITLE
App runs on other systems but not on mine

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [waydroid/waydroid#952]
**Describe the bug**
I've seen many people run Roblox by using libndk to run them and doing some [other](https://gitlab.com/TestingPlant/roblox-on-waydroid-guide/-/blob/main/README.md) steps, but for me Roblox doesn't run on my computer, Roblox just crashes.
I've tried multiple distros, Linux zen or 6.1 - 6.3 generic kernels with add-ons I've tried reinstalling it resetting my pc redoing different tutorials countless times, but I can't get it to work, so I'm 98% sure it's because my hardware somehow isn't working correctly with waydroid.

**Screenshots**
![image](https://github.com/waydroid/waydroid/assets/88291316/47aed70e-aec6-4b29-b201-10d44209c33d)
(The white box is the window closing)

![image](https://github.com/waydroid/waydroid/assets/88291316/43878283-3ea6-44b8-bf8b-547d5b20e27f)
My Specs

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.1, 1.4.0, 1.3.4
 - Waydroid Images Version: Not sure, I've beet trying multiple versions, including the newest.
 
**Desktop (please complete the following information):**
 - OS: Arch Linux, Pop!OS, Manjaro, Nobara Linux
 - GPU:  AMD Radeon™ RX 6700XT
 - Kernel version: Generic 6.1 - 6.3.7, Linux zen
 - Host mesa version: newest form the AUR and dev
 - Desktop: Gnome, KDE

**Additional context**
Crashes almost instantly sometimes loads

**Logs (please upload as file)**
[waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/11763432/waydroid-logcat.txt)
Hope thats right

**Comment by mak448a** [comment]
Have you used waydroid-script to install libhoudini/libndk? Libndk for ARM, libhoudini for intel

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Yes I've tried both, sadly both don't work.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I forgot to send my specs I think my processor may be the problem, I don't know though.
It's an AMD Ryzen 5 3600 I've had issues with it and compatibility before.

**Comment by mak448a** [comment]
Did you install GAPPS?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Yeah, I did, thanks for helping :)!

**Comment by 641i130** [comment]
Am dealing with a similar issue with a different game. It launches, but is black screen.

**Comment by YogSottot** [comment]
try this https://github.com/Slappy826/libndk-fixer

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Fixes the crashing but now it doesent load just a white screen
