### ISSUE TITLE
Cant install Waydroid (Debian/Ubuntu based)

### ISSUE THREAD

**Issue by VXEAD** [waydroid/waydroid#958]
Hi i make step by step ![image](https://github.com/waydroid/waydroid/assets/103393069/4955c4ae-e4aa-47af-932b-733b5439a7b4)
But cant install
![image](https://github.com/waydroid/waydroid/assets/103393069/3d2650a1-6754-4670-b16c-a76e2336a24e)

**Comment by aleasto** [comment]
What's your distro?
Share `/etc/os-release`

**Comment by cniw** [comment]
> > What's your distro? Share `/etc/os-release`
> 
> Trisquel OS

Please show the all output details from `cat /etc/os-release`

**Comment by VXEAD** [comment]
> > > What's your distro? Share `/etc/os-release`
> > 
> > 
> > Trisquel OS
> 
> Please show the all output details from `cat /etc/os-release`

Ver codename: aramo
Ubuntu codename: jammy

**Comment by VXEAD** [comment]
> Ver codename: aramo
> Ubuntu codename: jammy

Ver codename: aramo
Ubuntu codename: jammy

**Comment by cniw** [comment]
> Ubuntu codename: jammy
```bash
curl https://repo.waydro.id | sudo bash -s jammy
sudo apt install waydroid
```

**Comment by VXEAD** [comment]
> > Ubuntu codename: jammy
> 
> ```shell
> curl https://repo.waydro.id | sudo bash -s jammy
> sudo apt install waydroid
> ```

Thx so much!
