### ISSUE TITLE
Cant open Waydroid (Debian/Ubuntu based)

### ISSUE THREAD

**Issue by VXEAD** [waydroid/waydroid#962]
After i make install https://github.com/waydroid/waydroid/issues/958#event-9560742537
Im downloaded vanilla version. and after this i cant open Waydroid app
When im click nothing happened.
Help me

**Comment by msmalik681** [comment]
In terminal type:  echo $XDG_SESSION_TYPE

If it does not return wayland you need to use a compositor like weston.

**Comment by VXEAD** [comment]
> weston
How i can install Weston compiler? 
i dont know how i can do it
