### ISSUE TITLE
Permanent padding on the top? | Multi-Window mode | Fedora 38

### ISSUE THREAD

**Issue by Karamveer9200** [waydroid/waydroid#977]
**Describe the bug**
Window does not move further than this point in the upward direction (when not maximised), sort of like fixed padding. When maximised, no problem at all.

**Screenshots**
![Screenshot from 2023-06-26 07-41-14](https://github.com/waydroid/waydroid/assets/121487526/13461346-f589-4540-8a4a-9682ff6bdca0)

 - vendor_type = MAINLINE
 - system_datetime = 1682127058
 - vendor_datetime = 1682162466

 - OS: fedora 38
 - Device - ThinkPad t480

**Additional context**
window cannot be dragged upward any further, what's left is a strip of empty space at the top. 

**Logs 
[waydroid-prop.txt](https://github.com/waydroid/waydroid/files/11862524/waydroid-prop.txt)

**Comment by Commandcracker** [comment]
When I move the window down then I get the same padding as top, but it seams to be a bit more. @Karamveer9200 Is it the same for you ?
![Screenshot_20230626_155659](https://github.com/waydroid/waydroid/assets/49335821/1c81f5cb-887f-40bb-92a6-a3886438729c)

**Comment by Karamveer9200** [comment]
Found a temporary solution while messing, press and hold the super/windows key and then try to drag the window all-the way to the top. It solved my problem but this method is a bit glitchy.

**Comment by ayasa520** [comment]
https://github.com/casualsnek/waydroid_script#hide-status-bar

**Comment by Karamveer9200** [comment]
> https://github.com/casualsnek/waydroid_script#hide-status-bar

This solved the issue.  Thx :)
