### ISSUE TITLE
Is Rooted ADB safe in a privileged container?

### ISSUE THREAD

**Issue by ChrysoliteAzalea** [waydroid/waydroid#979]
**Is your feature request related to a problem? Please describe.**
Hello everyone! As far as I looked, Waydroid allows an unprivileged user to start a privileged Android container (and, as far as I understand, it cannot be run as an unprivileged container) by making a request to the Waydroid daemon, and then, through Developer settings, enable the "Rooted debugging" option, which allows the user to run ```adb root``` and get root access to the container. Since the container is privileged, the shell would run as an actual root and have system-wide capabilities. The impact is lessened, since the root shell is confined to the container, and its rights are limited by [restriction of capabilities](https://github.com/waydroid/waydroid/pull/504), [container-wide seccomp filter](https://github.com/waydroid/waydroid/pull/505) and [the AppArmor profile](https://github.com/waydroid/waydroid/pull/506), which, however, has not been [switched into enforce mode](https://github.com/waydroid/waydroid/pull/906)

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`
 system_datetime = 1682127058
vendor_datetime = 1682162466

**Screenshots:**
![rooted_debugging](https://github.com/waydroid/waydroid/assets/64576901/32cca5ee-4a2c-4459-835c-344e1ec21763)
![adb_run_as_root](https://github.com/waydroid/waydroid/assets/64576901/75290cb7-7e9a-4afd-9e0a-c37d262981ed)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - GPU: Intel Corporation GeminiLake [UHD Graphics 605]
 - Kernel version: 5.15, with Ubuntu patches
 - Host mesa version: 22.2.5-0ubuntu0.1~22.04.3
 - Desktop: Xfce as main, Weston to run Waydroid

**Describe the solution you'd like**
We can write a stricter AppArmor profile for ADBD, to prevent abuse.

**Describe alternatives you've considered**
We can also restrict running ADBD as root, because the root shell can also be safely accessed with ```waydroid shell``` (which is allowed for desktop root only, without creating the risk of privilege escalation).

**Additional context**

**Comment by Quackdoc** [comment]
currently waydroid should be considered insecure, I would consider this not safe. IMO the easiest solution for this would be to disable root adb since we have waydroid shell anyways, but it might be time to start thinking about tightening security anyways

**Comment by ChrysoliteAzalea** [comment]
We are tightening security through seccomp, capability restrictions, AppArmor, etc. I'm considering updating the profile for ADB in order to prevent abuse.

I'm also thinking about switching to an unprivileged container. LXD successfully runs lots of desktop things in unprivileged containers, some things are achieved through system call interception with seccomp filters.

**Comment by Quackdoc** [comment]
does seccomp interception have a notable perf impact akin to ptrace? I know it can be use as an effective alternative, but im not sure to what degree.

**Comment by ChrysoliteAzalea** [comment]
> does seccomp interception have a notable perf impact akin to ptrace? I know it can be use as an effective alternative, but im not sure to what degree.

There is [an article on LWN](https://lwn.net/Articles/899281/) about that.

P.S. I'm proposing a new AppArmor profile for ADBD in order to mitigate the problem.

**Comment by ChrysoliteAzalea** [comment]
Closing this issue as completed as [```adb root``` is disabled in Waydroid](https://github.com/waydroid/android_vendor_waydroid/pull/23).
