### ISSUE TITLE
No python-pyclips

### ISSUE THREAD

**Issue by KarandashKosmos** [waydroid/waydroid#981]
System: Debian 12

When I trying to use `apt install python-pyclip`:

E: Unable to find python-pyclip package.

When I trying `pip install pyclip`:

```
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.
```

Please help me find a way to fix `Failed to start Clipboard manager service`

P. S. Sorry for my English

**Comment by cniw** [comment]
pyclip is not available on Debian, Ubuntu, etc.
You must install it using pip but related to [PEP 668 – Marking Python base environments as "externally managed"](https://peps.python.org/pep-0668/) if you installing python packages manually, you'll see verbose messages that warn you like above.
This behavior start on Ubuntu 23.04 and Debian 12.
Do this to install

```bash
sudo pip install pyclip --break-system-packages
```

Worth to read https://fostips.com/pip-install-error-ubuntu-2304/

**Comment by ningacoding** [comment]
i have both installed on Ubuntu 23.04 x86_64
pycplip vía pip, and wl-clipboard vía apt

But clipboard not working two ways.

**Comment by dxdemetriou** [comment]
I tried this on KDE's wayland and worked both ways:
````
sudo pip install pyclip --break-system-packages
````

but is it possible to be used the python3-pyperclip which is available on Debian 12?

**Comment by Snowurm** [comment]
This works, but it is not a clean solution:
`sudo pip install pyclip --break-system-packages`

Is there a way to do this while respecting the externally-managed-environment?

**Comment by lcorbasson** [comment]
Use:
```
python3 -m venv ~/.venvs/pyclip
source ~/.venvs/pyclip/bin/activate
pip install pyclip
deactivate
mkdir "$HOME/bin"
cd "$HOME/bin"
ln -s ../.venvs/pyclip/bin/pyclip
echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"

```
and restart your session to apply changes.

**Comment by bexbasil** [comment]
This is old but if anyone is seeing this what fixed it for me was running pyclip in an isolated python environment. 

`sudo apt update
sudo apt install python3-venv
python3 -m venv ~/.venvs/waydroid
source ~/.venvs/waydroid/bin/activate
pip install pyclip
`

then run inside the created waydroid python environment:

`sudo apt install wl-clipboard
`

I also ran this command that was mentioned earlier but it didn't fix the issue until I ran the above commands: `sudo pip install pyclip --break-system-packages
`
