### ISSUE TITLE
Waydroid crashes | Namespace Gtk not available

### ISSUE THREAD

**Issue by minecrawler** [waydroid/waydroid#987]
**Describe the bug**

Upon starting Waydroid from the desktop, it does nothing (and crashes).

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4
 - Waydroid Images Version: lineage-18.1-20230422-GAPPS-waydroid_x86_64-system

**Desktop (please complete the following information):**
 - OS: Gentoo 2.13
 - GPU: llvmpipe
 - Kernel version: Gentoo Dist Bin 6.3.10
 - Host mesa version: 23.1.3
 - Desktop: KDE Plasma 5 (5.27.6)

**Additional context**

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead

```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /var/lib/waydroid/waydroid_base.prop
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ sys.use_memfd=true
   2   │ debug.stagefright.ccodec=0
   3   │ ro.hardware.gralloc=default
   4   │ ro.hardware.egl=swiftshader
   5   │ ro.hardware.camera=v4l2
   6   │ ro.opengles.version=196609
   7   │ waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
   8   │ waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
   9   │ waydroid.tools_version=1.4.0
  10   │ ro.vndk.lite=true
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

 - Log file, located at `/var/lib/waydroid/waydroid.log`

```
(047763) [16:22:46] ERROR: Namespace Gtk not available
(047763) [16:22:46] See also: <https://github.com/waydroid>
(047763) [16:22:46] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 128, in main
    actions.remote_init_client(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 270, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running

n/a

 - Output of `dmesg`

https://gist.github.com/minecrawler/b2bd974e692d43c5ee60f0595186fd33

**Comment by aleasto** [comment]
Report downstream

**Comment by minecrawler** [comment]
ok, but what does that error even mean? Is it missing a dependency? If yes, which one? Can I test a fix on my PC?
