### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by k2helix** [waydroid/waydroid#995]
**Describe the bug**
I'm trying to use a controller (dualshock 4) in Waydroid but it does not work when connected via USB nor Bluetooth after or before Waydroid is loaded. I also tried installing Magisk and the OneController module but still the same. 

**General information:**
 - Waydroid tools Version: 1.4.1
 - Waydroid Images Version, or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`: latest from https://ota.waydro.id/

**Desktop:**
 - OS: Fedora 38 x64

**Additional context:**
I use X11 so I'm running Waydroid in a Weston shell, but I have tried in a pure Wayland session and it does not work either.

**Comment by YogSottot** [comment]
```
waydroid prop set persist.waydroid.udev true
waydroid prop set persist.waydroid.uevent true
```

https://github.com/waydroid/waydroid/issues/289#issuecomment-1530761751

The controller must be connected after loading the waydroid. See link for example commands for software reconnection.

**Comment by k2helix** [comment]
Sorry for taking too long to answer.

I have just done this and the controller now works fine. Thanks!
