### ISSUE TITLE
Isn't play protect certified / CANT OPEN FORM!

### ISSUE THREAD

**Issue by VXEAD** [waydroid/waydroid#997]
Hi guys, now i can open/install Waydroid + Weston like a PRO. But i cant certified my device
https://github.com/waydroid/waydroid/issues/753
I read this guide, and now i know my id
But i cant apply it on my browser at Waydroid, cant open link idk
How i can certified now? Help me

**Comment by YogSottot** [comment]
https://docs.waydro.id/faq/google-play-certification

The link does not need to be opened in waydroid. Open it in your browser on your primary operating system
https://www.google.com/android/uncertified
