### ISSUE TITLE
Apps not installing from apks / google play store.

### ISSUE THREAD

**Issue by RaziFalah** [waydroid/waydroid#998]
Hello there, I've tried to download Tiktok on Waydroid but i could not do it using Google play store, so i downloaded the apk from Uptodown. However it did not work either even though it tried more than one version which i do not understand why. because similar apps like Instagram do work and i do have enough computing resources. 
I checked if it's a known issue with virtualization software but it turns out that apps on windows like BlueStacks and even android studio can download Tiktok. Here's some screenshots i provided:

![image](https://github.com/waydroid/waydroid/assets/92949627/d772202e-2e78-44ea-a110-eb403bdbc010)

![image](https://github.com/waydroid/waydroid/assets/92949627/3282ccfd-cf08-45cd-be60-0279d13e5625)

I would like to note that i already tired common fixes with google play and also settings such as time and date, privacy and i tried clearing caches and storage. Which none of these solutions actually worked for me.

===
I also tried to download photo editing app (Polish) And roblox game but they did not work as well.

**Comment by shuantsu** [comment]
Is your android image x86 or arm architecture?
I think some apps just run on arm architecture...

**Comment by RaziFalah** [comment]
I upgraded the image and installed the scripts @YogSottot . This worked for me thanks
