### ISSUE TITLE
Volume controle

### ISSUE THREAD

**Issue by RaziFalah** [waydroid/waydroid#999]
Hell there, i don't really know if i can adjust the sound volume or not, if i can i would like to please know how.
Otherwise it would be a good feature to add a volume controller. especially because i have maxed out the system volume and waydroid doens't seem to be affected.

**Comment by cniw** [comment]
Go to Android **Settings** => **Sound** => **Media volume** then set it maximal

![Screenshot_20230712_022927](https://github.com/waydroid/waydroid/assets/25974007/bebc76be-9eb7-411a-8b60-ab587aa494aa)

**Comment by RaziFalah** [comment]
Ok thanks, i noticed this after posting this dumb issue. sorry for wasting you time.
